### PR TITLE
Added double quotes for JSON keys

### PR DESCRIPTION
**Pull request by message**

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks, can you please squash your commits into one and update your commit summary to begin with "Docs:"?

**Comment by message** [comment]
@nzakas I'm not quite sure how to do that without loosing that pull request

**Comment by nzakas** [comment]
See http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html.

You should also take a moment to review our contribution guidelines: http://eslint.org/docs/developer-guide/contributing.html

**Comment by message** [comment]
Sorry, i'm useless

**Pull request closed without merging**
