### PR TITLE
Update docs to make `fix` param more clear in NodeJS API

### PR DESCRIPTION
**Pull request by NickHeiner**
See #6366.

### CODE REVIEW

**Comment by platinumazure** [comment]
I'd love to see a quick sentence in `executeOnFiles()` as well, just in case that's where someone is reading. What do you think?

**Comment by NickHeiner** [comment]
Yep, that makes sense to me. I've signed the CLA, but it is not yet showing up in the PR checks. Does that take some time to propagate?

**Comment by platinumazure** [comment]
Regarding jQuery CLA, I know that it's very finicky about the e-mail address (which you specified on signing the CLA). It has to exactly match the `git config user.email` value you have on your local Git. Can you confirm that they're the same?

**Comment by mysticatea** [comment]
If my memory is correct, jQuery CLA does not accept `noreply.github.com` mail address because  the mail address does not have the ability to receive mails.

**Comment by platinumazure** [comment]
Doc changes LGTM, but I would be grateful if @nzakas or @pedrottimark could take a look.

**Comment by platinumazure** [comment]
@NickHeiner Regarding jQuery CLA: Actually, seems jQuery CLA just doesn't accept e-mail addresses with that domain name, in case they need to contact you or whatnot. My apologies, but you're going to need to configure Git, GitHub, and the CLA with a different e-mail. Sorry for missing that earlier.

**Comment by NickHeiner** [comment]
Ok, I've fixed the email / CLA issue. Thanks for your help on that.

**Comment by ilyavolodin** [comment]
Thanks @NickHeiner LGTM.

**Pull request merged**
