### PR TITLE
Update: Use 'readonly' and 'writable' for globals (fixes #11359)

### LINKED ISSUE #11359: Change "readable" to "readonly" and "writeable" to "writable" in new globals configuration
**The version of ESLint you are using.**

master

**The problem you want to solve.**

#11338 merged a change that allowed globals to be specified as "writeable" or "readable". I believe "readable" doesn't accurately convey the setting. All variables present in the environment are readable, including writable variables

Also, "writeable" is misspelled. It should be spelled "writable".

**Your take on the correct solution to problem.**

1. Change "readable" to "readonly".
1. Change "writeable" to "writable".

**Are you willing to submit a pull request to implement this change?**

Yes, if no one else wants to.

### PR DESCRIPTION
**Pull request by nzakas**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

Changes globals configuration to also accept "readonly" and "writable".

**What changes did you make? (Give an overview)**

* Updated `config-ops#normalizeGlobalsConfig()` to also accept "readonly" and "writable" (the values returned from this function are unchanged).
* Updated the related tests.
* Updated documentation related to configuring globals.

**Is there anything you'd like reviewers to focus on?**

Did I miss anything?

### CODE REVIEW

**Comment by platinumazure** [comment]
Question: Should we remove the deprecated values in 6.x, 7.x, or never?

**Comment by g-plane** [comment]
IMHO, 6.x should keep deprecated but 7.x can remove them.

**Comment by not-an-aardvark** [comment]
I don't think we should remove `true` or `false` for the forseeable future -- there are too many configs that use them.

I don't mind removing `readable` and `writeable` sooner, although if we do that I think we should also rename the property from scope analysis. I don't think it's good design to have only "writeable" allowed in one place, and only "writable" allowed in another place.

**Comment by nzakas** [comment]
I wouldn't worry about removing the old values. We already have a ton of backwards-compatibility stuff in ESLint that we keep around just in case people are using them. And I definitely wouldn't remove `true` and `false`, just like we still allow 0, 1, 2 for rule configurations.

Keep in mind that there is a different audience (rule developers) who access the `eslint-scope` interface vs. people configuring ESLint for their code; there are far more of the latter. It would be nice to update `eslint-scope` at some point, but we'd probably need to do that in a back-compat way anyways.

**Pull request merged**
