### PR TITLE
Docs: fix typos,wrong path,backticks

### PR DESCRIPTION
**Pull request by molee1905**
**What issue does this pull request address?**

docs fixed

**What changes did you make? (Give an overview)**

fix typos,wrong path,backticks. 

for example: in the rule [no-undefined](http://eslint.org/docs/rules/no-undefined)

image

**Is there anything you'd like reviewers to focus on?**

no

### CODE REVIEW

**Comment by molee1905** [comment]
image
---
image
---
Could anyone tell me how can i pass the CLA Verification?

**Comment by ilyavolodin** [comment]
@kborchers could you help us with CLA again please?

**Comment by ilyavolodin** [comment]
LGTM. Thanks for PR. Waiting for CLA to be resolved before merging.

**Comment by vsemozhetbyt** [comment]
@molee1905 I recently had a problem with CLA, [maybe some tips there could help](https://github.com/eslint/eslint/pull/6641).

**Comment by nzakas** [comment]
@molee1905 you can't use your username as the name you sign the CLA with, it has to be an actual human name.

**Comment by kborchers** [comment]
Since we will be modifying the name check soon, I went ahead and added an exception to the signature and reran the check. Should be all set now and sorry for the delay.

**Comment by molee1905** [comment]
Thanks all ! 

> ### Sign Electronically
>The name and email address used to sign the CLA must match the name and email address in your git config. The author information for each commit in your Contributions will be cross-checked with this signature.

The CLA just requires the name and email mach the name and email address in one's git config, dose not require an actual human name; in my config,  the name and username both are **molee1905**, so there is no problem with the CLA's requirements.

i'am not the only one to be labeled **CLA: Error** with correct operation according to its requirement , maybe, the rule to sign the CLA successfully should be described in more detail，and it will be better to change the way of manual verification.

Hoping the change!

**Comment by ilyavolodin** [comment]
Thanks @kborchers for your help! LGTM. Thanks for PR @molee1905

**Pull request merged**
