### PR TITLE
feat(config-file): add alternative property name for config

### PR DESCRIPTION
**Pull request by GitScrum**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Add something to the core

**What changes did you make? (Give an overview)**

Add alternative property name for config in `package.json`. - `eslint`
Now you can use `eslint` in `package.json` to configure.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

**Comment by platinumazure** [comment]
@GitScrum Thanks for the pull request.

Can you please explain what problem this is solving?

**Comment by GitScrum** [comment]
@platinumazure Hi

> Can you please explain what problem this is solving?

I'm creating collector configurations and see some tacit agreement in such packages as `babel`, `ava`, `stylelint`, `eslint` all have roughly similar structure configuration `{ ...options, plugins: {...}, extends: {} }, babel { ...options, plugins: {...}, extends: {...}, presets: {...} }`. 

The naming of the packages is almost identical with the semantic logic configuration `babel-plugin-array-includes`, `babel-preset-babili` where `babel` is the package name matches the name in the configuration.

```json
"devDependencies": {
  "babel-plugin-array-includes": "^2.0.3",
  "babel-preset-babili": "0.0.9"
},
"babel": {
  "preset": [ ... ],
  "plugins": [ ... ]
}
```

Based on this understanding I want in the future to create some guidelines for choosing the package names and create Linter ))

**Comment by nzakas** [comment]
This was brought up a while ago and we decided not to make such a change.  Discussion: https://github.com/eslint/eslint/issues/2670

I don't see a good reason to revisit that decision.

**Comment by GitScrum** [comment]
What for you is good for others may be unacceptable. 
Explain why eslintConfig ? There are some reasons why you that critical ?

**Comment by nzakas** [comment]
@GitScrum all we are talking about is what the key of a JSON structure is, I'm not sure how such a decision could be considered unacceptable. I already linked to the previous discussion, but just to be clear: we've had this for a long time and there's no good reason to change it. Personal preference is not a good reason to either break existing users or introduce a second way of doing the same thing. 

I'm sorry that you disagree, however, I don't see any reason to revisit this decision. We have a lot of existing users we need to think about.

**Comment by GitScrum** [comment]
@nzakas 
> we've had this for a long time and there's no good reason to change it.

The base was provided above, as I wrote, I create a collector configuration which is based on [name-pkg]-[type/method]-[name]. But I didn't change but only provided an alternative method

> Personal preference is not a good reason 

Personal preference is when one person changes something for their inner/hidden project. In this case, we have more than one and my goal is open and described above.

> we've had this for a long time.

Do not think this argument why are you using eslintConfig and why it is critical for you.

> I'm not sure how such a decision could be considered unacceptable.

Do you think that adding alternative methods and giving in fact a single method will allow you to 
understand it ? Are you serious ?

> I'm sorry that you disagree, however, I don't see any reason to revisit this decision.

Don't be sorry, I did everything possible to improve your very best package, only your horizon is used to determine the future for this.

**Pull request closed without merging**
