### PR TITLE
Docs: Distinguish examples in rules under Node.js and CommonJS

### PR DESCRIPTION
**Pull request by pedrottimark**
A pull request for rules under **Node.js and CommonJS**

This gets us to 50% of the rules. About 7 pull requests to go. Hang in there.

What do you think about the wording of these example sentences?
* Example of **correct** code for this rule, **but** it is probably a mistake:
* Example of **incorrect** code for this rule, **but** it is probably not a mistake:
* Examples of **correct** code for the default `"err"` parameter name:
* Examples of **correct** code for a sample `"error"` parameter name:
* Examples of **incorrect** code for a sample module:

Here are the changes beyond example sentences:
* callback-return: move examples from Rule Details to Options; change capitalization in h3 from title case to sentence case
* global-require: delete period in main heading; delete json and You can enable this rule with the following syntax
* handle-callback-err: replace h3 Advanced configuration with h2 Options and h3 regular expression; move example from Rule Details to Options; replace ol and json with ul and inline code; replace error variable with error parameter
* no-mixed-requires: add allowCall incorrect code to default incorrect example; put example code for allowCall in incorrect/correct order
* no-new-require: delete As such sentence under Rule Details; add new to correct code
* no-restricted-modules: sample instead of meta-notation in json

### CODE REVIEW

**Comment by nzakas** [comment]
I think it's a bit confusing to say "correct code for this rule" and then later "correct code for a sample module". I think if the code is " for" something, it should always be for the rule. So I'd prefer "correct code for this rule with the default " err" parameter, " for example. 

Also not sure about the "but" sentences. Why are those necessary?

**Comment by pedrottimark** [comment]
**Yes**, I will update this PR according to patterns for rules do or do not have options as follows:
* Examples of incorrect/correct code for this rule with…
* Examples of incorrect/correct code for this rule

Does it make sense to see if we make other mid-course corrections in the second half before bringing the already-edited rule pages up to this standard?

**But** of course, I need to think harder and in a comment suggest some alternatives for rare examples of code under **Known Limitations**. Here is the current text in callback-return:
* Our rule does not detect this pattern, but it is likely a mistake.
* we won’t be able to detect that you’re calling the callback and so we won’t warn.
* but because of the difficulty in determining what you’re doing, this rule does not allow for this pattern.

**Comment by nzakas** [comment]
> Does it make sense to see if we make other mid-course corrections in the second half before bringing the already-edited rule pages up to this standard?

Sorry, I'm not sure what you're asking. Can you explain?

> Our rule does not detect this pattern, but it is likely a mistake.

I'd change "our" to "this" to match the rest of the docs, and maybe change "a mistake" to "incorrect" to match the other language.

**Comment by pedrottimark** [comment]
@nzakas what I meant is I will update the guidelines and start to use the “for this rule with” pattern immediately, but not go back to and make that improvement to the previously-merged rule pages until we get to the end.

The bulleted points are the baseline text that I was starting from. I will provide some alternatives ASAP.

**Comment by nzakas** [comment]
@pedrottimark ah, yeah, that sounds good. :+1:

**Comment by pedrottimark** [comment]
@nzakas Here is a way to get rid of **but** in callback-return under Known Limitations, The main changes is to leave the example code as information (ordinary gray background-color, not future red/green) and let its sentence have a different grammar pattern.

Let me know if these terms are a step in the wrong direction:

**Known Limitations**

Because it is difficult to understand the meaning of a program through static analysis, this rule has limitations:

* *false negatives* when this rule reports correct code, but the program calls the callback more than one time (which is incorrect behavior)
* *false positives* when this rule reports incorrect code, but the program calls the callback only one time (which is correct behavior)

**Passing the callback by reference**

The static analysis of this rule does not detect that the program calls the callback if it is an argument of a function (for example,  `setTimeout`).

Example of a *false negative* when this rule reports correct code:

And so on

**Comment by nzakas** [comment]
Looks awesome. :+1:

**Comment by nzakas** [comment]
I think this is ready, so merging. If there are still incremental changes to be made, we can keep making those.

**Pull request merged**
