### PR TITLE
Update: improve report location for space-infix-ops

### PR DESCRIPTION
**Pull request by golopot**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Changes an existing rule

**What changes did you make? (Give an overview)**

Make `space-infix-ops` report end location.

```js
const a = p&&q
//         ~   before
//         ~~  after

```

**Is there anything you'd like reviewers to focus on?**

No

### CODE REVIEW

**Comment by golopot** [comment]
One thing confuses me. In the docs (https://eslint.org/docs/developer-guide/working-with-rules#working-with-rules) the location column is said to be 0-based, but in test cases the location column is 1-based. What's wrong?

**Comment by kaicataldo** [comment]
@golopot I had to look this over myself, but it looks like when it's reported in the rule it's expected to be 0-based, but the error in the results is 1-based (see [here](https://github.com/eslint/eslint/blob/master/lib/linter/report-translator.js#L203)). Maybe someone on the team who has more context can speak to why this works that way.

**Comment by golopot** [comment]
I guess one reason context.reports expects 0-based column is that it allows passing a token location with `context.report({loc: someToken.loc})`, and that token columns are 0-based.

And one reason that problems.column is 1-based is that it is a more human friendly format, for example most editors display 1-based columns.

**Comment by kaicataldo** [comment]
Given that we have a champion and three approvals from the team, I'm marking this as accepted.

**Pull request merged**
