### PR TITLE
Add 'globalThis' to the list of es2020 globals (#12670)

### PR DESCRIPTION
**Pull request by Standard8**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ X ] Other, please explain: Adding `globalThis` to the list of environment variables

**What changes did you make? (Give an overview)** Added `globalThis` to the list of environment variables.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you for your contribution!

To make complete the support of `globalThis`, we have to update some rules as well. The rules that check `window.*` should check `globalThis.*` as well. The following rules are such kind of rules:

- `no-alert`
- `no-eval`
- `no-implied-eval`
- `no-misleading-character-class`
- `no-obj-call`
- `prefer-exponentiation-operator`
- `prefer-named-capture-group`
- `prefer-object-spread`
- `prefer-regex-literals`
- `require-unicode-regexp`

(Just a result of quick search. @eslint/eslint-team please add other rules if exist.)

Would you mind updating those rules?

**Comment by Standard8** [comment]
Unfortunately I'm not going to have any time soon for those rules - I've still got another PR I'm meant to be doing for you as well (I though this one was "simple", but obviously not quite).

**Comment by kaicataldo** [comment]
@Standard8 Given that it doesn't sound like you'll have time to complete this change, do you want to close this PR?

**Comment by Standard8** [comment]
> @Standard8 Given that it doesn't sound like you'll have time to complete this change, do you want to close this PR?

I can do, I just wasn't sure if it was something you'd take in bits.

**Pull request closed without merging**
