### PR TITLE
New: arrow-body-style rule (fixes #4109)

### LINKED ISSUE #4109: Rule Proposal: `arrow-block-style`
This rule is a styling rule for "non block" v.s. "single return block".

There is a trap in arrow function that returns an object.

```js
let foo = () => {};
```

This `{}` is a block, not an empty object.
This should be replaced with:

```js
let foo = () => ({});
// or
let foo = () => { return {}; };
// or
let foo = () => undefined;
// or
let foo = () => { /* do nothing */ };
```

This rule has an option.

- `"as-needed"` (default) - If it's possible, this suggests a use of expression without a block.
- `"always"` - This enforces using a block. 

----

```js
{
    "arrow-block-style": [2, "as-needed"]
}
```

**Valid**

```js
// OK, this is not a block.
let foo = () => 0;

// OK, this cannot replace with non-block (without a comma-sequence).
let foo = (retv, name) => {
    retv[name] = true;
    return retv;
};

// OK, this is considered as having some side effects, so the block is proper.
let foo = () => { bar(); };

// OK, it's explicit functions that does nothing.
// This behavior is the same as http://eslint.org/docs/rules/no-empty
let foo = () => { /* do nothing */ };
let foo = () => {
    // do nothing.
};
```

**Invalid**

```js
// This can be replaced with `() => 0` simply.
let foo = () => {
    return 0;
};

// This `{}` is a block.
// it should be fixed to `() => ({})` or `() => undefined` or `() => { /* do nothing */ }`.
let foo = () => {};
```

----

```js
{
    "arrow-block-style": [2, "always"]
}
```

**Valid**

```js
let foo = () => {
    return 0;
};
let foo = (retv, name) => {
    retv[name] = true;
    return retv;
};
```

**Invalid**

```js
let foo = () => 0;
```

----

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27309866-rule-proposal-arrow-block-style?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by mysticatea** [comment]
LGTM, thank you @alberto !

**Comment by michaelficarra** [comment]
Didn't you see https://github.com/eslint/eslint/issues/4109#issuecomment-148465552?

**Comment by alberto** [comment]
@michaelficarra I'm not sure what you mean. I didn't include the other patterns I mentioned there.

**Comment by michaelficarra** [comment]
Sorry, I thought that comment was referring to the whole rule.

**Comment by ilyavolodin** [comment]
LGTM. Going to hold off on merging in case we need another patch release.

**Comment by alberto** [comment]
Great, thanks!

**Comment by nzakas** [comment]
Should this be `arrow-body-style`? That seems more specific to what this rule does

**Comment by alberto** [comment]
Yeah, I like it better. @mysticatea?

**Comment by mysticatea** [comment]
Yes, I like too.

**Comment by nzakas** [comment]
This looks good to go. We're going to do one more patch release, then I think we can merge this.

**Comment by alberto** [comment]
@nzakas just a reminder that this one is ready

**Pull request merged**
