### PR TITLE
docs: fix link to npm package

### PR DESCRIPTION
**Pull request by Abdullah0sama**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
fix link to `@typescript-eslint/parser`

### CODE REVIEW

**Review by bmish — APPROVED** [review]
Thanks!

**Review by nzakas — APPROVED** [review]
LGTM. Thanks.

**Comment by nzakas** [comment]
@bmish if you approve a PR and don’t merge it, please be sure to explain why.

**Comment by bmish** [comment]
@nzakas was about to merge it after CI finished but then I saw you were on it already.

**Pull request merged**
