### PR TITLE
Add a test case which fails for autofixing `prefer-const`

### PR DESCRIPTION
**Pull request by SimenB**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

Wasn't able to find existing issue for this, sorry if it's a dupe.

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- [ ] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**
Added a failing test case

**Is there anything you'd like reviewers to focus on?**
Fixing the error! 😀

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Hi, thanks for the PR.

At the moment, the autofixer for `prefer-const` only fixes cases where a variable is assigned at the same time as it's declared, e.g. `let foo = 5`. Autofixers aren't guaranteed to fix every error reported by a rule.

The fixer could reasonably fix the scenario in your test, but it can't do this in general:

```js
let lines;
something();
lines = foo();

// cannot safely be fixed to:

let lines = foo();
something();
```

The above fix can't be performed safely, because it would change the runtime behavior of the code; `foo()` would execute before `something()`, when it previously executed afterwards.

```js
let lines;
if (condition) {
  lines = 'foo';
} else {
  lines = bar;
}

doSomethingWith(lines);

// cannot safely be fixed (and won't be reported, because `lines` is used outside the `if` block)
```

I suppose we could perform a fix if a `let` variable is later reassigned in the same block, and there are no references to it before then:

```js
let foo;

// ... other code ...

foo = baz();

// gets fixed to:

// ... other code ...

const foo = baz();
```

But this would definitely be evaluated as an enhancement to the existing functionality, and not as a bugfix.

**Comment by SimenB** [comment]
I think you first example should be fixed like

```js
let lines;
something();
lines = foo();

// should be fixed to:

something();
const lines = foo();
```

And the second won't be reported, like you mentioned.

I didn't think about the cases of side effects, but those shouldn't be reported at all, should they?

**Comment by not-an-aardvark** [comment]
> EDIT: I suppose something could be a function hoisted in the same scope, accessing lines, but that would just be weird, wouldn't it? And would eslint even report that as a violation of prefer-const?

Yes, it would report it:

```js
let foo;

function func() {
  return foo;
}

console.log(func()); // prints `undefined`

foo = 5;
```

The fix would not be safe in this case:

```js

function func() {
  return foo;
}

console.log(func()); // throws a ReferenceError

const foo = 5;
```

So I think we could theoretically do a fix under the following conditions:

1. A variable is declared with `let` but not defined.
1. The variable is assigned a value exactly once later on.
1. All references to the variable (aside from the initial declaration) are in the same scope as the variable's assignment.
1. It is impossible for the variable to be read before it is assigned.
1. If the file is not a module, and the file is intended to be run in a browser, and the variable declaration is in the top-level scope, the variable's assignment is also in the top-level scope.

Then we can perform a fix by making the assignment a `const` and removing the `let`.

**Comment by platinumazure** [comment]
@not-an-aardvark In the conditions outlined above, how many times does the rule report-- once, or twice? If once (e.g., only on the `let` declaration), then the fix must do a massive text range replacement (because only one fix is allowed per report). Do we want to report twice instead?

I'm a bit leery about this fix because it seems that we need to have a lot of information from different parts of the source available at once.

**Comment by not-an-aardvark** [comment]
@platinumazure Yes, it would require a very large text replacement; this is not ideal.

I don't think reporting twice would solve the issue, because the code would end up in a bad state if only one fix was applied and the other one was not. (My understanding is that there is never a guarantee that a given fix will be applied, so each fix should be atomic.)

That said, I don't think we should completely rule out this fix based on its complexity (since at least some of the logic is already in the rule, which allows it to report these cases).

These sorts of fixes would be easier if a fixer could make multiple fixes at a time, rather than replacing the entire text range between the endpoints. I think I'm going to create a proposal at some point to allow this (regardless of what we decide on this particular issue), since it's been a problem for lots of fixes, and has led to fixes that are larger than necessary.

**Comment by vitorbal** [comment]
@not-an-aardvark the discussions here might also be of interest: https://github.com/eslint/eslint/issues/5329.

Meanwhile, what should we do about this PR? I'm with @platinumazure, if we can't find a simple way to apply this fix, then I think we should just not do it.

**Comment by not-an-aardvark** [comment]
I agree -- I think it would probably be best to not fix this for now.

**Comment by vitorbal** [comment]
Alright, in that case, would anyone be opposed to closing this PR? We can always revisit edge cases of current autofixers once we improve our autofixing API.

**Comment by SimenB** [comment]
(I don't mind you guys closing it, but should it be tagged with something so you're able to more easily revisit it?)

**Comment by kaicataldo** [comment]
Kind of confused why this is a PR since there isn't a proposed solution/prototype. I think this would make way more sense as an issue.

**Comment by kaicataldo** [comment]
Going to close this since it sounds like the consensus is to not fix this right now. We can always revisit if an issue is created for this or review if a PR is made with a proposed solution.

**Comment by kaicataldo** [comment]
Thanks for reporting the issue regardless, @SimenB!

**Comment by SimenB** [comment]
Well, I prefer having tests showing me exactly what fails instead if examples I have to set up to test.

Ava even has a type of test just for this purpose: https://github.com/avajs/ava#failing-tests

> This allows you to merge `.failing` tests before a fix is implemented without breaking CI. This is a great way to recognize good bug report PR's with a commit credit, even if the reporter is unable to actually fix the problem.

But again, I have no problem with you guys closing this

**Pull request closed without merging**
