### PR TITLE
Fix typo in no-multi-spaces "exceptions" section.

### PR DESCRIPTION
**Pull request by MadaraUchiha**
It's called VariableDeclarator, not VariableDecleration.

### CODE REVIEW

**Comment by MadaraUchiha** [comment]
Also, I got no warning or error for using the wrong format. I expect eslint to error out on "unknown exception VariableDecleration on line X" or something similar.

**Comment by michaelficarra** [comment]
They are both estree node types. They should both work the same here.

**Comment by MadaraUchiha** [comment]
Well then, it's a different bug, since VariableDecleration didn't work for me, and VariableDeclerator did.

**Comment by nzakas** [comment]
@MadaraUchiha please file an issue describing the bug.

**Pull request closed without merging**
