### PR TITLE
Fix: Improve keyword-spacing typescript support (fixes #8110)

### LINKED ISSUE #8110: Keyword-spacing rule cannot parse typescript generated AST
**Tell us about your environment**
* **ESLint Version:**
master
* **Node Version:**
4.7.2
* **npm Version:**
4.0.5

**What parser (default, Babel-ESLint, etc.) are you using?**
typescript-eslint-parser
**Please show your full configuration:**

```json


    "env": {
        "es6": true,
        "node": true,
        "mocha": true
    },
    "extends": "eslint:all",
    "parser": "typescript-eslint-parser",
    "parserOptions": {
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
    }


```

**What did you do? Please include the actual source code causing the issue.**

```ts

const foo =  symbol => 4;

@ffff() 
class Test {
    @ggg()
    static async values() {

    }
}

@ffff() 
class Test {
    @ggg()
    get values() {

    }

    @hhh()
    set values() {

    }
}


@eeeee
export function hhh(fff, @ff ee) {
}


@ttyy
export async function ffgghf(ff) {

}

@ffd
async function* gjgjg() {

}




```

**What did you expect to happen?**
It should parse

**What actually happened? Please include the actual, raw output from ESLint.**
An exception is thrown:

TypeScript will mark the first token of `symbol => 3;` as a keyword instead of as an identifier. This causes the function checkSpacingForFunction() to try and detect spacing around symbol which fails with: 
```
Cannot read property 'before' of undefined
TypeError: Cannot read property 'before' of undefined
    at checkSpacingBefore (/home/reyad/Workspace/eslint/lib/rules/keyword-spacing.js:276:40)
    at EventEmitter.checkSpacingForFunction (/home/reyad/Workspace/eslint/lib/rules/keyword-spacing.js:364:17)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/home/reyad/Workspace/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (/home/reyad/Workspace/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/home/reyad/Workspace/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.enter (/home/reyad/Workspace/eslint/lib/eslint.js:928:36)
    at Controller.__execute (/home/reyad/Workspace/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/reyad/Workspace/eslint/node_modules/estraverse/estraverse.js:501:28)
```

Decorators are not supported by eslint but I think we can make the keyword-spacing rule work around them. The first token for a class method, with a decorator that starts with the keyword get, set, or async, is the at (@) symbol. This causes the keyword-spacing rule to fail with exception:

```
TypeError: Cannot read property 'before' of undefined
    at checkSpacingBefore (/home/reyad/Workspace/eslint/lib/rules/keyword-spacing.js:276:40)
    at checkSpacingAround (/home/reyad/Workspace/eslint/lib/rules/keyword-spacing.js:299:13)
    at EventEmitter.checkSpacingForProperty (/home/reyad/Workspace/eslint/lib/rules/keyword-spacing.js:503:17)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/home/reyad/Workspace/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (/home/reyad/Workspace/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/home/reyad/Workspace/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.enter (/home/reyad/Workspace/eslint/lib/eslint.js:928:36)
    at Controller.__execute (/home/reyad/Workspace/eslint/node_modules/estraverse/estraverse.js:397:31)
``` 

More information can be found here:
https://github.com/eslint/typescript-eslint-parser/issues/102

I'm not sure if this is the right way to solve these issues. The first problem, with symbol and arrow functions, is most likely a bug in typescript or something typescript-eslint-parser could handle. The second problem, with decorators, is something that can be handled better by the keyword-spacing rule. Typescript-eslint-parser could hide the decorator token, as babel-eslint does, but this isn't ideal since rules could be made for typescript decorators.

### PR DESCRIPTION
**Pull request by soda0289**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ X] Other, please explain:
https://github.com/eslint/eslint/issues/8110

**What changes did you make? (Give an overview)**
Allow keyword-spacing rule to find the first token better by skipping over decorators, generated by typescript, and not including symbol keyword when parsing arrow functions.

**Is there anything you'd like reviewers to focus on?**
Is this the best solution to allow the typescript parser to work correctly with the keyword-spacing rule?

### CODE REVIEW

**Comment by soda0289** [comment]
Sure thing

**Comment by soda0289** [comment]
@not-an-aardvark 
I have added some tests that ensure no exceptions are thrown when using a decorator with class or method and using some keywords as a parameter in arrow functions.

I also added back the check for `firstToken.type === "Keyword"` but included the check for `firstToken.value === "function"`

**Comment by mysticatea** [comment]
@eslint/eslint-team What do you think if we have typescript in devDependencies? As my understanding, we have been avoiding that we have custom parsers in devDependencies. Though I'm not oppose it...

**Comment by soda0289** [comment]
@mysticatea 
I have added more tests for decorators with normal parameters, and with keyword parameters. I also added a test for abstract classes with decorators.

**Comment by JamesHenry** [comment]
The part of me that wants to see a resolution to a long-standing issue thinks "hellz yes!" 😄 

Other immediate thoughts:

- Keeping the peerDependency version of TypeScript within the `typescript-eslint-parser`, and this new devDependency of ESLint in sync would be a bit of a pain... Not sure if there is anything super simple we can do about it, though.

  - Crazy idea - ESLint Bot could open a PR to ESLint every time a new version of the `typescript-eslint-parser` is published, which updates the devDependencies:
    - `typescript-eslint-parser`: `{{ whatever that new version was }}`
    - `typescript`: `{{ whatever the peerDependency of typescript-eslint-parser is }}`

- I'm excited about this PR because how ever we do manage this kind of change in ESLint can hopefully serve as a template for similar things in future

- @nzakas has definitely given some thought to how changes like this would first start getting introduced into ESLint, so this is one rare occasion that I would like to make sure we get his input. He has very limited availability at the moment but kindly offered that I email him with stuff it is important that he sees. I will follow-up with him now.

**Comment by soda0289** [comment]
I can understand the concern of increasing the number of devDependencies and including parsers in the test suite. One way I can see to avoid this is to create another package or repository that handled eslint parser integration tests. That way if you change how eslint works you would not need to run all the parser integration tests unless it modified how parsing or rules were handled. New rules and rule modifications could run the integration tests and we could learn more about how these changes would effect users of those parser. A failing test in the integration test suite might indicate a problem with the parser itself and not eslint.

Another idea would be to hardcode the AST that typescript-eslint-parser generates and use that as test input instead of code.

**Comment by nzakas** [comment]
I'm inclined to think that we shouldn't bundle the TypeScript parser and run a lot of TypeScript tests in this repo. Instead, I'd suggest creating a stub custom parser for testing purposes where you can return whatever AST you want (I did that for type annotations already). I'd just cover a couple basic cases rather than the large number of tests this PR adds. 

Then, I like the idea of having some kind of separate integration test. It seems like that could live in the TypeScript parser repo? I'm also not opposed to a separate repo for that.

**Comment by soda0289** [comment]
@nzakas I see somthing similar was done in this PR https://github.com/eslint/eslint/pull/7820. Will follow the pattern found there. Thanks!

**Comment by mysticatea** [comment]
@soda0289 I'm sorry for my unclear request. My concern was a code like `class Foo { @desc({set a(value) {}, get a() {}, async c() {}}) async[foo]() {} }`. In this case, I guessed the 2nd `async` would be ignored.

**Comment by soda0289** [comment]
@mysticatea 
Thanks for that test case it was very valuable. The old logic, of finding the keyword token by starting from the beginning of the method declaration, fails when keywords are used in decorators. I had not considered this case before. I have changed it so that we search backwards from the node.key, the method name node, until the first keyword token is found. Can you think of cases where this would fail?

@not-an-aardvark
 I misunderstand what you meant by custom parser and have since rewrote the tests using a parser that has the typescript produced AST results hard coded. This is a much cleaner solution as @nzakas helped me realize.

These test no longer depend on typescript or typescript-eslint-parser. Thanks for your patience and feedback I appreciate it.

**Pull request merged**
