### PR TITLE
Chore: Update copyright and license info

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by nzakas** [comment]
@alberto have you signed the jQuery CLA? You'd need to use this info:

```
alberto <alberto.email@gmail.com>
```

The bot will check both the name and the email, so you can either update your git settings so that you use your full name or you can sign the CLA using just "alberto".

**Comment by nzakas** [comment]
Please hold off on merging this for now, some folks from the Foundation have some questions about this. I'm chatting with them about how to resolve.

**Comment by alberto** [comment]
@nzakas i learnt that the bad way :/
I wrote them asking if it was possible to change my name and they said they would do it.

**Comment by nzakas** [comment]
Okay, so it looks like the Foundation is recommending that we remove the `@copyright` and `MIT license` lines from each file because we don't need them at all. 

@alberto is it easy for you to make that change?

**Comment by alberto** [comment]
Yeah, removing them is easier than it was adding the missing ones :D

**Comment by kaicataldo** [comment]
I volunteer to go through espree and doctrine 😄

**Comment by nzakas** [comment]
BTW, there are some other files in the ESLint repo that I had changed myself. @alberto would you mind doing those in this PR as well?

**Comment by ilyavolodin** [comment]
I'll take website in the evening, shouldn't be too much stuff there.

**Comment by alberto** [comment]
Sure

**Comment by platinumazure** [comment]
I'll do generator-eslint.

**Comment by btmills** [comment]
:hand: I'm planning on doing the Markdown plugin tonight.

**Comment by kaicataldo** [comment]
Actually, does doctrine fall under the same license as the rest? It looks like it uses the Apache License. Just want to double check before I go through and make the changes.

**Comment by kborchers** [comment]
@alberto your CLA signature should be good now so when you push the requested changes it should recheck and validate your CLA. ping me directly if it still says there is an error

**Comment by alberto** [comment]
awesome! thanks @kborchers

**Comment by alberto** [comment]
@kborchers it's still complaining

**Comment by kborchers** [comment]
Sorry about that @alberto. Can you just force push that same commit and see if it validates now?

**Comment by alberto** [comment]
@kborchers no luck

**Comment by kborchers** [comment]
Can you try once more @alberto? If it doesn't work I'll have to call in some reinforcements because I'll be stumped. Sorry about this hassle. :frowning:

**Comment by alberto** [comment]
@kborchers still doesn't work

**Comment by kborchers** [comment]
so strange! i'll get some help and ping ASAP

**Comment by nzakas** [comment]
@alberto can you rebase? Let's get this merged and we can figure out the CLA issue on a smaller PR.

**Comment by alberto** [comment]
Done

**Comment by kborchers** [comment]
CLA check passes. Sorry about that, it looks like it was hung up on the server for some reason.

**Comment by alberto** [comment]
That's great @kborchers. thank you very much ❤️  and sorry for all the trouble ^__^

**Pull request merged**
