### PR TITLE
Update: Add support for class in `valid-jsdoc` rule (fixes #4279)

### LINKED ISSUE #4268: require-jsdoc for ES6 class methods [$10]
The `require-jsdoc` rule only supports `FunctionDeclaration` node type. It would be nice to have support for ES6 class methods and maybe constructors.

<bountysource-plugin>
---
There is a **[$10 open bounty](https://www.bountysource.com/issues/27719739-require-jsdoc-for-es6-class-methods?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #4279: valid-jsdoc for ES6 class and methods
Make `valid-jsdoc` rule work for ES6 class and methods.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27772225-valid-jsdoc-for-es6-class-and-methods?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**
Not an expert in ES6, so just to make sure i covered all the scenarios here.
CC @nzakas @jacek-dargiel

### CODE REVIEW

**Comment by siergiej** [comment]
Can you update the `require-jsdoc` rule while you're at it?

**Comment by jacek-dargiel** [comment]
Can you update the `require-jsdoc` rule while you're at it?

**Comment by gyandeeps** [comment]
@jacek-dargiel I think we should open a separate issue to handle `require-jsdoc` rule update.
Thoughts @nzakas ?

**Comment by nzakas** [comment]
@gyandeeps issue #4628 is about `require-jsdoc`, but this PR modifies `valid-jsdoc`. This PR should have a separate issue.

**Comment by gyandeeps** [comment]
@nzakas lol, I dont know why i kept reading it as `valid-jsdoc`.
I will open a new issue for this PR and also work the real issue ie `require-jsdoc`.

**Comment by nzakas** [comment]
LGTM

**Comment by gyandeeps** [comment]
@nzakas I am not very familiar with ES6 but di you think in this PR I should have listened for `MenthodDefinition` for class methods?
Right I rely on `FunctionExpression` to take of that because `MenthodDefinition`.value is always a `FunctionExpression`.

**Pull request merged**
