### PR TITLE
New: prefer-async-await rule (fixes #9649)

### LINKED ISSUE #9649: new rule: Prefer using async/await instead of Promise.prototype.then/catch/finally
In our company we have an _unwritten_ rule to use **async functions**, instead of **Promise.prototype.then/catch/finally** with the advantage of having synchronous code with an asynchronous control flow. I believe that Promises are also harder to gasp for beginners, and require quite a bit of discipline, and are also prone to many misunderstandings in the order of execution and resolution, including discouraged patterns, e.g. .then(onFulfilled[, onRejected]).

in addition, performance of async functions is also on par with Promises now (https://v8project.blogspot.com/2017/02/v8-release-57.html)

we also encourage to wrap callbacks from third party modules and return Promises, if applicable (does not apply to events etc.), but that's a different story...

**Please describe what the rule should do:**

Disallows the usage of Promise.prototype.then/catch/finally, and suggest to use async/await instead. I would leave the static methods (all, race, reject, resolve) to be allowed - if one doesn't like those for whichever reason, one could just disallow the global Promise object with no-restricted-globals.

the idea might be the same (or similar) to:
https://github.com/avajs/eslint-plugin-ava/blob/master/docs/rules/prefer-async-await.md
https://github.com/avajs/eslint-plugin-ava/blob/master/rules/prefer-async-await.js

**What category of rule is this? (place an "X" next to just one item)**

[x] Enforces code style
[ ] Warns about a potential error
[x] Suggests an alternate way of doing something
[ ] Other (please specify:)

**Provide 2-3 code examples that this rule will warn about:**

```js
// some hypothetical promise-returning function:
function promise() {
  return Promise.resolve(true);
}

// disallow
promise().then((bool) => ... );

// allow/suggest
const bool = await promise();

// disallow
promise().catch((err) => ...)

// allow/suggest
try {
  const bool = await promise();
}
catch (err) {
   // ... err
}

// disallow
promise().finally(() => {})

// allow/suggest
try {
  const bool = await promise();
}
finally {
   // ... cleanup
}

or in combination:

// disallow
promise()
  .then(bool => ... )
  .catch(err => ...)
  .finally(() => ...);

// allow/suggest
try {
   const bool = await promise();
}
catch (err) {
   // error handling
}
finally {
  // cleanup
}

// disallow
promise().then(...).then(...).then(...)

// allow/suggest
await ..
await ..
await ...
```

**Why should this rule be included in ESLint (instead of a plugin)?**

I can imagine that a lot of developers and companies might have a desire to use this rule, mainly for code style (synchronous code flow) as well as consistency.

_edit: just fixed some missing await_

### PR DESCRIPTION
**Pull request by mdjermanovic**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] New rule #9649

**What changes did you make? (Give an overview)**

* Checks only method calls, like `foo.then()`
* Reports `.then()`, `.catch()` and `.finally()`
* Has ~~two~~ four options, to allow at top level, in getters/setters, await and yield expr.
* The main example is designed to show advantages of `async`/`await`

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by mdjermanovic** [comment]
> What about an often-intentional line like:
> 
> ```js
> await foo.catch(…)
> ```
> 
> ?
> 
> I’d hope that wouldn’t warn here, since by using await already I’ve made it clear that this is as far as i want to make it imperative.

I'll add an option to allow calls in `await` expressions, and another option for `yield` expressions.

**Comment by ljharb** [comment]
Also, changing then calls to await is only equivalent when it’s in a chain - iow, we should be careful this rule doesn’t encourage incorrect and unnecessary serialization.

**Comment by mdjermanovic** [comment]
> Also, changing then calls to await is only equivalent when it’s in a chain - iow, we should be careful this rule doesn’t encourage incorrect and unnecessary serialization.

Yes, 'Promise methods' might not be clear enough. I'll try to clarify that in the doc, and add a '**correct**' example with `Promise.all()`

**Comment by mdjermanovic** [comment]
And maybe the doc should use the term 'Promise.prototype methods' or 'Promise prototype methods'  instead of just 'Promise methods'.

**Comment by mdjermanovic** [comment]
Added await and yield options. Also, 'Promise methods' are now 'Promise prototype methods', there is a `Promise.all()` section and a couple more sentences to clarify.

**Comment by mdjermanovic** [comment]
> Also, changing then calls to await is only equivalent when it’s in a chain - iow, we should be careful this rule doesn’t encourage incorrect and unnecessary serialization.

Did you mean something like this:

```js
function foo(x, y) {
  f(x).then(a => {...});
  g(y).then(b => {...});
}
```

the rule reports warnings and someone changes it to:

```js
async function foo(x, y) {
  const a = await f(x);
  ...
  const b = await g(y);
  ...
}
```

which is an unnecessary serialization

**Comment by ljharb** [comment]
Yes, exactly. That makes code worse, not better.

**Comment by mdjermanovic** [comment]
What could the rule do to prevent that?

Maybe not report unless an additional rule option is explicitly set. If it is set, then report but show a different message suggesting to split the body into several async functions (there would be an example in the docs).

**Comment by ljharb** [comment]
This is the difficulty with lint rules pushing await at all, and why imo require-await is such a pervasively terrible rule.

await is sugar for nested promise thens or a chain; it should *not* be used otherwise.

The difficulty, then, is that await can’t be safely recommended unless you are absolutely certain that there are no other un-awaited async operations that would be initiated after the point you want to insert the await. To do this safely requires a knowledge of every function’s runtime behavior (ie, if there’s any function calls or accessors, you have to know if they return promises or not).

**Comment by mdjermanovic** [comment]
> The difficulty, then, is that await can’t be safely recommended unless you are absolutely certain that there are no other un-awaited async operations that would be initiated after the point you want to insert the await. To do this safely requires a knowledge of every function’s runtime behavior (ie, if there’s any function calls or accessors, you have to know if they return promises or not).

Since that's beyond the static analysis, maybe the rule could check only 'last' statements (after which the function will end), or perhaps just return statements. In fact, the async version can be truly equivalent only if the `then()` was returned in the non-async version?

Though, I'm not sure would such a rule be useful, or just confusing e.g. in cases where there are unrelated `then()`s in the same function.

**Comment by mdjermanovic** [comment]
And for those that are not returned, the message could tell to extract the code into a new async function.

**Comment by mdjermanovic** [comment]
For example, something like this (with better messages):

```js
function foo(x, y) {
  f(x).then(a => {...}); // Error: Extract to an async function
  return g(y).then(b => {...}); // Error: Use async/await syntax
}
```

**Comment by ljharb** [comment]
The issue there is indeed that if you add `await` in front of `f(x)`, then you're artificially delaying when `g` can be invoked; so the only safe way to write it with await is either:
```js
function foo(x, y) {
  f(x).then(a => {...}); // Error: Extract to an async function
  const b = await g(y);
  return ...;
}
```
or, if a human but not a linter wrote it (obv depending on what's in the ellipses):
```js
function foo(x, y) {
  const [a, b] = await Promise.all([f(x), g(y)]);
  processA(a);
  return processB(b);
}
```

I'm not sure how valuable a linter rule is that can only safely recommend the former change, nor do i think it's objectively cleaner.

**Comment by mdjermanovic** [comment]
The `Promise.all()` version is not equivalent, it waits for both before processing both?

The idea was to change this:

```js
function foo(x, y) {
  f(x).then(a => {...}); // Error: Extract to an async function
  return g(y).then(b => {...}); // Error: Use async/await syntax
}
```

into this:

```js
async function foo(x, y) {
  newFunction(x);
  const b = await g(y);
  ...
}

async newFunction(x) {
  const a = await f(x);
  ...
}
```

and there should be perhaps a try-catch somewhere to be fully equivalent.

**Comment by ljharb** [comment]
ah, gotcha. that would work but is a bit of a major change for an eslint rule to recommend, imo.

**Comment by mdjermanovic** [comment]
> ah, gotcha. that would work but is a bit of a major change for an eslint rule to recommend, imo.

I guess it depends on the user. 

If someone wants to completely switch to the async/await, this might be seen as a necessary step - is there another way to convert this code into an async/await equivalent? There can be an example in the docs.

If someone does not want major changes like this, there could be an option to check only return statements, or not use the rule at all.

Just to note, a new function declaration from the example is what a human can do (it should have a meaningful name etc.), autofix would probably be an anon async iife in the same place. It doesn't look much better on a small example, but if it is a replacement for a chain/nested thens, it should be more readable. Though, I'm not sure is this rule supposed to have autofix, it would be more like a transpiler than a fixer.

**Comment by ljharb** [comment]
You *can't* completely "switch" because async/await a) is not complete (there's no `Promise.all`) and b) you simply can't "not know about Promises" - they will always be present, even in a codebase using async/await, if the code is optimal.

**Comment by mdjermanovic** [comment]
> You _can't_ completely "switch" because async/await a) is not complete (there's no `Promise.all`) and b) you simply can't "not know about Promises" - they will always be present, even in a codebase using async/await, if the code is optimal.

Of course, the whole point of this rule is just to restrict `.then()`, `.catch()`, `.finally()` in favor of `async`, `await`, `try {} catch {} finally{}`, as described in #9649 with the reasons why is it useful.

And, as you said, it's important that this rule doesn’t encourage incorrect and unnecessary serialization, i.e. make the code worse. If it is impossible to achieve, then the rule probably shouldn't be included in the core rules, although the request is accepted.

I believe that this version should be modified to report different messages when a restricted call is in a return statement and when it isn't, all that with appropriate examples of how to change the code in the rule documentation.

The question is - is it good enough? Can it still make someone's code worse? Is it useful at all?

**Comment by ljharb** [comment]
My intuition is that any rule that attempts to encourage usage of `await` is not, on balance, useful.

**Comment by mdjermanovic** [comment]
Then I'll modify it and move to a plugin, perhaps it might be useful for someone thanks to this analysis.

Btw. [VSCode can auto-convert chains](https://dev.to/ben/visual-studio-code-can-now-convert-your-long-chains-of-promisethens-into-asyncawait-automagically-1b1b) (and nested calls), and it works by design only with returned ones.

**Comment by dnalborczyk** [comment]
@ljharb @mdjermanovic 

The way I personally see this is that this `rule` would be an **opt-in** (like a lot of other rules), nobody is saying it should be added to `eslint:recommended` or `eslint-config-airbnb-base`.

it's for people who _deliberately_ choose this for _their_ project as a matter of coding style.

if someone deliberately has a use case for this (e.g. as a one-off), there's always an opt-out ...
```js
function foo(x, y) {
  // eslint-disable-next-line name-of-rule
  f(x).then(a => {...});
  g(y).then(b => {...});  // eslint-disable-line name-of-rule
}
```
...or don't use this rule at all.

Nobody is saying to `"just forget about Promises"`, obviously you very much need to know how they work, and how they translate to `async functions`. I think a similar analogy would be that you have to know how SQL works, when using an ORM. You might get by without it, the outcome though is very likely terrible.

and, the usage of Promise.all/race/any/allSettled is still very much encouraged!

anyhow, I personally see it being _very useful_ for cases and projects like this: https://developers.google.com/web/fundamentals/primers/async-functions or this: https://medium.com/@pyrolistical/the-hard-error-handling-case-made-easy-with-async-await-597fd4b908b1

as a user of this rule I'd expect that this pattern:
```js
await foo.catch(…)
```
would have to become:
```js
try {
  await foo
} catch {
  ...
}
```

the whole point of this rule would be to discourage (or disallow) exactly that. if that's a very common pattern and if there's any merit, people can still choose to _not use this rule_, or _opt-out_, or, if it's possible to add it as a _rule parameter_, even better!

if someone likes to look at promise chains, that's great! this rule is not for you!

**Pull request closed without merging**
