### PR TITLE
Docs: Repair broken links and add migration links.

### PR DESCRIPTION
**Pull request by jrpool**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Added 3 migration links. Correct links requiring “.md” by adding that. Without that extension, I found those links producing a 404-status response.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the PR. I think the links are like that because they're intended to be viewed [here](https://eslint.org/docs/user-guide/) (where it's correct for them to have no extensions), rather than being viewed on GitHub.

**Comment by Aladdin-ADD** [comment]
seems like some `Related Rules` also have `.md`, and it's working. e.g. https://eslint.org/docs/rules/no-confusing-arrow#related-rules

I guess it's fine to add them. 😄  @not-an-aardvark

**Comment by not-an-aardvark** [comment]
Actually, I forgot that we [strip out .md extensions](https://github.com/eslint/eslint/blob/eb8cfb1cc738753a1e8175926f5ea240fcf51b07/Makefile.js#L737) when generating the site. So I'm fine with adding the extensions for the benefit of people reading the documentation on GitHub.

**Comment by not-an-aardvark** [comment]
Thanks for contributing!

**Pull request merged**
