### PR TITLE
Chore: Format style guide links so they can be clicked

### PR DESCRIPTION
**Pull request by ivandotv**
**What is the purpose of this pull request? (put an "X" next to item)**

[ x ] Other, please explain:

**What changes did you make? (Give an overview)**

When initializing new eslint project and coming to style guide step, visual studio code terminal doesn't properly format style guide links so when user clicks on one of the links (in the terminal) it takes them to e.q `https://github.com/airbnb/javascript)` (note the `)` at the end) 
Putting spaces after the opening brace and before the closing brace fixes this issue.
**Is there anything you'd like reviewers to focus on?**
No

### CODE REVIEW

**Comment by platinumazure** [comment]
Hi @ivandotv, thanks for the PR.

Wouldn't it be better to resolve this in Visual Studio Code? I'm not sure https://github.com/airbnb/javascript) is even a valid URL.

**Comment by ivandotv** [comment]
Clicking the airbnb link goes to 404 page on github.com
I can confirm that linux terminals recognize the url properly, so this is vscode editor issue (maybe some other editors too)
However many other npm modules are aware of this issue and they put spaces around links.

**Comment by ilyavolodin** [comment]
I think I'd be fine with this fix. It's so minor, it's not worth trying to push it off to VSCode (although it should also be reported there as well).

**Comment by platinumazure** [comment]
I just think spaces in parentheses are kind of ugly. Can we come up with another approach here? Maybe remove the parentheses altogether and use some other approach?

**Comment by g-plane** [comment]
We can use colon.

Screenshots:
图片

图片

Links can be detected properly.

**Comment by ivandotv** [comment]
I also like it more with the colon.
Should I make the change?

**Comment by g-plane** [comment]
Feel free to do it!

**Comment by aladdin-add** [comment]
merged, thanks for contributing!

**Pull request merged**
