### PR TITLE
Fix: `--no-ignore` should not un-ignore default ignores (fixes #5547)

### LINKED ISSUE #5547: `--no-ignore` should not un-ignore node_modules
**What version of ESLint are you using?**
Master

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**
Espree

**What did you do? Please include the actual source code causing the issue.**
Ran eslint with `--no-ignore` flag

**What did you expect to happen?**
Ignore settings from `.eslintignore` to be disregarded, as indicated in docs.

**What actually happened? Please include the actual, raw output from ESLint.**
ESLint linted all files within `node_modules`.

Despite having [tests](https://github.com/eslint/eslint/blob/d727f17f4efc888ed0e59259a4e4cac01a42f0d9/tests/lib/ignored-paths.js#L375-L383) to assert that `--no-ignore` will cause `node_modules` to be linted, I think this is not the behavior we expect or want.  

The --no-ignore docs say:
> --no-ignore
> Disables excluding of files from .eslintignore and --ignore-path files.

They don't say anything about also disabling default ignores.

After https://github.com/eslint/eslint/issues/5410 is fixed, it will be possible to lint within node_modules by using a negation pattern.  (e.g. `!/node_modules/package-to-lint/`), at which time I think it would make sense to keep `--no-ignore` from linting `/node_modules/` and `/bower_components/`.

Does the team agree?

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by IanVS** [comment]
Restarted AppVeyor.  PR LGTM.

**Comment by gronke** [comment]
How would a user override even the default ignore pattern? Before this change, it was possible to create (or reference) an empty `.eslintignore` file to achieve the same while still ignoring default pattern. I would expect no ignore pattern to apply at all when the feature was disabled, not even the default ones.

**Comment by IanVS** [comment]
@gronke Now that https://github.com/eslint/eslint/pull/5627 is merged, the defaults can be overridden with:

```
!/node_modules/
!/bower_components/
```

**Comment by gronke** [comment]
But you can not override then when `--no-ignore` option was provided. How do you un-ignore user and default pattern at the same time after this was merged?

**Comment by IanVS** [comment]
Ah, good point.  I'm not sure how to handle that case.

**Comment by gronke** [comment]
If I would like to disable all user ignore pattern, but not the default ones I'd execute

```bash
echo "" > /tmp/.eslintignore_empty
eslint --config /tmp/.eslintignore_empty
```

**Comment by IanVS** [comment]
If we are talking about workarounds, I think it is less common to want to unignore absolutely everything than it is to "unset" the `.eslintignore` file.  To unignore absolutely everything (except dotfiles, which is a different discussion), it should be possible to create an ignore file with only:

```
!/node_modules/
!/bower_components/
```

and specify it using `--ignore-path`.

I still think this PR is the way to go for the 90% use case, and will make us match our current documentation.

**Comment by gronke** [comment]
Perfect, just wanted to make sure we stay flexible. LGTM :+1:

**Comment by nzakas** [comment]
LGTM

**Pull request merged**
