### PR TITLE
Update: add `arrowFunctions` option to `no-empty` (fixes #5161)

### LINKED ISSUE #5161: Rule Proposal: `no-empty-function`
```js
const getEmptyObject = () => {};
console.log(getEmptyObject()); // undefined
```

If the body of an arrow function is `{}`, it's a block statement, not an empty object literal.
This might confuse developers.

This proposal is that we add the option to warn such empty arrow function to the `no-empty` rule.

----

The following patterns are considered problems:

```js
/* eslint no-empty: [2, {arrowFunctions: true}] */

const f = () => {};  /*error Empty block statement.*/
```

The following patterns are not considered problems:

```js
/* eslint no-empty: [2, {arrowFunctions: true}] */

// this is an empty object literal.
const f = () => ({});

// there is an clear comment.
const f = () => {
    // do nohting.
};
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30568567-rule-option-proposal-arrowfunctions-of-the-no-empty-rule?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #5161

### CODE REVIEW

**Comment by michaelficarra** [comment]
:-1: I think this should be its own rule. This is barely related to empty block statements.

**Comment by mysticatea** [comment]
Hmm, surely, probably rule such as `no-empty-function` is proper for this. But `no-empty` has had an option to warn empty methods already, so I thought this should be added to the `no-empty` rule for now.

Or, I can write new `no-empty-function` rule and deprecate the `method` option of the `no-empty` rule.
I don't have strong opinions here.

@eslint/eslint-team Thought?

**Comment by nzakas** [comment]
I think I agree with @michaelficarra. It's probably better to have a `no-empty-function` rule that deals with methods, arrow functions, and whatever else (especially since it looks like the `methods` option was undocumented).

**Comment by mysticatea** [comment]
OK, I will update #5161 and make new rule.

@nzakas The option has been added in 2.0.0 pre-release: http://eslint.org/docs/2.0.0/rules/no-empty

**Comment by nzakas** [comment]
@mysticatea ooh wow, maybe we should pull that back out for 2.0.0?

**Comment by mysticatea** [comment]
1. We can modify no-empty rule as this PR.
2. If possible, we can make no-empty-function rule and remove the `methods` option of no-empty rule. In this case, I can do in today, probably.
3. We can make no-empty-function rule and just deprecate the `methods` option of no-empty rule after 2.0.0.

**Comment by nzakas** [comment]
I think option 2 is best. Since we just added `methods`, releasing it and immediately deprecating it doesn't make much sense.

**Comment by mysticatea** [comment]
OK. I will do.

**Pull request closed without merging**
