### PR TITLE
docs: update 'Related Rules' and 'Further Reading' in remaining rules

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Follow-up to https://github.com/eslint/eslint/pull/15869

#### What changes did you make? (Give an overview)

Updated the remaining rules per the changes from https://github.com/eslint/eslint/pull/15869.

#### Is there anything you'd like reviewers to focus on?

* I replaced dead links with web.archive.org links (build fails when there are dead links).
* There are two pages with mixed content (http). There were 5 pages reported in [this Mixed content check](https://github.com/eslint/eslint/runs/6459685041). I fixed only 3 of them (by using https links), but for some reason the remaining 2 don't appear in the Mixed content check for subsequent commits. Those pages are:
  * https://deploy-preview-15884--docs-eslint.netlify.app/rules/prefer-promise-reject-errors/ (`http://bluebirdjs.com/img/favicon.png`)
  * https://deploy-preview-15884--docs-eslint.netlify.app/rules/yoda/ (`http://thomas.tuerke.net/images/tmtlogo.ico`)

I think we should fix the mixed content problem on those two pages, although the check doesn't report them, but I'm not sure how - remove the links, or use web.archive.org links instead, or something else?

### CODE REVIEW

**Comment by nzakas** [comment]
Any reason not to update the remaining two to HTTPS and call it done?

**Review by aladdin-add — APPROVED** [review]
lgtm~

**Comment by mdjermanovic** [comment]
> Any reason not to update the remaining two to HTTPS and call it done?

I totally forgot to mention the reason. Those two links are:

* http://bluebirdjs.com/docs/warning-explanations.html
* http://thomas.tuerke.net/on/design/?with=1249091668#msg1146181680

With `https://`, I'm getting ERR_CERT_COMMON_NAME_INVALID on both.

**Comment by nzakas** [comment]
I think we can leave these for now. I’m going to update the way those links are rendered so hopefully it won’t matter going forward.

**Review by nzakas — APPROVED** [review]

**Pull request merged**
