### PR TITLE
New: Allow plugins to provide environments (fixes #1130)

### LINKED ISSUE #1130: Allow the user to specify custom environments
### The problem I want to solve:
Currently I have a hackish way of calling eslint because my test files require a slightly different eslintrc than my normal js files. I could put my test files in a seperate directory, but besides the fact that I don't like that, I can image more groups of files that require a slightly different eslintrc such as files that need to run on IE6 (requiring eslint rules that prevent a comma at the end of a hashmap) vs. files that are only for nodejs. I don't think that requiring different directories is always the best solution.

### My take on the solution to problem.
My first take was to simply allow you to specify eslint overrides depending on the file name. (so you can have `some.test.js` and `some.crossplatform.js`) While this is a quick fix it was pointed out to me that this adds too much complexity to the configuration system. So perhaps we could make the environments configurable?

- I'm currently on master
- I'm willing to implement this myself

### discussion points
 - [x] whether to store the property in the .eslintrc or in a seperate file. (.eslintrc)
 - [ ] the name of the property in the .eslintrc
 - [ ] how to deal with naming collisions between the custom environment
 - [x] how to deal with two environments specifying a different severity. ([simply let the environment that is included latest win](#issuecomment-50901055))

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/3399822-allow-the-user-to-specify-custom-environments?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by eric-isakson**
Adapted lib/config.js to load plugins prior to env block processing and modify the environments object to include environments defined in plugins. Updated doc and tests.

### CODE REVIEW

**Comment by eric-isakson** [comment]
I read over the comments in the previous pull request about not wanting to prefix own rules in the environment definition. IMO, that is a nice to have but not a necessary requirement. In addition a change to a plugin name (which is used to prefix rules and environments) is a backward incompatible breaking change, so making it easy to change a plugin name should IMO not be a goal of the implementation. Please let me know if you strongly disagree or have other issues with my proposed change. I'm using this with a private internal fork and looking at the new feature for shared configs to support the use cases I require.

**Comment by eric-isakson** [comment]
In #2442 it was suggested that we move environments out of conf/environments.js, I would only do that for new environments and not change the existing definitions unless you want to add a feature that allows the plugin to "break" the plugin name prefixing on the environment definition. Moving the existing environments wouldn't buy much unless you are willing to make it a breaking change.

For example, moving the node environment definition to a plugin like "eslint-plugin-node" would change the name of that environment to "node/node" which would then break everyone that uses the "node" environment. You would also require them to add a dependency on the "eslint-plugin-node" module. Overall, I would expect such a breaking change to be unwelcome in the user base.

**Comment by ilyavolodin** [comment]
This doesn't cover scenario of enabling/disabling environments inline through comments. That's basically the reason I closed my old pull request for plugin environments.

**Comment by eric-isakson** [comment]
Actually it does, I’ve tried it in my own environment but couldn’t figure out how to create a test case for it.

**Comment by eric-isakson** [comment]
based on where I added the logic in lib/config.js any environment added via a plugin will be treated exactly as an environment from conf/environments.js with the exception that the environment name will be prefixed with the plugin name.

**Comment by nzakas** [comment]
We haven't yet resolved the right way to put environments into plugins - there are still too many questions to consider this proposal. Config shouldn't be loading plugins, that's beyond its responsibility.

If you'd like to discuss further, phase comment on the issue so we can work through the open questions.

**Comment by eric-isakson** [comment]
I'm happy to address any issues and work through them together. Should I comb through 1130 and the previous attempted fix for the issues or would you like to enumerate them here?

As to the responsibility of the config object, config already loads plugins:

https://github.com/eslint/eslint/blob/master/lib/config.js#L392

It is also currently based on a side effect where the base config.plugins property is manipulated by the utile.mergeConfigs function:

https://github.com/eslint/eslint/blob/master/lib/util.js#L36

My change just makes the collection of plugins an explicit operation that happens early enough to be able to manipulate the environmets:

https://github.com/eric-isakson/eslint/blob/master/lib/config.js#L359

Do you see some other way to achieve this?

**Comment by nzakas** [comment]
Let's have this discussion on the issue rather than here

**Pull request closed without merging**
