### PR TITLE
Adds missing "not" to semi.md

### PR DESCRIPTION
**Pull request by mariusschulz**
This should say _"if you do **not** want to …"_, right?

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Can you please update your commit message to begin with "Docs:"?

You can then amend your commit and re-push to update the PR:

```sh
$ git add .
$ git commit --amend --no-edit
$ git push -f
```

**Comment by mariusschulz** [comment]
Sure thing, commit message is updated.

I'm not sure why you suggested using both `git add .` and `--no-edit`, though, to be honest. A simple `git commit --amend` (followed by a force push) did the trick.

**Comment by ilyavolodin** [comment]
@mariusschulz I honestly just copied @nzakas instructions:-) I think those might've been created for updates that had some changes to files as well as title of the commit.

**Comment by mariusschulz** [comment]
@ilyavolodin Ah, that makes sense. ;) Right, the Git commands are for adding new files or file changes to the commit without updating the commit message (`--no-edit`).

**Pull request merged**
