### PR TITLE
Fixed no-func-assign rule on import declarations (#2060)

### PR DESCRIPTION
**Pull request by ZIJ**

### CODE REVIEW

**Comment by douglasduteil** [comment]
+1

**Comment by nzakas** [comment]
Thanks. Please take a moment to read over our contribution guidelines and update your pull request accordingly: http://eslint.org/docs/developer-guide/contributing.html

**Comment by nzakas** [comment]
Specifically, we have a commit message format, we require tests for all changes, and we need you to sign or CLA.

**Comment by btmills** [comment]
The commit message says `no-type-assign`, though the change is for the `no-func-assign` rule.

**Comment by ZIJ** [comment]
Thank you so much! Updated the pull.

**Comment by gianu** [comment]
+1

**Comment by nzakas** [comment]
Looks good. Can you please sign our CLA? http://eslint.org/cla

**Comment by ZIJ** [comment]
I already signed it before updating the pull. Just to be sure, did it again :)

**Comment by nzakas** [comment]
Sorry about that, for some reason you didn't show up initially when I checked it. Looks good now!

**Comment by jonathanKingston** [comment]
Upon update of broccoli-eslint to 0.17.1; I am seeing new issues which seem to be unreported relating to these changes (I'm unsure which is the best issue to re-raise here or if it is a new issue).

The code I have (Which I use to check each upgrade and is not automated yet):
```
import Ember from 'ember';
import Resolver from 'ember/resolver';
import loadInitializers from 'ember/load-initializers';
import config from './config/environment';

Ember.MODEL_FACTORY_INJECTIONS = true;

var App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver: Resolver
});
if (true == 1)
{console.log('spoon');};
console.log('test');

loadInitializers(App, config.modulePrefix);

export default App;
```

The error caused is:
```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at EventEmitter.fixImport (/home/jonathan/broccoli-eslint/node_modules/eslint/lib/rules/no-undef.js:113:54)
```

I will help debug further tomorrow, the code uses babel-eslint which could also be the issue.

**Comment by nzakas** [comment]
PRs should never be used to report issues. If you're seeing a new bug, please file a new issue.

**Pull request merged**
