### PR TITLE
Fix: Fix broken links in documentation

### PR DESCRIPTION
**Pull request by app**
Documentation update/fix
This is small update fixing broken links in Markdown documentation.

### CODE REVIEW

**Comment by app** [comment]
This is Documentation update/fix

**Comment by platinumazure** [comment]
The links work fine on [this page](http://eslint.org/docs/user-guide/) on the website. In what context are you seeing them as broken links? Are you viewing the GitHub rendering, perhaps?

**Comment by app** [comment]
I've got 404 error page https://github.com/app/eslint/blob/master/docs/user-guide/getting-started 
I'm using Chrome/Ubuntu

**Comment by app** [comment]
Ok. It seems to me I wrong :( 
Sorry

**Comment by platinumazure** [comment]
I can reproduce by starting at https://github.com/eslint/eslint/tree/master/docs/user-guide, and then clicking any of the links there.

@eslint/eslint-tsc Do we want to fix this, or are we okay with just saying the ESLint site (http://eslint.org) should be considered the sole documentation repository and people shouldn't use our eslint/eslint GitHub repo to look at docs?

**Comment by ilyavolodin** [comment]
Documentation we created is targeting website, so I think it's fine if the links don't work in the repository.

**Pull request closed without merging**
