### PR TITLE
Pin: table@4.0.2, because 4.0.3 needs "ajv": "^6.0.1", causing a conf…

### PR DESCRIPTION
**Pull request by MS-elug**
…lict with eslint 4.18.1 that requires "ajv": "^5.3.0"

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain: Update package json to avoid peerDependency issue due to the latest release of "table"

**What changes did you make? (Give an overview)**
Pin: table@4.0.2, because 4.0.3 needs "ajv": "^6.0.1", causing a conflict with eslint 4.18.1 that requires "ajv": "^5.3.0"

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by platinumazure** [comment]
For the rest of the team: I'm still trying to get eslint-canary working properly so I can validate the ajv upgrade I've proposed some time ago in another PR. So this PR could silence the peer dependency warning until my PR is validated and merged.

Besides the peer dependency warning being confusing, I don't think users experience any other harm (but @MS-elug please correct me if I'm wrong).

**Comment by realityking** [comment]
I just did `npm install` on fresh clone of master.

As I expected I get the unmet peer dependency warning:

```
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

But when I run `node bin/eslint.js -f table Makefile.js` I get a nicely formatted table.

This is really just npm reporting an error that isn't really an error. It might still be worth fixing to not confuse downstream users but it's a not the case that something is broken.

**Comment by not-an-aardvark** [comment]
> This is really just npm reporting an error that isn't really an error.

Right, I'm saying that this should be filed as a bug in npm, because it shouldn't arrange the dependencies in a manner such that this problem occurs.

I'm fine with hacking around the problem in the meantime, but this seems like something that should be fixed in general.

**Comment by zckrs** [comment]
This missing peer dep will block any lock deps throught `npm shrinkwrap`

**Comment by platinumazure** [comment]
@not-an-aardvark

> Right, I'm saying that this should be filed as a bug in npm, because it shouldn't arrange the dependencies in a manner such that this problem occurs.

I'm not sure this is the case. Peer dependencies are logical dependency declarations only, and it's up to the top-level project to declare its own dependencies that resolve all required peer dependencies (in theory; in practice, this is a little more difficult since indirect dependencies may specify peer deps that their consuming projects don't fulfill).

Put another way, npm only checks that ajv@^5.3.0 is available to ESLint, and ajv@^6.0.1 is available to table. This cannot be fulfilled with our current package.json. If anything, table (or one of its dependencies) should explicitly depend on ajv to fulfill the peer dependency and avoid the problem upstream.

If this was a dependency issue rather than peer dependency, I would agree this is an npm issue. But in this case, I'm not sure it's an npm issue.

Let me know if I'm missing something.

**Comment by ljharb** [comment]
If some version `table` has a peerDep on ajv 6, and eslint uses `table` directly, and eslint also needs ajv 5, then eslint can't use that version of table, because they're incompatible.

Whether table needs to peer-depend on ajv versus depend on it is separate; but at the moment, that's how it is.

**Comment by realityking** [comment]
@platinumazure Not quite.

The situation is the following:
eslint depends on table@^4.0.1 and ajv@^5.3.0
table depends on ajv@^6.0.1 and ajv-keywords@^3.0.0
ajv-keywords has a *peerDependency* on  ajv@^6.0.0

npm arranges theses packages in the following way

eslint
- table@4.0.3
-- ajv@6.2.0
- ajv@5.5.2
- ajv-keywords@3.0.0

Because ajv-keywords@3.0.0 is on the same level as ajv@5.5.2, npm shows this warnings as ajv@5.5.2 is not in range for the ajv-keywords peer dependency.

But when table loads ajv it correctly gets ajv@6.2.0 which does work with ajv-keywords@3.0.0

@ljharb table does not have a peer dependency on ajv. One its dependencies, ajv-keywords, does.

**Comment by ljharb** [comment]
@realityking ah, thanks. then in that case, `table` is in error, and should indeed have a direct dependency on ajv - otherwise, that peer dep (which is part of its API) is a breaking change.

**Comment by realityking** [comment]
@ljharb I'm not sure I follow. `table` *does* have a direct dependency on `ajv`. See here https://github.com/gajus/table/blob/bd4d09e0de99bda1f88fa648fca42d0547eb808e/package.json#L8-L9

**Comment by ljharb** [comment]
:-/ hmm, in that case i have no idea why this is causing an issue for eslint. This does seem more like a bug in npm, provided `rm -rf node_modules && npm install && npm ls` is still complaining.

**Comment by realityking** [comment]
@ljharb See the first part https://github.com/eslint/eslint/pull/10022#issuecomment-368601457. Because `ajv@5.3` and `ajv-keywords@3.0` get installed on the same level in the tree the peer dep validation fails. When accessing the modules in code everything is fine.

**Comment by ljharb** [comment]
Right; because `ajv-keywords` has a peer dep, that's satisfied by one of `table`'s unhoisted deps, it's incorrect for `npm` to hoist it above `table`.

**Comment by platinumazure** [comment]
Seems my comment was in error. Sorry for the confusion, folks.

**Comment by billyjanitsch** [comment]
@ljharb this is a known issue in npm, unfortuantely. The hoisting algorithm doesn't currently consider whether a package's peer dependencies will be satisfied when hoisting it.

There was a [quick/dirty fix](https://github.com/npm/npm/pull/17678) in npm 5.2.0 but they [rolled it back](https://github.com/npm/npm/issues/17717#issuecomment-314599702) in 5.3.0 because they wanted to fix it properly & the naive fix broke users with [questionable dependency workflows](https://github.com/npm/npm/pull/17678#issuecomment-314397354).

**Comment by kevzdev** [comment]
Encountered this issue on standard too: https://github.com/standard/standard/issues/1078#issuecomment-368962798

**Comment by billyjanitsch** [comment]
@kevzdev it occurs in standard because standard depends on eslint; it's the same issue.

**Comment by zkat** [comment]
Can you repro this with `npm@5.7.1`? We [patched peerDep stuff](https://github.com/npm/npm/commit/6954dfc192f88ac263f1fcc66cf820a21f4379f1) so it "should" be extraordinarily rare to crash like this.

you can one-off try that version of npm by trying to repro it with `$ npx npm@5.7.1 install`

**Comment by platinumazure** [comment]
@not-an-aardvark Any objection to merging this in, so we can at least allow `npm shrinkwrap` to start working again on our next release?

**Comment by not-an-aardvark** [comment]
I'm fine with merging this.

**Comment by not-an-aardvark** [comment]
@zkat Thanks for looking into this! I think I'm still encountering the problem with `npm@5.7.1`:

<details>

<summary>Commands used, `npm ls` output</summary>

```
$ npm i npm@5.7.1 -g
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.7.1
added 63 packages, removed 117 packages and updated 49 packages in 9.767s
~/code/sandbox$ npm -v
5.7.1
$ npm i eslint
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

+ eslint@4.18.1
added 139 packages from 146 contributors in 5.555s

$ npm ls
$ npm ls
foo@ /path/to/current/dir
└─┬ eslint@4.18.1
  ├─┬ ajv@5.5.2
  │ ├── co@4.6.0
  │ ├── fast-deep-equal@1.1.0
  │ ├── fast-json-stable-stringify@2.0.0
  │ └── json-schema-traverse@0.3.1
  ├─┬ babel-code-frame@6.26.0
  │ ├─┬ chalk@1.1.3
  │ │ ├── ansi-styles@2.2.1
  │ │ ├── escape-string-regexp@1.0.5 deduped
  │ │ ├─┬ has-ansi@2.0.0
  │ │ │ └── ansi-regex@2.1.1 deduped
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.1.1
  │ │ └── supports-color@2.0.0
  │ ├── esutils@2.0.2 deduped
  │ └── js-tokens@3.0.2
  ├─┬ chalk@2.3.1
  │ ├─┬ ansi-styles@3.2.0
  │ │ └─┬ color-convert@1.9.1
  │ │   └── color-name@1.1.3
  │ ├── escape-string-regexp@1.0.5
  │ └─┬ supports-color@5.2.0
  │   └── has-flag@3.0.0
  ├─┬ concat-stream@1.6.0
  │ ├── inherits@2.0.3
  │ ├─┬ readable-stream@2.3.4
  │ │ ├── core-util-is@1.0.2
  │ │ ├── inherits@2.0.3 deduped
  │ │ ├── isarray@1.0.0
  │ │ ├── process-nextick-args@2.0.0
  │ │ ├── safe-buffer@5.1.1
  │ │ ├─┬ string_decoder@1.0.3
  │ │ │ └── safe-buffer@5.1.1 deduped
  │ │ └── util-deprecate@1.0.2
  │ └── typedarray@0.0.6
  ├─┬ cross-spawn@5.1.0
  │ ├─┬ lru-cache@4.1.1
  │ │ ├── pseudomap@1.0.2
  │ │ └── yallist@2.1.2
  │ ├─┬ shebang-command@1.2.0
  │ │ └── shebang-regex@1.0.0
  │ └─┬ which@1.3.0
  │   └── isexe@2.0.0
  ├─┬ debug@3.1.0
  │ └── ms@2.0.0
  ├─┬ doctrine@2.1.0
  │ └── esutils@2.0.2 deduped
  ├─┬ eslint-scope@3.7.1
  │ ├─┬ esrecurse@4.2.1
  │ │ └── estraverse@4.2.0 deduped
  │ └── estraverse@4.2.0
  ├── eslint-visitor-keys@1.0.0
  ├─┬ espree@3.5.3
  │ ├── acorn@5.5.0
  │ └─┬ acorn-jsx@3.0.1
  │   └── acorn@3.3.0
  ├─┬ esquery@1.0.0
  │ └── estraverse@4.2.0 deduped
  ├── esutils@2.0.2
  ├─┬ file-entry-cache@2.0.0
  │ ├─┬ flat-cache@1.3.0
  │ │ ├── circular-json@0.3.3
  │ │ ├─┬ del@2.2.2
  │ │ │ ├─┬ globby@5.0.0
  │ │ │ │ ├─┬ array-union@1.0.2
  │ │ │ │ │ └── array-uniq@1.0.3
  │ │ │ │ ├── arrify@1.0.1
  │ │ │ │ ├── glob@7.1.2 deduped
  │ │ │ │ ├── object-assign@4.1.1 deduped
  │ │ │ │ ├── pify@2.3.0 deduped
  │ │ │ │ └── pinkie-promise@2.0.1 deduped
  │ │ │ ├── is-path-cwd@1.0.0
  │ │ │ ├─┬ is-path-in-cwd@1.0.0
  │ │ │ │ └─┬ is-path-inside@1.0.1
  │ │ │ │   └── path-is-inside@1.0.2 deduped
  │ │ │ ├── object-assign@4.1.1 deduped
  │ │ │ ├── pify@2.3.0
  │ │ │ ├─┬ pinkie-promise@2.0.1
  │ │ │ │ └── pinkie@2.0.4
  │ │ │ └─┬ rimraf@2.6.2
  │ │ │   └── glob@7.1.2 deduped
  │ │ ├── graceful-fs@4.1.11
  │ │ └─┬ write@0.2.1
  │ │   └── mkdirp@0.5.1 deduped
  │ └── object-assign@4.1.1
  ├── functional-red-black-tree@1.0.1
  ├─┬ glob@7.1.2
  │ ├── fs.realpath@1.0.0
  │ ├─┬ inflight@1.0.6
  │ │ ├── once@1.4.0 deduped
  │ │ └── wrappy@1.0.2
  │ ├── inherits@2.0.3 deduped
  │ ├── minimatch@3.0.4 deduped
  │ ├─┬ once@1.4.0
  │ │ └── wrappy@1.0.2 deduped
  │ └── path-is-absolute@1.0.1
  ├── globals@11.3.0
  ├── ignore@3.3.7
  ├── imurmurhash@0.1.4
  ├─┬ inquirer@3.3.0
  │ ├── ansi-escapes@3.0.0
  │ ├── chalk@2.3.1 deduped
  │ ├─┬ cli-cursor@2.1.0
  │ │ └─┬ restore-cursor@2.0.0
  │ │   ├─┬ onetime@2.0.1
  │ │   │ └── mimic-fn@1.2.0
  │ │   └── signal-exit@3.0.2
  │ ├── cli-width@2.2.0
  │ ├─┬ external-editor@2.1.0
  │ │ ├── chardet@0.4.2
  │ │ ├── iconv-lite@0.4.19
  │ │ └─┬ tmp@0.0.33
  │ │   └── os-tmpdir@1.0.2
  │ ├─┬ figures@2.0.0
  │ │ └── escape-string-regexp@1.0.5 deduped
  │ ├── lodash@4.17.5 deduped
  │ ├── mute-stream@0.0.7
  │ ├─┬ run-async@2.3.0
  │ │ └── is-promise@2.1.0
  │ ├── rx-lite@4.0.8
  │ ├─┬ rx-lite-aggregates@4.0.8
  │ │ └── rx-lite@4.0.8 deduped
  │ ├─┬ string-width@2.1.1
  │ │ ├── is-fullwidth-code-point@2.0.0
  │ │ └── strip-ansi@4.0.0 deduped
  │ ├── strip-ansi@4.0.0 deduped
  │ └── through@2.3.8
  ├── is-resolvable@1.1.0
  ├─┬ js-yaml@3.10.0
  │ ├─┬ argparse@1.0.10
  │ │ └── sprintf-js@1.0.3
  │ └── esprima@4.0.0
  ├── json-stable-stringify-without-jsonify@1.0.1
  ├─┬ levn@0.3.0
  │ ├── prelude-ls@1.1.2
  │ └─┬ type-check@0.3.2
  │   └── prelude-ls@1.1.2 deduped
  ├── lodash@4.17.5
  ├─┬ minimatch@3.0.4
  │ └─┬ brace-expansion@1.1.11
  │   ├── balanced-match@1.0.0
  │   └── concat-map@0.0.1
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├── natural-compare@1.4.0
  ├─┬ optionator@0.8.2
  │ ├── deep-is@0.1.3
  │ ├── fast-levenshtein@2.0.6
  │ ├── levn@0.3.0 deduped
  │ ├── prelude-ls@1.1.2 deduped
  │ ├── type-check@0.3.2 deduped
  │ └── wordwrap@1.0.0
  ├── path-is-inside@1.0.2
  ├── pluralize@7.0.0
  ├── progress@2.0.0
  ├─┬ require-uncached@1.0.3
  │ ├─┬ caller-path@0.1.0
  │ │ └── callsites@0.2.0
  │ └── resolve-from@1.0.1
  ├── semver@5.5.0
  ├─┬ strip-ansi@4.0.0
  │ └── ansi-regex@3.0.0
  ├── strip-json-comments@2.0.1
  ├─┬ table@4.0.3
  │ ├─┬ UNMET PEER DEPENDENCY ajv@6.2.0
  │ │ ├── fast-deep-equal@1.1.0 deduped
  │ │ ├── fast-json-stable-stringify@2.0.0 deduped
  │ │ └── json-schema-traverse@0.3.1 deduped
  │ ├── ajv-keywords@3.1.0
  │ ├── chalk@2.3.1 deduped
  │ ├── lodash@4.17.5 deduped
  │ ├─┬ slice-ansi@1.0.0
  │ │ └── is-fullwidth-code-point@2.0.0 deduped
  │ └── string-width@2.1.1 deduped
  └── text-table@0.2.0

npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0
```

Note: I omitted some unrelated messages about not having a `package.json` in the current directory.

</details>

**Comment by zkat** [comment]
alright, so, looking further into this: This is hitting an old bug (it was introduced with `npm@3`) where dependents of peerDeps get hoisted higher than an unhoistable peerDep.

The npm-side fix for this is.... non-trivial, which is partly why it's taken so long to fix. We basically need to completely rewrite the tree builder and change its architecture.

The workaround is more straightforward, and you have two options:

1. the big hammer that stops this from ever happening again is to use `npm install --legacy-bundling`, which generates `npm@2`-style trees -- the downside is that installs are slower, and you'll get full nesting on your tree, instead of the flat tree we've had since `npm@3`.

2. The smaller hammer is for you to play the numbers and make it so those nested peerDeps are hoistable. So, if you bump `ajv` to `ajv@6.2.0` for `eslint` itself so it's compatible with `table`'s, I think that should do the trick and it has the least impact.

**Comment by platinumazure** [comment]
Thanks @zkat. We do have PR #9856 (although I could tweak it to use the later version), but we need to check that it won't be a breaking change for our users since we use ajv wholesale in an important part of our API. Hopefully we can merge that in before too long.

**Comment by tr1s** [comment]
So what do I do in order to fix the warn? Do I just re-install eslint globally with this is merged?

screen shot 2018-02-27 at 9 42 56 pm

**Comment by not-an-aardvark** [comment]
Thanks for contributing!

**Comment by not-an-aardvark** [comment]
@tr1s We have a scheduled release on Friday (https://github.com/eslint/eslint/issues/9997), so the issue will be fixed at that point. In the meantime, you could try using `npm install --legacy-bundling` instead, or just ignoring the warning for now (it shouldn't cause any functionality issues).

**Comment by tr1s** [comment]
Cool thanks @not-an-aardvark

**Comment by mikermcneil** [comment]
See https://github.com/eslint/eslint/commit/6b71fd0bcbf9cc00ed4076587f5692b72f6e9aa5#commitcomment-28261398 and https://github.com/gajus/table/pull/60#discussion_r170164521

**Pull request merged**
