### PR TITLE
Fix: `no-warning-comments` cannot be set in a configuration comment

### LINKED ISSUE #3619: `no-warning-comments` cannot be set in a configuration comment
If you try to set `no-warning-comments` with `"location": "anywhere"` in a configuration comment, it itself is flagged as an error:

```js
/*eslint no-warning-comments: [2, { "terms": ["todo", "fixme", "any other term"], "location": "anywhere" }]*/

var x = 10;
```

Results:
```
1:1  error  Unexpected todo comment            no-warning-comments
1:1  error  Unexpected fixme comment           no-warning-comments
1:1  error  Unexpected any other term comment  no-warning-comments
```

### PR DESCRIPTION
**Pull request by BYK**
Fixes #3619

### CODE REVIEW

**Comment by ilyavolodin** [comment]
@BYK It looks like consensus that was reached in #3619 is slightly different then your implementation. Can you take a look?

**Comment by BYK** [comment]
@ilyavolodin updated per ticket. Sorry for the delay.

**Comment by gyandeeps** [comment]
Need a squash of commits.

**Comment by BYK** [comment]
@gyandeeps hah, thanks for the heads up. done.

**Comment by lo1tuma** [comment]
LGTM

**Pull request merged**
