### PR TITLE
Breaking: Stop checking JSX variable use, expose API instead (fixes #1911)

### LINKED ISSUE #1911: Using built-in tag via JSX literal incorrectly counts as variable usage
Minimal reproducing scenario:
```jsx
var div = 1;
React.render(<div />);
```
I would expect this to warn on unused `div` variable, but it does not.

React is in the process of removing the tag whitelist in JSX - it's slated to land in React 0.13 (facebook/react#2746).

The current rule is that JSX tags beginning with a lowercase character will transform to a string, and others will transform to a variable. I guess it's an open question whether this can be considered a part of the "JSX spec", or a react-specific implementation details

This logic to special-case tags that start with a lowercase character already exists in the no-undef rule, so the suggested fix is just to port this over to no-unused-vars.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9081978-using-built-in-tag-via-jsx-literal-incorrectly-counts-as-variable-usage?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

**Comment by nzakas** [comment]
Heads up to @yannickcr - this change is coming in 0.17.0 (today!).

**Comment by yannickcr** [comment]
Duly noted.

I'll update my plugin to use the new API.

**Comment by martijnvermaat** [comment]
With this PR, I get `no-unused-vars` errors for all React components that I use with JSX. Before, ESLint seemed to work just fine on jsx files.

Do I understand correctly that recognizing JSX component usage has been removed from ESLint proper and I should somehow use an ESLint plugin for my JSX files? Could somebody point me in the right direction?

**Comment by MoOx** [comment]
https://github.com/yannickcr/eslint-plugin-react

**Comment by martijnvermaat** [comment]
Ah thanks, this makes sense. For future reference, I now also see [this is mentioned in the release notes](http://eslint.org/blog/2015/03/eslint-0.17.0-released/#changes-to-jsx/react-handling) (on the ESLint blog, but not as clear in the changelog).

**Pull request merged**
