### PR TITLE
Chore: Use json5 for parsing json configs

### PR DESCRIPTION
**Pull request by caub**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[x] Add something to the core
[ ] Other, please explain:

json5 allow comments (like with the strip-comments package) but also trailing commas for example.

`.babelrc` supports json5 among others

It makes it easier to write an `.eslintrc`

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Hi, thanks for the PR. Can you open an issue for this proposal? We generally require an issue to be created for all enhancements to ESLint core (see [here](https://eslint.org/docs/developer-guide/contributing/pull-requests#getting-started)).

**Comment by platinumazure** [comment]
Unfortunately, we can’t accept pull requests that don’t follow our guidelines. I’m going to close this pull request now, but if you’d like to resubmit following our guidelines, we’ll be happy to review. (Specifically, we just need an issue for discussion. Once we see one, we could reopen this pull request. Thanks!)

**Comment by platinumazure** [comment]
Oh crap, I missed #9936. Sorry about this. Reopening.

**Comment by jehy** [comment]
If you really need comments in config, you can use .eslintrc.js file... I don't think that is really neccessary.

**Comment by caub** [comment]
editors like vscode provide autocompletion in `.eslintrc` / `.eslintrc.json` that's why it's by far my preferred format

**Comment by platinumazure** [comment]
Closing this as the corresponding issue has been closed.

**Pull request closed without merging**
