### PR TITLE
Fix: Enable full support to eslint-env comments (Fixes #2134)

### LINKED ISSUE #2134: "Use of future reserved word in strict mode" false positive with eslint-env es6
ESLint version: `0.17.1` (and 67936e0d571c613ac54f4097b4235e6411af0b79 gives the same results)

`foo.js`:
```js
/*eslint-env es6 */
let x = 42;
```

`.eslintrc`:
```json
{
    "ecmaFeatures": { "modules": true }
}
```

The false positive:
```
$ ./node_modules/.bin/eslint foo.js 

foo.js
  2:1  error  Use of future reserved word in strict mode

✖ 1 problem (1 error, 0 warnings)
```

### PR DESCRIPTION
**Pull request by ilyavolodin**
Refs #2134 There doesn't seems to be a way to unittest this code at all. Any suggestions?
Old code was also broken even for env rules. Somehow env globals work, but I can't figure out how...

### CODE REVIEW

**Comment by nzakas** [comment]
I'm not sure this is working the way we want - assign only works one level deep, so `rules` would end up being only want is in the environment, wouldn't it?

**Comment by nzakas** [comment]
I'd really like to see some tests that show both how it was broken and how the change fixes it.

**Comment by ilyavolodin** [comment]
Oh.. Sorry, I didn't realize assign was only one level deep. I'll change that to use merge config, I guess. In terms of tests, they only way I could think of for testing this is to write a code that will be specifically flagged by a rule in say node environment, and then turn on node environment through comments. I'll see if I can add that.

**Comment by ilyavolodin** [comment]
Ok, I added a test that succeeds now. However, after trying a few things, I determined that it's impossible to get `es6` environment to work correctly inline due to the fact that in order for us to get comments, we need to parse the code into AST first. So parsing happens before there's a chance to set the environment and enable ecmaFeatures. I see no way around that at all:-(
But at least this commit fixes a pre-existing issue where inline environments where not enabling rules at all. I'm not sure how valuable that is, since with 1.0.0 none of the environments will have an ability to set default rules anymore.

**Comment by nzakas** [comment]
Crap, that's a good point. Can you change the commit to say "refs" instead of "fixes"?

**Comment by ilyavolodin** [comment]
Done.

**Pull request merged**
