### PR TITLE
Fix: extend prefer-const fixer range to whole declaration (fixes #13899)

### LINKED ISSUE #13899: Bug: --fix ignores defined order and creates a JS error
**Tell us about your environment**

* **ESLint Version:** 6.8.0
* **Node Version:** 8.15
* **npm Version:** 6.4.1

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```
module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
        "prefer-const": "error",
        "no-undef-init": "warn"
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```
let foo= undefined; //foo is not reasigned so it will try to transform to const and keep initialization as undefined;
```

Eslint command:
```
node node_modules/eslint/bin/eslint.js --fix testfile.js
```

**What did you expect to happen?**
transform variable to constant but not remove the undefined init as it will become a constant.

**What actually happened? Please include the actual, raw output from ESLint.**
I have runned an autofix in a legacy code with more than 10k files. When it finds a variable that should be a constant (because it is not reasigned) and is initialized as ```undefined``` it fix the code transforming it to ```const foo;``` causing errors over the code. I tried to change the rules order to first turns it to a constant and them check the undefined init so it should be fixed (as per: https://eslint.org/docs/rules/no-undef-init). But is still happening.

**Are you willing to submit a pull request to fix this bug?**
Yes, need some guidance but I can do this :) 

eslint

### PR DESCRIPTION
**Pull request by snitin315**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Fixes https://github.com/eslint/eslint/issues/13899

### CODE REVIEW

**Comment by snitin315** [comment]
I'm not sure why the test case is failing although it is correctly converting
`let someFunc = () => { let a = 1, b = 2; foo(a, b) }` to `const someFunc = () => { const a = 1, b = 2; foo(a, b) }`
when I am testing manually.


https://user-images.githubusercontent.com/46647141/105633445-9f833b00-5e7e-11eb-90b1-ebf2ed245030.mp4

**Comment by mdjermanovic** [comment]
> I'm not sure why the test case is failing

There are overlapping ranges now, so the fixes cannot be applied in the same pass.

`RuleTester` runs only one pass, which in this case fixes the outer `let` only:

```js
const someFunc = () => { let a = 1, b = 2; foo(a, b) }
```

and compares the result of that single pass with the provided `output`.

Before this change, the ranges were not overlapping, so both `let`s could be fixed in the same pass.

>  although it is correctly converting
> `let someFunc = () => { let a = 1, b = 2; foo(a, b) }` to `const someFunc = () => { const a = 1, b = 2; foo(a, b) }`
> when I am testing manually.

`--fix` repeats linting up to 10 times if the code was auto-fixed, so the inner `let` gets fixed in the second pass.

**Comment by mdjermanovic** [comment]
The solution is to change the output in the failing test case, to:

```js
    output: "const someFunc = () => { let a = 1, b = 2; foo(a, b) }"
```

and it would be nice to also leave a comment that the inner `let` will be auto-fixed in the second pass.

**Comment by snitin315** [comment]
Thanks for the explanation @mdjermanovic. I have updated the test case.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by mdjermanovic** [comment]
Thanks for contributing!

**Comment by snitin315** [comment]
@mdjermanovicThanks for your review and help. Can you point me towards some more beginner-friendly issues where I can help?

**Pull request merged**
