### PR TITLE
Update: Allow $schema in config

### PR DESCRIPTION
**Pull request by yordis**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[x] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Allowed the usage of `$schema` in the configuration. This key is useful for some IDEs to find information about the schema of the JSON 🤷‍♂ 

**Is there anything you'd like reviewers to focus on?**

Make sure that I validated the key correctly

### CODE REVIEW

**Comment by yordis** [comment]
@kaicataldo could you give me a hand with this, please 🙏

**Comment by kaicataldo** [comment]
I'm not against this change if it helps folks! It looks like there's another PR [here](https://github.com/eslint/eslint/pull/12532), as well as an alternative proposal [here](https://github.com/eslint/eslint/issues/12010).

**Comment by kaicataldo** [comment]
Quick note: we generally require core changes to go through the RFC process outlined [here](https://github.com/eslint/rfcs/), but I personally think this is a small enough change that it might not warrant it. Let's see what the rest of the team thinks.

**Comment by g-plane** [comment]
I also agree that this is a small change.

**Comment by ilyavolodin** [comment]
Agree, this does not require RFC

**Comment by ilyavolodin** [comment]
I'll champion this. @eslint/eslint-team does anyone want's to support it?

**Comment by kaicataldo** [comment]
This has now been accepted.

**Comment by kaicataldo** [comment]
Thanks for contributing!

**Pull request merged**
