### PR TITLE
Chore: Fix typo in large.js

### PR DESCRIPTION
**Pull request by eltociear**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

#### What changes did you make? (Give an overview)
```
wether -> whether
```

### CODE REVIEW

**Review by samarmohan — APPROVED** [review]

**Review by aladdin-add — APPROVED** [review]
lgtm, but it's just a copy of jshint, not sure we want to maintain it. :)

**Comment by mdjermanovic** [comment]
> but it's just a copy of jshint, not sure we want to maintain it.

We accepted a similar change in the same file in https://github.com/eslint/eslint/pull/13204#discussion_r412501833, so it's probably ok (though I also think there is no need to change this particular file).

**Review by snitin315 — APPROVED** [review]

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

@eltociear can you please sign our [CLA](https://cla.js.foundation/eslint/eslint?pullRequest=14589) so we could merge this PR?

**Comment by eltociear** [comment]
@mdjermanovic thx!
I signed it!

**Comment by mdjermanovic** [comment]
Thanks for contributing!

**Pull request merged**
