### PR TITLE
chore: drop structuredClone polyfill for v9

### PR DESCRIPTION
**Pull request by bakkot**
I noticed this comment about a thing which could be removed and wanted to make sure it didn't get lost. Happy to close this if you don't want to worry about it.

~~This doesn't pass linting because `no-undef` claims that `structuredClone` is not defined, but I couldn't for the life of me figure out why. The `globals` package [has listed `structuredClone` in `node` since `13.12.0`](https://github.com/sindresorhus/globals/commit/48aeac3efdeee50db9f6d23de04b06eb00d3d6fb).~~ Fixed by upgrade to eslint-plugin-n, see below.

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

Removes a dependency which is no longer necessary in v9.

#### What changes did you make? (Give an overview)

Removed a polyfill.

### CODE REVIEW

**Comment by mdjermanovic** [comment]
> This doesn't pass linting because `no-undef` claims that `structuredClone` is not defined, but I couldn't for the life of me figure out why. The `globals` package [has listed `structuredClone` in `node` since `13.12.0`](https://github.com/sindresorhus/globals/commit/48aeac3efdeee50db9f6d23de04b06eb00d3d6fb).

@aladdin-add this seems to be related to `eslint-plugin-n`?

**Comment by aladdin-add** [comment]
> @aladdin-add this seems to be related to eslint-plugin-n?

Yes, will take a look later!


also, I'm change the pr title `"feat!"` => `"feat"`, as it's not a breaking change.

**Comment by mdjermanovic** [comment]
In the meantime, I think we can enable the global variable manually in this PR to make the linting pass.

https://github.com/eslint/eslint/blob/8792464ee7956af82dab582ca9ee59da596a608e/eslint.config.js#L100-L102

```diff
languageOptions: {
-    ecmaVersion: "latest",
+    ecmaVersion: "latest",
+    globals: {
+       structuredClone: "readonly"
+    }
},
```

**Comment by mdjermanovic** [comment]
Okay, this works now with the new version of eslint-plugin-n, there's no need to update our eslint.config.js.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Would like @nzakas to verify before merging.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
