### PR TITLE
Docs: References correct config file name

### PR DESCRIPTION
**Pull request by pckilgore**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CxONTRIBUTING.md).
- [x] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

From eslint/website#693

According to the `configuration.md` page, the `.eslintrc` file format has been deprecated, and the `--init` option will generate either a `.yml`, `.js`, or `.json` file depending on what you pick in the initialization wizard.

This commit syncs the getting-started instructions with the configuration instructions.

#### Is there anything you'd like reviewers to focus on?

`{}` syntax may be confusing, I'm certainly not wedded to it but I am used to it.

### CODE REVIEW

**Comment by kaicataldo** [comment]
Two things:

1. Can you confirm you have read the contributing docs?
2. I'm not sure why the commit message is failing...Does someone else see what's wrong?

**Comment by pckilgore** [comment]
Read the guidelines, forgot to check.  If you don't know why your linter doesn't like my commit message then I'm probably not going to be helpful other than to point out that it's probably not a helpful rule 🙃

**Comment by mdjermanovic** [comment]
I think it's failing because the commit message starts with a space.

**Comment by kaicataldo** [comment]
Ha, good catch. GitHub doesn't render the whitespace, but it looks like that is the case here. Thanks!

**Comment by kaicataldo** [comment]
Thanks for contributing!

**Pull request merged**
