### PR TITLE
allow plugins to be namespaced fixes #2360

### LINKED ISSUE #2360: Not allowing private NPM plugins to be added.
I'm trying to add a namespaced plugin for example `@eslint/eslint-plugin-custom-rules`, however, eslint is requiring that all plugins are prefixed with `eslint-plugin-`.

I am using `v0.19.0`. I will submit a PR shortly.

### PR DESCRIPTION
**Pull request by sethpollack**
This PR allows plugins to be namespaced, allowing the use private npm plugins.

### CODE REVIEW

**Comment by nzakas** [comment]
This looks like a good start. Please take a moment to read over our contributor guide: http://eslint.org/docs/developer-guide/contributing

We have a specific format for our commit messages and need you to sign our CLA: http://eslint.org/cla

Also, can you update the plugins documentation to specifically mention scoped packages?

**Comment by sethpollack** [comment]
Ok, is this better?

**Comment by nzakas** [comment]
Yup, looks good. Thanks!

**Comment by sethpollack** [comment]
Thanks!

**Pull request merged**
