### PR TITLE
Update: added node type based support to `space-before-function-paren`

### PR DESCRIPTION
**Pull request by twolfson**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What rule do you want to change?**

[space-before-function-paren](http://eslint.org/docs/rules/space-before-function-paren)

**Does this change cause the rule to produce more or fewer warnings?**

Neither, alternative options object

**How will the change be implemented? (New option, new default behavior, etc.)?**

New options object

**Please provide some example code that this change will affect:**

```js
// Can't have independent spacing settings for these currently
// The new options allow setting specifically for FunctionDeclaration and FunctionExpression
function foo() {}
[].forEach(funciton foo () {});
```

**What does the rule currently do for this code?**

It doesn't support independent control for function declarations vs expressions

**What will the rule do after it's changed?**

It supports independent control for function declarations vs expressions

**What changes did you make? (Give an overview)**

- Added alternative object syntax to rule (based on `one-var` alternative syntax)
- Added tests
- Added docs including links to corresponding JSCS rules

**Is there anything you'd like reviewers to focus on?**

I feel like I might have added too much new documentation. Let me know if you want me to cut it down

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the pull request!

Could you elaborate on why an option like this would be useful? My concern is that this seems like a very user-specific preference, so it might be better as part of a plugin rather than the core rule.

**Comment by twolfson** [comment]
Sure thing! I guess my reasoning is that it was a long standing option on JSCS via:

- [disallowSpacesInFunctionExpression](http://jscs.info/rule/disallowSpacesInFunctionExpression)
- [requireSpacesInFunctionExpression](http://jscs.info/rule/requireSpacesInFunctionExpression)
- [disallowSpacesInFunctionDeclaration](http://jscs.info/rule/disallowSpacesInFunctionDeclaration)
- [requireSpacesInFunctionDeclaration](http://jscs.info/rule/requireSpacesInFunctionDeclaration)

As a result, if it was popular enough to keep on JSCS, then it should probably be a core rule on ESLint as well. Case in point, a quick search shows 109k results for `requireSpacesInFunctionExpression` alone:

https://github.com/search?q=requireSpacesInFunctionExpression&type=Code&utf8=%E2%9C%93

For reference, `space-before-function-paren` seems to be at 79k itself:

https://github.com/search?utf8=%E2%9C%93&q=space-before-function-paren&type=Code

**Comment by platinumazure** [comment]
We do strive for JSCS compatibility (to a point, of course). If this is a missing compatibility item, I think we should accept this.

**Comment by twolfson** [comment]
Any word on this PR? It's been a few months =/

**Comment by twolfson** [comment]
Closing issue due to inactivity and loss of interest on my end

**Pull request closed without merging**
