### PR TITLE
Fix: Correct error and test messages to fit config search path

### PR DESCRIPTION
**Pull request by jrpool**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Corrected error message and test description so they no longer exclude home-directory config files from set of directories searched for config files.

**Is there anything you'd like reviewers to focus on?**
The change to the test description is intended to be temporary, pending a change of the test to make it ignore config files in the user’s home directory. If reviewers have any reservations about the idea of making that change to the test and, along with it, restoring the original description, I would appreciate their comments on that.

### CODE REVIEW

**Comment by kaicataldo** [comment]
Thanks for the PR! Do you mind explaining what the problem is that you're trying to solve with this PR?

**Comment by not-an-aardvark** [comment]
@kaicataldo I think this is related to the discussion in https://github.com/eslint/eslint/pull/9426.

**Comment by jrpool** [comment]
This PR arises from comments on my merged PR #9426 by @platinumazure and @not-an-aardvark. The search for config files ends with a search in the user’s home directory if no others are found, but the error message and test description make it seem as if that does not happen. This can lead to confusion about why the test is failing. This PR aims to prevent that confusion by more fully describing the search.

**Comment by kaicataldo** [comment]
Understood - thanks!

**Comment by kaicataldo** [comment]
> If reviewers have any reservations about the idea of making that change to the test and, along with it, restoring the original description, I would appreciate their comments on that.

I think this is fine as an intermediary step, since it accurately describes what is going on.

**Comment by kaicataldo** [comment]
Thanks for contributing to ESLint!

**Pull request merged**
