### PR TITLE
docs: Add base href to each page to fix relative URLs

### LINKED ISSUE #15844: [new docs site] relative links on URLs with and without a trailing slash
### Environment

`main` branch, `npm start` in the `docs` directory.

### What parser are you using?

Default (Espree)

### What did you do?

Open USER GUIDE > Rules > no-cond-assign. Then, in the Related Rules section click no-extra-parens link.

### What did you expect to happen?

To open no-extra-parens document.

### What actually happened?

The link is broken as it points to `rules/no-cond-assign/no-extra-parens`.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This is caused by writing `rules/no-cond-assign.md` to `rules/no-cond-assign/index.html`, unlike the current site where it is `rules/no-cond-assign.html`. The path on the new site is `rules/no-cond-assign/` (with `/` at the end) as opposed to the current site where it is `rules/no-cond-assign` (without `/` at the end) so the relative links in the document are broken.

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

This adds `<base>` to each page so relative URLs work correctly.

Fixes #15844

#### Is there anything you'd like reviewers to focus on?

Please double-check the deploy preview because this can't really be tested locally.

### CODE REVIEW

**Review by mdjermanovic — COMMENTED** [review]
This breaks UI in deploy previews, too. Maybe we should add `<base>` only in production builds?

**Comment by nzakas** [comment]
Hmmm, that will make it impossible to know if there’s a problem until we push live, as we can’t really test locally either. There must be a way to make this work for deploy preview that will give us confidence that it will work live.

**Comment by nzakas** [comment]
So this is a cross-origin fetch error, because the base URL is for `eslint.org`, we can't load stuff from the deploy preview URL. Looking at this.

**Comment by mdjermanovic** [comment]
In deploy previews, if `href` in `<base>` is an absolute URL then it would have to match the real one, i.e. to start with `https://deploy-preview-16046--docs-eslint.netlify.app/` for PR number 16046. Otherwise, all resources (css, js...) would be pulled from elsewhere, because `<base>` applies to everything. Per the MDN docs `href` in `<base>` can be relative, but I'm not sure if that would be representative for testing either.

**Comment by mdjermanovic** [comment]
We could maybe try with domain-relative URLs in `href` regardless of the context.

**Comment by nzakas** [comment]
Turns out you can use a relative base URL, and that will work everywhere. :tada:

**Review by mdjermanovic — APPROVED** [review]
LGTM! I don't see anything wrong in the deploy preview.

But the preview is doing trailing slash redirects, so it seems that the only way to find out if this fixes the issue is to merge and test with proxying on `https://eslint.org/docs/head/`.

**Review by snitin315 — APPROVED** [review]
Let's try this in prod 🚀

**Comment by mdjermanovic** [comment]
This seems to work well! I checked relative links on https://eslint.org/docs/head/user-guide/configuring and they are good now, unlike the links on the current https://eslint.org/docs/latest/user-guide/configuring page.

The only thing that looks a bit unusual on non-canonical URLs is that anchor-only links (`href="#..."`, e.g., the links in Table of Contents) are now pointing to the canonical URL, so they'll open another page instead of just scrolling the current page. I think this is okay.

**Pull request merged**
