### PR TITLE
feat: public FlatESLint nodejs API

### PR DESCRIPTION
**Pull request by ZerdoX-x**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other: Flat config is being public and being easy to migrate to for about a year. But there is an issue: when you opt in flat config, you cannot use nodejs API anymore.

#### What changes did you make?
Just a single line of code making some part of API public. Flat config is being public in CLI, docs and probably other parts for a long time, but not in NodeJS API.

#### Is there anything you'd like reviewers to focus on?

My usecase: https://stackoverflow.com/a/73818629/11858171
```
import { FlatESLint } from "eslint";

async function removeIgnoredFiles(files) {
	const eslint = new FlatESLint();
	const ignoredFiles = await Promise.all(
		files.map((file) => eslint.isPathIgnored(file)),
	);
	const filteredFiles = files.filter((_, i) => !ignoredFiles[i]);
	return filteredFiles.join(" ");
}

function buildEslintCommand(commandToRun) {
	return async (stagedFiles) => {
		const stagedAndNotIgnoredFiles = await removeIgnoredFiles(stagedFiles);
		return `${commandToRun} ${stagedAndNotIgnoredFiles}`;
	};
}

export default {
	"*.{svelte,?(m|c)(j|t)s}": [buildEslintCommand("pnpm lint:_eslint")],
};
```

### CODE REVIEW

**Comment by ZerdoX-x** [comment]
Could you please clarify, which type of contributor I am? I've never seen stuff like this and not sure what is the right answer in our case.

Am I Individual or Corporate Contributor?

**Comment by aladdin-add** [comment]
it's exported in `unsupported-api`: https://github.com/eslint/eslint/blob/9d4216d638d39844decffac33ee3d5a47413c80a/lib/unsupported-api.js#L25

you can use like this:
```js
const { FlatESLint } = require("eslint/use-at-your-own-risk");
```

**Comment by mdjermanovic** [comment]
@ZerdoX-x thanks for the PR, but we can't accept this change. `FlatESLint` is intentionally not in the NodeJS API. In v9.0.0, `ESLint` will be the current `FlatESLint` class. 

As noted in https://github.com/eslint/eslint/pull/17490#issuecomment-1689269652, you can access `FlatESLint` through `eslint/use-at-your-own-risk`.

**Comment by ZerdoX-x** [comment]
Oh, I see. Thank you. But sadly I cannot use it because it is not ESM compatible. Even tho I can still import from `eslint` because it's listed in `package.json` as `package.main`, so I'll stick with my patched package until eslint 9

**Comment by aladdin-add** [comment]
all cjs modules are esm-compatible, you just need to deconstruct:

```js
import eslint from "eslint/use-at-your-own-risk";

const { FlatESLint } = eslint;
```

**Comment by ZerdoX-x** [comment]
@aladdin-add did not know about this trick, thank you, all good now

**Pull request closed without merging**
