### PR TITLE
Updating migration guide for single-line disable

### PR DESCRIPTION
**Pull request by justinhelmer**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

The multiline comment string doesn't seem to work.

Main docs page is right; JSCS migration guide appears to be wrong.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by justinhelmer** [comment]
[as requested](https://github.com/eslint/eslint.github.io/pull/419)

**Comment by platinumazure** [comment]
Thanks! Can you please sign our Contributor License Agreement?

**Comment by ilyavolodin** [comment]
@justinhelmer just a friendly ping. Could you sign our CLA? Unfortunately we can't merge anything without a signed CLA.

**Comment by kaicataldo** [comment]
@justinhelmer Friendly ping. We'd love to land this, but we unfortunately can't until the CLA is signed.

**Comment by justinhelmer** [comment]
I signed this way back.

**Comment by justinhelmer** [comment]
The status in the comment is incorrect, it was signed a long time back

**Comment by kaicataldo** [comment]
@kborchers Hi! Any idea what might be going on here re the CLA bot?

**Comment by kborchers** [comment]
The commit was made by an account that GitHub doesn't recognize so this was either done with a different account that was deleted or something was done to the commit that edited the author information so it can't be tied to @justinhelmer.

**Comment by Aladdin-ADD** [comment]
oh, I have been encountered it before(my first contribution to ESLint 😄 ). 
maybe it's because your git configed email has not been added in github. could you please check it? @justinhelmer 

image

**Comment by platinumazure** [comment]
@justinhelmer Have you had a chance to look into the CLA issue, using the information provided [here](https://github.com/eslint/eslint/pull/9385#issuecomment-338507230) and [here](https://github.com/eslint/eslint/pull/9385#issuecomment-339402944)?

**Comment by justinhelmer** [comment]
@platinumazure apologize for not getting back sooner, I have been out of town.

I added my work email, hoping it will solve the problem

**Comment by justinhelmer** [comment]
The CLA assistant continues to show it signed, but it doesn't allow me to change emails. Let me know if there is any other action I need to take.

**Comment by platinumazure** [comment]
Closing/reopening the pull request seems to have fixed the CLA status. Now the only issue is the commit message (should just start with "Docs:"). Maybe we could take care of that on merge, but if you do get a chance to amend the commit summary, that would be super awesome. Thinks!

**Comment by justinhelmer** [comment]
done. Sorry for the delay

**Comment by justinhelmer** [comment]
Done!

**Comment by platinumazure** [comment]
Thank you! This looks good to me, I'll go ahead and merge shortly. Thanks so much for your patience on this!

**Pull request merged**
