### PR TITLE
fix typo (then -> than)

### PR DESCRIPTION
**Pull request by mourner**

### CODE REVIEW

**Comment by gyandeeps** [comment]
Please format your commit message as per our guidelines: http://eslint.org/docs/developer-guide/contributing

**Comment by mourner** [comment]
@gyandeeps do I have to create an issue for a typo just to reference it in the commit message?

**Comment by gyandeeps** [comment]
In your case a issue is not required.

**Comment by mourner** [comment]
@gyandeeps OK, updated.

**Pull request merged**
