### PR TITLE
Update: Make no-cond-assign work for ternaries (fixes #10091)

### LINKED ISSUE #10091: Make `no-cond-assign` work for ternaries too
**What rule do you want to change?**

`no-cond-assign`

**Does this change cause the rule to produce more or fewer warnings?**

More warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**

I guess new default?

**Please provide some example code that this change will affect:**

```js
  const str = (x = 0) ? 'zero' : 'non-zero'
```

**What does the rule currently do for this code?**

No warnings are produced

**What will the rule do after it's changed?**

Produce an "Unexpected assignment" warning for the condition of the ternary

### PR DESCRIPTION
**Pull request by goodoldneon**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Addresses issue https://github.com/eslint/eslint/issues/10091

**What changes did you make? (Give an overview)**
Made the `no-cond-assign` rule also check for ternaries.

### CODE REVIEW

**Comment by goodoldneon** [comment]
How do I change the commit message? Do I amend my commit, then force push? Or will that screw up the pull request? Sorry for the dumb question. This is my first pull request.

**Comment by platinumazure** [comment]
That's a great question, thanks for asking (and congratulations on your
first pull request). You can amend and force-push, which will satisfy our
status check. Optionally, you can edit the PR title separately for
consistency, but that's not required.

**Comment by goodoldneon** [comment]
I also forgot to add a valid test. Should I add the following line to the `valid` array, and then make a new commit?

`"var x; var b = (x === 0) ? 1 : 0;"`

**Comment by platinumazure** [comment]
That would be great. You might not need the `var x` since our rule tests
don't care about unresolved global variables. Either way is fine.

**Comment by goodoldneon** [comment]
Pushed a new commit. Is everything OK on my end?

**Comment by platinumazure** [comment]
I think so, I'll review properly later tonight. Thanks for your flexibility!

**Pull request merged**
