### PR TITLE
New: Rule - 'lines-between-class-methods' (fixes #5949)

### LINKED ISSUE #5949: Proposed Rule: Enforce lines between class methods
I would like to propose a rule that enforces empty lines between class functions. When enabled and set to "always" it should make sure that there is at least one empty line between every method in a class declaration. If set to "never" the opposite would be true, that is, there should not be any empty lines at all between class methods.

A line with a comment on should not count as an empty line.

This rule should not concern itself with the class padding (empty lines before the first method and after the last method) since that is already taken care of by `padded-blocks`.

It also shouldn't concern itself with how many empty lines that are present, since that is a job for `no-multiple-empty-lines`.

This is a stylistic rule.

The following patterns would be considered problems:

``` javascript
class Test1 {
  constructor () {
    // ...
  }
  otherFunc () {
    // ...
  }
}

class Test2 {
  constructor () {
    // ...
  }
  // comment
  otherFunc () {
    // ...
  }
}
```

The following pattern would be considered valid:

``` javascript
class Test3 {
  constructor () {
    // ...
  }

  otherFunc () {
    // ...
  }
}

class Test4 {
  constructor () {
    // ...
  }



  otherFunc () {
    // ...
  }
}

class Test5 {
  constructor () {
    // ...
  }

  // comment
  otherFunc () {
    // ...
  }
}

class Test6 {
  constructor () {
    // ...
  }

  // Comment

  otherFunc () {
    // ...
  }
}
```

### PR DESCRIPTION
**Pull request by LinusU**
This is the first time I'm writing a rule for eslint so please take an extra hard look so that I don't screw anything up :)

Things to do:
- [x] Bikeshed name
- [x] Handle comments

**Edit:**
Handled comments, changed the name and squashed everything into one commit.

Should be ready for review now 🙌 

If anyone is interested in the separate commits, here they are: https://github.com/LinusU/eslint/tree/class-padding-history

### CODE REVIEW

**Comment by nzakas** [comment]
Marking as "do not merge" because the issue isn't accepted yet

**Comment by LinusU** [comment]
@nzakas The issue has been updated to "Accepted" now. Is there anything that I should do at this point?

**Comment by ilyavolodin** [comment]
Issue is now accepted. Removing "do not merge". @LinusU no, you don't need to do anything yet. We'll code review this and leave you feedback if anything needs to be updated. (It's going to be a little while before we get to this, due to the fact that we are focused on fixing issues with the last release at the moment).

**Comment by LinusU** [comment]
No stress, thank you for the fast response :)

**Comment by ilyavolodin** [comment]
LGTM. You might want to make this rule fixable. Should be pretty easy, since it's just whitespace fixing. Although you might run into trouble with comments.

**Comment by nzakas** [comment]
There's an open discussion about whether this should be folded into a more general rule about lines after block statements: https://github.com/eslint/eslint/issues/3092

**Comment by LinusU** [comment]
Rebased on master, any updates on this?

**Comment by vitorbal** [comment]
Hi @LinusU, could you make sure the rule adheres to the new rule format that was introduced since you first submitted the PR? More information about the new format can be found here:
http://eslint.org/docs/developer-guide/working-with-rules

Also, we recently switched the `no-var` rule on for our codebase so it looks like you got a couple of linting errors because of that as well.

**Comment by vitorbal** [comment]
@LinusU Just to make sure it's still clear: as @nzakas mentioned, until the discussions in #3092 finish, we can't merge this yet.
Thank you for your understanding!

**Comment by kaicataldo** [comment]
We've actually consolidated the original issue and a few others into one issue (all dealing with padding blocks with newlines) here: https://github.com/eslint/eslint/issues/7356

Really appreciate all the work you did on this rule - we're still trying to decide exactly how we want to proceed. Feel free to join in on the discussion.

**Comment by kaicataldo** [comment]
On a side note - it doesn't look like we're going to be going with a separate rule implementation (though nothing is set in stone yet) specifically for lines between class methods, so chances are we won't be able to merge the PR in its current state.

**Comment by kaicataldo** [comment]
Ah, looks like there's another PR for this same issue: https://github.com/eslint/eslint/pull/6445

**Comment by alberto** [comment]
Closing this as we decided to go with a different rule proposal: https://github.com/eslint/eslint/issues/7356#issuecomment-280104767

We appreciate your work here @LinusU and we hope you can keep contributing to eslint. Things don't usually take this long to get sorted out.

**Comment by kaicataldo** [comment]
Thanks @LinusU for your contribution!

**Pull request closed without merging**
