### PR TITLE
Added a way to not document return statement if it matches a pattern

### PR DESCRIPTION
**Pull request by Telokis**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What rule do you want to change?**
`valid-jsdoc`

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option to allow the rule to be less restrictive if needed.

**Please provide some example code that this change will affect:**

```js
/**
 * Description
 * @param {function} callback mytest
 */
 function asyncFunc(callback){
    if (false) {
        return callback(null); // If this line matches the option, this snippet won't report.
    }
  };
```

**What does the rule currently do for this code?**
It always report if there is a non-documented `return` statement in a function.

**What will the rule do after it's changed?**
It will only report if the non-documented `return` statement **DOES NOT** match the pattern of the option `matchReturnOptional`

**What changes did you make? (Give an overview)**
Added an option to allow a rule to be less restrictive if needed.

**Is there anything you'd like reviewers to focus on?**
I'm not entirely sure about the name for the new option (`matchReturnOptional`)

### CODE REVIEW

**Comment by ilyavolodin** [comment]
What is the purpose of relaxing the rule so much? Could you provide a reason why you want to not document return statements in this case? Keep in mind, some people don't read documentation in the code, but generate documentation out of the code and read it separately.

**Comment by Telokis** [comment]
If eslint wants to be configurable, it should provide a way for anyone to allow/disallow specific things, that's the purpose of options. The fact that eslint if enforcing `return`s documentation makes no sense in the context of asynchronous programming based on callbacks where `return` is used to stop the function from proceeding any further.

The main reason is "I need it and eslint doesn't provide it".

**Comment by not-an-aardvark** [comment]
Thanks for the pull request!

Hmm, I'm unconvinced that this is useful enough to be worth adding to the core rule. Personally, I would say that it makes more sense to avoid returning the result of a callback in this case, because otherwise it might appear that the return value is getting used, which doesn't seem to be the case.

> If eslint wants to be configurable, it should provide a way for anyone to allow/disallow specific things, that's the purpose of options.

> The main reason is "I need it and eslint doesn't provide it".

It's true that some ESLint rules have options to allow for different styles. However, we don't aim to support every possible behavior that a user could want, as supporting very uncommon and user-specific preferences would not be worth the maintenance effort. Instead, we encourage users to create custom rules or plugins so that they can use ESLint to enforce any behavior they choose. 

Therefore, "I need it and eslint doesn't provide it" is not, on its own, a sufficient justification for adding an option to a core rule. We can evaluate this proposal and decide whether it's worth adding, but there is a possibility that we will decide not to add it, in which case you are free to implement it yourself in a custom rule and distribute it as a plugin.

**Comment by Telokis** [comment]
Thanks for the feedback.
I'd be glad to add a plugin but this seem to be a very very **very** small change to incorporate into a plugin.
In fact, returning the call to the callback is a design quite common. You can even see [Async doing it here](https://github.com/caolan/async/blob/49119a895d64991375d1a7b82b3a4d71e3ec8681/lib/during.js#L46)

Moreover, isn't this such a small modification that it doesn't require any maintenance whatsoever? I don't really know the code well but it seems to be quite an isolated addition.

**Comment by not-an-aardvark** [comment]
Thanks again for the pull request! Unfortunately, it looks like this proposal didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful.

**Pull request closed without merging**
