### PR TITLE
Docs: Clarify parameter documentation for `api.verify`

### LINKED ISSUE #5101: linter.verify() params documentation incorrect
In [`nodejs-api.md`](https://github.com/eslint/eslint/blob/a9fccf41e5f12610c1c358c86d996c4a28ba3223/docs/developer-guide/nodejs-api.md) it says:

> This method accepts four arguments:

But only enumerates 3 parameters. Inspecting the [source code and comments](https://github.com/eslint/eslint/blob/a9fccf41e5f12610c1c358c86d996c4a28ba3223/lib/eslint.js#L644-L657) reveals these differences from what's documented:

* It accepts 3-4 arguments.
* # 3 can be an options object or filename string.
* If # 3 is an object, the value of `saveState` is taken from its prop of the same name. Otherwise its the value of arg # 4 (if passed).

When this is updated it might make more sense to just enumerate the params and their optionality rather than stating the number literally.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30349384-linter-verify-params-documentation-incorrect?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #5104: linter.verify() `config` param under- / mis-documented
The [`linter.verify()` docs](https://github.com/eslint/eslint/blob/a9fccf41e5f12610c1c358c86d996c4a28ba3223/docs/developer-guide/nodejs-api.md#linter) provide no explanation of what `config` consists of, and the [source code docs](https://github.com/eslint/eslint/blob/2436cc6c1816a7890e35dab38e609daee84d7530/lib/eslint.js#L591) are incorrect:

> @param {Object} config An object whose keys specify the rules to use.

Please consider:

* Updating the source code docs for 1.x and 2.x to be accurate.

* Updating the end user docs to explain what it consists of. I'm guessing it's a subset of the `CLIEngine` opts. I haven't checked, but I assume the `verify()` docs really mean it when they say "It doesn't do any filesystem operations" (and a later example on the page supports that), meaning that options like `configFile|useEslintrc` wouldn't be applicable.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30363242-linter-verify-config-param-under-mis-documented?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BYK**
(fixes #5101) (fixes #5104)

### CODE REVIEW

**Comment by gyandeeps** [comment]
@byk can u plz put the `fixes xxxx` on first line of commit message as it wont come out correctly when generating docs?
Build passes because it checks for fixes in the whole commit message rather it should check for fixes in first line.

**Comment by BYK** [comment]
@gyabdeeps that's what I did first and then I got yelled at by the 72-char rule.

**Comment by gyandeeps** [comment]
This would do it
`Docs: Clarify docs for api.verify (fixes #1234, fixes #1234)` for now.
Usually what i do is put one issue number in 1st line and rest in other lines.

**Comment by BYK** [comment]
@gyandeeps - gotcha, good advice :) Updated!

**Comment by gyandeeps** [comment]
LGTM. Thanks @BYK

**Pull request merged**
