### PR TITLE
docs: update semi-style documentation

### PR DESCRIPTION
**Pull request by CzarOfScripts**
Corrected example with "first" option

#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

- [X] Documentation update
- [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
- [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
- [ ] Add autofix to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)
I corrected the example for the "first" option, it was incorrect.

#### Is there anything you'd like reviewers to focus on?
No

### CODE REVIEW

**Comment by Tanujkanti4441** [comment]
Thanks for contributing! Can you also sign  CLA?

**Comment by CzarOfScripts** [comment]
> Thanks for contributing! Can you also sign CLA?

To be honest, I haven't quite figured out how to do this.

**Comment by Tanujkanti4441** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/19114526/11061773/17776/#/?version=2)
> 
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/19114526/11061773/17776/#/?version=2) - login: @CzarOfScripts / name: Oliver Patterson . The commit ([bb9cd23](https://github.com/eslint/eslint/commit/bb9cd23bca1ec142938dbe6fe551805757165d55)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/19114526/11061773/17776/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

From here you can get the link

**Comment by CzarOfScripts** [comment]
> > [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/19114526/11061773/17776/#/?version=2)
> > 
> > * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/19114526/11061773/17776/#/?version=2) - login: @CzarOfScripts / name: Oliver Patterson . The commit ([bb9cd23](https://github.com/eslint/eslint/commit/bb9cd23bca1ec142938dbe6fe551805757165d55)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/19114526/11061773/17776/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).
> 
> From here you can get the link

I saw it, but I didn't understand what to write in "Mailing address".

**Comment by Tanujkanti4441** [comment]
>I saw it, but I didn't understand what to write in "Mailing address".

Enter your email address

**Comment by Tanujkanti4441** [comment]
I think the code example for `first` option in `semi-style` is already correct.
as you can see in the deploy preview of this PR by opening them in playground.
https://deploy-preview-17776--docs-eslint.netlify.app/rules/semi-style

The `incorrect` one are now don't have any errors and `correct` one are showing errors which must be vice-versa.

**Pull request closed without merging**
