### PR TITLE
Fix: fix writing config file when `source` is `prompt`

### PR DESCRIPTION
**Pull request by g-plane**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix

**What changes did you make? (Give an overview)**
When running `eslint --init`, if the user chooses `prompt` mode, write the config file with corresponding format.

### CODE REVIEW

**Comment by g-plane** [comment]
@platinumazure Do you mean write some tests to mock the user input and assert the output?

**Comment by platinumazure** [comment]
Yes, something like that. It would be nice to show that we never format the
configuration file with an undefined format, if possible.

**Comment by g-plane** [comment]
I'm not sure whether we can do some fake inputs to `inquirer`, but I will try in another PR.

**Comment by g-plane** [comment]
@platinumazure I don't know how to test this behavior. I have tried to pass some inputs through stdin but it didn't work.

**Comment by kaicataldo** [comment]
I'm not sure I understand what this PR is fixing. Mind explaining, maybe with an example?

**Comment by g-plane** [comment]
@kaicataldo Here is the reproduction steps:
1. Run `npm i -g eslint@5.0.0-alpha.4`
2. Run `eslint --init`
3. Choose "Answer questions about your style"
4. Anwser the rest questions **except the last one**
5. Choose JSON format or YAML format
6. You'll notice that ESLint generates `.eslintrc.js` though you have chosen JSON or YAML

So, this PR fixes this behavior.

**Comment by platinumazure** [comment]
@kaicataldo I assume your concerns are addressed?

**Comment by kaicataldo** [comment]
Please don’t block this on my account - I just wanted to understand what the change was :)

**Pull request merged**
