### PR TITLE
Breaking: Update `ignore` to v5

### LINKED ISSUE #13294: Upgrade ignore to 5.x?
**The version of ESLint you are using.**

7.0.0

**The problem you want to solve.**

The latest eslint still uses `ignore@^4.0.6`, but the latest version of `ignore@5.1.3` solves many known issues.
- .gitignore(.eslintignore) rules should always check paths that are relative to some directory which is usually the base dir of .gitignore file or the root directory of a repo. ignore <= 5 actually DONT KNOWN whether a pathname should be ignored if it is an absolute path.
- and also improves perf
- fixes some windows issues.

For details, we could check [releases](https://github.com/kaelzhang/node-ignore/releases)

**Are you willing to submit a pull request to implement this change?**

I'd like to help.

I submit this issue in order to discuss the necessarity whether we should do an upgrade which might introduce quite a few changes.

### PR DESCRIPTION
**Pull request by bmish**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[X] Other, please explain:

#### What changes did you make? (Give an overview)

Update dependency.

https://github.com/kaelzhang/node-ignore/releases/tag/5.0.0

Fixes #13294.

#### Is there anything you'd like reviewers to focus on?

No.

### CODE REVIEW

**Comment by aladdin-add** [comment]
related: https://github.com/eslint/eslint/issues/13294.

As a breaking change, it seems an enjoyable time to upgrade it as eslint v8.0.0.

**Review by snitin315 — APPROVED** [review]

**Review by mdjermanovic — COMMENTED** [review]
Can you provide an overview of breaking changes for ESLint users? This wasn't [announced](https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0) for v8.0.0, so it seems like the change would have to wait until v9.0.0.

**Comment by bmish** [comment]
@mdjermanovic It looks like the potential breaking change is that ignore v5 will throw an exception if an invalid path is passed to our `no-restricted-imports` or `no-restricted-modules` rules. If we can't include this breaking change in this release, then I could investigate catching the exception in our two rules so that the upgrade would not be a breaking change (as discussed in https://github.com/eslint/eslint/issues/13294). If there isn't time for that, we could target it for v9 instead.

**Comment by nzakas** [comment]
If the change just affects a couple of rules, I think we can include this in v8.0.0. We don't announce all changes to all rules ahead of time, and we can add this into the release notes.

**Comment by bmish** [comment]
@nzakas sounds good, I'd be in favor of including this change in v8 then.

**Comment by bmish** [comment]
I'm moving this PR back to draft since I've identified some missing test cases that it breaks for the `no-restricted-imports` / `no-restricted-modules` rules:

* `import relativeWithPatterns from '../foo';` when using `no-restricted-imports` rule with the `patterns` options
* `import absoluteWithPatterns from '/foo';` when using `no-restricted-imports` rule with the `patterns` options
* `var relativeWithPatterns = require('../foo');` when using `no-restricted-modules` rule with the `patterns` options
* `var absoluteWithPatterns = require('/foo');` when using `no-restricted-modules` rule with the `patterns` options

I'm going to add the missing test cases to the rules in https://github.com/eslint/eslint/pull/14910 to ensure they aren't mistakenly broken going forward. After that, we can reevaluate if it's possible to pull off this upgrade.

**Comment by mdjermanovic** [comment]
Note that [`@eslint/eslintrc`](https://github.com/eslint/eslintrc/blob/be0f70dacaa3ea1f0f606d240e5f63435b34810e/package.json#L71), which is still a dependency, also uses the `ignore` package, so we'll have two different version installed (ignore v4 for eslintrc, ignore v5 for ESLint).

**Comment by nzakas** [comment]
Should we upgrade eslintrc and/or not upgrade here?

**Comment by bmish** [comment]
> Should we upgrade eslintrc and/or not upgrade here?

Ideally, we would upgrade in both places of course, but I haven't yet found a way to upgrade here without breaking important test cases for these two rules. If we don't find a safe upgrade path in the coming days, it should be okay to have a different version in each package.

**Comment by aladdin-add** [comment]
Given these cases are very edge (not well tested and documented), I was wondering how many users were really using the "feature".  What do you think just removing the cases and document the limitation (in eslint v8.0.0)?

**Comment by bmish** [comment]
> Given these cases are very edge (not well tested and documented), I was wondering how many users were really using the "feature". What do you think just removing the cases and document the limitation (in eslint v8.0.0)?

I don't think they're edge cases at all. I've used relative imports/requires extensively in many projects. ESLint itself has them everywhere as well.

For example, this line from inside ESLint causes `no-restricted-modules` to crash when the rule is enabled with ANY pattern option. 

```
const { SourceCode } = require("../../../lib/source-code");
``` 

So these are indeed important test cases that were missing.

**Comment by aladdin-add** [comment]
oh yes, you are right! I just misread the failing tests.

**Comment by aladdin-add** [comment]
a solution is to skip abs/rel path: https://github.com/aladdin-add/eslint/pull/4/commits/994b66173da2efcc4d6668b80a8b0e484609236f.

its dark side is patterns cannot be `../foo` and `/foo`. see the test result: https://github.com/aladdin-add/eslint/pull/4/checks?check_run_id=3301845971#step:5:52

**Comment by bmish** [comment]
> a solution is to skip checking abs/rel path: [aladdin-add@994b661](https://github.com/aladdin-add/eslint/commit/994b66173da2efcc4d6668b80a8b0e484609236f).
> 
> its dark side is patterns cannot be `../foo` and `/foo`. see the test result: [aladdin-add/eslint#4 (checks)](https://github.com/aladdin-add/eslint/pull/4/checks?check_run_id=3301845971#step:5:52)

I don't think it's acceptable to skip checking absolute / relative import paths. That unnecessarily cripples the rule for what is likely to be a common use case for many people, for little to no tangible benefit.

Instead, I just pushed a WIP workaround where we simply strip the `./` or `../` prefix from the import path before checking it.

**Comment by ljharb** [comment]
Without the leading dot it means something very different tho - if i have one import from `./foo/bar` and another from `foo/bar`, those could be configured to be treated differently, since one is relative and one bare, no?

**Comment by bmish** [comment]
> Without the leading dot it means something very different tho - if i have one import from `./foo/bar` and another from `foo/bar`, those could be configured to be treated differently, since one is relative and one bare, no?

Correct, my workaround doesn't allow people to configure the rule to treat them differently. So overall I'm not happy with the options we have for using ignore v5 and would rather not upgrade than reduce the rule's functionality.

**Comment by nzakas** [comment]
Just a note: if the upgrade isn’t straight forward, we don’t need to upgrade. The amount of effort should be in line with the value we are getting. If the effort is too great and the value is low, let’s just skip the upgrade. (This is what happened with the Ajv upgrade — too many issues and we were fine with the current version, so we opted not to upgrade.)

**Pull request closed without merging**
