### PR TITLE
Fix: require-atomic-updates reports parameters (fixes #11723)

### LINKED ISSUE #11723: require-atomic-updates false positive with inline functions
**Tell us about your environment**

* **ESLint Version:** 6.0.0-alpha.1
* **Node Version:** 8.16.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    "parserOptions": {
        "ecmaVersion": 2017
    },
    "rules": {
        "require-atomic-updates": "error",
    },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
function get() { return {}; }
function update() {}

async function foo(bar) {
  let oldBar = await get(bar.id);

  let doIt = () => {
    bar.visible = true;
  };

  if (oldBar) {
    bar.installDate = oldBar.installDate;
  } else {
    bar.installDate = new Date();
  }
}
```

```bash
./node_modules/.bin/eslint index.js
```

**What did you expect to happen?**

No errors

**What actually happened? Please include the actual, raw output from ESLint.**

```
index.js
  12:5  error  Possible race condition: `bar.installDate` might be reassigned based on an outdated value of `bar.installDate`  require-atomic-updates
  15:5  error  Possible race condition: `bar.installDate` might be reassigned based on an outdated value of `bar.installDate`  require-atomic-updates

✖ 2 problems (2 errors, 0 warnings)
```

The problem in this case appears to be the inline function. If I comment out the `bar.visible = true;` then the errors go away.

**Are you willing to submit a pull request to fix this bug?**
Not at the moment

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix: #11723 

But the resolution is different from the original report. The report was a false positive, but this is a false negative. (See also https://github.com/eslint/eslint/issues/11723#issuecomment-496038083)

**What changes did you make? (Give an overview)**

This PR changes `require-atomic-updates` behavior.

- Makes the member accesses of parameters were not local. Parameters are local variables, but if it updates the member of a parameter asynchronously, it causes a race condition. This is the false negative that #11723 reported.
- ~~Makes the closure handling relax because it causes a ton of false positive. We cannot know if the closure will be run sync or async. If the synchronous callbacks such as `Array#map` trigger `require-atomic-updates` errors, it will confuse people. Since the rule is in `eslint:recommended`, it's better if false negative is less.~~

a295496e844a50f30d299dc86af9c7700ef513f7 and 4e845fdc73805ca9a279dddba362695bd1216c01 are the change. This PR contains a few refactoring.

**Is there anything you'd like reviewers to focus on?**

Is this direction is right?

Especially, about the closure handling relaxing. Do you have another idea to reduce false positive?

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Could you give an example of the problems with closures?

**Comment by mysticatea** [comment]
In general, we cannot distinguish if a closure will be run in sync or async. Hm, but indeed, I don't have ideas about concrete examples. I will revert that change. We can defer the change until a bug report with a concrete situation.

**Comment by mysticatea** [comment]
Done.

**Comment by platinumazure** [comment]
Friendly ping: @not-an-aardvark, did you want to review this after @mysticatea addressed your original question?

**Comment by not-an-aardvark** [comment]
Sorry, I haven't had time to review, but feel free to merge this if you/others are satisfied with the changes (i.e. don't let me be a blocker).

**Comment by mysticatea** [comment]
I'll merge this PR. Thank you!

**Pull request merged**
