### PR TITLE
Update: spaced-line-comment now also allows tab (fixes #1713)

### LINKED ISSUE #1713: Relax spaced-line-comment rule by allowing (at least one) tab as a whitespace
Currently the rule `spaced-line-comment` strictly expects one or more spaces as whitespace but it would be more useful if it would also allow one or more tabs.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/8005616-relax-spaced-line-comment-rule-by-allowing-at-least-one-tab-as-a-whitespace?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by doberkofler**
The spaced-line-comment rule now also allows tab and not only space. (fixes #1713)

PS: This is my first pull request for eslint.I read the documentation and hope to not have forgotten anything.

### CODE REVIEW

**Comment by nzakas** [comment]
Looks good. Can you please update the documentation for the rule and sign our CLA (http://eslint.org/cla)?

**Comment by doberkofler** [comment]
I've just signed the CLA and updated the docs.

**Comment by nzakas** [comment]
Thanks, can you squash your commits? We like to have one commit with both the code changes and the doc changes. You can use the commit message from your first commit to represent both.

**Comment by doberkofler** [comment]
Never tried to squash commits. Can you point me into the right direction on how to do this?

**Comment by nzakas** [comment]
See http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by nzakas** [comment]
I'll do it this time, because I want to get a release out.

**Comment by nzakas** [comment]
Merged manually.

**Comment by doberkofler** [comment]
I got up this morning and it was already done. Thank you!

**Pull request closed without merging**
