### PR TITLE
docs: Link to blog post in no-constant-binary-expression

### PR DESCRIPTION
**Pull request by captbaritone**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update

#### What changes did you make? (Give an overview)

Link to the blog post about no-constant-binary-expression in that rule's docs

#### Is there anything you'd like reviewers to focus on?

Nope

### CODE REVIEW

**Comment by mdjermanovic** [comment]
The docs site build is failing due to a missing entry for the new link in [docs/src/_data/further_reading_links.json](https://github.com/eslint/eslint/blob/main/docs/src/_data/further_reading_links.json)

We set up this to be automatically inserted [on pre-commit](https://github.com/eslint/eslint/blob/a75d3b47b84f59c080c0c8301ae859fa64aa0f0f/package.json#L39-L42), but it seems that it didn't work in your environment.

To fix this, you can manually run the script:

```shell
node tools/fetch-docs-links.js docs/src/rules/no-constant-binary-expression.md
```

and then commit `docs/src/_data/further_reading_links.json`

**Comment by captbaritone** [comment]
I thought the change would be simple so I made it using the GitHub UI. Looks like it's more complicated than that.

**Comment by nzakas** [comment]
Yeah, there’s a script that fetches all the info about the URL to display in the page. That runs on precommit so people can’t skip it. Clearly we forgot about GitHub UI-based edits. 😅 

You can either update the branch from your CLI or we can close this.

**Comment by captbaritone** [comment]
Updated

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
