### PR TITLE
Fix: `quote-props` rule should ignore computed and shorthand properties

### LINKED ISSUE #3544: `object-shorthand` and `quote-props` have incompatibilities
```bash
$> eslint -v
v1.2.1
```

My `.eslintrc`:

```json
{
  "ecmaFeatures": {
    "objectLiteralShorthandProperties": true
  },
  "rules": {
    "quote-props": [2, "consistent"],
    "object-shorthand": [2, "always"]
  }
}
```

The code:

```javascript
var x = true;
({
  x,
  'needs-quote': true
});
```

Running `eslint` gives the following output:

```bash
index.js
  2:2  error  Inconsistently quoted property `needs-quote` found  quote-props
```

Changing the code to:

```javascript
var x = true;
({
  'x': x,
  'needs-quote': true
});
```

Will instead give the error:

```bash
index.js
  3:3  error  Expected property shorthand  object-shorthand
```

So there's a Catch-22 between these two rules. I could of course rename the `x` variable to something else, but I would prefer to be able to use the object property shorthand syntax even when I have `"consistent"` or `"consistent-as-needed"` for the `quote-props` rule.

What do you think? I could probably solve this myself and submit a PR but the question is what's actually the best solution for this? Or maybe you're of the opinion that this is by design and the rules should really be incompatible when using this combination of options?

### LINKED ISSUE #3557: `quote-props` rule false positive on computed properties.
Spawned from #3544.

This rule should ignore computed properties.

```js
/* eslint-env es6 */
/* eslint quote-props: [2, "always"] */
var x;
var obj = ({
    [x]: 0
});
```

Actual:

```
> eslint -v
v1.2.1
> eslint test.js --no-eslintrc

test.js
  5:5  error  Unquoted property `x` found  quote-props

✖ 1 problems (2 errors, 0 warnings)
```

Expected:

no errors.

### PR DESCRIPTION
**Pull request by BYK**
Fixes #3557 and fixes #3544

### CODE REVIEW

**Comment by BYK** [comment]
This rule's code needs a bit cleaning up but I wanna do that after I merge these two patches to avoid merge conflicts.

**Comment by BYK** [comment]
@mysticatea - Please make sure the new tests cases are enough to cover all possibilities. I'm happy to add more if you think I missed some cases.

**Comment by mysticatea** [comment]
Looks good to me.

I agree, this rule's code needs a bit cleaning up.

**Comment by ilyavolodin** [comment]
LGTM. Just cleanup needed

**Comment by BYK** [comment]
>LGTM. Just cleanup needed

I'll do this as a follow up once we merge this and the other PR which also modifies this rule.

**Pull request merged**
