### PR TITLE
Fix: remove internal property from config generation (fixes #7758)

### LINKED ISSUE #7758: No documentation for config.installedESLint
When using `eslint --init`, the new `.eslintrc.js` contains:

```js
{
    installedESLint: true
}
```

This option is not documented anywhere. This is related to https://github.com/eslint/eslint/issues/6200.

### PR DESCRIPTION
**Pull request by alberto**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Prevent including an internal flag to the generated config in `--init`.

**Is there anything you'd like reviewers to focus on?**
No.

### CODE REVIEW

**Comment by alberto** [comment]
@kaicataldo not sure what you mean by
>  this is actually in the tests (which means they never actually worked? :/)

The tests are testing `getConfigForStyleGuide` which I guess is a seam exposed to be able to test the styleguide part. The function is a bit of a misnomer because it also installs the modules, but it doesn't call `writeFile` which is where I removed the flag. That method is untested, with a comment: `hard to test fs function`.

Let me know what you guys think should be done here.

**Comment by kaicataldo** [comment]
Ah, understood. Feel free to ignore that comment. Any thoughts on an alternate way of doing this? Mutating the actual configs object doesn't feel good for something that's really for internal use only (I don't think I realized that this would end up in the actual user config when I initially worked on it).

**Comment by kaicataldo** [comment]
i.e. Would a variable declared in this module but outside of the scope of the functions be a better way to flag this? We don't have to add and delete the key from `config` then.

**Comment by alberto** [comment]
You beat me to it. I could use a variable but then it wouldn't be testable in `getConfigForStyleguide`. Another possiblity would be to make `config` a more general project config concept and have an `eslint` property be the actual eslintrc config that gets written to file.

**Comment by kaicataldo** [comment]
Interesting...You're right about the tests. If everyone's okay with this implemenation, that's fine by me, but it might be nice to go through and see if we can make that better at some point :)

**Comment by alberto** [comment]
Ok. Can you update your review then so this doesn't go ignored?

**Comment by kaicataldo** [comment]
LGTM. Thanks for contributing!

**Pull request merged**
