### PR TITLE
Update: Use sails-hook-lint for Sails integration

### PR DESCRIPTION
**Pull request by amorriscode**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

After further testing, sails-hook-lint has been determined to be the best Sails.js integration available.

### CODE REVIEW

**Comment by amorriscode** [comment]
@kaicataldo Hey Kai, the issue was the old suggested hook (sails-hook-eslint) used an extremely old version of ESLint so it wasn't very useful. Now the current npm package in the docs (sails-eslint) actually has bugs out of the box. After testing I found that sails-hook-lint provides the functionality needed and runs great out of the box.

**Comment by amorriscode** [comment]
@nzakas Hey Nicolas, you're actually looking at the wrong npm package. I suggested sails-hook-lint not sails-hook-eslint. The name is very close but is actually different.

**Comment by nzakas** [comment]
Oops, right you are. I still don't think we should just replace what we have now with something else that seems to be equally well-maintained. I'd rather include both - ESLint doesn't want to play favorites on something we don't understand that well. Otherwise we'd be stuck going back and forth for every framework depending on who the last person to submit a documentation update was.

**Comment by amorriscode** [comment]
I added sails-eslint back in as per your request. That is a great point that I didn't think of, I just had issues getting sails-eslint running which is why I proposed the original change.

**Comment by kaicataldo** [comment]
Going to go ahead and merge this, @nzakas, since your concern was addressed

**Pull request merged**
