### PR TITLE
Docs: Document the second argument of `CLIEngine.executeOnText()`

### PR DESCRIPTION
**Pull request by sindresorhus**

### CODE REVIEW

**Comment by BYK** [comment]
@sindresorhus - I think you need to file an issue first and reference that.

**Comment by sindresorhus** [comment]
You think wrong:

> - Make sure there is an issue for any pull request you send.
>   - The only exception is for documentation changes.

http://eslint.org/docs/developer-guide/contributing.html#pull-requests

**Comment by BYK** [comment]
@sindresorhus ah, TIL.

Also I was okay with "you think wrong" (instead of "Nope", you can't edit e-mails :D).

**Comment by nzakas** [comment]
I will mark this day on my calendar: the day someone read the contribution guidelines! :tada:

**Pull request merged**
