### PR TITLE
Docs: Link JSCS rules to their corresponding page.

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by platinumazure** [comment]
This should probably be a separate issue, but we should get some consistency in how verbose we want to be for compatibility. I'm just noting it here. Changes LGTM.

**Comment by kaicataldo** [comment]
Awesome!

**Comment by pedrottimark** [comment]
Thank you for establishing a clear pattern for others to follow. Nice typographical craftsmanship to move colon outside bold formatting!

**Comment by hzoo** [comment]
Great; I added a lot more of these on the airbnb repo too (ex: https://github.com/airbnb/javascript#references--disallow-var)

**Pull request merged**
