### PR TITLE
Update: use local CLI from `./node_modules` if available (fixes #3293)

### LINKED ISSUE #3293: eslint-global-vs-local
global eslint cannot see local packages. And it kinda wrong: other tools like mocha, karma, grunt and gulp, user local versions of itself if it exists.

You can see the problem. You can run `eslint index.js` and `npm run eslint` in this repo

_index.js:_

    var some = '';

which violate airbnb codestyle. _.eslintrc:_

    { "extends": "eslint-config-airbnb" }

_package.json scripts field:_

      "scripts": {
        "eslint": "eslint index.js"
      },

local copy of eslint runned from npm-scripts works well. global one throw an error. from my perspective of other tools, its wrong.

```
➜  eslint-global-vs-local git:(master) ✗ eslint index.js
/usr/local/lib/node_modules/eslint/lib/config.js:141
                    throw e;
                          ^
Error: Cannot find module 'eslint-config-airbnb'
Referenced from: /Users/matmuchrapna/projects/eslint-global-vs-local/.eslintrc
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:104:48)
    at /usr/local/lib/node_modules/eslint/lib/config.js:135:46
    at Array.reduceRight (native)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:119:36)
    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:243:23)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:371:22)
```
You can play around with these files in this repo https://github.com/iamstarkov/eslint-global-vs-local

### PR DESCRIPTION
**Pull request by jamestalmage**
This has come up a few times (#3293, #1238, etc).

I recently created `fallback-cli`. As you can see from the PR, it makes it dead simple to implement the common paradigm of: "Install some CLI globally, but prefer whatever version is installed locally in `node_modules`".

This is backwards compatible all the way back to `eslint@0.0.4` (when the name changed).

### CODE REVIEW

**Comment by jamestalmage** [comment]
outside a project dir (global)

```
$ eslint --version 
v1.5.1
```

in a project dir that depends on `0.1.4` installed

```
$ eslint --version 
v0.1.4
```

**Comment by nzakas** [comment]
Please open a new issue to propose this change.

**Comment by catesandrew** [comment]
+1

**Comment by nzakas** [comment]
Per #3293, we've decided this will create enough confusion that we don't want to pursue adding this feature. Thanks.

**Comment by acthp** [comment]
I'm curious why fixing this would cause confusion, when eslint is the outlier here. Surely tooling that follows convention creates less confusion?

bash 'alias' is a non-solution, because apps other than bash (e.g. editors) need to run eslint.

**Pull request closed without merging**
