### PR TITLE
Fix: Optionally allow underscores in member names

### PR DESCRIPTION
**Pull request by eaviles**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
I included the check to see if the identifier is allowed when validating member names in the no-underscore-dangle rule.

**Is there anything you'd like reviewers to focus on?**
Not sure if ignoring the "allow" option with member names was the original behavior.

### CODE REVIEW

**Comment by platinumazure** [comment]
Hi @eaviles, thanks for the PR!

Hmm... This does seem like a bug to me, but I'd like to get opinions from more team members.

**Comment by kaicataldo** [comment]
So sorry for the delay here. I agree that this looks like a bug. Marking as accepted. @eaviles Are you able and still willing to fix the merge conflict?

**Comment by eaviles** [comment]
> So sorry for the delay here. I agree that this looks like a bug. Marking as accepted. @eaviles Are you able and still willing to fix the merge conflict?

Hi @kaicataldo thanks for the review. Yeah I’m still able and willing, I’ll take care of the merge conflict ASAP!

**Comment by kaicataldo** [comment]
Friendly ping :)

**Comment by eaviles** [comment]
> Friendly ping :)

Ashamed pong 🙈

Taking care of this ASAP!

**Comment by kaicataldo** [comment]
No worries! We appreciate you taking the time to contribute. Let us know if there's anything we can do to help!

**Comment by nzakas** [comment]
@eaviles Just following up to see if you're still planning on updating this?

**Comment by nzakas** [comment]
@eaviles one last check to see if you’re still working on this?

**Comment by eaviles** [comment]
@kaicataldo, @nzakas: I just resolved the conflict. Waiting for the checks to complete. Ready to follow up if needed ;)

**Comment by eaviles** [comment]
@kaicataldo, @nzakas, @mdjermanovic, @kaicataldo: trying to follow up… what's next? I can't merge this myself so just wondering about the procedure.

**Comment by nzakas** [comment]
@mdjermanovic are you ok with merging without further changes (unclear from your comment).

**Comment by mdjermanovic** [comment]
> @mdjermanovic are you ok with merging without further changes (unclear from your comment).

Yes, I'm ok with merging this without further changes.

**Comment by kaicataldo** [comment]
Thanks for contributing to ESLint.

**Pull request merged**
