### PR TITLE
Fix: consistent-docs-url crashes if meta.docs isn't present

### PR DESCRIPTION
**Pull request by s4san**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Issue ( #10722 )

**What changes did you make? (Give an overview)**

- Added a check to report missing property if `metaDocs` is `null`

**Is there anything you'd like reviewers to focus on?**

- Changed the `checkMetaDocsUrl` function

### CODE REVIEW

**Comment by s4san** [comment]
@platinumazure I tried to cover those cases, but it seemed a bit out of scope for this PR. I will try to elaborate,

Case 1: `meta` property is not defined on the exports object.

This crashes eslint and curiously, the `exportsNode` is of type `functionExpression`. I did not get to explore this case further.

Case 2: `meta` property is defined with a value of `undefined`

This creates an exception in `getPropertyFromObject` method where it tries to access `length` of `undefined`.

I was hoping to create a separate issue for this but I couldn't get to it. Do you think these should be investigated separately or should they be addressed in this PR?

**Comment by platinumazure** [comment]
Creating a separate issue is fine. Thanks for checking!

**Comment by s4san** [comment]
I have created an issue #10750 and I would like to work on it

**Comment by platinumazure** [comment]
Merged-- thanks @s4san for contributing!

**Pull request merged**
