### PR TITLE
Fix: Object shorthand rule incorrectly flagging getters/setters (fixes #2563)

### LINKED ISSUE #2563: object-shorthand rule errors on getters and setters
The following code generates an error with `"object-shorthand": [2, "always"]`:

```js
var x = {
    get y() {},
    set y(z) {}
};
```

Did a little digging and `node.shorthand === false` for those, so maybe the rule should exclude nodes where are `node.kind === "get"` or `node.kind === "set"`.

Using version 0.21.1.

### PR DESCRIPTION
**Pull request by bdougherty**

### CODE REVIEW

**Comment by michaelficarra** [comment]
LGTM.

**Comment by nzakas** [comment]
Thanks, can you please sign our CLA? http://eslint.org/cla

**Comment by bdougherty** [comment]
@nzakas thought I filled it out yesterday, but just did it again

**Comment by nzakas** [comment]
Argh, apparently you did but it just didn't show up for me until now. Sorry about the confusion.

**Pull request merged**
