### PR TITLE
Fix:`newline-per-chained-call` should only warn on methods

### LINKED ISSUE #5289: Feature Request: Add option to newline-per-chained-call for func calls only
Personally , I want to ask if its possible to have an option to chain function calls only and not object access as well?

Example:

```
// valid with option on, invalid with off
db.user
            .query()
            .then()
            .catch();
```

I'm not sure what to name the option, perhaps `funcCallOnly` ? e.g 

```
  'newline-per-chained-call': [2, {funcCallOnly: true}]
```

### PR DESCRIPTION
**Pull request by BYK**
Fixes #5289

### CODE REVIEW

**Comment by rpatil26** [comment]
+ @gajus 

This looks good to me and we initially started with chained calls only docs does mention the same, but as we went on discussing more, we included newlines for props too. Here's the conversation https://github.com/rpatil26/eslint/commit/060201842e1550a895bdcdb50f187c933d86744e#commitcomment-15618435

**Comment by BYK** [comment]
@rpatil26, @gajus - I can bring back some of that behavior such as forcing new lines when the chain depth exceeds a certain value and there's a function call in the middle (not at the end) but I'd rather that be an option since according to the feedback we got and my personal experience, that's rather an unusual case.

**Comment by rpatil26** [comment]
I personally agree. The option to control what to report would be good with default ON for the chained calls only. Let's wait to hear from @gajus too.

**Comment by gajus** [comment]
Thank you @rpatil26.

The proposed changes look good to me. As regarding to bringing in the depth option, that might be useful, but at the same time allows inconsistency.

**Comment by BYK** [comment]
@gajus - can you clarify the actions needed to move forward?

**Comment by gajus** [comment]
@BYK It is not up to me. It is going to be up to @nzakas or @ilyavolodin.

**Comment by nzakas** [comment]
I don't have a strong opinion. If the changes look good to @gajus and @rpatil26, and that don't break back compat, then that's good enough for me.

**Comment by ilyavolodin** [comment]
Looks like both @gajus and @rpatil26 are good with this change, can we merge this?

**Comment by rpatil26** [comment]
:+1:

**Pull request merged**
