### PR TITLE
Docs: Fix spacing on inline eslint directives

### PR DESCRIPTION
**Pull request by nikolas**
It looks nicer if there's either a space at the beginning and end of the
comment, or no spaces at all.

### CODE REVIEW

**Comment by BYK** [comment]
Hey, thanks for the pull request!

Can you please format your commit message according to [our guidelines](http://eslint.org/docs/developer-guide/contributing)? (Should add `Docs: ` at the beginning)

**Comment by nikolas** [comment]
Yeah, sorry about that. I'll re-push in a second.

**Comment by BYK** [comment]
Yay, thanks! :tada:

**Comment by nzakas** [comment]
Throughout our docs, we have no spacing at the beginning of these comments, so I'd like to keep that consistent.

**Comment by nzakas** [comment]
@nikolas do you want to go through and eliminate these spaces (per my previous comment)?

**Comment by nzakas** [comment]
No response; closing.

**Pull request closed without merging**
