### PR TITLE
docs: fix searchbar clear button

### LINKED ISSUE #16584: docs: Clear button in Searchbar flickers and disappears
### ESLint version

v8.21.0

### What problem do you want to solve?

1. Clear button appears only if the search query length is greater than 2 
2. Once the `no results found` modal appears if we enter text into search input, the clear button starts flickering and disappears. 

https://user-images.githubusercontent.com/42532987/204036388-a78e1747-145e-4f41-9299-e2def9b5a76d.mp4

### What do you think is the correct solution?

1. Clear button shouldn't disappear if a search query is present
2. Clear button shouldn't flicker if we type after the `no results found` modal appears

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I'm willing to send a fix to https://github.com/eslint/eslint.org (blog page) too.

Also, It would be better if we add debouncing.

### PR DESCRIPTION
**Pull request by shanpriyan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Fixed search bar clear icon flickering and disappearance issue

Fixed #16584 

## After fix

https://user-images.githubusercontent.com/42532987/204045234-0cc21b88-d866-48e2-b5b6-a3d8733777b1.mp4

### CODE REVIEW

**Review by amareshsm — APPROVED** [review]
LGTM

**Review by harish-sethuraman — COMMENTED** [review]
Right now I see clear icon even when we have 1 character. Just have to confirm if this is fine. I see network calls for getting the results of the search the same way we had before might be better? WDYT?

**Comment by amareshsm** [comment]
> Right now I see clear icon even when we have 1 character. Just have to confirm if this is fine. I see network calls for getting the results of the search the same way we had before might be better? WDYT?

 Right now I see a clear icon even when we have 1 character. Just have to confirm if this is fine >> I guess it is fine just showing the icon to clear the input.  let's see what others think @eslint/website-team .
 
 I see network calls for getting the results of the search the same way we had before might be better? WDYT?>> it's fine right?🤔

**Comment by harish-sethuraman** [comment]
> I see network calls for getting the results of the search the same way we had before might be better? 

we can try reducing the search requests by debouncing the request may be in a separate PR?

**Review by harish-sethuraman — APPROVED** [review]
Yea this PR LGTM

**Comment by shanpriyan** [comment]
> > I see network calls for getting the results of the search the same way we had before might be better?
> 
> we can try reducing the search requests by debouncing the request may be in a separate PR?

Yeah we can, I will raise that PR. Updated the same in issue.

**Comment by amareshsm** [comment]
Closing and re-opening the PR to fix CI.

**Comment by shanpriyan** [comment]
>we can try reducing the search requests by debouncing the request may be in a separate PR?

Done #16586 🚀

**Review by amareshsm — APPROVED** [review]
LGTM

**Review by kecrily — APPROVED** [review]
LGTM

**Review by snitin315 — APPROVED** [review]
This new behavior makes sense to me. I see that earlier we were not showing the clear button if there were no search results.

**Pull request merged**
