### PR TITLE
Docs: (curly) Fix broken code in example

### LINKED ISSUE #3539: Fix docs code for `curly`
The docs have:

```javascript
if (foo) return;
else foo();
```

Which would result in a runtime error if `foo` is ever falsy. It actually makes no difference with regards to actually explaining how the rule works, it's mostly just annoying so I thought I'd throw in a quick PR.

### PR DESCRIPTION
**Pull request by kentcdodds**
(fixes #3539)

### CODE REVIEW

**Comment by BYK** [comment]
@KenPowers - next time, instead of creating multiple pull requests, you can run `git commit --amend` and then `git push origin -f branch_name` to update your commit and reuse the existing PR ;)

**Comment by kentcdodds** [comment]
Right, that's what I'd do normally, but I just did this in the github editor. Probably could have been just as fast by cloning it locally, but meh :-)

**Comment by gyandeeps** [comment]
and also we dont need issue for minor docs changes

**Comment by kentcdodds** [comment]
But in the build, it failed in part because it didn't reference a specific issue in the commit message.

**Comment by gyandeeps** [comment]
It failes because you had "Docs (curly):" like this

**Comment by kentcdodds** [comment]
Hmmm... what's this mean then ([job output](https://travis-ci.org/eslint/eslint/jobs/77408354)):

> - Commit message must end with with one of:
>     '(fixes #1234)'
>     '(refs #1234)'
>    Where '1234' is the issue being addressed.

**Comment by gyandeeps** [comment]
We just print a generic message for this kind of failure

**Comment by kentcdodds** [comment]
Ah, understood. I thought it was a little overkill :-)

**Comment by kentcdodds** [comment]
Perhaps I'll make another PR that changes it to say "can" or "should except for docs fixes" ;-)

**Comment by KenPowers** [comment]
I'm assuming I was tagged by mistake?

**Comment by BYK** [comment]
@KenPowers - yup, may bad, lazy on typing. Sorry :(

**Comment by KenPowers** [comment]
@BYK No worries. I was just *really* confused when I saw this pop up in my inbox.

**Pull request merged**
