### PR TITLE
Update: Pass file path to parse function

### PR DESCRIPTION
**Pull request by azhang496**
ref: https://github.com/eslint/eslint/issues/5344

let me know if i need to update anything in the docs!

edit: moved the test into the "custom parser" describe since it was failing in the browser

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM, but waiting another day for others to look. Thanks @azhang496 for doing this!

**Comment by kaicataldo** [comment]
@ilyavolodin Any idea why the jQuery CLA check failed? @azhang496 has contributed before, so it was definitely working

**Comment by platinumazure** [comment]
@kaicataldo The jQuery CLA status page is also giving HTTP 404, so I'm not sure what to do here.

@azhang496 `path.join` doesn't exist in PhantomJS and browser environments, you might need to make sure your test is not run in Phantom.

**Comment by azhang496** [comment]
@platinumazure yep, moved the test into the custom parser section so it's not run in the browser

**Comment by kborchers** [comment]
Looking into this now and will update ASAP

**Comment by kborchers** [comment]
@azhang496 @platinumazure Sorry for the issue and delay but you should be all good now. There was a disk issue on the box that has now been resolved.

**Comment by nzakas** [comment]
LGTM, just waiting another day to fulfill our requirement that PRs remain open for two days so others have a chance to review.

**Comment by kaicataldo** [comment]
LGTM. Thanks for contributing to ESLint!

**Comment by platinumazure** [comment]
Thanks @kborchers for your help with the CLA.

**Comment by hzoo** [comment]
👍

**Comment by ilyavolodin** [comment]
Thanks @azhang496 for doing this!

**Pull request merged**
