### PR TITLE
docs: explain how to include predefined globals

### PR DESCRIPTION
**Pull request by mlwyatt**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

I've added a note about how to enable native globals as discussed in https://github.com/eslint/eslint/discussions/17101#discussioncomment-5706223

#### Is there anything you'd like reviewers to focus on?

I think the wording is pretty clear, but let me know if not.

### CODE REVIEW

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Leaving it open for @fasttime to verify.

**Comment by fasttime** [comment]
Thanks @mlwyatt! I've changed "native globals" to "predefined globals" in the title because some environments define globals that are not native (e.g. `mocha`'s `describe`, `it`, etc.).

**Review by fasttime — APPROVED** [review]
LGTM

**Comment by mdjermanovic** [comment]
@mlwyatt could you please submit the same changes again, in a new PR, as we had to [undo](https://github.com/eslint/eslint/pull/17227) them due to https://github.com/eslint/eslint/issues/17225.

**Pull request merged**
