### PR TITLE
Chore: enable no-prototype-builtins in codebase (fixes #10660)

### LINKED ISSUE #10660: no-restricted-globals rule crashes with 'hasOwnProperty' as restricted global
**Tell us about your environment**

* **ESLint Version:** v5.2.0
* **Node Version:** v8.11.1
* **npm Version:** v5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
	"rules": {
		"no-restricted-globals": ["error", "hasOwnProperty"],
	}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
module.exports = obj => hasOwnProperty(obj, 'name');
```

**What did you expect to happen?**
Should get a warning for using the global "hasOwnProperty".

**What actually happened? Please include the actual, raw output from ESLint.**

```
restrictedGlobalMessages.hasOwnProperty is not a function
TypeError: restrictedGlobalMessages.hasOwnProperty is not a function
    at isRestricted (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/rules/no-restricted-globals.js:97:45)
    at Program.scope.variables.forEach.variable (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/rules/no-restricted-globals.js:106:50)
    at Array.forEach (<anonymous>)
    at Program (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/rules/no-restricted-globals.js:105:33)
    at listeners.(anonymous function).forEach.listener (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/util/node-event-generator.js:294:14)
```

The issue is this line in `no-restricted-globals.js`:
```js
        function isRestricted(name) {
            return restrictedGlobalMessages.hasOwnProperty(name);
        }
```

which should be:

```js
        function isRestricted(name) {
            return Object.prototype.hasOwnProperty.call(restrictedGlobalMessages, name);
        }
```

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
refs #10660 

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

Do we want a way to find which rules can be enabled(to see if there's similar problems)?

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
I'm in favor of the idea, but there are a lot of existing use cases in the codebase that would need to be fixed before we can enable the rule.

**Comment by Aladdin-ADD** [comment]
will fix it asap!

**Comment by kaicataldo** [comment]
Agreed with @ilyavolodin.

**Comment by kaicataldo** [comment]
If we add a unit test as suggested in https://github.com/eslint/eslint/pull/10711, can we close the issue this is referencing in his PR? I ask because it looks like the other PR has stalled.

**Pull request merged**
