### PR TITLE
feat!: check for parsing errors in suggestion fixes

### LINKED ISSUE #15735: Change Request: RuleTester check for parsing errors in suggestion fixes
### ESLint version

8.12.0

### What problem do you want to solve?

The rule tester currently checks if any fixes [result in a parser error](https://github.com/eslint/eslint/blob/8bb527660ffddc122204fb5bf59076687aaa78b8/lib/rule-tester/rule-tester.js#L654) but it does include suggestion fixers.

### What do you think is the correct solution?

I would propose to include suggestion fixes as well by checking each suggestion in isolation.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by bmish**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[x] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Fixes #15735.

RFC (approved): https://github.com/eslint/rfcs/pull/101

In rule tester, check for parsing errors in suggestion fixes, and throw an error if a suggestion yielded invalid output.

This is a breaking change for plugin developers who may have had invalid suggestions.

#### Is there anything you'd like reviewers to focus on?

This PR is ready on my side. I'm lining this PR up now so that it's ready for the v9 release.

### CODE REVIEW

**Comment by nzakas** [comment]
@bmish can you provide a status update on this?

**Comment by bmish** [comment]
I believe this is still ready. It's one of several breaking changes I'm trying to have lined up ready to go when ESLint v9 comes around.

**Comment by nzakas** [comment]
Okay, we generally ignore PRs that are drafts until they marked as ready for review. Given that this is a breaking change, maybe we want to hold off on reviewing until we're ready for v9?

**Comment by bmish** [comment]
This PR is ready, except there is a failure with one rule we need to fix, see:
* https://github.com/eslint/eslint/pull/17661/files#r1413158284
* https://github.com/eslint/eslint/pull/17812

**Review by nzakas — CHANGES_REQUESTED** [review]
We are going to be removing `RuleTester` in v9, so can you revert those changes? I'd like to avoid merge conflicts as go through the process of removing `RuleTester`.

**Comment by bmish** [comment]
@nzakas done!

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
