### PR TITLE
chore: add incorrect and correct in all rule docs

### PR DESCRIPTION
**Pull request by harish-sethuraman**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

Add correct and incorrect to all code snippets 

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Ran `regex` to add `correct` and `incorrect` to all files at once

find 
```js
\*\*correct\*\*(.*)\n*(```.*(\n|.)*?```)
```
replace with
```js
**correct**$1

::: correct
$2 
:::
```
we basically group the text after the `**correct**` until the line end `\n` and that is `$1`. The `$2` is the code snippet wrapped within ***```***. Same works well with the text in correct as well

If you see one empty line after the ``` closing it is because of the new line addition after ::: correct or ::: incorrect but in file it is not going to be there

In case if you were wondering what would happen to the markdowns already with correct and incorrect values. The regex wouldn't match it so no adding correct and incorrect wrapper for those snippets :)

### CODE REVIEW

**Comment by mdjermanovic** [comment]
This is solving the same issue as https://github.com/eslint/eslint/pull/16021?

**Comment by harish-sethuraman** [comment]
Hey 👋🏻  Seems like yes but that has less addition may be something was missed in the manual effort? When I raised the PR there were only 30 file changes and it had been 3 days https://github.com/eslint/eslint/issues/16013#issuecomment-1159359676 no response for my comment either. Came across an easy way to replace all occurrences without missing any of them so sent a PR.

**Comment by mdjermanovic** [comment]
I merged https://github.com/eslint/eslint/pull/16021 because it was submitted first, but thanks for working on this!

**Comment by harish-sethuraman** [comment]
No Probs 😛

**Pull request closed without merging**
