### PR TITLE
Fix: sanitise Jekyll interpolation during site generation (fixes #2297)

### LINKED ISSUE #2297: Documentation: word missing in output
On [Working with rules](http://eslint.org/docs/developer-guide/working-with-rules) under the `context.report()` heading, the source reads:

    context.report(node, "`{{identifier}}` is unexpected!", { identifier: node.name });

But the output shows:

selection_006

### PR DESCRIPTION
**Pull request by michaelficarra**
I have no idea if this will work, but it probably will.

Fixes #2297.

**edit:** Why are these tasks in here and not eslint/eslint.github.io?

### CODE REVIEW

**Comment by nzakas** [comment]
Looks good to me.

The tasks are here because the site gets generated as part of each release.

**Comment by michaelficarra** [comment]
Still, that leads to really tight coupling. Can't the task be there and be invoked from here during a release?

**Comment by nzakas** [comment]
The tight coupling is necessary to ensure consistency between the repos. eslint.org is the target of the documentation, the source is this repo, it's a one-way push relationship.

**Comment by nzakas** [comment]
Actually, there are other places where we want variable insertion, so we can't do this without knocking them all out. Just need to escape the markdown.

**Comment by michaelficarra** [comment]
@nzakas: Do you have an example?

**Comment by nzakas** [comment]
I'm going to spend some time looking at this later - I don't want to jump into a solution without really evaluating the problem.

**Comment by nzakas** [comment]
Tested this and looks like it would work fine. Thanks.

**Comment by ilyavolodin** [comment]
I don't think it worked correctly: Take a look at this page: http://eslint.org/docs/developer-guide/working-with-rules#context.report() second `pre` doesn't look right.

**Comment by nzakas** [comment]
Gah, yeah, reverting.

**Pull request merged**
