### PR TITLE
Update: Add metadata to existing rules - Batch 1 (refs #5417)

### PR DESCRIPTION
**Pull request by vitorbal**
Add metadata to the existing rules. Batch 1. There will be roughly 11 batches in total.
The metadata was extracted out of lib/rules/README.md and I am using a jscodeshift transform to programmatically do the changes (with a few manual adjustments). [Here](https://gist.github.com/vitorbal/18f75cb8643e51c3540b344a67c4ddb3)'s the transform code, in case anyone is interested :)

### CODE REVIEW

**Comment by pedrottimark** [comment]
Two quick observations:
* Because the main heading of rule docs will soon change to the same format as the index page (rule-id: rule description) I think it is better for the initial letter in the first word to remain as lowercase.
* It looks like descriptions lack backticks (see `return` in array-callback-return) so maybe the transform needs to convert `code` elements?

**Comment by vitorbal** [comment]
@pedrottimark 
> Because the main heading of rule docs will soon change to the same format as the index page (rule-id: rule description) I think it is better for the initial letter in the first word to remain as lowercase.

Okay, no longer upper-casing the first letter now!

> It looks like descriptions lack backticks (see return in array-callback-return) so maybe the transform needs to convert code elements?

Great find, wow, how did I miss that :) fixed now! Thanks a lot for the feedback!

**Comment by ilyavolodin** [comment]
LGTM. @nzakas can we merge those change with minimal code review? There's a very high probability of merge conflicts in them, and since they are automated, and unittests are passing, there's a low chance of issues.

**Comment by nzakas** [comment]
@ilyavolodin yeah definitely. If tests are passing, I'd say get through this pain as quickly as possible.

**Pull request merged**
