### PR TITLE
Apply object-property-newline to destructuring and imports

### PR DESCRIPTION
**Pull request by morgs32**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
It would function almost exactly like object-property-newline except on destructured variables. Much of the below is an adaptation of that rule.

If you are destructuring lots of variables at once like so:
```
const { foo, bar, baz, abc, xyz, foobar, foobaz, bazfoo, barfoo, abcxyz, xyzabc, foobarbaz, bazbarfoo } = foobarbazabcxyz;
```
the line length can get pretty long. Readability decreases. I think it could be useful if there was a rule that detected the amount of characters in a line or the amount of variables being destructured. If that number happens to be too large (not sure what the right number here is), throw a warning/error suggesting a multiline destructuring like so:

```
const {
foo,
bar,
baz,
abc,
xyz,
foobar,
foobaz,
bazfoo,
barfoo,
abcxyz,
xyzabc,
foobarbaz,
bazbarfoo
} = foobarbazabcxyz;
```

*And similarly for imports*

**Is there anything you'd like reviewers to focus on?**
I need help with the tests of the rule on `imports`

### CODE REVIEW

**Comment by jrpool** [comment]
In tests/lib/rules/object-property-newline.js, lines 719-722:
(1) Include an "Exports must …" message, which seems to be a mistake.
(2) Include an expected error on line 3, even though there does not seem to be a line 3 in the code.

**Comment by jrpool** [comment]
I believe that this PR, to be complete, also needs to include a revised version of the documentation on the rule, to match the rule’s changed features.

**Comment by jrpool** [comment]
An `applyToImports` object option is invoked 5 times. Is it intended that that option exist?

**Comment by jrpool** [comment]
This PR treats object literals and destructuring assignments asymmetrically. The user can make the rule apply to the former only, or to both the former and the latter, but the user cannot make it apply only to the latter. Is there a reason to expect users will not want to do that?

Also, the rule definition seems to me to contain a substantial amount of code repeated 3 times that could be encapsulated into a function and called instead.

**Comment by morgs32** [comment]
@jrpool despite my reticence I'm really glad to have your feedback/help! I'll dig back into this tonight.

**Comment by timruffles** [comment]
@morgs32 are you still looking at this? Can I adopt the PR if not?

**Comment by amandakoster** [comment]
Excited for this feature/rule! Thank you in advance!

**Comment by willdavidow** [comment]
Excited to see this get merged!

**Comment by zachelrath** [comment]
@timruffles @morgs32 Are either of you still actively working on this? If not, would you like to hand it off to someone else?

**Comment by kaicataldo** [comment]
Should we close this PR so that others like @zachelrath can give this a shot?

**Comment by zachelrath** [comment]
@timruffles Are you up for taking this on? Just want to make sure multiple people aren't working on this at the same time :)

**Pull request closed without merging**
