### PR TITLE
Update: Key-spacing: allow 1+ spaces before/after colon (fixes #3363)

### LINKED ISSUE #3363: Key-spacing: allow 1+ spaces before/after colon
Currently, there doesn't seem to be a way to allow more than 1 space before/after a colon. With my teams' particular use-case, we want to _allow_ devs to align values if they wish, but have _at least_ 1 space after a colon.

### PR DESCRIPTION
**Pull request by BYK**

### CODE REVIEW

**Comment by BYK** [comment]
NOTE: This is just a reference implementation for the idea in https://github.com/eslint/eslint/issues/3363#issuecomment-130356603. Needs update to docs before moving forward.

**Comment by nzakas** [comment]
See comment in #3363: Not a good solution because `Infinity` isn't available in JSON or YAML.

**Comment by BYK** [comment]
Updated to use `null` instead of `Infinity`. Also updated the docs a bit.

**Comment by nzakas** [comment]
See my note on #3363. I don't think this is the right direction to go in.

**Comment by BYK** [comment]
:disappointed: that said I agree. I sort of pushed too hard on that one :)

**Pull request closed without merging**
