### PR TITLE
Docs: Fix multiline-ternary typos

### PR DESCRIPTION
**Pull request by cmalard**

### CODE REVIEW

**Comment by kaicataldo** [comment]
Thanks for catching these and for contributing! A few housekeeping things and we can get this merged. If you haven't already, please sign the jQuery CLA mentioned by the bot above. For the commit description, mind referencing which docs you're fixing? i.e. `Docs: Fix multiline-ternary typos`

**Comment by cmalard** [comment]
:-D

**Comment by kaicataldo** [comment]
Thanks!

**Comment by kaicataldo** [comment]
LGTM. Thanks for contributing to ESLint!

**Pull request merged**
