### PR TITLE
Update: single- and multiline const, let, var statements (fixes #10721)

### LINKED ISSUE #10721: Add "multiline-const", "multiline-let" and "multiline-var" STATEMENT_TYPEs to padding-line-between-statements rule
**What rule do you want to change?** `padding-line-between-statements`

**Does this change cause the rule to produce more or fewer warnings?** More

**How will the change be implemented? (New option, new default behavior, etc.)?** New accepted values for `prev` and `next` configuration options

**Please provide some example code that this change will affect:**

```js
const bouya = { hey: "ho" };
const kasha = {
  tik: "tok",
  onda: "clock"
};
```

**What does the rule currently do for this code?** The rule is unable to differentiate single-line and multi-line `const`, `let` and `var` statements.

**What will the rule do after it's changed?** The rule will offer the possibility to treat aforementioned cases differently, e.g. enforce blank lines around a multi-line variable declaration but not around a single-line one.

### PR DESCRIPTION
**Pull request by neemzy**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

https://github.com/eslint/eslint/issues/10721

**What changes did you make? (Give an overview)**

- Added new `STATEMENT_TYPE`s for multiline variable declarations (`multiline-const`, `multiline-let`, `multiline-var`, `singleline-const`, `singleline-let`, `single-line-var`)

### CODE REVIEW

**Comment by neemzy** [comment]
PR was updated as requested in #10721: `singleline-*` `STAMEMENT_TYPE`s were also added to allow for discrimination while preserving backwards compatibility.

**Comment by neemzy** [comment]
@platinumazure @not-an-aardvark Is that OK for you guys? :)

**Comment by neemzy** [comment]
@platinumazure Done, thanks!

**Comment by platinumazure** [comment]
Oh, can you take a look at the Contributor License Agreement issue? We can't merge this without you signing the CLA. Thanks!

**Comment by neemzy** [comment]
@platinumazure Hmm, that's strange, I signed it when I first opened the PR and can't sign it again if I check the details (fields are disabled and there is no submit button anyway). See https://imgur.com/a/ROMQPZy

**Comment by not-an-aardvark** [comment]
@neemzy It seems like your git commit was created with a different email address (`tpanier at synbioz dot com`) than the one associated with your GitHub account, which is why the CLA check is now failing. One way to fix it would be to amend the commit to make sure the correct email is used, or to add the other email address to your GitHub account.

**Comment by neemzy** [comment]
@platinumazure Are we waiting for more approvals from the team? :)

**Comment by nzakas** [comment]
@kaicataldo @not-an-aardvark any objections to merging this?

**Comment by neemzy** [comment]
Thanks! :)

**Pull request merged**
