### PR TITLE
Update: ignore negative ranges in fixes

### LINKED ISSUE #8116: 3.16.0 regression: padded-blocks autofix can generate incorrect code
**Tell us about your environment**

* **ESLint Version:** 3.16.0
* **Node Version:** 6.9.1
* **npm Version:** 3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```
module.exports = {
  rules: {
    "padded-blocks": ['error', 'never'],
  }
};
```

(This is the value specified by eslint-config-airbnb.)

**What did you do? Please include the actual source code causing the issue.**

I ran `eslint --fix` on this source code:

```js
function f() { // a

  b;
}
```

**What did you expect to happen?**

I expected it to fix the formatting and generate correct code.

**What actually happened? Please include the actual, raw output from ESLint.**

eslint generated this output:
```
➜  eslint_test_3 git:(master) ./node_modules/.bin/eslint --fix test.js

/Users/alanpierce/code/eslint_test_3/test.js
  6:1  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)
```

And the JS file was changed to have these contents:
```
function f() {
function f() { // a

  b;
}
```

This is a syntax error, so the file fails to parse after this change.

When I try this on eslint 3.15.0, it doesn't have any problems.

This is breaking the [coffeelint example build](https://github.com/decaffeinate/decaffeinate#status) for the decaffeinate project. The [lexical_linter.js](https://github.com/decaffeinate-examples/coffeelint/blob/decaffeinate/src/lexical_linter.js) file has two `static initClass` lines near the start, which causes a syntax error. (The example builds are a bit like eslint-canary for the decaffeinate project, and one of the conversion steps is to run `eslint --fix` on the resulting JS code.)

### PR DESCRIPTION
**Pull request by alberto**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Ignore fixes with negative ranges.

**Is there anything you'd like reviewers to focus on?**
I don't think https://github.com/eslint/eslint/pull/8117 is the sensible thing to do. I created a different PR to try to get this for the patch release. I'm sorry I couldn't review that sooner.

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
I think ignoring negative ranges might be a reasonable thing to do in general, but we would need to evaluate whether this is a breaking change. Given that https://github.com/eslint/eslint/pull/8117 just restores the behavior that existed before the regression, I think it makes sense to merge https://github.com/eslint/eslint/pull/8117 for the patch release and consider this change separately.

**Comment by platinumazure** [comment]
I don't think we should consider removing auto-fixes a breaking change. Autofix has always been on a best-effort basis and it's far more important (IMO) that we autofix correctly (or don't autofix if we aren't sure what correct behavior is) than we preserve behavior.

**Comment by alberto** [comment]
@not-an-aardvark why do you think it would be a breaking change? rules doing negative ranges should be bugs imho. As I mentioned in your PR, it wasn't applying the correct fix with `padded-blocks`, it was still inserting the '\n' at the wrong place.

**Comment by mysticatea** [comment]
In fact, I was planning to make PR (a breaking change) to add the assertion check of negative ranges after #8117.

**Comment by mysticatea** [comment]
Ok, I remembered our semver policy now.

As [our semver policy](https://github.com/eslint/eslint#semantic-versioning-policy), "A bug fix in a rule that results in ESLint reporting more errors." is minor version. If an autofix goes ignored, `eslint --fix` command would show more errors. So I think this should be in a minor change, this PR needs `Update:` prefix for our build script.

**Comment by alberto** [comment]
PR updated to remove temporary fix in https://github.com/eslint/eslint/pull/8117
Commit tag changed to "Update"

**Comment by alberto** [comment]
@mysticatea fwiw I don't think the semver policy should apply to running `--fix`.

In this case, if you run `eslint --fix` without this change and it modifies the code so it will no longer report certain fix, the state of your code will be different. Then, running `eslint` in this new state would result in the same number of warnings, with or without this change.

**Pull request merged**
