### PR TITLE
Fix: rule no-duplicate-case problem with CallExpressions. (fixes #2499)

### LINKED ISSUE #2499: no-duplicate-case false positives with CallExpressions
The `getHash` function of the `no-duplicate-case` rule does not include CallExpressions so the rule will report false positives when using function calls in case statements.

Some examples:

```
var a = 1,
    f = function(b) {
        return b ? {
            p1: 1
        } : {
            p1: 2
        };
    };

switch (a) {
    case f(true).p1:
        break;
    case f(true, false).p1:
        break;
    default:
        break;
}
```

```
var a = 1,
    f1 = function() {
        return {
            p1: 1
        }
    },
    f2 = function() {
        return {
            p1: 2
        }
    };

switch (a) {
    case f1().p1:
        break;
    case f2().p1:
        break;
    default:
        break;
}
```

```
var a = 1,
    f = function(s) {
        return {
            p1: s
        }
    };

switch (a) {
    case f(a + 1).p1:
        break;
    case f(a + 2).p1:
        break;
    default:
        break;
}
```
Related issue: https://github.com/eslint/eslint/issues/2038

### PR DESCRIPTION
**Pull request by matz3**
Fixes issue #2499

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Could you sign our cla here: http://eslint.org/cla/

**Comment by matz3** [comment]
Should be already done. I've submitted it before uploading the PR.

I just noticed that this fix does not include this case:

```
var a = 1,
    f = function(s) {
        return {
            p1: s
        }
    };

switch (a) {
    case f(a + 1).p1:
        break;
    case f(a + 2).p1:
        break;
    default:
        break;
}
```

I will adopt my code to support also that case.

**Comment by nzakas** [comment]
Is this good for review now?

**Comment by matz3** [comment]
Yep :+1:

**Comment by nzakas** [comment]
Lgtm, thanks

**Pull request merged**
