### PR TITLE
Docs: Add spaced-line-comment deprecation notice

### PR DESCRIPTION
**Pull request by btmills**

### CODE REVIEW

**Comment by nzakas** [comment]
This likely won't go out until 1.0.0... Isn't that to late?

**Comment by btmills** [comment]
This and #2905 should've been part of the PRs that originally deprecated those rules, but we missed it, though there are deprecation notices elsewhere (in the index, for example). I really don't want to carry an already-deprecated rule across into 1.0, but I think we can still do it: either cherry-pick these and do an 0.24.1 release, or we'll have the notices in the first 1.0 RC, but perhaps they won't have been removed by #1898 by then?

**Comment by nzakas** [comment]
The RC release won't update the docs because it won't make sense for most people. We'd have to do a separate release for docs, so cherry pick this and the other doc changes to the 0.x branch and do a gensite from there (without a release).

**Comment by btmills** [comment]
I'd be okay with cherry picking and updating docs from 0.x.

**Comment by nzakas** [comment]
Okay, merged. Do you want to do the cherry-pick?

**Comment by btmills** [comment]
I'm away from my laptop right now, but if it hasn't been done by the time I get back in a little bit I'm happy to do it and update here when it's done.

**Comment by nzakas** [comment]
@ilyavolodin has volunteered to do it

**Comment by ilyavolodin** [comment]
Done

**Pull request merged**
