### PR TITLE
Update: add option to ignore unused variables in array pattern decls

### PR DESCRIPTION
**Pull request by Nokel81**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Added an option (default false) to the `no-unused-var` rule to allow for unused variables in constructs of the following shape: `const [a, b] = [1, 2]; b;`. Namely, ignoring the unused variable `a`.

#### Is there anything you'd like reviewers to focus on?
Whether I added enough test cases.

### CODE REVIEW

**Comment by ljharb** [comment]
@Nokel81 why would you need this? `const [, b] = [1, 2]` works just fine.

**Comment by Nokel81** [comment]
for when you want to name it for code readability.

**Comment by ljharb** [comment]
Can you provide an example that's more than just "a" and "b" that would help explain how it aids readability to have an unused variable?

**Comment by Nokel81** [comment]
Sure, I have something like the following code:

```typescript
  const values = Object.values(metrics).map(metric =>
    normalizeMetrics(metric).data.result[0].values
  );
  const [
    memoryUsage,
    memoryRequests,
    memoryLimits, // eslint-disable-line no-unused-vars
    memoryCapacity,
    cpuUsage,
    cpuRequests,
    cpuLimits, // eslint-disable-line no-unused-vars
    cpuCapacity,
    podUsage,
    podCapacity,
    fsSize,
    fsUsage
  ] = values;
```

It would be really hard to read if we had only `,` there.

**Comment by ljharb** [comment]
Seems like it'd be much easier to read like this (assuming the variable names match the key names):
```js
const normalized = Object.fromEntries(Object.entries(metrics).map(([name, metric] => [
    name,
    normalizeMetrics(metric).data.result[0].values,
]));
const {
  memoryUsage,
  memoryRequests,
  memoryCapacity,
  cpuUsage,
  cpuRequests,
  cpuCapacity,
  podUsage,
  podCapacity,
  fsSize,
  fsUsage
} = normalized;
```

Also, that avoids relying on object key ordering, which is less brittle.

**Comment by Nokel81** [comment]
Ah I see thanks. Will close this then.

**Comment by jeanpaulc** [comment]
@ljharb Would you reconsider rep-opening this? TS recently merged a similar feature update for the `--noUnusedLocals` flag https://github.com/microsoft/TypeScript/pull/41378

**Comment by ljharb** [comment]
@jeanpaulc it's not up to me, but typescript can determine things that are impossible for eslint to determine, so i still don't think it's useful in eslint.

**Pull request closed without merging**
