### PR TITLE
Add framework option in the config initializer

### PR DESCRIPTION
**Pull request by Gillespie59**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ x ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
The first time I have tested the config initializer, I saw the possibility to install react plugin. In this PR, I propose to add a framework option in order to select the web framework you use in your application. For the moment, I only support React and AngularJS (I have created few years ago the AngularJS plugin for eslint)

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the pull request!

Hmm, I'm not sure I like this proposal. I think we ask about `React` because it is generally accompanied by JSX syntax, and `eslint-plugin-react` contains a lot of  rules relevant to  JSX. That's not the case for Angular, since it isn't as closely tied to a specific syntax.

The goal of the question is to help the user lint a particular syntax, not to try to guess the user's frontend framework. (Many users will neither be using React nor Angular -- they might not even be writing code for the browser at all.) It would be nice to have an easy way for users to find applicable plugins for their project, but I don't think making the `--init` helper present a choice of frameworks is the best way to do that.

**Comment by Gillespie59** [comment]
I understand. But in this case, in my opinion, the react plugin should not be proposed.

**Comment by nzakas** [comment]
> The goal of the question is to help the user lint a particular syntax, not to try to guess the user's frontend framework. 

Agree. I don't think we want to get into the business of managing lists of frameworks in ESLint. JSX is the special case here, and the followup question about React is there because we kept getting issues filed about ESLint not working as expected with React projects because we don't support React semantics. Adding this question installs the React plugin that fixes those problems and therefore saves us time triaging duplicate issues. 

Thanks for the submission, though I'm a :-1: for inclusion. In the future, you may want to consider opening an issue to request feedback first before implementing.

**Comment by Gillespie59** [comment]
I understand.  thanks for the project btw

**Pull request closed without merging**
