### PR TITLE
New: Add autofix to "default-case" rule

### PR DESCRIPTION
**Pull request by markokajzer**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [ ] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[x] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

+ Added an autofix to the `default-case` rule
+ Simplified checking if the switch statement already has a default case

#### Is there anything you'd like reviewers to focus on?

+ Does this make sense, or might this be considered an annoyance?

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Hi @markokajzer, thanks for the PR!

I personally don't think that this rule should be auto-fixable, for two reasons: 

* We can't know would the user prefer to insert an empty `default:` or a `// no default` comment.
* auto-fix could mask a bug - a missing meaningful `default:`.

This fix might make more sense as a [suggestion](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions), though the rule probably wouldn't be able to suggest a comment as well since the configuration for allowed comments is a regex. I'm not sure would it be helpful enough to suggest only `default: break;` (which could also trigger a `no-fallthrough` error if the last `case` doesn't have `break;`).

Curious to know what other team members think about this proposal.

**Comment by markokajzer** [comment]
Hello there and thank you for your time! You definitely mention some points that I thought about as well. I just wanted to tinker with the project a bit and thought it'd be useful for me if the default case was inserted automatically.

I agree that a suggestion could make more sense, if at all the team decides this is useful. :)

**Comment by nzakas** [comment]
I’m also of the mind that it doesn’t make sense to add autofixing to this rule. I’m not sure a suggestion makes sense either as the reason for not having a default case can’t really be discerned.

**Comment by markokajzer** [comment]
We can close the PR then :)

**Pull request closed without merging**
