### PR TITLE
Add exceptions to eslint's comma-style rule.

### PR DESCRIPTION
**Pull request by estk**
This is an amended PR.

### CODE REVIEW

**Comment by nzakas** [comment]
Looks reasonable to me. We'd need you to document these changes in the rule's documentation, squash your commits, sign the CLA (http://eslint.org), and format your commit message correctly. Please read over http://eslint.org/docs/developer-guide/contributing.html for more details.

**Comment by estk** [comment]
Great! I've already signed the cla, and I've updated the docs.

**Comment by nzakas** [comment]
Thanks, can you rebase to get rid of the build error?

**Comment by estk** [comment]
Rebased.

**Comment by nzakas** [comment]
Thanks, this looks really good. I'm going to hold off on merging because we might have one more patch release.

**Comment by evansimmons-ck** [comment]
Great, thanks so much for considering this!

**Comment by estk** [comment]
Great, thanks so much for considering this!

**Pull request merged**
