### PR TITLE
Upgrade: globals@11.7.0

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Other, please explain:

**What changes did you make? (Give an overview)**
upgrade globals@11.7.0, added bigint.

**Is there anything you'd like reviewers to focus on?**
no~

### CODE REVIEW

**Comment by platinumazure** [comment]
I'm okay with merging this in, but I'll ask: Do we want to wait until bigint is stage 4? (Not sure if the globals are included as part of the proposal or not.)

**Comment by silverwind** [comment]
BigInt also introduces new syntax for BigInt literals, so having the globals is only half the story.

**Comment by not-an-aardvark** [comment]
I don't think this particular PR needs to wait for stage 4, it's just a dependency upgrade that users will already be getting now anyway. This seems unrelated to whether we support BigInt literals.

**Comment by Aladdin-ADD** [comment]
I'm going to merge this if no objection.  /cc @platinumazure 
just want to make clear: it's simply a dep upgrade -- doesn't mean we support bigInt officially.

**Comment by platinumazure** [comment]
No objections, go ahead. Thanks!

**Pull request merged**
