### PR TITLE
Fix: delete unnecessary duplicated question (fixes #11617)

### LINKED ISSUE #11617: Format question asked twice when initializing configuration
**Tell us about your environment**

* **ESLint Version:**

5.16.0

* **Node Version:**

10.15.0

* **npm Version:**

6.8.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

When running config initialization wizard, `What format do you want your config file to be in?` appeared twice. This seems to be unnecessary.

スクリーンショット 2019-04-14 13 12 43

**What did you expect to happen?**

The latter question should not appear.

**What actually happened? Please include the actual, raw output from ESLint.**

Format question asked twice

**Are you willing to submit a pull request to fix this bug?**

Yes

### PR DESCRIPTION
**Pull request by 7ma7X**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

fix #11617 

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by platinumazure** [comment]
Hi @7ma7x, thanks for contributing!

Out of curiosity, was there a particular reason for choosing to delete the second version of the question? Was it just because it was the second one? Or have you considered the flow of questions and consider the first location to make more sense overall?

I personally could see an argument for asking this question last, as the answer has no bearing on anything else except for the writing of the config file.

**Comment by g-plane** [comment]
The second one seems duplicated.

**Comment by 7ma7X** [comment]
@platinumazure 

The latter question will appear only if you choose `Answer questions about your style` to the question `How would you like to define a style for your project?`. 
As the format question must be present in any case, the former question should be left as it is, I guess.

**Comment by platinumazure** [comment]
@7ma7X Awesome answer! Thanks for humoring me. :smile:

**Comment by 7ma7X** [comment]
modified commit message to keep with the commit-message guidlines

**Pull request merged**
