### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pure-js**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Rewrite code using npx feature introduced in npm@5.2.0

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by platinumazure** [comment]
I'm not sure we can make this change yet... We still support Node v6, which ships with npm v3 by default.

@eslint/eslint-team Thoughts?

**Comment by alberto** [comment]
Unfortunately, running `npx eslint` will install the package globally if it is not already present which could cause issues with our resolution system, so I am a bit hesitant to recommend using it.

**Comment by not-an-aardvark** [comment]
Actually, `npx eslint` temporarily does a local installation, so it shouldn't cause any problems.

However, I'm still not sure we should recommend it because it's not supported with npm3.

**Comment by michaelficarra** [comment]
Wouldn't `npx` use the latest version instead of the version specified in the `devDependencies`? I think this is simply incorrect.

**Comment by not-an-aardvark** [comment]
Based on the [documentation](https://www.npmjs.com/package/npx):

> By default, npx will check whether <command> exists in $PATH, or in the local project binaries, and execute that. If <command> is not found, it will be installed prior to execution.

So when the package is already installed, it's effectively a shorthand for prefixing a command with `node_modules/.bin`. When the package is not installed, it installs the package and then runs it. I think the second case isn't relevant to our documentation here because we tell the user to install it first.

**Comment by platinumazure** [comment]
I'm still thinking we probably shouldn't make this change because Node 6 comes with npm 3 by default. Anyone want to make the case for including this change?

**Comment by platinumazure** [comment]
Closing as we can't make this change while we support Node 6. If you would like us to consider this change later on, please feel free to create an issue. Thanks for the contribution regardless, we really appreciate it!

**Pull request closed without merging**
