### PR TITLE
Fix: `isPathIgnored` now considers extensions (fixes #4462)

### LINKED ISSUE #4462: `isPathIgnored()` should consider extension
It seems reasonable that the `CLIEngine`'s [`isPathIgnored()`](http://eslint.org/docs/developer-guide/nodejs-api#ispathignored) method should return `true` for files that don't match the extensions given to `CLIEngine`. 

```js
> eslint = require('eslint')
> cli = new eslint.CLIEngine()
> cli.options.extensions
[ '.js' ]
> cli.isPathIgnored('.git/index')
false
```

This is causing `eslint-watch` to lint files such as `.git/index` or `npm-debug.log` when files are changed. See: https://github.com/rizowski/eslint-watch/issues/52, https://github.com/rizowski/eslint-watch/blob/4b28d0d811b2c52713b52a51c44726daf51f3f09/src/watcher.js#L36-L39

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28325974-ispathignored-should-consider-extension?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kentor**
fixes #4462

### CODE REVIEW

**Comment by kentor** [comment]
Hmm perhaps `IgnoredPaths` should be changed instead of `isPathIgnored`?

**Comment by ilyavolodin** [comment]
If it's easy enough to change `IgnoredPaths` I would do that, since it would probably improve performance slightly.

**Comment by nzakas** [comment]
Yeah, that's better.

**Comment by kentor** [comment]
ok, i'll work on this when I have some time tomorrow

**Comment by kentor** [comment]
Actually to me it feels kind of weird to be checking extensions in IgnorePaths since that class seems to be mainly concerned with the eslintignore file.

**Comment by nzakas** [comment]
You were there one who suggested this change, are you saying you don't want it now?

**Comment by kentor** [comment]
I guess so. After I've taken a closer look at the code a bit I'm not sure if I want to expand the responsibility of the `IgnoredPaths` class to account for extensions, seeing as the class is described as `Responsible for loading ignore config files and managing ignore patterns`.

Also adding extensions checking may potentially break `executeOnText`?

Anyway I'm fine with it not changing at all since extensions checking is pretty trivial in user land since we have access to it via `cli.options.extensions`.

**Comment by nzakas** [comment]
Good points. I agree, let's not do this. Thanks for sharing your insights.

**Pull request closed without merging**
