### PR TITLE
Fix: valid-jsdoc error with square braces (fixes #2270)

### LINKED ISSUE #2270: Error in valid-jsdoc.js
```
TypeError: Cannot call method 'indexOf' of undefined
    at C:\Users\Cornelius\Documents\GitHub\red\node_modules\eslint\lib\rules\valid-jsdoc.js:107:45
```

Kind regards, 
Cornelius

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10793184-error-in-valid-jsdoc-js?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
This looks like it's just adding unit tests. Was the issue fixed in doctrine?

**Comment by gyandeeps** [comment]
@ilyavolodin Yes.

**Comment by nicjansma** [comment]
Can you share?  I don't see it in the commit log.

**Comment by gyandeeps** [comment]
Here is the doctrine PR which has the fix: https://github.com/eslint/doctrine/pull/126

**Pull request merged**
