### PR TITLE
Breaking: Remove JSX support from no-undef (fixes #2093)

### LINKED ISSUE #2093: no-undef does not check Node.js scope for variables used in JSX
no-undef does not check Node.js scope for variables used in JSX

test.js

```javascript
var App = require('App');

module.exports = <App />
```

.eslintrc

```yaml
env:
    node: true
ecmaFeatures:
    jsx: true
rules:
    no-undef: 2
```

Output:

```bash
test.js
  3:18  error  'App' is not defined                                                 no-undef

✖ 1 problem (1 error, 0 warnings)
```

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM

**Comment by BerkeleyTrue** [comment]
Looks like both of these have been merge. Will wait to test next release of eslint to close this.

**Comment by framerate** [comment]
Is their an ETA on this fix going out? Please point me to any notes on the next release! Thanks!

**Comment by nzakas** [comment]
Tentatively this weekend

**Comment by framerate** [comment]
Awesome! Good luck, @nzakas ! Thanks so much!

**Pull request merged**
