### PR TITLE
Update: make camelcase rule fixable

### PR DESCRIPTION
**Pull request by edwardkenfox**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[x] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What rule do you want to change?**

[camelcase](https://github.com/eslint/eslint/blob/ff8c4bb7fab10ada8a56afb70fd97f18da8258fe/lib/rules/camelcase.js)

**Does this change cause the rule to produce more or fewer warnings?**

No

**How will the change be implemented? (New option, new default behavior, etc.)?**

By implementing a new function to be used from the `fix` property of the `report()` function. 

**Please provide some example code that this change will affect:**

This PR does not affect how the rule validates the given code.

**What does the rule currently do for this code?**

Reports function names, variables and properties & etc. with underscores. 

**What will the rule do after it's changed?**

Remove underscores and uppercase the following character to match the camelcase rule itself when `--fix` option is passed to the eslint CLI.

**What changes did you make? (Give an overview)**

Added a function which is used by the `fixer` object in the `fix` property in the `report()` function.

**Is there anything you'd like reviewers to focus on?**

Whether fixing `__private_first_name` to `__privateFirstName` is acceptable or not. If not, any suggestion would be greatly appreciated.

### CODE REVIEW

**Comment by platinumazure** [comment]
I'm :-1: to this change because it will break developers' integrations with third party libraries that violate this rule. For variables declared by the developer, this fix may be correct, but for variables declared somewhere the developer has no control, this will just be a pain in their rear end.

**Comment by edwardkenfox** [comment]
@platinumazure Thanks for the feedback. I kind of understand what you mean, but just to be clear, is it something like the below you're thinking this change will be problematic? 

```js
// external-library.js
function foo_bar() {};
export { foo_bar };
```

```js
// app.js
import { foo_bar } from 'external-library';
```

In the above case, importing `foo_bar()` will violate camelcase rule, which, I believe, is the case anyways with or without the autofix. So, the developer would have to either disable eslint for each line or not use the camelcase rule. That said, I'm assuming that introducing autofix will only take affect on application code that will do no harm to the names that developers do not have control of. 

I am fairly new to eslint, so let me know if I'm missing anything.

**Comment by platinumazure** [comment]
@edwardkenfox You are right that ES6 style imports do allow for local renaming. This is true for CommonJS requires as well. However, sometimes a user is stuck having to use globals to communicate with libraries, and those globals might be controlled by the libraries.

I might be persuaded to :+1: this enhancement if it guaranteed that a truly global variable (not declared within the file) would not be autofixed, but explicit local declarations (including via CommonJS requires and ES6 imports) could be autofixed.

**Comment by edwardkenfox** [comment]
@platinumazure Understood, thanks a lot for the clarification. Will look into other rules to see if there's anything similar to this situation, if not come up with a solution myself.

**Comment by nzakas** [comment]
I'm afraid that this is a case where autofixing is not appropriate, as we can't possibly do this in such a way that it makes sense for every ESLint user. This was proposed a while back and we opted not to do it: 
https://github.com/eslint/eslint/issues/3730

For your use case, I'd suggest using a Babel plugin or a JS code shift instead. That way, you can narrowly specify what you want changed and where, and it's a much better solution for one-off large scale changes like this. 

:-1:

**Comment by edwardkenfox** [comment]
@nzakas Thanks for the reference and further explaining, now I clearly see why this isn't appropriate. I will look into jscodeshift, but for now I'll just use my forked version to satisfy my needs.

**Pull request closed without merging**
