### PR TITLE
Fix: nested indenting for offsetTernaryExpressions: true (fixes #13971)

### LINKED ISSUE #13971: Extra indenting in a nested ternary with offsetTernaryExpressions: true from Standard JS config
**Tell us about your environment**

* **ESLint Version:** 7.16.0
* **Node Version:** 14.5.3
* **npm Version:** 6.14.9

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

default

**Please show your full configuration:**

Here is the configuration from my work in <https://github.com/brodybits/react-native-module-init/pull/85> but with Prettier items removed since they are not needed to reproduce this issue:

<details>
<summary>Configuration</summary>

```js
parserOptions:
  ecmaVersion: 9

extends:
  - standard

plugins:
  - jest

env: { jest/globals: true }
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Reduced reproduction code that I made in a local `mock.test.js` file:

```js
const mockCallSnapshot = []

jest.mock('execa', () => (cmd, args, opts) => {
  mockCallSnapshot.push({ execa: [cmd, args, opts] })
  return cmd === 'git'
    ? args[1] === 'user.email'
      ? Promise.resolve({ stdout: 'alice@example.com' })
      : Promise.resolve({ stdout: 'Alice' })
    : Promise.resolve()
})
```

```bash
npx eslint mock.test.js
```

**What did you expect to happen?**

no errors

**What actually happened? Please include the actual, raw output from ESLint.**

```
/Users/brodybits/dev/react-native-module-init/mock.test.js
  7:1  error  Expected indentation of 8 spaces but found 6  indent
  8:1  error  Expected indentation of 8 spaces but found 6  indent

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

`npx eslint --fix mock.test.js` updates the code with extra indenting in the nested ternary like this:

```js
const mockCallSnapshot = []

jest.mock('execa', () => (cmd, args, opts) => {
  mockCallSnapshot.push({ execa: [cmd, args, opts] })
  return cmd === 'git'
    ? args[1] === 'user.email'
        ? Promise.resolve({ stdout: 'alice@example.com' })
        : Promise.resolve({ stdout: 'Alice' })
    : Promise.resolve()
})
```

I was able to reproduce this issue more simply with the following fragment in the test suite:

```js
        {
            code: unIndent`
              condition1
                ? condition2
                  ? Promise.resolve(1)
                  : Promise.resolve(2)
                : Promise.resolve(3)
            `,
            options: [2, { offsetTernaryExpressions: true }]
        },
```

**Are you willing to submit a pull request to fix this bug?**

Yes.

I was able to make a one-line fix based on bb6cf50826 (PR #12556) by @sheerun:

<details>
<summary>One-line fix</summary>

```diff
--- a/lib/rules/indent.js
+++ b/lib/rules/indent.js
@@ -1178,6 +1178,7 @@ module.exports = {
                     offsets.setDesiredOffset(colonToken, firstToken, 1);
 
                     offsets.setDesiredOffset(firstConsequentToken, firstToken,
+                        firstConsequentToken.type === "Punctuator" &&
                         options.offsetTernaryExpressions ? 2 : 1);
 
                     /*
```

</details>

This issue is in follow-up to the offsetTernaryExpressions option contributed in PR #12556 and has led to <https://github.com/standard/standard/issues/1624>.

/cc @sheerun

### PR DESCRIPTION
**Pull request by brodybits**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

resolves #13971

This update applies one more condition for the consequent to avoid extra indenting in a nested ternary expression like this:

```js
condition1
  ? condition2
    ? Promise.resolve(1)
    : Promise.resolve(2)
  : Promise.resolve(3)
```

Note that the condition was mostly copied from the condition that @sheerun had included for the alternate in PR #12556 (bb6cf5082623ffb67bb1495fee52c0610ee5f421).

#### Is there anything you'd like reviewers to focus on?

I hope there is enough information in issue #13971 to explain the issue and in this PR to understand the solution. I would be happy to add some more test cases and documentation updates if needed.

This PR can help unblock the following issues and updates in some other projects:

- https://github.com/standard/standard/issues/1624
- https://github.com/brodybits/prettierx/issues/41
- https://github.com/sheerun/prettier-standard/issues/76
- https://github.com/brodybits/react-native-module-init/pull/85

### CODE REVIEW

**Comment by sheerun** [comment]
looks good :)

**Comment by brodybits** [comment]
I have rebased and updated the title again to fit within the 72 characters, hope it is good to go. I will not likely be active on GitHub for the next 25-30 hours. Thanks!

**Review by btmills — APPROVED** [review]
LGTM, thanks @brodybits! Glad to see this could be fixed with a single condition.

**Comment by brodybits** [comment]
Much appreciated, this will unblock issues on "Standard JS" and `prettier-standard`.

**Pull request merged**
