### PR TITLE
Update: Deprecate option `maximum` in favor of `max` (fixes #5685)

### LINKED ISSUE #5685: Inconsistent option name: max vs. maximum
The new [max-statements-per-line](http://eslint.org/docs/rules/max-statements-per-line) has `max` option, but other existing rules (including `max-statements`) have `maximum`.

- http://eslint.org/docs/rules/max-statements
- http://eslint.org/docs/rules/max-depth
- http://eslint.org/docs/rules/max-nested-callbacks
- http://eslint.org/docs/rules/complexity
- http://eslint.org/docs/rules/max-params

Is this intentional?

### PR DESCRIPTION
**Pull request by vitorbal**
Add the option name `max` to all rules that currently accept an option
name `maximum` and add deprecation notes to the docs of each of those
rules.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM. The only thing is, I'm not sure we should keep "maximum" examples in the documentation. I don't remember how we handled deprecated options before. @eslint/eslint-team?

**Comment by vitorbal** [comment]
I could remove the `maximum` examples and keep only the deprecation notice for all cases, if you guys prefer.

**Comment by nzakas** [comment]
Yeah, I think we should remove `maximum ` from the examples

**Comment by vitorbal** [comment]
@ilyavolodin @nzakas updated!

**Comment by ilyavolodin** [comment]
@vitorbal Very nice! Thanks for PR

**Comment by vitorbal** [comment]
You're very welcome! Thank you for the awesome project and all the hard work :)

**Pull request merged**
