### PR TITLE
New: add ls-lint

### PR DESCRIPTION
**Pull request by loeffel-io**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [ ] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Other, please explain:

Already in use at [Vue.js 3](https://github.com/vuejs/vue-next) - Adding [ls-lint](https://github.com/loeffel-io/ls-lint) provides a clean project structure/filesystem for the eslint project for all updates and contributions.

```yaml
ls:
    '{bin,conf,lib,messages,packages,templates,tools}':
        .js: kebab-case
        .json: kebab-case
        .htm: kebab-case
        .html: kebab-case
        .txt: kebab-case
```

With this config ls-lint checks all your filenames and directory names inside or behind these directories `bin,conf,lib,messages,packages,templates,tools`

Would love to see this in eslint ❤️

### CODE REVIEW

**Comment by nzakas** [comment]
I’m sorry, your project is only a week old, so I don’t think it’s something we should adopt at this point in time. 

In the future, I’d suggest you mention that you are the author of the tool you’re recommending. It’s good practice to be upfront if you are promoting your own project (there’s nothing wrong with doing so, but letting people know that’s what you’re doing is a good idea).

**Comment by kaicataldo** [comment]
Agreed with @nzakas. While I see the value in this, I think we would want to wait until the tool is more mature.

**Comment by loeffel-io** [comment]
Thank you for your answer, i really appreciate it!

I can understand that my project is, for now, too fresh to merge - I'll keep you updated 👍 

`just fyi: the npm package is only a week old, the project itself started a month ago, is stable and now also a part of` [vant](https://github.com/youzan/vant)

**Comment by kaicataldo** [comment]
Sounds good.

**Pull request closed without merging**
