### PR TITLE
Docs: remove links to terminated jscs.info domain

### PR DESCRIPTION
**Pull request by pkuczynski**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

I removed links to `jscs.info` domain, as they all lead to a site with info

```
The domain jscs.info is for sale. To purchase, call BuyDomains.com at 781-373-6841 or 844-896-7299. Click here for more details.
```

**Is there anything you'd like reviewers to focus on?**

Nope

### CODE REVIEW

**Comment by pkuczynski** [comment]
You welcome :)

**Comment by not-an-aardvark** [comment]
Thanks!

**Comment by cup** [comment]
@not-an-aardvark not all instances were caught?

https://github.com/eslint/eslint/blob/master/docs/rules/padding-line-between-statements.md

**Comment by kaicataldo** [comment]
@cup Thanks for the info!. Would you like to make a PR?

**Comment by pkuczynski** [comment]
I will fire up a PR in a sec...

**Pull request merged**
