### PR TITLE
Build: Allow revert commits in commit messages (fixes #4452)

### LINKED ISSUE #4452: Allow revert commits in commit message verification
When we revert a PR using the GitHub web interface, it automatically creates a commit message of the form `Revert "Update: Add JSX exceptions to no-extra-parens (fixes #4229)"`. This caused #4450 to fail Travis. The commit message verification step should allow this format for commit messages.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28293792-allow-revert-commits-in-commit-message-verification?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
If I'm not mistaken (only done it once or twice and a while ago), you can't control the title of the Revert commit in Github. The default format is `Revert "old commit message"` so this will not help.

**Comment by alberto** [comment]
Oh, you mean because of the trailing semicolon, right?

**Comment by alberto** [comment]
Ok, I excluded all the checks for reverts.

**Comment by ilyavolodin** [comment]
Yeah, this looks better. Thanks!

**Pull request merged**
