### PR TITLE
feat: Allow ignoring rest sibling variables

### PR DESCRIPTION
**Pull request by IchordeDionysos**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain: Changes the recommended rules

#### What changes did you make? (Give an overview)

Enabled the option `ignoreRestSiblings` in the default ESLint config.

#### Is there anything you'd like reviewers to focus on?

https://github.com/eslint/eslint/discussions/18488

### CODE REVIEW

**Review by Tanujkanti4441 — COMMENTED** [review]
Hi @IchordeDionysos, thanks for the PR can you please give some examples or reason why this option should be true by default even though it can be changed when needed?
also can you sign the CLA as well?

**Review by Tanujkanti4441 — CHANGES_REQUESTED** [review]

**Review by mdjermanovic — COMMENTED** [review]
Can you please clarify whether the intent is to change the default for this option in the rule, or in the eslint:recommended config, or in `eslint-config-eslint`?  Note that this PR updates [`eslint-config-eslint`](https://www.npmjs.com/package/eslint-config-eslint), which is a configuration used for projects maintained by the ESLint team.

**Comment by IchordeDionysos** [comment]
@mdjermanovic 
I wanted to change `eslint:recommended`.
This was the only thing I was able to find. It's really hard to figure out what the recommended rules are and where they are defined.

**Comment by mdjermanovic** [comment]
The `eslint:recommended` configuration is here:

https://github.com/eslint/eslint/blob/main/packages/js/src/configs/eslint-recommended.js

But while our [semver policies](https://github.com/eslint/eslint?tab=readme-ov-file#semantic-versioning-policy) technically allow updates in `eslint:recommended` that result in strictly fewer linting errors to be made in minor releases, I think this kind of change would be more suitable for a major release, and we prefer to change the default value for option directly in the rule rather than in `eslint:recommended`, so I think the best course of the action at this point would be to open an issue so the team can discuss this change for the next major release.

**Pull request closed without merging**
