### PR TITLE
docs: place the playground button in the bottom right corner

### PR DESCRIPTION
**Pull request by kecrily**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Removes large white space from the code block.

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>

  <tr>
    <td>
image</td>
    <td>
image
</td>
  </tr>
</table>

### CODE REVIEW

**Comment by nzakas** [comment]
It does look a bit better this way, but I think we'll need to adjust the styles in light mode:

Screenshot 2023-12-13 at 10-56-14 getter-return - ESLint - Pluggable JavaScript Linter

I think the button needs a shadow or border to help make the edges clearer

**Comment by kecrily** [comment]
image

**Comment by fasttime** [comment]
I can see that after this change there will be extra empty space after all code blocks, even if there is no Playground button:

| Now | After |
|--------|------|
| image | image |

Is this intended?

**Comment by mdjermanovic** [comment]
IMO, it looks better when the button is in the code block. Also, if the button is over the border, when the horizontal scroll bar appears (usually it does on small screens, e.g. mobile), the button will overlap with it:

image

**Comment by kecrily** [comment]
> Is this intended?

@fasttime Yes, to avoid overlapping with other content on a small screen. But it shouldn't be found in a normal code block. now adjusted.

> IMO, it looks better when the button is in the code block. Also, if the button is over the border, when the horizontal scroll bar appears (usually it does on small screens, e.g. mobile), the button will overlap with it:

@mdjermanovic I fixed it. The scrollbar now no longer overlaps the buttons.

**Comment by Tanujkanti4441** [comment]
Screenshot 2023-12-17 222423

in my browser i have different scrollbar is it looking fine?

**Comment by kecrily** [comment]
> in my browser i have different scrollbar is it looking fine?

There's nothing wrong with its position, but it doesn't look very good.

**Comment by harish-sethuraman** [comment]
I feel like something like this on hover would be better with help text open in playground probably? 
Screenshot 2023-12-18 at 4 30 51 PM

we could use something like this to denote correct and in correct instead? 

Screenshot 2023-12-18 at 4 32 02 PM


end output would be somewhere close to this? (😅  edited entire thing in inspect tools design could be better). 
Why I'd prefer something like this is because,
-  we show a link to playground when we hover on code sample so it doesn't obstruct the view?   
- the correct in correct doesn't float anymore and lives more with the code block itself

Screenshot 2023-12-18 at 5 23 09 PM

**Comment by Tanujkanti4441** [comment]
i like the last design and instead of keeping that playground button in the code block we can place it to the correct/incorrect block with the `playground` name.

**Comment by nzakas** [comment]
This PR was just to move the button -- there's no good reason to change the overall design of the correct/incorrect code examples. If we can't agree on moving the button, then we should just close this PR.

**Comment by Tanujkanti4441** [comment]
if we shift the button to the bottom right corner we will end up with the same overlapping problem which we had previously

Screenshot 2023-12-23 201015

**Comment by amareshsm** [comment]
> if we shift the button to the bottom right corner we will end up with the same overlapping problem which we had previously
> 
> Screenshot 2023-12-23 201015

Yes we need to consider. Boz of this issue we decided to place the button inside the block in https://github.com/eslint/eslint/pull/17403

**Comment by kecrily** [comment]
This button is floating. It does not interfere with reading. And even if you don't move the button to the bottom right corner, it obscures the correct/incorrect icon.

image

**Comment by Tanujkanti4441** [comment]
> Back to top button is floating. It does not interfere with reading, just slide up or down. And even if don't move the button to the bottom right corner, it still overlaps the correct/incorrect icon.
> image

[comment](https://github.com/eslint/eslint/issues/17646#issuecomment-1780049570), as per this comment it is okay if button overlaps the things which  can't be clicked.

**Comment by kecrily** [comment]
image

Is this OK?

**Comment by nzakas** [comment]
Folks - this discussion has been going on for a while, so my vote is just to leave the button as-is. If it was an easy fix, that would be one thing, but we're continuing to run into edge cases and I just don't think it's worth the effort to continue down this path.

Thoughts?

**Comment by harish-sethuraman** [comment]
I'd also vote on keeping the same layout 👍🏻

**Comment by nzakas** [comment]
All right, let's just keep what we have. I appreciate the suggestions and work, but let's move on to more interesting problems. :)

**Pull request closed without merging**
