### PR TITLE
add functionsWithThis option for prefer-arrow-callback

### PR DESCRIPTION
**Pull request by hax**

### CODE REVIEW

**Comment by gyandeeps** [comment]
@hax Thans for the PR.
* Please sign our CLa if you have not done it already.
* Can you also update the docs with the option for the rule.
    * Reference any existing documents of rules with options to get an idea on how to go about documenting rule options.

**Comment by nzakas** [comment]
@hax are you still working on this?

**Comment by hax** [comment]
Sorry I took a holiday last week and forgot this :snail:

**Comment by nzakas** [comment]
No problem, do you have an idea when you'll work on this again! No pressure, just trying to plan our release.

**Comment by alberto** [comment]
@hax do you still intend to complete this?

**Comment by ilyavolodin** [comment]
This commit hasn't been updated in over a month. I'm going to close this. @hax if you want to finish this PR at any point, please open a new PR whenever you made the changes requested. Thanks!

**Pull request closed without merging**
