### PR TITLE
Fix: `id-length` does not work for most of the new ES6 patterns (fixes #3286)

### LINKED ISSUE #3286: id-length rule does not detect all possible cases for defining identifiers
Forked off of #3282, specifically https://github.com/eslint/eslint/pull/3282#issuecomment-127937612 reported by @mysticatea 

`id-length` rule does not support the following cases:

       {
            code: "class x { }",
            ecmaFeatures: {classes: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "class Foo { x() {} }",
            ecmaFeatures: {classes: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "function foo(x = 0) { }",
            ecmaFeatures: {defaultParams: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "function foo(...x) { }",
            ecmaFeatures: {restParams : true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "var {x} = {};",
            ecmaFeatures: {destructuring: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "var {a: [x]} = {};",
            ecmaFeatures: {destructuring: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "import x from \"x\";",
            ecmaFeatures: {modules: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "export var x = 0;",
            ecmaFeatures: {modules: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "({a: obj.x}) = {};",
            ecmaFeatures: {destructuring: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        }

### PR DESCRIPTION
**Pull request by BYK**

### CODE REVIEW

**Comment by BYK** [comment]
No idea why node 0.12 build failed. Says it timed out but may be a rebuild would fix it?

**Comment by ilyavolodin** [comment]
Kicked off a force rebuild. Let's see if it fixes it.

**Comment by BYK** [comment]
@ilyavolodin - thanks! Looks like that solved it.

**Comment by ilyavolodin** [comment]
LGTM. Want another set of eyes on this though. Hard to do code reviews from work machine.

**Comment by nzakas** [comment]
LGTM

**Pull request merged**
