### PR TITLE
Add VS to integrations

### PR DESCRIPTION
**Pull request by MariaSolOs**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Adding Visual Studio to the list of editor integrations.

#### Is there anything you'd like reviewers to focus on?
Nope.

### CODE REVIEW

**Comment by kecrily** [comment]
Thanks for your contribution, but you seem to have missed signing the CLA

**Comment by MariaSolOs** [comment]
> Thanks for your contribution, but you seem to have missed signing the CLA

Will do that right away!

**Review by kecrily — APPROVED** [review]

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by MariaSolOs** [comment]
@mdjermanovic I still don't see the changes reflected on the website. When should I expect to see this change?

Thanks!

**Comment by mdjermanovic** [comment]
The `latest` version of the docs will be updated after the [next release](https://github.com/eslint/eslint/issues/16351).

The `head` version is updated after each commit to the main branch. You can see the change here:

https://eslint.org/docs/head/user-guide/integrations

**Comment by MariaSolOs** [comment]
@mdjermanovic got it, thanks for explaining!

**Pull request merged**
