### PR TITLE
wip: Chore: switch to eslint-plugin-jsdoc (refs #11146)

### PR DESCRIPTION
**Pull request by aladdin-add**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x ] Other, please explain:

**What changes did you make? (Give an overview)**
start to using `eslint-plugin-jsdoc`, since `valid-jsdoc` and `require-jsdoc` has been deprecated.

**Is there anything you'd like reviewers to focus on?**
just a wip, we might have to disable some rules in `jsdoc/recommended`, since there is a large number of linting errors to fix.

the original errors: https://ci.appveyor.com/project/nzakas/eslint/builds/20697383

### CODE REVIEW

**Comment by kaicataldo** [comment]
I think we should maybe not rely on the `recommended` ruleset and just enable specific rules we want to have parity (or at least close to it) in our config.

**Comment by Aladdin-ADD** [comment]
It would be great if there is a new ruleset in `eslint-plugin-jsdoc` -- mapping the core rules to the plugin rules. (related issue: https://github.com/gajus/eslint-plugin-jsdoc/issues/107).

**Comment by kaicataldo** [comment]
According to https://github.com/gajus/eslint-plugin-jsdoc/issues/107#issuecomment-494599620, it looks like those changes have now been released!

**Comment by mysticatea** [comment]
I'm closing this PR since https://github.com/eslint/eslint/pull/12332 has switched to the plugin. Thank you.

**Pull request closed without merging**
