### PR TITLE
Fix: Update object-shorthand.md to fix typo.

### PR DESCRIPTION
**Pull request by B3rry**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Added a closing quotation mark to the option definition on line 92.

**Is there anything you'd like reviewers to focus on?**
No.

### CODE REVIEW

**Comment by gyandeeps** [comment]
Is your eslint fork super old or something?

**Comment by B3rry** [comment]
With regards to the failing builds? Nope. Forked ~30 mins ago via the site.

**Comment by not-an-aardvark** [comment]
It looks like your commit was created off of the year-old `2.13.1` branch, which is why the build is failing. If you rebase onto master, I think the build should pass.

**Comment by not-an-aardvark** [comment]
Oh actually, the issue is that `2.x` is the base branch of this PR for some reason. I think I can update that.

**Comment by not-an-aardvark** [comment]
Temporarily closing/reopening this PR so that the CI builds restart.

**Pull request merged**
