### PR TITLE
Fix: no-mixed-spaces-and-tabs (fixes #4189, fixes #4190)

### LINKED ISSUE #4189: no-mixed-spaces-and-tabs fails on blocklevel comments (regression)
this issue has returned : https://github.com/eslint/eslint/issues/1055
i noticed in eslint 1.7.1

it was fixed in this PR: https://github.com/eslint/eslint/pull/1058/files
possibly regressed by: https://github.com/eslint/eslint/commit/b8a12108f18a40bc98503f431a01879d5f6c43ca

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27515723-no-mixed-spaces-and-tabs-fails-on-blocklevel-comments-regression?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #4190: Rule `no-mixed-spaces-and-tabs` should not apply inside template literals - followup
https://github.com/eslint/eslint/issues/4054 didn't fix all cases.

-

foo.js:

```js
const foo = `${console}
	  foo`;
```

*The second line is `\t  foo`.*

```
~/dev
❯ eslint --version                                                               
1.7.1
                                                                                                                                               
~/dev
❯ eslint foo.js --env=es6 --rule='no-mixed-spaces-and-tabs: 2'

/Users/sindresorhus/dev/foo.js
  2:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs

✖ 1 problem (1 error, 0 warnings)
```

-

Can you just make the rule ignore *everything* inside a template literal?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27518253-rule-no-mixed-spaces-and-tabs-should-not-apply-inside-template-literals-followup?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #4192: no-magic-numbers: UnaryExpression + number is considered as error
Currently following code is considered as error: ```var foo = -42;```
I don't think it should do so

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27519646-no-magic-numbers-unaryexpression-number-is-considered-as-error?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**
Ignore comments and template literals

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM. We should see if we can simplify this code in the future. I think it's doing too many iterations and might be a performance bottleneck on large files. But the fix is fine for now.

**Comment by alberto** [comment]
Please don't merge. I think it is not complete. It is precisely because of trying to optimize it @ilyavolodin. The for loop is run just once.

**Comment by alberto** [comment]
I updated the PR with the unoptimized version and a test exposing the problem with the previous one.

**Comment by nzakas** [comment]
Ready for review?

**Comment by alberto** [comment]
Yes

**Comment by nzakas** [comment]
LGTM

**Pull request merged**
