### PR TITLE
Update: Add env 'nashorn' to support Java 8 Nashorn Engine (fixes #3874)

### LINKED ISSUE #3874: Add support for Java 8 Nashorn JavaScript Engine
Java 8 ships with a new JavaScript engine called **Nashorn**. As the successor of Rhino, Nashorn compiles JavaScript into JVM Bytecode and executes the code natively on the JVM.

Since Nashorn defines a few global variables, Nashorn script files cannot properly validated with the current ESLint Version 1.5.0. I propose to introduce a new environment `nashorn` into ESLint to respect all nashorn-specific global variables as described here:

https://wiki.openjdk.java.net/display/Nashorn/Nashorn+extensions

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26830878-add-support-for-java-8-nashorn-javascript-engine?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by winterbe**
This PR adds new env `nashorn` to support the global variables of the Java 8 Nashorn JavaScript Engine.

### CODE REVIEW

**Comment by winterbe** [comment]
Updated user guide to show new `nashorn` environment.

**Comment by nzakas** [comment]
Thanks, can you also sign our CLA? http://ESLint.org/cla

**Comment by winterbe** [comment]
Done.

**Comment by nzakas** [comment]
Thanks. Going to hold off on merging in case we need a patch release today.

**Comment by winterbe** [comment]
All right. No hurry.

**Comment by ilyavolodin** [comment]
@nzakas I think this can now be merged since a bunch of updates has already been merged, next release will have to be minor.

**Comment by nzakas** [comment]
Yup

**Pull request merged**
