### PR TITLE
Chore: Add GitHub organization to Sponsor button

### PR DESCRIPTION
**Pull request by btmills**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

**What changes did you make? (Give an overview)**

I added the @eslint organization to `FUNDING.yml` so that the "Sponsor" button on the [eslint/eslint](https://github.com/eslint/eslint) repository shows GitHub Sponsors as an option in addition to Open Collective.

**Is there anything you'd like reviewers to focus on?**

The [`FUNDING.yml` docs](https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository) haven't been updated to specifically mention sponsoring teams, so I'm hoping the format for teams is the same as for individual users.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
I don't know if we need both. Github org sponsorship goes through OpenCollective (i.e. all the donations through Github will end up in our OpenCollective account).

**Comment by btmills** [comment]
It seemed weird to me that the Sponsor button on https://github.com/eslint took me to the GitHub Sponsors page, whereas the Sponsor button on https://github.com/eslint/eslint showed a dialog linking to Open Collective. If we're fine with that, then this PR can be closed.

**Comment by platinumazure** [comment]
@btmills Does this PR resolve the inconsistency you described?

**Comment by btmills** [comment]
In theory, merging this would then include the GitHub organization in the Sponsors modal on https://github.com/eslint/eslint, but I can’t verify that ahead of time. My plan, if we want to add this at all, would be to merge this, check the modal, and revert this if it didn’t work.

**Comment by platinumazure** [comment]
I'd love to give users a consistent experience, so I'm :+1: to merging this and testing, but I'll defer to the rest of the team.

**Comment by kaicataldo** [comment]
I agree that we should have all the sponsorship links go to the same destination. Could we solve this problem by putting an additional link to Open Collective on our GitHub Sponsors page and point all the Sponsors links in repositories to that?

**Comment by ilyavolodin** [comment]
@btmills Sorry I wasn't clear. I'm 👍 for adding github as an option, but I think we can remove opencollective from that list, as github will wire all of the money into open collective (basically, github is acting just as an interface).

**Comment by mysticatea** [comment]
> but I can’t verify that ahead of time

For a reference, you can see the preview on https://github.com/eslint/eslint/edit/master/.github/FUNDING.yml

image

**Comment by ilyavolodin** [comment]
Nice find @mysticatea . Here's the link to PR change: https://github.com/eslint/eslint/edit/github-sponsors/.github/FUNDING.yml
I'm actually fine withe the way it looks so, approved.

**Comment by kaicataldo** [comment]
Looks like we have consensus from the TSC. Going to merge!

**Pull request merged**
