### PR TITLE
Fix: Module resolution (fixes #9897)

### LINKED ISSUE #9746: npm 5 link / lerna resolve issue
**Tell us about your environment**

* **ESLint Version:** ``4.13.1``
* **Node Version:** ``8.9.3``
* **npm Version:** ``5.6.0``

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Issue:**
When using Lerna with npm v5, eslint is unable to correctly resolve linked packages.

Example Repo: [chrisblossom/eslint-issue-9746](https://github.com/chrisblossom/eslint-issue-9746)

Updated repo to include both scoped and non-scoped example.

**What actually happened? Please include the actual, raw output from ESLint.**
```js
➜  example git:(master) eslint index.js
Cannot find module '@chrisblossom/eslint-config'
Referenced from: /Users/chris/github/eslint-issue-9746/packages/example/.eslintrc.js
Error: Cannot find module '@chrisblossom/eslint-config'
Referenced from: /Users/chris/github/eslint-issue-9746/packages/example/.eslintrc.js
    at ModuleResolver.resolve (/Users/chris/github/eslint-issue-9746/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/chris/github/eslint-issue-9746/node_modules/eslint/lib/config/config-file.js:471:25)
    at load (/Users/chris/github/eslint-issue-9746/node_modules/eslint/lib/config/config-file.js:542:26)
    at configExtends.reduceRight (/Users/chris/github/eslint-issue-9746/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/chris/github/eslint-issue-9746/node_modules/eslint/lib/config/config-file.js:403:28)
    at loadFromDisk (/Users/chris/github/eslint-issue-9746/node_modules/eslint/lib/config/config-file.js:514:22)
    at Object.load (/Users/chris/github/eslint-issue-9746/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.getLocalConfigHierarchy (/Users/chris/github/eslint-issue-9746/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/Users/chris/github/eslint-issue-9746/node_modules/eslint/lib/config.js:180:43)
```

### LINKED ISSUE #9897: Improve module resolution
**Tell us about your environment**

* **ESLint Version:**
v4.16.0
* **Node Version:**
v9.4.0
* **npm Version:**
v5.6.0

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

This is a follow-up of #9746.
See this repository, which explains the issue: chrisblossom/eslint-issue-9746

**What did you expect to happen?**

ESLint should be able to work inside Lerna projects.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint throws errors regarding module resolutions.

As described here (https://github.com/eslint/eslint/issues/9746#issuecomment-356810436) it seems that this is the expected behaviour, however I'd argue that the changes presented here: #9896 are actually improving the module resolution logic, while fixing #9746.

First, it splits up the `extraLookup` path into multiple paths where modules should be looked for, according to Node module specifications.

Secondly, the change to `getBaseDir` seems pretty straightforward: the `projectPath` should not be a `node_modules` directory.

If those changes are accepted, it would actually resolve issues users have with ESLint and Lerna, while improving the module resolution logic.

### PR DESCRIPTION
**Pull request by ngotchac**
**What is the purpose of this pull request?**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Tell us about your environment**

* **ESLint Version:**
v4.16.0
* **Node Version:**
v9.4.0
* **npm Version:**
v5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Not relevant to this issue

**Please show your full configuration:**
See https://github.com/chrisblossom/eslint-issue-9746

**What did you do? Please include the actual source code causing the issue.**
In some project, specifically using Lerna, ESLint could fail at finding some plugin modules.

**What did you expect to happen?**
ESLint should find the modules.

**What actually happened? Please include the actual, raw output from ESLint.**
ESLint would crash, as explained here: https://github.com/eslint/eslint/issues/9746 and here:
https://github.com/chrisblossom/eslint-issue-9746

**What changes did you make? (Give an overview)**

I modified the `getBaseDir` method in `/lib/config/config-file.js` to return the right 
project path if `eslint` is in the `node_modules` directory of a project.

I modified the Module resolver so that it splits the `extraLookup` value into an
array of directories to check thanks to the standard Node method:  `Module._nodeModulePaths`

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Hi, thanks for the PR.

As described in https://github.com/eslint/eslint/issues/9746#issuecomment-356810436, the current behavior is working as intended. Can you please create an issue describing the new behavior that you're proposing, and how it would solve the problem that was described in https://github.com/eslint/eslint/issues/9746? Based on the guidelines [here](https://eslint.org/docs/developer-guide/contributing/pull-requests#getting-started), we require an issue to be created for all improvements to ESLint core so that the design of the improvements can get sufficient discussion/review.

**Comment by ngotchac** [comment]
Sure thing, will do !

**Comment by ngotchac** [comment]
Done: #9897

**Comment by nzakas** [comment]
Closing, as the conversation has moved to #9897.

**Pull request closed without merging**
