### PR TITLE
Missing arguments in examples

### PR DESCRIPTION
**Pull request by mgedmin**
**What issue does this pull request address?**

An error in documentation

**What changes did you make? (Give an overview)**

Added the missing function argument in Reflect.apply() calls

**Is there anything you'd like reviewers to focus on?**

Not really

### CODE REVIEW

**Comment by mgedmin** [comment]
I apologize, but I'm not likely to find the time to read and agree to a CLA for this.

I'm also surprised to be asked about an issue number for a documentation-only fix when your issue template said that wasn't necessary for documentation-only fixes.  (Is your bot not smart enough to look at filenames in diffstat?)

**Comment by vitorbal** [comment]
Hi @mgedmin, thank you for the PR! The bot is not smart enough to detect this change is only doc-related, so you can ignore that.

The CLA is pretty short and straight-forward and as a bonus, signing it would mean you won't need to do it again for any project under the jQuery foundation.
That said, if you still don't feel like taking the time to read and accept it, I understand.
Regardless, thank you for your contribution to ESLint.

**Comment by mgedmin** [comment]
I'll definitely consider signing the CLA as soon as I have something serious to submit!

(And I realize that filing #7069 probably took more time than it would've taken me to read the CLA, it's just that I haven't had breakfast yet and I can't force myself to deal with legalese.)

**Comment by nzakas** [comment]
Sorry about the confusion here. For documentation changes, you don't need an issue, but you do need to put "Docs:" at the front of your commit message. The bot is pretty dumb, but if it sees "Docs:", then it won't warn about needing an issue.

We do need a CLA to accept any contributions, though, as it's part of our CI process. As @vitorbal pointed out, we do use the jQuery CLA, which is pretty straightforward and doesn't contain a lot of legalese.

We are working on some changes to hopefully make what's expected more apparent to new contributors.

**Pull request closed without merging**
