### PR TITLE
Docs: remove configuring.md

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

The actual URL for the Configuring ESLint page is:

* https://eslint.org/docs/user-guide/configuring (`configuring.html` content, created from `configuring.md`)

Now that we have merged https://github.com/eslint/eslint/pull/13837, the new URL should be:

* https://eslint.org/docs/user-guide/configuring/ (`configuring/index.html` content, created from `configuring/README.md`)

This is a different URL, note `/` at the end.

The problem is that, if we don't remove `configuring.html`, Netlify redirects `https://eslint.org/docs/user-guide/configuring/` to `https://eslint.org/docs/user-guide/configuring` and serves the content of `configuring.html`.

#### What changes did you make? (Give an overview)

Removed `configuring.md` so that we don't have `configuring.html` on the website.

With this change, Netlify will also be redirecting all old `https://eslint.org/docs/user-guide/configuring` links to `https://eslint.org/docs/user-guide/configuring/`, as in this preview: https://github.com/eslint/website/pull/824

#### Is there anything you'd like reviewers to focus on?

* We have some internal links from some other documents to particular sections in the old configuration page (e.g. the "Specifying Environments" link in https://eslint.org/docs/rules/no-undef#environments), Will be fixed by https://github.com/eslint/eslint/pull/14038.
* The actual site 301s `https://eslint.org/docs/user-guide/configuring/` to `https://eslint.org/docs/user-guide/configuring`. The next version will be doing the opposite. Could that make any problems (caches, SEO...)?

### CODE REVIEW

**Review by aladdin-add — APPROVED** [review]
it's no longer required - we have `docs/user-guide/configuring/README.md`

**Comment by nzakas** [comment]
I think the 301s should be okay. If we are concerned, I think we can configure that behavior in Netlify.

**Comment by mdjermanovic** [comment]
My concern is if someone (user or crawler) has somewhere cached that `https://eslint.org/docs/user-guide/configuring/` redirects to `https://eslint.org/docs/user-guide/configuring` (current URL), what will happen when we release the new version where `https://eslint.org/docs/user-guide/configuring` redirects back to `https://eslint.org/docs/user-guide/configuring/` (new URL).

Hopefully, it will ask again for `https://eslint.org/docs/user-guide/configuring/` before treating this as a cyclic redirect.

**Comment by nzakas** [comment]
301s are temporary redirects, so there should be minimal caching, if any.

**Comment by mdjermanovic** [comment]
301 is permanent redirect, 302 is temporary.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301

**Review by btmills — APPROVED** [review]
What's our backup plan if it turns out the preexisting 301 from `configuring/` to `configuring` ends up breaking something in combination with the new 301 from `configuring` back to `configuring/`? Rename the new docs to `configuration/` and redirect `configuring/?` there?

**Comment by mdjermanovic** [comment]
> What's our backup plan if it turns out the preexisting 301 from `configuring/` to `configuring` ends up breaking something in combination with the new 301 from `configuring` back to `configuring/`? Rename the new docs to `configuration/` and redirect `configuring/?` there?

Sounds good to me!

**Pull request merged**
