### PR TITLE
Revert "Update: adds nestedBinaryExpressions for no-extra-parens rule…

### PR DESCRIPTION
**Pull request by ilyavolodin**
Reverts eslint/eslint#5595 for a patch release

### CODE REVIEW

**Comment by spadgos** [comment]
Anything I need to do here? I assume this will be unreverted after the release is made?

**Comment by ilyavolodin** [comment]
@spadgos I'm very sorry about this. I jumped the gun a bit with merging this in. We need to make a patch release today to fix a bug that was introduced on Friday. I can merge this back in after the patch, but then, I think, it will show up under my name in the release notes. If you could just create another PR from the same branch as you did before (hopefully you haven't deleted it yet), then I can merge it back after a few days, and it will be credited to you.

**Comment by ljharb** [comment]
@ilyavolodin why do you need to make patch releases on master? Can't you just branch off of the tag?

**Comment by ilyavolodin** [comment]
@ljharb All of our tooling is made for doing releases of the master branch. We only branch off just before major releases (so we can maintain old version while we are working on the new one). It's a choice that was made a while back to make it a bit easier for a person managing release. You are correct, though, in this case, release off the branch would've made it a lot easier.

**Comment by ljharb** [comment]
This choice also seems to have caused the patch release to be released as a minor version - ie, v2.7.0 is out, but I assume you wanted v2.6.1?

**Comment by ljharb** [comment]
This is problematic because users using `~` now won't get the bug fix.

**Pull request merged**
