### PR TITLE
Fix: Set esquery to 1.1.x for ESLint v4

### PR DESCRIPTION
**Pull request by cesarguillotel**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [ ] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Update the version range from ^1.0.1 to 1.1.x for esquery for ESLint v4

### CODE REVIEW

**Comment by nzakas** [comment]
Can you explain the purpose of this request?

FWIW, we don’t have a way to re-release older ESLint versions.

**Comment by cesarguillotel** [comment]
> Can you explain the purpose of this request?
> 
> FWIW, we don’t have a way to re-release older ESLint versions.

Yes, it's linked to this issue but for the v4 version : https://github.com/eslint/eslint/issues/13081
The esquery update 1.2.0 realsed two days ago needs node 8, so it breaks projects using previous node version with ESLint v4.

**Comment by kaicataldo** [comment]
I don’t think this is something we should do given that Node 6 was end-of-lifed nearly a year ago.

**Comment by kaicataldo** [comment]
That being said, I do think it’s unfortunate that `esquery` published a semver-minor release with a breaking change.

**Comment by cesarguillotel** [comment]
I understand, but please note that this minor fix would actually help A LOT all companies using this version and node setup. So if you can do something about it, it will be very timesaving for us.
Please let us know if you can reconsider this update possibility.

**Comment by ljharb** [comment]
`npm publish --tag=4.x`, for example, will allow you to publish a backport without changing "latest". The tag can also be set via an env var, i believe, but I don't recall which one.

**Comment by nzakas** [comment]
Just to clarify: each release of ESLint goes through an extensive CI process before being released. That includes our tests, tests with popular plugins, building the website, etc. That whole system assumes we are working off the master branch. 

We just don’t have a way to do all of that for past releases, and our policy is not to do releases manually due to the complexity involved.

**Comment by kaicataldo** [comment]
As mentioned [here](https://github.com/eslint/eslint/pull/13082#issuecomment-604062770), we don't have a policy of releasing patches to old versions of ESLint. Thank you for your interest in improving ESLint.

**Pull request closed without merging**
