### PR TITLE
Docs: Increase visibility of code of conduct (fixes #8758)

### LINKED ISSUE #8758: Code of Conduct
I'd like to propose we add an official code of conduct to all ESLint org projects. While I think the team is overall conscious of making the process of contributing to ESLint a welcoming experience, it would be great to have readily available documentation about how we as maintainers and contributors should conduct ourselves as we work together.

If you haven't yet, check out the results from the [Open Source Survey](http://opensourcesurvey.org/2017/). The results are rather grim (not unexpectedly, unfortunately). I'd love for ESLint to be a shining example of inclusivity, and having a code of conduct is an actionable and important part of that.

My assumption is that no one would be against this (let's talk about it if you are!), but I'd like to discuss what that code of conduct should contain, whether we use and commit to upholding a code that is already in existence, such as the [Contributor Covenant](http://contributor-covenant.org/), or if we want to come up with our own language.

cc @eslint/eslint-team

### PR DESCRIPTION
**Pull request by kaicataldo**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Increase visibility of the code of conduct in our documentation as well as GitHub issue/PR templates.

**Is there anything you'd like reviewers to focus on?**
Did I miss any spots?

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
I don't feel strongly about this, but maybe it would be better to reference the code of conduct at the end of the templates, not the beginning. We've had very few CoC violations, and we've had a lot of cases where people don't fill in the info in the template. Assuming people are more likely to read the text at the beginning of the template, it seems like leaving the required info at the beginning of the template would be a better use of the space. (IMO, it might not even be necessary to have so many links to the CoC at all, given that the low visibility wasn't really a problem before.)

It's useful to have a code of conduct because we can reference it if someone is violating it -- I just want to make sure we're not throwing it in peoples' faces.

**Comment by kaicataldo** [comment]
I hear you, but I don't know if I agree. We haven't had many violations, but the purpose of this in my mind is not to fix a problem with contributors we already have, but rather to make it loud and clear to newcomers and potential contributors that we actively want to make this a welcoming and inclusive place for everyone.

I've personally heard from multiple contributors about how great of an experience contributing to ESLint was, and that was a _surprise_ (given the reputation a lot of open source projects have). For me, this is not only for those times when we encounter behavior that we want to discourage, but also for letting people know up front that these are the expectations they can have of us as a community.

Just my 2c, and totally up for discussing further :)

**Comment by not-an-aardvark** [comment]
I see what you mean. I still think it would be better to move it to the end of the issue/PR templates rather than the beginning, but I'm fine with either.

**Comment by kaicataldo** [comment]
@not-an-aardvark Would you be okay with trying this out with GitHub templates and, if it doesn't seem to be helpful, move it then? My inclination is to err on it being too visible than not visible enough.

**Pull request merged**
