### PR TITLE
Typo fix 'colum' -> 'column'

### PR DESCRIPTION
**Pull request by cobbweb**
A simple typo fix

### CODE REVIEW

**Comment by kaicataldo** [comment]
Thanks for the pull request! Mind signing the jQuery CLA so we can merge this?

**Comment by nzakas** [comment]
@cobbweb can you please sign the CLA so we can merge this? Thanks!

**Comment by cobbweb** [comment]
Sorry I thought I'd signed it... turns out I'd lost some git config locally.

**Comment by ilyavolodin** [comment]
Thanks @cobbweb

**Pull request merged**
