### PR TITLE
Chore: dogfooding `no-var` rule and remove `var`s (refs #6407)

### PR DESCRIPTION
**Pull request by mysticatea**
Refs #6407.

This PR applies `no-var` rule to our code.

- I tweaked some code for references from outside of the block which has declarations.
- I fixed some tests which are using our `.eslintrc.yml` or our code with `--no-eslintrc`.
    - https://github.com/eslint/eslint/blob/e82545849bc2924663b93936c4156df1251b10fd/tests/lib/cli-engine.js#L103
    - https://github.com/eslint/eslint/blob/e82545849bc2924663b93936c4156df1251b10fd/tests/lib/cli-engine.js#L425
    - https://github.com/eslint/eslint/blob/e82545849bc2924663b93936c4156df1251b10fd/tests/lib/cli-engine.js#L2258
- I added a dependency `karma-babel-preprocessor` for tests of PhantomJS. `let` in `tests/lib/eslint.js` caused syntax errors.

### CODE REVIEW

**Comment by mysticatea** [comment]
Also, `let` is slower than `var`, so I profiled performance between before/after this PR. As a result, I could see no significant differences.

**Before**

```
C:\Users\t-nagashima.AD\Documents\GitHub\eslint [chore/no-var-and-prefer-const]> npm run perf

> eslint@3.1.1 perf C:\Users\t-nagashima.AD\Documents\GitHub\eslint
> node Makefile.js perf


Loading:
  Load performance Run #1:  363.21531ms
  Load performance Run #2:  359.273145ms
  Load performance Run #3:  361.171179ms
  Load performance Run #4:  366.161369ms
  Load performance Run #5:  363.397929ms

  Load Performance median:  363.21531ms


Single File:
  CPU Speed is 3392 with multiplier 13000000
  Performance Run #1:  3858.823388ms
  Performance Run #2:  3873.5548909999998ms
  Performance Run #3:  3858.693893ms
  Performance Run #4:  3937.017115ms
  Performance Run #5:  3874.006157ms

  Performance budget exceeded: 3873.5548909999998ms (limit: 3832.5471698113206ms)


Multi Files (450 files):
  CPU Speed is 3392 with multiplier 39000000
  Performance Run #1:  14332.274141ms
  Performance Run #2:  12398.347067ms
  Performance Run #3:  11891.07006ms
  Performance Run #4:  11816.343988ms
  Performance Run #5:  12031.848532ms

  Performance budget exceeded: 12031.848532ms (limit: 11497.641509433963ms)
```

**After**

```
C:\Users\t-nagashima.AD\Documents\GitHub\eslint [chore/no-var-and-prefer-const +0 ~519 -0 !]> npm run perf

> eslint@3.1.1 perf C:\Users\t-nagashima.AD\Documents\GitHub\eslint
> node Makefile.js perf


Loading:
  Load performance Run #1:  361.830118ms
  Load performance Run #2:  360.144889ms
  Load performance Run #3:  363.776148ms
  Load performance Run #4:  355.25944ms
  Load performance Run #5:  363.504784ms

  Load Performance median:  361.830118ms


Single File:
  CPU Speed is 3392 with multiplier 13000000
  Performance Run #1:  3892.6454169999997ms
  Performance Run #2:  3874.342117ms
  Performance Run #3:  3895.069274ms
  Performance Run #4:  3918.40291ms
  Performance Run #5:  3852.414501ms

  Performance budget exceeded: 3892.6454169999997ms (limit: 3832.5471698113206ms)


Multi Files (450 files):
  CPU Speed is 3392 with multiplier 39000000
  Performance Run #1:  11876.235927ms
  Performance Run #2:  11997.202451ms
  Performance Run #3:  11880.865707ms
  Performance Run #4:  11883.21531ms
  Performance Run #5:  11817.850825ms

  Performance budget exceeded: 11880.865707ms (limit: 11497.641509433963ms)
```

**Comment by gyandeeps** [comment]
LGTM, waiting for others to review.

**Comment by platinumazure** [comment]
LGTM with merge-base of 1025772. I can't speak to the karma preprocessor though, hopefully someone else can cover that.

This is one of those things that should probably be merged quickly; otherwise, @mysticatea will either need to rebase with some frequency or scramble with another commit after this is merged, if someone has added a `var` statement in the meanwhile.

**Comment by ilyavolodin** [comment]
LGTM

**Pull request merged**
