### PR TITLE
Fix: max-len and eslint-disable

### LINKED ISSUE #8778: max-len rule doesn't respect eslint-disable directive
**Tell us about your environment**

* **ESLint Version:** v3.19 (feels like any)
* **Node Version:** v4.5.0 (-//-)
* **npm Version:** v2.15.11 (-//-)

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```
module.exports = {
  rules: {
    'max-len': ["error", 20]
  }
};
```

**What did you do? Please include the actual source code causing the issue.**

No error:
```js
/* eslint-disable */var q0123456789 = 0x123456789/* eslint-enable */;
```

Error:
```js
    /* eslint-disable */var q0123456789 = 0x123456789/* eslint-enable */;
```

**What did you expect to happen?**

No error.

**What actually happened? Please include the actual, raw output from ESLint.**

Max-len rule reporting an error.

### PR DESCRIPTION
**Pull request by zxqfox**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Tell us about your environment**

* **ESLint Version:** master (any)
* **Node Version:** v4.5.0 (doesn't matter)
* **npm Version:** v2.15.11 (doesn't matter)

**What parser (default, Babel-ESLint, etc.) are you using?** default (any)

**Please show your full configuration:**
```json
{ "rules": { "max-len": ["error", 20] } }
```

**What did you do? Please include the actual source code causing the issue.**
```js
    /* eslint-disable */var o123456789 = 'o123456789';
```

**What did you expect to happen?**

No error.

**What actually happened? Please include the actual, raw output from ESLint.**

Error reported.

Fixes #8778

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for reporting this and making a PR. I'm not really convinced that this is a bug -- it seems kind of arbitrary to move the report location to the middle of the line rather than the start just to avoid a report message for this particular code. To avoid this particular report, you could separate `eslint-disable` onto the previous line:

```js
/* eslint-disable */
veryVeryVeryVeryVeryVeryVeryVeryLongLine;
/* eslint-enable */
```

**Comment by zxqfox** [comment]
Well, we can't do that according to specific of our needs.

Why you think it's not a bug?

`eslint-disable` should or disable rule either should not. Disabling the rule shouldn't be related to position of `/* eslint-disable */` directive.

p.s. We've found that while trying to disable rule with `/* eslint-disable-line */`. JSCS has block-form `/* jscs:ignore */` to ignore the line, but eslint hasn't so we decided to use `eslint-disable` and it doesn't work too.
We need to wrap a block of code to disable check but max-len rule make us crying.

**Comment by not-an-aardvark** [comment]
> Disabling the rule shouldn't be related to position of `/* eslint-disable */` directive

By design, `eslint-disable` only disables problems that occur after the comment itself (and before the next `eslint-enable` comment). So the position of the directive definitely matters.

Could you clarify why you can't put the comment on the line before?

You can also use `// eslint-disable-line max-len` or `// eslint-disable-next-line max-len` as line comments to avoid this issue.

**Comment by zxqfox** [comment]
Probably, `max-len` should be a _line_-rule and should not check `column` in `isDisabledByReportingConfig`. But then we should implement this special rule type to all _line_ rules.

**Comment by zxqfox** [comment]
We wrapping blocks of code to special construction:
```js
assert(test, 'long long message');
→
(/*enableIfDebug()*/+0 && assert(test, 'long long message'));
```
We don't want to change line numbers because it makes debug harder (if users of our code doesn't want or can use source maps). It's very important.

In more complex situation we have:
```js
check && assert(test, `long long
long long long long
long long long message`);
→
check && (/*enableIfDebug()*/+0 && assert(test, `long long
long long long long
long long long message`));
```

That's why we can't use nor `// eslint-disable-next-line` neither `// eslint-disable-line`

We could use `/* eslint-disable-line */` but it doesn't work.

**Comment by not-an-aardvark** [comment]
It seems like you could do

```js
check && assert(test, // eslint-disable-line max-len
  `long long
long long long long
long long long message`);
```

Or

```js
// eslint-disable-next-line

check && assert(test, `long long
long long long long
long long long message`);
```

**Comment by zxqfox** [comment]
Well. We can't because it adds lines. We can't do that.

**Comment by zxqfox** [comment]
But this PR isn't good tho ;-( Anyway it doesn't resolve the original issue, thank you for feedback

**Pull request closed without merging**
