### PR TITLE
Docs: Fix Formatting

### PR DESCRIPTION
**Pull request by dhurlburtusa**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

- [x] Documentation update
- [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
- [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)

Added missing closing backtick.

#### Is there anything you'd like reviewers to focus on?

No.

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Hi @dhurlburtusa and thanks for the PR, nice catch!

The change looks good, can you please sign our [Contributor License Agreement](https://cla.js.foundation/eslint/eslint?pullRequest=14154) so we could merge it?

**Comment by dhurlburtusa** [comment]
FYI, I tried three times to sign the CLA with Chrome but when I click the checkbox (shows up after authenticating with GitHub), it kills the browser.

I then tried in FireFox and it worked.

So, I think we are good to go now. Please let me know if there is anything else.

**Comment by mdjermanovic** [comment]
> FYI, I tried three times to sign the CLA with Chrome but when I click the checkbox (shows up after authenticating with GitHub), it kills the browser.
> 
> I then tried in FireFox and it worked.

Sorry about that, we haven't had this issue before. We'll track to see if it happens again.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks for contributing!

**Pull request merged**
