### PR TITLE
Update: no-multiple-empty-lines fixer (fixes #6225)

### LINKED ISSUE #6225: no-multiple-empty-lines fixer
The no-multiple-empty-lines rule does not yet have a fixer for auto removing extra lines. I would like to have a fixer to remove these lines where applicable.

I already made the code to solve this issue. I'll link the PR a.s.a.p.

### PR DESCRIPTION
**Pull request by RRMoelker**
Multiple empty lines rule fixer. Removes empty lines at beginning, middle or end of file. An array of lines is created along with an array of range starts. This is required to define the deletion ranges from line indices.

### CODE REVIEW

**Comment by alberto** [comment]
You should add tests for windows line endings: `\r\n`

**Comment by nzakas** [comment]
Agreed. @RRMoelker can you add some test with Windows line endings?

**Comment by RRMoelker** [comment]
I will try to add support for the Windows line endings this weekend.

**Comment by platinumazure** [comment]
Adding "do not merge" until Windows line ending tests come in.

**Comment by RRMoelker** [comment]
Windows line endings were not being fixed correctly. Nice catch. The problem is that the SourceCode.lines variable contains lines without the newline character(s). This workaround works. Though at it's core translating between source code position and ranges is just not complete enough to make great fixers at the moment.

**Comment by RRMoelker** [comment]
@nzakas @platinumazure Windows line ending support and tests added.

**Comment by nzakas** [comment]
Lgtm. Thanks @RRMoelker !

**Comment by nzakas** [comment]
Oops, one last thing: can you update the documentation? There are two places to update:

1. https://github.com/eslint/eslint/blob/master/docs/rules/README.md put "(fixable)" after the rule description 
2. https://github.com/eslint/eslint/blob/master/docs/rules/no-multiple-empty-lines.md insert a notice about it being fixable at the top (you can copy from https://github.com/eslint/eslint/blob/master/docs/rules/space-in-parens.md)

**Comment by ilyavolodin** [comment]
@RRMoelker quick ping to update documentation.

**Comment by RRMoelker** [comment]
@ilyavolodin I will update the documentation this weekend.

**Comment by ilyavolodin** [comment]
Awesome! Thanks!

**Comment by ilyavolodin** [comment]
LGTM. Thanks @RRMoelker

**Pull request merged**
