### PR TITLE
Chore: Update deprecated information

### PR DESCRIPTION
**Pull request by wafuwafu13**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Update deprecated information.
Ref: https://eslint.org/docs/rules/#deprecated

### CODE REVIEW

**Comment by bmish** [comment]
Looks reasonable. We should add tests that deprecated rules:
* Have a `This rule was deprecated...` notice at the top of their rule doc
* Have `@deprecated` in their rule doc comment

I believe Makefile.js is the place where we currently have checks like that.

**Comment by wafuwafu13** [comment]
here :eyes:
https://github.com/eslint/eslint/blob/3d7d5fb32425e8c04d3eaa0107a2ab03a2e285df/Makefile.js#L786

Can I add tests in next PR?

**Review by nzakas — APPROVED** [review]
LGTM. Thanks.

**Comment by nzakas** [comment]
@wafuwafu13 yes, you can do that in a separate PR

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
