### PR TITLE
Fix: comma-dangle with always-multiline shouldn't allow a trailing comma without a new line afterward

### LINKED ISSUE #2091: comma-dangle always-multiline should only count newlines before closing curly
The new `always-multiline` behavior of `comma-dangle` requires a trailing comma if a newline appears anywhere in the literal. It would probably make more sense if it only considered the space right before the closing bracket.

E.g. these two cases are currently not allowed, but they probably should be:

```javascript
{x: {
  foo: 'bar',
}}
```

```javascript
{a: 1, b: 2,
  c: 3, d: 4}
```

This is a followup to #1984.

### PR DESCRIPTION
**Pull request by BenoitZugmeyer**
Fixes #2091.

Sorry for the long commit message.

### CODE REVIEW

**Comment by nzakas** [comment]
Can you shorten it? It will need to the change log in its current state.

**Comment by nzakas** [comment]
The code looks good. Can you add tests for the cases explicitly mentioned in the issue?

**Comment by BenoitZugmeyer** [comment]
Done. It's a little less explicit, I can't think of a shorter way to illustrate this commit.

**Comment by nzakas** [comment]
Lgtm

**Pull request merged**
