### PR TITLE
Fix: Fix formatting in Pull Request GitHub template

### PR DESCRIPTION
**Pull request by revolter**
**What is the purpose of this pull request? (put an "X" next to item)**

- [ ] Documentation update
- [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
- [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [x] Other, please explain:

The checklist wasn't properly formatted.

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the PR! However, I think this is intentional based on https://github.com/eslint/eslint/pull/7072#discussion-diff-77872859, https://github.com/eslint/eslint/pull/9408, and https://github.com/eslint/eslint/pull/7520.

**Comment by revolter** [comment]
Sorry.

**Comment by platinumazure** [comment]
Hi @revolter, thanks for the PR.

The current format is intended, because we don't actually want that to be a checklist. PRs have just one type/purpose: the goal of that section is not for PRs to tick off all options. So this is currently formatted as we intend. Thanks for contributing regardless!

**Comment by revolter** [comment]
Makes quite a lot of sense, but as others stated before me, it looked like a mistake.

**Pull request closed without merging**
