### PR TITLE
Chore: Don't require an issue reference in check-commit npm script

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

```
[ ] Documentation update
[ ] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:
```

*If the item you've check above has a template, please paste the template questions here and answer them.*

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [ ] I've included tests for my change
- [x] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**

This removes the check for an issue reference in the `npm run check-commit` script, since that is no longer required by eslintbot or the docs. (discussed in Gitter)

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

**Comment by platinumazure** [comment]
For any reviewers: I had recommended submitting the PR with no tests because there don't seem to be existing tests. If we want tests around Makefile.js functionality, my preference would be that we just include `checkGitCommit` tests in this PR and create a separate issue/PR for adding test coverage elsewhere in that file.

**Comment by platinumazure** [comment]
@not-an-aardvark Thanks for submitting this! Unfortunately you need to remove the `ISSUE_REGEX` declaration as well since the variable is unused. I'll take another look when Travis and AppVeyor are passing :smile:

**Comment by not-an-aardvark** [comment]
Whoops, that's what I get for not running the tests locally. Fixed.

**Comment by platinumazure** [comment]
LGTM, waiting for others to review. (TSC folks, feel free to merge sooner if you like.)

**Comment by nzakas** [comment]
LGTM. Thanks!

**Pull request merged**
