### PR TITLE
WIP: Update: align argument for indent VariableDeclarator(fixes #8976)

### LINKED ISSUE #8976: align argument for indent VariableDeclarator
I'd like to allow eslint to accept code that looks like this:

```
const foo = 'bar',
      baz = 'foo';

if (foo === 'bar') {
    console.log(baz);
}
```

I created a pull request for a change to the VariableDeclarator rule adding decimals (#8975), but it was pointed out that a different argument altogether (ie "first") would be a better way of solving the problem.

What it would do would be to allow variable declaractions to be aligned as above regardless of the indentation level

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))

**What changes did you make? (Give an overview)**
fixes #8976

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by kaicataldo** [comment]
Friendly ping. Anything you need help with to finish this up?

**Comment by not-an-aardvark** [comment]
I know this is still a WIP, but I wonder if it would be possible to update the `VariableDeclarator` logic to use a similar mechanism to array elements, so `'align'` would be like `'first'`.

**Comment by kaicataldo** [comment]
@Listor the subsequent commits will all be squashed and merged, so the commit message only matters for the initial commit.

**Comment by Listor** [comment]
@kaicataldo sure but the test for the commit-message is failing so I was assuming it is because of that.

**Comment by Aladdin-ADD** [comment]
Sorry, I don't have time to get this finished.please feel free to pick up if you're interested. ❤️

**Pull request closed without merging**
