### PR TITLE
[Not a Pull Request] Running eslint from a Docker container

### PR DESCRIPTION
**Pull request by DavidBruant**
This is not a pull request.
This is a proposal and the beginning of a discussion (which can be as short as you wish), not the end of one. With code attached.

# Context 

I tried what I suggested [here](https://github.com/eslint/eslint/issues/4483#issuecomment-158641836) in response to the idea of dropping Node < 4 support. The purpose of this "PR" is more to demonstrate that the idea can work

# How it works

In this "PR", there is the dockerfile to build a docker image that contains the latest stable version of eslint (latest at time of `docker build`). The image can be built with `docker build -t eslint .`

Then, you can have the following session:
````bash
> node -v 
v0.10.38 # using in my machine an old Node version
> docker run -t -v $PWD:/usr/code:ro eslint node -v
v5.1.0 # The docker container has a very recent version of Node
> docker run -t -v $PWD:/usr/code:ro eslint eslint -v
v1.10.1 # Latest eslint is in the container
> docker run -t -v $PWD:/usr/code:ro eslint eslint .

/usr/code/lib/eslint.js
  61:27  error  Expected '===' and instead saw '=='  eqeqeq

✖ 1 problem (1 error, 0 warnings)
````

Detailing `docker run -t -v $PWD:/usr/code:ro eslint eslint .`:
* `docker run` : https://docs.docker.com/engine/reference/run/
* `-t` : to have colors in the terminal
* `-v $PWD:/usr/code:ro`: make the current directory as a volume accessible from the Docker container
* `eslint` : docker image containing the latest Node and latest eslint
* `eslint .` : run the `eslint` command inside the container on the current directory (which is the volume on `$PWD`)

## Performance

There could be a concern about performance, but I haven't noticed a difference. Running eslint on eslint takes between 13 and 14s on my machine whether it's directly on my machine (Linux host) or from the Docker container. 
YMMV, I'm interested in hearing what other people on Mac or Windows experience.

# Conclusion

It works :-) I have some version of Node on my machine, I can run the latest eslint running on Node 5.1 without trouble.

Even if there is no interest from the eslint team to host this solution and/or maintain it, at least, this "PR" proves this is a workable solution for those who can have Docker on their machine.

# Beyond this work

I haven't looked into how this would work with plugins, there might be trouble with working with globally installed eslint plugins. Maybe it's just a matter of adding another volume.

If there is interest from the eslint team in this solution (for people who cannot migrate to newer versions of Node, but want newer versions of eslint), you might want to create the eslint Docker image and host it in the dockerhub so people don't need to do the `docker build` step themselves.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Sorry, I'm not really up to date on docker, but would this be any different then https://github.com/nowk/eslintd?

**Comment by DavidBruant** [comment]
> Sorry, I'm not really up to date on docker

No worries. Don't hesitate if you have other questions, even on Docker itself.

> but would this be any different then https://github.com/nowk/eslintd?

In spirit, this is exactly the same idea (sorry for not finding it earlier :-/ Love the *`I refuse to install node.js directly on my machine.`* :-p ).
The differences are I can see are:
* They freezes the eslint version to 1.5.1 (not sure why) and I always build with the latest version from npm
* They wrap the docker command line in a bash script so you can type `eslint` (as usual) instead of `docker run -t -v $PWD:/usr/code:ro eslint eslint .`

These differences are fairly minor.


Ok... hmm... This seems easy and low-effort enough to me that I can maintain the solution myself. I'll do the first iteration, document the process and come back here. 
The purpose when it's done is so you can decide to either merge my work and maintain it (via repo ownership transfer; maybe I can maintain it under the eslint flag instead of as myself) or just to add a link to this work in the readme/doc so people who are interested can find out about it even if you don't maintain it.

**Comment by lo1tuma** [comment]
For me it feels a bit over complicated to just manage that eslint runs with the correct node version. Using nvm or [nix](http://nixos.org/nix/) is much simpler.

**Comment by DavidBruant** [comment]
> For me it feels a bit over complicated to just manage that eslint runs with the correct node version. Using nvm or nix is much simpler.

I don't have experience with nix, but for nvm, I don't understand how it'd be simpler. Do you have to switch of node version everytime you want to use eslint? and back when you're working on your code?
What would be the process in either case?

In the docker case, once you've aliased `docker run -t -v $PWD:/usr/code:ro eslint eslint .`, the docker part is transparent and you don't here about it after the setup phase.

**Comment by lo1tuma** [comment]
If you use `nvm use` to manage the node version, you set the version only for the current shell session so you don’t have to switch all the time, you only have to run eslint from a different session. Apart from that you could simple use `nvm exec` which executes a given command in a given node version, e.g. `vm exec 5 node_modules/.bin/eslint .`.

Nix is similar to nvm but instead of only managing node versions you can manage any kind of dependencies and execute them in an isolated environment.

**Comment by DavidBruant** [comment]
> you set the version only for the current shell session so you don’t have to switch all the time

Ah cool, I didn't know that was possible. This is indeed perhaps a simpler solution than Docker for those who use Node, but not Docker; nvm is less intrusive a dependency than Docker.

**Comment by ilyavolodin** [comment]
@lo1tuma To me all of those solutions are over complicated when comparing to direct `npm install`:-) So I think it's just what people are used to. There are a lot of people that deal with Docker on the daily bases, so for them this might be the most obvious solution. It definitely doesn't hurt to have another way, just in case.

**Comment by lo1tuma** [comment]
> There are a lot of people that deal with Docker on the daily bases, so for them this might be the most obvious solution.

I’m one of those people, I use docker every day. But on Mac OS it is a bit of an effort to setup docker, which is probably also the case for windows. That’s why I use nvm and nix for dependency management on my developer machine and docker only on our build and production servers.

**Comment by nzakas** [comment]
Closing as we're not likely to merge, but feel free to continue discussion here.

**Pull request closed without merging**
