### PR TITLE
Fix: Allow comment before comma for comma-spacing rule (fixes #2408)

### LINKED ISSUE #2408: Comment before comma trigger comma-spacing error
Use default setting on http://eslint.org/demo/

Codes:

```javascript
var myfunc = function (x, y, z) {
  "use strict";
  /* ... */
  return [x, y, z];
};
myfunc(404, true/* bla bla bla */, "hello");
```

Result:

> 6:33 - There should be no space before ','.

i'm new here, not sure if this is a feature or bug. maybe related to #1457

### PR DESCRIPTION
**Pull request by gyandeeps**
I am thinking what I have done would be expensive, but I wan't able to figure any other way since I was not able to use `getComments(node)` function as tokens at this level did not carry `leadingComments` and `trailingComments`.

After fixing I actually saw this coversation: https://github.com/eslint/eslint/issues/2211#issuecomment-91922185
I guess we can hold on to this PR if we are planning on a better solution in the future.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
spacing + comments code should be centralized. There're a bunch of rules that would be able to use it. So I would hold of until we can decide how to do that.

**Comment by gyandeeps** [comment]
@ilyavolodin I agree. :+1:

**Comment by gyandeeps** [comment]
@nzakas Should we keep this PR open or close it.
Since we will make such change in an efficient way in future.

**Comment by nzakas** [comment]
Unless anyone is ready with a proposal for how to centralize, I'd rather get this fix in. We have a ton of duplicate code already, a little more is a small price to pay for closing a bug.

**Comment by gyandeeps** [comment]
I think then we should merge this and whenever we fix this problem centrally then we can come back.
Yes, it would fix the bug for now, which is good.

**Pull request merged**
