### PR TITLE
docs: Add Powered by Algolia label to the search.

### PR DESCRIPTION
**Pull request by amareshsm**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:
Added the Powered by Algolia label to the search.

#### What changes did you make? (Give an overview)
Added powered by Algolia label under the search box
fixes: https://github.com/eslint/eslint/issues/18620 

#### Is there anything you'd like reviewers to focus on?
Need to verify that the changes work correctly across all device screen sizes.

### CODE REVIEW

**Comment by nzakas** [comment]
Same feedback as https://github.com/eslint/eslint.org/pull/595

**Review by Tanujkanti4441 — COMMENTED** [review]
How about if we link the 'Powered by Algolia' text to the site of Algolia?

**Comment by amareshsm** [comment]
> How about if we link the 'Powered by Algolia' text to the site of Algolia?

Yes, we can link.

**Review by nzakas — APPROVED** [review]
LGTM! Can you also make the same change in the `v8.x` branch?

**Pull request merged**
