### PR TITLE
New: Add prefer-inclusive-language

### PR DESCRIPTION
**Pull request by drewwyatt**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

- [ ] Documentation update
- [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
- [x] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

**Please describe what the rule should do:**

This rule is heavily inspired by the newly proposed [`inclusive_language` rule in SwiftLint](https://github.com/realm/SwiftLint/pull/3243) and [Github's recent decision to rename default branches to `main`](https://twitter.com/natfriedman/status/1271253144442253312) (also mentioned in the linked PR). 

This PR aims to focus (by default) on two sets of terms [identified by the IETF](https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1): master/slave and blacklist/whitelist.
Both sets of terms can be replaced with alternatives that are clear in their intent, and also more inclusive/less offensive. This list does not seek to be exhaustive or to meet the needs of all projects/teams that might use this (which is why it is configurable).

**What category of rule is this? (place an "X" next to just one item)**

- [ ] Enforces code style
- [ ] Warns about a potential error
- [x] Suggests an alternate way of doing something
- [ ] Other (please specify:)

**Provide 2-3 code examples that this rule will warn about:**

```js
var blackList = ['foo', 'bar'];
let whitelist = ['a', 'b'];

const MasterDetail = new View();
class Coordinator {
  attach(slaves) {
    // ...
  }
}
```

**Why should this rule be included in ESLint (instead of a plugin)?**

This rule aims to help uphold The Standards outlined in the [Open JS Foundation Code of Conduct](https://github.com/openjs-foundation/cross-project-council/blob/master/CODE_OF_CONDUCT.md), which this project adheres to. Specifically:

- Demonstrating empathy and kindness toward other people
- Being respectful of differing opinions, viewpoints, and experiences
- Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience
- Focusing on what is best not just for us as individuals, but for the overall community

### CODE REVIEW

**Comment by kaicataldo** [comment]
Thanks for the PR. Given the [recent changes to our rules policy](https://eslint.org/blog/2020/05/changes-to-rules-policies), we won't be able to add this to core rules.

This rule seems like a great candidate for a 3rd party plugin, or could probably also be enforced using [https://eslint.org/docs/rules/no-restricted-syntax](`no-restricted-syntax`).

**Comment by drewwyatt** [comment]
@kaicataldo I noticed you added the [evaluating] label to this (despite the finality that "we won't be able to add this to core rules." carries). Is this still open for discussion?

**Comment by mdjermanovic** [comment]
This rule would be maybe too similar to [id-denylist](https://eslint.org/docs/rules/id-denylist), so we would probably add some options to the existing rule (e.g., to look for a substring as in this proposal, not just the exact match) instead of a new rule, but that also falls under the new rules policy.

**Comment by drewwyatt** [comment]
@mdjermanovic that makes sense.

1. Would a PR adding the substring option to `id-denylist` be welcome?
2. If yes, is there a way to make the terms listed in this PR available a higher level that would also be welcome as a PR? either through an additional config, or an additional `id-denylist` option?

**Comment by mdjermanovic** [comment]
> * Would a PR adding the substring option to `id-denylist` be welcome?
> * If yes, is there a way to make the terms listed in this PR available a higher level that would also be welcome as a PR? Either through an additional config, or an additional `id-denylist` option (or something else)?

Per our evaluation process, a rule change needs a champion and consensus from the team in order to be accepted (please see https://eslint.org/docs/maintainer-guide/issues#accepting-issues), so we usually recommend opening a "Rule change request" issue before doing any work.

Also, this would be a new option (or options) in a rule that is categorized as a "stylistic rule", and per the [recent changes to our rules policy](https://eslint.org/blog/2020/05/changes-to-rules-policies) all stylistic rules are frozen. Though, I think in this case it might be arguable whether this change is about a style, or it falls under "a better way to do something". @kaicataldo thoughts?

**Comment by mdjermanovic** [comment]
Actually, this may be redundant, since we also have [id-match](https://eslint.org/docs/rules/id-match) rule which can be configured to disallow identifiers that contain certain words (and also has `ignoreDestructuring` option as the proposed rule):

```js
/* eslint id-match: ["error",
  "^((?![Bb]lack[Ll]ist|[Ww]hite[Ll]ist|[Mm]aster|[Ss]lave).)*$"
]*/

var fooMasterBar; // error
```

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGlkLW1hdGNoOiBbXCJlcnJvclwiLFxuICBcIl4oKD8hW0JiXWxhY2tbTGxdaXN0fFtXd11oaXRlW0xsXWlzdHxbTW1dYXN0ZXJ8W1NzXWxhdmUpLikqJFwiXG5dKi9cblxudmFyIGZvb01hc3RlckJhcjsgLy8gZXJyb3IiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

**Comment by drewwyatt** [comment]
@mdjermanovic that makes total sense. 

Given that, would you consider a PR adding this to a config like `eslint:inclusive`, or, ideally even making this part of `eslint:recommended`?

**Comment by mdjermanovic** [comment]
> Given that, would you consider a PR adding this to a config like `eslint:inclusive`, or, ideally even making this part of `eslint:recommended`?

I think this is more suitable for a [shareable config](https://eslint.org/docs/developer-guide/shareable-configs), but other team members might have a different opinion.

**Comment by kaicataldo** [comment]
Agreed with @mdjermanovic that this would be a better fit for a shared config.

**Comment by nzakas** [comment]
Just FYI, this plugin was recently created: https://github.com/muenzpraeger/eslint-plugin-inclusive-language. It may be worthwhile to check and see if that is solving the problem you'd like to address.

**Pull request closed without merging**
