### PR TITLE
Upgrade: espree to 3.2.0, remove tests with SyntaxErrors (fixes #7169)

### LINKED ISSUE #7169: Master unit tests are failing after Espree upgrade
**Tell us about your environment**

* **ESLint Version:** Master branch
* **Node Version:** n/a
* **npm Version:** n/a

**What parser (default, Babel-ESLint, etc.) are you using?** Espree 3.2.0

After release of Espree 3.2.0 our unit tests started failing in master: See https://travis-ci.org/eslint/eslint/jobs/160511634 for example. This is not good, since we haven't enabled ES2017 anywhere yet, and all of the tests should continue to pass.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- [x] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**

This removes tests that were failing due to the update to Espree 3.2.0. (See #7169)

These tests contained code that had a SyntaxError according to the ES spec, but previously had been parsed by Acorn rather than throwing an error. The fix is to just remove the tests.

Downstream users of ESLint will not be affected by this update unless their code contained invalid syntax, in which case this update is a bugfix for them. (Code like this would have thrown an early error at runtime anyway.)

edit: For what it's worth, [here's](https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-early-errors) the clause in ecma262:

> It is a Syntax Error if IsSimpleParameterList of *FormalParameterList* is **false** and BoundNames of *FormalParameterList* contains any duplicate elements.

**Is there anything you'd like reviewers to focus on?**

Also see: #7101

### CODE REVIEW

**Comment by ljharb** [comment]
um, why would we want to remove these? One of the huge value props of a linter is that it can report things more helpfully than just "a syntax error".

**Comment by ljharb** [comment]
I think these tests are still very valid for sloppy mode - it's only in strict mode that they're syntax errors.

**Comment by ljharb** [comment]
@bterlson - can you confirm that duplicate args in non-simple parameter lists are a syntax error here, and whether that's true in both strict and sloppy mode?

**Comment by bterlson** [comment]
@ljharb: confirmed, and it's true in both sloppy and strict. See: https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-early-errors.

**Comment by michaelficarra** [comment]
LGTM

**Comment by mysticatea** [comment]
@not-an-aardvark Could you update `package.json` as well? I'd like to ensure using new espree. Also, I think proper `Upgrade:` instead of `Chore:`.

**Comment by mysticatea** [comment]
Though this does not have 2 days yet, I'll merge this PR since this has gotten enough eyes and other PRs are failing tests.

**Pull request merged**
