### PR TITLE
feat: add declaration loc to message in block-scoped-var

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes https://github.com/eslint/eslint/issues/17244

#### What changes did you make? (Give an overview)

In the `block-scoped-var` rule, I added the location info of declarations to reported messages. This should clarify cases where there are multiple errors on the same reference, and seems useful in general.

### CODE REVIEW

**Comment by fasttime** [comment]
Thanks for this PR! I would suggest to add a test with at least 3 redeclarations of a variable in different blocks, for example:

```js
if (foo) {
    var a = 1;
} else if (bar) {
    var a = 2;
} else {
    var a = 3;
}
```
This would let us verify the case of two (or more) messages with the same `line` and `column` but different `data`.

In the current implementation, when $n \geq 1$ blocks in a scope declare the same variable, the rule will report $n\times\(n - 1\)$ problems. I think that this unexpectedly large number or messages (and the fact that they all contained the same text!) is the reason for the confusion in the linked issue #17244.

**Comment by mdjermanovic** [comment]
> ```js
> if (foo) {
>     var a = 1;
> } else if (bar) {
>     var a = 2;
> } else {
>     var a = 3;
> }
> ```

I added this test, thanks for the suggestion!

**Review by fasttime — APPROVED** [review]
LGTM.

**Review by snitin315 — APPROVED** [review]
LGTM. Thanks!

Can we merge PRs or do we need to hold PRs until we finish #17225?

**Comment by mdjermanovic** [comment]
> Can we merge PRs or do we need to hold PRs until we finish #17225?

We can merge all PRs now, only it would be best to avoid merging those that could cause merge conflicts with tasks from #17225.

**Pull request merged**
