### PR TITLE
Update: Extended no-console rule (fixes #5095)

### LINKED ISSUE #5095: Add more params to no-console rule
Hi guys!
Thanks for the awesome tool!

So I am using eslint with recommended preset. It has **no-console** rule turned on.
That's fine, I need to check against `console.log(message)` left after development. But there are some places where I actually use `console.warn(message)` or `console.error(message)` according to the business logic of the application. And I don't want to ignore that all the time with inline comments to make eslint pass.

So I am suggesting to add more params to no-console rule, so that it can be configured to warn about console.log, but pass for console.warn/error.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30338372-add-more-params-to-no-console-rule?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by EricHenry**
…e functions (fixes #5095)

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Can you shorten commit message to not exceed 72 characters please? Otherwise it gets truncated in release notes.

**Comment by platinumazure** [comment]
And to complicate the request to shorten the commit summary, it should probably start with "Update:" instead of "New:".

If you want to include more detail in the commit message, it can be done on lines after the first (those aren't included in the 72-character check).

**Comment by EricHenry** [comment]
Thanks for the heads up @ilyavolodin  & @platinumazure. This is my first PR, your patience is really appreciated!

**Comment by ilyavolodin** [comment]
LGTM. @EricHenry Thanks for the PR. One more question. It looks like our bot is sleeping on the job again. Did you sign our [CLA](http://eslint.org/cla/) if not, could you sign please, and respond here once you've done that? Sorry, I can't check it myself, bot usually does that, but it's currently MIA.

**Comment by EricHenry** [comment]
@ilyavolodin no worries at all, I believe I had done it yesterday. However, for good measure I just signed it again. :)

**Comment by ilyavolodin** [comment]
Sounds good. Thanks again for the PR.

**Pull request merged**
