### PR TITLE
Fix: Check space after anonymous generator star (fixes #5435)

### LINKED ISSUE #5435: space-before-function-paren does not work for anonymous generator functions
**What version of ESLint are you using?**
2.2.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**
* babel-eslint

```js
{
  "rules": {
    "space-before-function-paren": [2, {"anonymous": "always", "named": "always"}]
  }
}
```
**What did you do? Please include the actual source code causing the issue.**
Example:
```js
var bla = function *() {}

bla()
```

**What did you expect to happen?**
I expected it to not lint, because the documentation for the [generator-star-spacing rule](generator-star-spacing.html) says:
> In anonymous function expressions, spacing between the * and the opening parenthesis is not checked. This is checked by the space-before-function-paren rule.

**What actually happened? Please include the actual, raw output from ESLint.**
Eslint is not complaining about the missing space between the `*` and the `(`.

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by btmills** [comment]
LGTM.

@nzakas This change will start reporting something that we always intended to check, but the docs said we weren't. Does that mean this needs to wait for a major release?

**Comment by ilyavolodin** [comment]
Yeah, this is probably a breaking change, unless we put it behind an option.

**Comment by nzakas** [comment]
From looking over the issue, I'd say we can treat it as a bug fix. It looks like we meant for this to work previously but it fell through the cracks.

**Comment by gyandeeps** [comment]
is this good to go?

**Comment by ilyavolodin** [comment]
Yes. If it's not a breaking change, then it's good to be merged.

**Pull request merged**
