### PR TITLE
Update: allow continue instead of if wrap in guard-for-in (fixes #7567)

### LINKED ISSUE #7567: allow negated condition in for-in guards in guard-for-in rule
I would like `guard-for-in` to allow the following pattern in addition to what it currently allows.

```js
for (key in foo) {
    if (!{}.hasOwnProperty.call(foo, key)) continue;
    doSomething(key);
}
```

To be clear, the difference is that this guard has a negated condition with a `continue` as the consequent. The `continue` should be allowed as the only statement in a block as well, to be compatible with that brace style preference.

```js
for (key in foo) {
    if (!{}.hasOwnProperty.call(foo, key)) {
        continue;
    }
    doSomething(key);
}
```

**edit:**

**What rule do you want to change?**

`guard-for-in`

**Does this change cause the rule to produce more or fewer warnings?**

Fewer.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New default behaviour.

**Please provide some example code that this change will affect:**

```js
for (key in foo) {
    if (!{}.hasOwnProperty.call(foo, key)) continue;
    doSomething(key);
}
```

```js
for (key in foo) {
    if (!{}.hasOwnProperty.call(foo, key)) {
        continue;
    }
    doSomething(key);
}
```

**What does the rule currently do for this code?**

Warns.

**What will the rule do after it's changed?**

Not warn.

### PR DESCRIPTION
**Pull request by michaelficarra**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by ljharb** [comment]
Could this be behind an option? I want to preserve the current behavior (disallowing continue statements).

**Comment by michaelficarra** [comment]
@ljharb I don't think that'd be appropriate here. This rule is not stylistic. It intends to protect you from a potential hazard, and either pattern is safe.

**Comment by platinumazure** [comment]
I agree this should probably be behind an option, and it seems if we want to allow `continue`, we should also allow `break` in the same way.

Let's discuss in the issue.

**Comment by ljharb** [comment]
Since the rule isn't checking *what* the guard is doing - ie, it's not enforcing a hasOwnProperty check - it's not actually protecting against a hazard. I've seen plenty of people accidentally bypass this rule by checking something besides hasOwnProperty.

**Comment by platinumazure** [comment]
I agree @ljharb, but I think that should be discussed as a separate issue.
This is a rule that came from JSHint originally, and they had the same
limitation there. (We could certainly improve the rule to actually be
useful in this regard! I just wanted to explain the historical reason for
its current state.)

**Comment by michaelficarra** [comment]
@platinumazure `break`/`return`/`throw` wouldn't be used to avoid iterating prototype properties like `continue` is.

**Comment by platinumazure** [comment]
@ljharb Could you use `no-restricted-syntax` to catch the style that you don't want, while allowing this change to occur without a new option? Just wondering... We could certainly add a new option later if we needed to (i.e., if enough people asked for it).

**Comment by ljharb** [comment]
@platinumazure if we want to ban `continue`, then yes, but if we want to allow `continue` (just not in this style) then we couldn't. I think it should go behind an option.

**Comment by michaelficarra** [comment]
I still think that an option here is inappropriate for the reasons I mentioned above. This rule is listed in the [Best Practices](https://eslint.org/docs/rules/#best-practices) section, not the [Stylistic Issues](https://eslint.org/docs/rules/#stylistic-issues) section. Using it to enforce a particular style is an abuse of this rule. And without an option, it still always protects you from the possible hazard.

**Comment by ilyavolodin** [comment]
I do agree with @michaelficarra here. This rule is in a different category then things like `no-continue`. It's not really meant for styleguide use (as far as I understand that's the problem @ljharb has with adding it in without an option). The style rule should be the one that allows/disallows `continue` inside specific nodes. I know we don't have available right now, but it can be created as a plugin.

**Comment by ljharb** [comment]
"styleguide use" covers all categories of rules; my issue with adding it without an option is that i want the entire body of the for loop to be surrounded by the *same* single condition, and i want the extra nesting, so that the existence of the condition is clear.

It is not a "best practice" to early-continue a for loop under a guard (nor is it a bad practice). In fact, it's simply @michaelficarra's preferred style here.

In terms of protecting against a hazard, this rule does not actually *protect* against the hazard - it simply requires *any* condition.
> This rule is aimed at preventing unexpected behavior that could arise from using a for in loop without filtering the results in the loop.

The unexpected behavior is when you encounter an inherited property; filtering the results isn't a generic solution to that problem.

**Comment by platinumazure** [comment]
I don't see why we couldn't add an option here-- after all, @michaelficarra could certainly use the option in his own setup.

Can someone convince me why adding an option would be a bad idea?

**Comment by not-an-aardvark** [comment]
It makes the rule slightly more complicated for users to configure, and also slightly more complicated for us to maintain. Additionally, the option seems to be tangential to the main purpose of the rule. In this case I don't think it's worthwhile.

**Comment by michaelficarra** [comment]
@ljharb I'd love for the rule to be stricter about the condition of the guard, but I think that change is inappropriate for this PR. Also, "best practice" (probably not the best term) is defined on that page as

> better ways of doing things to help you avoid problems

and I believe that both approaches allowed by this rule accomplish that goal.

**Pull request merged**
