### PR TITLE
Update: Implement autofixing for comma-dangle rule (fixes #4418) 

### LINKED ISSUE #4418: Implement autofixing for comma-dangle rule
<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28244725-implement-autofixing-for-comma-dangle-rule?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nightwing**

### CODE REVIEW

**Comment by IanVS** [comment]
I believe the commit message should start with "Update:" instead of "New:".  

"New" is for brand new features, whereas "Update" is for backwards-compatible improvements. (see http://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changes)

**Comment by nzakas** [comment]
We are going to hold off on this for now, so closing.

**Comment by ianobermiller** [comment]
> We are going to hold off on this for now, so closing.

@nzakas Could you please explain why? We use ESLint internally at Facebook, and I'd rather not fork the rule internally.

**Comment by ilyavolodin** [comment]
@ianobermiller The reason is overlapping ranges. You can see more information in the discussion for this PR: #4418 Basically, this has a potential to conflict with other rules and itself.

**Comment by ianobermiller** [comment]
@ilyavolodin I don't really buy these arguments. We know that lots of autofixes *might* conflict with each other (if they are both enabled and both need to fix the same line). But I don't see why that should preclude us from adding them at all; the argument about eslint user experience being worse if it takes longer must be weighed against eslint *not* fixing things it certainly could. 

If the main autofixes that conflict with `comma-dangle` are the spacing rules, it seems arbitrary that those get precedence. This should be implemented in core, and as @nilsboy said let the user figure it out.

**Comment by ilyavolodin** [comment]
@ianobermiller I don't think we are saying this is never going to be implemented. Autofixing is experimental feature, and we still don't have a good grasp at all of the things we need to watch out for. It's already been proposed to take another look at our approach for autofixing in 3.0 timeframe and try to figure out how we can change the core to minimize amount of potential issues. So I think this PR being closed is more of a "postponed" and not necessarily "won't fix".

**Comment by ianobermiller** [comment]
@ilyavolodin Thanks for the response. Looking forward to autofixing becoming a first-class feature.

**Pull request closed without merging**
