### PR TITLE
Chore: Remove needless filter call

### PR DESCRIPTION
**Pull request by Connormiha**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

I removed needless `filter` call and moved checking to next `forEach`.

### CODE REVIEW

**Comment by ljharb** [comment]
To me this doesn't seem like an improvement. `comments` isn't going to have millions of items in it, so the perf of this is effectively identical.

**Comment by Connormiha** [comment]
> To me this doesn't seem like an improvement. `comments` isn't going to have millions of items in it, so the perf of this is effectively identical.

Filter looks very strange at this place. Because after filter, was called `forEach` with filtering by many params(via if + return).

**Comment by ljharb** [comment]
I code like that all the time. It makes the forEach - the side-effecting part - smaller, which makes the code more readable.

**Comment by Connormiha** [comment]
But this code has already included another `if -> return` inside forEach:
```js
if (applyDefaultIgnorePatterns && (defaultIgnoreRegExp.test(node.value) || fallThroughRegExp.test(node.value))) {
   return;
}

if (ignorePattern && customIgnoreRegExp.test(node.value)) {
   return;
}
```

`filter` does not reduce side-effect part at this place.

Before: `filter` + `forEach`(with 2 `if -> return`)
After: `forEach`(with 3 `if -> return` )

**Comment by ljharb** [comment]
That’s an argument for moving those conditions to the filter, not for moving another condition into the forEach.

**Comment by nzakas** [comment]
Folks, what we have here is just a difference of opinion on how to structure such code. In these cases, we default to what is already present in the codebase as there isn’t a discernible benefit to making the change and it’s not worth a long discussion when this comes down to personal preference.

**Pull request closed without merging**
