### PR TITLE
Chore: Enable `typeof` check for `no-undef` rule in eslint-config-eslint

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

```
[ ] Documentation update
[ ] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:
```

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
* (n/a) I've included tests for my change
- [x] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**

As recommended on Gitter, this enables the `typeof: true` option for `no-undef` in `eslint-config-eslint`. It should hopefully prevent errors like the one in #7100.

**Is there anything you'd like reviewers to focus on?**

The tests will fail due to the issue in #7100, so I'll rebase this branch after that issue gets fixed.

### CODE REVIEW

**Comment by platinumazure** [comment]
Thanks for the PR! I'll see if I can rustle up some reviewers for #7102 quickly and then we can get this in. :smile:

**Comment by mysticatea** [comment]
:+1:

**Comment by ilyavolodin** [comment]
:+1:

**Comment by gyandeeps** [comment]
👍

**Comment by mysticatea** [comment]
I added `accepted` label.
But this requires to rebase after #7102 is merged, since CI build is failing currently.

**Comment by platinumazure** [comment]
LGTM!

**Comment by vitorbal** [comment]
LGTM. Thanks, @not-an-aardvark!

**Pull request merged**
