### PR TITLE
fix func-style expression option example

### PR DESCRIPTION
**Pull request by craigmichaelmartin**

### CODE REVIEW

**Comment by pedrottimark** [comment]
Good eyes! It looks like a two-part inconsistency which I neglected to follow up in #5198 my bad 😳

In the JSON `"expression"` should be `"declaration"` because that is the form that would need an exception to allow arrow functions:

```json
"func-style": [2, "expression", { "allowArrowFunctions": true }]
```

And therefore the example you noticed can move as it was to the end of the **declarations** section just before **When Not To Use It**

```js
/*eslint func-style: [2, "declaration", { "allowArrowFunctions": true }]*/

var foo = () => {};
```

Does that make sense? If yes, can you please:

1. Edit the file.
2. Start your commit message with Docs:
3. Squash your previous and this new commit into one as described in http://eslint.org/docs/developer-guide/contributing/pull-requests#step5
4. Push your branch to your fork to update this pull request.

Thanks again!

**Comment by craigmichaelmartin** [comment]
Thank you for your kind and helpful reply! I'll have something in a minute.

**Comment by ilyavolodin** [comment]
LGTM. @pedrottimark let me know if you think it's good to merge.

**Comment by pedrottimark** [comment]
:+1:

**Comment by ilyavolodin** [comment]
Thanks for the PR!

**Comment by pedrottimark** [comment]
@craigmichaelmartin If you have an eye for detail and would like to keep your momentum going with further contributions to eslint, we are working this month on consistency of the sentence which precedes example code.

Compare the page you just edited to some rules in the list under Possible Errors which have the pattern: Examples of **incorrect/correct** code…

To make sure that the guidelines in #5446 are clear, it would be a big help if someone other than me takes a share of the rule pages. Interested?

**Comment by craigmichaelmartin** [comment]
I definitely feel for your goal. When I found this error, I was setting up eslint for the first time and noticed many of the inconsistencies between rules. As a user it is taxing to reacquaint yourself with the terminology and flow for each rule. That said, I've got a full load for the foreseeable future. Feel free to ping me in the future, and best of luck! :)

**Pull request merged**
