### PR TITLE
New: List target files (fixes #11005)

### LINKED ISSUE #11005: add --list-target-files option
**The version of ESLint you are using.**

5.7.0

**The problem you want to solve.**

I'm working on https://awesomecode.io, our users may not use `eslint` directly on their shell, we have a requirement to list target files so that our users can add ignore patterns properly.

**Your take on the correct solution to problem.**

We can add prefix `DEBUG=eslint:linter` to get target files, but it's very slow and its output contains too many verbose text.

My solution is to add `--list-target-files` option, then it gets all target files without parsing files, so it's super fast. Its output is straightforward, only lists the target filenames.

### PR DESCRIPTION
**Pull request by flyerhzm**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[X] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

It can list target files without parsing files.

**Is there anything you'd like reviewers to focus on?**

It's easy to debug what files are parsed and what are not.

### CODE REVIEW

**Comment by flyerhzm** [comment]
#11005

**Comment by flyerhzm** [comment]
https://github.com/eslint/eslint/issues/11005

**Comment by flyerhzm** [comment]
@not-an-aardvark issue is added.

**Comment by ilyavolodin** [comment]
As the underlying issue hasn't been accepted, and there hasn't been any discussion on this PR for a while, I'm going to close it. Thanks again for the PR.

**Pull request closed without merging**
