### PR TITLE
Chore: rename shadowed global

### PR DESCRIPTION
**Pull request by UziTech**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [ ] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Tell us about your environment**

* **ESLint Version:** 6.8.0
* **Node Version:** 12.13.0
* **npm Version:** 6.13.7

**What did you do? Please include the actual source code causing the issue.**

use rollup to include eslint in the browser

**What did you expect to happen?**

bundle `eslint/lib/linter/linter.js`

**What actually happened? Please include the actual, raw output from ESLint.**

rollup error:

```sh
[!] Error: Unexpected token
node_modules\eslint\lib\rules\no-obj-calls.js (50:33)
48:                 const traceMap = {};
49:
50:                 for (const global of nonCallableGlobals) {
                                     ^
51:                     traceMap[global] = {
52:                         [CALL]: true
```

#### What changes did you make? (Give an overview)

rename variable `global` to `g`

### CODE REVIEW

**Comment by mdjermanovic** [comment]
I'm not against this change if it would help, but as far as I know `global` isn't a reserved word. 

I believe this could be a bug in `@rollup/plugin-commonjs` as the code on which the parser throws seems to be the following:

```js
for (const commonjsHelpers.commonjsGlobal of nonCallableGlobals) {
    traceMap[commonjsHelpers.commonjsGlobal] = {
        [CALL]: true
    }; 
}
```

It looks like the local `global` variable was transformed as if it was the Node's `global`. This doesn't happen if the plugin is used with `commonjs({ ignoreGlobal: true })`.

**Comment by ljharb** [comment]
global is very much not a reserved word.

**Comment by mdjermanovic** [comment]
I'm anyway :+1: to rename this variable because it's shadowing the global `global`, in order to avoid possible errors if the code gets changed in the future.

**Comment by UziTech** [comment]
`commonjs({ ignoreGlobal: true })` did work to prevent the error in rollup, but I agree shadowing the `global` variable might have unintended effects in the future.

**Comment by mdjermanovic** [comment]
> `commonjs({ ignoreGlobal: true })` did work to prevent the error in rollup, but I agree shadowing the `global` variable might have unintended effects in the future.

Though, `{ ignoreGlobal: true }` might break something else. It might be good to anyway open an issue at https://github.com/rollup/plugins since this does look like a bug in the plugin.

**Comment by kaicataldo** [comment]
Marking as accepted as I do think it's best not to shadow Node's `global` object. We should change the commit message. Maybe `Chore: rename shadowed global`?

**Comment by kaicataldo** [comment]
Thanks for contributing!

**Pull request merged**
