### PR TITLE
docs: add keyboard controls to docs search results

### PR DESCRIPTION
**Pull request by shanpriyan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
- Added keyboard navigation of docs search results using `ArrowUp` and `ArrowDown`
- Pressing `Esc` key will close the search results dropdown and focuses the input
- Added `⌘ + K` key binding to focus the search field

#### Is there anything you'd like reviewers to focus on?
Similar to [eslint/eslint.org/issues/309](https://github.com/eslint/eslint.org/issues/309)

### CODE REVIEW

**Review by harish-sethuraman — APPROVED** [review]
LGTM. Closes https://github.com/eslint/eslint.org/issues/309

**Review by amareshsm — APPROVED** [review]
LGTM

**Review by snitin315 — APPROVED** [review]
LGTM. Thanks for contributing ⭐

**Comment by snitin315** [comment]
@shanpriyan CI is failing. can you once rebase on top of the `main` branch?

**Comment by shanpriyan** [comment]
> @shanpriyan CI is failing. can you once rebase on top of the `main` branch?

Done.

**Pull request merged**
