### PR TITLE
Fix: indent check for else keyword with Stroustrup style (fixes #5218)

### LINKED ISSUE #5218: `indent` rule are missing a problem at `else` when I'm using Stroustrup style.
`indent` rule are missing a problem at `else` when I'm using Stroustrup style.
On `v2.0.0-rc.1`.

**Code:** test.js

```js
/* eslint indent: 2*/
{
    if (a) {
        foo();
    }
  else {
        bar();
    }
}
```

**Expected:**

```
$ eslint test.js --no-ignore --no-eslintrc

test.js
  6:2  error  Expected indentation of 4 space characters but found 2  indent

✖ 1 problems (1 errors, 0 warnings)
```

**Actual:**

No errors.

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM

**Comment by gyandeeps** [comment]
ping @BYK

**Comment by BYK** [comment]
@gyandeeps LGTM. I'm just concerned about how complicated indent got but I have started working on the rewrite.

**Comment by gyandeeps** [comment]
I guess complication is nature of indent based on the number of different patterns we have.
Looking forward to your re-write. Let me know if you need help or brainstorm.

**Pull request merged**
