### PR TITLE
Update: Add AssignmentPattern to space-infix-ops

### PR DESCRIPTION
**Pull request by BYK**
Related to #3299.

### CODE REVIEW

**Comment by BYK** [comment]
Updated the commit to fix lint errors.

**Comment by ilyavolodin** [comment]
Can you rebase? And also change commit message to include issue that this is fixing?

**Comment by BYK** [comment]
Rebased.

@ilyavolodin - This is not fixing any issue AFAIK. I was inspired by the discussion in #3299, that's about it. If we require an issue for every commit/PR I can create one but before that we need to resolve the dispute about this with @michaelficarra so keeping the commit message the same for now.

**Comment by michaelficarra** [comment]
I'd prefer we implement this and variable initialiser checks in a separate rule. If duplicate object properties and duplicate class elements are different rules, these certainly should be as well.

**Comment by BYK** [comment]
@michaelficarra - if we can find a good way to remove variable init checks from `space-infix-ops` rule, I'm okay with this approach. The reason I implemented it here was because the code was already there and very easy to amend :)

**Comment by BYK** [comment]
@ilyavolodin - okay fixed the commit message to reference the issue too. The failure is because `node 012` timing out for no reason again.

**Comment by michaelficarra** [comment]
@BYK What do you mean "good way"? Just revert #465.

**Comment by BYK** [comment]
>@BYK What do you mean "good way"? Just revert #465.

That would be a breaking change. That's what I mean by a "good way" :) I'd prefer renaming the rule to reflect that it covers `=` too at this point TBH.

@nzakas any thoughts?

**Comment by michaelficarra** [comment]
Why would it be breaking? It just warns on fewer things than it did before. Breaking would be warning on things that it did not (and was not expected to) before. So actually, merging this as is would be breaking.

**Comment by nzakas** [comment]
@BYK we do require an issue for every PR, but I'm not sure how this relates to #3299. Let's start with a fresh issue, describe the bug you think you found, and we can go from there.

**Comment by BYK** [comment]
@nzakas - Submitted #3380 and tried to explain the situation a bit. Please LMK if you find my initial attemp messy so I can try clarifying. @michaelficarra may also help improving it :)

**Comment by BYK** [comment]
@michaelficarra - anything that breaks previously established assumptions is a breaking change. I'd argue that people expect this rule to apply all `=`s so I disagree. That said I see your point. Let's continue on #3380?

**Comment by BYK** [comment]
>I'd argue that people expect this rule to apply all =s so I disagree.

To be clear, I have no data to back this up so it is just an opinion, not a fact.

**Comment by ilyavolodin** [comment]
LGTM

**Comment by BYK** [comment]
@ilyavolodin - Updated commit tag to be `Update:` instead of `Fix:`

**Pull request merged**
