### PR TITLE
Fix: Consolidate try/catches to top levels (fixes #5243)

### LINKED ISSUE #5243: 2.0 eslint --init doesn't save the config file
1. I use version 2.0 (just installed)
2. I typed in my command line 'eslint --init', answered the questions and tried to save as an js of jaml file
3. I expected to save my config file on my current directory.
4. Nothing happened, file didn't save on my directory.

### PR DESCRIPTION
**Pull request by IanVS**
This also prevents needing to pass the `callback` to each function, instead letting it be handled within the `prompt` function.  Any error at any point in the processing should now be caught and displayed.

### CODE REVIEW

**Comment by IanVS** [comment]
The reason this fixes #5243, is that it will now error and explain that an npm project must be set up before using a popular style guide (due to needing to install a shared config).

**Comment by IanVS** [comment]
@btmills, how does this look to you?

**Comment by nzakas** [comment]
Lgtm. Will wait for @btmills to approve.

**Comment by btmills** [comment]
LGTM! This is a much better way to do it. Nice.

**Pull request merged**
