### PR TITLE
Docs: describe all RuleTester options (fixes #4810)

### LINKED ISSUE #4810: Document expected error line and column properties
@mjomble pointed out in [#4807 (comment)](https://github.com/eslint/eslint/pull/4807#discussion_r48448802) that http://eslint.org/docs/developer-guide/working-with-rules#invalid-code doesn't mention the optional `line` and `column` properties on the expected error object. We should document their existence and mention cases where they might be necessary.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29410238-document-expected-error-line-and-column-properties?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**
**What issue does this pull request address?**

#4810, #6709

**What changes did you make? (Give an overview)**

Added descriptions for `parser`, `settings`, and `globals` to test descriptions. Also added mention of using `line` and `column` for invalid tests.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

**Comment by platinumazure** [comment]
Per #6709, perhaps you might want to add a reference to `filename` as well? That way you could kill two issues with one PR.

**Comment by nzakas** [comment]
Yeah, good call.

**Comment by ilyavolodin** [comment]
LGTM, but waiting another day for others to look

**Comment by gyandeeps** [comment]
LGTM, waiting for others to review.

**Pull request merged**
