### PR TITLE
Fix: Add exceptions (refs #9233)

### PR DESCRIPTION
**Pull request by doodadjs**
**What is the purpose of this pull request? (put an "X" next to item)**

[X ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))

**What changes did you make? (Give an overview)**

Add exceptions to the "camelcase" rule, either by name or with a RegExp.

**Is there anything you'd like reviewers to focus on?**

Yes, the "by name" option, please.

**What rule do you want to change?**

camelcase

**Does this change cause the rule to produce more or fewer warnings?**

More

**How will the change be implemented? (New option, new default behavior, etc.)?**

New "exceptions" option

**Please provide some example code that this change will affect:**

```js
 function execute_GET(req, res) {
 }
 function execute_POST(req, res) {
 }
 function execute_HEAD(req, res) {
 }
 ....
```

**What does the rule currently do for this code?**

All fail the test.

**What will the rule do after it's changed?**

All pass the test when function names added to the "exceptions" list.

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the pull request. Can you please fill out the [rule change proposal template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md)?

**Comment by doodadjs** [comment]
Please help me with merging.

**Comment by not-an-aardvark** [comment]
It's possible that this pull request will be merged in the future. However, before that happens we will need you to fill out the [rule change proposal template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md) to clarify what this change is actually doing, and why you think it would be a useful addition.

See our [pull requests guide](https://eslint.org/docs/developer-guide/contributing/pull-requests) for more details about what to expect when making a pull request.

**Comment by ilyavolodin** [comment]
Why can't you name those function `executePost`, `executeGet`, etc.

**Comment by doodadjs** [comment]
@ilyavolodin: No, I want to stay with "execute_*", sorry.

**Comment by doodadjs** [comment]
I have an issue with the PR, will commit some changes soon, sorry.

**Comment by platinumazure** [comment]
I'm not sure this is an appropriate/necessary change, because it should be possible to use [`id-match`](https://eslint.org/docs/rules/id-match) instead of camelcase to achieve what you need. Or, you can use [inline configuration comments](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments) to suppress errors on those lines.

**Comment by doodadjs** [comment]
@platinumazure Sure, I could deactivate "camelcase", but that's not what I want.

**Comment by platinumazure** [comment]
@doodadjs You could deactivate `camelcase` and use `id-match` to achieve camelcase rules, except for the function names for which you want to make an exception. `id-match` can do everything `camelcase` can do and more. Honestly, the `camelcase` rule is almost obsolete as a result.

If you decide to give it a try, please feel free to stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you need any help.

**Comment by doodadjs** [comment]
Closed too soon, problem is with globals.

**Comment by doodadjs** [comment]
Closing now. "id-match" is the proper way.

**Comment by not-an-aardvark** [comment]
I'm glad you figured it out. Thanks for the contribution regardless!

**Pull request closed without merging**
