### PR TITLE
Chore: Cache `node_modules` on travis

### PR DESCRIPTION
**Pull request by SimenB**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

**What changes did you make? (Give an overview)**
Add caching of `node_modules` in Travis.

This make `npm install` basically free, instead of the 90 sec it takes
now

https://docs.travis-ci.com/user/caching/

**Is there anything you'd like reviewers to focus on?**
- Does something like it exist for Appveyor?
- Should `npm 3` always be installed on travis? (node 4 bundles npm 2)

### CODE REVIEW

**Comment by gyandeeps** [comment]
When would the cache get invalidated?
I think installing all the time make it great bcz we r running against latest and greatest.

**Comment by SimenB** [comment]
You can invalidate in manually in travis, but all it does is zip up the folder specified `node_modules` and upload it. Next time it's downloaded and unzipped, then `npm install` will see it's already got everything (or maybe not), and be done early. Afterwards, a new version is zipped, then rinse and repeat.

This cache is per branch and per PR at least.

If you always want to test against latest, just enable greenkeeper

**Comment by gyandeeps** [comment]
What was the problem faced by  you, which we are trying to solve here?
Why I ask is because we want to makesure we have a problem before we try to solve something.

**Comment by SimenB** [comment]
My "problem" is that the build takes 30-50% longer than it needs to.

Not a huge issue I suppose, but easy to fix 😄

**Comment by platinumazure** [comment]
At this point, I'm not convinced of the utility (our PR volume is low enough that a few minutes on the build is not a big deal, IMO). Do you believe the experience is terrible from a PR submitter perspective?

**Comment by not-an-aardvark** [comment]
I don't think we should do this. If a dependency gets updated and it breaks our build, we will want to know about it. If we cache `node_modules`, then the old version of the dependency will get used, so we won't notice the breakage on travis.

**Comment by kaicataldo** [comment]
As someone who frequently makes pull requests, I personally haven't found this to be a major annoyance. This doesn't seem worthwhile to me unless we can automate the invalidating of the cache when a new version of a package is published.

**Comment by nzakas** [comment]
FWIW, this was discussed previously and we decided not to do it: https://github.com/eslint/eslint/issues/5641

I'm also of the mind that we shouldn't do this.

**Comment by ilyavolodin** [comment]
Agree. We've had some issues before with new versions of non-pinned libraries that were caught by build system. With caching it might not happen until the cache is invalidated.

**Comment by gyandeeps** [comment]
Thanks for the contribution @SimenB . I think the team has decided to not pursue this approach/change.

**Comment by vitorbal** [comment]
I would just like to make sure it's clear from our part (and I'm pretty sure I speak for the whole team) that we really appreciate all your contributions lately to ESLint, @SimenB!

**Pull request closed without merging**
