### PR TITLE
chore: Use build hook for docs deploy

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

Workflow change

#### What changes did you make? (Give an overview)

I switched the docs deploy workflow to use a Netlify build hook instead of building the website locally. I verified that this will trigger a full build and deploy to production.

#### Is there anything you'd like reviewers to focus on?

Please double-check that this will work correctly. :)

### CODE REVIEW

**Comment by mdjermanovic** [comment]
> I switched the docs deploy workflow to use a Netlify build hook instead of building the website locally. I verified that this will trigger a full build and deploy to production.

I can see two deploys triggered by hook, but the version on the site is still 8.15.0:

https://new.eslint.org/docs

**Comment by mdjermanovic** [comment]
Probably because publishing is locked to a deploy that was on May 19.

**Comment by nzakas** [comment]
Welp, it appears I was once again confused by the Netlify terminology. So it was deployed but not published. I guess we do need to manually build in order to publish. I don’t see any additional options with build hooks.

**Comment by mdjermanovic** [comment]
Is the problem that we have locked the publishing, or that build hooks cannot publish at all?

**Comment by nzakas** [comment]
It's that auto-publishing is turned off. As best I can tell:

* **build** - means building the artifact
* **deploy** - means deployed to a test environment
* **publish** - means deployed to the production environment

So build hooks will build and deploy but not publish unless auto-publishing is on.

Let's try adding `--prod` to the current script and see if that gets us where we want to be.

**Comment by mdjermanovic** [comment]
Maybe we could set up the site to auto-build/deploy/publish from another branch on every update of that branch, and force-update that branch on releases. That would also allow for fixing critical UI bugs directly on the published site between releases without changing the content.

**Comment by nzakas** [comment]
> Maybe we could set up the site to auto-build/deploy/publish from another branch on every update of that branch, and force-update that branch on releases.

That was where I started, too. I just wasn’t sure if we wanted to add another step to the release process. Let’s see if this PR works and we can always add another branch later.

**Pull request merged**
