### PR TITLE
chore: pin WebdriverIO dependencies to specific versions

### PR DESCRIPTION
**Pull request by aladdin-add**
It may be the latest version that is causing the browser tests to keep failing. This commit removes the `^`, so that npm installs the exact version.

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ x] Other, please explain:

### CODE REVIEW

**Comment by aladdin-add** [comment]
@christian-bromann can you look at the failing - it was happening even pinned all the related-deps.

**Comment by christian-bromann** [comment]
@aladdin-add this seems to Chrome behaving differently in the latest `stable` version rather than WebdriverIO. I will take a look to verify.

**Comment by christian-bromann** [comment]
It seems like browser tests on `main` just pass fine: https://github.com/eslint/eslint/actions/runs/11839789108/job/32997767812

**Comment by mdjermanovic** [comment]
> It seems like browser tests on `main` just pass fine: https://github.com/eslint/eslint/actions/runs/11839789108/job/32997767812

It needed several attempts to pass. Last couple of weeks, the test has failed more often than not. It usually fails with "navigation canceled, as new navigation is requested by reload":

```
[0-0] RUNNING in chrome - file:///tests/lib/linter/linter.js
[0-0]  Error:  WebDriver Bidi command "browsingContext.navigate" failed with error: unknown error - navigation canceled, as new navigation is requested by reload
[0-0] FAILED in chrome - file:///tests/lib/linter/linter.js

 "concise" Reporter:
========= Your concise report ==========
chrome (v131.0.6778.69) on linux
❌ Failed to setup tests, no tests found
```

**Comment by mdjermanovic** [comment]
> @mdjermanovic @aladdin-add shall we merge this?

It doesn't seem that pinning dependencies to any particular version fixes the test, so merging this wouldn't help. Seems like we should close this and open a new PR to update the dependencies to the latest versions when the problem is fixed in them. @aladdin-add what do you think?

**Comment by aladdin-add** [comment]
sounds good. I'll send a new pr for testing.

**Pull request closed without merging**
