### PR TITLE
Upgrade: Updated puppeteer version to v4.0.0

### PR DESCRIPTION
**Pull request by odidev**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[X] Other, please explain: 

#### What changes did you make? (Give an overview)

Updated Puppeteer version to latest in package.json as the latest puppeteer version has support for aarch64 platform and also added architecture check to set ```CHROME_BIN``` path in karma.conf.js.

### CODE REVIEW

**Comment by kaicataldo** [comment]
@eslint/eslint-team Could we get another pair of eyes on this?

**Comment by g-plane** [comment]
We currently have no such testing environment (aarch64), so it's hard to verify.

**Comment by odidev** [comment]
Thanks for merging this PR @btmills it will be really helpful if you could make a release with the changes in this PR.

**Comment by btmills** [comment]
@odidev you can subscribe to https://github.com/eslint/eslint/issues/13470 for updates on our next release, which is currently scheduled for July 17th.

**Pull request merged**
