### PR TITLE
Chore: upgrade doctrine@2.0.1

### PR DESCRIPTION
**Pull request by Aladdin-ADD**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Doctrine 2.0.1 was never released. We hit an error during release process, but none of us have permissions to release it manually.

**Comment by Aladdin-ADD** [comment]
it's weird that we didn't release 2.0.1, but a tag was there. need to delete?

**Comment by ilyavolodin** [comment]
We could either manually role back package.json to version 2.0.0 and release again now that the issue has been fixed, or we could manually push new release to npm. Either way works.

**Comment by platinumazure** [comment]
I don't think we can upgrade to 2.0.1 since that was a failed release. I'm going to mark as "do not merge" for now.

**Comment by platinumazure** [comment]
Closing since #9656 upgraded to doctrine@^2.0.2. Thanks for contributing @Aladdin-ADD!

**Pull request closed without merging**
