### PR TITLE
Breaking: remove `no-empty-label` (fixes #5042)

### LINKED ISSUE #5042: no-empty-label errors on labelled if statement
Labels apply to statements, not loops specifically. This is defined in §12.12 in the [Ecmascript 3](http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%203rd%20edition,%20December%201999.pdf) and [Ecmascript 5](http://www.ecma-international.org/ecma-262/5.1/#sec-12.12) standards, as well as §13.13 in the [Ecmascript 2015 (6.0) standard](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-labelled-statements).

Grammar (ES3/5):
```
LabelledStatement :
    Identifier : Statement
```
<sup>ES6 (ES2015) grammar not shown since it spans multiple rules</sup>

This means labels also apply to if statements.

```js
someLabel:
if (true) {
	console.log('first');
	break someLabel;
	console.log('second');
}
```

outputs:

```console
$ node iflabel.js
first
```

ESLint seems to treating labelled if statements as invalid. In fact, it appears other block statements are being considered as invalid as well.

```js
var obj = {foo: 'bar', qux: 'qix'};

someLabel:
with (obj) {
	console.log(qux);
	break someLabel;
	console.log(foo);
}
```

outputs:

```console
$ node withlabel.js
qix
```

and even normal blocks:

```js
someLabel: {
	console.log('first');
	break someLabel;
	console.log('second');
}
```

outputs:

```console
$ node blocklabel.js
first
````

However, with the following `.eslintrc`

```json
{
  "rules": {
    "no-empty-label": 2
  }
}
```

ESLint errors out with:

```
3:1  error  Unexpected label "someLabel"  no-empty-label
```

Which is incorrect.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30144606-no-empty-label-errors-on-labelled-if-statement?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #5042 

- Two options are added to `no-labels`: `allowLoop` and `allowSwitch`.
  Those substitute for `no-empty-label`.
- `no-empty-label` is removed.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM

**Comment by nzakas** [comment]
@mysticatea can you also add a note in the 2.0.0 migration guide?

**Comment by gyandeeps** [comment]
@nzakas I think he did already for the rule deprecation.

**Comment by nzakas** [comment]
I don't see it: https://github.com/eslint/eslint/blob/master/docs/user-guide/migrating-to-2.0.0.md#removed-rules

**Comment by gyandeeps** [comment]
Its inside this PR: https://github.com/eslint/eslint/pull/5129/files#diff-4e8fb7bccbeea097f675ce88b6e35e46R55

**Comment by nzakas** [comment]
Oops! Totally missed that. Thanks.

**Comment by gyandeeps** [comment]
:+1:

**Comment by Qix-** [comment]
Awesome, thanks so much everyone :+1:

**Pull request merged**
