### PR TITLE
added all globals for full jshint compatibility

### PR DESCRIPTION
**Pull request by valorkin**
dependant on https://github.com/sindresorhus/globals/pull/17

### CODE REVIEW

**Comment by nzakas** [comment]
If you want to support specific environments, please file an issue. I'm not willing to blindly include everything JSHint includes without reviewing them first.

**Comment by valorkin** [comment]
@nzakas 
I suppose this ones would be good to have, because they are widely used:
`phantom`,` jquery`, `prototypejs`, `shelljs`

No so popular:
`mootools`, `couch`, `qunit`, `dojo`

this one are useless because already included in `node` or some other:
`nonstandard`, `browserify`, `devel`, `typed`

useless:
`yui`, `rhino`

**Comment by valorkin** [comment]
@nzakas to be clear about my intentions as a lot of eslint users I want to replace 
jshint and jscs with eslint

one more issue where I would really appreciate your help
there gulp-eslint project, but maintainer is lost attention to this module
https://github.com/adametry/gulp-eslint/issues/24
may be you know how to solve this

Regards, Dima

**Comment by nzakas** [comment]
Please for an issue so we can discuss.

**Pull request closed without merging**
