### PR TITLE
Fix: `indent` does not check FunctionDeclaration nodes properly

### LINKED ISSUE #3173: function body indentation false positive ("indent" rule)
With this code:

```js
export function create (id, xfilter, rawType,
                        width=defaultWidth, height=defaultHeight,
                        footerHeight=defaultFooterHeight,
                        padding=defaultPadding) {
  // ... function body, indented two spaces
}
```

And this config:

```json
"indent": [2, 2, { "indentSwitchCase": true }]
```

There is an unexpected error:

```
/t.js:6:2: Expected indentation of 24 characters.
```

I expect to be able to use 2 spaces indentation for the function body. The indentation of the function parameters should not effect the body.

### PR DESCRIPTION
**Pull request by BYK**
Fixes #3173

### CODE REVIEW

**Comment by gyandeeps** [comment]
@BYK Can also include the exact code form the issue as a unit test please?

**Comment by BYK** [comment]
@gyandeeps I added a simplified version of it. Is that not okay? The one in the issue is a bit too long.

**Comment by BYK** [comment]
@gyandeeps - you got it

**Comment by gyandeeps** [comment]
Awesome. Thanks
Just curious based on the recent test addition, did we also fix this issue(https://github.com/eslint/eslint/issues/3279) with this PR?

**Comment by BYK** [comment]
@gyandeeps - I added that code to tests and it still fails with the same error because that portion is treated as a `BlockStatement` having a return statement in it, instead of a `FunctionExpression`. Weird thing is, the `BlockStatement` is under a `FunctionExpression`. Looks like a parser bug to me TBH.

**Comment by gyandeeps** [comment]
I dont think its a parser issue because it parses it correctly (as far I can see)
But just curious what happens if you remove the export fro your current unit test and let them be regular functions?

**Comment by BYK** [comment]
@gyandeeps - they still pass with this patch (they fail without it).

I'll look into #3279 separately. It looks related but probably there's something else I'm missing because they are `FunctionExpression` nodes anyways (this one is fixing for `FunctionDeclaration` nodes).

**Comment by gyandeeps** [comment]
This looks good to me. Thanks

**Pull request merged**
