### PR TITLE
Fix: Install required eslint plugin for "standard" guide (fixes #6656)

### LINKED ISSUE #6656: Install all required eslint plugins for "standard" style guide
**What version of ESLint are you using?**

3.0.1

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**What did you do? Please include the actual source code causing the issue.**

eslint --init

Select `Standard`.

**What did you expect to happen?**

All the required eslint plugins would be installed.

**What actually happened? Please include the actual, raw output from ESLint.**

Only `eslint-plugin-standard` was installed, but not `eslint-plugin-promise`.

### PR DESCRIPTION
**Pull request by feross**
**What issue does this pull request address?**

#6656 

**What changes did you make? (Give an overview)**

`eslint-config-standard` peer depends on `eslint-plugin-promise`, so
let's install that for users.

**Is there anything you'd like reviewers to focus on?**

Nothing. Just so you know, you guys are awesome 👍

### CODE REVIEW

**Comment by feross** [comment]
Just signed the CLA 👍

**Comment by ilyavolodin** [comment]
LGTM, but waiting another day for others to look

**Comment by IanVS** [comment]
LGTM too.

**Comment by alberto** [comment]
LGTM. Thanks for contributing.

**Pull request merged**
