### PR TITLE
Update: auto-fix global strict mode (fixes #12034)

### LINKED ISSUE #12034: Automatically fix strict configured as "global"
**The version of ESLint you are using.** v6.1.0

**The problem you want to solve.** I want `eslint --fix` to be able to automatically add `"use strict";` at the top of modules when [strict](https://eslint.org/docs/rules/strict) is configured as `"global"`.

**Your take on the correct solution to problem.** Someone should add a fixer to the strict rule that handles the `"global"` mode.

**Are you willing to submit a pull request to implement this change?** Yes! See: https://github.com/eslint/eslint/pull/12035

### PR DESCRIPTION
**Pull request by christianbundy**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[X] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)** Previously ESLint was able to report errors when the strict rule had the "global" option, but it wasn't able to fix the error. This commit adds an automatic fix that adds `'use strict'; ` to the beginning of each file that doesn't already have a strict mode declaration.

**Is there anything you'd like reviewers to focus on?** This is my second contribution to ESLint and I'm probably doing at least *something* wrong, so I'd appreciate any input or suggestions on how to
improve this code. My main concerns right now:

- This uses single-quotes, which seems like an unnecessary opinion.
- This adds a ~~single space~~ newline, which also seems ~~like an unnecessary opinion~~ fine?
- This passes tests but there could be edge-cases I haven't considered.

Thanks for your help!

### CODE REVIEW

**Comment by ljharb** [comment]
Any file with a function that uses `this`, or references undeclared variables, or attempts to alter nonconfigursble/nonwriteable properties, would break with this autofix - typically autofixes are only permitted when they are safe.

**Comment by christianbundy** [comment]
Are there any suggestions that you could make, or do you think this is out-of-scope for ESLint?

**Comment by ljharb** [comment]
I can think of a number of ways the rule could determine an autofix isn’t safe; but i suspect it’d be difficult to come up with a way to guarantee its safe.

**Comment by platinumazure** [comment]
I agree with @ljharb: I don't think it's safe to put this fix in the core ESLint rule. Maybe other team members will feel differently.

That said, you are welcome to create a custom rule and add the fix there (you could even use something like [`eslint-rule-composer`](https://github.com/not-an-aardvark/eslint-rule-composer) to leverage the original rule as much as possible and only change the fix logic).

**Comment by christianbundy** [comment]
Thanks a lot of the thoughts on this PR! Closing now.

**Pull request closed without merging**
