### PR TITLE
New: add "multiline" option to padding-line-between-statements (#9642)

### PR DESCRIPTION
**Pull request by hotforfeature**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

https://github.com/eslint/eslint/issues/9642

**What changes did you make? (Give an overview)**
Added an `isMultilineStatement(node)` function to the rule, and implemented a new `"multiline"` option that uses It. I also modified the `"multiline-block-like"` option to use the new function.

**Is there anything you'd like reviewers to focus on?**
I haven't added tests yet, I'm trying to wrap my head around how the test cases work. Any help or suggestions are welcome.

### CODE REVIEW

**Comment by platinumazure** [comment]
Looks like both #9642 and #9491 relate to this general idea. #9491 is accepted right now.

@hotforfeature Could you please take a look at both of the issues linked above and let us know if #9642 is definitely proposing something that #9491 is missing (or vice versa), or if the proposal in #9491 might be suitable for your use case?

**Comment by hotforfeature** [comment]
Yes, it looks like #9491 is proposing the same thing as what I proposed and added. I must have missed it when searching through the issues before I created mine.

**Comment by platinumazure** [comment]
@hotforfeature No problem. Since #9491 is accepted, do you want to modify this PR to match that issue and close the other issue? Thanks!

**Comment by Aladdin-ADD** [comment]
closing, since #8668 get merged. thanks for contributing!

**Pull request closed without merging**
