### PR TITLE
feat: update eslint-scope to ignore `"use strict"` directives in ES3

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

Updates `eslint-scope` to include https://github.com/eslint/eslint-scope/pull/87.

#### What changes did you make? (Give an overview)

Updated package.json, and added tests for two core rules that will be affected by this change:

* `no-invalid-this` will have fewer warnings.
* `no-eval` will have more warnings.

#### Is there anything you'd like reviewers to focus on?

Marked as draft as it currently uses eslint-scope from GitHub.

### CODE REVIEW

**Comment by ljharb** [comment]
I think this should be considered a breaking change; there exists no workaround to enforce ES3 syntax and *also* that it will parse in ES5+ with strict mode in the same eslint run.

**Comment by mdjermanovic** [comment]
@ljharb eslint-scope is already released with this change, this PR only updates dependency requirements to ensure consistent behavior with ESLint v8.9.0.

This change is only related to scope analysis, and now it will work correctly for ES3. In particular, `this` in functions in ES3 environments refers to the global object regardless of `"use strict"`.

**Comment by ljharb** [comment]
@mdjermanovic right. but it won't work correctly for ES3 code that runs in an ES5+ engine, which is what actually matters. `ecmaVersion: 3` means "ES3 syntax", it doesn't mean "i am only running code in an ES3 engine", because precisely zero people are doing that.

**Comment by ljharb** [comment]
At any rate, it's clear the decision is made, but what this means is that I have to pin my shared eslint config forever at v8.8.0, since with v8.9.0+, i will run the risk of breaking over 10% of npm's download traffic, because eslint will allow code that runs in IE 6-8 but breaks in every other browser.

**Comment by mdjermanovic** [comment]
I understand that, but this is a case where same code works differently in ES3 and ES5 engines. This change fixes analysis for ES3, and brings a possibility to correctly analyze code for both ES3 and ES5 (albeit, with two runs).

**Comment by ljharb** [comment]
Before, strict code that works in ES5+ would always work in ES3.

In other words, this change allows code patterns that break in every modern browser from now until the end of time, and will *only ever* work in ancient ES3 engines.

**Pull request merged**
