### PR TITLE
Chore: `leave` only takes one argument: `node`

### PR DESCRIPTION
**Pull request by dimitropoulos**
**What is the purpose of this pull request? (put an "X" next to item)**
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

**What changes did you make? (Give an overview)**
removed an unused argument

**Is there anything you'd like reviewers to focus on?**
as far as I can tell by the two existing usages this is not used:

1. https://github.com/eslint/eslint/blob/5dad0b1d80c9cf380c49f46266c35d461d3cecad/lib/linter.js#L668
1. https://github.com/eslint/eslint/blob/5dad0b1d80c9cf380c49f46266c35d461d3cecad/lib/util/source-code.js#L402

### CODE REVIEW

**Comment by dimitropoulos** [comment]
@aladdin-add done. :)

**Comment by platinumazure** [comment]
Is this a public API?

I think we should examine why the function had two parameters in the first place, to see if they might be needed (especially for consumers outside of ESLint, if this is a public API), before we merge this change.

**Comment by dimitropoulos** [comment]
no, I do not believe it's in the public api.  it was introduced [here](https://github.com/eslint/eslint/commit/1c2aafdc03467ab3a3291b238f561f784b60616e#diff-71079228fe3e221a1fdbfe8b5f24efc8R155) and never touched again.

though.. even if it were in the public API it wouldn't matter because it's an unused argument.  perhaps @mysticatea (the author of the line in question) can weigh in?

**Comment by platinumazure** [comment]
> though.. even if it were in the public API it wouldn't matter because it's an unused argument.

If it's in the public API, then other people could be using that argument outside of ESLint. In that case it would be a breaking change. If it's not part of the public API, then this isn't a breaking change.

I think you're probably right that the traverser isn't part of the public API, but I would like a team member to confirm.

**Comment by mysticatea** [comment]
That argument has come from `estraverse` library. Because the `Traverser` class was introduced as a tweaked `estraverse`.

I don't mind with either way. It's consistent with the `enter` handler if the second argument exists, but we can add it when we need.

**Comment by dimitropoulos** [comment]
interesting.  from [what I can see](https://github.com/estools/estraverse/blob/6ebdf08ea4b4429ccc2e36a6f9405cbbb878ed7d/estraverse.js#L734) `estraverse` doesn't have the second argument either.

Why would it be desirable to have the same arguments as another handler (the `enter` handler, in this case)?

thanks :)

**Comment by mysticatea** [comment]
> interesting. from what I can see estraverse doesn't have the second argument either.

Here: https://github.com/estools/estraverse/blob/6ebdf08ea4b4429ccc2e36a6f9405cbbb878ed7d/estraverse.js#L328

> Why would it be desirable to have the same arguments as another handler (the enter handler, in this case)?

It's API design. Symmetric is helpful for predictable for the users of the `Traverser` class.

**Comment by aladdin-add** [comment]
closing, as described in https://github.com/eslint/eslint/pull/11748#issuecomment-494981511 .

Thanks for contributing regardless!

**Pull request closed without merging**
