### PR TITLE
Update: add propertiesPattern for id-match rule

### PR DESCRIPTION
**Pull request by tinymins**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

New feature: add new option `propertiesPattern` and it's `errorMessage` config to provide more humanized error report.
```js
/* eslint id-match: [2, "^[a-zA-Z]+$", { 
  "propertiesPattern": "^[a-z_][a-zA-Z]*$",
  "errorMessage": "Identifier '{{name}}' is not in camelcase.",
  "propertiesErrorMessage": "Properties identifier '{{name}}' is not in lower camelcase."
}] */
const someObject = {
  _propertiesCanStartWithUnderscore: true,
};
```

**Is there anything you'd like reviewers to focus on?**

Temporarily not.

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Hi, thanks for the pull request!

Would you mind splitting this up into smaller PRs? It's generally easier to discuss and review proposed changes when they're not all bundled into the same PR, because this allows some of the changes to be merged incrementally. If there is disagreement about a particular feature of a large PR, then the entire PR ends up blocked, but if there is disagreement about a feature on one of several smaller PRs, then the other PRs can still get merged while that feature is discussed.

It would also be useful if you could fill out the [bug report template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md) for the bugs that you're fixing, and the [rule change proposal template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md) for the new options that you're proposing. At a glance, it seems like the fixes/options that this PR introduces could be worthwhile, but it's hard to tell because the motivation for these options isn't clear.

**Comment by tinymins** [comment]
@not-an-aardvark Thanks, the reason why I merged all changes together is that the change is too large. If the PR got splitted into several parts, each one will get conflicted with any other one.

But if splitting is still recommended, I'll try my best start dealing with it now.

**Comment by platinumazure** [comment]
Definitely please let's split this. If you're worried about conflicts, maybe you could just create PRs for the changes you think are most important/valuable first. Thanks!

**Comment by tinymins** [comment]
I'll do this later, thanks!

**Comment by nzakas** [comment]
@tinymins sorry we lost track of this. What we're asking for is to split the bug fixes and the enhancements into separate pull requests so we can evaluate them separately. If you are willing to do that, we're happy to take a look at each of them. It's just too difficult to figure out which changes apply to which problems in this PR.

Thanks, and apologies again for losing track of this.

**Comment by kaicataldo** [comment]
@tinymins One more friendly ping. Are you willing and able to continue working on this?

**Comment by tinymins** [comment]
> @tinymins One more friendly ping. Are you willing and able to continue working on this?

Sorry for the delay, I'll restart working on this as soon as possible.

**Comment by kaicataldo** [comment]
No problem! Given that https://github.com/eslint/eslint/pull/10554 was merged, it's not clear to me what the remaining changes here will be. Before you start work on it, do you mind either creating a new issue with a proposal of what changes you'd like to make? Once we accept that, then we can start looking at a PR.

Usually it would be fine to just update this PR, but given that it's been open for such a long time and it's changed quite a lot since it was first made, I think it would be clearer to start fresh. Making a new issue will hopefully also mean that it'll get a lot more visibility and discussion. Thanks!

**Comment by kaicataldo** [comment]
Thanks for making a new issue! Can we close this PR now, and if the issue gets accepted, create a new PR? It’ll be a lot easier for everyone reviewing the issue and PR to follow what’s going on if we can separate from the previous proposal.

**Comment by ilyavolodin** [comment]
Closing this PR based on the last comment. Please feel free to reopen it when the issue gets accepted.

**Pull request closed without merging**
