### PR TITLE
Fix: change err report in constant condition (fixes #9398)

### LINKED ISSUE #9398: no-constant-condition reported error range is too broad
**Tell us about your environment**

* **ESLint Version:** 4.8.0
* **Node Version:** 8.3.0
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "rules": {
    "no-constant-condition": "error"
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
if (true) {
  something();
}

something(true ? 1 : 0);
```

**What did you expect to happen?**

The reported error ranges should only include the constant conditions themselves. In the above cases, the words "true".

**What actually happened? Please include the actual, raw output from ESLint.**

The reported error ranges include the entire statement/expression that the constant condition is part of.

```json
$ eslint test.js --format json | jq
[
  {
    "filePath": "/home/lydell/bugs/eslint/test.js",
    "messages": [
      {
        "ruleId": "no-constant-condition",
        "severity": 2,
        "message": "Unexpected constant condition.",
        "line": 1,
        "column": 1,
        "nodeType": "IfStatement",
        "source": "if (true) {",
        "endLine": 3,
        "endColumn": 2
      },
      {
        "ruleId": "no-constant-condition",
        "severity": 2,
        "message": "Unexpected constant condition.",
        "line": 5,
        "column": 11,
        "nodeType": "ConditionalExpression",
        "source": "something(true ? 1 : 0);",
        "endLine": 5,
        "endColumn": 23
      }
    ],
    "errorCount": 2,
    "warningCount": 0,
    "fixableErrorCount": 0,
    "fixableWarningCount": 0,
    "source": "if (true) {\n  something();\n}\n\nsomething(true ? 1 : 0);\n"
  }
]
```

Expected:

```diff
@@ -7,11 +7,11 @@
         "severity": 2,
         "message": "Unexpected constant condition.",
         "line": 1,
-        "column": 1,
+        "column": 5,
         "nodeType": "IfStatement",
         "source": "if (true) {",
-        "endLine": 3,
-        "endColumn": 2
+        "endLine": 1,
+        "endColumn": 9
       },
       {
         "ruleId": "no-constant-condition",
@@ -22,7 +22,7 @@
         "nodeType": "ConditionalExpression",
         "source": "something(true ? 1 : 0);",
         "endLine": 5,
-        "endColumn": 23
+        "endColumn": 15
       }
     ],
     "errorCount": 2,
```

**Note:** I don't know how the reported `"source"` properties are supposed to work, so I can't tell whether they are correct or not.

Visual representation of the problem:

screenshot from 2017-10-07 14-53-15

Notice how much more than the constant conditions are underlined.

See also: https://github.com/steelbrain/linter-ui-default/issues/398#issuecomment-331632791 and onwards.

### PR DESCRIPTION
**Pull request by VictorHom**
**What is the purpose of this pull request? (put an "X" next to item)**
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

**What did you do? Please include the actual source code causing the issue.**
To update the node in the report so that the error underlines in code editor linter is more accurate.

The node type in the report had to be updated as well.

**What did you expect to happen?**
For example, from the issue - with this fix, the linter looks like so
screen shot 2017-10-13 at 11 14 49 pm

### CODE REVIEW

**Comment by platinumazure** [comment]
By the way, if you need to restart the PR checks, you can also close and reopen the pull request rather than pushing commits. Also, team members should be able to access Travis and AppVeyor and restart the builds there (well, I'm not sure about AppVeyor). Hope this helps in future :smile:

**Comment by VictorHom** [comment]
Thanks for the labels. I'll try to remember that for next time.

I'm going to keep this open for a few days and address comments in that time.

**Comment by not-an-aardvark** [comment]
Thanks for the PR!

> I'm going to keep this open for a few days and address comments in that time

To clarify, should we wait on merging this until you address some comments?

(Generally, if you want to indicate that something shouldn't be merged, it's good to add the "do not merge" label so that it doesn't get merged by mistake.)

**Comment by VictorHom** [comment]
Ah all I meant was to keep it open and see if anyone had thoughts on it. I'll merge it today

**Pull request merged**
