### PR TITLE
add execScript to no-eval rule (See #2873)

### PR DESCRIPTION
**Pull request by mozfreddyb**
As discussed in #2873.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Can you update commit message to follow our guidelines please? http://eslint.org/docs/developer-guide/contributing#step-2-make-your-changes

**Comment by mozfreddyb** [comment]
I have changed the commit message.

**Comment by michaelficarra** [comment]
After looking further into the documentation, it appears this function behaves like an indirect call to eval, which is considerably less problematic. :-1:.

**Comment by mozfreddyb** [comment]
Can you please be elaborate? Why is this less problematic?

**Comment by michaelficarra** [comment]
Unlike direct eval, `execScript` cannot access or make changes to the containing scope.

**Comment by mozfreddyb** [comment]
> **Remarks**
> Script executed through the execScript method can access all global variables available to the calling script

https://msdn.microsoft.com/en-us/library/ms536420%28VS.85%29.aspx


Do I misinterpret this article or do we misunderstand each other? :-)

**Comment by michaelficarra** [comment]
You should research the difference between direct and indirect call to eval. Here is the relevant spec section: http://ecma-international.org/ecma-262/6.0/#sec-function-calls-runtime-semantics-evaluation

**Comment by nzakas** [comment]
Good point. 

@mozfreddyb what he's saying is that `execScript` acts more like `setTimeout` in the way it executes code, so it would make more sense in no-implied-eval. I think he's right.

**Comment by mozfreddyb** [comment]
OK, I've tried to bring this into the no-implied-eval rule then.
I also tried to convey the changes in the rule documentation, as I assumed that this belongs into the same commit.

**Comment by nzakas** [comment]
Lgtm. Thanks for your patience and willingness to work through the details of this.

**Pull request merged**
