### PR TITLE
chore: fix off-by-one `min-width: 1023px` media queries

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

Updates css for the new docs site.

We have `min-width: 1023px` in several media queries. This seems like an off-by-one error as it matches >= 1023px which was probably not the intention.

#### What changes did you make? (Give an overview)

Changed `min-width: 1023px` to `min-width: 1024px` in media queries.

#### Is there anything you'd like reviewers to focus on?

`max-width: 800px` in multiple places also looks suspicious, but I wasn't sure about that one so I left it out from this PR.

### CODE REVIEW

**Comment by nzakas** [comment]
@SaraSoueidan can you comment on this? Is this intentional?

**Comment by SaraSoueidan** [comment]
@nzakas It was intentional, yes. 

It's not a new practice. It ensures the “desktop” media queries aren't triggered on a 1024p-wide viewport, which has typically been a tablet (such as iPad) size. This practice has been carved in my brain for years that it comes naturally now.

If @mdjermanovic has tested the site on medium-size displays and found no issues, then this PR LGTM.

**Comment by mdjermanovic** [comment]
> It ensures the “desktop” media queries aren't triggered on a 1024p-wide viewport, which has typically been a tablet (such as iPad) size.

I'm confused now. If we don't want these styles to apply on 1024px, then shouldn't this actually be `min-width: 1025px`?

Before & after this change are same on 1024px:

<details>
<summary>1024px before & after this change</summary>

image

</details>

But different on 1023px, because both `min-width: 1023px` and `max-width: 1023px` styles that we have apply when the width is exactly 1023px:

<details>
<summary>1023px before this change</summary>

image



</details>

<details>
<summary>1023px after this change</summary>

image

</details>

**Comment by nzakas** [comment]
I followed up with Sara (she’s been extremely busy) and she said to go ahead and merge this.

**Review by nzakas — APPROVED** [review]

**Pull request merged**
