### PR TITLE
fix: array-bracket-spacing fixer comments fix (fixes #13319)

### LINKED ISSUE #13319: array-bracket-spacing autofix removes inline comments
**Tell us about your environment**

* **ESLint Version: 7.0.0**
* **Node Version: v14.2.0**
* **npm Version: v6.14.4**

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
I can reproduce it with just:

<details>
<summary>Configuration</summary>

```js
module.exports = {
	rules: {
		"array-bracket-spacing": [ "warn", "never", {
			objectsInArrays: false,
			arraysInArrays: false
		} ],
	}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

A comment with a space preceding or following it causes the autofix to delete the comment.
```js
let a = [ /* test */]
let b = [/* test */ ]
```

**What did you expect to happen?**
I expected just any surrounding spaces to be deleted since eslint won't complain about the following:
```js
let a = [/* test */]
let b = [/* test */]
```

**What actually happened? Please include the actual, raw output from ESLint.**
Running eslint with `--fix` or letting an IDE autofix errors deletes the comment.
```js
let a = []
let b = []
```

**Are you willing to submit a pull request to fix this bug?**
No.

### PR DESCRIPTION
**Pull request by anikethsaha**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
In this check, the comments are being skipped while fix and but they are considered while checking.

#### Is there anything you'd like reviewers to focus on?
fixes #13319 

Let me know if I missed some cases

### CODE REVIEW

**Comment by mdjermanovic** [comment]
This changes behavior a bit and it seems to be inconsistent in some cases:

```js
/* eslint array-bracket-spacing: ["error", "never"] */

[/**/ a]; // error

[ /**/a]; // error

[/**/ /**/a]; // no error, this was error before
```

**Comment by anikethsaha** [comment]
@mdjermanovic I was thinking if it was required to remove that `middle` space? cause as the rule is focussed on the `bracket`'s position right?

**Comment by mdjermanovic** [comment]
> @mdjermanovic I was thinking if it was required to remove that `middle` space? cause as the rule is focussed on the `bracket`'s position right?

I left a [comment](https://github.com/eslint/eslint/issues/13319#issuecomment-643652630) on the issue.

**Comment by nzakas** [comment]
Closing due to age

**Pull request closed without merging**
