### PR TITLE
Fix: Allow project relative globs in overrides config (fixes #9740)

### LINKED ISSUE #9740: Usage of minimatch's `matchBase` prevents overrides from targeting project root files.
**Tell us about your environment**

* **ESLint Version:** 4.13.1
* **Node Version:** v8.6.0
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**
Default.

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  rules: {
    'no-console': 'error'
  },
  overrides: [
    {
      files: ['index.js'],
      rules: {
        'no-console': 'off'
      },
    }
  ]
};
```
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

**Files present:**
```js
// src/index.js
console.log('no-console is disabled due to overrides improperly matching nested file');
```

```js
// index.js
console.log('no-console is properly disabled');
```

**Command Ran:**
```bash
eslint index.js src/index.js
```

I've created a repo to make testing this easier:

```bash
git clone git@github.com:rwjblue/__match-base-issue.git
cd __match-base-issue
yarn
yarn test
```

**What did you expect to happen?**

Expected output:

```
/path/to/src/index.js
  1:1  error  Unexpected console statement  no-console

✖ 1 problem (1 error, 0 warnings)
```

**What actually happened? Please include the actual, raw output from ESLint.**

No errors were reported.

---

### Detailed Explanation

The new `overrides` feature added in ESLint 4.1.0 (https://github.com/eslint/eslint/pull/8081) is _awesome_ (massively better than "sprinkling" config around in a repo or in specific files via comments). Unfortunately, there is a hole in the `overrides` support due to a small implementation decision.

When the overrides are processed to determine if each individual override matches or does not match a given file, the [`matchBase` option](https://github.com/isaacs/minimatch#matchbase) is passed in to [minimatch](https://github.com/isaacs/minimatch) and the includes/excludes are processed.

The code that does this [can be found here](https://github.com/eslint/eslint/blob/8e1a095f4cc3b371a0a424b66e13ec77734193a2/lib/config/config-ops.js#L362-L381), but is also included below for explanation purposes:

```js
function pathMatchesGlobs(filePath, patterns, excludedPatterns) {
  const patternList = [].concat(patterns);
  const excludedPatternList = [].concat(excludedPatterns || []);

  patternList.concat(excludedPatternList).forEach(pattern => {
    if (path.isAbsolute(pattern) || pattern.includes("..")) {
      throw new Error(`Invalid override pattern (expected relative path not containing '..'): ${pattern}`);
    }
  });

  const opts = { matchBase: true };

  return patternList.some(pattern => minimatch(filePath, pattern, opts)) &&
    !excludedPatternList.some(excludedPattern => minimatch(filePath, excludedPattern, opts));
}
```

The usage of `matchBase: true` to `minimatch` means that patterns without a `/` in them will be matched against the `filePath`s base name (i.e. `path.basename(filePath)`). This allows matching "all JS files" as simple as `*.js` instead of using `**/*.js`. Unfortunately, this means that it is now
impossible to match files in the project root without _also_ matching nested files with the same base name.

### PR DESCRIPTION
**Pull request by rwjblue**
Prior to this change it was impossible to target files in the project root in `overrides` configuration without _also_ matching files of the same name in nested directories. This was due to the specific options passed to `minimatch` when testing the provided patterns.

After this change, it is now possible to prefix a glob with `./` to "anchor" it to the project root. This has the perceived behavior of making it possible to target `./index.js` independently of `src/index.js` (for example). Due to the fact that `./` previously _never matched_ anything (as evidendenced by the unit tests) we can be certain that this does not break any preexisting globs.

Fixes #9740.

### CODE REVIEW

**Comment by platinumazure** [comment]
I'm not going to lie, I don't like the different behavior for `*.js` vs `./*.js`. It feels kind of unintuitive to me.

I really wish we had handled the override globs the same way we handle globs passed in as lint arguments (i.e., `*.js` would be the same as `./*.js`). But I guess it's too late to think about changing that until the next major.

**Comment by rwjblue** [comment]
I totally agree with you, I only settled on this as a path forward that was non-breaking. 

One possible option would be to deprecate or warn on _any_ values that don’t start with `./` throughout 4.x and then remove the `matchBase` minimatch option in 5.x (making `./*.js` and `*.js` to mean the same thing again).

**Comment by not-an-aardvark** [comment]
It seems like that would break the use case in https://github.com/eslint/eslint/issues/8813#issuecomment-337344850.

**Comment by rwjblue** [comment]
@not-an-aardvark - I don’t think so, but the glob would change a bit. In that case, you would use `**/*.js` (or other extension).

**Comment by rwjblue** [comment]
FWIW, I would be interested in trying to help find a path forward in #8813 with some team guidance once this is done. We (ember-cli team) are happily using `overrides` as a much better system than “sprinkling” configuration throughout many files/directories.

**Comment by not-an-aardvark** [comment]
(Disclaimer: I'm a bit confused by how our glob matching works in general -- please correct me if the following is wrong.)

If I'm understanding correctly, `**/*.js` would not work for the use case described in https://github.com/eslint/eslint/issues/8813#issuecomment-337344850, because the path gets resolved from the location of a config file, which is in `node_modules/`. For example, if a config in `node_modules/eslint-config-foo/index.js` contains `overrides: ['*.js']`, it currently matches all JavaScript files regardless of location. However, if the config contained `**/*.js` instead, then it would only get applied to files matching `node_modules/eslint-config-foo/**/*.js`, which is not the same as the current behavior.

**Comment by platinumazure** [comment]
It seems like this is a similar problem to the overrides/extends issue: We
need to be able to distinguish between a "direct" config and an "extended"
config, and in the latter case, apply the glob patterns relative to the
direct config.

**Comment by mysticatea** [comment]
How about introducing `$CWD` environment variable? `$CWD/index.js` would match to `index.js` on the project root. It's clear even if it exists in shareable configs.

**Comment by j-f1** [comment]
`$PWD` is a standard environment variable (at least on macOS) that contains the current working directory.

**Comment by platinumazure** [comment]
Unfortunately we've let this one sit even through most of the 5.0.0 major release cycle.

Is it worth just making a breaking change here to get more sensible behavior?

(cc @rwjblue, @not-an-aardvark, @mysticatea)

**Comment by nzakas** [comment]
It looks like there was agreement on the problem but not on a solution.

Given that this request would result in a breaking change, it falls under our new RFC process. As such, I'm closing this pull request. If anyone is interested in pushing such a change forward, please submit an RFC. Details can be found here:

https://github.com/eslint/rfcs

Thanks, and apologies for the lack of communication.

**Pull request closed without merging**
