### PR TITLE
Docs: Minor fixes in no-new-func (refs #5451)

### PR DESCRIPTION
**Pull request by brettz9**
`npm run check-commit` says "More than one commit found, please squash", but there is only one commit in this branch/PR. I guess maybe that is because it is checking my original PR.

I wasn't sure whether to even include "(refs #5451)" since the pull request portion of that PR isn't going to be submitted and since commits tagged with "Docs" are stated as not needing their own issue.

### CODE REVIEW

**Comment by brettz9** [comment]
I will wait for your approval on this before preparing the other PRs which I am supposed to put together out of PR #5451.

**Comment by nzakas** [comment]
You can remove the "refs #5451". Doc changes don't require an issue in the commit message, and that's not even an issue. :)

**Comment by brettz9** [comment]
Not sure whether you get notified when amendments are made, but I amended to remove the ref. (With Github redirecting issues to PRs, I thought it might work--oh well...)

**Comment by ilyavolodin** [comment]
LGTM! Thanks for PR!

**Pull request merged**
