### PR TITLE
Fix: id-length rule doesn't catch violations in arrow function parameters (fixes #3275)

### LINKED ISSUE #3275: id-length rule doesn't catch violations in arrow function parameters
For example:

    function sortByString(propertyName) {
        return (a, b) => {
            const
                valueA = a && a[propertyName],
                valueB = b && b[propertyName];

            return (valueA || "").localeCompare(valueB || "");
        };
    }

The rule does not catch `a` or `b` despite the default being min length >= 2.

### PR DESCRIPTION
**Pull request by BYK**

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you!

I have found more missing patterns.
But I'm not sure whether or not those should be handled in this PR.

```js

        {
            code: "class x { }",
            ecmaFeatures: {classes: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "class Foo { x() {} }",
            ecmaFeatures: {classes: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "function foo(x = 0) { }",
            ecmaFeatures: {defaultParams: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "function foo(...x) { }",
            ecmaFeatures: {restParams : true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "var {x} = {};",
            ecmaFeatures: {destructuring: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "var {a: [x]} = {};",
            ecmaFeatures: {destructuring: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "import x from \"x\";",
            ecmaFeatures: {modules: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
        {
            code: "export var x = 0;",
            ecmaFeatures: {modules: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        }
```

**Comment by mysticatea** [comment]
```
        {
            code: "({a: obj.x}) = {};",
            ecmaFeatures: {destructuring: true},
            errors: [{ message: "Identifier name 'x' is too short. (< 2)", type: "Identifier"}]
        },
```

**Comment by BYK** [comment]
@mysticatea  - heh, thanks for all these reminders. I'll be honest, I left these out intentionally in the first pass since we are using ES5 mainly and I wanted people to ask for these before adding them upfront.

I think we should be specific in this PR and then in a new one we should add all the missing ones. Does that make sense?

**Comment by mysticatea** [comment]
Sounds good to me.

**Comment by nzakas** [comment]
Can one of you file an issue for the other missing ones?

**Pull request merged**
