### PR TITLE
New: Banner style (was issue 9361)

### PR DESCRIPTION
**Pull request by jr-grenoble**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

What rule do you want to change?
indent

Does this change cause the rule to produce more or fewer warnings?
No change in the amount of warnings.

How will the change be implemented? (New option, new default behavior, etc.)?
New option, named `banner`.

Please provide some example code that this change will affect:
If the banner option is set to true, the following code becomes legal (see end brackets):
```js
class Polygon {
    constructor (
        num, // number of sides 
        radius, // radius of the excircle
        ) {
        this.num = num;
        this.radius = radius;
        }
    get exradius () {
        return this.radius;
        }
    get inradius () {
        const vector = [
            Math.cos ( Math.Pi / this.num ),
            Math.sin ( Math.Pi / this.num )
            ];
        return someComputationWith(vector);
        }
    }
```

What does the rule currently do for this code?
This rule currently rejects banner-style code and issues errors for all closing brackets (parens, braces, square brackets).

What will the rule do after it's changed?
The rule will now accept this style.

**What changes did you make? (Give an overview)**
I added the `banner` boolean option, defaulting it to `false` so that there's no impact when not in use.
I mainly followed the recommendation from @not-an-aardvark and took care of handling special cases such as indentation resulting from the use of CallExpression, FunctionalExpression… as well as handling the cases associated with parentheses around function parameters. I also handled the cases associated with arrays,  objects and curly braces within templates.

**Is there anything you'd like reviewers to focus on?**
This is my first submission to eslint…
The name of the option is `banner`, but it could be changed to something else, e.g. `banner-style` or `ratliff-style`.
The documentation is minimal, but I can add more if needed.

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the pull request!

I'm not really convinced this is worth adding to core. In general, we only add rule options if they're important enough that the rule is deemed incomplete without the change (see our [rule change documentation](https://eslint.org/docs/developer-guide/contributing/rule-changes#accepting-a-rule-change)). This is a tradeoff between (a) supporting the preferences of as many users as possible, and (b) ensuring that core rules are maintainable in the long term. For proposed options that would only be useful to a small number of users, we generally prefer that people use plugins instead.

In this case, I've never actually seen a JavaScript project that uses this indentation style. (I don't doubt that they exist -- I'm just emphasizing that the style isn't very common.) So I'm unconvinced that this would be useful to enough of our users that it would be worth adding to core.

That said, we can see if there's anyone else on the team who would be willing to champion this proposal.

**Comment by platinumazure** [comment]
I agree with @not-an-aardvark's points in general.

That said, I'm wondering if there's anything in the indentation/token traversal logic that we could consider exporting as a public API (maybe in a separate package)? The logic we have in the rule now is very useful and allows for high extensibility in the indent rule, and advising people to write their own version of the rule means copying the rule and making tweaks (eslint-rule-composer will not be practical here). So I wonder if that's something we should consider.

**Comment by not-an-aardvark** [comment]
I'm not opposed to the general idea, but I'm concerned that exposing the `indent` logic as a separate package would lock us into the current structure of the `indent` rule, and prevent us from making changes to it in the future. It seems like that would require some very careful API design to ensure that we don't make any API promises that we can't keep after refactoring.

**Comment by jr-grenoble** [comment]
I agree with @not-an-aardvark 's position to keep eslint compact and general purpose. Yet, the argument that the banner/Ratliff/Python style is not used much is somewhat a chicken and egg issue: eslint is the dominant linter in the ES space (for good reasons), and as R&D manager of large organizations, I will always mandate that untainted and up to date eslint be used in the build environment, even if it does not fit the indentation style we favor. I assume most organizations and projects do the same. As eslint doesn't support the banner style, this style is in practice "banned" from the ES community: plugins are ok for new rules, but not really practical for existing rules, because of the maintenance cost.

The fact that Ratliff is documented in Wikipedia and has been seen as providing enough benefits that Python made it into the core language shows on the other hand that this is not a minor tweak in coding style.

I know I sound like preaching for my own chapel, but I think a) the option doesn't hurt (the option defaults to false) and b) allowing it might attract more people to the ES community.

**Comment by ilyavolodin** [comment]
Why do you think that this should be done in `indent` rule? Would it be better suited for `brace-style` rule? It would also be much easier to convince us that it's worth adding into that rule, because we try very hard to touch `indent` rule as little as possible (due to the complexity of the rule).

**Comment by platinumazure** [comment]
@ilyavolodin brace-style mostly focuses on the line placement (same line or next line). It doesn't enforce column position of braces, primarily because that's the job of the indent rule.

**Comment by jr-grenoble** [comment]
@ilyavolodin in addition to the answer from @ilyavolodin, brace style only deals with curly braces, while the banner style also applies to indentation of square brackets and parens. Furthermore, the banner style aligns closing parens in line with the parameters/arguments of call and function expressions, hence it depends on the CallExpression, FunctionExpression… options of the indent rule.

Obviously this behavior could be further parametrized (e.g. applying the style only to curly braces and not to other bracketing symbols), but at this stage my implementation assumes one wants to use the style uniformly.

**Comment by ilyavolodin** [comment]
Thanks for the explanation. I don't have strong feelings one way or the other about this change. On one hand, it seems to be a valid style and as it currently stands ESLint would be blocking it. On the other - it adds to indent rule, which is by far the most complex and hardest to support rule we have. I really hate touching indent any more then we have to. I will defer to other members of the team on this proposal.

**Comment by platinumazure** [comment]
This change looks pretty reasonable to me on the whole, and I've seen more than just one person talking about it, so I'm (mostly) convinced that this is a style that some people could actually use. Thus, I'm vaguely in favor of including the change (given how simple it is).

That said, I am worried about potentially opening the floodgates for all sorts of, well, arbitrary-seeming changes/requests if we approve this one. Maybe someone else will want their closing token outdented an extra level (mirror of banner). Maybe someone will want a hanging indent on the body and closing token. Maybe... (etc.) And this isn't a fault of the banner indentation style or its proponents, but as @ilyavolodin said, this rule is already *really* hard to maintain and we wouldn't want to make things unreasonably hard on ourselves. So it seems like we need to draw the line somewhere.

I'll go ahead and :+1: this change, but I will advise that it will be a *massively* uphill battle to get enough support from the team (including a champion) to meet our [consensus requirements](https://eslint.org/docs/maintainer-guide/issues#accepting-issues) for accepting new proposals.

**Comment by not-an-aardvark** [comment]
I'm :-1: for this because I don't think we should add options that are only useful to a very small percentage of our users. This is especially true for the `indent` rule since it's so difficult to maintain with the existing options.

I realize that maintaining a separate plugin imposes a maintenance burden, but it seems like the alternative is for the ESLint team to adopt that same maintenance burden. I don't think the alternative is scalable for very rarely-used options.

**Comment by jr-grenoble** [comment]
Thanks all for the healthy debate. I do sympathize with the urge to keep rules simple. I do however have a couple of observations:

- there are many other rule changes that serve a much smaller population; here, the main point against the pull request is not the size of the target audience, but the difficulty of maintaining "indent".
- this the more so as the whole purpose of the rule change is to onboard developers coming from other backgrounds who are turned off by the lack of support for their idiom. IOW the number of eslint users who use this idiom is currently small because their idiom is not supported…
- as highlighted by @platinumazure, the changes are **very small**, and the burden of maintaining them is proportionally small. In fact, the bulk of the changes are in the test files. Apart from that, the main change in the rule is to turn a 0 into a `options.banner ? 1 : 0` in a couple of lines plus a single if statement addition in the `addElementListIndent` method.

If this helps, I can commit to revalidate or refactor the rule changes at each future iteration of "indent", so that the burden of testing/validating… is on my shoulders.

**Comment by ilyavolodin** [comment]
The argument against this change is not just purely complexity of indent rule, but more around the number of available indentation styles and exceptions to them (https://en.wikipedia.org/wiki/Indentation_style). If we accept somewhat unpopular style, why shouldn't we accept other indentation styles that might be equally underrepresented? Even if each indentation style increases complexity by a few lines of code, ones you do all of the styles + personal preferences for each one, it will turn into code with complexity so high, that nobody will be able to touch it without a fear of breaking something else. Even if we don't accept any other style, just because this PR modifies a few lines of code, doesn't mean it doesn't increase complexity of the rule significantly. Because from now on, whenever we make a change to indent rule, we also have to think about how it will affect ratliff style.

Let me ask a different question. Indent rule allows you to disable indentation checks for certain AST Nodes. Would it be possible to setup configuration that would ignore all of the differences between ratliff style and 1tbs/allman? If it's possible, then you could create pretty light-weight plugin that would enforce just the differences between styles.

**Comment by jr-grenoble** [comment]
@ilyavolodin thanks for the suggestion!

Just to make sure we're on the same page, brace-style is actually complementary to the banner indentation option: depending on your preferences, you can use any of the 3 brace styles (1tbs/allman/stroustrup) _together_ with the banner indent option, and these styles will determine where the _opening_ curly brace is. The banner indent option isn't really concerned with that opening brace, all it does is position the _closing_ brace one indentation level further to the right than in the regular style, thus aligning the closing brace with block statements. Furthermore, the banner option also acts on arrays, sets and parenthesized lists (e.g. parameter lists or argument lists), also pushing the closing bracket one indentation level further.

To follow your suggestion, I tried to look at what I can disable in the indent rule, but the problem is that it seems that I cannot prevent the indent rule from de-indenting closing brackets, whether curly braces, square brackets or parens. Nor can I tell the indent rule to ignore where these brackets are.

So, I think I'm stuck there… Or am I missing something?

ps: as an aside, the fact that indent is so touchy that it is nearly impossible to evolve it looks like a sign that some refactoring/simplification might be needed. If that's the only path, I'm willing to explore it, but I lack the experience of the eslint team with respect to why indent is considered so touchy. Any hints/caveats would be useful. Also let me know if it is seriously worth a try.

**Comment by platinumazure** [comment]
@jr-grenoble I think from my perspective, you're basically on the right track. The indent rule is operates on tokens, but its options API is node based. Options are largely based on node types that are "containers" of other nodes, like IfStatement, FunctionDeclaration, etc. So this proposal represents one of the first options on the API that is node-agnostic and focuses more on tokens.

Regarding refactoring/redesigning the rule: You are probably right, but you should know that we did a major redesign of the rule already for ESLint 4.0. So there might be a little bit of refactoring fatigue among the team now :smile: You may wish to look for the issue/PR for the new rule to see how many different considerations had to be incorporated into the design of the new rule. As Ilya has noted, it's more complicated than you might think. I'll edit the issue/PR numbers into this comment if I find them later (I'm on my mobile now and digging for issues is hard).

Thanks for a great discussion so far!

**Comment by ilyavolodin** [comment]
@jr-grenoble I understand the difference between this and brace-style, however, other indentation styles would also have to modify indent rule (like GNU and Whitesmiths, for example).
So if we were to add an option to disable de-indent on the closing bracket, would that help? (I'm not sure that the right way to go though).
Indent rule has been re-written from a scratch at least 4 times in the last 5 years. The reason why it's so touchy is just the level of complexity and number of different options/preferences that people request.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Pull request closed without merging**
