### PR TITLE
Fix: Report shorthand method names in complexity rule

### LINKED ISSUE #3955: The `complexity` rule shows "anonymous" for shorthand methods.
The rule should show the method name instead of "anonymous".
Plus, the position should be at the head of each method name.

**Code:**

```js
/* eslint-env es6 */
/* eslint complexity: [2, 1] */
var obj = {
    foo(a) {
        return a ? 0 : 1;
    }
};
```

**Actual:**

ESLint v1.5.1

image

**Expected:**

```
4:5 - Function 'foo' has a complexity of 2. 
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26994003-the-complexity-rule-shows-anonymous-for-shorthand-methods?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Lapixx**
Fixes #3955

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks! Can you add some tests that verify this change?

**Comment by Lapixx** [comment]
That should cover the case. Let me know if anything else is missing!

**Comment by mysticatea** [comment]
I thought it needs a test below:

```js
{ code: "var obj = { a: function b(x) { return x ? 0 : 1; } };", options: [1], errors: [{ message: "Function 'b' has a complexity of 2."}] }
```

If a function is in a property, the function can have different name from the property name.
Using the `Property.method` flag, we can detect whether or not the function is a method shorthand property.

```
 || (node.parent.type === "Property" && node.parent.method)) {
```

**Comment by Lapixx** [comment]
Looks like the complexity rule already takes care of that, also before adding the fix for shorthand notation. Checking `node.parent.method` doesn't change the behaviour.

**Comment by mysticatea** [comment]
Ah, I got it.
When the function has own id, it's using own id.

Thank you!

**Comment by Lapixx** [comment]
Should I add the test you mentioned? It covers a new case and I guess it couldn't hurt, right? (not sure about guidelines / conventions.)

**Comment by mysticatea** [comment]
Well, I'm glad if you add the test. It would make clear for future.

**Comment by Lapixx** [comment]
Added it!

**Comment by mysticatea** [comment]
Thank you very much!

**Pull request merged**
