### PR TITLE
Upgrade: bump inquirer to ^7.0.0

### PR DESCRIPTION
**Pull request by josgraha**
**What is the purpose of this pull request? (put an "X" next to item)**
Bump `inquirer` package to `^7.0.0` because 6.x depends on `lodash@4.17.12` which has [Snyk Issue]( https://www.npmjs.com/advisories/1065)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:
Bump `inquirer` package to `^7.0.0` because 6.x depends on `lodash@4.17.12` which has [Snyk Issue]( https://www.npmjs.com/advisories/1065)

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by platinumazure** [comment]
Hi @josgraha, thanks for the PR!

I want to test this locally tonight, then I'll approve the changes. I'll leave this open in case others want to review.

**Comment by platinumazure** [comment]
Note to merger: Commit message needs to start with "Upgrade:"

**Comment by josgraha** [comment]
I'm sorry folks but I misread the [Snyk Issue](https://www.npmjs.com/advisories/1065) only applies to `lodash` prior to `4.17.12`, I don't think this is required unless we just want to upgrade to the latest `lodash` in transitive dependencies

**Comment by platinumazure** [comment]
Hi @josgraha, thanks for following up.

I think we can accept this upgrade anyway as it's pretty low risk, and dependency upgrades are something we sometimes struggle with here. So, I appreciate this contribution nonetheless. Thanks!

**Pull request merged**
