### PR TITLE
Small typo fix in no-useless-call documentation

### PR DESCRIPTION
**Pull request by zpao**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Can you prefix your commit messages with "Docs: " please?

**Comment by zpao** [comment]
Sure. FWIW, if that's something you're going to ask people to do, it might be worth adding that to http://eslint.org/docs/developer-guide/contributing.html (I mean that in the friendliest way - I'm guilty of the same sort of thing!)

**Comment by ilyavolodin** [comment]
It's actually already there: http://eslint.org/docs/developer-guide/contributing.html#step-2-make-your-changes It's just a bit hard to find if you don't know what to look for.

**Comment by zpao** [comment]
Ah so it is, sorry! I just looked at the bulleted list above that. Anyway, rebased. Sorry I didn't use a descriptive branch name (edit on GH is too easy, though I had to go local to rebase anyway) :P

**Comment by ilyavolodin** [comment]
Thanks!

**Pull request merged**
