### PR TITLE
docs: Update Exponentiation operator MDN link

### PR DESCRIPTION
**Pull request by yellowjacketcoder**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
I changed the MDN link for Exponentiation operator

### CODE REVIEW

**Comment by yellowjacketcoder** [comment]
@mdjermanovic Can you check this now?

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by yellowjacketcoder** [comment]
> LGTM, thanks!

No need to thank me, I am enjoying the start of my open-source journey. It's not much but it's honest work :)

**Comment by yellowjacketcoder** [comment]
@mdjermanovic When will these changes go live on the website? I am assuming it will update from here?

**Comment by mdjermanovic** [comment]
> @mdjermanovic When will these changes go live on the website? I am assuming it will update from here?

Yes, documentation on eslint.org website will be updated with the latest changes from this repository during today's release (https://github.com/eslint/eslint/issues/15911).

**Comment by mdjermanovic** [comment]
It's live now:

https://eslint.org/docs/rules/prefer-exponentiation-operator

**Pull request merged**
