### PR TITLE
Docs: Corrected documentation (fixes #6397)

### LINKED ISSUE #6397: Docs: wrong example code for "exceptions" option in id-length rule
[http://eslint.org/docs/rules/id-length#exceptions](http://eslint.org/docs/rules/id-length#exceptions)

It is taking about exceptions, but there is a max property

### PR DESCRIPTION
**Pull request by sibennayak**
Corrected the documentation for Rule id-length #exceptions. The issue was due to a copy paste error. Results can be seen iin /docs/rules/id-length#exceptions

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM. Thanks for PR

**Comment by BYK** [comment]
Thanks! LGTM too.

**Comment by ilyavolodin** [comment]
Ah... Actually I just noticed that commit history doesn't look right. It looks like you merged in changes from #6126 
You probably will need to cherry-pick your changes into a new branch and resubmit. That's probably the easiest way to fix this.

**Comment by sibennayak** [comment]
Maybe I did something out of order during my commit. This was my first time. It seems the documentation is missing the step for pushing the changes. Raised an issue at https://github.com/eslint/eslint/issues/6595

**Comment by vitorbal** [comment]
Seems like this PR does the same as #6593. I think we should merge #6593 instead, since @GramParallelo [originally announced that he would like to work on this first](https://github.com/eslint/eslint/issues/6397#issuecomment-230178542). How should we proceed?

**Comment by nzakas** [comment]
Agreed. I'll merge #6593 in favor of this.

Sorry for the confusion @sibennayak.

**Pull request closed without merging**
