### PR TITLE
Add failing unit test

### PR DESCRIPTION
**Pull request by doug-wade**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

I added a failing unit test that I believe should be passing.  This demonstrates https://github.com/eslint/eslint/issues/8271

**Is there anything you'd like reviewers to focus on?**

Helping me understand where it is appropriate to make the changes to fix this failing test, and what changes those might be.

### CODE REVIEW

**Comment by doug-wade** [comment]
In particular, I set a mess of debugger statements throughout the [no-invalid-this rule](https://github.com/eslint/eslint/blob/master/lib/rules/no-invalid-this.js), and none of them were hit.  It seems that most of the heavy lifting is done in [ast-utils.isDefaultThisBinding](https://github.com/eslint/eslint/blob/master/lib/ast-utils.js#L600), but I'm not sure what all collateral damage will be done if I edit that, although from the doc string, maybe thats a good idea?

**Comment by vitorbal** [comment]
Thanks for the PR!
But as @not-an-aardvark [already pointed out](https://github.com/eslint/eslint/issues/8271#issuecomment-287259340) in #8271, we don't generally support stage 2 syntax in core rules, and eslint-plugin-babel [already has a replacement `no-invalid-this` rule](https://github.com/babel/eslint-plugin-babel#rules) to get around this.

**Comment by vitorbal** [comment]
Closing this. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other questions!

**Comment by doug-wade** [comment]
Hi @vitorbal, thanks for the quick feedback and the helpful links -- it got me fixed up right quick!  Much appreciated.

**Pull request closed without merging**
