### PR TITLE
Update: `space-infix-ops`: new option for PEP8-style default parameters

### LINKED ISSUE #3587: `space-infix-ops`: add option for PEP8-style default parameters?
Would it be possible to add an option to `space-infix-ops` to allow or enforce assignment without spaces for ES6 default parameters?
### The use case for the rule - what is it trying to prevent or flag?

As of ESLint 1.2.0, `space-infix-ops` also applies to assignments. As such, developers who prefer to enforce spaces around assignments as per other ops but wish to omit them _only_ in default function parameters will now receive an unwanted warning or error.
### Whether the rule is trying to prevent an error or is purely stylistic

Purely stylistic, but intended to remove a false positive.
### Why you believe this rule is generic enough to be included

Default parameter value assignments are different from other types of variable assignments, in that they are part of a function's definition. This has different implications for how you read them as you scan through code. As such, developers may wish to apply different formatting rules to them according to their preferred style.

For an example from a community where this feature already exists, [Python's Style Guide (PEP8)](https://www.python.org/dev/peps/pep-0008/#other-recommendations) recommends spaces around all binary operators _except_ for when assigning default parameter values. It's likely that developers with Python experience who are using default parameters will already be using this style.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26305621-space-infix-ops-add-option-for-pep8-style-default-parameters?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BYK**
Fixes #3587 

Sort of a WIP due to 2 reasons:

1. The new option name is not certain yet
2. Whether to enforce no spaces or simply ignore them is not determined yet

### CODE REVIEW

**Comment by nzakas** [comment]
Also, because it's not marked as "accepted" yet. :)

**Comment by nzakas** [comment]
@byk still working on this?

**Comment by BYK** [comment]
Which direction should this patch go? I'll start working on a new rule, `space-ops` with better configuration but in the mean time I think we should have a stop-gap solution.

**Comment by kentor** [comment]
Also should probably add test cases for `function foo({ a=1 })` and `function foo({ a=1 }={})`.

**Comment by nzakas** [comment]
Let's just stick with the new rule. I don't think a stopgap is necessary here

**Comment by ilyavolodin** [comment]
Closing this in favor of a new rule `space-ops`

**Pull request closed without merging**
