### PR TITLE
Upgrade: espree 3.1.4

### PR DESCRIPTION
**Pull request by kaicataldo**
Upgrade Espree for the comment attachment fix: https://github.com/eslint/espree/issues/264

### CODE REVIEW

**Comment by kaicataldo** [comment]
Hopefully this fixes all the cases we saw of incorrect leading comments! The new test's results before the Espree version upgrade in this PR:

screen shot 2016-04-21 at 6 17 24 pm

**Comment by kaicataldo** [comment]
Whoops, had forgotten to make an issue

**Comment by mysticatea** [comment]
This upgrade should fix #5756 also :tada:

**Comment by nzakas** [comment]
Lgtm

**Pull request merged**
