### PR TITLE
Update: add fixer for `no-useless-escape`

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[x] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- [x] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**

This adds an autofixer for [`no-useless-escape`](http://eslint.org/docs/rules/no-useless-escape). When a character is being uselessly escaped (e.g. `"\z"`), the fixer removes the backslash (`"z"`).

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

**Comment by platinumazure** [comment]
I'm not sure we should have a fixer for this rule. Most of the time, when someone is asking in chat about why the rule reported a particular character sequence, it turns out they were intending to have a backslash literal all along, so the correct fix was to double up the backslashes.

I don't think we can know with certainty what the user's intent was (`\\:` vs `:`), so I am :-1: to including autofix on this rule.

**Comment by not-an-aardvark** [comment]
@platinumazure Note that there are already a lot of existing fixers that do things like this. For example, `indent` will fix this:

```js
if (condition)
  doTheFirstThing();
  doTheSecondThing();
```

...to this:

```js
if (condition)
  doTheFirstThing();
doTheSecondThing();
```

...which is semantically the same, even though the user might have intended to do this:

```js
if (condition) {
  doTheFirstThing();
  doTheSecondThing();
}
```

**Comment by mysticatea** [comment]
Thank you for this PR!

I had thought the fixing is very clear until I read @platinumazure 's comment.

Granted, there are issues about that: #5831, #6148, #6514, #6842
Their intentions were `//`.

**Comment by mysticatea** [comment]
Personally, I like this fixing. :worried:

**Comment by platinumazure** [comment]
Sorry, but I'm not convinced fixing is a good idea here. The reason is because, as far as I can tell, it's almost 50/50 whether the correct fix is to add an extra backslash, or to remove the existing backslash and use the unescaped character. I don't think that's something we can predict with any accuracy.

If someone can convince me of how we can reliably predict what the correct fix is for a given report, I'll reconsider. But until then, I remain opposed.

**Comment by nzakas** [comment]
I'm inclined to agree with @platinumazure that the correct fix in this case isn't always obvious, so it would be best not to try to fix it.

As this has already been open for a month and there's some :-1:s here, I'm closing.

**Pull request closed without merging**
