### PR TITLE
Fix: Location info in `dot-notation` rule (fixes #5397)

### LINKED ISSUE #5397: dot-notation line numbers are incorrect
**What version of ESLint are you using?**
demo, 1.10.3

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**

* `dot-notation: 2`
* `espree`

**What did you do? Please include the actual source code causing the issue.**
```js
/* eslint dot-notation: 2 */
getResource()
    .then(function(){})
    ["catch"](function(){})
    .then(function(){})
    ["catch"](function(){});
```

**What did you expect to happen?**
```sh
4:4 - ["catch"] is better written in dot notation. (dot-notation)
6:4 - ["catch"] is better written in dot notation. (dot-notation)
```

**What actually happened? Please include the actual, raw output from ESLint.**
```sh
2:1 - ["catch"] is better written in dot notation. (dot-notation)
2:1 - ["catch"] is better written in dot notation. (dot-notation)
```

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM

**Comment by mysticatea** [comment]
LGTM :+1:

**Comment by michaelficarra** [comment]
I thought you wanted to report the `[`, not the expression.

**Comment by gyandeeps** [comment]
My intention was the location of the property.

**Comment by michaelficarra** [comment]
Okay well that's just not what seemed to be understood by @ilyavolodin and I in #5397.

**Comment by nzakas** [comment]
@gyandeeps the issue does say to report the location of the `[`. For that, you'd need to get the previous token from `node.property `.

**Pull request merged**
