### PR TITLE
Docs: Mark object-shorthand as fixable.

### PR DESCRIPTION
**Pull request by NickHeiner**
The contributing instructions ask for each PR to have an issue as well. I am happy to do that, but in this case it seemed sufficiently trivial that a separate issue was not necessary.

This is a follow-up to #6418.

### CODE REVIEW

**Comment by pedrottimark** [comment]
@NickHeiner Thank you. Your commit message is fine. Docs tag is enough.

Somewhere in docs explains, but possibly not everywhere. Can you do me a favor to paste a link to the section that was not clear to you?

If you point at the right of the heading text, and then click the anchor that appears, the anchor link appears in browser address bar.

**Comment by NickHeiner** [comment]
> Somewhere in docs explains, but possibly not everywhere. Can you do me a favor to paste a link to the section that was not clear to you?

I'm not sure what you're asking me.

**Comment by pedrottimark** [comment]
@NickHeiner Sorry. When you mentioned the contributing instructions in https://github.com/eslint/eslint/pull/6485#issue-161304693 did you mean feedback from the bot or something you read in the docs on the site implied you had to open an issue first. That has come up before, and so I would like to see what we can do to make the requirements clearer for Docs PRs.

**Comment by aubergine10** [comment]
@pedrottimark The only mention I've seen in the guides about not needing separate issue for Docs PRs is a single (easily missed) bullet point here: http://eslint.org/docs/developer-guide/contributing/pull-requests#getting-started

**Comment by NickHeiner** [comment]
Yes @aubergine10 that's exactly what I was going off of. But now that you link to it again, I do see that it says docs-only PRs do not need issues. :smile:

**Comment by pedrottimark** [comment]
Thanks guys. On the main goal, the rules index and rule doc looks good to me 👍

**Comment by nzakas** [comment]
FYI: The bot will warn you if you need an issue for your PR. 

Is this ready for merge?

**Comment by ilyavolodin** [comment]
Yes, good to merge.

**Pull request merged**
