### PR TITLE
Fix: remove dupe error message in bin/eslint (fixes #8964)

### LINKED ISSUE #8964: When a crash occurs, the error message is printed twice
**Tell us about your environment**

* **ESLint Version:** 4.2.0
* **Node Version:** 8.1.4
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
rules:
  no-restricted-syntax: [error, 'Invalid selector [[[[']
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
a;
```

**What did you expect to happen?**

The configuration isn't valid (it includes an invalid selector), so I expected ESLint to output an error message.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint outputted the same error message twice, once with the stack trace and once without:

<details>
<summary>Output</summary>

```
Syntax error in selector "Invalid selector [[[[" at position 18: Expected " ", "." or [^ [\],():#!=><~+.] but "[" found.
Error: Syntax error in selector "Invalid selector [[[[" at position 18: Expected " ", "." or [^ [\],():#!=><~+.] but "[" found.
    at tryParseSelector (/path/to/node_modules/eslint/lib/util/node-event-generator.js:163:19)
    at lodash.memoize.rawSelector (/path/to/node_modules/eslint/lib/util/node-event-generator.js:175:28)
    at memoized (/path/to/node_modules/lodash/lodash.js:10566:27)
    at NodeEventGenerator.eventNames.forEach.rawSelector (/path/to/node_modules/eslint/lib/util/node-event-generator.js:235:30)
    at Array.forEach (native)
    at new NodeEventGenerator (/path/to/node_modules/eslint/lib/util/node-event-generator.js:234:20)
    at Linter.verify (/path/to/node_modules/eslint/lib/linter.js:909:34)
    at processText (/path/to/node_modules/eslint/lib/cli-engine.js:203:31)
    at processFile (/path/to/node_modules/eslint/lib/cli-engine.js:245:18)
    at executeOnFile (/path/to/node_modules/eslint/lib/cli-engine.js:585:25)

```

</details>

This isn't specific to the `no-restricted-syntax` rule -- it seems to occur whenever any error is thrown from anywhere.

### PR DESCRIPTION
**Pull request by VictorHom**
[X ] Other, please explain: remove the dupe error message which re-adds what was previously fixed in [here](https://github.com/eslint/eslint/commit/fc2abb0933e4f34bfaa2d591f5a882e4f1ccf481)

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the PR! Sorry about the delayed response.

The fix in https://github.com/eslint/eslint/pull/8965 was reverted as a result of https://github.com/eslint/eslint/issues/9011 (it was causing some error messages to not appear at all). Has that problem been solved? It seems like if we make only this change, the problem described in https://github.com/eslint/eslint/issues/9011#issuecomment-318879745 will reappear.

**Comment by VictorHom** [comment]
@not-an-aardvark Can you recreate the issue? Im currently using:

(venv) ➜  eslint_sandbox node --version
v8.2.1
(venv) ➜  eslint_sandbox npm -version
5.3.0

With the latest eslint and with this change in the pr, I am not getting duplicated error messages.

Do you have a way to create case where no error message show at all?

**Comment by not-an-aardvark** [comment]
I tested this by adding a space character to the beginning of the `.eslintrc.yml` file in the ESLint repository, (making it invalid YAML), then running `bin/eslint.js Makefile.js`.

On `master`, the output is:

```
Cannot read config file: /path/to/eslint/.eslintrc.yml
Error: end of the stream or a document separator is expected at line 3, column 1:
    plugins:
    ^
YAMLException: end of the stream or a document separator is expected at line 3, column 1:
    plugins:
    ^
    at generateError (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readDocument (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1512:5)
    at loadDocuments (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Object.safeLoad (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
    at loadYAMLConfigFile (/path/to/eslint/lib/config/config-file.js:95:21)
    at loadConfigFile (/path/to/eslint/lib/config/config-file.js:231:22)
    at loadFromDisk (/path/to/eslint/lib/config/config-file.js:530:18)
    at Object.load (/path/to/eslint/lib/config/config-file.js:592:20)
```

On this branch, the output is:

```
YAMLException: end of the stream or a document separator is expected at line 3, column 1:
    plugins:
    ^
    at generateError (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readDocument (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1512:5)
    at loadDocuments (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Object.safeLoad (/path/to/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
    at loadYAMLConfigFile (/path/to/eslint/lib/config/config-file.js:95:21)
    at loadConfigFile (/path/to/eslint/lib/config/config-file.js:231:22)
    at loadFromDisk (/path/to/eslint/lib/config/config-file.js:530:18)
    at Object.load (/path/to/eslint/lib/config/config-file.js:592:20)
```

Note that the line at the top ("Cannot read config file: /path/to/eslint/.eslintrc.yml") is missing when using this branch.

**Comment by kaicataldo** [comment]
Where do we stand with this?

**Comment by kaicataldo** [comment]
Friendly ping!

**Pull request closed without merging**
