### PR TITLE
Docs: Added naming convention details to plugin usage

### PR DESCRIPTION
**Pull request by hbarcelos**
**What is the purpose of this pull request? (put an "X" next to item)**

- [x] Documentation update
- [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
- [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

**What changes did you make?**

Updated the "Working with Plugins" documentation section to clarify the usage of scoped and non-scoped packages for ESLint plugins. This was something that was never really clear to me, which led me to openning #12190 .

**Is there anything you'd like reviewers to focus on?**

I am not sure I made the edits in the right place. If not, please point me to the right direction.

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you for working on this.

I think that this should be in the "[Configuring ESLint](https://eslint.org/docs/user-guide/configuring)" page because it's about configuration rather than the plugin implementation.

**Comment by hbarcelos** [comment]
> Thank you for working on this.
> 
> I think that this should be in the "[Configuring ESLint](https://eslint.org/docs/user-guide/configuring)" page because it's about configuration rather than the plugin implementation. ( in other words, it's for the users of plugins rather than plugin authors)

That actually makes a lot of sense.

I've amended the changes to move the Naming Convention section to the proper page.

**Comment by hbarcelos** [comment]
Even though I amended the commits to use the correct user, the CLA bot is still complaining. What can we do about this?

**Comment by mysticatea** [comment]
I'm not familiar with the CLI checker, but I guess that one of the commits in this PR has a different email.

**Comment by hbarcelos** [comment]
Looks like doing a rebase fixed it.

**Comment by hbarcelos** [comment]
I just did that because one of the CI jobs was complaining about it.
Is it ok to have them failing?

**Comment by platinumazure** [comment]
> Is it ok to have them failing?

No, but I'm surprised the CI jobs enforce that list style. Not sure if we changed something in configuration somewhere...

**Comment by mysticatea** [comment]
No. Read the lint message. You have fixed it with a wrong way.

> docs/user-guide/configuring.md: 359: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
> docs/user-guide/configuring.md: 360: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
> docs/user-guide/configuring.md: 361: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
> https://github.com/eslint/eslint/runs/210954641

**Comment by hbarcelos** [comment]
> No. Read the lint message. You have fixed it with a wrong way.
> 
> > docs/user-guide/configuring.md: 359: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
> > docs/user-guide/configuring.md: 360: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
> > docs/user-guide/configuring.md: 361: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
> > https://github.com/eslint/eslint/runs/210954641

LOL, I feel so stupid :sweat_smile:

I've read the [docs](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md004). Looks like when there's no explicit config, the linter will only ensure consistent usage across the file. That's the reason why it passed when I changed all asterisks to dashed.

Anyways, I've amended the commits, should be okay now.

**Pull request merged**
