### PR TITLE
Fix: sort-keys ignores destructuring patterns (fixes #6896)

### LINKED ISSUE #6896: sort-keys TypeError on destructuring object assignment
**What version of ESLint are you using?**
3.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default ecmaVersion:6

**Please show your full configuration:**
sort-keys:2

**What did you do? Please include the actual source code causing the issue.**
```js
let {a} = 0
```

**What did you expect to happen?**
no error

**What actually happened? Please include the actual, raw output from ESLint.**
```
Cannot read property 'prevName' of null
TypeError: Cannot read property 'prevName' of null
    at EventEmitter.Property (/usr/local/lib/node_modules/eslint/lib/rules/sort-keys.js:127:39)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/usr/local/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:895:36)
    at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/usr/local/lib/node_modules/eslint/lib/util/traverser.js:36:33)
```

@mysticatea #6800

### PR DESCRIPTION
**Pull request by kaicataldo**

### CODE REVIEW

**Comment by kaicataldo** [comment]
Whoops, hub kept the name of my last PR

**Comment by vitorbal** [comment]
LGTM, but waiting another day for others to take a look

**Comment by ilyavolodin** [comment]
LGTM, but waiting another day for others to look

**Comment by platinumazure** [comment]
LGTM, thanks @kaicataldo.

**Comment by mysticatea** [comment]
LGTM, thank you @kaicataldo !

**Pull request merged**
