### PR TITLE
Fix: ignore parser option if set to default parser (fixes #5241)

### LINKED ISSUE #5241: ESLint@2 only working with npm@3?
It appears to me that ESLint@2 is only working with npm@3 now. Is that correct?

I was trying to run [mocha-eslint](https://github.com/BadgeLabs/mocha-eslint) with ESLint@2 and npm@2, but it complained that it `Cannot find module 'espree' from '/Users/tbn/Code/mocha-eslint/node_modules'`. If I use npm@3 instead it works fine.

I've stepped through the code and it looks like ESLint@2 expects `espree` (or any other parser/package) to be installed next to `eslint` in the main `node_modules` folder, while ESLint@1 was apparently okay with `espree` being nested in `node_modules/eslint/node_modules/espree`.

Has this been changed on purpose or should it be considered a bug?

In my limited knowledge the fix should be relatively easy by first looking for the package in the main `node_modules` and if that fails fallback to looking in `node_modules/eslint/node_modules` instead.

### PR DESCRIPTION
**Pull request by kaicataldo**

### CODE REVIEW

**Comment by nzakas** [comment]
I was thinking about this. I tried to create a look up shortcut here:
https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L307

So maybe the right solution is not to ignore the default parser, but rather, to change the lookup to start  from `__dirname ` instead of higher up.

**Comment by nzakas** [comment]
Oops, what I meant is, maybe change https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L315 to `__dirname`

**Comment by kaicataldo** [comment]
Ah yes, that makes sense. Problem is that the block above gets run before it ever hits that - will do a bit more digging and see what else needs to be changed. This is a much better solution though :+1:

**Comment by kaicataldo** [comment]
Alright, I have a better understanding of what's going on now. What you suggested above definitely works, but [this check](https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L308) is currently preventing from that ever being hit.

Seems like we have a few options:
 - Change the aforementioned check
 - Somehow provide a fallback that tries to resolve the module with `__dirname` rather than `filepath` if [this line](https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L446) throws an error. I think we really only want it to make the secondary module resolution (with `__dirname`) if it's the default parser, as a safeguard against any possible side effects.

@nzakas Thoughts/preferences on which route above (or if you have another suggestion) to take?

**Comment by kaicataldo** [comment]
```
if (config.parser) {
    try {
        config.parser = resolveModule.sync(config.parser, {
            basedir: getLookupPath(path.dirname(path.resolve(filePath)))
        });
    } catch(error) {
        if (config.parser === defaultOptions.parser) {
           config.parser = resolveModule.sync(config.parser, {
               basedir: getLookupPath(path.dirname(path.resolve(__dirname)))
           });
        } else {
          throw error;
        }
    }
}
```

**Comment by kaicataldo** [comment]
Sorry, didn't mean to close!

**Comment by kaicataldo** [comment]
Updated to show how this might work if we take the strategy I mentioned above. Will of course squash my commits if this is accepted.

**Comment by nzakas** [comment]
OK, let's go with your original approach of falling back to default if the parser is "Espree". Thanks for the analysis.

**Comment by kaicataldo** [comment]
Just to be clear, do you mean the first commit in this PR?  Thanks for looking this stuff over!

**Comment by nzakas** [comment]
@kaicataldo yes, sorry. I think your original first commit is the way to go.

**Comment by kaicataldo** [comment]
Cool, reverted back to just the original commit.

**Comment by nzakas** [comment]
Lgtm

**Pull request merged**
