### PR TITLE
Support ignore identifier list for no-shadow.

### PR DESCRIPTION
**Pull request by mirek**

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks for the pull request. Please take a moment to read over our [contribution guidelines](http://eslint.org/docs/developer-guide/contributing.html) to see the correct way to format your commit message and the other expectations for a pull request.

Also note that we need an issue describing the problem this is addressing. If an issue already exists, you need to reference it in the commit message; if it doesn't exist, then please create one.

**Comment by mathieumg** [comment]
@mirek Perhaps you could be interested by https://github.com/Cellule/eslint-plugin-shadow-exception

**Comment by nzakas** [comment]
@mirek are you planning on continuing to work on this?

**Comment by mirek** [comment]
Yes but as I see it it's completed, what do you mean by work? Should I add more test or something else?

**Comment by IanVS** [comment]
@mirek It needs to be rebased against master, and the commit message should start with `Update: `

**Comment by nzakas** [comment]
@mirek can you rebase?

**Comment by nzakas** [comment]
No response, so closing.

**Pull request closed without merging**
