### PR TITLE
docs: add background to code-path-diagrams for dark-mode

### PR DESCRIPTION
**Pull request by Tanujkanti4441**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
have made a new container called 'img-container' to wrap all the image diagrams and added the background and border radius property to that new container.

#### Is there anything you'd like reviewers to focus on?
related to issue #16683

### CODE REVIEW

**Review by amareshsm — COMMENTED** [review]
Can you pls add before and after screenshots?

**Comment by Tanujkanti4441** [comment]
<details>
<summary>before</summary>

Screenshot 2023-01-25 092147

</details>

<details>
<summary>after</summary>

Screenshot 2023-01-25 092428

</details>

**Review by snitin315 — COMMENTED** [review]
I'm 👍🏻 on this change for applying white background in light mode and `--color-neutral-300` in dark mode.

@Tanujkanti4441 There is another image in the [Architecture doc ](https://eslint.org/docs/latest/contribute/architecture/) can you also update that page?

**Comment by Tanujkanti4441** [comment]
> I'm 👍🏻 on this change for applying white background in light mode and `--color-neutral-300` in dark mode.
> 
> @Tanujkanti4441 There is another image in the [Architecture doc ](https://eslint.org/docs/latest/contribute/architecture/) can you also update that page?

Done. https://deploy-preview-16822--docs-eslint.netlify.app/contribute/architecture/

**Review by amareshsm — APPROVED** [review]
LGTM. I'm okay with this change.

**Review by harish-sethuraman — APPROVED** [review]
LGTM. Will require someone from @eslint/eslint-tsc  to confirm if this is fine

**Review by snitin315 — APPROVED** [review]
LGTM, thanks for contributing.

**Review by kecrily — APPROVED** [review]
LGTM

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
