### PR TITLE
Docs: Fix JS syntax and doc URL in working-with-custom-formatters.md

### PR DESCRIPTION
**Pull request by nostalic**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Fix a minor JS typo in the custom formatter documentation sample for detailed formatter which causes a syntax error https://eslint.org/docs/developer-guide/working-with-custom-formatters#detailed-formatter

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]

**Comment by nostalic** [comment]
@snitin315 I had to push the change again due to the commit message check - no code changes involved.

Could you please review and approve again if correct? thanks!

**Review by snitin315 — APPROVED** [review]

**Review by mdjermanovic — CHANGES_REQUESTED** [review]
@nostalic thanks for the PR!

The change looks good, but formatter still isn't working as intended because there was another "bug". 

Can you please also change line 198:

```diff
- ruleUrl: data.rulesMeta[msg.ruleId].url,
+ ruleUrl: data.rulesMeta[msg.ruleId].docs.url,
```

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Now it produces output that looks like the example at the end of this section.

**Comment by mdjermanovic** [comment]
Just removed an extra space from the end of the PR title.

**Comment by mdjermanovic** [comment]
Thanks for contributing!

**Pull request merged**
