### PR TITLE
Bug: Add "Error" to the "new-cap" rule exceptions (fixes #2098)

### LINKED ISSUE #2098: new-cap rule could accept "Error" as an exception
Hello,

Currently, the "new-cap" rule has a property "capIsNewExceptions" which defaults to the following value: 
["Object", "Function", "Number", "String", "Boolean", "Date", "Array", "Symbol", "RegExp"]

What do you think about adding "Error" to this list?

Cheers

### PR DESCRIPTION
**Pull request by mickaeltr**
It also:
- sorts exceptions alphabetically (so they are easier to read)
- adds a missing test for the "Symbol" exception.

### CODE REVIEW

**Comment by gyandeeps** [comment]
As per the [contribution guidelines](http://eslint.org/docs/developer-guide/contributing.html), please append you message with `Fix:` and not `Bug:`

**Comment by mickaeltr** [comment]
I wrote "Bug" because #2098 was labelled as bug.

**Comment by gyandeeps** [comment]
Thats fine but here `Fix:` denotes that you fixed a bug with this PR.

**Comment by mickaeltr** [comment]
My bad, I don't know why, I was sure that "Bug" was in the Tag list!

**Pull request closed without merging**
