### PR TITLE
docs: remove manually maintained anchors

### PR DESCRIPTION
**Pull request by kecrily**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Remove manually maintained TOC, and custom anchors (`<a name="anchor-name"></a>`)

GitHub automatically generates anchors and TOC based on the heading in the Markdown file, and I don't think we need to maintain them manually anymore.

截屏2022-12-20 21 12 33

### CODE REVIEW

**Review by mdjermanovic — COMMENTED** [review]
We're publishing the README file and the Table of Contents section seems useful on the npm page, so I'm not sure if we want to remove it.

https://www.npmjs.com/package/eslint

**Comment by kecrily** [comment]
I didn't realize until now that npmjs.org didn't support auto-generated TOC, but they seem to support auto-generated anchors already, I manually added the anchors after the other package links to try. So let's just remove the manually maintained anchors?

Then submit an auto-generated TOC suggestion to npmjs.org and delete the manually maintained TOC separately when it is implemented?

**Comment by snitin315** [comment]
Yes, let's keep the TOC. I'm ok with removing manual anchors 👍🏻

**Comment by mdjermanovic** [comment]
I'd be also fine with removing anchors. @aladdin-add what do you think?

**Comment by aladdin-add** [comment]
yes, I concur! :)

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
