### PR TITLE
Build: Automatically generate rule index (refs #2860)

### PR DESCRIPTION
**Pull request by ilyavolodin**
**What issue does this pull request address?**
Adds a task to release script to automatically generate rule listing page for the website

**What changes did you make? (Give an overview)**
Added a script that retrieves metadata from all core rules, then runs it through ejb template and copies the output into website folder

**Is there anything you'd like reviewers to focus on?**
I tested the script locally, but not as part of the release script (since I don't want to release anything). I think it should work, but another set of eyes should be helpful

### CODE REVIEW

**Comment by nzakas** [comment]
Hmmm, I'm not a fan of having the HTML for the site in this repo. Is it possible to just create a data file (put into `_data` folder in `eslint.github.io`) and then just have a Liquid template that creates the HTML?

**Comment by ilyavolodin** [comment]
Hmm... I guess I could do that. The only issue is first paragraph of text. And removed rules. I can create a separate file in this repository to track removed rules, but I'm not sure what would be a good place to put it in? Any suggestions?

**Comment by nzakas** [comment]
What first paragraph of text are you referring to? And what is the problem with it?

I'd stick the list of removed rules in `conf` for now. That's where most of our meta-data-type stuff currently is.

**Comment by ilyavolodin** [comment]
The paragraph starting with:
>Rules in ESLint are grouped by category to help you understand their purpose.

**Comment by nzakas** [comment]
@ilyavolodin and what's the problem with that paragraph? You said there's an issue but didn't say what the issue is.

**Comment by ilyavolodin** [comment]
Oh, sorry. The issue that I mentioned is that we now keep all of the documentation in this repository. But if we are going to keep the template for index page in the website repository, where do we store that first paragraph? Should it be in this repository, or website? And if it's this one, where should it go?

**Comment by ilyavolodin** [comment]
Updated pull request to automatically generate yaml file instead of run ejs template. The rest can be checked into the website directly.

**Comment by nzakas** [comment]
Ah, I'd say let's just store that first paragraph in the `eslint.github.io` repo. It doesn't change often enough that I'm too worried about it.

**Comment by nzakas** [comment]
LGTM. We just need to agree on where that paragraph goes. I don't think sticking it in `categories.json` makes much sense.

**Comment by ilyavolodin** [comment]
Sounds good. I'll move that paragraph into website repo in the evening.

**Comment by ilyavolodin** [comment]
Removed `intro` from the json file and moved it into website repository (https://github.com/eslint/eslint.github.io/pull/275) I think this should be good now.

**Comment by nzakas** [comment]
Lgtm. I'll leave merging to you, so you can coordinate the changes in the website repo.

**Comment by ilyavolodin** [comment]
Website has auto-generated json file checked in. So I think both are ready to be merged in. The reason why I marked one of them with Do not merge, is that if website PR is merged and eslint one is not, next release it's going to get overridden. So I'll merge both now.

**Pull request merged**
