### PR TITLE
Fix: overindent in VariableDeclarator parens or brackets (fixes #5492)

### LINKED ISSUE #5492: indent.VariableDeclarators insufficient for different scenarios
I ran into a problem just now, with this code:

```js
    const a = 'asdf',
          b = 'asdfjkhg';
    const arrayOfObjects = [
      {
        name: 'Bob',
        age: 32,
      },
      {
        name: 'Mary',
        age: 32,
      },
    ];
```

No matter how I set `VariableDeclarators`, I can't win. :) Either it complains about the alignment of variables `a` and `b`, or if I adjust for that, it complains about the curly braces.

IMO, and according to how I interpret the documentation, `VariableDeclarators` should only be concerned with indentation of variable names, *not* indentation of other syntax such as brackets and braces. In other words, the code above should be totally valid given this setting:

```js
    "indent": [2, 2, {
      "SwitchCase": 1,
      "VariableDeclarator": {"let": 2, "const": 3}
    }],
```

### PR DESCRIPTION
**Pull request by dgreensp**

### CODE REVIEW

**Comment by gyandeeps** [comment]
LGTM. Thanks for the PR.

**Comment by gyandeeps** [comment]
ping @BYK

**Comment by BYK** [comment]
I feel like someone else's gonna complain about this change so not sure if this should be behind an option (no idea what that will be). Also commit log needs to be fixed, see @eslintbot please @dgreensp :)

**Comment by dgreensp** [comment]
@BYK I don't think there's anything controversial here.  All the existing tests pass except one -- so people still get their hanging brackets, etc. etc. -- and this one test was added by you, I think, while fixing https://github.com/eslint/eslint/issues/3329, but the original user report actually expects a single indent here, not a double indent, so the test isn't evidence of some other opinion or intention.  Anyway, it's hard to imagine an editor or IDE putting a double or triple indent after a trailing bracket.

I think I fixed the bot errors; let me know if not!

**Comment by BYK** [comment]
Meh, I'm indifferent since I find this exception case weird anyways. I was simply warning you that this would probably break someone else's preference. 

If @gyandeeps is okay, the code looks good.

**Comment by gyandeeps** [comment]
@dgreensp Have signed our CLA?

**Comment by ilyavolodin** [comment]
Yes, verified CLA. Good to merge?

**Comment by gyandeeps** [comment]
thanks @ilyavolodin for confirmation .

**Comment by dgreensp** [comment]
Woot!!  Thanks guys!

**Comment by ffxsam** [comment]
@dgreensp You rock!

**Comment by gyandeeps** [comment]
Thanks for the PR. :+1:

**Pull request merged**
