### PR TITLE
Fix: Remove default parser from CLIEngine options (fixes #6182)

### LINKED ISSUE #6182: eslint 2.10.1 - Parsing error: Unexpected token
**What version of ESLint are you using?**
2.10.1

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**
```
module.exports = {
    "extends": "airbnb",
    "parser": "babel-eslint",
}
```

**What did you do? Please include the actual source code causing the issue.**

I have a sample demonstrating the issue at:
https://github.com/michael-wolfenden/eslint-2-10-1-issue

but running eslint via webpack with:

```
export class Counter {
  static initialCount = 0;
}
```

generates the error:

```
C:\Dev\eslint-issue\Counter.js
  2:23  error  Parsing error: Unexpected token =
```

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
```
C:\Dev\eslint-issue\Counter.js
  2:23  error  Parsing error: Unexpected token =
```

## Addition information

The issue first occurred with `2.10.0` so at first I assumed it was the same issue as #6158 , however upgrading to `2.10.1` didn't fix the issue. It appears as though the eslint babel parser isn't kicking in.

Another thing to note is that the issue only occurs when running eslint via webpack.

### PR DESCRIPTION
**Pull request by alberto**
Not sure how to add tests for this, submitting because it's probably breaking badly for a lot of people.

I think it won't break anything if no parser is specified, since it is set by `lib/eslint.js`, but please review @eslint/eslint-team

### CODE REVIEW

**Comment by ilyavolodin** [comment]
This would fix the issue for people trying to use `babel-eslint` through gulp/grunt, but I'm not sure it will not break people who want to use Espree through gulp/grunt.

**Comment by alberto** [comment]
@ilyavolodin fwiw I tried with the repo supplied in the issue, removing the parser from config and it worked fine

**Comment by nzakas** [comment]
Before doing this, do we know why there's a problem? Presumably, 2.9.0 worked fine with this in place, and we added this default for a reason, so I don't think it's a good idea to just remove it (especially without tests).

My hunch is that it's the extra `|| !this.parser` here that is the actual problem: https://github.com/eslint/eslint/pull/6160/files#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9R260

If not, then I think the better course of action is to revert https://github.com/eslint/eslint/pull/6160 and try to re-solve https://github.com/eslint/eslint/issues/6158

**Comment by alberto** [comment]
I think it was caused by #6108 and #6160 fixed it in the command line but not in the api

**Comment by nzakas** [comment]
@alberto can you explain more? I'm not sure I understand what you mean by fixing on the CLI but not the API.

**Comment by alberto** [comment]
Sorry, I was on my cellphone before. I just wanted to point out that if you intended to revert #6160 to release a non-broken version quickly, you should probably revert #6108 too.

Let me try to explain my understanding of the situation:
#6108 introduced some reordering in the merging of options that caused an issue to people in 2.10.0 using other parsers either when running from the cli (running eslint directly) or from the Node API. #6160 fixes it when running eslint from the command-line, by removing the default parser and not overriding it if it was not explictly passed. But the default parser is still set when run from the node API and takes precedence over the config, as if it was passed explicitly. This PR tries to fix that.

**Comment by nzakas** [comment]
I don't want to rush a new version out -- my point is that we added the default parser in there for a reason so I don't think removing it is a good idea. There's no reason why all the other defaults would work okay except for `parser`, so we should figure out the difference and fix that.

**Comment by nzakas** [comment]
I'm going to take a look at #6182 now that I'm back at a computer

**Comment by nzakas** [comment]
Okay, I just updated with tests and setting `parser` to an empty string. (Pushed to same branch as the original.)

**Comment by nzakas** [comment]
Merging so I can do a patch release with this change.

**Comment by nzakas** [comment]
@alberto I'll leave the branch for you to delete when ready since you created it.

**Comment by alberto** [comment]
Nice! Thanks for finishing this (and for the credit).

**Pull request merged**
