### PR TITLE
Update: Run appveyor tests against travis node versions

### PR DESCRIPTION
**Pull request by amilajack**
This updates the appveyor tests to run tests against the same versions that travis runs on.

### CODE REVIEW

**Comment by platinumazure** [comment]
Hi @amilajack, thanks for contributing! Just FYI, I believe the reason we had constrained AppVeyor to run only against latest Node is because AppVeyor only ran one build at a time, and so it would become a major bottleneck in the PR validation process. So unless that has changed, this PR might be closed.

**Comment by amilajack** [comment]
I don't think that has changed. Closing.

**Comment by platinumazure** [comment]
@eslint/tsc. Given that we now have a 48 hour waiting period for most PRs, is the slowness of AppVeyor now tolerable enough, and the value of multiple AppVeyor builds high enough, that this is worth revisiting? (My assumption is no but I think it's fair to ask given our policy changes.)

**Comment by ilyavolodin** [comment]
AppVeyor build is there mostly to verify that our code works correctly on Windows. I don't think adding more builds would help a lot.

**Pull request closed without merging**
