### PR TITLE
Upgrade: Consuming handlebars@^4.0.0 (fixes #3632)

### LINKED ISSUE #3632: Update handlebars dep
Looks like the current version of Handlebars includes a potentially sketchy version of [**uglify-js**](https://nodesecurity.io/advisories/uglifyjs_incorrectly_handles_non-boolean_comparisons) (which was fixed in **handlebars@4**).

```sh
$ nsp shrinkwrap

Name       Installed   Patched   Vulnerable Dependency
uglify-js    2.3.6    >= 2.4.24  eslint > handlebars
```

Looks like a few more potentially questionable modules if we include the devDependencies. Not sure how many of those can easily be fixed since they're pretty nested dependencies, so we'd have to see if all the upstream modules are patched and re-published:
```sh
$ npm shrinkwrap --dev
wrote npm-shrinkwrap.json

$ nsp shrinkwrap
Name       Installed   Patched   Vulnerable Dependency
uglify-js    2.2.5    >= 2.4.24  eslint > browserify > umd > ruglify
uglify-js    2.3.6    >= 2.4.24  eslint > handlebars
uglify-js    2.3.6    >= 2.4.24  eslint > istanbul > handlebars
uglify-js    2.2.5    >= 2.4.24  eslint > mocha > jade > transformers
semver       1.1.4     >=4.3.2   eslint > phantomjs > npmconf
qs           0.6.6      >= 1.x   eslint > phantomjs > request
qs           0.6.6      >= 1.x   eslint > phantomjs > request
```

---

And for giggles, here's the current list of outdated modules:
```sh
$ npm outdated --depth 0

Package                         Current                    Wanted                       Latest  Location
beefy                             1.1.0                     1.1.0                        2.1.5  beefy
brfs                              0.0.9                     0.0.9                        1.4.1  brfs
browserify                        8.1.3                     8.1.3                       11.0.1  browserify
chai                             1.10.0                    1.10.0                        3.2.0  chai
coveralls                        2.11.2                    2.11.2                       2.11.4  coveralls
esprima-fb     10001.1.0-dev-harmony-fb  10001.1.0-dev-harmony-fb  15001.1001.0-dev-harmony-fb  esprima-fb
handlebars                        3.0.3                     3.0.3                        4.0.0  handlebars
markdownlint                      0.0.6                     0.0.6                        0.0.7  markdownlint
npm-license                       0.2.3                     0.2.3                        0.3.1  npm-license
object-assign                     2.1.1                     2.1.1                        4.0.1  object-assign
optionator                        0.5.0                     0.5.0                        0.6.0  optionator
phantomjs                      1.9.7-15                  1.9.7-15                       1.9.18  phantomjs
semver                            4.3.6                     4.3.6                        5.0.1  semver
shelljs                           0.3.0                     0.3.0                        0.5.3  shelljs
sinon                            1.14.1                    1.14.1                       1.16.1  sinon
user-home                         1.1.1                     1.1.1                        2.0.0  user-home
```

### PR DESCRIPTION
**Pull request by platinumazure**
Just for kicks, I updated the handlebars dependency to `^4.0.0` (which pulls in 4.0.1 as of when I wrote this). `npm test` passed, not sure if there is anything I can do to verify more deeply. If there is something I can/should do for extra verification, please let me know.

Fixes #3632. (Sort of-- it only fixes the original scope of the issue. Maybe a different issue could be created for the devDependencies?)

### CODE REVIEW

**Comment by gyandeeps** [comment]
What about devDependencies?
I think this is what is expected from this PR. LGTM.

**Comment by nzakas** [comment]
Dev dependencies aren't all that important.

**Comment by nzakas** [comment]
@platinumazure can you change your commit message to begin with "Upgrade:"?

**Comment by platinumazure** [comment]
@nzakas Sorry, I missed that one in the list. I will do so when I get home from work. Thanks!

**Comment by platinumazure** [comment]
@nzakas Fixed and done, let me know if you see any other issues.

**Comment by SimenB** [comment]
I'm curious, why is Handlebars a dependency for a CLI tool? Not really a problem (We use handlebars in our app, so it's just deduped away), but it seems unnecessary, doesn't it?

**Comment by platinumazure** [comment]
@SimenB See #3632 for more information, but long story short it's a very indirect dependency.

**Pull request merged**
