### PR TITLE
Build: Remove commit check from appveyor (fixes #6292)

### LINKED ISSUE #6292: AppVeyor build is still running `npm run check-commit`
Hopefully pretty self-explanatory. Travis is no longer running the commit check, but AppVeyor's configuration was not modified and so it continues to run the commit check.

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by IanVS** [comment]
:+1:

**Comment by IanVS** [comment]
Actually, shouldn't it also be removed from package.json and makefile.js? It's essentially dead code at this point, isn't it?

**Comment by alberto** [comment]
Mmm, now that you mention it... @nzakas did you actually intend to remove all git checks or just the number of commits in #6263? `check-commit` also validates the commit message format and length.

**Comment by nzakas** [comment]
The bot already does the other checks, so we don't need Travis/Appveyor doing it as well. 

I left the task in Makefile.js because I was unsure if developers were using it locally (it is mentioned in the pull request docs).

**Comment by platinumazure** [comment]
@nzakas I sometimes use it locally. That said, I think we can leave it in Makefile.js without actually invoking it in `npm test` or in Travis/AppVeyor.

**Comment by alberto** [comment]
Ok, make sense. PR is good as is, then.

**Pull request merged**
