### PR TITLE
Docs: typo in "no-new" rule

### PR DESCRIPTION
**Pull request by AntoineSmagghe**
Typo

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

- [x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Corrects a typo

### CODE REVIEW

**Comment by chenxsan** [comment]
@AntoineSmagghe I think you need to update the commit message with `git commit --amend`, then force push it again.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks

**Comment by nzakas** [comment]
Thanks. Can you please sign our [CLA](https://cla.js.foundation/eslint/eslint?pullRequest=14791)?

**Review by nzakas — COMMENTED** [review]
The existing text is actually correct. It’s showing you can call the Thing constructor without “new”.

**Pull request closed without merging**
