### PR TITLE
Fix: use Reflect.ownKeys in prefer-reflect rule (fixes #7075)

### LINKED ISSUE #7075: Docs: Reflect.getOwnPropertyNames does not exist
In the [documentation](https://github.com/eslint/eslint/blob/master/docs/rules/prefer-reflect.md#reflectgetownpropertynames) and [source code](https://github.com/eslint/eslint/blob/master/docs/rules/prefer-reflect.md#reflectgetownpropertynames) for the `prefer-reflect` rule, the user is instructed to use `Reflect.getOwnPropertyNames` in place of `Object.getOwnPropertyNames`. However, `Reflect.getOwnPropertyNames` doesn't actually exist. The closest corresponding Reflect method is `Reflect.ownKeys`, although this isn't quite the same because it also includes Symbol properties.

### PR DESCRIPTION
**Pull request by dwhieb**
**What is the purpose of this pull request? (put an "X" next to item)**

```
[X] Documentation update
[ ] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:
```

*If the item you've check above has a template, please paste the template questions here and answer them.*

What rule do you want to change?
`prefer-reflect`

Does this change cause the rule to produce more or fewer warnings?
This rule produces one new warning.

How will the change be implemented? (New option, new default behavior, etc.)?
I changed the suggested alternative for `Object.getOwnPropertyNames` from `Reflect.getOwnPropertyNames` (which doesn't exist in the ES6 spec) to `Reflect.ownKeys`, which is the closest equivalent. It also adds `Reflect.ownKeys` as the suggested alternative for `Reflect.getOwnPropertySymbols`.

Please provide some example code that this change will affect:
```
Object.getOwnPropertyNames({})
Object.getOwnPropertySymbols({})
```

What does the rule currently do for this code?
Produces the warning `Avoid using Object.getOwnPropertyNames, instead use Reflect.getOwnPropertyNames.`

What will the rule do after it's changed?
It will produce two warnings:
* `Avoid using Object.getOwnPropertyNames, instead use Reflect.ownKeys.`
* `Avoid using Object.getOwnPropertySymbols, instead use Reflect.ownKeys.`

**Please check each item to ensure your pull request is ready:**

- [X] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- [X] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**
I replaced `Reflect.getOwnPropertyNames` with `Reflect.ownKeys` in both the code and documentation for `prefer-reflect`. I also added `Reflect.ownKeys` as the suggested alternative to `Object.getOwnPropertySymbols`.

**Is there anything you'd like reviewers to focus on?**
N/A

### CODE REVIEW

**Comment by ljharb** [comment]
Should this rule also then recommend `Reflect.ownKeys` over `Object.getOwnPropertySymbols`? I would think so, for symmetry with this PR's change.

**Comment by dwhieb** [comment]
Forgot to update tests - sorry. I'll reopen this once I'm done.

**Comment by dwhieb** [comment]
> Should this rule also then recommend Reflect.ownKeys over Object.getOwnPropertySymbols?

That makes sense to me. I'll include this change as well.

**Comment by dwhieb** [comment]
Should be all set. I signed the CLA but it's throwing an error because GitHub was using an anonymous email in my first commit. My other commits have the correct email however. I also wasn't able to change the commit summary to eslintbot's satisfaction, but I think it's correct.

I wrote new tests for the prefer-reflect rule and revised existing ones where needed. All tests are passing.

**Pull request closed without merging**
