### PR TITLE
Chore: Replace chalk with nanocolors

### PR DESCRIPTION
**Pull request by ai**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

- [ ] Documentation update
- [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
- [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [x] Other, please explain:

Dependency change without breaking changes

#### What changes did you make? (Give an overview)

I color output library from `chalk` to [Nano Colors](https://github.com/ai/nanocolors).

#### Is there anything you'd like reviewers to focus on?

Reasons to change color library:

- New one is better for end-users:
  - Nano Colors has no dependencies and use only **[16 kB](https://packagephobia.com/result?p=nanocolors)** in `node_modules`. `chalk` has [5 dependencies](https://npm.anvaka.com/#/view/2d/chalk) and takes **[101 kB](https://packagephobia.com/result?p=chalk)**.
  - Nano Colors is [faster](https://github.com/ai/nanocolors#benchmarks). It **7 times** faster for loading and **5 times** faster for method calls. Not so important for this small task, but nice to have.
- Backward compatible:
  - Detects color support in a same way as `chalk` does: it uses Node.js `tty` module, `TERM`, `NO_COLOR`, `FORCE_COLOR` env variables, `--color`/`--no-color` arguments.
  - Nano Colors supports **Node.js ≥ 6** ([CI](https://github.com/ai/nanocolors/blob/main/.github/workflows/test.yml#L41-L58)) and both ESM and CJS imports (even universal browsers/Node.js projects).
  - It is ready for Windows and CI.
- Can be trusted:
  - **[Stylelint](https://github.com/stylelint/stylelint/pull/5560), [SVGO](https://github.com/svg/svgo/pull/1586), [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware/pull/1049), [Browserslist](https://github.com/browserslist/browserslist/blob/main/package.json#L24), [PostCSS](https://github.com/postcss/postcss/blob/main/package.json#L70)** switched to Nano Colors too.
  - Nano Colors has around 1M downloads per day and 0 opened issues.
  - It will have a good support. My other projects from nano-series like very popular [Nano ID](https://github.com/ai/nanoid/) shows a minimal number of bugs and excellent response time.
- Other reasons:
  - Nano Colors has nice tree-shakable API: `import { red } from 'nanocolors'`.
  - Now `stylish` formatter test less relies on implementation.

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Dear ESLint maintainers, thank you for all your work. 

I strongly advise against migrating to nanocolors. Let me explain.

@ai, who is well-known in the JavaScript community for Autoprefixer, PostCSS, etc., shamelessly copied one of my most downloaded node packages ([Colorette](https://github.com/jorgebucaran/colorette), >20M/week) and rebranded it as nanocolors. 

A substantial amount of work and hours have gone into Colorette over the years, we've fixed numerous bugs and found creative ways to optimize performance, decrease package size, and more. nanocolors blatantly plagiarizes all this work. It's unethical and unprofessional.

Seeing him leverage his notability and following to promote and increase the adoption of nanocolors (https://github.com/babel/babel/pull/13783), which he just released a few days ago, is unethical and disgraceful. As an open-source maintainer myself I feel discouraged. 

This is not in the true spirit of open source.

**Review by jorgebucaran — CHANGES_REQUESTED** [review]
Dear ESLint maintainers, thank you for all your work. 

I strongly advise against migrating to nanocolors. Let me explain.

@ai, who is well-known in the JavaScript community for Autoprefixer, PostCSS, etc., shamelessly copied one of my most downloaded node packages ([Colorette](https://github.com/jorgebucaran/colorette), >20M/week) and rebranded it as nanocolors. 

A substantial amount of work and hours have gone into Colorette over the years, we've fixed numerous bugs and found creative ways to optimize performance, decrease package size, and more. nanocolors blatantly plagiarizes all this work. It's unethical and unprofessional.

Seeing him leverage his notability and following to promote and increase the adoption of nanocolors (https://github.com/babel/babel/pull/13783), which he just released a few days ago, is unethical and disgraceful. As an open-source maintainer myself I feel profoundly discouraged. 

This is not in the true spirit of open source.

**Comment by ai** [comment]
I answered to @jorgebucaran accusations in another PR https://github.com/babel/babel/pull/13783#issuecomment-927107377

**Review by g-plane — APPROVED** [review]

**Comment by aladdin-add** [comment]
I'm fine to keep using chalk - it's actively maintained, 101k -> 16k is not a very big win for node.js users. But let's see what's the team thinking.

**Comment by sindresorhus** [comment]
Relevant: https://github.com/babel/babel/pull/13783#issuecomment-927317201

**Pull request closed without merging**
