### PR TITLE
docs: fix: typo prefer-const.md

### PR DESCRIPTION
**Pull request by ArdRhena**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### CODE REVIEW

**Review by mdjermanovic — COMMENTED** [review]
I'm not sure if this was a typo, but with `i` the example indeed makes more sense. Can you sign the CLA so we could merge this change?

**Review by ArdRhena — COMMENTED** [review]
Bug fix

**Comment by ArdRhena** [comment]
> Bug fix

**Review by harish-sethuraman — APPROVED** [review]
LGTM, Thanks

**Comment by harish-sethuraman** [comment]
Can you rename the commit? 

To Fix: You can fix this problem by running `git commit --amend`, editing your commit message, and then running git push -f to update this pull request.

**Comment by snitin315** [comment]
I think that's fine, we can update the message while merging.

**Pull request merged**
