### PR TITLE
New: no-empty-catch rule flagging empty catch blocks in try statement (fixes #1841)

### LINKED ISSUE #1841: Option to have no-empty rule flag empty 'catch' blocks
Many times when just prototyping for the first time, folks will use this construct because they're not interested in the error:

```js
try {
... code that code could throw
} catch (e) {
}
```

But later, for production-ready code, you want to make sure that there is indeed error handling code in those 'catch' blocks.

The current rule doesn't flag 'catch' blocks. I'd like to propose a config option for the 'no-empty' rule that would flag them.

Maybe something like: `"no-empty": [2, {"includeCatchBlocks": true}]`or some such.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8624737-option-to-have-no-empty-rule-flag-empty-catch-blocks?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by doberkofler**

### CODE REVIEW

**Comment by nzakas** [comment]
Sorry, I thought we had agreed to make this an option of `no-empty` and allow people to specify which blocks are intentionally empty using a comment?

**Comment by doberkofler** [comment]
I do have misunderstood your comments but generally like the idea of having a separate rule with higher granularity better.

**Comment by nzakas** [comment]
I'm sorry, that's not what we agreed to.

**Comment by doberkofler** [comment]
I already agreed that I misunderstood your comments but could you please elaborate why you dislike the idea of separating this rule from the existing one ?

**Comment by nzakas** [comment]
Please refer back to the issue for the discussion.

**Pull request closed without merging**
