### PR TITLE
Docs: Update issue closing policy (fixes #6765)

### LINKED ISSUE #6765: Proposal: Issue commenting period
**Problem**

Our open issue list is growing faster than we're able to close issues. We used to try to keep open issues under 100, and then we passed 200, and now we're well on our way to 300. I don't think keeping such a long issue list is of benefit to anyone -- the older issues rarely, if ever, get resolved, and they never get any other type of attention. Most of the open issues are stuck in the "evaluating" stage and only sometimes do we ever fully evaluate the request and decide what to do.

**Proposal**

I'd like to propose a formal "commenting period" for all issues (maybe 14 days?). The idea is that someone on the team needs to support an issue within the commenting period in order for it to be considered. Any issues that are still labeled "evaluating" after 14 days, and haven't otherwise been committed to (for instance, we've committed to the JSCS tasks even though many are still "evaluating"), we will just automatically close.

Why I think this will work:

1. If no one is willing to step forward for an idea within two weeks, it's unlikely that it will happen because the issue ends up pushed down the issue list and ends up out-of-sight (and therefore, out-of-mind).
2. We can give people quicker feedback on their ideas by closing things that haven't gained interest, rather than leaving them in limbo wondering what's happening.
3. We all have too many issues to review, and while I can't speak to everyone else's experience, I tend to focus on the newer ones because they tend to trigger notifications.

In the end, the open issues would end up as a list of things that have a very good chance of being implemented rather than a backlog of issues that are mostly ignored.

### PR DESCRIPTION
**Pull request by nzakas**
**What issue does this pull request address?**

#6765

**What changes did you make? (Give an overview)**

Updated the maintainer guide to describe that unaccepted issues should be closed after 21 days.

**Is there anything you'd like reviewers to focus on?**

Wording is understandable.

### CODE REVIEW

**Comment by platinumazure** [comment]
LGTM.

**Comment by gyandeeps** [comment]
LGTM, waiting for others to review.

**Comment by alberto** [comment]
LGTM

**Comment by kaicataldo** [comment]
LGTM

**Pull request merged**
