### PR TITLE
Fix: Do not strip underscores in camelcase allow (fixes #11000)

### LINKED ISSUE #11000: camelcase: new allow option strips underscores before checking name
**Tell us about your environment**

* **ESLint Version:** 3.7.0
* **Node Version:** 8
* **npm Version:** 6

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
        "camelcase": [
            "error",
            {
                "properties": "always",
                "allow": ["webpack_public_path", "UNSAFE_componentWillMount", "UNSAFE_componentWillRecieveProps", "UNSAFE_componentWillUpdate"]
            }
        ],
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
__webpack_public_path__ = config.publicPath;
```

**What did you expect to happen?**

No Errors

**What actually happened? Please include the actual, raw output from ESLint.**

An error occurred.

Its quite clear from the code what went wrong:

```
                /*
                 * Leading and trailing underscores are commonly used to flag
                 * private/protected identifiers, strip them
                 */
                const name = node.name.replace(/^_+|_+$/g, ""),
                    effectiveParent = (node.parent.type === "MemberExpression") ? node.parent.parent : node.parent;

                // First, we ignore the node if it match the ignore list
                if (isAllowed(name)) {
                    return;
                }
```

It strips `_` only when there is more than one at the beginning or end. This is quite counter intuitive that I need to also strip them for the allow option.

### PR DESCRIPTION
**Pull request by lukeapage**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

refactor when the name is stripped so it doesn't affect the allow option

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by lukeapage** [comment]
@platinumazure please can you re review now I added a test?

**Comment by lukeapage** [comment]
Any idea how I can get a second review?

**Comment by platinumazure** [comment]
@lukeapage Hope and pray, I guess? Just kidding.

I'll ask for another review in our team chat. Thank you for following up!

**Comment by platinumazure** [comment]
@lukeapage Merged, thanks for contributing! (And I do apologize for the long delay.)

**Pull request merged**
