### PR TITLE
Upgrade: file-entry-cache@6.0.0

### PR DESCRIPTION
**Pull request by realityking**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[X] Other, please explain: upgrading `file-entry-cache` to version 6. This drops the indirect dependency on `write`. See royriojas/flat-cache#49

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Thanks for the PR!

Is required Node version the only breaking change in `file-entry-cache@6.0.0`?

**Comment by realityking** [comment]
Yes it is. And it was explicitly aligned to that of eslint.

**Review by btmills — APPROVED** [review]
LGTM. Thanks for going out of your way to align the supported versions!

Marking as "accepted" after mdjermanovic and nzakas mentioned this as good to go in today's release discussion.

**Comment by realityking** [comment]
The thanks for aligning with eslint version should go to @royriojas who made it happen :)

**Pull request merged**
