### PR TITLE
Fix: no-extra-boolean-cast invalid autofix for Boolean() without args

### PR DESCRIPTION
**Pull request by mdjermanovic**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix

**Tell us about your environment**

* **ESLint Version:** 6.1.0
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 2015,
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
/*eslint no-extra-boolean-cast: "error"*/

// Bug #1

var foo = Boolean() ? bar() : baz();

if (Boolean()) {
    foo();
}

while (Boolean()) {
  foo();
}

// Bug #2

var foo = typeof!Boolean();
```

[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tZXh0cmEtYm9vbGVhbi1jYXN0OiBcImVycm9yXCIqL1xuXG4vLyBCdWcgIzFcblxudmFyIGZvbyA9IEJvb2xlYW4oKSA/IGJhcigpIDogYmF6KCk7XG5cbmlmIChCb29sZWFuKCkpIHtcbiAgICBmb28oKTtcbn1cblxud2hpbGUgKEJvb2xlYW4oKSkge1xuICBmb28oKTtcbn1cblxuLy8gQnVnICMyXG5cbnZhciBmb28gPSB0eXBlb2YhQm9vbGVhbigpOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

**What did you expect to happen?**

Not to change behavior and/or remove the code.

**What actually happened? Please include the actual, raw output from ESLint.**

```js
/*eslint no-extra-boolean-cast: "error"*/

// Bug #1

var foo = true;

true

true

// Bug #2

var foo = typeoftrue;
```

**What changes did you make? (Give an overview)**

Fixed bugs:

* Bug#1 - code was assuming it's always `!Boolean()` and the fix was replacing `parent` with `true`.
* Bug#2 - didn't check can the tokens be adjacent.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by kaicataldo** [comment]
This change makes sense to me. I know that this is the current behavior, but the fixer changing

```js
if (Boolean()) {
    foo();
}

while (Boolean()) {
  foo();
}
```
to 
```js
true;

true;
```
feels like the autofixer overreaching to me. Now that we're fixing 
```js
var foo = Boolean() ? bar() : baz();
```
to
```js
var foo = false ? bar() : baz();
```
, I wonder if we should be fixing the first example above to

```js
if (false) {
    foo();
}

while (false) {
  foo();
}
```

as well? Additionally, seems like it should fix the following:

```js
if (!Boolean()) {
    foo();
}

while (!Boolean()) {
  foo();
}
```
to
```js
if (true) {
    foo();
}

while (true) {
  foo();
}
```
I'm curious what the rest of the team has to say about this - there might be some historical context around this that I'm not aware of.

**Comment by mdjermanovic** [comment]
> This change makes sense to me. I know that this is the current behavior, but the fixer changing
> 
> ```js
> if (Boolean()) {
>     foo();
> }
> 
> while (Boolean()) {
>     foo();
> }
> ```
> 
> to
> 
> ```js
> true;
> 
> true;
> ```
> 
> feels like the autofixer overreaching to me. 

I think this is a bug from #7977. It was assumed that this rule warns on `Boolean()` only when it's in `!`,
but it can appear in other 'boolean contexts'.

While these two don't change behavior (just delete a lot of unreachable code, which I guess is also not okay), the first example does:

```js
var foo = Boolean() ? bar() : baz();
```
 
to
 
```js
var foo = true;
```

This is certainly a bug, `foo = baz()` is changed to `foo = true`.

> Now that we're fixing
> ```js
> var foo = Boolean() ? bar() : baz();
> ```
> 
> to
> 
> ```js
> var foo = false ? bar() : baz();
> ```
> 
> , I wonder if we should be fixing the first example above to
> 
> ```js
> if (false) {
>     foo();
> }
> 
> while (false) {
>     foo();
> }
> ```
> 
> as well? 

It's working exactly like that with this fix:

```js
{
    code: "if (Boolean()) {}",
    output: "if (false) {}",
    errors: [{
        messageId: "unexpectedCall",
        type: "CallExpression"
    }]
},
```

> Additionally, seems like it should fix the following:
> 
> ```js
> if (!Boolean()) {
>     foo();
> }
> 
> while (!Boolean()) {
>     foo();
> }
> ```
> 
> to
> 
> ```js
> if (true) {
>     foo();
> }
> 
> while (true) {
>     foo();
> }
> ```

It was already working like this, and this shouldn't be changed by this fix.  But to be sure, I'll add these test cases.

**Comment by mdjermanovic** [comment]
Added 3 test cases and modified 1 to match the example, and everything works as you described :)

**Comment by mdjermanovic** [comment]
Can't verify in the PR version at the moment, but I'm pretty sure that this comment will be removed, as it is within the node which is supposed to be replaced.

It was already working like that ([Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tZXh0cmEtYm9vbGVhbi1jYXN0OiBcImVycm9yXCIqL1xudm9pZCAhIC8qIENvbW1lbnQgKi8gQm9vbGVhbigpXG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)). I'll fix that in this PR, autofix shouldn't delete user's comments.

I've already noticed that many rules are deleting comments (which should never happen I guess) and was thinking about an additional method in the `FixTracker` which would set a flag to check for comments within the range before the fix. I'll open an issue with that idea if it makes sense.

**Comment by platinumazure** [comment]
> I've already noticed that many rules are deleting comments (which should never happen I guess) and was thinking about an additional method in the FixTracker which would set a flag to check for comments within the range before the fix. I'll open an issue with that idea if it makes sense.

That sounds like a great idea!

**Comment by mdjermanovic** [comment]
Comments should be safe now in these and other autofix cases in this rule, please check is it ok.

**Pull request merged**
