### PR TITLE
New: the `no-class-assign` rule (fixes #2718)

### LINKED ISSUE #2718: Rule Proposal: no-class-assign
This rule is similar to [`no-func-assign`](http://eslint.org/docs/rules/no-func-assign).

The following patterns are considered warnings:

```js
class A { }
A = 0;
```

```js
class A {
  b() { A = 0; }
}
```

```js
let A = class A {
  b() { A = 0; }
};
```

The following patterns are not considered warnings:

```js
let A = class A { };
A = 0;
```

```js
let A = class {
  b() { A = 0; }
};
```

```js
class A {
  b() { let A = 0; } // shadowing
};
```

I'm happy to work if it was accepted.

### PR DESCRIPTION
**Pull request by mysticatea**
The implementation of this rule is almost same as #2732 :)

### CODE REVIEW

**Comment by nzakas** [comment]
Can you rebase on top of master?

**Comment by mysticatea** [comment]
I rebased.

**Comment by ilyavolodin** [comment]
Sorry one more rebase required (I just merged your other PR, that caused this to get out of sync).

**Comment by mysticatea** [comment]
Yeah, I rebased again.

**Pull request merged**
