### PR TITLE
Docs: Fix incorrect `api.verify` JSDoc for `config` param

### PR DESCRIPTION
**Pull request by BYK**
Refs #5104 (specifically https://github.com/eslint/eslint/issues/5104#issuecomment-184236204)

### CODE REVIEW

**Comment by gyandeeps** [comment]
@jmm is this what you expected?

**Comment by BYK** [comment]
@gyandeeps - stop the press, gonna update one more thing.

**Comment by gyandeeps** [comment]
:smiley_cat:

**Comment by BYK** [comment]
@gyandeeps @jmm - updated

**Comment by jmm** [comment]
@gyandeeps Yeah, pretty much. Personally I would've left off the "to configure everything" and just left it at "An ESLintConfig instance", or "See the ESLintConfig type definition" like I suggested, but the main thing is that it no longer says it's the rule configuration.

**Pull request merged**
