### PR TITLE
correct eol-last desire value documentation

### PR DESCRIPTION
**Pull request by chaintng**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Please check each item to ensure your pull request is ready:**

- [X] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [X] I've included tests for my change
- [X] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**
Correct desire eol-last value after this pull request https://github.com/eslint/eslint/pull/6952

**Is there anything you'd like reviewers to focus on?**
nope :)

### CODE REVIEW

**Comment by chaintan17** [comment]
setting just `"always"` alone break the API.
please see this issue https://github.com/airbnb/javascript/issues/1088#issuecomment-249403495

I think we need to make backward compatability also because it's minor release.

What do you think @kdex ?

**Comment by kdex** [comment]
@chaintng Hm, I've failed to reproduce this on ESLint 3.5.0 and 3.6.0 with the following file:
```js
/* eslint eol-last: ["error"] */\n
var a = 2;
```
The output is as expected:
```
╰─$ ./bin/eslint.js check.js

/home/kdex/dev/eslint/check.js
  2:1   error  Use the global form of 'use strict'            strict
  2:1   error  Unexpected var, use let or const instead       no-var
  2:5   error  'a' is defined but never used                  no-unused-vars
  2:11  error  Newline required at end of file but not found  eol-last

✖ 4 problems (4 errors, 0 warnings)
```

If you have a consistent way of reproducing this error, could you please— in addition to this PR—open up an issue about it?

**Comment by chaintng** [comment]
Ah, yes. i was misunderstanding.
But why Travis throw failed test 😕 

i try `npm test` on `master` branch it also failed too 😕

**Comment by kdex** [comment]
Travis indeed [failed](https://travis-ci.org/eslint/eslint) for some node versions. The build and tests for Node 4.x were successful. Node 5.x and 6.x failed with:
```
ESLint couldn't find the plugin "eslint-plugin-node".
```
which seems like a problem on our end; don't worry about it. It has nothing to do with `eol-last`.

For more information on the failure, see #7239.

**Pull request merged**
