### PR TITLE
Chore: update eslint-config-eslint's required node version

### PR DESCRIPTION
**Pull request by aladdin-add**
it is a breaking change in eslint-config-eslint; tagged `Chore` to avoid eslint's major release.

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Other, please explain:

#### What changes did you make? (Give an overview)
as the title.

#### Is there anything you'd like reviewers to focus on?

atm, the commit format(and release tool) did not consider `eslint-config-eslint` -- there is a room to improve. :)

### CODE REVIEW

**Comment by kaicataldo** [comment]
> atm, the commit format(and release tool) did not consider eslint-config-eslint -- there is a room to improve. :)

Can you clarify what you mean by this?

**Comment by aladdin-add** [comment]
to `eslint-config-eslint`, the tag should be `breaking`. But doing so will make eslint release a major version.

**Comment by nzakas** [comment]
I think we also need to manually update the `eslint-config-eslint` package version with this change?

**Comment by kaicataldo** [comment]
I had to figure out how this worked, too. It looks like we have it set up to select the semver release type when kicking off the release (you can see the bot updating the version [here](https://github.com/eslint/eslint/commit/827259ea009f98a0fdf3f7ebf1bfb6cd661ce28d#diff-9973abe2a0f4368f633265d64eba2ead)), so this should be fine as-is!

**Comment by nzakas** [comment]
Okay cool, then I'll merge this.

**Pull request merged**
