### PR TITLE
Upgrade: `js-yaml` to v4

### PR DESCRIPTION
**Pull request by bmish**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[X] Other, please explain:

#### What changes did you make? (Give an overview)

Updates dependency.

https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md#400---2021-01-03

Also allow Python licenses ([OSI](opensource.org/licenses/alphabetical) approved) for transitive dependency argparse.

#### Is there anything you'd like reviewers to focus on?

No.

### CODE REVIEW

**Comment by bmish** [comment]
It looks like the licensing check failed:

```
Validating licenses
Python-2.0 license for argparse@2.0.1 is impermissible.
```

**Comment by nzakas** [comment]
Let me ask the OpenJS folks

**Review by nzakas — APPROVED** [review]
I believe this is fine.

**Review by snitin315 — APPROVED** [review]
LGTM

**Pull request merged**
