### PR TITLE
Docs: Use GitHub Multiple PR/Issue templates

### PR DESCRIPTION
**Pull request by kaicataldo**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[X] Other, please explain:

This change utilizes GitHub's new [multiple issue and pull request templates feature](https://github.com/blog/2495-multiple-issue-and-pull-request-templates) to make it so that users don't have to copy and paste the the template questions manually when they're filing a new issue.

**What changes did you make? (Give an overview)**
Added more issues templates for the various types of issues we see reported.

**Is there anything you'd like reviewers to focus on?**
Thoughts on this change? 

Also, I think this would be helpful for PRs as well, though I'm not sure how we would do that. Any ideas?

Wasn't entirely sure what labels to put on this, so please feel free to update if you deem it necessary!

### CODE REVIEW

**Comment by platinumazure** [comment]
Question: Should we consolidate/move items in the templates folder into .github/ISSUE_TEMPLATE and update the website's issue guides to point directly there? I'm not sure if there's any reason to keep both directories but let me know if I'm missing something.

**Comment by kaicataldo** [comment]
The only issue with that is that we currently reference those templates in the PR template. Ideally, I'd like to do the same thing for PRs (linking to various PR templates) but I wasn't sure how to link to that URL, since it seems like it would be different for each PR. But maybe I'm wrong about that?

If we can figure out how to do that, we can definitely remove the templates in the `templates` directory, which would be great!

**Comment by platinumazure** [comment]
> but I wasn't sure how to link to that URL, since it seems like it would be different for each PR

Not sure I understand this part? How would it be different for new PRs?

**Comment by kaicataldo** [comment]
> Not sure I understand this part? How would it be different for new PRs?

Please correct me if I'm wrong, but I believe PR urls are unique per PR and look like: `https://github.com/eslint/eslint/compare/master...my-branch`. Is there an easy way to append `?template=some-template.md` to these unique URLs?

**Comment by platinumazure** [comment]
> Please correct me if I'm wrong, but I believe PR urls are unique per PR and look like: `https://github.com/eslint/eslint/compare/master...my-branch`. Is there an easy way to append `?template=some-template.md` to these unique URLs?

Good call, you're right-- if someone creates a pull request from a branch page or using the "recently pushed branches" div. However, there is a "New Pull Request" button on the PR list which links to (e.g.) https://github.com/eslint/eslint/compare, which could easily have a template on it. That page lets you pick the base and head branch; however, I admit it might not be an intuitive interface (and might not work for users' forks at all). So I think we would need to dig a bit more if we wanted to implement this for PRs as well.

**Comment by not-an-aardvark** [comment]
Personally, I almost never use the https://github.com/eslint/eslint/compare page to create a PR -- I look for the yellow bar on the front page of the repo that appears after I push a branch.

**Comment by kaicataldo** [comment]
How do we feel about merging this now and looking into using multiple PR templates in the future?

**Pull request merged**
