### PR TITLE
Fix: Update the message to include number of lines (fixes #4342)

### LINKED ISSUE #4342: Error message for no-multiple-empty-lines incorrect in multiple cases
**What version are you using?**
1.8.0

**What did you do?**
Added the following rule and ran eslint
```
"no-multiple-empty-lines": [2, { "max": 3, "maxEOF": 1 }],
```

**What happened?**
The error message returned by the rules says `Multiple blank lines not allowed.` when in fact multiple lines are allowed

**What did you expect to happen?**

The message was incorrect so it took other engineers a while to realize what the issue was - they thought it was a bug in eslint initially.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28012493-error-message-for-no-multiple-empty-lines-incorrect-in-multiple-cases?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by briandela**
The message returned was a bit confusing as it says "Multiple blank lines not allowed." even when multiple blank lines are allowed. Minor update to the message to include the number of blank lines allowed.

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks! Can you also update the tests?

**Comment by IanVS** [comment]
Travis is failing because your commit summary uses "FIX" at the beginning, instead of "Fix".  You should be able to change it with `git commit --amend`, and then `git push -f`

**Comment by IanVS** [comment]
Ah hah, there's a typo in the test for the rule, which is why they're passing.  [expectedError](https://github.com/eslint/eslint/blob/13fd818ae8d065a3a2ee7a54a47105bf8f066454/tests/lib/rules/no-multiple-empty-lines.js#L21) & [expectedErrorEOF](https://github.com/eslint/eslint/blob/13fd818ae8d065a3a2ee7a54a47105bf8f066454/tests/lib/rules/no-multiple-empty-lines.js#L25) misspell `message` as `messsage` (three `s`'s).

**Comment by briandela** [comment]
@IanVS Any pointers on how to test with messages which vary based on the rule input?

**Comment by briandela** [comment]
Scratch that - please ignore my question - pretty obvious actually once I read that the messages was spelled incorrect.

Updating now.

**Comment by briandela** [comment]
@IanVS @nzakas I've fixed the tests so they are taken into account and also updated so the test looks for the correct message based on the value of `max` or `maxEOF`.

**Comment by IanVS** [comment]
:+1: @briandela. Thanks.

**Pull request merged**
