### PR TITLE
Fix: Replace `assert.deepEqual` by `lodash.isEqual` (fixes #6111)

### LINKED ISSUE #6111: Test failing in node 6.1
Mocha is timing out on travis on node@6.1, which is causing all builds to fail.

### PR DESCRIPTION
**Pull request by alberto**
~~Pushing this as a temporary fix for our build while we find the root issue.~~

### CODE REVIEW

**Comment by kaicataldo** [comment]
Should we maybe leave a comment noting that it's a temporary fix?

**Comment by alberto** [comment]
Pushed another fix

**Comment by mysticatea** [comment]
:+1:

**Comment by kaicataldo** [comment]
Lgtm

**Comment by nzakas** [comment]
Some feedback:

1. This should be tagged as "fix" rather than "build" because it affects much more than the build.
3. `assert.ok` will not show a diff, so we're removing useful information from the test output.

If this is just temporary, I'd prefer to wait and just mark Node.js 6 as being okay to fail in Travis for now (https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail).

**Comment by mysticatea** [comment]
Might `assert.equal(JSON.stringify(beforeAST, null, 2), JSON.stringify(afterAST, null, 2))` work? 
Mocha would show diff lines for string comparision.

**Comment by alberto** [comment]
@nzakas don't think marking the build as non breaking is a good solution, since we will just ignore any other failures. I would rather do what @mysticatea proposed or increase the tests timeout so it doesn't break.

**Comment by alberto** [comment]
Another alternative would be to only use assert when the ASTs differ:

```
if (!lodash.isEqual(beforeAST, afterAST)) {
    assert.deepEqual(beforeAST, afterAST, "Rule should not modify AST.");
}
```

**Comment by ilyavolodin** [comment]
This is a strange change, but as long as it fixes CI, LGTM.

**Comment by mysticatea** [comment]
I like https://github.com/eslint/eslint/pull/6112#issuecomment-218723102 idea.

**Comment by ilyavolodin** [comment]
@mysticatea That's what this PR implements. But now we do deep comparison twice in the case something changed. Not a huge deal, just strange.

**Comment by mysticatea** [comment]
Oh, I hadn't noticed it since @eslintbot doesn't exist close to the commit.
Yeah, I feel it's strange, too. But `assert.deepEqual` would not be executed in most cases, so I'm OK. :D

**Comment by alberto** [comment]
@ilyavolodin yeah, it was a bit faster than what @mysticatea proposed in my tests, and the output stays the same.

**Pull request merged**
