### PR TITLE
Fix: handle destructuring with defaults in camelcase rule (fixes #8511)

### LINKED ISSUE #8511: camelcase rule doesn't ignore default parameter assignment when disabled
**Tell us about your environment**

**ESLint Version:** 3.19.0
**Node Version:** 6.9.4
**npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?** Default

**Please show your full configuration:**

```
module.exports = {
    "extends": "standard",
    "plugins": [
        "standard",
        "promise"
    ],
    "parserOptions": {
      "ecmaVersion": 6
    },
    "env": {
      "node": true
    },
    "rules": {
      "semi": ["error", "always"],
      "camelcase": [2, {"properties": "never"}]
    }
};
```

**What did you do? Please include the actual source code causing the issue.**

Disabling the `camelcase` rule does not appear to respect ES6 default parameter assignment when used with object destructuring syntax.

Here's a simple example:

```
// example.js

function snakeCase ({
  param_1 = 'default value',
  param_2 = 'another default'
} = {}) {
  // do stuff
}

module.exports = snakeCase;

```

**What did you expect to happen?**

Eslint should not care that `param_1` and `param_2` are using snake case instead of camelCase as the rule is disabled

**What actually happened? Please include the actual, raw output from ESLint.**

```
error  Identifier 'param_1' is not in camel case                            camelcase
error  Identifier 'param_2' is not in camel case                            camelcase
```

### PR DESCRIPTION
**Pull request by vitorbal**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Fixes the bug reported in #8511. I changed the logic of the `camelcase` rule to properly handle destructuring with defaults.

**Is there anything you'd like reviewers to focus on?**
I think not!

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the PR!

It seems like the rule allows

```js
/* eslint camelcase: [error, { properties: never }] */

var { foo: bar_baz } = qux;
```

Is this intentional? The `bar_baz` variable is not a property key, so it seems like the `properties` option shouldn't apply here.

That behavior also occurs without this PR, but I bring it up because this PR also makes it so that the following is valid, when it arguably shouldn't be:

```js
var { foo: bar_baz = 1 } = quz;
```

**Comment by vitorbal** [comment]
Thanks for the quick feedback! Apologies on the delay.

@platinumazure: I don't think the rule checks the right-side of the default value assignment in the example you suggested if `properties` is set to `never`. 
I'm not sure if this is intentional or not. Default values outside of destructuring are also handled the same way:
```js

/* eslint camelcase: ["error", {properties: "never"}] */
const no_camelcased = 0;
function foo(value_1 = no_camelcased) {}

// ^ only reports the first occurrence of no_camelcased on line 1
```

**Comment by vitorbal** [comment]
Sorry all, I got caught up with work stuff. Just wanted to post an update since I haven't had much time for OSS the last few weeks.

@not-an-aardvark I agree with the destructuring rename issue you brought up. I've done some investigating and it looks like the code never took this into account, but I'm not sure if this was intentional or not.
I'm reworking the logic in the rule to take this into account now, and I think I'll have something ready by next weekend!

**Comment by kaicataldo** [comment]
@vitorbal Friendly ping - anything we can help with here?

**Comment by vitorbal** [comment]
@kaicataldo sorry, I've just been really busy with work stuff lately :(
I'm hoping to have a chance to pick up my slack on this during the weekend!

**Comment by vitorbal** [comment]
Super sorry, I've been quite busy at work and I won't have time to work on this for a while. Feel free to pick this up and finish it off if interested!

**Comment by erindepew** [comment]
I can pick this up :)

**Comment by ilyavolodin** [comment]
@erindepew Go for it! We appreciate any help!

**Comment by kaicataldo** [comment]
In regards to https://github.com/eslint/eslint/pull/8529#issuecomment-298194202 - could we land this with the fix for default params with destructuring and fix renaming destructured params in a separate PR?

**Comment by kaicataldo** [comment]
@platinumazure 
> I would expect my_default to be flagged in both locations as it's not a "property key".

I disagree on this one. The camelcase rule should only check when declaring/renamed destructing a variable, since that's the only time a user has control over the name.

```js
import { my_default } from 'foo'; // This should warn
const { my_default } = require('foo'); // This should warn
const my_default = 0; // This should warn
const { my_default } = foo; // This should warn
const { bar: my_default } = foo; // This should warn
function foo({ value_1: my_default }) {} // This should warn

function foo({ value_1 = my_default }) {} // This shouldn't warn, because it should be caught at the time of declaration
```

The above errors would be fixed by the following:
```js
import { my_default as myDefault } from 'foo';
const { my_default: myDefault } = require('foo');
const myDefault = 0;
const { my_default: myDefault } = foo;
const { bar: myDefault } = foo;
function foo({ value_1: myDefault }) {}
```

We can make a new issue for this to separate this discussion from the current PR - I'll try to get to it after lunch :)

**Comment by kaicataldo** [comment]
Friendly ping @platinumazure @not-an-aardvark

**Comment by kaicataldo** [comment]
Re: #9468 I didn't realize that this all would touch the same part of the code. Maybe it would be easier to combine these into one PR as was originally suggested? Otherwise, we can get this merged and @erindepew can make a new PR once it lands.

**Comment by kaicataldo** [comment]
PR author has updated https://github.com/eslint/eslint/pull/9468 to include the changes from this PR as well as a bug fix for the destructuring reassignment bug! Shall we close this in favor of that PR now?

**Comment by platinumazure** [comment]
I'm okay with closing this if vitorbal is. Thanks to both of you for contributing, we really appreciate it.

**Comment by vitorbal** [comment]
I’m okay with closing this. Thanks guys for pushing it further, apologies
again for going AWOL recently.

**Comment by kaicataldo** [comment]
@vitorbal No problem and no need to apologize! Thanks for your work on this. Closing in favor of #9468, which takes this PR and adds an additional bug fix.

**Pull request closed without merging**
