### PR TITLE
Breaking: fix comma-dangle schema (fixes #13739)

### LINKED ISSUE #13739: Fix comma-dangle schema
`comma-dangle` schema should be fixed to allow only 1 element (either string or object, not string + object) in the configuration array, since the rule reads only the first element and ignores the rest:

> This rule has a string option or an object option:
> ```js
> {
>     "comma-dangle": ["error", "never"],
>     // or
>     "comma-dangle": ["error", {
>         "arrays": "never",
>         "objects": "never",
>         "imports": "never",
>         "exports": "never",
>         "functions": "never"
>     }]
> }
> ```

Allowing multiple elements can be misleading, as in #13165. Users might expect that an additional object can be used to override the string option.

We already fixed this in #13166 but reverted the change in #13564 per the semver policy, so this is a task for the next major version.

### PR DESCRIPTION
**Pull request by JoakimoNilsson**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #13739 

#### What changes did you make? (Give an overview)

Added `additionalItems: false` in order to allow specifying only 1 option.

#### Is there anything you'd like reviewers to focus on?
Please see #13166 for discussions regarding semver handling on this (breaking) change. A revert was made on the accepted PR, so this fix is pending a new major release

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Hi @JoakimoNilsson, thanks for the PR!

I converted this to draft to avoid accidental merging, as it's a breaking change so we'll wait for the next major release.

**Comment by JoakimoNilsson** [comment]
Thank you @mdjermanovic! If there's anything I can do don't hesitate to ask!

**Comment by mdjermanovic** [comment]
@JoakimoNilsson the change looks good!

Could you please update the commit message to start with `Breaking:`?

It can be like the current PR title: `Breaking: fix comma-dangle schema (fixes #13739)`

Alternatively, we could change the commit message on merge.

**Comment by nzakas** [comment]
Let's just update on merge.

**Review by nzakas — APPROVED** [review]

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Review by snitin315 — APPROVED** [review]
LGTM

**Pull request merged**
