### PR TITLE
Chore: Remove `fixable` from multiline-ternary metadata (fixes #6683)

### LINKED ISSUE #6683: multiline-ternary has incorrect metadata
I forgot to remove the `fixable` key from `multiline-ternary`'s metadata when we decided to not autofix for the rule. This should be removed. Sorry for the oversight!

https://github.com/eslint/eslint/blob/master/lib/rules/multiline-ternary.js#L21

### PR DESCRIPTION
**Pull request by kaicataldo**
**What issue does this pull request address?**
I forgot to remove the fixable key from multiline-ternary's metadata when we decided to not autofix for the rule. This should be removed. Sorry for the oversight!

**What changes did you make? (Give an overview)**
Remove the key

**Is there anything you'd like reviewers to focus on?**
N/A

### CODE REVIEW

**Comment by kaicataldo** [comment]
Sorry to bug you, @kborchers. Any idea why the CLA is saying it's not accepted? I didn't change anything on my end, but the email it's checking against appears to be `Kai Cataldo <kaicataldo@users.noreply.github.com>`

**Comment by platinumazure** [comment]
@kaicataldo Did you make this commit from the GitHub online interface? If so, it will use the e-mail configured on your user profile (or, if you haven't configured one, the one with users.noreply.github.com in it).

**Comment by kaicataldo** [comment]
Ah, I did! Is there a way to fix it?

**Comment by ilyavolodin** [comment]
@kaicataldo You will have to clone it locally and change author, then resubmit (probably easier to just close this one and submit a new one from your regular local fork).

**Comment by kaicataldo** [comment]
Will do - sorry all for the confusion!

**Pull request closed without merging**
