### PR TITLE
Update: rename getter-return's option property

### LINKED ISSUE #8854: consistent-return and getter-return has a similar option property
# consistent-return and getter-return has a similar option property, but naming different.

## consistent-return option:

+ "treatUndefinedAsUnspecified": false (default) always either specify values or return undefined implicitly only.
+ "treatUndefinedAsUnspecified": true always either specify values or return undefined explicitly or implicitly.

## getter-return option:
+ "allowImplicit": false (default) disallows implicitly returning undefined with a return; statement.

it is confusing to users, better to be consistent.

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Changes an existing rule ([template]

**What changes did you make? (Give an overview)**
fixes #8854 

**Is there anything you'd like reviewers to focus on?**

default value to be true?

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
I'll champion this proposal.

**Comment by Aladdin-ADD** [comment]
hmm. seems the default value should be true?

**Comment by not-an-aardvark** [comment]
Wait, I don't think we should change the name to `treatUndefinedAsSpecified`. It seems like the whole point of this update is to be consistent with the `consistent-return` rule, so we should keep the same option name as `consistent-return`.

**Comment by Aladdin-ADD** [comment]
but in consistent-return, the default value is true, in getter-return, it should be true. can a default value be true?

**Comment by not-an-aardvark** [comment]
Based on the [docs](http://eslint.org/docs/rules/consistent-return#options), the default value is false in `consistent-return`.

**Comment by Aladdin-ADD** [comment]
sorry for error in speaking，in getter-return, it should be true.

**Comment by not-an-aardvark** [comment]
I've looked at this again, and I'm no longer sure it's worth changing the names to be consistent. In `getter-return`, the option means that `return;` should be *disallowed*, whereas in `consistent-return` the option means that `return;` should be considered equivalent to `return undefined`. Since they mean different things, maybe it's better for the option names to be different.

**Comment by Aladdin-ADD** [comment]
>  In getter-return, the option means that return; should be disallowed, whereas in consistent-return the option means that return; should be considered equivalent to return undefined.

in getter-return, the option being true means `return;` is allowed, that is same to consistent-return option being false. their option is just reverse.

**Comment by Aladdin-ADD** [comment]
treating `return;` as `return undefined;` allows using `return;`

so there is a little difference in represention, however it's doing the same thing.

**Comment by not-an-aardvark** [comment]
Ok, let's close it then. Sorry about the confusion!

**Pull request closed without merging**
