### PR TITLE
Update: Allow empty arrow body (fixes #4411)

### LINKED ISSUE #4411: False positive for `arrow-body-style` rule when used as a noop
```
~/dev
❯ eslint --version                                                                            
v1.9.0
                                                                                                                                               
~/dev
❯ echo 'stream.on('error', () => {});' | eslint --stdin --env=es6 --rule='arrow-body-style: [2, "as-needed"]'

<text>
  1:24  error  Unexpected empty block in arrow body  arrow-body-style

✖ 1 problem (1 error, 0 warnings)
```

Sometimes you have to pass a noop function. In this example the braces are required, but ESLint still complains, even though the setting is `as-needed`.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28214191-false-positive-for-arrow-body-style-rule-when-used-as-a-noop?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by mysticatea** [comment]
#4411 has a breaking label?

**Comment by nzakas** [comment]
Yeah, this one shouldn't have been merged as it's a breaking change.

**Comment by nzakas** [comment]
I'm going to revert the merge. Let's discuss back on #4411

**Comment by ilyavolodin** [comment]
Ahhh... Good point about breaking change. I didn't think of that. Sorry.

**Comment by ilyavolodin** [comment]
@alberto Could you resubmit this PR, so we could merge it into 2.0 once it's ready?

**Comment by alberto** [comment]
@ilyavolodin do you mean force-pushing it again? Should I rebase?

**Comment by ilyavolodin** [comment]
@alberto No, I mean I accidently merged this PR, and @nzakas reverted it, since it's a breaking change. Now this PR is closed, but we should reopen it, so we don't forget to merge it for 2.0. You should be able to create a new PR from the repository homepage (at the top right corner)

**Comment by alberto** [comment]
@ilyavolodin I can't just create a PR with the current branch, since it has already been merged:
> master is up to date with all commits from issue4411

**Comment by ilyavolodin** [comment]
Yes, I noticed that. Not sure why, since it was reverted right after the merge. Maybe you need to rebase it on top of current master first?

**Comment by alberto** [comment]
Reverting just creates a new commit, but the current one is already in master. I'm not sure rebasing is the right thing either for the same reason, so I'll reapply it again manually on top of master in a new branch.

**Pull request merged**
