### PR TITLE
Fix: Process file if direct path given to the file (fixes #3649)

### LINKED ISSUE #3649: Incorrectly warning about ignored files
After globs were added to the cli input in 5a599c70a98eaed0d43a8f28690921ef4ad0702d, my command to lint rule docs has broken:

```
DEBUG=eslint* node_modules/.bin/eslint --plugin markdown --no-eslintrc --config conf/rule-doc-config.json docs/rules/quote-props.md
  eslint:cli Running on files +0ms
  eslint:config Using command line config conf/rule-doc-config.json +3ms
  eslint:cli-engine Linting complete in: 3ms +10ms

/home/ian/Local_code/eslint/eslint/docs/rules/quote-props.md
  0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override

✖ 1 problem (0 errors, 1 warning)
```

Compare to my output if I revert to the commit prior to globs being added:

```
▶ git reset --hard 37bb3159f748463861ba9aadf704e76af3c2537d
HEAD is now at 37bb315 Merge pull request #3518 from ev0rtex/update-expression-rule-logic

▶ DEBUG=eslint* node_modules/.bin/eslint --plugin markdown --no-eslintrc --config conf/rule-doc-config.json docs/rules/quote-props.md
  eslint:cli Running on files +0ms
  eslint:config Using command line config conf/rule-doc-config.json +3ms
  eslint:cli-engine Processing docs/rules/quote-props.md +10ms
  eslint:cli-engine Linting docs/rules/quote-props.md +1ms
  eslint:config Constructing config for /home/ian/Local_code/eslint/eslint/docs/rules/quote-props.md +0ms
  eslint:config Not using .eslintrc or package.json files +0ms
  eslint:config Merging command line config file +1ms
  eslint:config Merging command line environment settings +0ms
  eslint:config Merging command line plugins +0ms
  eslint:cli-engine Load plugin markdown +4ms

docs/rules/quote-props.md
    7:20  error  Unexpected token ;
  130:6   error  Unexpected string

✖ 2 problems (2 errors, 0 warnings)
```

Something appears to have changed in how files are determined to be ignored.  Furthermore, if I follow the warning's advice and add `--no-ignore`, the warning is not shown, but the file is still not linted:

```
▶ DEBUG=eslint* node_modules/.bin/eslint --plugin markdown --no-ignore --no-eslintrc --config conf/rule-doc-config.json docs/rules/quote-props.md
  eslint:cli Running on files +0ms
  eslint:config Using command line config conf/rule-doc-config.json +2ms
  eslint:cli-engine Linting complete in: 2ms +9ms
```

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
@BYK Can you review please?

**Comment by IanVS** [comment]
:+1: This fixes the problem I was having in the issue:

```
Local_code/eslint/eslint  issue3649 ✗      
▶ DEBUG=eslint* node_modules/.bin/eslint --plugin markdown --no-eslintrc --config conf/rule-doc-config.json docs/rules/quote-props.md
  eslint:cli Running on files +0ms
  eslint:config Using command line config conf/rule-doc-config.json +2ms
  eslint:cli-engine Processing /home/ian/Local_code/eslint/eslint/docs/rules/quote-props.md +11ms
  eslint:cli-engine Linting /home/ian/Local_code/eslint/eslint/docs/rules/quote-props.md +0ms
  eslint:config Constructing config for /home/ian/Local_code/eslint/eslint/docs/rules/quote-props.md +1ms
  eslint:config Not using .eslintrc or package.json files +0ms
  eslint:config Merging command line config file +0ms
  eslint:config Merging command line environment settings +1ms
  eslint:config Merging command line plugins +0ms
  eslint:cli-engine Load plugin markdown +3ms
  eslint:cli-engine Linting complete in: 60ms +52ms

/home/ian/Local_code/eslint/eslint/docs/rules/quote-props.md
    7:20  error  Unexpected token ;
  130:6   error  Unexpected string

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by BYK** [comment]
I'm not sure if this is the best approach. I think we should check if a pattern is a file when pre-processing the patterns and then treat it specially at the stage.

Also, I'd say this was the correct behavior. Even if you pass the file specifically, if its extension is not supported, it should not be processed so fixing the error message to be more specific would be better IMO.

@eslint/eslint-team thoughts?

**Comment by BYK** [comment]
Oh, I missed https://github.com/eslint/eslint/issues/3649#issuecomment-137845412. Okay so if this is the behavior we want, I still think we should not rely on the pattern not having an extension and detect explicitly passed files and treat them accordingly.

**Comment by BYK** [comment]
I've submitted an alternative patch, #3666, demonstrating my approach. It is definitely more involved than @gyandeeps approach but I think that is the correct way forward.

That said since I was involved with the initial glob implementation too I think I'm a bit biased. So @eslint/eslint-team please be as objective as possible. I won't be offended if we go with @gyandeeps' patch :)

**Comment by nzakas** [comment]
Yeah, I think using a lack of extension isn't the best determination of whether something is a pattern or not.

**Comment by gyandeeps** [comment]
@BYK Feel free to close this PR if this is not the best approach.
Thanks

**Comment by BYK** [comment]
@gyandeeps I can't do that since I submitted an alternative. A third person should decide which is the better approach, objectively :)

**Comment by nzakas** [comment]
Closing in favor of #3666

**Pull request closed without merging**
