### PR TITLE
Update: Add exceptions option to camelcase.

### PR DESCRIPTION
**Pull request by coreyfarrell**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

please explain:
**What rule do you want to change?**
camelcase

**Does this change cause the rule to produce more or fewer warnings?**
It can cause fewer warnings to be produced if the new option is used.

**How will the change be implemented? (New option, new default behavior, etc.)?**
A new option "exceptions" can be provided to the camelcase rule.

**Please provide some example code that this change will affect:**

```js
const mysql = require('mysql');
const pool = mysql.createPool();

const account_id = 'value';
const message_cause = 'dbas like underscores';
pool.query('INSERT INTO account_log SET ?', {account_id, message_cause}, err => {
  if (err) {
    throw err;
  }
  pool.end();
});
```

**What does the rule currently do for this code?**
The camelcase rule must be disabled when dealing with outside code that requires use of underscored names.

**What will the rule do after it's changed?**
After the change the example above would be able to include the option `"exceptions": ["account_id", "message_cause"]` in the `camelcase` options object instead of disabling it entirely.

**What changes did you make? (Give an overview)**
Add support for "exceptions" to be provided in the camelcase options object, ignore any identifiers listed in the object.

**Is there anything you'd like reviewers to focus on?**
Nothing I can think of.

### CODE REVIEW

**Comment by j-f1** [comment]
For your example, you can use a regular object literal

```js
const mysql = require('mysql');
const pool = mysql.createPool();

const accountId = 'value';
const messageCause = 'dbas like underscores';
pool.query('INSERT INTO account_log SET ?', {account_id: accountId, message_cause: messageCause}, err => {
  if (err) {
    throw err;
  }
  pool.end();
});
```

which will avoid the issue altogether.

**Comment by coreyfarrell** [comment]
@j-f1 I just tried your code, it still produces errors when camelcase is enabled.

**Comment by BrianRosamilia** [comment]
Why can't this just be made to be more generic and have an option called `obj` or `params` (objparams?) where it won't check for camel case names in an object parameter?  Having to add an array of string exceptions seems kludgey 

To reiterate, this rule would be the exact same as `always` for the `camelcase` rule, but the last example 

```
var obj = {
    my_pref: 1
};
```

is allowed

https://eslint.org/docs/rules/camelcase#always

I actually came here to make a feature request for this and found this issue.  It seems much needed.

**Comment by j-f1** [comment]
That’s what the `properties: never` option does @BrianRosamilia.

**Comment by ilyavolodin** [comment]
As @j-f1 mentioned, this should pass with `properties: never` flag. Do we need to add another option that basically satisfies the example provided?

**Comment by coreyfarrell** [comment]
The point of my patch is to allow specific camel case symbols to be used anywhere.  If I'm dealing with a database which uses time_id I don't care where time_id is used, variables, symbols or parameters.  I don't want to allow all camel case property names, only the names from the database.

**Comment by platinumazure** [comment]
@coreyfarell Maybe you want to take a look at the `id-match` rule? That rule lets you define a regex representing a valid identifier. I think you could theoretically use a regex like `"^(?:[^_]+|time_id)$"` to get what you want here (of course, you may need to tweak).

**Comment by coreyfarrell** [comment]
In theory the id-match rule could work.  It looks difficult to use but I'm going to close this PR because it feels like a waste of time.

**Pull request closed without merging**
