### PR TITLE
Update: Fix call, new and member expressions in no-extra-parens

### PR DESCRIPTION
**Pull request by mdjermanovic**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix

This PR fixes 3 things in `no-extra-parens`:

1. False negatives when the `object` node in a `MemberExpression` is a `NewExpression` with parens. Example: `(new foo()).bar`. This change can generate **more** warnings by default.
2. False positives and invalid autofix when chained `NewExpression` is the `calee` of a `CallExpression` or a `NewExpression`. Example: `(new new foo())()`
3. The rule will now report `leftParenToken.loc` instead of just `leftParenToken.loc.start`.

**Tell us about your environment**

* **ESLint Version:**  6.4.0
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 2015,
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue.**

[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczplcnJvciAqL1xuXG4obmV3IGZvbygpKS5iYXI7XG5cbihuZXcgbmV3IGZvbygpKSgpO1xuXG5uZXcgKG5ldyBuZXcgZm9vKCkpKGJhcik7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHkiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXByb3RvdHlwZS1idWlsdGlucyI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtY2F0Y2giOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJuby13aXRoIjoyLCJyZXF1aXJlLWF0b21pYy11cGRhdGVzIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6e319fQ==)

```js
/* eslint no-extra-parens:error */

(new foo()).bar;

(new new foo())();

new (new new foo())(bar);
```

**What did you expect to happen?**

1 error, for the first line only.

**What actually happened? Please include the actual, raw output from ESLint.**

2 errors and invalid autofix for the other two lines.

```js
/* eslint no-extra-parens:error */

// false negative
(new foo()).bar; 

// false positive and invalid autofix - effectively removes call expression
new new foo()(); 

// false positive and invalid autofix - `bar` becomes argument of the second `new`
new new new foo()(bar); 
```

**What changes did you make? (Give an overview)**

1. Additional check in `MemberExpression`.
2. Fixed bug in `isNewExpressionWithParens` function.
3. The rule now reports the full left paren's `loc` instead of `loc.start`.

**Is there anything you'd like reviewers to focus on?**

Please verify that these are indeed false positives/negatives, and that the false negative wasn't intentional (I guess it's a bug as there were no test cases to confirm that it was intentional).

### CODE REVIEW

**Comment by ilyavolodin** [comment]
I'm a bit confused. Parents are needed for the first expression: `(new foo()).bar` is not the same thing as `new foo().bar`. And is `new new` syntax even valid? If it is, it's most likely a mistake, I think.

**Comment by mysticatea** [comment]
> Parents are needed for the first expression: (new foo()).bar is not the same thing as new foo().bar.

The `(new foo()).bar` and `new foo().bar` are the same thing. I guess you are confused with `(new foo).bar`.

> And is new new syntax even valid?

Yes, valid. Constructors can return another constructor.

```js
function Foo() {
    return Bar
}

function Bar() {
}

var bar = new new Foo // a Bar's instance.
```

> If it is, it's most likely a mistake, I think.

I agree. But the problem is `no-extra-parens` changes semantics unintentionally. It's a bug in the rule.

**Comment by mdjermanovic** [comment]
> I'm a bit confused. Parents are needed for the first expression: `(new foo()).bar` is not the same thing as `new foo().bar`.

It's the same thing, but the extra parens could be indeed helpful in this situation to avoid confusion. That's why I was wondering was it intentionally omitted. However, there is no test case to show this intention, so I believe it's a bug (unintentional oversight).

**Comment by ilyavolodin** [comment]
Ah, I did mix it up with `(new foo).bar`. In that case, I guess those fixes are fine. They do cover an extreme edge-cases, but it doesn't hurt.

**Pull request merged**
