### PR TITLE
Chore: add a Git .mailmap with my new name

### PR DESCRIPTION
**Pull request by mgol**
**What is the purpose of this pull request? (put an "X" next to item)**

* [ ] Documentation update
* [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
* [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
* [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
* [ ] Add autofixing to a rule
* [ ] Add a CLI option
* [ ] Add something to the core
* [x] Other, please explain:

Add a Git .mailmap with my new name.

**What changes did you make? (Give an overview)**

I created a `.mailmap` file with my new name.

**Is there anything you'd like reviewers to focus on?**

No.

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the PR. Could you clarify what effect this has? I'm not familiar with `.mailmap`.

**Comment by mgol** [comment]
@not-an-aardvark `.mailmap` is used by `git shortlog` (see e.g. what `git shortlog -nse` prints) & `git blame`. By default it doesn't affect `git log` or `git show`, mainly for historical reasons (see http://git.661346.n2.nabble.com/git-log-to-use-mailmap-by-default-td7570862.html). It can be made so in two ways:

1. By adding a `--use-mailmap` option: `git log --use-mailmap` or `git show COMMIT_HASH --use-mailmap`
2. By configuring Git globally to respect the `.mailmap` for logging: `git config --global log.mailmap true`. When set, this option is also respected for `git show`.

`.mailmap` affects what lots of apps present (mainly because Git respects it in many places). For example, it changes what WebStorm shows when you use its "Annotate" feature - a visual representation of `git blame` inside of the editor.

**Comment by mysticatea** [comment]
Hmm, I think it's not big pros to add new dotfile. I'd like to add dotfiles if it helps us to prevent mistakes (e.g., we added `.gitattributes` for contributors which use Windows), but I want not to add dotfiles to merely change looks.

**Comment by mgol** [comment]
Fair enough. Note that such things may be more important to other people, e.g. trans folks after a name change who would rather not see their old name when doing `git blame` etc. (I know OSS projects where it's used for this exact purpose).

Feel free to close the PR if you feel it's not worth a new file in its current state.

**Comment by platinumazure** [comment]
Is there anything else we can move from the top-level directory to make it feel less cluttered? Maybe moving some other files would make this change easier to accept.

**Comment by mgol** [comment]
@platinumazure mailmap location [can be set in Git config](https://metacpan.org/pod/Git::MoreHooks::CheckCommitAuthorFromMailmap#Mailmap-File) but AFAIK the config cannot be enforced by the repository.

**Comment by ilyavolodin** [comment]
@mgol I want to be sensitive to name changes/updates, but adding a whole new dot file for one entry seem like an overkill to me. We haven't seen this type of requests so far, I think if we get any more of them, we will add a new file and can update it with your name as well, but for now, I'm going to close this PR. Please let us know if you feel very strongly that this should be added, and we will reconsider.

**Comment by mgol** [comment]
No, I’m completely fine with not landing this patch. Thanks for your
consideration. :)
-- 
Michał Gołębiowski-Owczarek

**Pull request closed without merging**
