### PR TITLE
Fix: valid-jsdoc failure for missing return in interface methods (fixes #9978)

### LINKED ISSUE #9978: valid-jsdoc fails with missing return error for interface methods
**Tell us about your environment**

* **ESLint Version: 4.17.0**
* **Node Version: v8.3.0**
* **npm Version:**

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
'use strict';

module.exports = {
  extends: 'eslint:recommended',
  parserOptions: {
    ecmaVersion: 6
  },
  env: {
    browser: true,
    es6: true
  },
  rules: {
    'valid-jsdoc': ['error', {
      requireReturn: false,
      requireReturnDescription: false,
      requireParamDescription: false
    }]
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
"use strict";

/**
 * A thing interface.
 * @interface
 */
function Thing() {}

/**
 * An interface method which returns
 * @return {Object}
 */
Thing.prototype.bar = function() {};
```

```bash
$(npm bin)/eslint .
```

**What did you expect to happen?**
No valid-jsdoc error. As according to [JsDoc documentation](http://usejsdoc.org/tags-interface.html):

> You do not need to add the @interface tag to each member of the interface (for example, the interface's instance methods).

**What actually happened? Please include the actual, raw output from ESLint.**
```Unexpected @return tag; function has no return statement.```

### PR DESCRIPTION
**Pull request by germanz**
…es #9978)

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Added lookup in ancestor nodes for possible "interface" JsDoc tag in class/interface description when checking members.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by platinumazure** [comment]
Accepting this due to the corresponding issue being accepted.

**Comment by platinumazure** [comment]
Friendly ping @germanz: Are you still planning to work on this?

**Comment by germanz** [comment]
Hi. Sure, I'm a little bit busy at the moment, but will definitely look into this.

**Comment by germanz** [comment]
@platinumazure your concerns were right, I need to rework the logic to rely on AST of the file in order to reliably find the class/interface definition properly.

**Comment by platinumazure** [comment]
Friendly ping @germanz: Anything we can do to help with this PR? Would you be okay if others help push some commits to try to resolve the current issues?

**Comment by germanz** [comment]
I am ok if somebody is willing to fix the issue either on top of my commit or separately. Shall I remove the pull request?

**Comment by kaicataldo** [comment]
@germanz If you don't think you'll have time to finish up the work, it's fine to close it. It'll still be visible to anyone who wants to work on this in the future. Thanks for contributing, regardless!

**Comment by nzakas** [comment]
Thanks for the pull request. As of yesterday, we have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. All JSDoc features are now deprecated and we won't be fixing bugs or making any further improvements to those features.

We are recommending that people transition over to use the [`eslint-plugin-jsdoc`](https://github.com/gajus/eslint-plugin-jsdoc) plugin instead of the built-in rules in ESLint.

As a reminder, the work you've put into this pull request can still be used in a custom rule that you publish in your own plugin if it's something you need for your own projects.

Thanks for understanding and we apologize for any inconvenience.

**Pull request closed without merging**
