### PR TITLE
docs: Update section titles

### LINKED ISSUE #16578: update section headings to use non-gerund forms
### ESLint version

V8.x

### What problem do you want to solve?

Docs for ESLint currently often use gerund “-ing” form in section titles

### What do you think is the correct solution?

Change titles to use base verb form. 

Ex: “configuring a plugin” —> “configure a plugin”

Also update on section index pages that link to headers in child pages.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by bpmutter**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

Update section titles with the following:

- start with non gerund verb forms
- be title case

Also updated all inline links to reference the new section title names.

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### Is there anything you'd like reviewers to focus on?

Resolves #16578 and #16609

### CODE REVIEW

**Comment by ollie-iterators** [comment]
I am wondering if the "is" should really be capitalized in "When There Is a Function"

**Comment by bpmutter** [comment]
> I am wondering if the "is" should really be capitalized in "When There Is a Function"

generally "Is" is capitalized, as it's a verb. you can check here - https://capitalizemytitle.com/ and learn more here https://titlecaseconverter.com/blog/is-is-capitalized/

**Comment by Rec0iL99** [comment]
Reopened since @bpmutter was on vacation and is a work in progress.

**Comment by Rec0iL99** [comment]
Not stale. Work in progress.

**Comment by nzakas** [comment]
@bpmutter what is the status of this PR? Unsure how to move forward.

**Comment by nzakas** [comment]
Waiting for @bpmutter's response.

**Comment by bpmutter** [comment]
> @bpmutter what is the status of this PR? Unsure how to move forward.

i'd recommend closing it. looks like headers are updated but not the internal links to those headers. would be a non-trivial process to update all the internal links to these.

**Comment by nzakas** [comment]
Got it, thanks.

**Pull request closed without merging**
