### PR TITLE
Don't throw spurious shadow errors for classes

### PR DESCRIPTION
**Pull request by taion**
For eslint/eslint#2545

### CODE REVIEW

**Comment by gyandeeps** [comment]
Please format your commit message as per our guidelines: http://eslint.org/docs/developer-guide/contributing

**Comment by taion** [comment]
Updated commit message.

**Comment by gyandeeps** [comment]
Can you please prefix your message with "Fix:"

**Comment by taion** [comment]
My bad. Was in a hurry and didn't read beyond the bullet points at the start of the "Pull Requests" section.

**Comment by nzakas** [comment]
Can you add a failing case? Something like this:

```
class A {
    constructor() {
        let A;
    }
}
```

**Comment by taion** [comment]
For reasons unclear to me, the error gets raised twice. I've set up the test case to reflect that, and to show that it doesn't happen spuriously. I'm quite far out of my depth here and don't have time to dig further at the moment. Given that you're not looking to release the next version for a bit, feel free to take this over and fix in a more correct way if needed.

**Comment by nzakas** [comment]
Thanks, we'll take a look. That's definitely buggy behavior, so we can't merge as-is.

**Comment by taion** [comment]
It's significantly better than the status quo of erroring on every class declaration, though! :D

**Comment by nzakas** [comment]
Exchanging one error for another is not the way we operate

**Comment by taion** [comment]
To clarify, that's not exactly what's happening here. It's already the case against 0.21.1 that a shadowing name inside of a class declaration will raise two `no-shadow` errors rather than one. This PR doesn't do anything about that problem; it just fixes the issue that the class declaration itself spuriously introduces a `no-shadow` error. This is not a new bug introduced by this change; it's an existing bug that this change doesn't fix (rather, doesn't touch at all).

Also, in a slightly more serious tone, while the "double `no-shadow` error" is an inconvenience, #2545 is blocking us from upgrading to 0.21.1, while that issue does not.

**Comment by nzakas** [comment]
Are you saying the double reporting existed in *0.21.0*? If so, please file a new issue and remove the extra test from this PR.

**Comment by taion** [comment]
No, it's in 0.21.1. I can comment out the test case and file a new issue if you'd like, but it's not a bug caused by this PR.

**Comment by taion** [comment]
I take that back - it actually is in 0.21.0 as well.

**Comment by taion** [comment]
I filed #2552 reflecting the double-reporting issue. Is there anything left to do w/r/t this PR? I'm eager to unpin my `eslint` dependency as soon as I can, so I don't forget and get bitten down the road.

**Comment by nzakas** [comment]
Can you remove the invalid test?

**Comment by taion** [comment]
Do you want me to get rid of it entirely, correct the assertion (but have it be failing), or correct the assertion but comment it out?

**Comment by nzakas** [comment]
Remove it completely.

**Comment by taion** [comment]
Done.

**Comment by nzakas** [comment]
Thanks

**Pull request merged**
