### PR TITLE
docs: HTTPS link to yeoman.io

### PR DESCRIPTION
**Pull request by coliff**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:
#### What changes did you make? (Give an overview)

fix an URL

### CODE REVIEW

**Review by bmish — APPROVED** [review]
Thanks!

**Comment by Gstar123456** [comment]
tor. 24. nov. 2022 kl. 16:35 skrev eslint-github-bot[bot] <
***@***.***>:

> Hi @coliff!, thanks for the Pull Request
>
> The *first commit message* isn't properly formatted. We ask that you
> update the message to match this format, as we use it to generate
> changelogs and automate releases.
>
>    - The commit message tag wasn't recognized. Did you mean "docs",
>    "fix", or "feat"?
>    - There should be a space following the initial tag and colon, for
>    example 'feat: Message'.
>    - The first letter of the tag should be in lowercase
>
> *To Fix:* You can fix this problem by running git commit --amend, editing
> your commit message, and then running git push -f to update this pull
> request.
>
> Read more about contributing to ESLint here
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>
-- 
Gstar

**Comment by Gstar123456** [comment]
tor. 24. nov. 2022 kl. 16:35 skrev netlify[bot] ***@***.***>:

> 👷 Deploy Preview for *docs-eslint* processing.
> Name Link
> 🔨 Latest commit 9f98219
> 🔍 Latest deploy log
> https://app.netlify.com/sites/docs-eslint/deploys/637f8f2b0c0bb20008e94763
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>
-- 
Gstar

**Comment by Gstar123456** [comment]
tor. 24. nov. 2022 kl. 16:35 skrev Christian Oliff ***@***.***
>:

> Prerequisites checklist
>
>    - I have read the contributing guidelines.
>
> What is the purpose of this pull request? (put an "X" next to an item)
>
> [x] Documentation update
> [ ] Bug fix (template)
> [ ] New rule (template)
> [ ] Changes an existing rule (template)
> [ ] Add autofix to a rule
> [ ] Add a CLI option
> [ ] Add something to the core
> [ ] Other, please explain:
> What changes did you make? (Give an overview)
>
> fix an URL
> Is there anything you'd like reviewers to focus on?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/eslint/eslint/pull/16582
> Commit Summary
>
>    - 9f98219 HTTPS link to yeoman.io
>
> File Changes
>
> (1 file)
>
>    - *M* docs/src/developer-guide/development-environment.md (2)
>
> Patch Links:
>
>    - https://github.com/eslint/eslint/pull/16582.patch
>    - https://github.com/eslint/eslint/pull/16582.diff
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>
-- 
Gstar

**Pull request merged**
