### PR TITLE
Docs: Fix typo and missing article before noun in docs

### PR DESCRIPTION
**Pull request by pmsandhu**
…lons.

#### Prerequisites checklist

- [X ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Fixed a typo in the `developer-guide/working-with-rules#providing-suggestions` documentation - changed semicolumns to semicolons.

### CODE REVIEW

**Comment by pmsandhu** [comment]
@yeonjuan Reread the link you sent and realized that my git email was set to my work email and not my personal email so that is why the commit author was not recognized. In order to link this pr with the correct email I added another minor documentation fix to the `Node.js API - CLIEngine#executeOnFiles()` section where there article `an` was missing before the word `array`.

**Review by anikethsaha — APPROVED** [review]

**Review by yeonjuan — APPROVED** [review]
LGTM Thanks :)

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by mdjermanovic** [comment]
Thanks for contributing!

**Pull request merged**
