### PR TITLE
Update: Improve the error messages for `no-unused-vars` (fixes #7282)

### LINKED ISSUE #7282: no-unused-vars false positive for use on right side of assignment
**Tell us about your environment**

* **ESLint Version:** http://eslint.org/demo
* **Node Version:** n/a
* **npm Version:** n/a

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

None, inline

**What did you do? Please include the actual source code causing the issue.**

```js
/* eslint no-unused-vars: "error" */
// 'foo' is defined but never used. (no-unused-vars)
var foo;
foo = 42;
foo = foo();
foo = foo.bar();
foo = bar(foo);

// No error
var bar;
bar = 42;
bar();
```

**What did you expect to happen?**

No error. `foo` is used multiple times on the right side of the assignment expressions.

**What actually happened? Please include the actual, raw output from ESLint.**

3:5 - 'foo' is defined but never used. (no-unused-vars)

It looks like references are being excluded on both sides of assignment expressions instead of just the left side.

Originally seen on http://stackoverflow.com/questions/39787723/eslint-no-unused-vars-stream-conditional-pipe-use-case

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What rule do you want to change?**

**Does this change cause the rule to produce more or fewer warnings?**

The same amount

**How will the change be implemented? (New option, new default behavior, etc.)?**

The error message will change for the current behavior.

**Please provide some example code that this change will affect:**

```js
var foo;

foo = 1;
```

**What does the rule currently do for this code?**

```
1:5  error  'foo' is defined but never used  no-unused-vars
```

**What will the rule do after it's changed?**

```
1:5  error  'foo' is assigned a value but never used  no-unused-vars
```

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- (n/a) I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**

Also see: https://github.com/eslint/eslint/issues/7282#issuecomment-250937430

This updates the error message for `no-unused-vars`. The new error message is used whenever a variable is assigned at least once (e.g. `var foo = 5;`, `var foo; foo = 5;`). The old error message is used if the variable is never assigned (`var foo;`).

The current behavior has led to a lot of confusion for users (see the linked comment for some examples), so I think this would be a beneficial change.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

**Comment by mysticatea** [comment]
Ah, I think this PR fixes #6703 also.

**Comment by not-an-aardvark** [comment]
@btmills I would be fine with either. I'm leaning slightly towards what we already have (`'{{name}}' is assigned a value but never used` since the rule cares about whether the *variable* is used, not the value. I'm open to further bikeshedding on the message, though.

**Comment by btmills** [comment]
```js
var foo = 42;
foo = bar(foo);
```

When I suggested saying the value is never used instead of the variable, that's the scenario I was imagining. If that's not compelling, I'm fine with it as-is.

**Comment by not-an-aardvark** [comment]
Based on an informal Gitter survey, it seemed like people generally preferred the `'foo' is assigned a value but never used` message, so I decided to leave it as-is.

**Pull request merged**
