### PR TITLE
Update: adding some tests for no-redeclare to test named functions (fixes #2953)

### LINKED ISSUE #2953: Should no-redeclare also check functions?
I just got burned by a stupid mistake, but I think it should've been caught by `no-redeclare`.

Given the following code:

```
var a = true;
function a() {}
```

If I turn on `no-redeclare: 2`, this is **not** treated as an error, but I think it should.

To be clear, this was a stupid mistake on my part. I added a `var` to the top of a file that was named the same as a function declared much further down in my code. Nonetheless, I think `no-redeclare` should take hoisted functions into account as well.

### PR DESCRIPTION
**Pull request by dominicbarnes**
This addresses [my comment](https://github.com/eslint/eslint/issues/2953#issuecomment-120084338) in #2953 and adds a couple of trivial tests for the case that originally helped me discover this bug.

I have idea if I formatted this PR correctly, so please correct me if I need to change anything and get this merged. :)

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Can you change your commit message to start with "Update:" instead of "Build"?

**Comment by dominicbarnes** [comment]
Sure thing! I wasn't _quite_ sure which tag to use.

**Comment by dominicbarnes** [comment]
@ilyavolodin done :)

**Comment by ilyavolodin** [comment]
Thanks

**Pull request merged**
