### PR TITLE
Fix: Add linting of Markdown files to "npm test" script (fixes #2182)

### LINKED ISSUE #2182: Add linting of Markdown files to "npm test" script
Malformed Markdown content can lead to problems in the generated HTML (ex: #1292, #1468, #1815, #1847).

One solution - called for in #1297 - is to introduce a Markdown linter.

I'm about to submit a pull request that does so.

### PR DESCRIPTION
**Pull request by DavidAnson**
Lint all Markdown files in the project.
Suppress rules that may be controversial or deliberately violated.

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks, this looks great!

Can you update your commit message to begin with "Build:" instead of "Fix:"?

Also, can you please sign our CLA: http://eslint.org/cla

**Comment by DavidAnson** [comment]
Great - reword-ed and signed!

I'll probably follow up with PRs to enable some of the other rules as time permits.

Also, FYI that there seemed to be a pre-existing test failure at or before the parent of the PR's commit.

**Comment by nzakas** [comment]
Are you sent a test failure? If so, please provide some details. I've been working on master and don't see any failures. Note that Travis had been a bit flaky the past few days.

**Comment by DavidAnson** [comment]
I can reproduce the following test failure with commit 507c2c24 (prior to this PR, so no need to block the merge) on two different Windows machines. If nothing stands out for you, I'll look into it this evening. (First guess would be line-ending differences??)

```
  1) no-ex-assign try { } catch ({e}) { this.something = 2; }:
     AssertionError: Should have no errors but had 1: [ { fatal: true,
    severity: 2,
    message: 'Unexpected token {',
    line: 1,
    column: 16 } ]: expected 1 to equal 0
```

**Comment by nzakas** [comment]
I'm on Windows as well, but maybe a line-ending issue. Make sure you're using the latest Espree. 

If you find a problem, please file another issue. Thanks!

**Pull request merged**
