### PR TITLE
Chore: Add configuration wrapper markdown for the bug report template

### PR DESCRIPTION
**Pull request by revolter**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

**What changes did you make? (Give an overview)**

Copied the wrapper markdown from https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE.md.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by Aladdin-ADD** [comment]
the change looks good to me. But I'm not sure if the template is still needed.

**Comment by revolter** [comment]
What do you mean by "needed"? It's currently linked from https://github.com/eslint/eslint/blob/master/.github/PULL_REQUEST_TEMPLATE.md (`Bug fix`).

**Comment by Aladdin-ADD** [comment]
we can change the link to `.github/ISSUE_TEMPLATE/BUG_REPORT.md`, and then remove the identical template. (if it was not used somewhere else)

**Comment by revolter** [comment]
@Aladdin-ADD, Could be, as I think it's identical, but it's not a decision I can take. I could, instead, close this and open another one that does the removal if you guys decide it's the way to go.

**Comment by Aladdin-ADD** [comment]
@platinumazure thoughts on https://github.com/eslint/eslint/pull/10669#issuecomment-407582466 ?

I'm seeing a rationality to remove the identical template!

**Comment by not-an-aardvark** [comment]
* Before GitHub supported multiple issue templates, we had a single issue template with several links to other templates, with the expectation that the user would copy-paste the contents of one of the other templates into the issue. These other templates were in the `templates/` folder.
* Now that GitHub supports multiple issue templates, we moved our templates into `.github/ISSUE_TEMPLATE/`, and we no longer ask users to copy-paste templates into issues. (We still ask users to do this for PRs.)
* I don't think GitHub's UI uses anything in the `templates/` folder. It only uses things in the project root or in `.github/`.
* We could remove the issue template from `templates` if we update the link in the PR template to point to the templates in `.github/ISSUE_TEMPLATE`. However, it's worth noting that the files in `.github/ISSUE_TEMPLATE` have some metadata at the top. I'm not sure if this would degrade the user experience when copy-pasting them.

**Comment by platinumazure** [comment]
@Aladdin-ADD @not-an-aardvark I'm not clear what the next steps are here. Can this be merged as is, or are changes needed?

**Comment by not-an-aardvark** [comment]
@platinumazure This can be merged as-is. It might be a good idea for us to consider removing this file from `templates/` entirely, but as-is this is an improvement over the existing situation.

**Comment by platinumazure** [comment]
Merged. Thanks @revolter for contributing!

**Comment by revolter** [comment]
Thanks for merging!

**Pull request merged**
