### PR TITLE
Chore: enable additional eslint-plugin-jsdoc rules

### PR DESCRIPTION
**Pull request by kaicataldo**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

**What changes did you make? (Give an overview)**

Following up on https://github.com/eslint/eslint/pull/12332, this enables two more rules for consistency:
 - [newline-after-description](https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-newline-after-description)
 - [require-hyphen-before-param-description](https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-require-hyphen-before-param-description)

I set both to enforce "never" because that seemed like the more common style within the codebase, but I don't have any personal preferences as to which we pick. I do think it would be good if it was consistent, though, since I believe that would reduce overhead for contributors who don't have much experience with JSDoc.

I think it would also be nice to enable [require-description](https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-require-description), but there are 31 instances of missing descriptions and I wanted to move onto some more important things. Could it be worth making a detailed issue with links to the doc blocks missing description and put the `help wanted` label on it?

**Is there anything you'd like reviewers to focus on?**
Do others agree that this is something we should do?

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Personal preference: require-hyphen-before-param-description to always, but I can live with either, to be honest.

**Comment by kaicataldo** [comment]
@ilyavolodin I have no preference either way and am happy to defer to consensus.

**Comment by kaicataldo** [comment]
I'm going to go ahead and merge this so as to avoid merge conflicts, but I'm definitely not tied to which style we choose (and would be happy to change it later).

**Comment by kaicataldo** [comment]
@mysticatea I like the idea of enabling `require-description` and using `eslint-disable-*` comments! Will make a follow up PR.

**Pull request merged**
