### PR TITLE
chore: Upgrade cross-spawn to 7.0.6

### PR DESCRIPTION
**Pull request by folortin**
cross-spawn 7.0.6

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Hi @folortin, thanks for the PR! Can you please fill out the PR template? Also, since this change is tagged as `fix`, can you provide more details on what problem it fixes?

**Comment by lumirlumir** [comment]
Hello, @mdjermanovic,  

I believe this PR addresses a security vulnerability caused by the `cross-spawn` package.  

When I run `npm audit`, I see a 'Severity: high' warning, as shown in the screenshot below.  

image

**Comment by nzakas** [comment]
There is a [security advisory](https://github.com/advisories/GHSA-3xgq-45jj-v275) for cross-spawn < 6.0.6, but that's a transitive dependency for ESLint, so not within our control. The version we are using, 7.0.5, does not have this vulnerability. So this is just a chore.

**Comment by mdjermanovic** [comment]
Per the [CHANGELOG](https://github.com/moxystudio/node-cross-spawn/blob/master/CHANGELOG.md), it also doesn't seem that any bugs or security issues were fixed in v7.0.6, compared to v7.0.5.

Either way, seems fine to merge this as a chore.

**Review by mdjermanovic — APPROVED** [review]

**Pull request merged**
