### PR TITLE
Fix: no-restricted-globals crash with "hasOwnProperty" (fixes #10660)

### LINKED ISSUE #10660: no-restricted-globals rule crashes with 'hasOwnProperty' as restricted global
**Tell us about your environment**

* **ESLint Version:** v5.2.0
* **Node Version:** v8.11.1
* **npm Version:** v5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
	"rules": {
		"no-restricted-globals": ["error", "hasOwnProperty"],
	}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
module.exports = obj => hasOwnProperty(obj, 'name');
```

**What did you expect to happen?**
Should get a warning for using the global "hasOwnProperty".

**What actually happened? Please include the actual, raw output from ESLint.**

```
restrictedGlobalMessages.hasOwnProperty is not a function
TypeError: restrictedGlobalMessages.hasOwnProperty is not a function
    at isRestricted (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/rules/no-restricted-globals.js:97:45)
    at Program.scope.variables.forEach.variable (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/rules/no-restricted-globals.js:106:50)
    at Array.forEach (<anonymous>)
    at Program (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/rules/no-restricted-globals.js:105:33)
    at listeners.(anonymous function).forEach.listener (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/richard/github/website-backend/playosmo-js/node_modules/eslint/lib/util/node-event-generator.js:294:14)
```

The issue is this line in `no-restricted-globals.js`:
```js
        function isRestricted(name) {
            return restrictedGlobalMessages.hasOwnProperty(name);
        }
```

which should be:

```js
        function isRestricted(name) {
            return Object.prototype.hasOwnProperty.call(restrictedGlobalMessages, name);
        }
```

### PR DESCRIPTION
**Pull request by IceDune**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Issue #10660 

**What changes did you make? (Give an overview)**
fixed typeError during isRestricted check.

**Is there anything you'd like reviewers to focus on?**
changed the isRestricted function

### CODE REVIEW

**Comment by IceDune** [comment]
@Aladdin-ADD , hi, is there any change i need to do?

**Comment by Aladdin-ADD** [comment]
thanks for the PR!  mind adding a test to show what it's trying to fix?😄  

and you need sign our [CLA](https://cla.js.foundation/eslint/eslint?pullRequest=10711) before we can merge the PR.

**Comment by IceDune** [comment]
Shall i make another commit as this one has my other email id? 
I'll make it with the one i signed up for the CLA with.

**Comment by IceDune** [comment]
@Aladdin-ADD ,the license is signed.
but i don't know how to write test cases, could you help me with that?

**Comment by Aladdin-ADD** [comment]
the tests file is in  https://github.com/eslint/eslint/blob/6eb972ce13f00228b5e4e47966100cc743bce8b6/tests/lib/rules/no-restricted-globals.js#L22-L24

you can add a unit test that would fail without this change, but pass with this change. if you have some more questions, please feel free to join the [gitter](https://gitter.im/eslint/eslint).

**Comment by IceDune** [comment]
@platinumazure yeah, got it.

**Comment by Aladdin-ADD** [comment]
Cloising, as the issue was addressed in https://github.com/eslint/eslint/pull/10664. Thanks for the contributing regardless!

**Pull request closed without merging**
