### PR TITLE
Breaking: add rules to recommended (fixes #8865)

### LINKED ISSUE #8865: Discussion: eslint-recommended changes proposal
these rules can be candidate to added in next major release:

+ no-eval
+ no-implied-eval
+ no-with
+ no-new-func
+ no-array-constructor
+ no-new-wrappers
+ for-direction
+ getter-return (new added)
+ no-proto
+ require-await
+ no-return-await
+ no-useless-rename

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
add `for-direction` & `getter-return` to recommended (fixes ##8865)

**Is there anything you'd like reviewers to focus on?**

some rules like `no-eval` and `no-implied-eval` etc. need more discussion?

### CODE REVIEW

**Comment by Aladdin-ADD** [comment]
I have created a issue #8865 for discussion, should I create a new one?

**Comment by not-an-aardvark** [comment]
Sorry, I didn't notice that you linked to #8865.

**Comment by Aladdin-ADD** [comment]
just pushed a commit to set `recommended: true`.

unrelated: `recommended` is only used to gen docs? the `conf/eslint-recommended.js`  file  seems enough to do it.

**Comment by platinumazure** [comment]
> unrelated: `recommended` is only used to gen docs? the `conf/eslint-recommended.js`  file  seems enough to do it.

It would be nice to have conf/eslint-recommended.js and `meta: { docs: { recommended: true } }` be in sync, but I think we can fix that in future.

I skimmed the linked issue and I think I agree that `for-direction` and `getter-return` are for sure worth adding to `eslint:recommended`. Worst case, we could add some more in a later PR while we're still in prerelease mode.

**Comment by not-an-aardvark** [comment]
Thoughts on adding [`no-prototype-builtins`](https://eslint.org/docs/rules/no-prototype-builtins)?

**Comment by not-an-aardvark** [comment]
Personally, I've found that `hasOwnProperty` is usually used when accepting input anyway, because if the argument was already known then there would be no reason to use `hasOwnProperty`. I think this is a common source of potential crashes, e.g. in webapps that use `hasOwnProperty` on an object provided by the client.

**Comment by Aladdin-ADD** [comment]
it can be used in some ability detection:
```js
window.hasOwnProperty('console'); // to detect if console exists
```
but I'm seeing it's very rare, and it's no harm to use `Object.prototype.hasOwnProperty`. That is to say, I'm not oppose to add `no-prototype-builtins`.

Unrelated: 
seems the rule allow some methods from `Object.prototype`, like `toString`, `toLocaleString` (and not shown in the docs).  is this expected?

**Comment by not-an-aardvark** [comment]
**TSC Summary**: In major releases in the past, we've usually added some rules to `eslint:recommended`.
**TSC Question**: What rules should we add? The `for-direction`, `getter-return`, and `no-prototype-builtins` rules have been proposed in this issue so far.

**Comment by ilyavolodin** [comment]
`for-direction` and `getter-return` sound good to me. I don't think we should add `no-prototype-builtins`. I always found that rule to be too paranoid for my taste. While it's a good rule in theory, in practice, I doubt many people would want to use those long chains in their code.

**Comment by not-an-aardvark** [comment]
Personally, I've found that using `hasOwnProperty` is a bug fairly often (basically anytime it's called on an object that comes from external input). The prevalence of these bugs is underrated because people often don't realize that their code has a bug, because they don't write tests for input that involves `hasOwnProperty`. In my opinion, calling the `hasOwnProperty` method on an object is a code smell -- it's not a good idea to use a pattern that's highly prone to bugs when a reliable (albeit slightly more verbose) pattern exists.

**Comment by ilyavolodin** [comment]
@not-an-aardvark I don't disagree with your statement. I'm just being realistic. This rule complicates code in a significant way, and requires users to do something unnatural. While it's good guard against possible bugs, it doesn't apply in a lot of situations. If you have full control over the code (as in, don't use external libraries), and are not overriding native object properties, you don't need to jump through those hoops. It also doesn't apply if you fully trust libraries you use.
As such, while this rule is valuable, it doesn't apply to everyone and should probably not be included in our recommended set.

**Comment by not-an-aardvark** [comment]
I see what you're saying, although it's worth noting that the issue still applies even if you don't use any external libraries and you're in control of the code you're writing. For example, imagine this HTTP server code:

```js
function searchEndpoint(req, res) {
  let pageOfSearchResults;
  if (req.query.hasOwnProperty('page') {
    pageOfSearchResults = req.query.page;
  } else {
    pageOfSearchResults = 1;
  }
  // ...
}
```

This code will crash the server if someone sends a request like `/search?hasOwnProperty=1` to the server.

In other words, the rule applies whenever the object is coming from either (a) external user input (e.g. a querystring) or (b) an external library. The only case where it *doesn't* apply is when the object was created in your own code and no external code or user input has control over the properties. But if that's the case, it's usually not useful to call `hasOwnProperty` on the object anyway, because you would usually already know what properties it has. So the cases where `hasOwnProperty` is useful are also the cases where it causes bugs.

**Comment by platinumazure** [comment]
We've kept things out of eslint:recommended (or removed after putting them in) for more trivial reasons. I don't think we should put in `no-prototype-builtins` based on that.

**Comment by not-an-aardvark** [comment]
In [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/c271eee0c355058b90acb511a6e70a0c4520b121/notes/2018/2018-04-26.md#breaking-add-rules-to-recommended-fixes-8865), the TSC decided to add `for-direction` and `getter-return` to `eslint:recommended`, but not `no-prototype-builtins`.

**Comment by Aladdin-ADD** [comment]
force pushed to follow the tsc decision. ready to be reviewed.

**Pull request merged**
