### PR TITLE
Chore: enable linebreak-style on ESLint codebase

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Other, please explain:

**What changes did you make? (Give an overview)**

This enables linebreak-style on the ESLint codebase. As a result, it should no longer be necessary to convert linebreaks as part of the release process.

Refs: https://github.com/eslint/eslint-release/issues/17

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

**Comment by ilyavolodin** [comment]
I'm not sure that's a good idea. If somebody has git setup with checkout "as-is" and check-in "unix" this will be constantly erroring on Windows machine. This rule would only matter to somebody who is doing manual releases from their computer.

**Comment by gyandeeps** [comment]
> If somebody has git setup with checkout "as-is" and check-in "unix" this will be constantly erroring on Windows machine.

I think you meant checkout window style and check-in unix style. because i use as-is checkout style and it will not error.

**Comment by not-an-aardvark** [comment]
I don't think this will happen because our `.gitattributes` file instructs git to always checkout with LF.

**Comment by ilyavolodin** [comment]
I mean if you are creating a PR on Windows and modifying files, git will not fix line-endings until you check in your changes. If you run `npm test` you will get errors from this rule.

**Comment by not-an-aardvark** [comment]
Oh, good point. Do editors on windows generally default to CRLF?

In my view, the problem here is that converting all linebreaks in the repo on release is error-prone because the build could pass even though the repository is in an unreleasable state. This could result in another broken release if we do a release without using the release tool in the future for whatever reason. It seems like it would be better to have the build fail if the shebang is invalid.

* Now that we have a `.gitattributes` file, I don't think the original problem would occur anyway, because the files wouldn't get checked out with CRLF even on windows.
* As an alternative to enabling `linebreak-style` on the entire codebase, we could use the [shebang](https://github.com/mysticatea/eslint-plugin-node/blob/f1a137b1250cd457cd9dfdf0bf851d1efa0ce2fa/docs/rules/shebang.md) rule from `eslint-plugin-node` to make sure that shebangs aren't followed by `\r\n`.

**Comment by ilyavolodin** [comment]
Yes, most editors default to CRLF on Windows. Using shebang rule sounds better to me. Adding linebreak-style on the whole repository will raise the bar of entry for new contributors on Windows. Converting linebreaks as part of the release has been working without issues for the last 2 years, so I'm not sure I'm convinced that we need to change something that isn't really broken.

**Comment by not-an-aardvark** [comment]
Ok, closing this for now.

**Pull request closed without merging**
