### PR TITLE
Fix: prefer-named-capture-group incorrect locations (fixes #12233)

### LINKED ISSUE #12233: prefer-named-capture-group is reporting incorrect locations
**Tell us about your environment**

* **ESLint Version:**  6.3.0
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 2015,
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgcHJlZmVyLW5hbWVkLWNhcHR1cmUtZ3JvdXA6IFwiZXJyb3JcIiovXG5cblJlZ0V4cChcIlxcXFxkXFxcXHMoYSlcIik7XG5cblJlZ0V4cChcIihcIiArIFwiYVwiICsgXCIpXCIpO1xuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHkiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtY2F0Y2giOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJuby13aXRoIjoyLCJyZXF1aXJlLWF0b21pYy11cGRhdGVzIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6e319fQ==)

```js
/*eslint prefer-named-capture-group: "error"*/

RegExp("\\d\\s(a)");

RegExp("(" + "a" + ")");
```

```bash
eslint index.js
```

**What did you expect to happen?**

2 errors, but not with incorrect locations.

**What actually happened? Please include the actual, raw output from ESLint.**

```
3:13  error  Capture group '(a)' should be converted to a named or non-capturing group  prefer-named-capture-group
5:9   error  Capture group '(a)' should be converted to a named or non-capturing group  prefer-named-capture-group
```

```js
/*eslint prefer-named-capture-group: "error"*/

RegExp("\\d\\s(a)"); // highlighting '\s('

RegExp("(" + "a" + ")"); // highlighting '(" '
```

**Are you willing to submit a pull request to fix this bug?**

Yes.

Perhaps if `arguments[0]` is not a string literal which `raw` is same as internal presentation, then report the location of the whole `arguments[0]`?

### PR DESCRIPTION
**Pull request by mdjermanovic**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix #12233

This PR fixes reporting incorrect location in `prefer-named-capture-group` when the pattern in `RegExp()` or `new RegExp()` is any of the following:

* Computed string
* String with an escape sequence
* Multiline string

**Tell us about your environment**

* **ESLint Version:**  6.3.0
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 2015,
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue.**

[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1uYW1lZC1jYXB0dXJlLWdyb3VwOmVycm9yICovXG5cblJlZ0V4cCgnJyArICcoYSknKTtcblJlZ0V4cCgnXFxcXGRcXFxcZChhKScpO1xuUmVnRXhwKGBcbihhKWBcbik7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHkiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXByb3RvdHlwZS1idWlsdGlucyI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWNhdGNoIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8td2l0aCI6MiwicmVxdWlyZS1hdG9taWMtdXBkYXRlcyI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjJ9LCJlbnYiOnt9fX0=)

```js
/* eslint prefer-named-capture-group:error */

RegExp('' + '(a)');
RegExp('\\d\\d(a)');
RegExp(`
(a)`
);
```

**What did you expect to happen?**

3 errors with correct locations.

**What actually happened? Please include the actual, raw output from ESLint.**

```
  3:9   error  Capture group '(a)' should be converted to a named or non-capturing group  prefer-named-capture-group
  4:13  error  Capture group '(a)' should be converted to a named or non-capturing group  prefer-named-capture-group
  5:10  error  Capture group '(a)' should be converted to a named or non-capturing group  prefer-named-capture-group
```

**What changes did you make? (Give an overview)**

In the above cases, report the whole `arguments[0]` location.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by platinumazure** [comment]
Given that we specify the capture group content, I'm wondering if we should just always report the full pattern to simplify the logic here...

**Comment by mdjermanovic** [comment]
It is indeed a lot of code just to improve the reported location. If it would be better to simplify, I can modify this PR.

**Comment by mdjermanovic** [comment]
I think the intention to report the exact location is because this rule, unlike other regex/string rules, reports multiple errors for the same node [#11392 (comment)](https://github.com/eslint/eslint/pull/11392#discussion_r257240169)

**Comment by mdjermanovic** [comment]
If all agree I can change the code to report:

* Just 1 error (the first one), with its group content in the message.
* The whole `new RegExp`/`regex literal` node as location.

**Comment by mysticatea** [comment]
:+1:

**Comment by platinumazure** [comment]
I would like all errors reported for better UX, but if that's a pain to implement, I'm okay with 1 error. And I definitely think the whole node should be reported.

**Comment by mdjermanovic** [comment]
> I would like all errors reported for better UX, but if that's a pain to implement, I'm okay with 1 error. And I definitely think the whole node should be reported.

This shouldn't be a problem technically. If it's okay to report multiple errors from the same rule for the same location (the full node), it can be done.

**Comment by platinumazure** [comment]
I have no problem with it since the error message lists the unnamed capture group in question. So although the location is the same, users should understand each as a distinct error.

If other team members think this could be a confusing UX, I'm okay with one error. And if the error message did not show the actual issue, then I would agree we should only show one error, because multiple identical-looking errors is a bad user experience.

**Comment by mdjermanovic** [comment]
It's modified now. The rule still reports multiple errors for the same regular expression, but always the full node (regex Literal, NewExpression or CallExpression) as the location.

**Pull request merged**
