### PR TITLE
Improve comma-dangle documentation

### PR DESCRIPTION
**Pull request by pgilad**
Fix a minor misspelling (an -> a). Also, reading paragraphs is pretty hard in order to figure out options, so I refactored the options to be on a bullet list.

### CODE REVIEW

**Comment by gyandeeps** [comment]
Can you please
* Sign our [CLA](http://eslint.org/cla/)
* Prepend your commit message with "Docs:"

As per our contribution guidelines: http://eslint.org/docs/developer-guide/contributing/

**Comment by pgilad** [comment]
Done on both accounts

**Comment by ilyavolodin** [comment]
Build is failing due to markdown linting error:
```
docs/rules/comma-dangle.md: 19: MD032 Lists should be surrounded by blank lines
```

**Comment by pgilad** [comment]
Fixed, thanks!

**Pull request merged**
