### PR TITLE
Update: check logical assignment in no-constant-condition

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What rule do you want to change?**

no-constant-condition

**Does this change cause the rule to produce more or fewer warnings?**

more

**How will the change be implemented? (New option, new default behavior, etc.)?**

new default behavior

**Please provide some example code that this change will affect:**

```js
if (a ||= true);

if (a &&= false);

if (a ||= b || true);

if (a && (b &&= false));

if (!(a ||= 'foo') === true);

if (!(a ||= 'foo') === false);
```

**What does the rule currently do for this code?**

no errors

**What will the rule do after it's changed?**

all conditions will be reported

#### What changes did you make? (Give an overview)

Added logic for logical assignments.

#### Is there anything you'd like reviewers to focus on?

This wasn't included in https://github.com/eslint/eslint/pull/13618 as it was waiting for refactoring and bug fixes from https://github.com/eslint/eslint/pull/13245. Can we treat this as a semver-minor bug fix?

### CODE REVIEW

**Comment by btmills** [comment]
It's interesting that this rule doesn't currently check non-logical assignment expressions. For example, `if (a |= true)` in one of your tests is a constant condition, but the rule currently allows it. Had the rule already checked non-logical assignment expressions, I'd say yes, this is a semver-minor change so that this rule supports a new language feature. But since we're not currently checking any assignment expressions, it seems inconsistent to start checking logical assignments in a semver-minor change when adding checks for the existing non-logical assignment operators would be a semver-major change or behind an option.

Should this instead add a `checkAssignments` option that checks all assignment expressions, logical and non-logical? We could enable it by default in the next major.

**Comment by mdjermanovic** [comment]
It does check the direct `=` and other expressions that evaluate to one of the operands, like logical and sequence. It doesn't have the logic for specific arithmetic and bitwise binary operators like `|` yet, so it skips compound assignments.

For example, this is nearly the same as `if (a ||= true);`:

```js
/* eslint no-constant-condition: "error" */

if (a = a || true); // error
```

[demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWNvbnN0YW50LWNvbmRpdGlvbjogXCJlcnJvclwiICovXG5cbmlmIChhID0gYSB8fCB0cnVlKTtcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

It indeed doesn't account for `=` and others in `isLogicalIdentity`, so `if (a || (a = true));`, which would be fully equivalent, isn't currently an error.

Maybe we could [remove this](https://github.com/eslint/eslint/blob/81bad3ee918fb71d592ad8b331366bbe95e99da2/lib/rules/no-constant-condition.js#L113-L116), but leave the rest?

**Review by nzakas — COMMENTED** [review]
Can you also update the examples in the documentation?

**Comment by mdjermanovic** [comment]
> Can you also update the examples in the documentation?

Added examples for `&&=` and `||=`.

**Review by nzakas — APPROVED** [review]
LGTM

**Review by btmills — APPROVED** [review]
LGTM

**Comment by btmills** [comment]
To resolve my question above, we decided in yesterday's TSC meeting to update our semantic versioning policy to allow adding new rule checks for new language features in semver-minor features. That's being done in https://github.com/eslint/eslint/pull/13970, and this is semver-minor per that policy.

**Pull request merged**
