### PR TITLE
Update : Add `keywords` flag to `consistent-as-needed` mode in `quote-props`

### LINKED ISSUE #3532: Add `keywords` flag to `consistent-as-needed` mode in `quote-props`
I was happy to see that I was able to enforce consistency on keys with `consistent-as-needed`, but it looks like the `{ keywords: true }` option is not available.

### PR DESCRIPTION
**Pull request by BYK**
Fixes #3532

### CODE REVIEW

**Comment by BYK** [comment]
Updated the docs too.

**Comment by gyandeeps** [comment]
Do we need to add a test for `keyword: false` and it should show errors?

**Comment by BYK** [comment]
>Do we need to add a test for keyword: false and it should show errors?

Default is that and I think there are test cases for it so I don't think we need any tests for that.

**Comment by guerrero** [comment]
@BYK There's a problem in the tests you've created. You're testing literals that contains quoted reserved keywords but you're not testing literals with unquoted reserved words so if you check the next code with ESLint it returns a false valid output without errors:

```js
/*eslint quote-props: [2, "consistent-as-needed", {"keywords": true}]*/

var x = {
    while: 1, // `while` is a reserved word. This should return an error but it doesn't.
    volatile: "foo"
};

```
And yeah, all test are passing but that's because you haven't created a test to check this case. So, we need to place the following test in invalid tests for `qoute-props`:

```js
{
    code: "({ while: 0, b: 0 })",
    options: ["consistent-as-needed", {keywords: true}],
    errors: [{
        message: "Properties should be quoted as `{{property}}` is a reserved word.", type: "ObjectExpression"
    }]
}
```
And then to fix it in `quote-props.js` rule we need to place this code at [line 157](https://github.com/eslint/eslint/blob/master/lib/rules/quote-props.js#L157):

```js
} else if (KEYWORDS && checkQuotesRedundancy && key.type === "Identifier" && isKeyword(
    context.report(node, "Properties should be quoted as `{{property}}` is a reserved word.");
}
```
And that's all. I have checked guidelines and contributing rules and I can implement that if you want but I don't know which is the process to fix an already merged PR, maybe @nzakas can help to solve this question.

Thanks for your work!

**Comment by IanVS** [comment]
@guerrero Thanks for the report!  Your best bet is to open a new issue, then once it is reviewed and accepted, submit a PR.

**Comment by guerrero** [comment]
Thanks, I've created the issue.

**Comment by ilyavolodin** [comment]
@guerrero To answer your last question, once PR is merged, it's part of the core codebase, so the process for fixing an issue with it is what's described in contributing guidelines.

**Pull request merged**
