### PR TITLE
Add WebExtensions globals.

### PR DESCRIPTION
**Pull request by bwinton**
As per [Chrome’s documentation](https://developer.chrome.com/extensions/api_index), [Opera’s documentation](https://dev.opera.com/extensions/index.html), and [Firefox’s documentation](https://wiki.mozilla.org/WebExtensions), and the [globals project](https://github.com/sindresorhus/globals/pull/55).

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks. Please take a moment to read over our contribution guide to see how to properly submit this PR: http://eslint.org/docs/developer-guide/contributing/pull-requests

**Comment by bwinton** [comment]
Ah, thanks!  I saw that as I was clicking through the pull request, but it vanished before I could read it.

I don't know how to to test this change with the existing infrastructure, but if you can point me at the file that tests the other environments, I'll be happy to try and add a test for this in that style.

**Comment by ilyavolodin** [comment]
You can take a look at this pull request to see how to add unit tests for environments: https://github.com/eslint/eslint/pull/3875/files

**Comment by bwinton** [comment]
Ilya: Thank you!  Those were very helpful.  I _believe_ I've done everything required, but if you'ld like me to make any more changes, please let me know, and I'll be happy to.

**Comment by ilyavolodin** [comment]
LGTM. One more thing, have you signed our CLA? Our bot is sleeping on the job again, so I can't check:-)

**Comment by bwinton** [comment]
Yep!  (That was the first thing I did, after nzakas pointed me to the contributing doc.)

**Pull request merged**
