### PR TITLE
Fix: allow semi as braceless body of statements (fixes #6386)

### LINKED ISSUE #6386: no-extra-semi does not handle empty if blocks
**What version of ESLint are you using?**

`2.12.0`

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

`{"extends": "eslint:recommended"}
`

**What did you do? Please include the actual source code causing the issue.**

```js
if(arr[0] === "1");
else if(arr[0] === "2"){
	...
}
```

**What did you expect to happen?**

Nothing.

**What actually happened? Please include the actual, raw output from ESLint.**

```
  31:48  error  Unnecessary semicolon  no-extra-semi
```

Also, when using `--fix`, the semicolon is removed, which leads to invalid code.

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by platinumazure** [comment]
I missed the discussion- why avoid flagging the semicolon, rather than just avoiding a bad auto-fix?

**Comment by ilyavolodin** [comment]
@platinumazure Cause if IfStatement doesn't have body, semi is required. And we are currently flagging it as extra.

**Comment by platinumazure** [comment]
Ah, right. For some reason I thought we were recommending the use of empty
blocks there- thanks for the clarification.

**Comment by mysticatea** [comment]
Thank you @alberto !

I'd like to fix similar issues in this, I guess `WithStatement` and `LabelledStatement` have the same problem.

**Comment by alberto** [comment]
Makes sense. I'll add those too.

**Comment by mysticatea** [comment]
LGTM, thank you!

**Pull request merged**
