### PR TITLE
Fix: rewrite overwriting logic of config

### LINKED ISSUE #3915: globalReturn is not reset when node environment is set to false
Using ESLint v1.5.0 and the following directory structure:

```
..
.eslintrc
src
 - .eslintrc
 - test.js
```

If the top level .eslintrc file has
```
{
  "env": { "node": true }
}
```
and the one inside `src` directory has
```
{
  "env": { "node": false, "browser": true }
}
```
For test.js file environments correctly cascade to `node: false` and `browser: true`, however, `globalReturn` ecmaFeature is still set to `true`. I don't think that's correct behavior. This can be reproduced by using `no-unused-vars`, declaring unused variable inside test.js and then adding `exported` comment with variable name. ESLint will report variable still being unused (will file another issue for this #3916). @mysticatea could you take a look? I think this is related to the fix for #3735 since this is behaving correctly in ESLint v1.4.0

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26904523-globalreturn-is-not-reset-when-node-environment-is-set-to-false?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #3915 

I rewrite config's inheritance and overwriting logic.
The old way could not handle overwriting of environments with `false`.
The new way stores history of overwriting for each `globals` and `ecmaFeatures`. Then it selects the correct value from final `env` and history.
I added a class `CascadingConfigData` to manages history of overwriting.

----

This is a little bit faster than before.

**Before:**

```
CPU Speed is 3392 with multiplier 7500000
Performance Run #1:  3486.3081ms
Performance Run #2:  3462.279093ms
Performance Run #3:  3428.105712ms
Performance Run #4:  3418.651979ms
Performance Run #5:  3418.054008ms
Performance budget exceeded: 3428.105712ms (limit: 2211.0849056603774ms)
```

**After:**

```
CPU Speed is 3392 with multiplier 7500000
Performance Run #1:  3495.445491ms
Performance Run #2:  3406.694375ms
Performance Run #3:  3398.599885ms
Performance Run #4:  3395.976783ms
Performance Run #5:  3395.71085ms
Performance budget exceeded: 3398.599885ms (limit: 2211.0849056603774ms)
```

### CODE REVIEW

**Comment by mysticatea** [comment]
I had forgotten about `/* eslint-env` comments...

**Comment by nzakas** [comment]
Yikes! This is a pretty massive change. In the future, before you rewrite something this large, please talk about what you're planning on doing.

It's going to take me a while to review this.

**Comment by mysticatea** [comment]
I'm sorry. An intention of [this comment](https://github.com/eslint/eslint/issues/3915#issuecomment-142766786) was to make a large change. I will write more details in the future.

The core idea of this PR is [getSnapshot function](https://github.com/eslint/eslint/pull/3958/files#diff-af01dc6354b01e23c32eba0651e29428R228)
`CascadingConfigData` is a class for that.
`CascadingConfigData` instance exists for each config file (and shared config), the instances have tree structure.
And other changes are processes to make the tree structure of `CascadingConfigData`.

I will add a support of `/* eslint-env` comments to this PR later.
I will add a overload of `eslint.verify()` to accept `CascadingConfigData` instance in the argument `config`. `eslint.verify()` does exactly overwrite env with using `CascadingConfigData` if `config` is a `CascadingConfigData` instance. Otherwise, it does overwrite env as the same way as before.
Then I will make `CLIEngine` giving a `CascadingConfigData` instance to `eslint.verify()`.

**Comment by nzakas** [comment]
I think that's too much change to fix a bug. I'd like to see if there's a much smaller change to address this.

**Comment by mysticatea** [comment]
I don't have other idea yet.
I believe history of overwriting is needed to overwrite config correctly. My thinking cannot leave from there....

Now, yes, management of history is a large responsibility,  so I thought the responsibility should be extracted to a specialized class: `CascadingConfigData`.
This object manages history of overwriting as singly linked lists. And this resolves config at finally.
This class is isolated from file system.

`config.js` finds config files and makes `CascadingConfigData` from positional relationship of config files.

I considered the following patterns:

----

**src/.eslintrc**

```js
{
    "ecmaFeature": {"globalReturn": false}
}
```

**src/foo/.eslintrc**

```js
{
    "env": {"node": true}
}
```

* The result of `globalReturn` should be `true`.
  The way that resolves `env` content at finally cannot make this because existing `ecmaFeatures` is not overwritten. #3836. Now eslint resolves `env` content at each config and overwrites upper's. It makes correct in this case.

----

**src/.eslintrc**

```js
{
    "env": {"node": true}
}
```

**src/foo/.eslintrc**

```js
{
    "ecmaFeature": {"globalReturn": false}
}
```

* The result of `globalReturn` should be `false`.
  This is an opposite side of the previous pattern. The current way makes correct.

----

**src/.eslintrc**

```js
{
    "env": {"node": true, "commonjs": true}
}
```

**src/foo/.eslintrc**

```js
{
    "env": {"node": false}
}
```

* The result of `require` variable should exist.
  Such as `Buffer` should be removed, but `require` should not be removed. So we cannot remove `env` content merely. The current way cannot address this pattern correctly. But the previous way (to resolve `env` content at finally) can make correct.

----

**src/.eslintrc**

```js
{
    "ecmaFeature": {"globalReturn": true},
    "env": {"node": true}
}
```

**src/foo/.eslintrc**

```js
{
    "env": {"node": false}
}
```

* The result of `globalReturn` should be `true`.
  This is similar to the previous pattern.

**Comment by hsablonniere** [comment]
I didn't get into the details of the PR but we would really like to do this in our project ;-)

**Comment by nzakas** [comment]
I think we need to rethink this a bit. Closing for now.

**Pull request closed without merging**
