### PR TITLE
Fix: do not fail on unknown operators from custom parsers (fixes #10475)

### LINKED ISSUE #10475: Do not fail on unrecognized logical operators
ESLint throws an error when trying to use the [nullish coalescing operator](https://github.com/tc39/proposal-nullish-coalescing) (`foo ?? bar`):

```
Error: unreachable
      at CodePathState.popChoiceContext (node_modules/eslint/lib/code-path-analysis/code-path-state.js:444:23)
      at processCodePathToExit (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:434:19)
      at CodePathAnalyzer.leaveNode (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:627:9)
      at Traverser.leave (node_modules/eslint/lib/linter.js:959:32)
      at Traverser.__execute (node_modules/estraverse/estraverse.js:397:31)
      at Traverser.traverse (node_modules/estraverse/estraverse.js:491:28)
      at Traverser.traverse (node_modules/eslint/lib/util/traverser.js:31:22)
      at Linter._verifyWithoutProcessors (node_modules/eslint/lib/linter.js:953:19)
      at preprocess.map.textBlock (node_modules/eslint/lib/linter.js:994:35)
      at Array.map (<anonymous>)
      at Linter.verify (node_modules/eslint/lib/linter.js:993:42)
      ...
```

That operator is part of a proposal in Stage 1, so according to the ESLint policy it doesn't have official support, but it shouldn't fail when it's present in the AST (from a different parser).

This problem happens for any operator other than `&&` and `||` in a logical expression, which are explicitly handled in the code.

This is just to track the discussion we're having in #10399. 

**Affected ESLint versions**: v4.19.1 (latest stable) and v5.0.0-rc.0 (latest).

### PR DESCRIPTION
**Pull request by rubennorte**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[X] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

I modified the code path analysis code to explicitly check the operator of the logical expressions in order to create new code paths. This will allow users to use a custom parser that adds a new operator (like `??`) without breaking the code. The error users see now is

```
Error: unreachable
      at CodePathState.popChoiceContext (node_modules/eslint/lib/code-path-analysis/code-path-state.js:444:23)
      at processCodePathToExit (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:434:19)
      at CodePathAnalyzer.leaveNode (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:627:9)
      at Traverser.leave (node_modules/eslint/lib/linter.js:959:32)
      at Traverser.__execute (node_modules/estraverse/estraverse.js:397:31)
      at Traverser.traverse (node_modules/estraverse/estraverse.js:491:28)
      at Traverser.traverse (node_modules/eslint/lib/util/traverser.js:31:22)
      at Linter._verifyWithoutProcessors (node_modules/eslint/lib/linter.js:953:19)
      at preprocess.map.textBlock (node_modules/eslint/lib/linter.js:994:35)
      at Array.map (<anonymous>)
      at Linter.verify (node_modules/eslint/lib/linter.js:993:42)
      ...
```

Fixes #10475 (see for more details) and provides a more generic solution to #10399 (which is against the ESLint policy about providing support for pre-Stage 3 proposals).

### CODE REVIEW

**Comment by platinumazure** [comment]
This approach looks promising, thanks for writing this up! Hopefully the rest of the team (and probably the TSC-- I assume the TSC will need to review) will agree.

**Comment by rubennorte** [comment]
@not-an-aardvark I considered merging them into a "logical" kind, but this required less modifications in the code and looked cleaner (as it didn't need to modify anything inside code-path-state).

**Comment by mysticatea** [comment]
Thank you for this PR.

LGTM.

But I have a concern: the type of token's `type` property must be a string ([AST spec](https://eslint.org/docs/developer-guide/working-with-plugins#the-ast-specification)). It's better if the added test uses a valid AST.

**Comment by rubennorte** [comment]
@mysticatea I just copied the output from babel-eslint (the version is in the file comment). If that's wrong I think we should fix it there.

Also the goal of this PR is to allow us to use new operators with babel-eslint (or other custom parsers), so it seems better to directly use the same output it provides.

**Comment by mysticatea** [comment]
I'd like to fix it by hand to adhere the AST spec; to "Punctuator" or something like.

**Comment by rubennorte** [comment]
I finally committed an intermediate solution (update the AST with the fix I sent to babel-eslint).

Do you think we can have this merged soon? Also, would it be possible to cut a v4.20.0 release with this?

**Comment by not-an-aardvark** [comment]
To answer your question about release timing: we have scheduled releases every 2 weeks, and our [next release](https://github.com/eslint/eslint/issues/10458) is scheduled for next Friday, June 22nd. That release is expected to be the first stable release of ESLint v5.0. We've been doing prereleases for ESLint v5.0 for the last couple months, and unfortunately we don't really have the manpower to maintain multiple release branches simultaneously, so we only backport changes if a critical bug is found.

That said, since the upcoming release is expected to be stable, it should be possible to use it relatively soon.

**Comment by rubennorte** [comment]
That seems reasonable. I'll test the last prerelease in Facebook to upgrade it as soon as this gets merged. If I can do something to accelerate the merge of this PR, please let me know. Thanks!

**Comment by platinumazure** [comment]
After some discussion with other team members, I've been persuaded that this is a bug fix, not an enhancement. Relabeling accordingly. Sorry for the inconvenience/confusion!

**Comment by rubennorte** [comment]
@platinumazure that's cool. Do you need me to make any further changes in order to get this merged and included in the next release?

**Comment by platinumazure** [comment]
@rubennorte Not from my perspective. I just want to leave this open a bit longer so more team members could review and potentially request changes. Whether we merge today or next week, it will definitely make next week's release (barring a catastrophe).

**Comment by not-an-aardvark** [comment]
Thanks!

**Pull request merged**
