### PR TITLE
docs: Update link for schema examples

### PR DESCRIPTION
**Pull request by Svetzayats**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Link to examples of JSON Schema led to 404. Updated to actual link. 

#### Is there anything you'd like reviewers to focus on?
No.

### CODE REVIEW

**Comment by Tanujkanti4441** [comment]
Hi @Svetzayats, thanks for the PR a good catch, can you also sign CLA.

**Comment by Svetzayats** [comment]
I signed CLA, thank you for the reminder. Is there anything else needed to do?

**Comment by Tanujkanti4441** [comment]
> Hi, @Tanujkanti4441 , I signed CLA, thank you for the reminder. Is there anything else needed to do?

The change looks good to me,  if there will anything we will let you know through a change request.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
