### PR TITLE
Fix: multiline-comment-style autofix (fixes #9485)

### LINKED ISSUE #9485: bug: multiline-comment-style incorrectly autofix (option separate-lines).
**Tell us about your environment**

* **ESLint Version:**master

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
                "rules": {
                    "multiline-comment-style": [
                        2,
                        "separate-lines"
                    ]
                },


```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
/* foo
 bar */qux;
```

**What did you expect to happen?**
```js
// foo
// bar
qux;
```
**What actually happened? Please include the actual, raw output from ESLint.**
```js
// foo
// barqux;
```

### PR DESCRIPTION
**Pull request by gpiress**
Fix the autofix for multiline-comments with seperate-lines option.

Add test present in the issue description to avoid future regressions.

Remove old test that wasn't aligned with the rule description.

### CODE REVIEW

**Comment by gpiress** [comment]
@Aladdin-ADD please review to see if it properly fixes the issue #9485

**Comment by Aladdin-ADD** [comment]
@gpiress  I'm terribly sorry!  ❤️

seems I missed this test, and it seems working as intended.

**Comment by gpiress** [comment]
@Aladdin-ADD no worries!

If the test that is in the codebase is the expected behavior, should the docs mention it somehow? Reading the docs and the options for this rule, it isn't obvious to me that it was the desired behavior.

**Comment by Aladdin-ADD** [comment]
sure! mind create a PR to improve the docs?

**Comment by gpiress** [comment]
I can create a PR to improve this, for sure! One thing that I'd like to see but I don't know now is if there's a reason this is the expected behavior when `seperate-lines` is set. We can talk about it when I create the PR for it.

**Pull request closed without merging**
