### PR TITLE
Update: Add semi-spacing fixer for semicolon only line 

### PR DESCRIPTION
**Pull request by inuscript**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[x] Add autofixing to a rule

**What rule do you want to change?**

* semi-spacing

**Does this change cause the rule to produce more or fewer warnings?**

Yes, warning when code has semicolon only line.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New default behavior.

**Please provide some example code that this change will affect:**

```js
var a = b
;
var c = d;
```

and `--fix` to

```js
var a = b;
var c = d;
```

**What does the rule currently do for this code?**

Not warning and fixing.

**What will the rule do after it's changed?**

Warn semicolon only line.

**What changes did you make? (Give an overview)**

Currently, semi-spacing is ignore isolated semicolon only line and I want fix this (like [comma-style](http://eslint.org/docs/rules/comma-style) )

**Is there anything you'd like reviewers to focus on?**

My purpose(want) is fix isolated semicolon line, and I try add this fixing to `semi-spacing`. 
But this may more appropriate rule or may create new rule.

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks for the PR. I think this use case is outside of what the semi-spacing rule is intended to address, but let's see what others on the team think.

**Comment by vitorbal** [comment]
I tend to agree. I think this rule would make a great custom rule, but It doesn't belong in the core, in my opinion.

**Comment by ilyavolodin** [comment]
It looks like the rule completely ignores line-break right now. More than that, if you have semi-colon on a separate line, with `{ "before": true }` configuration, it looks like currently it's impossible to make the code not error on that line. Even if the semi-colon is not alone. The following example will always show and error and is not fixable:

```js
/* eslint semi-spacing: ["error", { "before": true, "after": false }] */
foo()
; [].reduce()
```

So I think we have to fix that behavior somehow. Once it fixed, we might consider adding a fixer for it (depending on how it's fixed, I guess).

**Comment by kaicataldo** [comment]
I agree with the comments from the rest of the team. Thanks for the contribution regardless.

**Comment by not-an-aardvark** [comment]
Closing this since there seems to be consensus that this should not be added to core. Thanks anyway for the contribution!

**Comment by inuscript** [comment]
Thank you for review. I understand.

But I have a question (associate with this). 
I found different result on run semi always and never.

```js
// before
var a = b
;
var c = d;
```

```
# run semi rule never => always
$ eslint *.js --fix --rule 'semi: [2, never]' 
$ eslint *.js --fix --rule 'semi: [2, always]'
```

And result to

```js
// after
var a = b;

var c = d;
```

I think this may not prefered behavior.

Is this valid behavior?

**Pull request closed without merging**
