### PR TITLE
Docs: Clarify JSX option usage

### PR DESCRIPTION
**Pull request by richardcrichardc**
Make it clear that you need to do more than just enable JSX to get useful linting when JSX is used.

### CODE REVIEW

**Comment by richardcrichardc** [comment]
Your bots (or git) are too smart for me. I have removed the offending whitespace and updated the name of the pull request.

**Comment by platinumazure** [comment]
Thanks to Github's squash-merge functionality, we should be able to take care of minor issues with the commit message. Hopefully someone will review and merge this soon (or provide feedback if there are issues with the proposed changes). Thanks for the PR!

**Comment by ilyavolodin** [comment]
This is not really a correct change. JSX doesn't automatically mean React. There are other frameworks  that use JSX, and not all of them have issues that React has (specifically about `no-unused-vars`). So I don't think this is the right thing to merge in.

**Comment by richardcrichardc** [comment]
@ilyavolodin Feel free to edit/reprase. I have only used JSX with react and only have the vague notion it can be used with other tools - I think I am pretty typical in this respect.

My pain point was I spent two plus hours figuring out how to get eslint working correctly with JSX+React. The only reference I found in the docs was in a changelog from last year (which I now cannot find).  I think it is a fair assumption to think enabling JSX should make rules work for typical use cases of JSX.

**Comment by lo1tuma** [comment]
This is already explained [in the FAQs](https://github.com/eslint/eslint#does-eslint-support-jsx) but it is not mentioned on eslint.org.

**Comment by richardcrichardc** [comment]
Very easy to miss the FAQ's when they are not in the searchable documentation. @ilyavolodin I have replaced the text with the wording from the FAQ, which is clearer about the difference between React.js and JSX.

**Comment by ilyavolodin** [comment]
Sounds good. Could you sign jQuery CLA please?

**Comment by richardcrichardc** [comment]
Do you mean eslint CLA - http://eslint.org/cla/ ?

**Comment by platinumazure** [comment]
No, we've recently been welcomed by the jQuery Foundation and so we now use their CLA. We should probably take down the ESLint CLA page. I'll open an issue on eslint.github.io. Thanks for bringing this to our attention!

**Comment by richardcrichardc** [comment]
So I should fill in the form on this page? 
https://contribute.jquery.org/CLA/

**Comment by platinumazure** [comment]
Yes please- thanks a lot!

**Pull request merged**
