### PR TITLE
Fix: one-var exception for ForStatement.init (fixes #2505)

### LINKED ISSUE #2505: `one-var": [2, { initialized: "never" }]` raised when multiple declarations exist in for loop
This is related to #2342.

I want to use the rule `"one-var": [2, { initialized: "never" }]`. It mostly works correctly, except it complains about:

```js
var arr = [1, 2, 3];
for (var i = 0, len = arr.length; i < len; i++) {
  // ...
}
```

With this error: `Split initialized 'var' declarations into multiple statements.`

Is there some way to ignore statements inside for loops? I don't mind multiple declarations in there, but I do want to prevent this:

```js
var i = 0, j = 5, k = 99;
```

### PR DESCRIPTION
**Pull request by btmills**

### CODE REVIEW

**Comment by lo1tuma** [comment]
I think your change would also allow the following when setting `one-var` to `"always"`:


```js
var foo;

for (var i = 0;;) {}
```

Is this intended?

Personally I want to disallow var declarations in for statements, thats why I’ve set `one-var` to `"always"`.

**Comment by btmills** [comment]
Ah no, this was inspired by [#2505 (comment)](https://github.com/eslint/eslint/issues/2505#issuecomment-101082858), but clearly I need a more nuanced filter to check specifically for that case. Will update.

**Comment by btmills** [comment]
This should be more specific now, and I added another test to be sure.

**Comment by nzakas** [comment]
Lgtm

**Pull request merged**
