### PR TITLE
Chore: Adopt `eslint-plugin/prefer-message-ids` rule internally

### PR DESCRIPTION
**Pull request by bmish**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[X] Other, please explain:

#### What changes did you make? (Give an overview)

The public rule [eslint-plugin/prefer-message-ids](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/prefer-message-ids.md) is more robust than our internal version, and it's also valuable for us to dogfood this public rule as it's the same one that third-party plugin authors will use. So this PR deletes our custom version and switches us to the public rule for internal usage.

Follow-up to https://github.com/eslint/eslint/pull/14823.

CC: @aladdin-add

#### Is there anything you'd like reviewers to focus on?

No.

### CODE REVIEW

**Review by aladdin-add — APPROVED** [review]
👍

**Review by mdjermanovic — COMMENTED** [review]
It makes sense to enable `eslint-plugin/prefer-message-ids`, as it catches some things that `internal-rules/consistent-meta-messages` doesn't (e.g., someone could define `meta.messages` but still mistakenly use `message` in `context.report()`).

However, it doesn't work for rules where `context` is passed to functions that eventually call `context.report()`, like [`no-duplicate-imports`](https://github.com/eslint/eslint/blob/8be8a36010145dfcd31cbdd4f781a91989e3b1bd/lib/rules/no-duplicate-imports.js#L176) or [`padding-lines-between-statements`](https://github.com/eslint/eslint/blob/8be8a36010145dfcd31cbdd4f781a91989e3b1bd/lib/rules/padding-line-between-statements.js#L244), so maybe we should use both the plugin rule and the internal rule?

**Comment by bmish** [comment]
It is true that we can't always detect all usages of `context.report` since it may be used inside helper functions. If we're worried about that, how about I update `eslint-plugin/prefer-message-ids` to also flag a violation when `meta.messages` is missing? That's a new rule I just wrote and I would much prefer to have one comprehensive rule rather than rely on two.

**Comment by mdjermanovic** [comment]
> If we're worried about that, how about I update `eslint-plugin/prefer-message-ids` to also flag a violation when `meta.messages` is missing? That's a new rule I just wrote and I would much prefer to have one comprehensive rule (covering both situations) rather than rely on two.

Makes sense to me :+1:

**Review by nzakas — APPROVED** [review]

**Review by nzakas — APPROVED** [review]

**Comment by bmish** [comment]
@mdjermanovic I have updated the rule to handle that case so this PR is ready to be merged :)

**Pull request merged**
