### PR TITLE
Fix: Proposed no-magic-numbers option: ignoreJSXNumbers (fixes #5348)

### LINKED ISSUE #5348: Proposed no-magic-numbers option: ignoreJSXNumbers
eslint version: 2.1.0

When using the `no-magic-numbers` rule, numbers that are placed inside of JSX props are caught by the rule. Example:
```javascript
<input maxLength={10} />
```
returns
```javascript
error  No magic number: 10   no-magic-numbers
```
Assigning numbers to props is similar to assigning them to variables, where the name of the prop makes the meaning explicit. In these cases the rule should be ignored. I propose a new option is added to this rule called `ignoreJSXNumbers`. This option would ignore any number that is defined as a JSX element property.

### PR DESCRIPTION
**Pull request by bsbeeks**

### CODE REVIEW

**Comment by nzakas** [comment]
LGTM

**Comment by nzakas** [comment]
Oops, can you update your commit summary to begin with "Update:"?

**Comment by bsbeeks** [comment]
Yep, making the change now...

**Comment by nzakas** [comment]
Thanks!

**Comment by mdebruijne** [comment]
Hi @bsbeeks, @nzakas; do you have on your ToDo to add the ignoreJSXNumbers option to the documentation?

https://github.com/eslint/eslint/blob/master/docs/rules/no-magic-numbers.md

**Comment by bsbeeks** [comment]
We decided to ignore single JSX numbers by default. So no ignoreJSXNumbers option, or documentation updates were needed.

**Comment by mdebruijne** [comment]
I didn't know that default behavior of rules are not documented. Good to know. Thanks for the information.

**Comment by BYK** [comment]
I think this should have been documented (and still should be). I also think we should have added this as an option. @eslint/eslint-team thoughts?

**Comment by BYK** [comment]
Also @mdebruijne, thanks for bringing this up!

**Comment by bsbeeks** [comment]
Happy to make any adjustments that the eslint team deems necessary. Let me know.

**Pull request merged**
