### PR TITLE
Fix: line-comment-position "above" string option now works (fixes #7100)

### LINKED ISSUE #7100: Faulty option parsing in line-comment-position
**Tell us about your environment**

* **ESLint Version:** 3.5.0
* **Node Version:** 6.5.0
* **npm Version:** 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

```yaml
rules:
  line-comment-position:
    - error
    - above
```

**What did you do? Please include the actual source code causing the issue.**

Linted the following file:

```js
// Meep
console.log("Meep");
```

**What did you expect to happen?**

For there not to be any linting errors.

**What actually happened? Please include the actual, raw output from ESLint.**

There was a linting error:

```
1:1  error  Expected comment to be beside code  line-comment-position
```

The cause of the problem is a typo [here](https://github.com/eslint/eslint/blob/6cfe5195caaa16c4e310d51ba54c6523444a47df/lib/rules/line-comment-position.js#L53). `typeof option` should be `typeof options`.

### PR DESCRIPTION
**Pull request by platinumazure**
**What is the purpose of this pull request? (put an "X" next to item)**

```
[ ] Documentation update
[x] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:
```

Re: bug report template: See issue #7100.

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- [x] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**

Added test case given in #7100, and fixed the typo in the rule.

**Is there anything you'd like reviewers to focus on?**

~~Not really, this should be pretty straightforward.~~

I do have a question about whether I should include test cases for things like `// jscs:disable` being beside code with "above" option. I don't know if that case makes sense inline, though (i.e., I know jscs:disable applies to the next line, but maybe there are other cases that should be tested).

### CODE REVIEW

**Comment by mysticatea** [comment]
LGTM but would like someone else to verify.

**Comment by platinumazure** [comment]
@mysticatea Thanks! I just came up with a question for reviewers after you reviewed-- sorry! The question is:

> I do have a question about whether I should include test cases for things like // jscs:disable being beside code with "above" option. I don't know if that case makes sense inline, though (i.e., I know jscs:disable applies to the next line, but maybe there are other cases that should be tested).

Please let me know if your opinion changes based on that question. Thanks!

**Comment by kaicataldo** [comment]
LGTM

**Comment by mysticatea** [comment]
LGTM since this PR addresses #7100. But it's always good if there are more tests.

**Comment by kaicataldo** [comment]
Thanks for contributing!

**Pull request merged**
