### PR TITLE
New: add no-dupe-ternary-expression (refs #13744)

### PR DESCRIPTION
**Pull request by GrayedFox**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

- [x] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))

**Please describe what the rule should do:**
This rule should detect duplicate ternary expressions (i.e. identical ternary alternate and consequent nodes).

**What category of rule is this? (place an "X" next to just one item)**

- [x] Warns about a potential error

**Provide 2-3 code examples that this rule will warn about:**

```js
        "const getFee = isMember => isMember ? 2.00 : 2.00;",
        "formula = condition && condition1 ? User.months * oldRate - User.fee : User.months * oldRate - User.fee",
        "condition1 ? foo() : condition2 ? bar() : condition3 ? baz() : baz()",
        "5 < 7 ? (5 < 6 ? false : false) : true"
```

**Why should this rule be included in ESLint (instead of a plugin)?**

It warns about a very likely problem that is applicable to any/all projects.

#### What changes did you make? (Give an overview)

- added docs explaining rule and limitations
- added tests
- added core rule logic

#### Is there anything you'd like reviewers to focus on?
The rule has been discussed [here](https://github.com/eslint/eslint/issues/13744).

The rule ended up being deceptively simple to write. If reviewers could please focus on the tests and whether they cover all edge cases that would be greatly appreciated.

This rule does **not** detect duplicate ternary conditions.

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Makes sense to me, identical alternate and consequent nodes is certainly an error in the code.

Not sure what would be the best name for this rule.

**Comment by anikethsaha** [comment]
> Not sure what would be the best name for this rule.

The current one make sense as well. Else we can have something like `no-dupe-ternary-branches` or something else

**Comment by GrayedFox** [comment]
Will likely turn this into a plug in over the next days - feel free to close if consensus has not been reached (any review is still of course very welcome!) 🙇🏾

**Comment by GrayedFox** [comment]
Closing in favour of the plugin 

https://www.npmjs.com/package/eslint-plugin-ternary

**Pull request closed without merging**
