### PR TITLE
chore: combine multiple RegEx replaces with one

### PR DESCRIPTION
**Pull request by thefourtheye**
**What issue does this pull request address?**

Performance improvement

**What changes did you make? (Give an overview)**

Combining two subsequent RegEx `replace`s with one `replace`.

**Is there anything you'd like reviewers to focus on?**

Yes, the RegEx.

### CODE REVIEW

**Comment by thefourtheye** [comment]
Okay. Signed the CLA now.

**Comment by ilyavolodin** [comment]
@thefourtheye Chore PRs require an open issue. Would you mind opening a new issue for this.

**Comment by thefourtheye** [comment]
@ilyavolodin Sure. PTAL at #6669

**Comment by ilyavolodin** [comment]
LGTM, but waiting another day for others to look

**Pull request merged**
