### PR TITLE
Fix: no-use-before-define false positive with exports (fixes #7858)

### LINKED ISSUE #7858: no-use-before-define false positive with binding exports
**Tell us about your environment**

* **ESLint Version:** 3.12.2
* **Node Version:** 7.2.0
* **npm Version:** (yarn) 0.18.1

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

```js
// too big, relevant part
module.exports = {
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module'
  },
  rules: {
    'no-use-before-define': ['error', {functions: false, classes: false}]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
export { group as default }
const group = new Set()
```

**What did you expect to happen?**

No warnings.

**What actually happened? Please include the actual, raw output from ESLint.**

```
   1:10  error  'group' was used before it was defined       no-use-before-define
```

---

Binding exports do not _read_ the variable, so they do not cause TDZ errors.

Note that, when circular imports are involved, it is possible to cause a TDZ error by accessing an export whose binding is still in TDZ, but that would happen regardless of the position of the `export` binding.

Also note that _only_ binding exports should not be errors. `export default` should error as it is a value*, not a binding:

```js
export default Group // ReferenceError
class Group {}
```

[*]: it is a binding when exporting `FunctionDeclaration` or `ClassDeclaration`, but those are already correctly handled, in the `export default` case, by the rule with the appropriate options.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (see https://github.com/eslint/eslint/issues/7858)

**What changes did you make? (Give an overview)**

This updates `no-use-before-define` to avoid reporting variables in `ExportNamedDeclaration` nodes.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

**Comment by platinumazure** [comment]
Should/can this be behind an option? Part of the point of this rule is to flag use before definition *even when we know the definition is hoisted*, so I wouldn't want to change the default behavior for export declarations unless it's actually impossible to put the export at the end. If it's possible to do it either way, I think this should be a new option.

**Comment by ilyavolodin** [comment]
Agree with @platinumazure I'm not sure this is a bug that needs fixing at all. Unless somebody can convince me, I'm not even sure that we need an option for this case.

**Comment by not-an-aardvark** [comment]
I have no strong opinions on the correct behavior here.

cc @Kovensky

**Comment by mysticatea** [comment]
Maybe this is useful to separate interface and implementations. For example:

<details><summary>Open an example</summary>

```js
//------------------------------------------------------------------------------
// Interface
//------------------------------------------------------------------------------

import foo from "foo"
import bar from "bar"

export { A, B, C }

//------------------------------------------------------------------------------
// Implementation
//------------------------------------------------------------------------------

class A {
    //
    // ... long implementations
    //
}

class B {
    //
    // ... long implementations
    //
}

class C {
    //
    // ... long implementations
    //
}
```

</details>

.

Developers can look at the head of the source code to check what this file exports. If they use IDE, probably they can jump to implementations by `ctrl+click` to know details. It may be one of good style.

If we add this behavior, I would prefer it behind options.

Though, I have no confidence myself if this is legal code or not...

**Comment by ilyavolodin** [comment]
@mysticatea I would say that in your example, it's better to separate `export` from `imports` and move `export` down to the bottom to make it clear what is provided as an output. However, if that's not the style that you want to use, I would say you should just disable this rule.

`no-use-before-define` is not a rule that prevents errors, it's a stylistic rule that makes it easy for people that are new to JS to understand existing code. If you are coming from languages like Java, C++ or C# you are used to declaring your variables before using them. That applies to `export` statements in my opinion.

**Comment by mysticatea** [comment]
> If you are coming from languages like Java, C++ or C# you are used to declaring your variables before using them. 

My example would be natural for C++er, I think. They often separate interface to header files from implementations. It's what my example is doing.

Also, `no-use-before-define` is not merely stylistic rule. The rule detects ReferenceErrors caused by TDZ. It's a rule which detects possible errors. I think bad if we must disable whole rule for apparent legal code.

**Comment by ilyavolodin** [comment]
Ok, fair enough. I do not have strong enough feeling about this to block it. Although I, most definitely, feel very strongly that this should not be a default behavior, and should be behind an option.

**Comment by mysticatea** [comment]
Thank you, @ilyavolodin .
I agree that this shouldn't be a default behavior.

**Comment by alberto** [comment]
Agree. There are already options for functions, classes and variables.

**Comment by not-an-aardvark** [comment]
Looks like there's consensus that this shouldn't be default behavior. I don't really feel strongly about adding an option, so I'll close this PR. If we want to add an option we can go through the normal issue-accepting process.

**Pull request closed without merging**
