### PR TITLE
Chore: enable object-curly-newline & object-property-newline.(fixes #9042)

### LINKED ISSUE #9042: Discussion: enable object-curly-newline on eslint codebase.
I found we have been inconsistent on this. what about enable this rule? and options to set?

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Other, please explain:

**What changes did you make? (Give an overview)**
enalbe object-curly-newline.(fixes #9042)

**Is there anything you'd like reviewers to focus on?**

Personally I see the fixed code looks a little strange:
```js
context.report({
  node, message, data: {
    name: node.name
  }
});
```
any thoughts?

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
>Personally I see the fixed code looks a little strange:
>```js
>context.report({
>  node, message, data: {
>    name: node.name
>  }
>});
>```
>any thoughts?

Personally, I prefer putting everything on a new line in that case:

```js
context.report({
  node,
  message,
  data: { name: node.name }
});
```

**Comment by Aladdin-ADD** [comment]
agree. is there a rule or option to enforce this? I thought `consistent: true` would fix it to something like you mentioned. @not-an-aardvark

**Comment by not-an-aardvark** [comment]
I think [`object-property-newline`](http://eslint.org/docs/rules/object-property-newline) enforces that.

**Comment by Aladdin-ADD** [comment]
what if I want to allow (all in one line):
```js
var foo = { key1: 1, key2: 2, key3: 3 };
```
and per property per line:
```js
var foo = {
  key1: 1,
  key2: 2,
  key3: 3,
};
```

just report **inconsistent properties** like this:
```js
var foo = {
  key1: 1, key2: 2,
  key3: 3
};
```

**Comment by not-an-aardvark** [comment]
Does the `allowMultiplePropertiesPerLine` option solve that?

**Comment by Aladdin-ADD** [comment]
no, it only allow multi-properties per line. and will not report error when being `inconsistent`. I think this can be an useful enhancement for many users.

**Comment by not-an-aardvark** [comment]
> oh, sorry, it does. I just missed something.

Yeah, the option name is a bit misleading :P

**Pull request merged**
