### PR TITLE
enableTypeSort

### PR DESCRIPTION
**Pull request by thepian**
New: sort-import enableTypeSort option will require imports to be grouped into package, path and css groups.

**What rule do you want to change?**

sort-imports

**Does this change cause the rule to produce more or fewer warnings?**

No, it is optional.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New option

**Please provide some example code that this change will affect:**

```js
import { themr } from 'react-css-themr';
import { Link } from 'react-router';
import React from 'react';

import { withI18n } from './../lib/i18n';

import iconStyles from './../../styles/shared/fontIcons.sass';

class Navigation extends React.Component {
```

**What does the rule currently do for this code?**

It makes the code look like

```js
import { themr } from 'react-css-themr';
import { Link } from 'react-router';
import { withI18n } from './../lib/i18n';
import React from 'react';
import iconStyles from './../../styles/shared/fontIcons.sass';

class Navigation extends React.Component {
```

**What will the rule do after it's changed?**

Separates out assets(not JS) and splits 3rd party from app source imports

**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Added an extra option to sort-imports for structuring blocks of packages, path imports and style imports

**Is there anything you'd like reviewers to focus on?**
Is this relevant for people in general, might be, anyway it's optional.

### CODE REVIEW

**Comment by platinumazure** [comment]
I'm a bit confused by the CSS business. How is this relevant for ESLint core?

**Comment by ilyavolodin** [comment]
Agree... I think sorting is fine, but CSS/LESS/SCSS doesn't belong in the core (I assume this is for webpack).

**Comment by nzakas** [comment]
@thepian in order for us to consider new rule options, you need to fill out the [template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md) mentioned in the PR description. Please do that and then we can circle back to review the proposal.

**Comment by thepian** [comment]
It makes sense to do something about the CSS extensions defaults. I suppose it would be anything that isn't `.js`. How about something like third block is assets(could also be templates or JSON) in general which could be files converted to JS or other ways to "import" such as webpack/jspm CSS import.

Should I open an issue and discuss things there instead?

**Comment by kaicataldo** [comment]
@thepian Thanks for the pull request and for filling out the template. Discussing here is fine unless you'd prefer to discuss in a separate issue.

I'm not against having alternative ways of sorting, but this proposal feels too opinionated to me. I'm actually not a huge fan of the none/all/single/multiple sorting the rule currently enforces, as I don't think that's a particularly helpful way of organizing modules. It also forces you to change the order when you change what is being imported even if the target module doesn't change, which feels like unnecessary noise in the diff.

I like the idea of having different sorting styles (with the ability to configure them), as this proposal suggests. The default `style` could be something like "number", with this proposal being "type".

If we're thinking along these lines, though, I would love to see more generic categories along the lines of:
 - `native` (native Node modules like `fs`, `path`)
 - `external` (package manager installed modules in `node_modules`)
 - `local` (modules within the project directory (*not* in `node_modules`)

I hadn't thought about alternative filetypes, but perhaps an option could be a regex that would enforce the sorting of imports that match the regex?

So configuration might look something like 
```
{
    sort-imports: ["error", { "style": "type", "order": ["native", "external", "local", "\.css$",  "\.mustache$"] }]
}
```

**Comment by thepian** [comment]
Personally I found the whole sorting to be problematic. We are doing it at my current project, and I'm not convinced of the tradeoff, but since I have working code it makes sense to put it somewhere in a useful form.

Alphabetic sorting for instance is also opinionated. What to do about casing. take this

import abc;
import React;
import windowing;

vs

import abc;
import windowing;
import React;

vs

import abc;
import windowing;
import React;

With ignoreCase only the first will be correct. Without ignoreCase only the third will be correct. However in JS the casing of the first letter has a special meaning so the middle one might also be what you're looking for.

I take the feedback to be nice PR, but needs more thought.

**Comment by kaicataldo** [comment]
@thepian What do you think of what I proposed?

**Comment by thepian** [comment]
I need to rewrite some things, will reopen when I've had time to rework

**Pull request closed without merging**
