### PR TITLE
 Build: Fix path related failures on Windows in tests

### LINKED ISSUE #4061: Path related failures on Windows when running tests
When running `npm test` on Windows, I get the following errors:

```
  1) CLIEngine executeOnFiles() should return a warning when an explicitly given file is ignored:
     AssertionError: expected 'C:\\tmp\\eslint\\fixtures\\passing.js' to equal '\\tmp\\eslint\\fixtures\\passing.js'
      at Context.<anonymous> (C:\Users\BYK\Documents\Projects\eslint\eslint\tests\lib\cli-engine.js:532:20)

  2) Config findLocalConfigFiles() should return the path when an .eslintrc file is found:
     AssertionError: expected 'C:\\tmp\\eslint\\fixtures\\config-hierarchy\\broken\\.eslintrc' to equal '\\tmp\\eslint\\fixtures\\config-hierarchy\\broken\\.eslintrc'
      at Context.<anonymous> (C:\Users\BYK\Documents\Projects\eslint\eslint\tests\lib\config.js:115:20)

  3) Config findLocalConfigFiles() should return the path when a package.json file is found:
     AssertionError: expected 'C:\\tmp\\eslint\\fixtures\\config-hierarchy\\broken\\package.json' to equal '\\tmp\\eslint\\fixtures\\config-hierarchy\\broken\\package.json'
```

This is happening on latest master with Node 4.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27200159-path-related-failures-on-windows-when-running-tests?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BYK**
Fixes #4061.

### CODE REVIEW

**Comment by gyandeeps** [comment]
LGTM.
Do we want to make the commit message to start with "Build:" since this doesn't have any impact to the consumers of eslint?

**Comment by BYK** [comment]
>Do we want to make the commit message to start with "Build:" since this doesn't have any impact on the consumers of eslint?

Makes sense to me. Will leave the decision to you or @nzakas though.

**Comment by gyandeeps** [comment]
Sounds good @BYK

**Comment by BYK** [comment]
@gyandeeps updated the commit message.

**Comment by nzakas** [comment]
Lgtm

**Pull request merged**
