### PR TITLE
Update: Require JSDoc comments only on exported properties (fixes #7812)

### LINKED ISSUE #7812: Proposal: JSDoc only on exported nodes
**What rule do you want to change?**

`require-jsdoc` - [link](http://eslint.org/docs/rules/require-jsdoc)

Support making a rule so that the ESLinters for JSDocs are only applied on items which are going to leave the current source file ( and thus would be visible outside of the current scope. )

**Does this change cause the rule to produce more or fewer warnings?**

It would add an option to produce fewer warnings.

**How will the change be implemented? (New option, new default behavior, etc.)?**

There could be a `scope` attribute to require-jsdoc which allows you to define whether to apply the rules to all nodes. Or to only ones which will be available outside of it's file.

```json
{
    "require-jsdoc": ["error", {
       "scope": "all" || "exported",
        "require": {
            "FunctionDeclaration": true,
            "MethodDefinition": false,
            "ClassDeclaration": false,
            "ArrowFunctionExpression": false
        }
    }]
}

```

**Please provide some example code that this change will affect:**

for Modern: `import/export`

```js
export class MyThing {}
export function simpleFunction(one, two) {}
```

For the `require` style, something like this

```js
module.exports = class Runner extends EventEmitter {}

module.exports.jestChildProcessWithArgs = (workspace: ProjectWorkspace, args: Array<string>): ChildProcess => {}

```

So for some example code:

```js

var foo = (test) => {
    return test + 10;
}

/**
 * It returns 10
 */
export class Test{
    /**
    * returns the date
    */
    getDate(){}
}
```

**What does the rule currently do for this code?**

At the moment all JSDoc checks are applied wholesale throughout your source code. Meaning even internal functions, or test helper functions require comprehensive comments. So this would raise errors for `foo` but not `test`.

**What will the rule do after it's changed?**

With the scope as `exported` then the code above would not produce any errors.

### PR DESCRIPTION
**Pull request by david-mitchell**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #7812

**What changes did you make? (Give an overview)**

I pulled down #7867 (which had been abandoned) and brought it closer to completion. I haven't yet updated the documentation for the rule, but I think that this may be otherwise good to go.

**Is there anything you'd like reviewers to focus on?**

This is my first attempted contribution to eslint, so please treat it with a high degree of scrutiny.

### CODE REVIEW

**Comment by kaicataldo** [comment]
It looks like the original issue regarding this was closed. Do we want to re-evaluate this here, or just treat it as accepted since the original issue was accepted?

**Comment by david-mitchell** [comment]
I’m not quite sure what re-evaluation would be necessary. I thought the final proposal was pretty good—it only fizzled because the original developer didn’t have time to work on it.

**Comment by nzakas** [comment]
Thanks for the pull request. As of yesterday, we have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. All JSDoc features are now deprecated and we won't be fixing bugs or making any further improvements to those features.

We are recommending that people transition over to use the [`eslint-plugin-jsdoc`](https://github.com/gajus/eslint-plugin-jsdoc) plugin instead of the built-in rules in ESLint.

As a reminder, the work you've put into this pull request can still be used in a custom rule that you publish in your own plugin if it's something you need for your own projects.

Thanks for understanding and we apologize for any inconvenience.

**Comment by dclaze** [comment]
+1 for a rule only requiring JSDoc for exported functions **ONLY**. This is important for our team, since we want to avoid unnecessary/redundant comments on well named private functions.

Does anyone know if there is an equivalent request for this behavior in the recommended 
[https://github.com/gajus/eslint-plugin-jsdoc](eslint-plugin-jsdoc) package?

**Comment by platinumazure** [comment]
@dclaze Hard to say.

https://github.com/gajus/eslint-plugin-jsdoc/issues/162 shows a request for adding require-jsdoc to eslint-plugin-jsdoc, so it's not present at the moment to be modified. Not sure if it's best to jump on that issue or to create a new issue. But it's probably a good idea to port the rule over at some point.

**Pull request closed without merging**
