### PR TITLE
Docs: Clarified that core PRs require issue in maintainer guide

### PR DESCRIPTION
**Pull request by platinumazure**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain: Maintainer guide update

**What changes did you make? (Give an overview)**

Added a note to maintainer guide that core PRs require an issue.

**Is there anything you'd like reviewers to focus on?**

Not really. Like my last PR to this file, the goal is to document de facto standards rather than make a substantive change to those standards.

Applying "tsc agenda" label for now, though in theory this could be approved by a majority of TSC here.

Apologies for not including this in my last PR-- I had made the commit but forgot to push it.

### CODE REVIEW

**Comment by platinumazure** [comment]
**TSC Summary:** We relaxed our requirement about PRs needing an issue and only apply it to PRs that make core changes. This change updates the Maintainer Guide to provide a corollary for this requirement by encouraging team members to check that core PRs have issues.

**TSC Question:** Should this change be applied?

**Comment by not-an-aardvark** [comment]
Personally I don't think this needs to go on the TSC agenda given that it's just summarizing a policy that's already established elsewhere. But I have no objection to putting it on the agenda if you think it should be discussed.

**Comment by platinumazure** [comment]
@not-an-aardvark My take is that anything remotely representing official team policy needs to be approved by TSC. Like pretty much everything else, that can be done via TSC meeting or via TSC coming to consensus on the issue itself. The "tsc agenda" label is so that the TSC meeting will definitely cover this if it hasn't been approved before then.

In particular, I don't specifically believe that a TSC meeting is *required*, so we are in agreement there. But I'm just trying to afford TSC an opportunity to review.

**Comment by not-an-aardvark** [comment]
I wonder if we should have a `tsc-review` label to distinguish between those two categories -- where `tsc-agenda` is "things that should be discussed at the TSC meeting", and `tsc-review` is "things that the TSC should take a look at, and discuss at the meeting eventually if consensus isn't reached".

Anyway, the general labelling policy is off-topic for this PR, so we don't have to have this discussion here.

**Pull request merged**
