### PR TITLE
Chore: Adopt `eslint-plugin/require-meta-docs-description` internally

### PR DESCRIPTION
**Pull request by bmish**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[X] Other, please explain:

**What changes did you make? (Give an overview)**

This PR replaces the `internal-rules/consistent-docs-description` lint rule with [eslint-plugin/require-meta-docs-description](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/require-meta-docs-description.md). Why?

1. The replacement rule has identical behavior.
2. The replacement rule is more generic.
3. The replacement rule can be used by any eslint plugin.
4. This allows us to reduce the amount of code in eslint.

**Is there anything you'd like reviewers to focus on?**

Feel free to double-check that the replacement rule has the same behavior as the deleted rule.

### CODE REVIEW

**Comment by kaicataldo** [comment]
I'm not sure this is the right course of action since I could see us wanting to reserve the right to easily validate internal rules differently than custom plugin rules.

**Comment by bmish** [comment]
@kaicataldo I hear that. But I would note that:

1. eslint is already using all of the other recommended rules from [eslint-plugin-eslint-plugin](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin) (@not-an-aardvark added it originally)
2. I specifically wrote [eslint-plugin/require-meta-docs-description](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/require-meta-docs-description.md) to match eslint's desired behavior
3. [eslint-plugin/require-meta-docs-description](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/require-meta-docs-description.md) provides a `pattern` option allowing full customization of the regexp that rule descriptions should match

**Comment by kaicataldo** [comment]
Thanks for providing more context around that. Your reasoning makes sense to me!

**Comment by platinumazure** [comment]
@kaicataldo Just want to make sure your concerns around merging this have been addressed-- if so, this can probably be merged. Thanks!

**Comment by kaicataldo** [comment]
Thanks for contributing to ESLint!

**Pull request merged**
