### PR TITLE
Chore: Add tests for false positive in `newline-before-return` (refs #6090)

### PR DESCRIPTION
**Pull request by zxqfox**
Just additional tests for false positive.

### CODE REVIEW

**Comment by kaicataldo** [comment]
I wonder if we should change the name - it wasn't really a false positive for us, as the user reporting the false positive was using babel-eslint and it was determined that the bug is in the Babylon parser.

Also curious about the tests - they don't actually cover the case reported in the issue (#6090). That being said, I'm all for more tests :D

**Comment by zxqfox** [comment]
Tests for cases reported in the issue (they fail with older version or espree) are on lines 82 and 83.
I've added the rest because I don't get why it even fails. Prob I shouldn't do it.

I think we should left at least tests for reported case. The rest are optional, of course.

**Comment by nzakas** [comment]
Let's keep the tests focused on the reported case.

**Comment by zxqfox** [comment]
I've left just the most important tests for reported case at my pov.

**Comment by kaicataldo** [comment]
LGTM

**Comment by zxqfox** [comment]
> I don't believe adding the assignment makes a difference.

For some reason with older espree there were a bug so these are another cases not covered before.

Just close if we don't want it ;-)

**Comment by nzakas** [comment]
@kaicataldo @zxqfox looks like this was left hanging, what do you want to do here?

**Comment by zxqfox** [comment]
@nzakas Just to add few test cases.

It was a bug in earlier version of espree, then @kaicataldo fixed it, and then user reported similar issue in babel-eslint. I didn't noticed it and added tests, catched the old bug in espree which was already fixed ;-)

I'd add these tests just to cover case for (let's say) testing with another parser but it's not necessary for espree so we can close it.

**Comment by kaicataldo** [comment]
I believe the current tests cover all the cases added except for https://github.com/eslint/eslint/pull/6093/files#diff-85b10dedd745849e5db16ee07aa5fedfR71. I think the empty block with the comment test is valuable, but I believe the other cases are already covered in the current test (they're the same test but with the function assigned to a variable).  If @zxqfox feels like these other cases should be added, I don't want to get in the way!

I still don't feel like these tests cover the scenario in the original issue (as I outlined above - see the 2nd half of my previous comment), which I thought was what we agreed on focusing on. Just some thoughts - never want to get in the way of adding more tests.

**Comment by nzakas** [comment]
@kaicataldo how about we close this PR, and you can submit the tests you think are important?

**Comment by kaicataldo** [comment]
Sorry, wasn't my intention to derail this PR. @nzakas - I can do that if @zxqfox is on board.

**Comment by kaicataldo** [comment]
I created a PR as @nzakas requested. I would really like to make sure @zxqfox reviews it though, to make sure he's on board with all this :)

**Comment by zxqfox** [comment]
Closing in favor #6273

**Pull request closed without merging**
