### PR TITLE
Docs: Revise contributor documentation on issue labels.

### PR DESCRIPTION
**Pull request by jrpool**
Made this more DRY and extended its coverage to previously missing but important
labels (like `accepted`, `evaluating`, and `blocked`) by referencing maintainer
doc instead of repeating. Reorganized labels by the questions they answer for
contributors. Incorporated bounty info into priority section. Some labels, like
`needs bikeshedding`, seem totally undocumented. Fixing that could be another task.

**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Revised issue-label and issue-priority documentation for contributors to provide a more friendly experience and decrease the risk of label documentation in multiple places getting out-of-sync.

**Is there anything you'd like reviewers to focus on?**
Whether I may have mischaracterized any label.

### CODE REVIEW

**Comment by platinumazure** [comment]
Thanks @jrpool for the contribution! I love this: this is definitely a step in the right direction. Focusing on questions a user might ask makes a ton of sense.

My only small reservation is whether we should be linking to the Maintainer Guide. It's public, sure, but it's not something we really expect users to have to read. If anything, I'm wondering if the Maintainer Guide should link to the Contributing docs (somewhere, not necessarily the page you're editing in this PR) since the meaning of labels definitely should be public knowledge.

Iterating further, I'm half wondering if we should have a Contributing Guide (more narrative flow, sometimes uses a question/answer approve) and Contributing Reference (more like documentation, documents nitty-gritty of labeling and public processes), and the Maintainer Guide and Contributing Guide can both point to the Contributing Reference as needed.

And now I'm way too far down the rabbit hole, so definitely take this with a grain of salt. :smile: At any rate, I think this change is definitely an improvement. If the rest of the team is okay with linking to the Maintainer Guide in this PR, I'm not going to oppose.

**Comment by jrpool** [comment]
1. Thanks for the comments, @platinumazure. I have further edited the text in response, to remove the apparent suggestion that the Maintainer Guide is essential reading for contributors.

2. I have been trying to follow the instructions for PRs, but I don’t know why this PR now also contains others’ commits changing two no-constant-condition files.

**Comment by platinumazure** [comment]
Maybe a bad rebase? Feel free to drop by our [Gitter chat](https://gitter.im/eslint/eslint) and hopefully someone can help you. 😄

**Comment by jrpool** [comment]
OK, thanks to @not-an-aardvark I have stripped this PR to just my own commits.

**Pull request merged**
