### PR TITLE
Chore: enable max-len.

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Other, please explain:

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

since we are using 4 spaces indent, it's very easy to exceed 120, I set max-len to 160 and ignore options to true.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Oh, could we please not enable this rule. I have it enabled on my code-base, and I absolutely hate it. I don't see the value in limiting the length of the string, but it creates a huge number of formatting inconsistencies the developers need to spend time fixing.

**Comment by platinumazure** [comment]
@ilyavolodin This PR enables the ignoreStrings option (and pretty much all ignore options). So strings don't have to be artificially broken up (unless the line is already too long even without the string, and in that case the string can go down a line). Am I missing something?

**Comment by ilyavolodin** [comment]
`max-len` rule take into account indentation. So in the deeply nested code, you have almost no space to write your statements. I don't know, I personally just really dislike this rule. If everyone else on the team wants it in - I'll adjust.

**Comment by not-an-aardvark** [comment]
I don't really feel strongly about enabling `max-len`. That said, I generally think it's good to replace style nitpicks with linting rules. (I think this PR was created as a result of https://github.com/eslint/eslint/pull/9389#discussion_r143841033.)

If the `max-len` rule has ergonomic issues that are preventing us from using it, we might also want to examine whether we can fix those issues to make it easier for other users to use it.

**Comment by platinumazure** [comment]
Deeply nested code also probably could/should be refactored into functions. 😀 But I don't strongly mind whether we turn this on or not.

**Comment by ilyavolodin** [comment]
I just know that I've had max-len enabled on my work project for a year now, and I finally gave up and disabled it few days ago, cause I couldn't force myself to constantly correct my code when it's perfectly readable as is. So it's a personal thing. As I said, if everyone else fills like we should enable it, I'll adjust (I've been doing it for over a year, so it's inconvenient but fine).

**Comment by Aladdin-ADD** [comment]
haha, I had the similar experience. so the config is as tolerant as possible. 
Actually we have abide by it -- there are only ~10 errors in the repo! no worries~ 😄

**Pull request merged**
