### PR TITLE
[WIP] Update: Adds the ability to scope require-jsdoc to exported properties

### LINKED ISSUE #7812: Proposal: JSDoc only on exported nodes
**What rule do you want to change?**

`require-jsdoc` - [link](http://eslint.org/docs/rules/require-jsdoc)

Support making a rule so that the ESLinters for JSDocs are only applied on items which are going to leave the current source file ( and thus would be visible outside of the current scope. )

**Does this change cause the rule to produce more or fewer warnings?**

It would add an option to produce fewer warnings.

**How will the change be implemented? (New option, new default behavior, etc.)?**

There could be a `scope` attribute to require-jsdoc which allows you to define whether to apply the rules to all nodes. Or to only ones which will be available outside of it's file.

```json
{
    "require-jsdoc": ["error", {
       "scope": "all" || "exported",
        "require": {
            "FunctionDeclaration": true,
            "MethodDefinition": false,
            "ClassDeclaration": false,
            "ArrowFunctionExpression": false
        }
    }]
}

```

**Please provide some example code that this change will affect:**

for Modern: `import/export`

```js
export class MyThing {}
export function simpleFunction(one, two) {}
```

For the `require` style, something like this

```js
module.exports = class Runner extends EventEmitter {}

module.exports.jestChildProcessWithArgs = (workspace: ProjectWorkspace, args: Array<string>): ChildProcess => {}

```

So for some example code:

```js

var foo = (test) => {
    return test + 10;
}

/**
 * It returns 10
 */
export class Test{
    /**
    * returns the date
    */
    getDate(){}
}
```

**What does the rule currently do for this code?**

At the moment all JSDoc checks are applied wholesale throughout your source code. Meaning even internal functions, or test helper functions require comprehensive comments. So this would raise errors for `foo` but not `test`.

**What will the rule do after it's changed?**

With the scope as `exported` then the code above would not produce any errors.

### PR DESCRIPTION
**Pull request by orta**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #7812

**What changes did you make? (Give an overview)**

This is a WIP PR, I mainly looked at a few of the tests, will add some more and do force-pushes to this commit. Then I will ping @nzakas 👍 

**Is there anything you'd like reviewers to focus on?**

Nothing so far.

### CODE REVIEW

**Comment by nzakas** [comment]
@orta are you still working on this?

**Comment by vitorbal** [comment]
It would be really awesome to see this change released! @orta let us know if you need some help with anything. You can also drop by our [Gitter chat](https://gitter.im/eslint/eslint) if you prefer! :)

**Comment by orta** [comment]
Sorry, I've been finding it hard to find time to work on this on during work hours, so it's taking longer than I expected. 

One thing that seems tricky is that I need to figure out how to either look back up the AST from the current injection point to determine if it's an exported node tree, or to hook in at a new point to go down the AST to denote where that _could_ start.

**Comment by kaicataldo** [comment]
@orta Sorry for taking a while to get back to you. Nodes have a `parent` property that you can use to iterate up the AST. I think you can start from the nodes that the rule currently checks, iterate up the tree and, if they are exported, check the nodes.

**Comment by orta** [comment]
Alright - yeah, that makes a lot of sense, the source code is covered in `.parent`. I really should have noticed that 👍 

Alright, so this will now recurse up the AST until it hits either an `export` or `export default`. E.g. something like 

```js
/** OK */
export class Thing {
  constructor() {}
}
```

Would raise an issue on the  constructor if `MethodDefinition` is true 👍

**Comment by kaicataldo** [comment]
@orta Are you sure we that we want to do a recursive check? What about the following situation:

```js
export default function() {
  function thing() {} // This function isn't exported but I think it will warn with the current logic, right?
  thing();
}
```

**Comment by orta** [comment]
Hrm, yeah that makes sense, I was only thinking about functions on classes. I think that makes sense. Will have to figure out some of the edge cases 👍

**Comment by gyandeeps** [comment]
@orta just checking in, are you still working on this?

**Comment by kaicataldo** [comment]
@orta One more friendly ping.

**Comment by kaicataldo** [comment]
Thanks so much for working on this. I'm going to close this since the author hasn't responded since February, but please feel free to reopen a PR at any time. We really appreciate your contribution regardless.

**Comment by igor-savin-ht** [comment]
@kaicataldo I think I can try to finish the work that was started here, what are the outstanding issues before this can be merged?

**Pull request closed without merging**
