### PR TITLE
fix: allow implicit undefined return in `no-constructor-return`

### LINKED ISSUE #18486: Bug: possible `no-constructor-return` false negative with nested blocks
### Environment

https://eslint.org/play/#eyJ0ZXh0IjoiY2xhc3MgQSB7IGNvbnN0cnVjdG9yKCkgeyByZXR1cm4gfSB9XG5jbGFzcyBCIHsgY29uc3RydWN0b3IoKSB7IHsgcmV0dXJuIH0gfSB9Iiwib3B0aW9ucyI6eyJydWxlcyI6eyJuby1jb25zdHJ1Y3Rvci1yZXR1cm4iOlsiZXJyb3IiXX0sImxhbmd1YWdlT3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19

### What parser are you using?

Default (Espree)

### What did you do?

Run this code in the playground
```js
class A { constructor() { return } }
class B { constructor() { { return } } }
```

### What did you expect to happen?

I was expecting class `A` and `B` constructors to both produce errors for the `Unexpected return statement in constructor. (no-constructor-return)`.

### What actually happened?

Class `A` results in an error but as soon as you start wrapping the return statement in empty blocks it confuses the rule(class `B`).
It might very well be the intended behavior I'm just posting this issue here for confirmation since it isn't discussed anywhere in PRs or issues mentioning this rule and it is an undocumented behavior.

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiY2xhc3MgQSB7IGNvbnN0cnVjdG9yKCkgeyByZXR1cm4gfSB9XG5jbGFzcyBCIHsgY29uc3RydWN0b3IoKSB7IHsgcmV0dXJuIH0gfSB9Iiwib3B0aW9ucyI6eyJydWxlcyI6eyJuby1jb25zdHJ1Y3Rvci1yZXR1cm4iOlsiZXJyb3IiXX0sImxhbmd1YWdlT3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by rzvxa**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

closes #18486

#### What changes did you make? (Give an overview)
This PR will change the `no-constructor-return` behavior slightly to allow implicit undefined return statements regardless of it's position in the constructor.

#### Is there anything you'd like reviewers to focus on?

It should in theory be a breaking change but the impact is so negligible - and covered by other rules - that we might want to merge this as a backward-compatible change.
~~It is my first contribution here and I didn't run the test suit locally I'm relying on CI to run those so it might need manual intervention to run tests here.~~

### CODE REVIEW

**Comment by mdjermanovic** [comment]
It's fine to treat this as a semver-minor bug fix.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Leaving open for 2 days if anyone else would like to review it.

**Review by Tanujkanti4441 — APPROVED** [review]
LGTM, thanks!

**Review by snitin315 — APPROVED** [review]
LGTM. Thanks for contributing.

**Pull request merged**
