### PR TITLE
Docs: Correct violations of “Variable Declarations” in Code Conventions

### PR DESCRIPTION
**Pull request by jrpool**
Violated convention is “using a single var statement with one variable per line.
All lines after the first should be indented one level”. Interpreted this as
applying to “let” and “const”, too.

**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
In 2 places in 1 document, converted a sequence of adjacent variable declaration statements to a single statement containing a sequence of declarations, to make them conform to the Code Conventions.

**Is there anything you'd like reviewers to focus on?**
This is a pilot PR, intended to discover whether corrections of this kind are desired. If so, I intend to submit more of them on other files and an update to the convention to extend it to “const” and “let”.

### CODE REVIEW

**Comment by platinumazure** [comment]
Personally, I'm undecided about these changes in our docs. We have a set of coding conventions for the repository, and we enforce some of them by setting up a particular lint configuration internally. However, we do have to show examples of using other options in the docs. (For example, we use 4 space indent but we also have examples for 2 space indent and tabs.)

Basically, the coding conventions are internal and are a strict subset of the valid ways to write JS code. The docs are user-facing and should support a wider range of styles. So I don't think there is much need or value in enforcing our internal conventions inside the docs.

That said, if others on the team are in favor, I'm not strongly opposed.

**Comment by jrpool** [comment]
Thanks, @platinumazure. Good point. If this PR is approved, then I’ll want to be careful to avoid correcting code inside docs that is deliberately in violation of conventions for illustration. In this particular case, I believe these violations are not deliberate. To me, it seems desirable to show examples of compliant code in docs, except where the examples are intended to illustrate noncompliance.

**Comment by not-an-aardvark** [comment]
To be honest, I'm not sure we've followed this stylistic guideline in the codebase itself. Personally I think I prefer the opposite guideline (using separate declarations for each variable), but in any case I'm fine with updating the documentation to be more consistent.

**Comment by jrpool** [comment]
Does @not-an-aardvark’s comment imply a desire to propose a change in this coding convention? If such a proposal were pending, I would refrain from submitting further PRs to clarify the convention and make the code consistent with it until after the decision.

**Comment by not-an-aardvark** [comment]
I suppose I would mildly prefer to change the convention, but I also don't really feel strongly about it and I don't want to block documentation changes. I can make an issue for it in the next few days when I have time, so that we can get it resolved one way or the other

**Pull request merged**
