### PR TITLE
Fix: Indent rule errors if an array literal starts a new statement (fixes #3328)

### LINKED ISSUE #3328: Indent rule errors if an array literal starts a new statement
This issue appeared with v1.1.0.

Rule:
```yml
indent: [2, 2, {"SwitchCase": 1, "VariableDeclarator": 2}]
```

Code:
```js
[
  ['gzip', 'gunzip'],
  ['gzip', 'unzip'],
  ['deflate', 'inflate'],
  ['deflateRaw', 'inflateRaw'],
].forEach(function(method) {
  console.log(method);
});
```

Error:
```
  1:1  error  Expected indentation of 2 characters but found 0  indent
  2:3  error  Expected indentation of 4 characters but found 2  indent
  3:3  error  Expected indentation of 4 characters but found 2  indent
  4:3  error  Expected indentation of 4 characters but found 2  indent
  5:3  error  Expected indentation of 4 characters but found 2  indent
  6:2  error  Expected indentation of 2 characters but found 0  indent
```

Cross-reference: https://github.com/nodejs/io.js/pull/2286

### PR DESCRIPTION
**Pull request by BYK**
This might be a bit of a blatant fix but didn't break any existing tests so I guess it is okay.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
@gyandeeps Can you code review please?

**Comment by gyandeeps** [comment]
Awesome. Looks good.
This portion of code has become overly complicated now as we have so many variations including the mix of vars.

**Comment by BYK** [comment]
>This portion of code has become overly complicated now as we have so many variations including the mix of vars.

Don't you find it ironic that one of the most basic rules expected from a linter is one of the hardest? :) Anyways, hope I didn't contribute to that complexity, at least not a lot.

**Comment by gyandeeps** [comment]
yeah, but there so many ways to write syntax in javascript that trying to covers them has made it complicated. Specially arrays and objects with a mix of special indentation under variable declarations.
Thats why I wanted another set of eyes so that we are implementing using the best possible way.

**Comment by BYK** [comment]
>there so many ways to write syntax in javascript that trying to covers them has made it complicated

Definitely. And indentation is something both people obsess over and have differing styles so it actually makes sense as you meantioned.

**Pull request merged**
