### PR TITLE
Chore: "yorkie" -> "simple-git-hooks"

### PR DESCRIPTION
**Pull request by g-plane**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

Other, please explain: Infrastructure change.

#### What changes did you make? (Give an overview)

Migrated the Git hooks manager from [yorkie](https://github.com/yyx990803/yorkie) to [simple-git-hooks](https://github.com/toplenboren/simple-git-hooks).

`simple-git-hooks` is now used in some famous projects like PostCSS, Autoprefixer and so on. ([See this](https://github.com/toplenboren/simple-git-hooks#who-uses-simple-git-hooks))

Andrey Sitnik has stated about `simple-git-hooks` at his pull requests. ([source](https://github.com/sapegin/mrm/pull/149)) Note that `yorkie` is forked from `husky` v4, so we can treat `yorkie` as `husky` v4.

#### Is there anything you'd like reviewers to focus on?

I'm not sure.

### CODE REVIEW

**Comment by nzakas** [comment]
Can you explain more about this change? Is there an issue with Yorkie? Does simple-git-hooks provide some benefit?

Note that Yorkie is used by Vue, so it is also fairly well-tested.

**Comment by g-plane** [comment]
- Yorkie is forked but no longer updated.
- simple-git-hooks has no dependencies and smaller install size, faster.

**Review by nzakas — APPROVED** [review]
LGTM

**Comment by nzakas** [comment]
Waiting for others to review.

**Comment by noto-u** [comment]
I prefer yorkie for the automatic update and well tested, if ain't broke don't fix philosophy. Simple-git-hooks I noticed that coworkers have to run a command to update configuration when it's changed in master branch.

> If you need multiple verbose commands per git hook, flexible configuration or automatic update of git hooks, please check out the other packages:
> * Lefthook
> * husky
> * pre-commit

**Comment by nzakas** [comment]
@noto-u thanks for the feedback. I didn’t realize that was an issue with simple-git-hooks (mentioned here: https://github.com/toplenboren/simple-git-hooks#when-to-use-it). In that case, I think we should stick with Yorkie.

**Comment by g-plane** [comment]
It shouldn't be a big problem. If we need to update automatically, we just need to add `install` or `postinstall` script to `package.json` file.

**Comment by nzakas** [comment]
I was already skeptical about this change, and now I’m not comfortable with it. We aren’t having any problems with Yorkie, so let’s just keep using it.

**Pull request closed without merging**
