### PR TITLE
chore: update algolia referrer

### PR DESCRIPTION
**Pull request by harish-sethuraman**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain: referrer addition for algolia

#### What changes did you make? (Give an overview)

- exact copy of https://github.com/eslint/eslint.org/pull/660

### CODE REVIEW

**Review by amareshsm — APPROVED** [review]
LGTM. Waiting for 2nd approval.

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks!

**Comment by nzakas** [comment]
We also need to do this on the v8.x branch. Anyone up for that?

**Comment by harish-sethuraman** [comment]
Do I send a pr to that branch or it has direct push access? I’ll do it

**Comment by nzakas** [comment]
Send a PR to that branch. It's protected like `main`

**Comment by mdjermanovic** [comment]
> We also need to do this on the v8.x branch.

This isn't finished yet?

**Comment by amareshsm** [comment]
> > We also need to do this on the v8.x branch.
> 
> This isn't finished yet?

No yet. @harish-sethuraman Need to do the same on the v8.x branch would you like to take it?

**Comment by aladdin-add** [comment]
no worries - the PR is https://github.com/eslint/eslint/pull/19178.

**Comment by harish-sethuraman** [comment]
sorry missed it my bad, Thanks Aladdin!

**Pull request merged**
