### PR TITLE
Update: Make `constructor-super` support 'as' casting.

### PR DESCRIPTION
**Pull request by mf-pherlihy**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Tell us about your environment**

* **ESLint Version:** 6.8.0
* **Node Version:** 10.18.1
* **npm Version:** 6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**

Typescript

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended"
  ],
  "plugins": ["@typescript-eslint"],
  "env": {
    "browser": true,
    "node": true,
    "commonjs": true,
    "shared-node-browser": true,
    "es6": true,
    "worker": true,
    "serviceworker": true,
    "webextensions": true
  },
  "parserOptions": {
    "project": "./tsconfig.eslint.json",
    "sourceType": "module",
    "impliedStrict": true,
    "warnOnUnsupportedTypeScriptVersion": false
  },
  "rules": {

    "constructor-super": 2 // http://eslint.org/docs/rules/constructor-super

  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```ts
// Unexpected 'super()' because 'super' is not a constructor.
class A extends (B as any) { constructor() { super(); } }
```

**What did you expect to happen?**

No error should be reported.

**What actually happened? Please include the actual, raw output from ESLint.**

```ts
// Unexpected 'super()' because 'super' is not a constructor.
class A extends (B as any) { constructor() { super(); } }
```

#### What changes did you make? (Give an overview)

I added an additional case in `isPossibleConstructor` to support the `TSAsExpression` node type.

#### Is there anything you'd like reviewers to focus on?

I wasnt sure where this should be fixed? I assumed here and NOT the typescript-eslint plugin?

### CODE REVIEW

**Comment by kaicataldo** [comment]
Thanks for the PR! Generally, we've been avoiding adding TS-specific syntax changes into core rules. Can this be done in a more generic way that doesn't involve checking for a `@typescript-eslint` AST node? Otherwise, I think we should see what the @typescript-eslint team thinks of supporting this rule. I hate to throw it over the wall, but we're already spread quite thin in terms of core contributors, and we've generally decided that we can't take on the maintenance burden of supporting experimental or TS syntax.

**Comment by kaicataldo** [comment]
Labeling this is an enhancement rather than a bug fix because we don't currently support TS syntax.

**Comment by mdjermanovic** [comment]
Alternatively, `isPossibleConstructor()` could be rewritten to explicitly check what can't be constructor (e.,g., literals, `{}`, `[]`, `+foo` etc.) instead of what can be as it's implemented now.

I believe it could be done, though it would be difficult to test does the new code retains the current behavior aside from fixing this particular issue. It's also a lot of work so it might be better to wait for [consensus](https://eslint.org/docs/maintainer-guide/issues#accepting-issues) on this, i.e., for the enhancement to be accepted first.

**Comment by mdjermanovic** [comment]
It's also possible that we'll need to change this rule at some point, regardless of this issue.

To clarify, the primary use case for the `isPossibleConstructor()` check is to report invalid `super()` calls when the class `extends null`:

```js
/*eslint constructor-super: "error"*/

class A extends null {
  constructor() {
    super(); // Unexpected 'super()' because 'super' is not a constructor.
  }
}
```

It's because `super()` throws `TypeError` in this case.

It's also incorrect to not `return` a value from the constructor if the class `extends null` as it will result in a `ReferenceError`. This rule catches that as well, but the message is confusing as it suggests an invalid solution:

```js
/*eslint constructor-super: "error"*/

class A extends null {
  constructor() { // Expected to call 'super()'.
  }
}
```

Anyway, if I understand correctly this behavior could be changed in the near future with tc39/ecma262#1321 so we might need to update the rule.

At the moment, `extends null` can be used only if the constructor returns something, and it's a valid code by this rule:

```js
/*eslint constructor-super: "error"*/

class A extends null {
  constructor() {
    return Object.create(A.prototype);
  }
}
```

**Comment by mdjermanovic** [comment]
It's also possible to write something like this at the moment:

```js
/*eslint constructor-super: "error"*/

class A extends null {
  constructor() {
    super(); // Unexpected 'super()' because 'super' is not a constructor. (constructor-super)
  }
}

Object.setPrototypeOf(A, function() {});

new A(); // doesn't throw anything
```

This seems to be a valid code but the rule reports error, thus it could be seen as a false positive or a known limitation since the rule can't always know what will be called with `super()` in runtime.

So it might make sense to put the `isPossibleConstructor()` check behind an option, which might indirectly solve this issue, though the option would also hide possible errors with `extends null` or certain errors with code such `extends 1` (which always result in a runtime error at the time when the class is created).

**Comment by kaicataldo** [comment]
Closing this due to lack of activity. If you would like to continue advocating for this change, please feel free to open a new issue or PR.

**Pull request closed without merging**
