### PR TITLE
docs: add backtick in `-0` in `description` of `no-compare-neg-zero`

### PR DESCRIPTION
**Pull request by lumirlumir**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Hello,

Although `-0` is wrapped in an inline code block using backticks in the official documentation, it is missing in the `description` property of the `no-compare-neg-zero.js` rule. So, I added it.

Here’s a screenshot of the official documentation.

https://eslint.org/docs/latest/rules/no-compare-neg-zero

image

#### Is there anything you'd like reviewers to focus on?

It’s just a simple fix, and I am not sure if it should be categorized as a bug. so I didn’t use the bug template.

However, if I need to use the template, I’ll be happy to do so.

### CODE REVIEW

**Review by Tanujkanti4441 — COMMENTED** [review]
To change this you have to update the [_data/rules_meta.json`](https://github.com/eslint/eslint/blob/main/docs/src/_data/rules_meta.json) file.

**Comment by lumirlumir** [comment]
Thanks @Tanujkanti4441, I've updated it.

However, the original _data_rules_meta.json file had no EOF, so one was added automatically. Is it okay to leave it as is?

**Comment by Tanujkanti4441** [comment]
> However, the original `_data_rules_meta.json` file had no EOF, so one was added automatically. Is it okay to leave it as is?

yes we can leave that as is.

**Review by Tanujkanti4441 — DISMISSED** [review]
LGTM, thanks!

**Comment by nzakas** [comment]
The [_data/rules_meta.json](https://github.com/eslint/eslint/blob/main/docs/src/_data/rules_meta.json) file is autogenerated, that's why it doesn't have a newline at the end of the file. It should be automatically updated by our precommit hook. Did you edit the file on the GitHub website instead of locally on your computer?

**Comment by lumirlumir** [comment]
@nzakas 

Oh, unfortunately yes. I'll recommit it right away using the pre-commit hook.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
