### PR TITLE
chore: bump cross-spawn

### PR DESCRIPTION
**Pull request by maybebot**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

Addressing Regular expression denial of service bug in dependency. While it might not be critical for ESLint usage it pops up in certain internal tooling that register vulnerabilities in packages

#### What changes did you make? (Give an overview)

Bump `cross-spawn` version to 7.0.5

### CODE REVIEW

**Comment by mdjermanovic** [comment]
We're using cross-spawn with predefined arguments only so there's no impact on ESLint, but it's fine to bump the version if it helps avoid the warnings.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by blurredpixel** [comment]
@mdjermanovic would it be possible to backport this to current 8.x as maintenance release?

**Comment by RaviVadera** [comment]
@mdjermanovic would it be possible to backport this to current 8.x as maintenance release?

**Comment by mdjermanovic** [comment]
ESLint v8.x is EOL so the ESLint team is not making any further changes to it. You can find more details about options for EOL release lines support here: https://eslint.org/version-support/

**Pull request merged**
