### PR TITLE
Fix: `no-unused-vars` false positive around callback (fixes #6576)

### LINKED ISSUE #6576: no-unused-vars false positive after upgrading to v3.0.0
**What version of ESLint are you using?**
3.0.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Default.

**Please show your full configuration:**
```
{
	"root": true,
	"env": {
		"browser": true,
		"es6": true,
		"amd": true,
		"jquery": true
	},
	"globals": {
		"_": false,
		"angular": false,
		"CKEDITOR": false,
		"google": false
	},
	"parserOptions": {
		"ecmaVersion": 6
	},
	"rules": {
		// Possible errors
		"no-dupe-keys":                  2,
		"no-empty":                      1,
		"no-ex-assign":                  1,
		"no-irregular-whitespace":       2,

		// Best practices
		"curly":                       [ 2, "all" ],
		"dot-notation":                [ 2, {
			"allowKeywords": true
		}],
		"dot-location":                [ 2, "property" ],
		"eqeqeq":                      [ 2, "allow-null" ],
		"guard-for-in":                  1,
		"no-else-return":                1,
		"no-labels":                     2,
		"no-extend-native":              2,
		"no-fallthrough":                0,
		"no-lone-blocks":                1,
		"no-loop-func":                  2,
		"no-multi-spaces":               0,
		"no-multi-str":                  2,
		"no-native-reassign":            2,
		"no-param-reassign":             0,
		"no-return-assign":              0,
		"no-unused-expressions":         0,
		"radix":                         1,
		"yoda":                          2,

		// Variables
		"no-undef":                      2,
		"no-unused-vars":                2,
		"no-use-before-define":        [ 2, "nofunc" ],

		// Stylistic issues
		"array-bracket-spacing":       [ 2, "always", {
			"objectsInArrays": false
		}],
		"brace-style":                 [ 2, "1tbs", {
			"allowSingleLine": true
		}],
		"camelcase":                   [ 2, {
			"properties": "never"
		}],
		"comma-spacing":                 2,
		"comma-style":                   2,
		"computed-property-spacing":   [ 2, "always" ],
		"eol-last":                      0,
		"indent":                      [ 2, "tab", {
			"SwitchCase": 1
		}],
		"key-spacing":                   0,
		"lines-around-comment":        [ 2, {
			"allowBlockStart": true
		}],
		"max-nested-callbacks":        [ 1, 5 ],
		"new-parens":                    2,
		"newline-after-var":             0,
		"no-spaced-func":                0,
		"object-curly-spacing":        [ 2, "always" ],
		"one-var":                     [ 2, {
			"initialized":   "never"
		}],
		"quotes":                      [ 2, "double" ],
		"keyword-spacing":             [ 2, {
			"before": true,
			"after": true
		}],
		"space-in-parens":               0,
		"space-infix-ops":               2,
		"space-unary-ops":             [ 2, {
			"words": true,
			"nonwords": false
		}],
		"spaced-comment":              [ 2, "always" ],

		// Legacy
		"max-len":                     [ 2, 150 ]
	}
}
```

**What did you do? Please include the actual source code causing the issue.**
```js
var unregisterFooWatcher;
// ...
unregisterFooWatcher = $scope.$watch( "foo", function( foo ) {
	// ...some code..
	unregisterFooWatcher();
});
```

**What did you expect to happen?**
Code linted just fine.

**What actually happened?**
```
/path/to/file.js
  29:8  error  'unregisterFooWatcher' is defined but never used  no-unused-vars
```

Seems to be caused by modifications of #6348 and #6535.

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #6576.

I added a check to check whether the Identifier of a read reference exists inside of a function node which can be used later or not.

"can be used later" is meant:

- the function is assigned to a variable.
- the function is bound to a property, and the object can be used later.
- the function is bound to an argument of a function call.

If a reference exists in a function which can be used later, the reference is read when the function is called.

### CODE REVIEW

**Comment by mysticatea** [comment]
I added a check to cover https://github.com/eslint/eslint/issues/6576#issuecomment-230137227 in this PR.
In that case, the reference itself can be used later.

**Comment by nzakas** [comment]
LGTM. Can you update the docs to account for what "can be used later" means?

**Comment by nzakas** [comment]
I'll update the docs so we can merge this.

**Comment by nzakas** [comment]
Actually, I'm going to hold off on merging this for now as I have some questions back on the issue.

**Comment by nzakas** [comment]
Okay, I misunderstood something. Nevermind. :)

**Pull request merged**
