### PR TITLE
Docs: Add details about "--fix" option for "sort-imports" rule

### PR DESCRIPTION
**Pull request by dharFr**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update

**What changes did you make? (Give an overview)**
I removed the "fixable" statement from the `sort-imports` rule, as it is not actually supported (see #6866).

**Is there anything you'd like reviewers to focus on?**
Nope.

### CODE REVIEW

**Comment by gyandeeps** [comment]
Based on the source code, this rule is fixable under certain conditions.

**Comment by dharFr** [comment]
OK. What about clarifying that statement then?Because from a user point of view, in my use-case as well as in thoses described in #6866, the current documentation seems to be incorrect. 

Thx

**Comment by vitorbal** [comment]
@dharFr sure, that would make sense. Documentation improvement PRs are always welcome.
I would suggest adding a separate sentence after the "fixable" statement, because we are planning on adding that "fixable" statement line programmatically to every fixable rule in the future.

**Comment by dharFr** [comment]
Ok thanks @vitorbal . 
For what I can tell, the `--fix` option seems to work for single lines fixes only but not for multiple lines. e.g. : 
``` js
import {B, A} from 'foo' // --> will be corrected to import {A, B} from 'foo'
```
``` js
import B from 'foo'
import A from 'bar' // --> won't be corrected
```
Is that correct or do I miss something? 

Therefore, would it be OK if I update my PR to add the following sentence?
> Disclaimer : For this rule, the `--fix` option only fixes sorting problems between multiple members on a single line but does not fix `import` statements order on multiple lines.

**Comment by not-an-aardvark** [comment]
@dharFr That's correct. The reason for this is that fixing the first case can't change the behavior of the code, whereas fixing the second case changes the order that the `foo` and `bar` modules get executed, which can change the result of the program.

Feel free to update the docs to make that more clear. Since the line at the top of the documentation is the same for all fixable rules, it might be better to put a note within the documentation file instead (like what we do with the [`eqeqeq`](http://eslint.org/docs/rules/eqeqeq#rule-details) documentation), since that might make it easier if we ever automate the line at the top of the documentation in the future.

**Comment by dharFr** [comment]
Thanks @not-an-aardvark. I just updated the branch according to your feedback.

**Comment by dharFr** [comment]
Is there something wrong with Travis hook? The build seems to be OK, but it's still marked as pending...

**Comment by alberto** [comment]
I forced a rebuild. It's green now.

**Comment by gyandeeps** [comment]
LGTM :+1: 
Thanks for contributing.

**Pull request merged**
