### PR TITLE
Docs: Fix: Typo

### PR DESCRIPTION
**Pull request by Isti115**
Fix: Changed article from "an" to "a" in front of "string".

### CODE REVIEW

**Comment by alberto** [comment]
Thanks @Isti115. Can you change the commit message to begin with "Docs: ", please?

**Comment by Isti115** [comment]
@alberto, I changed the title of the pull request, but as far as I know, to change the commit message I would need to clone the repository locally onto my computer which I wouldn't do if it's not neccessary.
Do I need to do that, or is it fine this way?
(Forgive me for any inconveniences I cause, I am not nearly as familiar with git as I should be.)

**Comment by alberto** [comment]
@Isti115 yes, I'm sorry, but you need to amend the commit message so we can later identify the kind of change.

**Comment by Isti115** [comment]
I cloned it, amended the message and then force pushed. It now shows the modification on the online interface for me. Does it look good now? :)
It wasn't as hard as I thought (I have never had to change a commit message before, so I didn't know the exact proedure until now), so no problem. Sorry for bothering you with such questions! :)

**Comment by platinumazure** [comment]
@Isti115 Commit message looks good, thanks so much for changing it. Have you signed the CLA yet? (If you have, I don't have permissions to check it, so I'm just asking to make sure)

**Comment by ilyavolodin** [comment]
Thanks @Isti115 for PR!

**Pull request merged**
