### PR TITLE
Build: add Node v10 to travis

### PR DESCRIPTION
**Pull request by alberto**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[X] Other, please explain:

**What changes did you make? (Give an overview)**
Add Node v10 to travis

**Is there anything you'd like reviewers to focus on?**
No

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you.

Looks to need to fix a test.

```diff
-     }, /Output is incorrect\. \(' foo = bar;' === 'invalid output'\)$/);
+     }, /Output is incorrect\. \(' foo = bar;' (?:===|strictEqual) 'invalid output'\)$/);
```

[tests/lib/testers/no-test-runners.js#L29](https://github.com/eslint/eslint/blob/b32d1f48cecc1eecd1352a978d7b393ad047337c/tests/lib/testers/no-test-runners.js#L29)

**Comment by alberto** [comment]
Yes, thanks for pointing it out.

**Comment by mysticatea** [comment]
Hmm, I'm not sure what the new test failings are.
I couldn't reproduce those failings in my PC...

**Comment by alberto** [comment]
Ugh, I used the wrong node version locally 🤦‍♂️ I'll have a look at it later.

**Comment by not-an-aardvark** [comment]
I think the test failures are fixed in https://github.com/eslint/eslint/pull/10182.

**Comment by platinumazure** [comment]
After merging #10182, it seems there are still some errors we might need to look at. So we decided to hold off on merging this for tonight's alpha release.

**Comment by alberto** [comment]
Ok, sorry it took so long. I've traced at least some of the errors down to [an issue](https://github.com/tschaub/mock-fs/issues/236) with `mockFs` and changes in `fs.statSync`.

**Comment by tschaub** [comment]
@alberto `mock-fs@4.5` has been published with Node 10 support.

**Comment by alberto** [comment]
Awesome! Thanks @tschaub

**Comment by alberto** [comment]
I'm sorry I had some problems getting the test to fail for the right reason and then got busy, so if anyone wants to take over this, feel free to do so.

**Comment by Aladdin-ADD** [comment]
Just pushed a commit to fix the message. 🚀

**Pull request merged**
