### PR TITLE
Docs: Fix a typo in the require-yield.md

### PR DESCRIPTION
**Pull request by vsemozhetbyt**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Replace "that have `yield` expression" by the "that have no `yield` expression" in the  **When Not To Use It**.

**Is there anything you'd like reviewers to focus on?**

No.

### CODE REVIEW

**Comment by platinumazure** [comment]
@vsemozhetbyt Could you please rebase on latest master and force push? That will result in a passing Travis/AppVeyor build. Thanks and sorry for the inconvenience.

**Comment by vsemozhetbyt** [comment]
@platinumazure Sorry, I'm not very experienced in git, I usually fix typos by GitHub interface( Maybe this PR should be closed and somebody else could fix it more properly. Sorry for my incompetence.

**Comment by not-an-aardvark** [comment]
@vsemozhetbyt No worries. Would you mind if I rebase and then push to your branch on GitHub? That way we can keep using this pull request.

**Comment by platinumazure** [comment]
No, it's not you, it's just that at the time you opened the PR, we happened
to have let a lint error into master. That's on us.

If you wouldn't mind allowing us to push to your branch (there should be a
checkbox on the PR edit screen that says something like "Allow
collaborators to push to your branch", then we can merge master and squash
and you don't need to worry about it anymore.

Thanks so much for your contribution, we really appreciate it and we're
sorry that our mistake is causing problems.

On Nov 24, 2016 1:16 PM, "Vse Mozhet Byt" <notifications@github.com> wrote:

@platinumazure <https://github.com/platinumazure> Sorry, I'm not very
experienced in git, I usually fix typos by GitHub interface( Maybe this PR
should be closed and somebody else could fix it more properly. Sorry for my
incompetence.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/eslint/eslint/pull/7652#issuecomment-262834110>, or mute
the thread

**Comment by vsemozhetbyt** [comment]
@not-an-aardvark , @platinumazure Sure, if you please. Is this the right option checked?

**Comment by platinumazure** [comment]
Yes, thanks so much!

**Pull request merged**
