### PR TITLE
docs: fix language option styling

### PR DESCRIPTION
**Pull request by amareshsm**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:
Fixed language option styling.

#### What changes did you make? (Give an overview)
Due to the style change (`pre[class*="language-"]` to `div[class*="language-"]` - `syntax-highlighter.scss`) in #16606, language option styles were affected. Fixed by excluding the `.language-switcher` class.

| Before | After |
| --- | --- |
|  image |  image |
|  image |  image |

### CODE REVIEW

**Comment by harish-sethuraman** [comment]
Wasn't it part of design? I thought it was part of design 😅

**Comment by amareshsm** [comment]
> Wasn't it part of design? I thought it was part of design 😅

No, it's not a part of the design.

**Review by harish-sethuraman — APPROVED** [review]
LGTM. Thanks

**Comment by chenxsan** [comment]
Absolutely that's a visual regression my pr introduced.

**Comment by nzakas** [comment]
Can we change this line to use “pre” instead of “div” and then revert the CSS?
https://github.com/eslint/eslint/pull/16606/files#diff-0e154e64478403222a01a7cb42c83ab07a2e01a90f65b5d0839b922570d4b03aR65

**Comment by chenxsan** [comment]
> Can we change this line to use “pre” instead of “div” and then revert the CSS? https://github.com/eslint/eslint/pull/16606/files#diff-0e154e64478403222a01a7cb42c83ab07a2e01a90f65b5d0839b922570d4b03aR65

Hi Nicholas, I'm afraid we can't simply change that and revert the respective css changes. The default [`fence` rule](https://github.com/markdown-it/markdown-it/blob/1529ff4944329eb8080a8558dab85164b6c212cd/lib/renderer.js#L39) of `markdown-it` will always return `<pre><code></code></pre>`. Replacing that `div` with `pre` will result in a nested `pre` like 

```
<pre>
  <pre><code/></pre>
</pre>
```

which would introduce another styling problem.

It's possible to keep the original css class if I didn't implement the `div` wrapper in the beginning. Let me know if you want me to file a pull request to update it or prefer to merge this fix.

**Comment by nzakas** [comment]
Ah I see. I'm just not a fan of using `:not()` to fix this kind of an error -- we should have unique and non-overlapping CSS class names for the two different use cases like we did before.

**Comment by chenxsan** [comment]
> Ah I see. I'm just not a fan of using `:not()` to fix this kind of an error -- we should have unique and non-overlapping CSS class names for the two different use cases like we did before.

Class name collisions seem inevitable when they're semantic :), especially when we have many contributors in open source projects.

How about renaming `language-switcher` to `locale-switcher`, which would require a few more changes than the current fix in this pull request:

**Comment by nzakas** [comment]
> Class name collisions seem inevitable when they're semantic :), especially when we have many contributors in open source projects.

Yes but we didn't have any until this change. :) Managing exclusions tends to cause errors in the long-run because you need to keep track of them.

Can't we just add the `language-` class [here](https://github.com/eslint/eslint/pull/16606/files#diff-0e154e64478403222a01a7cb42c83ab07a2e01a90f65b5d0839b922570d4b03aR50) and have it work like it used to?

**Comment by chenxsan** [comment]
> > Class name collisions seem inevitable when they're semantic :), especially when we have many contributors in open source projects.
> 
> Yes but we didn't have any until this change. :) Managing exclusions tends to cause errors in the long-run because you need to keep track of them.
> 
> Can't we just add the `language-` class [here](https://github.com/eslint/eslint/pull/16606/files#diff-0e154e64478403222a01a7cb42c83ab07a2e01a90f65b5d0839b922570d4b03aR50) and have it work like it used to?

Sure. That was my plan when I said above I can file another pull request to update it:

**Comment by harish-sethuraman** [comment]
@amareshsm shall we close this in favour of https://github.com/eslint/eslint/pull/16669 I think both of the PRs are solving the same problem?

**Comment by amareshsm** [comment]
> @amareshsm shall we close this in favour of #16669 I think both of the PRs are solving the same problem?

yes once the PR is ready we check and close this PR.

**Comment by amareshsm** [comment]
Closing this in favor of #16669

**Pull request closed without merging**
