### PR TITLE
Build: CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Other

**What changes did you make? (Give an overview)**

This PR switches CI service to Azure Pipelines from the pair of Travis CI and AppVayer.

Azure Pipelines service has some pros.

- It supports all of Linux, Windows, and macOS.
- It's fast and provides 10 parallel jobs for OSS projects.
- It shows the test results readable: https://dev.azure.com/eslint/eslint/_build/results?buildId=7&view=ms.vss-test-web.build-test-results-tab
- It shows code coverage without other services: https://dev.azure.com/eslint/eslint/_build/results?buildId=7&view=codecoverage-tab

This PR does:

- Set up Azure Pipelines.
- Remove Travis CI configuration.
- Remove AppVayer configuration.
- Remove Coveralls process.
- Update README.md badges.
- Fix tests for some reasons:
    - I have realized that the current test failed if I ran tests on `D:\` drive (Azure Pipelines run the tests on `D:\` drive) because the in-memory file system that the tests use didn't support `D:\` drive.
      This PR fixes the in-memory file system.
    - Azure Pipelines failed to parse the test results if the description of test cases has control characters.
      This PR fixes `RuleTester` as sanitize the description.

**Is there anything you'd like reviewers to focus on?**

- Is this direction good?
- I'm not sure if we are still using Code Climate. Is it needed?

### CODE REVIEW

**Comment by aladdin-add** [comment]
I think it should be: "Build:"

**Comment by g-plane** [comment]
Do we really need to upload coverage report on all platforms?

**Comment by mysticatea** [comment]
I updated the issue description since I have done my trial.

@aladdin-add I fixed the label.

@g-plane Job Template was nice. In ideal, I wanted to merge all coverage results because it has different coverages by Node.js versions and platforms.

**Comment by ilyavolodin** [comment]
Looks like a good idea. Couple of quick questions: Is there a limit on number of builds/minutes for OSS project? Have you had a chance to check build time and compare it to Travis/AppVeyor?

**Comment by g-plane** [comment]
@ilyavolodin Azure Pipelines is umlimited for OSS. As for the build time, Azure Pipelines doesn't provide cache currently, but the container performance should be better than Travis and AppVeyor.

**Pull request merged**
