### PR TITLE
Fix: support absolute filename in preprocessor

### PR DESCRIPTION
**Pull request by JounQin**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

- [ ] Documentation update
- [x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
- [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)

fix https://github.com/eslint/eslint/issues/11989#issuecomment-797285447

### CODE REVIEW

**Comment by mdjermanovic** [comment]
We intentionally don't allow absolute paths, because the processor can then return any path, while it must be a child file of the original file, as specified in the [Specifying Processor](https://eslint.org/docs/user-guide/configuring/plugins#specifying-processor) user documentation:

> ESLint handles such a named code block as a child file of the original file. You can specify additional configurations for named code blocks in the overrides section of the config.

The returned path also shouldn't contain any path separators (e.g., `../filename.js` or `\dir\filename.js`).

**Comment by JounQin** [comment]
This limitation breaks rules which require file exist like https://github.com/typescript-eslint/typescript-eslint/issues/3174

I was thinking to create a temporary file for `typescript-eslint`.

I don't understand why it should be limited, what's  the benif?

**Comment by mdjermanovic** [comment]
> I don't understand why it should be limited, what's the benif?

* Expected behavior, so that users can configure `overrides` accordingly, knowing that the exported code blocks are child paths.
* Performance. If the path can be anything, our config system would have to determine the configuration for a path that might be unrelated to the original path, and that may include config files lookup.

**Comment by JounQin** [comment]
OK, fair enough to me. Let's continue to discuss it on the original issue for getting real path.

**Pull request closed without merging**
