### PR TITLE
Fix: `func-style` should ignore ExportDefaultDeclarations

### LINKED ISSUE #5183: [func-style] error when anonymous function is exported as default
Consider the following one-liner:

```js
export default function () {}
```

Eslint config (from demo):
ECMA features: 
- [x] modules

Rules:
- [x] func-style

Error is reported:

```
1:16 - Expected a function expression. (func-style)
```

Although the example given is obviously not a function expression there might be a way to define exception in the rule for the case when one want to have all functions created using function expressions but allow anonymous (or maybe even named?) function to be exported as default from a module.

It makes sense to do so for short modules that export one single function as default.

Without a way to express this exception one valid way to default-export a function is this:

```js
const init = function () {};

export {init as default};
```

which makes us define provisional variable which would be unneeded otherwise.

### PR DESCRIPTION
**Pull request by BYK**
Fixes #5183

### CODE REVIEW

**Comment by mysticatea** [comment]
Looks good to me!

**Comment by michaelficarra** [comment]
This also adds an exception for named default exports. The exception was to be for unnamed default exports only.

**Comment by BYK** [comment]
@michaelficarra - what is the expected behavior with named default exports? I'm happy to follow-up with a fix if you can file a bug detailing the expected behavior.

**Comment by michaelficarra** [comment]
@BYK The expected behaviour is to still report named default exports like `export default function f(){}` and `export default class A {}` [as we discussed in the issue](https://github.com/eslint/eslint/issues/5183#issuecomment-182547134).

**Comment by BYK** [comment]
@michaelficarra I read the discussion, read the rule docs one more and looked at the examples you provided and still have no clue about what you are asking for. Can you please tell me what the rule should do with sample configs and code so I can fix it?

I'm guessing you want to warn on unnamed function declarations when someone prefers declarations that said the rule just enforces declarations or expressions, I don't see anything about forcing a name. Since any function "definition" is considered a declaration with a default export, I have no idea what I should do here.

**Comment by michaelficarra** [comment]
@BYK If I prefer all functions to be function expressions (e.g. a user of this rule), I am not going to want to see `export default function f() {}` in my code. This is a function declaration. The `func-style` rule's job is to prevent me from accidentally writing those. This construct should still be reported. The resolution in #5183, which this PR claimed to fix, was to only allow an exception for `export default function(){}`, a special-case function declaration that has no name and is only allowed in this position.

**Comment by platinumazure** [comment]
@michaelficarra Sounds like preferred function style might be another possible "repository setting" that could/should be shared among rules, do you agree?

**Comment by michaelficarra** [comment]
@platinumazure I think all settings would best be configured in that manner, but please let's not get off track in this thread.

**Comment by BYK** [comment]
@michaelficarra okay now that explains my confusion since @nzakas said the action should be simply ignoring default exports. So my understanding is you want to only ignore this if `id` for this function is `null` instead of outright ignoring default exports right? That makes sense to me but it is not academically "correct".

What do you think @nzakas?

**Comment by michaelficarra** [comment]
@BYK If you read the quote from @nzakas that I linked above, this is already quite clear:

> And yes, the question of this issue is about **unnamed** default export functions. My feeling is that these should be omitted from this rule.

Emphasis mine.

**Pull request merged**
