### PR TITLE
Chore: use "file:" dependencies for internal rules/config

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Other, please explain:

**What changes did you make? (Give an overview)**

This updates the setup of our internal linting rules to use "file:" dependencies within the project, rather than the `eslint-plugin-rulesdir` package. If this works well, it could be a good alternative for packages like `eslint-plugin-rulesdir` and `eslint-plugin-self`.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

**Comment by platinumazure** [comment]
Thanks @not-an-aardvark, this looks interesting.

Out of curiosity, what problem are you trying to solve here?

**Comment by g-plane** [comment]
@platinumazure VS Code doesn't work well with `eslint-plugin-rulesdir`.

**Comment by not-an-aardvark** [comment]
It's generally pretty inconvenient for projects to use custom rules that are also developed alongside the project itself. (We use [`eslint-plugin-rulesdir`](https://github.com/not-an-aardvark/eslint-plugin-rulesdir), which requires the user to load the plugin and globally mutate it before ESLint loads it. It also has some problems with VSCode on Windows due to drive letter capitalization.) If we dogfood this and it works well, we could potentially document this pattern as a recommendation for users.

**Comment by platinumazure** [comment]
Thanks @g-plane and @not-an-aardvark. Now I've caught up on the Gitter chat :smile:

I'd like to wait to merge this until we know we don't need a patch release, just in case of any unexpected impact to users.

**Pull request merged**
