### PR TITLE
Docs: Remove superfluous object option sample code

### PR DESCRIPTION
**Pull request by revolter**
**What is the purpose of this pull request? (put an "X" next to item)**

- [x] Documentation update
- [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
- [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

**What changes did you make? (Give an overview)**

The other rules don't have this sample code block, so this PR makes the `no-else-return` documentation consistent with the others.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the PR! I'm fine with changing this for now for consistency, although my impression is that the example might be useful to users who don't know how to configure options. I wonder if it would be better to change other rules to add an example instead (although admittedly that might be a much bigger task).

**Comment by revolter** [comment]
Well, I'd like something else from these. I'd like for them (`.md` files) to be auto-generated instead of manually created. This way, the whole structure, formatting, and maintaining would be far easier. Similar to how _fastlane_ [does it](https://github.com/fastlane/fastlane/blob/480d2d2b66e9713708ed898cac058158d1dfa94f/fastlane/Fastfile#L338-L407).

**Comment by revolter** [comment]
We also have [a bunch of checks](https://github.com/fastlane/fastlane/blob/480d2d2b66e9713708ed898cac058158d1dfa94f/fastlane/Fastfile#L471-L546) to prevent inconsistent content.

**Comment by Aladdin-ADD** [comment]
I have a concern to change other rules: some rules have a very big number options (such as indent), and some and/or options could cause confusing.

**Comment by revolter** [comment]
Maybe have a hyperlink on every rule that points to a separate doc explaining it?

**Comment by not-an-aardvark** [comment]
I think it would be reasonable to autogenerate some parts of the documentation. Presumably, we would still need to manually write other parts (e.g. code samples and descriptions).

**Comment by Aladdin-ADD** [comment]
thanks for contributing!

**Comment by revolter** [comment]
Thanks for merging! Btw, the same examples are actually in the same file too, but closer to the end: https://github.com/revolter/eslint/blob/fa9c9e93cecfecd2871646c0dce2d2198854adda/docs/rules/no-else-return.md#allowelseif-false

**Pull request merged**
