### PR TITLE
Fix: `curly` with `multi` had false positive

### LINKED ISSUE #3856: Curly braces around inner `if`
I'm linting this code:

	if (true) {
		if (false)
			console.log(1)
	} else if (true)
		console.log(2)

With this package.json:

	{
		"eslintConfig": {
			"rules": {
				"curly": [ 1, "multi" ]
			}
		}
	}

And I get this output:

	$ node_modules/eslint/bin/eslint.js file.js 

	/home/andy/mason3/ESLINT/file.js
	  1:1  warning  Unnecessary { after 'if' condition  curly

	✖ 1 problem (0 errors, 1 warning)

Without the curly braces, running the code will log '2'.
With them, it will not log anything.

I've tested this with eslint 1.5.0.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26807652-curly-braces-around-inner-if?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #3856

### CODE REVIEW

**Comment by michaelficarra** [comment]
I'd like to see tests like these:

```js
if (true) { while(false) if (true); } else;
```

```js
if (true) { for(;;) if (false); } else;
```

**Comment by mysticatea** [comment]
Good catch, thank you @michaelficarra !

@nzakas May I add the dependency of `esutils`?
I will use trailingStatement function via `lib/ast-utils.js`.

**Comment by nzakas** [comment]
Sounds good

**Comment by mysticatea** [comment]
I updated this PR.

**Comment by nzakas** [comment]
LGTM

**Pull request merged**
