### PR TITLE
Fix: eslint --quiet no longer fixes warnings (fixes #8675)

### LINKED ISSUE #8675: Confusion around how --quiet and --fix should behave together
See #8353 for background.

I think the best way to fix this is to allow users the option to go either way and to be very explicit about how the options work.

Here's one proposal along those lines:

* Rename --quiet to --no-report-warnings (supporting --quiet as an alias and preserving its behavior), to avoid reporting warnings but possibly fix them
* Add option --no-fix-warnings to support not running autofix on warnings but possibly report them (no effect if `--fix` not specified)
* Users can use both to completely ignore warnings altogether

With this proposal, our CLI options become more clear and more flexible with regard to whether warnings are *reported/logged* (`--quiet`/`--no-report-warnings`) and whether warnings are *fixed* (`--no-fix-warnings`).

I'll champion.

### PR DESCRIPTION
**Pull request by platinumazure**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

See #8675.

**What changes did you make? (Give an overview)**

`eslint --quiet --fix` no longer fixes the warnings that are not reported.

**Is there anything you'd like reviewers to focus on?**

Please do not merge until we have agreed that #8675 represents a bug, rather than an enhancement request.

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
This fix doesn't seem correct to me. It looks like the autofix output now is written after the results are filtered rather than before, but the it seems like the output itself will already be present before `getErrorResults` is called. Is there something I'm missing?

**Comment by platinumazure** [comment]
@not-an-aardvark I ran the following command in my branch and in master:

```shell
$ node ./bin/eslint.js --fix --quiet --no-ignore --no-eslintrc --rule "quotes:[1, double]" ./tests/fixtures/single-quoted.js
```

In my branch, the file was not modified. In master, it was. So I think the basic fix is correct.

...That said, I think I see what you might be getting at-- if we apply fixes to output files and then use that when calling `CLIEngine#outputFixes`, then it will result in warning fixes being applied when there is at least one error in the file. So I'll revisit this tomorrow.

**Comment by platinumazure** [comment]
Okay, I've thought this through. Here's what I've come up with:

1. Currently, only `lib/cli.js` supports a quiet flag. This construct does not exist in CLIEngine or in the linter.
1. In order for this to be truly fixed, CLIEngine and/or the linter would need to have logic for preventing warning fixes from being applied if CLI is being run in quiet mode.
1. This could be implemented by adding quiet options to CLIEngine and/or the linter.
1. However, it might be better to implement a more generic solution if possible.

I thought of btmills' issue about allowing editor integrations to filter which fixes get applied. I think it could be more strategically sensible to implement that logic, and then use this in `lib/cli.js` to create a simple filter which prevents warning fixes from being applied if `--quiet` is enabled in the CLI.

@not-an-aardvark Do you have any thoughts on this?

**Comment by not-an-aardvark** [comment]
Late reply, but using the filtering logic from https://github.com/eslint/eslint/issues/8039 sounds good to me.

**Comment by platinumazure** [comment]
Closing as I will be adopting a different approach.

**Pull request closed without merging**
