### PR TITLE
Docs: Mark no-useless-rename as fixable in rules index

### PR DESCRIPTION
**Pull request by daltones**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Nice catch! Could you sign our CLA? I'll rename commit message to start with `Docs` since this is just a documentation change.

**Comment by daltones** [comment]
I think I'll have to commit again because my e-mail appears as a github auto-generated one and I could not sign the CLA.

**Comment by ilyavolodin** [comment]
Ah, did you submit this PR though Github web interface? I assume that's why the email is like that. If not, you should be able to change you email locally and force push to update this PR.

**Comment by daltones** [comment]
@ilyavolodin Yes, I did through web interface.

Replaced by #6297.

**Comment by ilyavolodin** [comment]
Nice. Thanks, I'll close this one in favor of #6297

**Pull request closed without merging**
