### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by friederbluemle**
A couple of minor typo/capitalization fixes.

Also see https://github.com/eslint/website/pull/798

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks. Please see the previous comment about signing the CLA. We'll need you to electronically sign before we can merge this.

**Comment by friederbluemle** [comment]
Thanks @nzakas - Signed the CLA and rebased the branch.

@LarryBattle - Mind explaining what the 👎 is about? 😂

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

Note to merger: commit message should start with `Docs:`

**Comment by friederbluemle** [comment]
Thanks @mdjermanovic - Updated commit message.

**Review by nzakas — APPROVED** [review]

**Pull request merged**
