### PR TITLE
Fix: Correct grammar in object-curly-newline reports (fixes #6725)

### LINKED ISSUE #6725: Typo in error message for object-curly-newline
**What version of ESLint are you using?**
2.13.1

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**
```js
{ 'object-curly-newline' : 'error' }
```

**What did you do? Please include the actual source code causing the issue.**
```sh
eslint file.js --env=es6 --rule='object-curly-newline: [2]'
```
```js
// file.js
const foo = {
    one : 1, two : 2
};
```

**What did you expect to happen?**
Receive a grammatically correct error message.
```
Unexpected line break after opening brace
```

**What actually happened? Please include the actual, raw output from ESLint.**
Received a grammatically incorrect error message.
```
Unexpected a line break after this open brace
```
Key words being: "Unexpected a line"

---

I may not have time to create a PR for a while. Filing this so it doesn't get forgotten.

### PR DESCRIPTION
**Pull request by vitorbal**
**What issue does this pull request address?**
Typo in the error report messages of `object-curly-newline` (#6725).

**What changes did you make? (Give an overview)**
Fixed the typo and adjusted the tests.

**Is there anything you'd like reviewers to focus on?**
Should we also remove the "this" in the sentence? i.e.:
`Unexpected line break after this opening brace.`
vs.
`Unexpected line break after opening brace.`

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you very much!

**Comment by vitorbal** [comment]
@mysticatea no problem at all :)

**Comment by ilyavolodin** [comment]
LGTM, but waiting another day for others to look

**Comment by nzakas** [comment]
Lgym

**Pull request merged**
