### PR TITLE
Docs: Add valid example that shows vars in a block scope

### PR DESCRIPTION
**Pull request by edg2s**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
All the current valid examples show hoisting the var to the function scope. This example makes is clear that this rule allows you to declare vars inside a block scope, just not use them out of that scope.

### CODE REVIEW

**Review by nzakas — CHANGES_REQUESTED** [review]
Thanks. Can you add a corresponding example in the “invalid” section, too? Note that all of the current examples in the “valid” section are rewritten versions of the code in the “invalid” section, and that is by design.

**Comment by edg2s** [comment]
I did notice that, but I don't think there is a functionally equivalent invalid example for this function. I could move the console.log down but that would be different functionality.

**Comment by nzakas** [comment]
You may want to consider a different example, then, that can show the same thing.

**Comment by edg2s** [comment]
> You may want to consider a different example, then, that can show the same thing.

As I said above, I have considered this. Any invalid case would have a variable being used outside the scope in which it was defined. In order to fix that _without_ changing the functionality you would have to move the variable declaration further up, but the whole point of this PR is to add an example of a var in a block scope.

**Comment by edg2s** [comment]
> Note that all of the current examples in the “valid” section are rewritten versions of the code in the “invalid” section, and that is by design.

And there are many other places where the examples don't (or can't) match up perfectly, e.g. https://eslint.org/docs/rules/no-compare-neg-zero, https://eslint.org/docs/rules/valid-typeof, https://eslint.org/docs/rules/dot-location, ...

**Comment by nzakas** [comment]
The goal isn’t necessarily to show a bad example and then the fixed version, it’s to show an example of what the rule will flag and then a similar example that shows what the rule won’t flag.

Despite other rules not always following this pattern, this rule’s documentation does, so I’d prefer to stick with it.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
