### PR TITLE
docs: Update sort-keys options properties count

### PR DESCRIPTION
**Pull request by lb-**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Currently the options listing for `sort-keys` says there are 3 properties, however this is not accurate. I have updated this to be generic so it does not have to be modified if new properties are added.

It appears that the 4th property `allowLineSeparatedGroups` was added via https://github.com/eslint/eslint/pull/16138 & relates to https://github.com/eslint/eslint/issues/12759 

I could not see any open PRs or issues for this.

#### Is there anything you'd like reviewers to focus on?

N/A

### CODE REVIEW

**Review by Rec0iL99 — CHANGES_REQUESTED** [review]
Thanks for the PR @lb-. Could you please sign the CLA before this gets merged?

Please follow the PR heading formatting instructions from the bot too (https://github.com/eslint/eslint/pull/18025#issuecomment-1907073782)

**Comment by lb-** [comment]
OK I think I am good now. Commit message is good & CLA done.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by lb-** [comment]
Thanks.

**Pull request merged**
