### PR TITLE
fix #1963

### LINKED ISSUE #1963: escope throws error when import is used
Maybe this is a duplicate of https://github.com/eslint/espree/issues/10 if that is the case, please feel free to close this issue :)

Here is a simple js file:

```es6
import foo from 'foo';
```

When I run eslint (0.16.0 or master) with the default parser and this .eslintrc config:

```
{
    "rules": {
        "quotes": [1, "single"],
        "no-unused-vars": 1
    },
    "ecmaFeatures": {
        "modules": true,
    },
}
```

I get the following error:

```
 
/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:73
            throw new Error(text);
                  ^
Error
    at assert (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:73:19)
    at Referencer.extend.ImportDeclaration (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:1383:13)
    at Referencer.Visitor.visit (/home/fabricio/bug/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (/home/fabricio/bug/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
    at Referencer.extend.Program (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:1236:18)
    at Referencer.Visitor.visit (/home/fabricio/bug/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Object.analyze (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:1430:20)
    at EventEmitter.module.exports.api.verify (/home/fabricio/bug/node_modules/eslint/lib/eslint.js:651:35)
    at processFile (/home/fabricio/bug/node_modules/eslint/lib/cli-engine.js:193:27)
    at /home/fabricio/bug/node_modules/eslint/lib/cli-engine.js:293:26

```

The same happens if the .eslintrc is:

```
{
    "rules": {
        "quotes": [1, "single"],
        "no-unused-vars": 1
    },
    "env":{
        "es6": true
    },
    "ecmaFeatures": {
        "modules": true
    }
}
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9306547-escope-throws-error-when-import-is-used?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by fczuardi**

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks, nice catch. We should add a test for this in eslint.js.

Please take a moment to read over our contributor guide: http://eslint.org/docs/developer-guide/contributing.html

We will need:

1. Update commit message as described
2. Sign our CLA (details in the link)
3. Add a test

**Comment by fczuardi** [comment]
I have agreed and signed the CLA and I am reading the contributor guide 
now, I will write a test  and submit a new PR as soon as I figure out 
how to add one :P

**Comment by nzakas** [comment]
See: https://github.com/eslint/eslint/blob/master/tests/lib/eslint.js#L2198

Just add a new test in that section

**Comment by fczuardi** [comment]
Made a better pull request at https://github.com/eslint/eslint/pull/1966

**Comment by fczuardi** [comment]
oh, I added to the other section, just saw the comment https://github.com/eslint/eslint/pull/1964#issuecomment-77716113

**Pull request closed without merging**
