### PR TITLE
Update: Define plugins in config using absolute paths (fixes #3458)

### LINKED ISSUE #3458: Support having plugins as dependencies in shareable config
My shareable config uses rules from an external plugin and I would like to make it a `dependency` so the user doesn't have to manually install the plugin manually. I couldn't find any docs on this, but it doesn't seem to work, so I'll assume it's not currently supported.

``` js
module.js:338
    throw err;
          ^
Error: Cannot find module 'eslint-plugin-no-use-extend-native'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:106:26
    at Array.forEach (native)
    at loadPlugins (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:97:21)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:182:5)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:224:12)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:391:26
```

I assume it's because you only try to load the plugin when the config is finished merging.

Other shareable configs that depend on a plugin [instructs the users](https://github.com/feross/eslint-config-standard#usage) to manually install the plugin too and they [have it in `peerDependencies`](https://github.com/feross/eslint-config-standard/blob/00fabb06f7622e8762d3a657a7c364993b22d0dd/package.json#L15). I find this sub-optimal though and I don't want the users to have to care what plugins my config uses internally.

The whole point of shareable configs is to minimize boilerplate and overhead, so this would be a welcome improvement.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25976721-support-having-plugins-as-dependencies-in-shareable-config?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mpal9000**
```javascript
// eslint-config-x/index.js
const xPluginPath = require.resolve('eslint-plugin-x')

module.exports = {
  // ...
  plugins: [
    xPluginPath,
  ],
  rules: {
    // ...
    [`${xPluginPath}/rule-name`]: 2,
    // ...
  },
  // ...
}
```

### CODE REVIEW

**Comment by nzakas** [comment]
Marking as "do not merge" because the issue is not accepted yet. 

@mpal9000 thanks for the attempt. Can you explain the approach here?

**Comment by mpal9000** [comment]
The goal is to move all (dev)dependencies related to eslint (except "eslint" itself), of any package, to a "common" config package. So any package can `npm i -D eslint eslint-config-common` and then define  the "common" config to ".eslintrc".

This can be done inside "common" package (.js file only), by using something like `require.resolve()` to get the absolute path of a plugin and then use that path as the plugin identifier.

**Comment by mpal9000** [comment]
It is also consistent with `{parser: require.resolve('babel-eslint')}` which currently works

**Comment by nzakas** [comment]
Thanks for the explanation. It looks like this pull request doesn't actually address the issue referenced in the commit message. Can you open a new issue describing the problem you're trying to solve here?

**Comment by mpal9000** [comment]
The PR is a very minimal way to tackle the problem of too many devDependency installations. It lets you "have plugins as dependencies in shareable config" (issue title)

**Comment by nzakas** [comment]
@mpal9000 we require issues for all PRs so we have a record of the problem being solved. Can you open an issue for this?

**Comment by ilyavolodin** [comment]
@mpal9000 Code changes looks good. But we would need some unit tests and documentation updates too.

**Comment by mpal9000** [comment]
@ilyavolodin @nzakas Probably I'll find some time in the weekend for both.
When using filepaths there is a downside to comments and warning messages. You have to write `eslint-disable-line /path/to/plugin/rule` instead of `eslint-disable-line plugin/rule` and that absolute path can be very long. In warning messages you see a long absolute path, but this can be solved with a formatter too. I had in mind to start with this PR and then add an aliasing mechanism on top

**Comment by nzakas** [comment]
@mpal9000 I think we should just use the package name as defined in `package.json` rather than the full file path.

**Comment by mpal9000** [comment]
@nzakas you mean as an alias, or to keep the current way of defining plugins?

**Comment by nzakas** [comment]
@mpal9000 to keep the current way. I don't think we should have file paths as part of the way we identify plugins.

**Comment by mpal9000** [comment]
@nzakas ok, thanks
filepaths can be used to make the distinction between local and foreign dependencies with a few lines. They can be hidden from the user with aliasing to module names internally

**Comment by nzakas** [comment]
@mpal9000 are you going to finish working on this?

**Comment by mpal9000** [comment]
@nzakas Hi and sorry for the late response. I have no time currently to do some extra work with this PR. But the naming issues (absolute paths instead of plugin names) can be solved later with another PR. I thought you didn't want to continue with it. What made you change your mind?

**Comment by nzakas** [comment]
@mpal9000 sorry, lost track of this. I didn't say I didn't want to do it, I just had some concerns about the implementation. No worries, we'll roll this into the general configs depending on plugins discussion anyway.

**Comment by mpal9000** [comment]
@nzakas That would be nice! I'll let you know if anything changes. Thanks

**Pull request closed without merging**
