### PR TITLE
fix: rule-proposal + PR tempalte markdown checkboxes

### PR DESCRIPTION
**Pull request by graingert**
**What is the purpose of this pull request? **

- [ ] Documentation update
- [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
- [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [x] Other, please explain: rule-proposal + PR template markdown checkboxes and update comment accordingly.

**What changes did you make? (Give an overview)**
rule-proposal + PR template markdown checkboxes and update comment accordingly.

**Is there anything you'd like reviewers to focus on?**
The swish new checkboxes and the new comment

### CODE REVIEW

**Comment by vitorbal** [comment]
Thanks for your PR. Could you go into more details on the reasoning for this change? More specifically, could you fill in the [PR submission template](https://raw.githubusercontent.com/eslint/eslint/master/.github/PULL_REQUEST_TEMPLATE.md)?

**Comment by graingert** [comment]
@vitorbal I think this is what you meant.

**Comment by not-an-aardvark** [comment]
Thanks for the PR. However, based on [this discussion](https://github.com/eslint/eslint/pull/7072#discussion-diff-77872859), I think the current formatting is intentional.

**Comment by graingert** [comment]
ah woops

**Pull request closed without merging**
