### PR TITLE
feat: pass cwd to formatters (refs eslint/rfcs#57)

### PR DESCRIPTION
**Pull request by mysticatea**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Add something to the core: eslint/rfcs#57

#### What changes did you make? (Give an overview)

This is the implementation of eslint/rfcs#57. It updates the adapter of `ESLint.prototype.loadFormatter` method to pass `cwd` to formatters. The `cwd` is useful to make relative paths from absolute paths for readability.

#### Is there anything you'd like reviewers to focus on?

Is this direction right?

### CODE REVIEW

**Comment by mad-briller** [comment]
any news on this? would like to write a custom formatter that outputs relative paths for ci/cd purposes and this is a requirement to do that and it's over a year old

another issue was raised in the past about this:
https://github.com/eslint/eslint/issues/13376

**Comment by btmills** [comment]
This implements an approved RFC, so re-labeling as accepted.  We just need someone to resolve the merge conflicts so this is reviewable. I'm happy to pick it up unless someone else gets to it first.

**Comment by btmills** [comment]
This is ready for review.

The rebase turned out to be a little more complicated than expected because this was previously using the in-memory filesystem that we've since stopped using. I created a fixture instead. There were a few tests that use the formatter fixtures directory as a target, and I had to update those with the new file.

mysticatea's commits are covered by the old CLA, so I've hidden the comment from the CLA bot.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks for finishing this up.

**Comment by mdjermanovic** [comment]
@btmills merging https://github.com/eslint/eslint/pull/15243 caused conflicts in the tests that lint the content of `/fixtures/formatters/`. Can you resolve the conflicts? Once we merge this, I'll make a PR to change those tests to use some other files, so that this doesn't happen again.

**Comment by btmills** [comment]
Merge conflicts resolved!

**Review by mdjermanovic — COMMENTED** [review]
Just a couple of suggestions about the docs.

**Comment by btmills** [comment]
Thanks for those improvements. I committed those and fixed a merge conflict caused by the markdownlint update that was merged a few hours ago.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
