### PR TITLE
Chore: avoid handling rules instances in config-validator

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

**What changes did you make? (Give an overview)**

This is a modified version of #9277, which was merged but then reverted later for performance reasons. The performance issues from #9177 have been fixed (`Linter` no longer creates a new map of rules whenever it lints text).

The goal of this change is to progress towards being able to remove the `rules` property from `Linter` instances. Unfortunately, this isn't possible yet, since there are a few other modules that rely on reading the list of defined rules.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
The goal of this change is to progress towards being able to remove the `rules` property from Linter instances. This property is not supposed to be part of the public `Linter` API, but there are other parts of core using it, so we can't remove it yet.

**Comment by ilyavolodin** [comment]
Just to clarify, when you are talking about `rules` property you mean `linter.rules`, right? `linter.getRules()` will still be available?

**Comment by not-an-aardvark** [comment]
Yes, that's correct.

**Comment by ilyavolodin** [comment]
@not-an-aardvark Could you rebase please?

**Pull request merged**
