### PR TITLE
Chore: update no-unused-vars caughtErrors in eslint-config-eslint

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Other, please explain:

Updates `eslint-config-eslint`

#### What changes did you make? (Give an overview)

Added `caughtErrors: "all"` to `no-unused-vars` in order to enforce omission of catch binding in cases where the caught error  would not be used.

#### Is there anything you'd like reviewers to focus on?

Does this change make sense? Also, please verify that all supported Node versions support optional catch binding.

### CODE REVIEW

**Comment by aladdin-add** [comment]
image

the supported Node versions seems fine.(and the CI passed)

**Comment by yeonjuan** [comment]
@mdjermanovic
I test it in node v10.12.0 and it looks fine.
Maybe should we update the engine field in `eslint-config-eslint package.json`?
It's still `"node": "^8.10.0 || ^10.13.0 || >=11.10.1"`

**Comment by kaicataldo** [comment]
Even though it won't cause any issues, I think it does makes sense to have it match the engines range in `eslint`'s package.json.

**Comment by mdjermanovic** [comment]
> Maybe should we update the `engine` field in `eslint-config-eslint package.json`?
> It's still `"node": "^8.10.0 || ^10.13.0 || >=11.10.1"`

Should we update the `engine` field in this PR, because the change made so far in this PR basically requires `catch {}`, which isn't supported in `8.10.0`?

**Comment by yeonjuan** [comment]
> Should we update the engine field in this PR, because the change made so far in this PR basically requires catch {}, which isn't supported in 8.10.0?

IMO, it's not strongly necessary for this PR. 😀

**Comment by aladdin-add** [comment]
well, I've created a PR #13379 to update it.

**Pull request merged**
