### PR TITLE
Update: `no-underscore-dangle`, add list of allowed identifiers

### PR DESCRIPTION
**Pull request by Antonius-S**
#### Prerequisites checklist

- [x ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Extend rule options to allow defining a list of identifiers after which underscored members won't produce a report.

```
no-underscore-dangle: ["error", { "allowAfter": [ "self" ] }]
```

```js
const self = this;
some.on('event', function() {
  self._private();
});
```

Just a proposal. I made it for myself and it seems to work. If team accepts the change, I could do all the proper stuff - testing, PR decoration, docs and so on. If change won't be accepted, I don't want to do useless work.

### CODE REVIEW

**Comment by btmills** [comment]
Hi @Antonius-S :wave: Thank you for taking the time to contribute to ESLint. We [recently froze changes to stylistic rules](https://eslint.org/blog/2020/05/changes-to-rules-policies) in core so that the team can dedicate more effort to our [roadmap](https://github.com/orgs/eslint/projects/1). I'll close this because we aren't changing `no-underscore-dangle` right now. However, I took a look at the code, and it looks like you're well on your way to creating your own version of `no-underscore-dangle`. I'd encourage you to release it as a plugin, and if you do, please share in the `#lookwhatimade` channel in our [Discord chat](https://eslint.org/chat)!

**Comment by Antonius-S** [comment]
Hi @btmills sounds surprising considering pretty much similar changes in recent commit history... And making the whole plugin just for little modification is hardly a right way. Probably with current freezing of rules a mechanism of user-defined rules should be added.

**Comment by btmills** [comment]
> a mechanism of user-defined rules should be added.

If creating a plugin for your rule sounds like overkill, you can use the [`--rulesdir` command line option](https://eslint.org/docs/user-guide/command-line-interface#specifying-rules-and-plugins) to tell ESLint where to find your rule.

**Comment by Antonius-S** [comment]
Looks promising, I'll give it a try. Thanks!

**Comment by Antonius-S** [comment]
Reworked this rule along with several others to use as custom rule set in https://github.com/Antonius-S/ESLint-custom-rules

**Pull request closed without merging**
