### PR TITLE
Fix: Curly rule incorrectly flagging lexical declarations (fixes #11663)

### LINKED ISSUE #11663: curly: multi-or-nest should allow lexical declarations to have braces for single-statement blocks
**What rule do you want to change?**
curly

**Does this change cause the rule to produce more or fewer warnings?**
fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
The `multi-or-nest` option should allow single-statement blocks with lexical declarations (`let`, `const`, `function`, and `class`) to have braces.

**Please provide some example code that this change will affect:**

```js
if (foo) {
  const bar = 'baz';
}
```

**What does the rule currently do for this code?**
ESLint outputs the error "Unnecessary { after 'if' condition." if the `multi-or-nest` option is set. After this is fixed:
```js
if (foo)
  const bar = 'baz';
```
it outputs the error "Parsing error: Unexpected token const" as lexical declarations need to be in a block.

**What will the rule do after it's changed?**
The `multi-or-nest` option would allow the code and not output any errors.

**Are you willing to submit a pull request to implement this change?**
I would if I could, but I'm not great at coding.

### PR DESCRIPTION
**Pull request by BRKurek**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

**What changes did you make? (Give an overview)**
Added a lexical declaration check to the `multi-or-nest` curly rule to prevent single line lexical declarations from being flagged as errors. See #11663 

**Is there anything you'd like reviewers to focus on?**
Nothing specific

### CODE REVIEW

**Comment by platinumazure** [comment]
Thanks for the PR!

What should happen to `var` declarations? Are they allowed inside control statement bodies as single statements?

**Comment by BRKurek** [comment]
I think we should keep handling `var` declarations the way we do now -- if they are inside a control statement body as a single statement the brackets should not be there when using curly with `multi-or-nest`. The reason we're adjusting the logic for `const`, `let`, `function`, and `class` is that they need to exist inside a block, so removing the brackets causes a parsing error.

**Comment by platinumazure** [comment]
Wow, I didn't realize `var` was valid syntax there. I had assumed it would also be invalid syntax. But I've just tested it in espree and it is indeed valid.

In that case, I agree with your proposed direction.

**Comment by BRKurek** [comment]
There was not an existing test for that case, added.

**Comment by BRKurek** [comment]
No problem!

**Pull request merged**
