### PR TITLE
Update: Adds ConditionalExpression option to indent rule (fixes #12968)

### LINKED ISSUE #1234: vars-on-top documentation is lying
The documentation of the `vars-on-top` rule says that it only requires var-statements to be on the top of functions but it also warns if a var-statement is not on the top of the global scope.

### LINKED ISSUE #12968: Indent rule's flatTernaryExpressions option isn't working
**Tell us about your environment**

**Node version:** v10.19.0
**npm version:** v6.13.4
**Local ESLint version:** v6.8.0
**Global ESLint version:** Not found

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
	'env': {
		'browser': true,
		'es6': true
	},
	'extends': 'eslint:recommended',
	'globals': {
		'Atomics': 'readonly',
		'SharedArrayBuffer': 'readonly'
	},
	'parserOptions': {
		'ecmaFeatures': {
			'jsx': true
		},
		'ecmaVersion': 2018,
		'sourceType': 'module'
	},
	'plugins': ['react'],
	'rules': {
		'indent': [
			'error',
			'tab',
			{
				flatTernaryExpressions: true,
				MemberExpression: 0,
				SwitchCase: 1,
			},
		],
	},
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
let func

func = ({
	hello,
	someone,
}) =>
	someone
	? someone
	: hello

func = ({
	hello,
	someone,
}) => (
	someone
	? someone
	: hello
)

const test = (
	func()
	? (
		blah
		? 'phil'
		: 'kevin'
	)
	: 'jacob'
)

func
test
```

```bash
yarn eslint index.js
```

**What did you expect to happen?**
I expected it allow ternaries to be flat; thus, not requiring a tab before the `?` and `:`.

**What actually happened? Please include the actual, raw output from ESLint.**
```sh
  17:1  error  Expected indentation of 1 tab but found 0   indent
  65:1  error  Expected indentation of 2 tabs but found 1  indent
  66:1  error  Expected indentation of 2 tabs but found 1  indent
  73:1  error  Expected indentation of 2 tabs but found 1  indent
  74:1  error  Expected indentation of 2 tabs but found 1  indent
  81:1  error  Expected indentation of 2 tabs but found 1  indent
  82:1  error  Expected indentation of 3 tabs but found 2  indent
  83:1  error  Expected indentation of 4 tabs but found 2  indent
  84:1  error  Expected indentation of 4 tabs but found 2  indent
  85:1  error  Expected indentation of 2 tabs but found 1  indent
  86:1  error  Expected indentation of 2 tabs but found 1  indent

✖ 11 problems (11 errors, 0 warnings)
  11 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Are you willing to submit a pull request to fix this bug?**
Yes.

### PR DESCRIPTION
**Pull request by Sawtaytoes**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [ ] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

https://github.com/eslint/eslint/issues/12968

**What rule do you want to change?**
`indent`

**Does this change cause the rule to produce more or fewer warnings?**
No change in warnings.

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option.

**Please provide some example code that this change will affect:**

Setting `ConditionalExpression: 1` (default):
```js
let func

func = ({
  hello,
  someone,
}) =>
  someone
    ? someone
    : hello

func = ({
  hello,
  someone,
}) => (
  someone
    ? someone
    : hello
)

const test = (
  func()
    ? (
      blah
        ? 'phil'
        : 'kevin'
    )
    : 'jacob'
)

func
test
```

Setting `ConditionalExpression: 0` (my intended use case):
```js
let func

func = ({
  hello,
  someone,
}) =>
  someone
  ? someone
  : hello

func = ({
  hello,
  someone,
}) => (
  someone
  ? someone
  : hello
)

const test = (
  func()
  ? (
    blah
    ? 'phil'
    : 'kevin'
  )
  : 'jacob'
)

func
test
```

**What does the rule currently do for this code?**
It has the expression 1 depth further out from the `?` and `:`.

**What will the rule do after it's changed?**
Allow altering the depth of `ConditionalExpression` to any value instead of the hardcoded value of `1`. Default behavior is unchanged.

Also, plays nicely with the unpublished `offsetTernaryExpressions`.

#### What changes did you make? (Give an overview)
Added `ConditionalExpression` to `indent` which allows modifying this value to anything other than `1`. The specific use case in question is `0`.

#### Is there anything you'd like reviewers to focus on?
Nothing.

### CODE REVIEW

**Comment by Sawtaytoes** [comment]
It won't let me sign the CLA as I've done it already with my GitHub account. Also, it's not seeing that I added that other email address as my GitHub email. Not really sure what to do about that.

**Comment by kaicataldo** [comment]
It looks like the CLA check has passed - maybe there was some delay.

Regarding this proposal, the indent rule is already quite complex and I'm a bit concerned with how complicated configuring ternaries is getting.

**Comment by Sawtaytoes** [comment]
@kaicataldo I completely understand your concern.

I thought about this for a while. The solution to fixing `indent`'s growing complexity is splitting it into multiple rules like `indent-ternary` and `indent-array-elements`.

Right now, `indent` is a "god rule" in ESLint. It fixes every tabbing issues caused by other auto-fix rules. Without it, the majority of auto-fix rules wouldn't work correctly. So while it may add complexity, the ideal solution is splitting up `indent`. Then all these customization options would make more sense.

`indent` is also not something I could easily fork and fix because of the `offsets` functions. If these were moved out into a utils package that I could import at will, then I could fork and fix this on my own and leave those changes out of ESLint.

The way it is right now, ternary formatting is lacking. We can only mimic what Prettier does, but if I wanted Prettier, I'd used it instead. With `indent`, all the other configuration options are necessary to their respective AST type, so I'm simply adding one for ternaries because of an existing need I have in my projects at home and work.

**Comment by Sawtaytoes** [comment]
PR is now passing all checks.

**Comment by Sawtaytoes** [comment]
I'll take a look. It's been a while since I last looked at this code, but I can go back and see what I can do.

**Comment by kaicataldo** [comment]
The team has made the difficult decision to freeze stylistic rules (please see https://eslint.org/blog/2020/05/changes-to-rules-policies for more details), and we unfortunately won't be able to accept this proposal.

Thanks for contributing to ESLint and for being willing to implement your proposal.

**Pull request closed without merging**
