### PR TITLE
Update: Add "multiline" type to padding-line-between-statements

### PR DESCRIPTION
**Pull request by Lobstrosity**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Adds `multiline-expression` statement type to existing `padding-line-between-statements` rule.

**Is there anything you'd like reviewers to focus on?**

n/a

**What rule do you want to change?**

`padding-line-between-statements`

**Does this change cause the rule to produce more or fewer warnings?**

More (or at least never fewer)

**How will the change be implemented? (New option, new default behavior, etc.)?**

Adds `multiline-expression` property to existing `StatementTypes` object (basically a copy/paste of the existing `expression` property and a copy/paste of the line numbers check from existing `multiline-block-like` property).

**Please provide some example code that this change will affect:**

Given the following rule:

```js
"padding-line-between-statements": [
  "error",
  { "blankLine": "always", "prev": "*", "next": "multiline-expression" }
]
```

The following code (single-line expression without padding line) is **correct**:

```js
const promise = fetch();
promise.then(console.dir);
```

The following code (multi-line expression with padding line) is **correct**:

```js
const promise = fetch();

promise.then(data => {
  console.dir(data);
});
```

The following code (multi-line expression without padding line) is **incorrect**:

```js
const promise = fetch();
promise.then(data => {
  console.dir(data);
});
```

**What does the rule currently do for this code?**

Currently, no warnings/errors emitted for any of the samples above.

**What will the rule do after it's changed?**

No warnings/errors will be produced for the **correct** samples. An error will be produced for the **incorrect** sample.

### CODE REVIEW

**Comment by platinumazure** [comment]
Seems reasonable (and useful), :+1: from me.

**Comment by kaicataldo** [comment]
@eslint/eslint-team Looks like this just needs a champion to move forward.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this proposal didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement this as a custom rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Comment by Aladdin-ADD** [comment]
since #9491 has been accept, shall we reopen this PR, and marked accepted?

**Comment by platinumazure** [comment]
I've reopened this PR, thanks!

@Lobstrosity If you're still willing to work on this, here's what we need:

* We'll the CLA signed before we can accept this contribution.
* In addition, please make sure that this PR addresses the proposal we accepted in #9491, or at least has only minor differences. (I haven't checked yet, I'm not saying this PR definitely doesn't match the proposal.)

Thanks for your patience as we worked through our process!

**Comment by Lobstrosity** [comment]
@platinumazure: Thank you for re-evaluating.

I have signed the CLA.

And I have added test cases to confirm that with this rule:

```js
{ blankLine: "always", prev: "multiline-expression", next: "return" }
```

The following are **correct**:

```js
() => {
  someArray.forEach(x => doSomething(x));
  return theThing;
}
```

```js
() => {
  someArray.forEach(
    x => doSomething(x)
  );

  return theThing;
}
```

But this is **incorrect**:

```js
() => {
  someArray.forEach(
    x => doSomething(x)
  );
  return theThing;
}
```

**Comment by platinumazure** [comment]
@Lobstrosity Thanks, awesome work! I apologize for letting this sit so long. Not sure we can get this into today's release (at least, I'd like one more reviewer before merging); but if we miss today's, it should definitely get in next release. Thanks for contributing!

**Comment by platinumazure** [comment]
Thanks for contributing, @Lobstrosity! And I'm glad we could finally get this in-- thanks for your patience!

**Pull request merged**
