### PR TITLE
chore: add version to rules

### PR DESCRIPTION
**Pull request by DeepshikaS**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Reference : https://github.com/eslint/eslint/issues/16008

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]
LGTM, thank you for contributing ⭐

**Review by snitin315 — CHANGES_REQUESTED** [review]
To fix the lint, can you also add `Version` to the know headers array?

https://github.com/eslint/eslint/blob/103860ef7e627175257ba583349cf0cd36792e5a/Makefile.js#L833

**Review by mdjermanovic — COMMENTED** [review]
Thanks for working on this! But I'm not sure if we want to add this section manually to each rule as it is done in this PR, or automatically generate it from Git history as we do for the current website. so I'll ask @nzakas what the plan was.

**Review by nzakas — CHANGES_REQUESTED** [review]
Thanks for this, but we need to insert this data automatically because we won’t know the correct version for new rules until the release is made. We currently calculate the release version during release and automatically update the docs (in Makefile.JS). For the new site, we want to do the same thing and generate/update a data file with the version info.

**Comment by nzakas** [comment]
Closing in favor of https://github.com/eslint/eslint/pull/16036

**Pull request closed without merging**
