### PR TITLE
Docs: add more examples in no-plusplus

### LINKED ISSUE #11343: `no-plusplus` rule errors with valid JS code, requires more code as workaround
**What rule do you want to change?**
`no-plusplus`

**Does this change cause the rule to produce more or fewer warnings?**
fewer, depends on approach taken to solve it

**How will the change be implemented? (New option, new default behavior, etc.)?**
I'm here to suggest a change in a high-level, haven't looked at the source code to suggest a solution implementation.

**Please provide some example code that this change will affect:**
```js
let a = 1;
let b;
let c = b || a++;
```

**What does the rule currently do for this code?**
At the moment the above throws a violation of the `no-plusplus` rule. The only workaround for satisfying the rule is to increment `a` in a new statement to have the same effect, because:
`let c = b || a+=1;` (which is the recommended solution from the docs) throws `Uncaught ReferenceError: Invalid left-hand side in assignment`, and
`let c = b || (a+1);` increments `a` **before** assigning to `c`, which isn't the intention here.

**What will the rule do after it's changed?**
It should either allow  valid statements like the above or only throw a warning instead of an error

**Are you willing to submit a pull request to implement this change?**
Possibly, haven't looked at the source code yet.

### PR DESCRIPTION
**Pull request by g-plane**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update

**What changes did you make? (Give an overview)**
I noticed #11343 , so I add more examples in the documentation.
Closes #11343 

**Is there anything you'd like reviewers to focus on?**
No.

### CODE REVIEW

**Comment by kureci** [comment]
`var baz = input || bar++` will give a _different_ result from `var baz = input || (bar += 1)`
See my comment [https://github.com/eslint/eslint/issues/11343#issuecomment-463151284](here)

If you want to see the result try running these two lines in your browser console, the former will do a 'post-increment' after assigning to `baz` whereas `(bar += 1)` will increment `bar` and **then** assign to `baz`

**Comment by g-plane** [comment]
Oh right, should I change to `++bar`?

**Comment by kureci** [comment]
@g-plane `++bar` is the same as `(bar += 1)` :)
I'd say just remove that example, because at the moment statements like `var baz = input || bar++` is just not supported by the `no-plusplus` rule and should be written in two separate lines:
```
var baz = input || bar;
bar++;
```
Unfortunately there is no easy way to get around it and we might just need to disable the rule if we want to write code like above in a single line, as stated [in this comment on the isssue](https://github.com/eslint/eslint/issues/11343#issuecomment-463158534)

**Comment by g-plane** [comment]
@kureci So do you have any ideas on this PR?

**Comment by kureci** [comment]
I'd say undo it :( because right now it's wrong.

**Pull request closed without merging**
