### PR TITLE
feat: docs license

### PR DESCRIPTION
**Pull request by sam3k**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)
Currently we don't have a documentation-specific license, so it defaults to all rights reserved. As discussed in the [tsc-meeting in 2023-03-09](https://github.com/eslint/tsc-meetings/blob/main/notes/2023/2023-03-09.md#documentation-specific-license), we are going to license the docs under [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/).

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes: https://github.com/eslint/eslint/issues/16980

#### What changes did you make? (Give an overview)
I've added the the following license change to the docs footer as agreed:

> © OpenJS Foundation and ESLint contributors, [www.openjsf.org](https://www.openjsf.org/). Content licensed under [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/).

#### Is there anything you'd like reviewers to focus on?
I was only able to preview the English version; but did the change to `zh-hans.yml` as well.

### CODE REVIEW

**Review by nzakas — APPROVED** [review]
LGTM. Would like one other review to verify before merging.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by stbischof** [comment]
1. Since this Project is specified to have default MIT License [here](https://github.com/eslint/eslint/blob/main/LICENSE) and [here](https://camo.githubusercontent.com/ca0a233b5442fba44471d76afe67ffb991fd317428a75c36cf944b1de247f425/68747470733a2f2f6170702e666f7373612e696f2f6170692f70726f6a656374732f67697425324268747470732533412532462532466769746875622e636f6d25324665736c696e7425324665736c696e742e7376673f747970653d6c61726765)  your argument seems  wrong:

```
Currently we don't have a documentation-specific license, so it defaults to all rights reserved. 
```

2. Public founded Projects in Germany are now very often having open Source Rules:

Since [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/) is not compatible to OpenSource  - [see Rules for Open Source in public founded projects](https://wikijs.opencode.de/de/Hilfestellungen_und_Richtlinien/Lizenzcompliance) .

They are not allowed to use/work on this projects with this public money. Since a Developer must write not only code but also docs its now impossible to contribute.

**Comment by Rec0iL99** [comment]
> 1. Since this Project is specified to have default MIT License [here](https://github.com/eslint/eslint/blob/main/LICENSE) and [here](https://camo.githubusercontent.com/ca0a233b5442fba44471d76afe67ffb991fd317428a75c36cf944b1de247f425/68747470733a2f2f6170702e666f7373612e696f2f6170692f70726f6a656374732f67697425324268747470732533412532462532466769746875622e636f6d25324665736c696e7425324665736c696e742e7376673f747970653d6c61726765)  your argument seems  wrong:
> 
> ```
> Currently we don't have a documentation-specific license, so it defaults to all rights reserved. 
> ```
> 
> 2. MIT - license covers `and associated documentation`
>    so the PR is braking the license of source
> 
> ```
> Permission is hereby granted, free of charge, to any person obtaining a copy
> of this software and associated documentation files (the "Software"),
> ```
> 
> 3. Public founded Projects in Germany are now very often having open Source Rules:
> 
> Since [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/) is not compatible to OpenSource - [see Rules for Open Source in public founded projects](https://wikijs.opencode.de/de/Hilfestellungen_und_Richtlinien/Lizenzcompliance) .
> 
> They are not allowed to use/work on this projects with this public money. Since a Developer must write not only code but also docs its now impossible to contribute.

@stbischof has opened a discussion for the same in #17175.

**Pull request merged**
