### PR TITLE
Update: Add automated suggestion to `radix` rule for parsing decimal numbers

### PR DESCRIPTION
**Pull request by bmish**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What rule do you want to change?**

[radix](https://eslint.org/docs/rules/radix)

**Does this change cause the rule to produce more or fewer warnings?**

No.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New automated suggestion.

**What does the rule currently do for this code?**

Does not provide an automated suggestion nor autofix.

**What will the rule do after it's changed?**

Provide an automated suggestion to change 

```js
parseInt('123');
```

to

```js
parseInt('123', 10);
```

because parsing decimal numbers is the most common use case.

#### What changes did you make? (Give an overview)

Added a suggestion fixer function and tests.

#### Is there anything you'd like reviewers to focus on?

No.

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Thanks for the PR! I support this enhancement :+1:

**Review by nzakas — APPROVED** [review]
LGTM. Thanks.

**Comment by fisker** [comment]
Is trailing comma case tested? `parserInt(10,)`

**Comment by bmish** [comment]
> Is trailing comma case tested? `parserInt(10,)`

@fisker good idea, added that test case.

**Comment by fisker** [comment]
Edge case `parseInt(  (0, 10)  )` will fail.

**Comment by nzakas** [comment]
@fisker can you provide what it would be fixed to as well?

**Comment by fisker** [comment]
I think a better fix should check the penultimate token, if it's a comma token, insert `10,`, if not insert `10`, both insert before the last token `)`

**Comment by bmish** [comment]
I'll give that a try.

One other question, does it sound good for me to add suggestions for other common radix parameters? I think octal (8) and hexadecimal (16) are the other common ones.

**Comment by fisker** [comment]
Oh , I'm sorry, I fogot the second argument maybe already exists, maybe just check that  fist argument `isParenthesized` is simplier.

**Comment by fisker** [comment]
> add suggestions for other common radix

I don't think that will be useful, if it's missing most time its's just forgot `10`, but if it's not a valid `radix` I think most time it's just typo. My suggestion a little different https://github.com/eslint/eslint/issues/14356

**Comment by bmish** [comment]
@fisker I added handling for the sequence expression. Good catch on that.

For now, I'll keep only one suggestion.

**Comment by fisker** [comment]
LGTM

**Comment by nzakas** [comment]
@eslint/eslint-tsc can I get another pair of eyes on this?

**Review by btmills — APPROVED** [review]
Good idea! LGTM

**Pull request merged**
