### PR TITLE
chore: replace yorkie with simple-git-hooks

### PR DESCRIPTION
**Pull request by kecrily**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

update dependency

#### What changes did you make? (Give an overview)

Replace yorkie with simple-git-hooks.

[yorkie was last updated five years ago](https://github.com/yyx990803/yorkie/commit/a4cf01d789da2633a33a888b496fa35395e72109) and is apparently no longer being maintained. And its authors use simple-git-hooks instead of yorkie in their own projects ([vue](https://github.com/vuejs/core/blob/3be4e3cbe34b394096210897c1be8deeb6d748d8/package.json#L96), [vite](https://github.com/vitejs/vite/blob/4f582c91d7e0e17c144fadf02a2b2ff485973ab5/package.json#L85)).

### CODE REVIEW

**Review by nzakas — APPROVED** [review]
Okay with me. We'll need to do the same thing in the other repos, as well.

I'm not sure, but I think this will have no effect until people run `npm install` again.

Would like @mdjermanovic to review before merging.

**Comment by mdjermanovic** [comment]
Some issues with simple-git-hooks were mentioned in https://github.com/eslint/eslint/pull/14243, and we decided to stick with yorkie.

**Comment by harish-sethuraman** [comment]
May be we could try better alternatives (if we decide to move away from yorkie)? if `simple-git-hooks` has some issues that we can't handle we can maybe choose [husky](https://typicode.github.io/husky/) over it. may repos (webpack loaders, reactjs site, lexical, etc...) consume husky.

**Comment by kecrily** [comment]
> Some issues with simple-git-hooks were mentioned in #14243, and we decided to stick with yorkie.

I think that things have changed.

- Vue doesn't use yorkie anymore.
- It turns out we don't really need automatic updates that much. This is because according to the commit, we haven't changed it since it was introduced.

**Comment by amareshsm** [comment]
> May be we could try better alternatives (if we decide to move away from yorkie)? if `simple-git-hooks` has some issues that we can't handle we can maybe choose [husky](https://typicode.github.io/husky/) over it. may repos (webpack loaders, reactjs site, lexical, etc...) consume husky.

we already discussed [husky](https://typicode.github.io/husky/) decided to use yorkie instead of husky. https://github.com/eslint/eslint.org/pull/292#issuecomment-1203354690
https://github.com/eslint/eslint.org/pull/292#discussion_r936139399

**Comment by nzakas** [comment]
Okay, after reviewing the others issues and discussions, let's just stick with yorkie. It's working for us right now, and until we end up having problems with it, we'll just stick with it.

**Comment by kecrily** [comment]
Looking at yorkie's PR list, we can see that it has problems with nvm installed with brew under macOS.

While we haven't seen anyone in eslint encounter this problem yet, we can't rule out the possibility that someone will encounter it in the future, or that someone has already encountered it without feedback.

**Pull request closed without merging**
