### PR TITLE
Docs: Fix anchor in 'docs/developer-guide/working-with-rules.md' 

### PR DESCRIPTION
**Pull request by Nate-Wilkins**
#### What is the purpose of this pull request?

[X] Documentation update

#### What changes did you make? (Give an overview)

Fixes the `getSourceCode()` anchor ref.

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]
Thanks!

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

Can you please sign our [CLA](https://cla.js.foundation/eslint/eslint?pullRequest=14332), so we could merge this?

**Comment by Nate-Wilkins** [comment]
Signed :+1:

**Comment by mdjermanovic** [comment]
Thanks for contributing!

**Pull request merged**
