### PR TITLE
docs: update documentation URL in error message

### PR DESCRIPTION
**Pull request by snitin315**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Fix https://github.com/eslint/eslint/issues/17463

#### Is there anything you'd like reviewers to focus on?
Nothing

### CODE REVIEW

**Review by fasttime — APPROVED** [review]
LGTM, thanks! I'm going to merge this with prefix "docs:", since this fix only affects the documentation.

**Comment by snitin315** [comment]
I feel it should be `fix`, since this changes the error message which is part of source code and will require a version bump for users to take effect.

**Comment by fasttime** [comment]
> I feel it should be `fix`, since this changes the error message which is part of source code and will require a version bump for users to take effect.

Ah okay, I recall a similar PR being merged as "docs:", so I assumed this would be the case for this one, too. I'll see if I can find a reference.

**Comment by fasttime** [comment]
@snitin315 Not exactly the same but [this comment](https://github.com/eslint/eslint/pull/17051#issuecomment-1496405293) advises using "docs:" for a change in a rule's description, which also takes a version bump to update, at least for the tools that use that information.

**Comment by snitin315** [comment]
I see. Should be fine then.

**Pull request merged**
