### PR TITLE
Docs: no-mixed-operators - fixes #9962

### LINKED ISSUE #9962: Docs: no-mixed-operators - allowSamePrecedence option docs improvement
**Tell us about your environment**
N/A (macOS Sierra 10.12.6)

* **ESLint Version:**
v4.17.0

* **Node Version:**
N/A (v8.9.1)

* **npm Version:**
N/A (v5.5.1)

**What parser (default, Babel-ESLint, etc.) are you using?**
N/A (default)

**Please show your full configuration:**
N/A

**What did you expect to happen?**
The `allowSamePrecedence` option of the `no-mixed-operators` rule should correctly document "Examples of incorrect code for this rule with `{"allowSamePrecedence": false}` option".

**What actually happened? Please include the actual, raw output from ESLint.**
The documentation is incorrect, as it is the same as "Examples of correct code for this rule with {"allowSamePrecedence": true} option":
```js
/*eslint no-mixed-operators: ["error", {"allowSamePrecedence": true}]*/

// + and - have the same precedence.
var foo = a + b - c;
```
```js
/*eslint no-mixed-operators: ["error", {"allowSamePrecedence": false}]*/

// + and - have the same precedence.
var foo = a + b - c;
```

This should simply be changed to something like this:
```js
/*eslint no-mixed-operators: ["error", {"allowSamePrecedence": false}]*/

// + and * have different precedence.
var foo = a + b * c;
```

### PR DESCRIPTION
**Pull request by munkychop**
**What is the purpose of this pull request? (put an "X" next to item)**

[x ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Improved documentation for `no-mixed-operators` rule - `allowSamePrecedence` option.

**Is there anything you'd like reviewers to focus on?**
N/A

### CODE REVIEW

**Comment by platinumazure** [comment]
Thanks @munkychop!

Would you mind tweaking your commit message so that it ends with "(fixes #9962)"? (Unfortunately, our commit-message status check is not yet smart enough to detect when an issue is referenced but it doesn't *quite* meet our preferred format.)

**Comment by munkychop** [comment]
Sure thing, I'll update that now

**Comment by platinumazure** [comment]
Thanks @munkychop!

I'm sorry for being so specific but we like parentheses around the issue reference. So maybe something like "Docs: Clarify no-mixed-operators options (fixes #9962)"?

Really appreciate you sticking with this and working with us. Thanks!

**Comment by munkychop** [comment]
Ah, I see. Sure thing.

**Comment by platinumazure** [comment]
Thanks @munkychop, this looks great! I'm going to just let this sit for a few hours in case any other team members want to look, but we'll probably merge this pretty soon.

Thanks for contributing and fixing our docs, we really appreciate it.

**Comment by not-an-aardvark** [comment]
Thanks for contributing!

**Pull request merged**
