### PR TITLE
Docs: Add missing `meta.docs.suggestion` property in some examples

### PR DESCRIPTION
**Pull request by bmish**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Updated some documentation examples and test cases to include the `meta.docs.suggestion` property when providing suggestions. Previously, usage of this property was inconsistent which could be confusing to developers hoping to correctly implement their own suggestions.

These changes were extracted from #14292.

### CODE REVIEW

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by nzakas** [comment]
I don’t think these changes make sense given how this field is being used currently (which is to say, not in a way that it matters for plugin rules).

I’d rather we come up with a coherent story for whether or not this field should be included and why before outing examples throughout our docs.

**Comment by mdjermanovic** [comment]
We're already mentioning this field in the document:

https://eslint.org/docs/developer-guide/working-with-rules#rule-basics

> suggestion (boolean) specifies whether rules can return suggestions (defaults to false if omitted)

**Comment by bmish** [comment]
Hmm, I thought this property was already part of the public API as @mdjermanovic mentioned, so I was just updating the examples to consistently use it, i.e. no change in status quo.

As I mentioned in #14292, there seems to be some confusion / lack of consistency around this property, so maybe we should consider reevaluating it in a separate discussion.

**Comment by nzakas** [comment]
I know we have this property documented, however, as already pointed out, we are actually not enforcing its usage for rules with suggestions. I think adding examples of something that isn’t properly implemented will only serve to confuse people more than they status quo.

I’d rather not call attention to something that doesn’t work as described and would prefer we just delete its mention from the documentation until we decide if we want to introduce a formal meta.suggestions property that is enforced.

**Comment by bmish** [comment]
@nzakas Sounds good, I opened this issue to discuss: #14312.

**Pull request closed without merging**
