### PR TITLE
It is not io.js anymore, but Node.js

### PR DESCRIPTION
**Pull request by thefourtheye**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Could you prefix your commit message with "Docs:"

**Comment by thefourtheye** [comment]
@ilyavolodin I am sorry, I am not in front of a computer right now. If you are landing it now, can you please fix that while landing? I'll remember the format from the next time onwards.

**Comment by IanVS** [comment]
Also, if you haven't already signed the CLA, could you please do so? http://eslint.org/cla/

**Comment by thefourtheye** [comment]
@ilyavolodin Updated the commit message. PTAL.
@IanVS Done! :-)

**Pull request merged**
