### PR TITLE
Support proposal-nullish-coalescing-operator

### PR DESCRIPTION
**Pull request by Hypnosphi**
https://tc39.github.io/proposal-nullish-coalescing/

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 8.11.2
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
`babel-eslint@`

**Please show your full configuration:**
```
{
  "root": true,
  "parser": "babel-eslint",
  "extends": [
    "@jetbrains",
    "@jetbrains/eslint-config/browser",
    "@jetbrains/eslint-config/es6",
    "@jetbrains/eslint-config/react",
    "@jetbrains/eslint-config/test",
    "plugin:flowtype/recommended",
    "prettier",
    "prettier/flowtype",
    "prettier/react",
  ],
  "env": {
    "browser": true,
    "mocha": false
  },
  "rules": {
    "flowtype-errors/show-errors": "error",
    "flowtype-errors/enforce-min-coverage": ["error", 80],

    "linebreak-style": "off",
    "complexity": "off",

    "react/sort-comp": "off",
    "react/prop-types": "off",
    "sort-class-members/sort-class-members": ["error", {
      "order": [
        "[static-properties]",
        "[static-methods]",
        "[properties]",
        "constructor",
        "UNSAFE_componentWillMount",
        "componentDidMount",
        "UNSAFE_componentWillReceiveProps",
        "shouldComponentUpdate",
        "UNSAFE_componentWillUpdate",
        "getSnapshotBeforeUpdate",
        "componentDidUpdate",
        "componentWillUnmount",
        "[arrow-function-properties]",
        "[methods]",
        "render",
      ],
    }],

    "prettier/prettier": ["error", {
      "printWidth": 100,
      "semi": false,
      "singleQuote": true,
      "trailingComma": "all",
      "bracketSpacing": false
    }],

    "import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": [
          "**/*.test.js",
          "**/*.stories.js",
          "**/load-tests.js",
          "**/StoryUtils.js"
        ],
        "optionalDependencies": false,
        "peerDependencies": false
      }
    ],

    "no-magic-numbers": ["error", { "ignore": [-1, 0, 1, 2] }],
  },
  "globals": {
    "BS": true,
    "base_uri": true,
    "internalProps": true,
    "_tc_es": true,
  },
  "settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": true
    }
  },
  "plugins": [
    "flowtype",
    "flowtype-errors",
    "sort-class-members",
    "prettier"
  ],
  "overrides": [
    {
      "files": ["load-tests.js", "**/*.test.js"],
      "env": {
        "mocha": true
      },
      "rules": {
        "no-magic-numbers": "off",
        "quotes": ["error", {"avoidEscape": true}],
        "react/jsx-no-bind": "off",
        "react/jsx-no-literals": "off"
      },
      "globals": {
        "sandbox": false,
        "expect": false
      }
    },
    {
      "files": ["**/*.stories.js"],
      "env": {
        "commonjs": true
      },
      "rules": {
        "react/jsx-no-literals": "off"
      }
    },
    {
      "files": ["reactui.js"],
      "rules": {
        "flowtype-errors/enforce-min-coverage": "off"
      }
    }
  ]
}

```

**What did you do? Please include the actual source code causing the issue.**
```
const a = null
const b = a ?? 'default'
```

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
```
unreachable
Error: unreachable
    at CodePathState.popChoiceContext (/Users/jetbrains/Perforce/Filipp.Riabchun_unit-951_3393/react-ui/node_modules/eslint/lib/code-path-analysis/code-path-state.js:444:23)
    at processCodePathToExit (/Users/jetbrains/Perforce/Filipp.Riabchun_unit-951_3393/react-ui/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:434:19)
    at CodePathAnalyzer.leaveNode (/Users/jetbrains/Perforce/Filipp.Riabchun_unit-951_3393/react-ui/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:627:9)
    at Traverser.leave [as _leave] (/Users/jetbrains/Perforce/Filipp.Riabchun_unit-951_3393/react-ui/node_modules/eslint/lib/linter.js:868:28)
    at Traverser._traverse (/Users/jetbrains/Perforce/Filipp.Riabchun_unit-951_3393/react-ui/node_modules/eslint/lib/util/traverser.js:155:18)
    at Traverser._traverse (/Users/jetbrains/Perforce/Filipp.Riabchun_unit-951_3393/react-ui/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (/Users/jetbrains/Perforce/Filipp.Riabchun_unit-951_3393/react-ui/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser._traverse (/Users/jetbrains/Perforce/Filipp.Riabchun_unit-951_3393/react-ui/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser.traverse (/Users/jetbrains/Perforce/Filipp.Riabchun_unit-951_3393/react-ui/node_modules/eslint/lib/util/traverser.js:115:14)
    at runRules (/Users/jetbrains/Perforce/Filipp.Riabchun_unit-951_3393/react-ui/node_modules/eslint/lib/linter.js:862:15)

```

See https://github.com/babel/babel-eslint/issues/611

I'm not sure what's the proper place to add tests for this

**What changes did you make? (Give an overview)**
Thanks to @lehni for actually making the change, namely making `??` behave similarly to `||`

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by kaicataldo** [comment]
Thanks for contributing. In general, ESLint support anything below stage 4 in core. This is tricky, though, because as of right now I don't believe there are no official APIs that would allow babel-eslint to enable this behavior.

**Comment by cpojer** [comment]
Hey @kaicataldo,

I think you are absolutely right that eslint should only support stage 4 proposals, however as you point out right now there is no way to support this feature from a custom parser. I think we can consider finding a way for these operators to be configurable from the parser in the future, however this is a very minor change to eslint at this time that doesn't seem to me like it would have deep negative implications for eslint if this PR was merged.

To provide some more context, we are currently rolling this syntax feature out all across Facebook. This eslint issue is the remaining blocker for us before we can do this. We believe this is a reasonable proposal to solve a real problem people have at Facebook and we'd love to gather experience through usage in a large codebase like ours that we can then take to TC39 to drive the feature through the standards process or advice against adding it to ECMAScript if it turns out not to be a good proposal. This syntax feature in particular seems very easy to codemod away with a reasonable replacement so we are ok to give this a shot. Our only alternative is to maintain a fork of eslint which puts maintenance burden on us that we'd prefer not to take. Thanks so much for considering this :)

**Comment by platinumazure** [comment]
I've created #10441 for long-term discussion. I'd like to see if we can get a design out quickly there.

If not, I wouldn't be completely opposed to putting something in temporarily now as long as we can mark it as experimental/non-semver and that we can remove it as soon as possible.

That said, let's see if we can figure out a long-term solution quickly so we don't need to take that step... :smile:

**Comment by not-an-aardvark** [comment]
Is there a way we could make this change more generic? It would be nice if ESLint could avoid crashing on any custom operators, including `??`.

One of the reasons we don't generally support experimental syntax is that it's difficult to keep our support up to date, particularly if a proposal ends up changing (so the same AST might end up with two different sets of semantics depending on whether the user is targetting an earlier version of the proposal).

Instead of adding special logic for `??` here, I'm wondering if it would be possible to add a general "unknown operator fallback" behavior instead. That way, ESLint could have reasonable behavior (e.g. not crashing, providing mostly-correct code path info) for all custom operators, and we wouldn't need to explicitly support any particular version of an experimental proposal.

In the long term, I think it would be nice to allow parsers to provide code path information, but that doesn't need to block this issue.

**Comment by platinumazure** [comment]
@not-an-aardvark I think we could avoid crashing, but I don't think we can do a generic change that simultaneously allows for correct operator precedence or code path analysis without requiring input. So there would be a lot of false negatives or positives on no-extra-parens, etc.

That might be okay in the short term if we also encourage people to write custom versions of those rules, I suppose. Maybe that's what you have in mind?

**Comment by not-an-aardvark** [comment]
Yes, I agree that it wouldn't be possible to be both generic and correct in every case here. I'm hoping we could be incorrect in the least-intrusive way (e.g. by allowing rules to have false negatives for that syntax while still correctly handling the rest of the AST, and allowing users to create custom rules for that syntax to fill in the gaps).

My mental model here is that ESLint core should ideally be able to run on any arbitrary AST objects that it's given, but with core rules most bets are off (although we can try to make things work reasonably well in core rules for ASTs which are only slightly different from ESTree ASTs). That way, users can fill in the gaps with custom rules without being blocked by a crash like this in ESLint core.

**Comment by BYK** [comment]
How about hiding the unknown operator fallback behind a flag so the default is to crash/error with a message pointing to the flag? This would solve the problem in a fairly safe way since you need to willingly opt into the "unknown behavior" land? It would also unblock people in this specific case.

Alternatively, we may allow providing the precedence information in a config parameter?

**Comment by not-an-aardvark** [comment]
In general, I don't want ESLint core to be a blocker for any operators that people want to add, including `??`. I think requiring a command-line flag to use a specific custom operator wouldn't scale well for when other operators are added, or for when the behavior of an operator changes.

There are a lot of places where core rules aren't built to handle custom syntax, and our general approach has always to let people use custom rules to handle that case without adding support for custom syntax to ESLint core. I think we should do the same thing here -- the only difference is that ESLint core is currently crashing when it encounters that operator. If we update the code to avoid crashing by providing a default fallback, we can unblock people in this case without committing to maintaining support for experimental syntax.

**Comment by BYK** [comment]
>If we update the code to avoid crashing by providing a default fallback, we can unblock people in this case without committing to maintaining support for experimental syntax.

Sounds good to me. Shall I send a PR for that?

@cpojer would that work for you folks?

**Comment by platinumazure** [comment]
I think instead of merging this directly, the goal would be to have a changeset that sets a sensible default operator precedence and code path functionality for unknown operators. In other words, there should be no direct mention of `??`.

Let me know if I'm misunderstanding, @not-an-aardvark.

**Comment by not-an-aardvark** [comment]
Yes, that's correct.

**Comment by lehni** [comment]
For what it's worth: I'm the author of the original commit, and I've made available a workaround that can already be used until a proper fix makes its way into eslint:

https://github.com/babel/babel-eslint/issues/611#issuecomment-388809054

**Comment by pvdz** [comment]
It sounds like an immediate fix is not going to be committed and released any time soon. May I suggest an alternative that may be quicker to be accepted and allow us to unblock ourselves without putting too much of a burden on the ESLint team?

What if there was a plugin that is a callback `ast -> ast` that would be called immediately after the parsing step? It would accept the AST as-is and return an AST as-eslint-expects it. This way the parser can do whatever it wants, the ast plugin could scrub/babel/modify the AST to conform to ESLint's expectation and ESLint has almost zero burden regarding the maintenance here.

In this particular example, such a plugin could take the AST, walk the tree, replace the `operator` value of [`LogicalExpression`](https://github.com/estree/estree/blob/master/es5.md#logicalexpression) nodes from `??` to `||` and prevent ESLint crashing.

The impact for ESLint is an extra option, a callback to check, and to call immediately (and only) after the parsing step.

Would this be acceptable and possibly released quickly?

**Comment by rubennorte** [comment]
@pvdz that would work for us too and would be flexible enough to fix some other issues in the future. In this case, the only thing preventing us from adding new operators is that specific check in the code path analyzer. If we generalize it enough I think we can go around this without adding a new option (which may take more time). I'll create an alternative PR for this soon.

**Comment by not-an-aardvark** [comment]
@pvdz I'm not sure a step like that would be needed because ESLint already allows parsers to provide any AST. As a result, amy transformation like this could already be achieved within a parser itself by simply running the transformation on an original result before returning the AST to ESLint as a parse result.

**Comment by kaicataldo** [comment]
To add some more context, this is actually how both `babel-eslint` and `typescript-eslint-parser` actually work - they use @babel/parser and typescript under the hood to generate the initial AST and then run transformations over it to make it ESTree compatible.

**Comment by platinumazure** [comment]
Is this PR still needed?

**Comment by rubennorte** [comment]
@platinumazure, #10476 got merged, so it shouldn't be necessary.

**Pull request closed without merging**
