### PR TITLE
Fix: arraysInObjects for object-curly-spacing (fixes #275)

### PR DESCRIPTION
**Pull request by xjamundx**
Quick port from the existing space-in-brackets rule of this missing exception

### CODE REVIEW

**Comment by ilyavolodin** [comment]
@xjamundx You forgot to add a schema to this rule with the initial pull request. Could you add it now please?

**Comment by xjamundx** [comment]
I knew I missed something :)

**Comment by xjamundx** [comment]
Will work on this now!

**Comment by xjamundx** [comment]
@ilyavolodin let me know if that will work

**Comment by ilyavolodin** [comment]
LGTM

**Pull request merged**
