### PR TITLE
Update inquirer

### PR DESCRIPTION
**Pull request by TrySound**
Lodash was updated. Dep tree will be 1mb less.

### CODE REVIEW

**Comment by platinumazure** [comment]
Per the eslintbot comment above, we need at least the following:

1. Please sign our CLA if you haven't done so
1. Please modify your commit message to begin with "Upgrade:"
1. Please modify your commit message to end with "(fixes #1111)" where 1111 is an issue related to this fix

Thanks!

**Comment by TrySound** [comment]
@platinumazure Should I create issue for this?

**Comment by ilyavolodin** [comment]
@TrySound Yes please

**Comment by gyandeeps** [comment]
@IanVS Can you please verify this update?

**Comment by IanVS** [comment]
I don't see anything that looks like it would give us trouble.  Tried it out and seems to work okay.

**Comment by gyandeeps** [comment]
@TrySound Can u also sign our [CLA](http://eslint.org/cla/) if you have not done it already?

**Comment by TrySound** [comment]
@gyandeeps I done it already.

**Comment by gyandeeps** [comment]
k. Thanks

**Pull request merged**
