### PR TITLE
Update: Allow var declaration at end of block (fixes #5246)

### LINKED ISSUE #5246: eslint 2.0 newline-after-var bug with brackets
```javascript
var cond = true;

if (cond) {
    var foo = 1;
}
```
Output:
```
4:5  error  Expected blank line after variable declarations  newline-after-var
```

Rule `newline-after-var` must be ignored brackets. 
```javascript
var cond = true;

if (cond) {
    var foo = 1;
    var bar = 1;
}
```
Also with bugs.

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
I'm not 100% sure this is a fix. This looks more like an update to me, since this functionality didn't exist before.

**Comment by nzakas** [comment]
Agree, this is an update

**Comment by alberto** [comment]
Ok, updated.

**Comment by btmills** [comment]
LGTM.

**Pull request merged**
