### PR TITLE
Build: Do not stub console in testing (fixes #1328)

### LINKED ISSUE #1328: Don’t stub console.log
The [cli test](https://github.com/eslint/eslint/blob/976aac7a43e1def7140025e56469879224a48282/tests/lib/cli.js#L24-L25) stubs `console.log` and `console.error`. As mocha is using `console.log` in its reporters we probably don’t get some assertion errors printed to the console (see #1325).

I suggest to use `sinon.spy` instead.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5026756-don-t-stub-console-log?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**
* Need some suggestions on the file name.

### CODE REVIEW

**Comment by nzakas** [comment]
Nice! Maybe instead of `logging`, do `out`? I don't know, naming is hard. :)

**Comment by gyandeeps** [comment]
Why I used the name `logging` is because then we can use the same file for https://github.com/eslint/eslint/issues/1961 enhancement. Still no strong opinion.

**Comment by nzakas** [comment]
Ah interesting, I also don't have a strong opinion since we're not exposing this API. I'm fine with leaving as `logging`, we can always change later if we don't like it.

**Comment by gyandeeps** [comment]
sounds good. :+1:

**Pull request merged**
