### PR TITLE
Build: re-add phantomjs dependency with locked down version (fixes #3026)

### LINKED ISSUE #3026: Missing dependency when using npm v3
In #3022 the phantomjs dependency was removed, which still works with npm v2 because npm automatically installs missing peer dependencies. This behavior changed with npm v3, where peer dependencies won’t be automatically installed.

```
$ npm -v
3.1.1
$ npm install
npm WARN EPEERINVALID mocha-phantomjs@3.5.4 requires a peer of phantomjs@1.9.1 - 1.9.7-15 but none was installed.
```

So if you install the eslint dependencies with npm v3 `npm test` won’t work anymore:

```
$ npm test
module.js:334
    throw err;
          ^
Error: Cannot find module 'phantomjs'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mschreck/workspace/eslint/node_modules/mocha-phantomjs/bin/mocha-phantomjs:140:17)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:467:10)
npm ERR! Test failed.  See above for more details.
```

### PR DESCRIPTION
**Pull request by lo1tuma**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Why do we need it at this point?

**Comment by gyandeeps** [comment]
I think to prepare for npm 3 each module has to take care of that. So basically we are covering for them. Shouldn't we report that as an issue on their repo.

**Comment by IanVS** [comment]
Looks like they are already planning to revert: https://github.com/nathanboktae/mocha-phantomjs/issues/167#issuecomment-121768039

**Comment by nzakas** [comment]
Can someone give a clear description of what's going on with this? I've been trying to follow, but the rapid-fire changes have me a bit confused.

**Comment by IanVS** [comment]
Here's how I understand it:

- Mocha-phantomjs has a peer dependency on phantomjs.
- ESLint had a dev dependency on phantomjs
- Mocha-phantomjs locked down the version of phantomjs in their peer dependency.  
  - This is bad practice, because it forces consuming projects to specify exactly that version, or remove the dependency on phantomjs
- phantomjs was removed from ESLint deps in https://github.com/eslint/eslint/pull/3022/
- However, peer dependencies are changing between npm v2 and v3
  - In v2, they are automatically installed into the parent project.  That is why https://github.com/eslint/eslint/pull/3022 fixed the immediate problems
  - In npm v3, peer dependencies are no longer automatically installed, so https://github.com/eslint/eslint/pull/3022/ does not work with npm v3. see https://github.com/eslint/eslint/issues/3026

Moving forward:
- mocha-phantomjs is [reverting](https://github.com/nathanboktae/mocha-phantomjs/issues/167#issuecomment-121768039) their recent change which broke ESLint
- The lockdown of their peer dependency will become a [new minor version](https://github.com/nathanboktae/mocha-phantomjs/commit/297e1f2b06113886cb710647a4bc9ccc1dcf9dde)
- In their next major version, they will remove the peer dependency, and instead install as a direct dependency

Does that help at all?

**Comment by nzakas** [comment]
Yes, thanks. What a mess.

**Comment by lo1tuma** [comment]
@IanVS thanks for the summary :smiley:.

I’ve updated the PR and also locked down `mocha-phantomjs`.

**Pull request merged**
