### PR TITLE
Docs: Consistent wording in rules README

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Nice! The only thing, we should also modify rule's pages with the same changes.

**Comment by alberto** [comment]
Yeah, I originally intended to put this first for approval and ask about also changing the rules, but then I forgot  :sweat_smile:

**Comment by pedrottimark** [comment]
Super! You reduced the number of description prefixes from 20 to 8 verbs: disallow, encourage, enforce, ensure, require, restrict, specify, treat…as it

As suggested in https://github.com/eslint/eslint/pull/5630#issuecomment-198934420, how about a *common pattern* of rule-name: rule description

That is:
* in the rule list, s/ - /: /
* in rule pages, move the rule-name from the end to the beginning followed by colon instead of enclosed in parentheses, use the description from the list in most cases, therefore reduce capitalization from Title Caps to phrase capitalization

**Comment by alberto** [comment]
Do you think the list of verbs could be further reduced?

**Comment by alberto** [comment]
@pedrottimark where do you want to remove the suffixes from? I did a quick search and only found `(recommended)` and `(fixable)` in the README.

For the other proposed changes, can someone from @eslint/eslint-team confirm this is desired before I go and change all the rules docs?

**Comment by pedrottimark** [comment]
@alberto what I meant is that the rule descriptions in the list seem stronger than in the rule pages when there is a difference, but if we copy that text, we don’t want to bring (recommended) or (fixable) into the rule pages. Does that make sense?

To your previous https://github.com/eslint/eslint/pull/5630#issuecomment-199461859:
Yes, a good goal is to reduce the verbs so they correspond to **use cases** for rules.
By the way, unclear or inconsistentent noun phrases in rule descriptions have been on the back burner of my brain.

**Comment by kaicataldo** [comment]
Just for some context, currently (recommended) and (fixable) are used to add the icons on the rules list page: https://github.com/eslint/eslint.github.io/pull/180

Makes sense to me to not necessarily bring those labels into the rule page itself

**Comment by alberto** [comment]
@pedrottimark @kaicataldo thanks, now I see what you meant

**Comment by pedrottimark** [comment]
May I suggest wait on updates to the rule pages to avoid merge conflicts with the updates to sentences preceding example code?

You might want to look at pictures of some previously suggested, but not yet decided, improvements to the icons in rules list and rule pages:

* https://github.com/eslint/eslint.github.io/issues/186#issuecomment-196460629
* https://github.com/eslint/eslint.github.io/issues/186#issuecomment-196464881
* https://github.com/eslint/eslint.github.io/issues/186#issuecomment-196460152

They are independent of wording improvements, but the whole is more than the sum of the parts ;)

**Comment by alberto** [comment]
Ok, so I updated the README with the proposed changes for now. We can later create another PR for the rules.

**Comment by nzakas** [comment]
What's the verdict on merging this? Wait?

**Comment by pedrottimark** [comment]
This is a great step forward, which seems well worth merging.

Because it is so much easier to see potential improvements in the context of the entire list, how about leaving open the opportunity to iterate on it a few times before updating the rule pages? Their headings have been inconsistent with the list for a while now, from previous rounds of editing.

Is it time to change from lists to tables with check mark and wrench icon at the left? I could make a follow-up pull request soon. It depends on just one more replace rule in the doc.html layout file at eslint.github.io

**Comment by nzakas** [comment]
@pedrottimark I don't care how many times we iterate as long as things are improving. My only concern is that the longer these doc change PRs sit, the more potential for problems as documentation is being updated and added. I just want to keep things moving.

**Comment by pedrottimark** [comment]
:+1:

**Pull request merged**
