### PR TITLE
Docs: add extra space after comma

### PR DESCRIPTION
**Pull request by Ky6uk**

### CODE REVIEW

**Comment by greg5green** [comment]
The change itself looks good, but the CI tests are failing because the commit message guidelines weren't met @Ky6uk

**Comment by alberto** [comment]
Thanks @Ky6uk. I'm sorry that you had trouble making the build pass. I have submitted https://github.com/eslint/eslint/pull/5370 with the fix.

**Comment by Ky6uk** [comment]
@alberto np. I just don't want to spend much time for typofix like that. I expected two-clicks-fix :hammer:.  Also, your CI tests looks failed too. :cat:

**Comment by IanVS** [comment]
@Ky6uk Yes, our requirements are pretty strict, which is unfortunate for small changes like this, but they help us keep a useful and curated changelog for each version.  I hope you're enjoying ESLint and that we haven't chased you off from contributing.  The guide is at http://eslint.org/docs/developer-guide/contributing/ if you find anything else that needs changing.  :)

**Pull request closed without merging**
