### PR TITLE
Docs: Make env match ecmaVersion in example

### PR DESCRIPTION
**Pull request by nfriedly**
**What issue does this pull request address?**
This is a docs improvement to help avoid the confusion I experienced in #6894

**What changes did you make? (Give an overview)**
Added es6 env to example config where ecmaVersion is set to 6

**Is there anything you'd like reviewers to focus on?**
No

### CODE REVIEW

**Comment by vitorbal** [comment]
Thanks, @nfriedly! LGTM, but waiting another day for others to take a look.

**Comment by nfriedly** [comment]
Actually, after reading @ilyavolodin's comments on #6894, I'm not sure this makes as much sense. `es6: true` implies `ecmaVersion: 6` so having both seems unnecessary.  But the example I changed in this PR is supposed to show how to use `parserOptions`, not environments, so I'm not sure it's the right approach now. 

Maybe we should just a note calling that the es6 env is probably what you want (?) 

Or maybe a different example that comes higher up and has the es6 env instead of the ecmaVersion.

(or perhaps both)

I'm not sure, but I think it deserves a bit more thought.

**Comment by nzakas** [comment]
I agree, this doesn't seem to be the correct area to make a change. 

In general, I'm not sure this is a big problem as `--init` is most frequently used to setup configs and will do this for you.

**Comment by nfriedly** [comment]
Yea, I think the problem is that it's the first example on the page. 

To give a background story, my co-worker, who wasn't aware of `--init`, went to http://eslint.org/docs/user-guide/configuring looked at the example and thought "yea, that's about what I want - ES6 and JSX", and copy-pasted it as his starting point.

Initially everything worked fine because he wasn't using any of the new ES6 globals. But, a few days later, he asked me why it was choking with `error  'Set' is not defined  no-undef`. I glanced at it and thought `ecmaVersion: 6` seemed different than I remembered, but I'm no expert either. I checked the config page myself, read what it said about `ecmaVersion`, but didn't make the connection that it only enables half of what I think of as "ES6". And sure enough, removing that line caused a lot more errors from ES6 stuff. So we just put `Set` in `globals` and went on with out business. 

But it kept nagging me, because it just didn't feel "right". So I came back to it and after banging my head into things for a while, I eventually semi-figured it out and filed this and the other ticket. And, then with more help, I realized that even this "fix" wasn't very good.

So, that's a long-winded way of saying that I do think there's room for improvement on that documentation page. Either a different example config that comes higher up on the page with a more common config, and/or a note in the `parserOptions` section to clarify that `ecmaVersion: 6` is only half of what a naive user like myself thinks of as "ES6".  

This would have saved my colleague and I several hours of head-banging, and presumably it would prove helpful to other users also.

**Comment by nzakas** [comment]
Okay, it sounds like we all agree that this isn't the right fix, so closing. If you'd like to propose another solution o the problem you had, feel free to open another PR.

**Pull request closed without merging**
