### PR TITLE
Update: no-restricted-imports custom message for patterns (fixes #11843)

### LINKED ISSUE #11843: Support for "message" with "patterns" in `no-restricted-imports`
Creating a new request for a [closed issue](https://github.com/eslint/eslint/issues/11134), as suggested [here](https://github.com/eslint/eslint/issues/11134#issuecomment-498474195).

**What rule do you want to change?** no-restricted-imports

**Does this change cause the rule to produce more or fewer warnings?** Neither

**How will the change be implemented? (New option, new default behavior, etc.)?** Allow a new format for an existing option

**Please provide some example code that this change will affect:**

```js
// I can currently customize the error message for restricted path imports like this
import * as moment from 'moment';
// But I can't customize the error message for restricted pattern imports like this
import { Button } from '../../framework/buttons';
```

What I'd like to do in my ESLint config:

```json
{
  "rules": {
    "no-restricted-imports": ["error", {
      "paths": [{"name": "moment", "message": "Don't import moment"}],
      "patterns": [{"name": "**/framework/*", "message": "Only import from the root of /framework"}]
    }]
  }
}
```

**What does the rule currently do for this code?** I can't customize the error message for the restricted pattern import

**What will the rule do after it's changed?** It should allow me to customize the error message for the restricted pattern import

**Are you willing to submit a pull request to implement this change?** Sure, though I'd like to get some clarity on how difficult the "large option schema change" mentioned [here](https://github.com/eslint/eslint/issues/11134#issuecomment-442213289) would be.

### PR DESCRIPTION
**Pull request by lexholden**
…

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

As per the spec agreed upon in https://github.com/eslint/eslint/issues/11843 - the rule `no-restricted-imports` now allows multiple patterns to be grouped together with a message that is logged if any match fails

For example, `{ patterns: [{ group: ["foo/*", "bar/*"], message: "'foo' and 'bar' are deprecated, please use 'baz' instead." }] }` would log error `'foo/some/subimport' import is restricted from being used by a pattern. 'foo' and 'bar' are deprecated, please use 'baz' instead.`

#### Is there anything you'd like reviewers to focus on?

Wrote this for a personal project, but happy to tweak anything required to shepherd it through any part of the community process that I've missed from the contributor guidelines or add some more robust test edge cases if proposed.

### CODE REVIEW

**Review by mdjermanovic — CHANGES_REQUESTED** [review]
@lexholden thanks for the PR! This looks very good, but the schema needs some modifications. I also left some suggestions about the docs and tests.

**Comment by lexholden** [comment]
@mdjermanovic thanks for the excellent suggestions, agree with all of them and pushed the changed. Let me know if you think of anything else.

**Review by mdjermanovic — CHANGES_REQUESTED** [review]
This looks great, I just missed in the first review that we should also add to docs some [examples](https://eslint.org/docs/rules/no-restricted-imports#examples) of incorrect/correct code with the new configuration.

It can be something like this

incorrect:

```js
/*eslint no-restricted-imports: ["error", { patterns: [{
    group: ["lodash/*"],
    message: "Please use the default import from 'lodash' instead."
}]}]*/

import pick from 'lodash/pick';
```

correct:

```js
/*eslint no-restricted-imports: ["error", { patterns: [{
    group: ["lodash/*"],
    message: "Please use the default import from 'lodash' instead."
}]}]*/

import lodash from 'lodash';
```

**Comment by lexholden** [comment]
@mdjermanovic good point. Done.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by mdjermanovic** [comment]
Thanks for contributing!

**Comment by maxisam** [comment]
Thank you @lexholden This is a great feature!

**Pull request merged**
