### PR TITLE
feat: cli init: support modules installation via yarn or pnpm

### PR DESCRIPTION
**Pull request by ninofiliu**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

- [ ] Documentation update
- [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
- [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
- [ ] Add autofixing to a rule
- [x] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)

When running `npx eslint --init`, we get asked questions that generates an eslint config, which might required additional packages to be installed. We then get asked whether we want ESLint to install them for us, but we can only install them with @npm.

I'm a fan of @pnpm and we use @yarnpkg over here at @toucantoco so I figured out it'd be nice to add support for these alternatives too!

Here's a demo: https://asciinema.org/a/446868

#### Is there anything you'd like reviewers to focus on?

Everything is self-explanatory I think

### CODE REVIEW

**Comment by nzakas** [comment]
Have your tried running this locally for setup a project? The last time we attempted to add Yarn support there was an issue with running Yarn inside of —init (can’t remember the exact issue but it did sideline the attempt)

**Comment by ninofiliu** [comment]
@nzakas yes it seems to work smoothly both [on a demo codebase](https://asciinema.org/a/446951) and [on the big yarn codebase](https://asciinema.org/a/446952) that is our main product at @toucantoco

**Comment by ninofiliu** [comment]
Do I have to manually increment the minor version btw? Or will a bot do that

**Comment by mdjermanovic** [comment]
`eslint --init` functionality is now frozen, because we're working on a new package that will replace `eslint --init` (https://github.com/eslint/eslint/issues/14768). Support for `yarn` and `pnpm` is planned for the new package (https://github.com/eslint/eslint/issues/13645).

Here's a previous attempt to support yarn: https://github.com/eslint/eslint/pull/13756

We found an issue in the case where locally installed ESLint has to be replaced with another version due to peer dependency requirements of selected configs and plugins, so we decided to postpone this feature and implement it in the new package. Another problem was with how yarn stores dependency requirements in `package.json`. Both problems are described in https://github.com/eslint/eslint/pull/13756#issuecomment-737624127.

**Comment by ninofiliu** [comment]
@mdjermanovic oh okay, thanks for the precise infos! Since `eslint --init` is frozen & will be replaced by a package that'll support yarn and pnpm, I'm closing this

**Pull request closed without merging**
