### PR TITLE
docs: Fixing Focus Order by Rearranging Element Sequence

### PR DESCRIPTION
**Pull request by amareshsm**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:
Fixing Focus Order by Rearranging Element Sequence.

Ref: https://github.com/eslint/eslint.org/pull/615#issuecomment-2299003407

#### What changes did you make? (Give an overview)
similar to https://github.com/eslint/eslint.org/pull/673

### CODE REVIEW

**Comment by nzakas** [comment]
I think we may need a bit of JavaScript here to hide the dropdown once you tab out of it. Otherwise, the focus moves to the Algolia link behind the dropdown.

Screenshot 2024-12-16 110610

**Comment by amareshsm** [comment]
> I think we may need a bit of JavaScript here to hide the dropdown once you tab out of it. Otherwise, the focus moves to the Algolia link behind the dropdown.
> 
> Screenshot 2024-12-16 110610

done.

**Review by Tanujkanti4441 — APPROVED** [review]
LGTM, thanks.

Would like another team member to review this.

**Review by nzakas — APPROVED** [review]
LGTM. Nice work.

**Pull request merged**
