### PR TITLE
fix: Ensure crash error messages are not duplicated

### LINKED ISSUE #17560: Bug: Duplicate error message displayed when flat config contains eslintrc top-level key
### Environment

Node version: v18.16.0
npm version: v7.10.0
Local ESLint version: v8.49.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19045

### What parser are you using?

Default (Espree)

### What did you do?

Created an `eslint.config.js` file with `globals` as a top-level key.

<details>
<summary>Configuration</summary>

```
export default [
    {
        globals: {},
    }
];

```
</details>

```js
let x = 1;
```

### What did you expect to happen?

I should get an error message explaining that `globals` is invalid.

### What actually happened?

I got two error messages explaining that `globals` is invalid.

```
$ npm run lint

> @humanwhocodes/env@3.0.0 lint
> eslint src/ tests/


Oops! Something went wrong! :(

ESLint: 8.47.0

A config object is using the "globals" key, which is not supported in flat config system.

Flat config uses "languageOptions.globals" to define global variables for your files.

Please see the following page for information on how to convert your config object into the correct format:   
https://eslint.org/docs/latest/use/configure/migration-guide#configuring-language-options

Oops! Something went wrong! :(

ESLint: 8.47.0

A config object is using the "globals" key, which is not supported in flat config system.

Flat config uses "languageOptions.globals" to define global variables for your files.

Please see the following page for information on how to convert your config object into the correct format:   
https://eslint.org/docs/latest/use/configure/migration-guide#configuring-language-options
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-yk4rv3

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Interestingly, the StackBlitz repro doesn't show this behavior but I'm able to reproduce it consistently locally (on Windows in VS Code).

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Ensures that the CLI will only output each crash error message once by saving all displayed messages into a set and then checking that before displaying again.

Fixes #17560

#### Is there anything you'd like reviewers to focus on?

I tried and failed a couple of times to create an automated test to reproduce the behavior described in #17560. I could use some help coming up with one.

### CODE REVIEW

**Review by BYK — APPROVED** [review]
Implementation LGTM. ~~Looking into ways for automated tests tho.~~

Couldn't find any way to reproduce this. We may just want to add some comments in the code to raise awareness.

**Comment by nzakas** [comment]
@mdjermanovic can you take a look at this?

**Comment by mdjermanovic** [comment]
Here's a test that fails for me locally before this change and passes after this change: https://github.com/eslint/eslint/commit/fe54b062a2dc2e5fbb4596088c4b1c29799b52a1

To try it out:

```
git fetch origin
git checkout origin/issue17560-test
npm test
```

**Comment by mdjermanovic** [comment]
Here's another test, this one is similar to the scenario described in https://github.com/eslint/eslint/issues/17560: https://github.com/eslint/eslint/commit/be43092c5940a21455cef523f6967b1b080fdace

```
git fetch origin
git checkout origin/issue17560-test-2
npm test
```

It's failing for me locally (Windows) before this change, but it might be working in other environments, and whether it would really produce duplicate errors before this change depends on the implementation of dependencies, so it might be better to use the more generic test I left in my previous comment, or perhaps add both.

**Comment by fasttime** [comment]
> Here's another test, this one is similar to the scenario described in #17560: [be43092](https://github.com/eslint/eslint/commit/be43092c5940a21455cef523f6967b1b080fdace)
> 
> ```
> git fetch origin
> git checkout origin/issue17560-test-2
> npm test
> ```
> 
> It's failing for me locally (Windows) before this change, but it might be working in other environments, and whether it would really produce duplicate errors without this change depends on the implementation of dependencies, so it might be better to use the more generic test I left in my previous comment, or perhaps add both.

Locally on macOS this test is failing for me but it passes after the changes in the PR are applied. So it's the same as on Windows.

**Comment by nzakas** [comment]
I'll add both tests. 👍

**Comment by nzakas** [comment]
Confirmed that both tests also fail for me, so looks like we are covered.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
