### PR TITLE
Update: make the rule 'no-sync' more exact

### PR DESCRIPTION
**Pull request by lingxiaoguang**
**What is the purpose of this pull request? (put an "X" next to item)**

[] Documentation update
[] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Changed the rule's selector to make it more accurate.  The previous rule would report errors when dealing with attributes, but the correct one should be that only methods would report errors.

```
let options = {
     cacheUpdateSync: true
}
if (options.cacheUpdateSync) {
}
```
Like this, ‘cacheUpdateSync’ is an attribute and reports an error
```
Unexpected sync method: 'cacheUpdateSync'. (no-sync)
```

In fact, only methods should report errors.

The following way will report errors, because  the `obj.cacheUpdateSync`  is a method
```
obj.cacheUpdateSync();
```
```
let func = obj.cacheUpdateSync;
func()
```
```
func = obj.cacheUpdateSync;
func()
```
I considered all the cases, only direct invocation, initialization, assignment need to check.

**Is there anything you'd like reviewers to focus on?**

As above

### CODE REVIEW

**Comment by lingxiaoguang** [comment]
> [CLA assistant check](https://cla.js.foundation/eslint/eslint?pullRequest=11266) 
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.js.foundation/eslint/eslint?pullRequest=11266) before we can accept your contribution.

Ok

**Comment by lingxiaoguang** [comment]
> Thanks for the pull request. Can you explain more about the problem you are trying to address? It's not clear from your description. (Also, note that the automated testing has failed for this pull request.)

I don't know why so many errors have been reported here. I just changed the rules and tests of ‘no-sync’.There are 125 errors in total.

**Comment by kaicataldo** [comment]
@lingxiaoguang Are you saying that tests aren't failing in your local environment? They look like valid test failures to me.

**Comment by kaicataldo** [comment]
@lingxiaoguang Friendly ping

**Comment by lingxiaoguang** [comment]
(My english is poor.)
Sorry, I forgot it in these days. 
I did this  because of the problem I encountered.  It tells me don't use methods which name end with 'Sync', but I just use an attribute. So I spent some time to improve it. Not familiar with the flow and not solve the test errors carefully spent many time.
Today  I found my way doesn't solve the problem completely, so I want to close it.

**Pull request closed without merging**
