### PR TITLE
Chore: add isValidThisArg in ast-utils.

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Other, please explain:

**What changes did you make? (Give an overview)**
`isValidThisArg` is used both in `no-useless-call.js` and `prefer-spread.js`. placed it in ast-utils in case some other rules will use it.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
IMO, it might be better to export `equalTokens` from `ast-utils` rather than `isValidThisArg`, because `equalTokens` seems like it's more useful in general. But I'm fine with either.

**Comment by Aladdin-ADD** [comment]
> IMO, it might be better to export equalTokens from ast-utils rather than isValidThisArg, because equalTokens seems like it's more useful in general.

maybe we can export both?

**Comment by not-an-aardvark** [comment]
I'm fine with that too, although I think `isValidThisArg` is fairly small and situational compared to `equalTokens`.

**Comment by kaicataldo** [comment]
I'm fine with both too as long as we have test coverage :)

**Comment by Aladdin-ADD** [comment]
@not-an-aardvark @kaicataldo  updated the PR to export `equalTokens`, and added tests.

**Pull request merged**
