### PR TITLE
Docs: Specify language for all code fences, enable corresponding markdow...

### PR DESCRIPTION
**Pull request by DavidAnson**
...nlint rule.

Based on your feedback to avoid purely stylistic changes, this is probably the last markdownlint PR I'll propose. (Even this one could be a stretch.) As always, just let me know if it's not appropriate.

PS - Unless you'd like to get rid of multiple consecutive blank lines?

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Looks good.

**Comment by nzakas** [comment]
Yeah, I'm not sure if this actually matters or not. Is there a way to not require the language, but if present, it must be a valid option (no typos)?

**Comment by DavidAnson** [comment]
That was an idea I had, but it's not how the rule is currently implemented. I'll make a note and revisit this if/when that's available.

**Comment by nzakas** [comment]
Okay, let's give this a try.

**Comment by DavidAnson** [comment]
Cool. If it doesn't work out, please be aggressive about disabling rules. If you have feedback (like the above), please pass it on to me. If you find a bug or false positive, I definitely want to know!

**Pull request merged**
