### PR TITLE
New: add rule no-misspelled-length

### PR DESCRIPTION
**Pull request by eschaefer**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[X] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Please describe what the rule should do:**

Disallows misspelling the 'length' property.

**What category of rule is this? (place an "X" next to just one item)**

[ ] Enforces code style
[X] Warns about a potential error
[ ] Suggests an alternate way of doing something
[ ] Other (please specify:)

**Provide 2-3 code examples that this rule will warn about:**

```js
var wordLength = "Word".lenght;

if ("Foo".lnegth > 0) {
    return true;
}
```

**Why should this rule be included in ESLint (instead of a plugin)?**

A misspelled length property does not result in an error, but instead is valid (but buggy) Javascript code that tries to access an undefined property on an object.

This rule checks that if all sorted letters in the property accessor are found in 'length' as well, the property is probably misspelled.

**What changes did you make? (Give an overview)**

Added all code and tests relevant to making `no-misspelled-length` rule work as intended.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by eschaefer** [comment]
*specific* reactions and feedback appreciated!

**Comment by manucorporat** [comment]
Why not using typescript?

**Comment by mysticatea** [comment]
Thank you for your contribution.

- Adding a new feature requires a champion and 3 or more upvotes from the ESLint team on the issue.
- I think this rule is too specific to add to the ESLint core. You can provide the rule by your plugin.

**Comment by ljharb** [comment]
why about using .length on a map/set? What about:
```js
const obj = { lenght: 3 };
obj.lenght
```
?

**Comment by kaicataldo** [comment]
While it’s most likely someone is trying to access the `length` property in the example given above, I don’t think ESLint can make that assumption and disallow property names in a blanket way like that.

As @manucorporat suggests, type systems such as TypeScript or Flow seem like a much more precise way to avoid these sorts of errors.

If this is something you’d like to enforce, this seems like a great option for a custom rule!

**Comment by ilyavolodin** [comment]
This rule is way too narrow and specific for ESLint. Having a rule just for a single property in the core would set a precedence for other tiny rule and would blow already large number of rules out of control. Sorry, very much 👎 for adding it to the core. This is a perfect example of good plugin rule.

**Comment by platinumazure** [comment]
As a note, you could use `no-restricted-properties` and provide at least a few common misspellings to help catch this in your own codebase. That way, you don't even have to write a custom rule.

**Comment by eschaefer** [comment]
Thanks everyone! Sounds like a plugin is the way to go here. @platinumazure I will also look at using `no-restricted-properties` 👍

**Pull request closed without merging**
