### PR TITLE
Update: Ability to load plugins by path

### PR DESCRIPTION
**Pull request by mpal9000**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[X] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
See #6237 
Problem in PR #6016 with long plugin names on rule definitions, error messages and eslint comments solved

Example shareable config:
```json
{
  "name": "eslint-config-shareable",
  "version": "0.0.1",
  "dependencies": {
    "babel-eslint": "7.2.0",
    "eslint": "4.0.0-alpha.2",
    "eslint-plugin-fp": "2.3.0"
  }
}
```

```js
'use strict'

module.exports = {
  parser: require.resolve('babel-eslint'),

  plugins: [
    require.resolve('eslint-plugin-fp'),
  ],

  rules: {
    'fp/no-mutation': 'error',
  },
}
```

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the pull request.

Does this solve the issue described in https://github.com/eslint/eslint/issues/6237#issuecomment-301375357? I'm not sure it would be a good idea to move forward with this until we have a way to make sure plugins with the same name can't conflict with each other.

**Comment by mpal9000** [comment]
Hello

> Right now, this isn't a problem because plugins have to be in node_modules, so it's not possible to have two plugins with the same name.

Currently you can have two plugins with the same name, if they are not semver compatible, because they won't be both flattened.

I think a simple check inside `load()` method and a descriptive error message with plugin name, absolute path and version, is enough for that case.
ie.
```js
if (shortName in plugins) { throw DuplicatePluginError('...') }
```
instead of
```js
if (!plugins[shortName]) {...}
```
I'm using this PR with shareable configs for a few months without any problem (I don't have duplicates).
It is inline with `parser: require.resolve('babel-eslint')`, which is currently supported and also with how babel allows to define shareable configs, ie. with filepaths

We can also restrict "filepath" plugins to be valid node modules, by doing a similar to "pkg-up" lookup, but with searching only inside "node_modules" directories.

**Comment by not-an-aardvark** [comment]
> Currently you can have two plugins with the same name, if they are not semver compatible, because they won't be both flattened.

This is incorrect. Plugins are loaded from eslint itself, not the config that depends on them. As a result, a plugin in a nested `node_modules` folder won't be loaded at all. (This is why plugins are required to be `peerDependencies` in shareable configs -- also see #3458).

> I think a simple check inside `load()` method and a descriptive error message with plugin name, absolute path and version, is enough for that case.

In principle this might work, but it could cause a poor user experience when using shareable configs. For example, it's possible that two downloaded shareable configs could both reference two plugins with the same name using relative paths. If an error was thrown, the user wouldn't have any way to resolve this error, because they did not create either config.

**Comment by mpal9000** [comment]
If the plugins with the same name, are not the same plugin, one of the shareable configs is invalid, because plugins should be npm modules, even if they are defined with filepaths. In that case maybe the error is sufficient. If it's the same plugin and we need to support both of them at the same time, maybe they could be automatically suffixed with the package name of the shareable config. so the user could write something like
```js
rules: {
  'plugin-a/config-a/rule-a': 'error',
  'plugin-a/config-b/rule-b': 'warning',
},
```

**Comment by not-an-aardvark** [comment]
That's similar to my proposal in https://github.com/eslint/eslint/issues/3458#issuecomment-266594020. It might work, but there were a few team members that had concerns about it.

I would also like to resolve this issue, and I think it would be great if we could make things "just work" in the common case. However, I think the solution will require some discussion in https://github.com/eslint/eslint/issues/3458, and it seems like it will be more complicated than just throwing an error when plugins conflict. It might be better to move this discussion to https://github.com/eslint/eslint/issues/3458 so we don't end up rehashing the same discussion in multiple places.

**Comment by mpal9000** [comment]
All right. I think that the feature of shareable configs is important and we are talking about an edge case. I prefer to write prefixed plugin names if needed, or see errors about incompatible configs, than specifying dependencies for every package/app, again and again. I also believe that this problem can be solved in steps and that is why I made the PR. Because it is the minimum amount of code to make shareable configs work. Aliasing and prioritizing of conflicting plugins can be another step. Εspecially when the discussion is two years old.

**Comment by mpal9000** [comment]
I also prefer not being able to "extend" shareable configs with "recommended" configs of plugins, but only with the built in "eslint:recommended". At least temporarily

**Comment by not-an-aardvark** [comment]
I agree that this is an edge case which is blocking usability for more common cases. However, I don't think it's a good idea to rush to a solution here. Yes, your solution will generally work when the user isn't using a shareable config, but it will cause the same problems as the ones discussed in https://github.com/eslint/eslint/issues/3458 when the user is using a shareable config. The reason https://github.com/eslint/eslint/issues/3458 is hard is because we're not making special exceptions for the simple case -- it's important that all regular configs are usable as shareable configs, and vice versa.

Ultimately, I think a solution to this issue will also require a solution to https://github.com/eslint/eslint/issues/3458.

**Comment by not-an-aardvark** [comment]
Closing because I don't think this is a workable solution to https://github.com/eslint/eslint/issues/6237.

**Pull request closed without merging**
