### PR TITLE
Update: Brace style for `import` statements

### PR DESCRIPTION
**Pull request by IanSavchenko**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What rule do you want to change?**
brace-style

**Does this change cause the rule to produce more or fewer warnings?**
More warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
No new options, just more types of statements covered

**Please provide some example code that this change will affect:**

```js
// covers cases like this
import { a, b } from 'module';
```

**What does the rule currently do for this code?**
Currently, the rule does not process import statements.

**What will the rule do after it's changed?**
It will check if braces style in import statements with multiple specifiers is correct.

**What changes did you make? (Give an overview)**
Added support for `import` statements with multiple specifiers to be checked by the rule.

**Is there anything you'd like reviewers to focus on?**
Not really sure if this somehow should be also mentioned in the docs for the rule.

### CODE REVIEW

**Comment by platinumazure** [comment]
With this implementation, is there a way to allowSingleLine for import braces, but not for other statement types that use curly braces?

I think this should go behind an option, personally. It seems like an unnecessarily breaking change if done as a default behavior change.

**Comment by platinumazure** [comment]
Example style for why I think an option is needed:

```js
import { a, b } from "foo.js";   // allow single line here, maybe use max-len to control when we need to go multiline

if (bar) {                       // forbid single line here
}
```

**Comment by not-an-aardvark** [comment]
In my opinion, it doesn't really make sense to apply `brace-style` to import statements -- aesthetically they seem more similar to object literals than blocks.

**Comment by platinumazure** [comment]
True, maybe we should create import-curly-newline and import-specifier-newline to match object-curly-newline and object-property-newline?

**Comment by ljharb** [comment]
The rule is called "brace style", so anything with braces should be covered by this rule - destructuring, named import/export syntax, blocks, object literals, etc.

However, I definitely think it should be added behind an option.

**Comment by not-an-aardvark** [comment]
I'm skeptical that users have the same intuition about formatting `if` blocks as they do for formatting object literals. For example, I personally don't write code like `if (foo) { bar(); }` on one line, but I do write code like `foo({ a: 1 })` on one line. That's generally why we've used rules like `object-curly-newline` for objects rather than `brace-style`. (I think the `brace-style` rule was originally only supposed to apply to block statements, although we've extended it to apply to classes and `switch` bodies.)

**Comment by ljharb** [comment]
As long as all these things are controllable, separate rules would be fine too, but if the name of the rule is "brace style", then it should be able to apply to anything with curly braces.

**Comment by platinumazure** [comment]
> if the name of the rule is "brace style", then it should be able to apply to anything with curly braces

That's hardly fair when many of our earlier rules were inherited from or heavily based on JSHint rules, which are famously terse. We've been naming newer rules with longer and clearer names (object-curly-newline instead of curly-newline), but we can't reasonably impose a burden on our users by renaming old rules, at least not without a very good reason (and we would deprecate the old rule, not remove it). So, yes, the name "brace-style" is imprecise and it would be nice to change, but we have to keep usability in mind.

**Comment by not-an-aardvark** [comment]
I think the name of the rule is originally from ["One true brace style"](https://en.wikipedia.org/wiki/Indentation_style#Variant:_1TBS_(OTBS)).

**Comment by ljharb** [comment]
Indeed; and one true brace style conceptually governs import/export syntax braces too, as far as the airbnb guide is concerned :-)

**Comment by IanSavchenko** [comment]
Thanks for the discussion, guys! Probably, I should have had it before writing code, but I had some inspiration at that moment to code first...

As @not-an-aardvark pointed, it's actually closer to object destruction syntax and I agree with that. But I would also point out that there is 'from' keyword, so there are multiple possibilities to put a curly before it. `object-curly-newline` does not cover those styles as `brace-style`.  Also, there is some inconsistency among rules `object-curly-newline`, `object-curly-spacing` and `object-property-newline`, where `object-curly-spacing` rule governs `import` statements, but the other two rules do not.

So, I have seen following options on the thread:

1. Leave the changes in the `brace-style` rule. 
- As @platinumazure said, `allowSingleLine` probably needs separate treatment for import statements. I would probably say, that in this case every type of statement governed by the rule (blocks, `if`s, functions, etc) would need to have it's own config for consistency.
2. Move changes to `object-curly-newline` since the syntax is actually closer to it. 
- As I mentioned above, this probably will require some inconsistent options added, because `import` has also `from` part and the rule must say where to put the closing brace before it. This is set by different styles options like in `brace-style` (1tbs, Allman, Stroustrup).
3. Make a new rule something like `import-curly-newline`.
- Looks very flexible in all senses. It seems that import statements stand aside from other syntax and require separate treatment.
- As @platinumazure also suggested, there could be `import-specifier-newline` (and I actually happen to already have it implemented as a local rule).
- My concern is that right now there is no consistent approach to `import` statements in eslint. Different aspects are governed by different rules. For example, `object-curly-spacing` governs `import` also. Should this be changed and new "symmetrical" rule be introduced like `import-curly-spacing`? Do such breaking changes happen in eslint?
- Don't want to sidetrack the discussion, but JFYI I also have `padded-blocks` rule on my list that I suppose has to check import specifiers list to not have unnecessary empty lines. That's again a consistency concern.

**Comment by ilyavolodin** [comment]
I think another possibility is leave the change in the `brace-style` and put it behind an option.

**Comment by platinumazure** [comment]
This discussion appears to have stalled.

Where are we at? Do we potentially have consensus on one of the suggested approaches?

If not, is this something our TSC needs to look at and provide direction on?

**Comment by IanSavchenko** [comment]
I am ready to accept the possibility to set this behavior with an option flag as @ilyavolodin suggests. Or anything else you guys agree on.

Would it potentially look something like:
```
eslint brace-style: ["error", "1tbs", { 
  "allowSingleLine": false,
  "ImportDeclaration": ["stroustrup", {
     "allowSingleLine": true
   }]
}]
```

Another question: do the docs updates have to go in the same PR?

**Comment by nzakas** [comment]
@ilyavolodin @platinumazure @not-an-aardvark can any of you provide guidance on how to move this forward?

**Comment by nzakas** [comment]
Friendly ping @ilyavolodin @platinumazure @not-an-aardvark can any of you provide guidance on how to move this forward?

**Comment by ilyavolodin** [comment]
Sorry, didn't see the comments addressed to me. I think the right choice here is to put this behind a new option.

**Comment by ilyavolodin** [comment]
This PR has been open for a very long time without any movement. We are going to close it for now, if somebody wants to re-implement this change with suggested approach, please feel free to open a new PR.

**Pull request closed without merging**
