### PR TITLE
docs: use higher contrast color tokens for code comments

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes https://github.com/eslint/eslint.org/issues/665. Corresponds to https://github.com/eslint/eslint.org/pull/666.

#### What changes did you make? (Give an overview)

I swapped out the hardcoded comment colors with the closest theme tokens that had sufficient contrast.

<table>
<thead>
<tr>
<th>Mode
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>Light</td>
<td>'Before' screenshot in light mode of a code block with just barely too low contrast for code comments</td>
<td>'After' screenshot in light mode of a code block with just barely too low contrast for code comments</td>
</tr>
<tr>
<td>Dark</td>
<td>'Before' screenshot in dark mode of a code block with just barely too low contrast for code comments</td>
<td>'After' screenshot in dark mode of a code block with just barely enough contrast for code comments</td>
</tr>
</tbody>
</table>

#### Is there anything you'd like reviewers to focus on?

If there are other ad-hoc colors just barely off from color tokens, I'd be happy to clean those up in a followup?

### CODE REVIEW

**Review by Tanujkanti4441 — COMMENTED** [review]
Thanks for the PR!

But in no-js mode the color is still not bright can you please fix that also?

js mode
Screenshot 2024-11-28 121825

no-js mode
Screenshot 2024-11-28 121846

and CI is failing could it be because the branch is not up-to-date?

**Comment by JoshuaKGoldberg** [comment]
Ooh, interesting. That looks to me like a more root issue about text using light mode styles in dark mode when no-js is enabled. I think that's out of scope of this PR?

**Comment by JoshuaKGoldberg** [comment]
Oh! I was wrong, code comments just aren't using the same dark/light mode queries as most of the app. Updated.

**Review by Tanujkanti4441 — APPROVED** [review]
LGTM, thanks!

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
