### PR TITLE
docs: resubmit pr 17115 doc changes

### PR DESCRIPTION
**Pull request by aladdin-add**
credits: https://github.com/domdomegg

Refs:
* https://github.com/eslint/eslint/issues/17225
* https://github.com/eslint/eslint/pull/17115

#### Prerequisites checklist

- [ ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### CODE REVIEW

**Review by mdjermanovic — APPROVED** [review]
LGTM, but we have to ask the original author for permission to merge this.

**Comment by mdjermanovic** [comment]
@domdomegg unfortunately, we had to revert https://github.com/eslint/eslint/commit/af5fe64c398c9bd4206c3c6c1ade81768b291031 due to https://github.com/eslint/eslint/issues/17225. 

This PR submits the same changes. Would you like to resubmit the changes yourself, or give us permission to merge these changes (i.e, permission to merge this PR)?

**Review by snitin315 — APPROVED** [review]
LGTM. I feel we can merge if we don't get any response from the original other in the next few days.

cc @domdomegg

**Review by domdomegg — APPROVED** [review]
Apologies for the delay here, and thanks for the re-ping (without which I wouldn't have seen it).

LGTM

**Pull request merged**
