### PR TITLE
Docs: update space-in-parens related rules

### PR DESCRIPTION
**Pull request by brodybits**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

update space-in-parens related rules: remove the obsolete reference and add newer references

#### Is there anything you'd like reviewers to focus on?

references should no longer be deprecated

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Thanks for the PR! The change makes sense, `space-in-brackets` was deprecated and replaced by other rules a long time ago.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by brodybits** [comment]
Thanks !!

**Review by btmills — APPROVED** [review]
Thanks, this is helpful! LGTM

**Pull request merged**
