### PR TITLE
Chore: use `actions/setup-node@v2`

### PR DESCRIPTION
**Pull request by snitin315**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Other, please explain: CI related

#### What changes did you make? (Give an overview)

updated `setup-node`  action to `v2` for CI node workflow.

https://github.com/marketplace/actions/setup-node-js-environment

#### Is there anything you'd like reviewers to focus on?

No

### CODE REVIEW

**Review by bmish — APPROVED** [review]

**Review by mdjermanovic — COMMENTED** [review]
Should we also update [line 38](https://github.com/eslint/eslint/blob/6641d88e17d952a8e51df5e0d3882a842d4c3f35/.github/workflows/ci.yml#L38), and is there an overview of breaking changes in `v2`?

**Comment by bmish** [comment]
I was looking to find out if there were any breaking changes, it's hard to tell but doesn't look like it: https://github.com/actions/setup-node/releases

**Comment by mdjermanovic** [comment]
I found a question about v2 breaking changes (https://github.com/actions/setup-node/issues/223), as it seems that an overview of v2 is missing. By https://github.com/actions/setup-node/issues/223#issuecomment-763138835, it does look like there were no breaking changes.

**Review by aladdin-add — APPROVED** [review]

**Comment by snitin315** [comment]
> Should we also update [line 38](https://github.com/eslint/eslint/blob/6641d88e17d952a8e51df5e0d3882a842d4c3f35/.github/workflows/ci.yml#L38), and is there an overview of breaking changes in `v2`?

Yes, I missed that one. There aren't any breaking changes, we can update safely.

**Review by nzakas — APPROVED** [review]

**Pull request merged**
