### PR TITLE
Docs: Remove broken links to jslinterrors.com (fixes #7368)

### LINKED ISSUE #7368: Docs: Links to jslinterrors.com now go to an ads site
For example http://eslint.org/docs/rules/one-var links to http://jslinterrors.com/combine-this-with-the-previous-var-statement/

See: https://github.com/jamesallardice/jslint-error-explanations/issues/39

There [looks to be 17 pages with links to jslinterrors.com](https://github.com/eslint/eslint/search?utf8=%E2%9C%93&q=jslinterrors). I would've submitted a pull request removing the links, but I didn't know if there is somewhere else those pages can still be viewed? Perhaps they can be commented out until the domain is fixed or an alternative found?

See also https://github.com/eslint/eslint/pull/7342 where one of these links was just removed.

### PR DESCRIPTION
**Pull request by curiousdannii**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

All links to jslinterrors.com in the docs are deleted. Fixes #7368.

See also https://github.com/jamesallardice/jslint-error-explanations/issues/39

### CODE REVIEW

**Comment by curiousdannii** [comment]
So apparently you have some markdown rules... they could really do with an explanation in the docs! ;)

**Comment by kaicataldo** [comment]
Do we know for sure it's coming back? My personal preference is to remove the links entirely and then revert in the future if it does come back. Not a huge fan of leaving a bunch of commented out stuff around.

**Comment by curiousdannii** [comment]
@kaicataldo The author of jslinterrors.com [sounds very sure](https://github.com/jamesallardice/jslint-error-explanations/issues/39#issuecomment-250028253) that the site will come back, but it may take some time, and it may not be at the same domain.

I thought comments would be better than deleting the lines because this isn't such a significant issue that people will be keeping a close watch for when it does return (unless it returns before this is merged of course!) and so it's quite likely the site will return without a prompt commit to add the links back. If the links remain in the files but are commented out then in X months time someone editing the files will see them and be prompted to check if the domain is back yet.

Of course it's also very likely that people will notice when the site returns, or that the comments never would prompt anyone to check. Who knows :P. If the rest of the team would prefer them all just to be deleted that's fine!

**Comment by nzakas** [comment]
I'd suggest we just remove the links. Our documentation should be pretty standalone at this point.

**Comment by kaicataldo** [comment]
@curiousdannii Yes please! Let's remove those links (and the "Further Reading" section, if it is then empty as a result) rather than comment them out. Thanks!

**Comment by curiousdannii** [comment]
@kaicataldo Done.

**Comment by platinumazure** [comment]
@curiousdannii Thanks very much for re-signing the CLA. The jQuery foundation has become the JS Foundation and they changed the contribution license terms, so everybody needed to re-sign. Hopefully you won't need to sign it again.

**Comment by kaicataldo** [comment]
LGTM. Thanks for contributing to ESLint!

**Comment by vitorbal** [comment]
Thanks, @curiousdannii!

**Pull request merged**
