### PR TITLE
Fix: ensure using correct estraverse

### LINKED ISSUE #3951: Error: Unknown node type AssignmentPattern
The following code:
```js
var o = {
    f(c = 2) {}
};
```
breaks ESLint 1.5.1 (i.e. the latest one) completely:
```
/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/estraverse/estraverse.js:517
                        throw new Error('Unknown node type ' + nodeType + '.');
                        ^

Error: Unknown node type AssignmentPattern.
    at Controller.traverse (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/estraverse/estraverse.js:517:31)
    at EventEmitter.module.exports.api.verify (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/eslint/lib/eslint.js:780:24)
    at processText (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/eslint/lib/cli-engine.js:220:27)
    at processFile (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/eslint/lib/cli-engine.js:257:18)
    at executeOnFile (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/eslint/lib/cli-engine.js:600:23)
    at /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/eslint/lib/cli-engine.js:624:17
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/eslint/lib/cli-engine.js:622:18)
    at Object.cli.execute (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/eslint/lib/cli.js:159:95)
    at Object.<anonymous> (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/eslint/bin/eslint.js:61:20)
```

One issue is that this code is valid ES6 and should be recognized; another one is that a parse error should at least show which file cannot be parsed; it's very hard to find the reason when you have thousands of files and you just know one of them is causing this.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26986343-error-unknown-node-type-assignmentpattern?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #3951.

I'm not sure this PR's direction is right.

Currently there are cases that npm@3 does not install eslint correctly.
That cause is:

- browserify is depending on estraverse@1.9.3  
  (browserify -> module-deps -> detective -> escodegen -> estraverse)
- eslint is importing estraverse via estraverse-fb, then browserify's estraverse is imported wrongly.

```
<root>
├ browserify
├ eslint
│ └ estraverse@4.1.1
├ estraverse@1.9.3
├ estraverse-fb@1.3.1  <-- estraverse-fb is having estraverse in peerDependencies, 
                           so it should be installed into eslint directory. but...
...
```

So this PR imports estraverse and estraverse-fb severally, then it apply estraverse-fb to estraverse manually.

### CODE REVIEW

**Comment by mysticatea** [comment]
And I'm not sure a way to test...

**Comment by zertosh** [comment]
Ah, here is a simple repro case https://github.com/zertosh/eslint-npm-3-estraverse-dedupe-fail

**Comment by nzakas** [comment]
@mysticatea I think this is a case where we have to manually verify that the change works.

**Comment by mysticatea** [comment]
@zertosh Thank you for the response and the update of `node-detective` :)

@nzakas I verified that manually.

1. Prepares an environment to reproduce the issue.
    
    ```
    > npm i npm
    npm@3.3.10 node_modules\npm
    > .\node_modules\.bin\npm i escodegen eslint
    ...
    ```
    
    ```
    ├ eslint@1.8.0
    │  └ estraverse@4.1.1
    ├ estraverse@1.9.3
    ├ estraverse-fb@1.3.1
    ```

    test.js
    
    ```js
    /* eslint-env es6 */
    /* eslint no-undef: 2 */
    let {foo = 0} = obj;
    ```

2. Does reproduce that.
    
    ```
    > .\node_modules\.bin\eslint test.js
    C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\estraverse\estraverse.js:517
                            throw new Error('Unknown node type ' + nodeType + '.');
                            ^
    
    Error: Unknown node type AssignmentPattern.
        at Controller.traverse (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\estraverse\estraverse.js:517:31)
        at EventEmitter.module.exports.api.verify (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\eslint.js:779:24)
        at processText (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli-engine.js:225:27)
        at processFile (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli-engine.js:262:18)
        at executeOnFile (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli-engine.js:671:23)
        at C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli-engine.js:695:17
        at Array.forEach (native)
        at CLIEngine.executeOnFiles (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli-engine.js:693:18)
        at Object.cli.execute (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli.js:161:95)
        at Object.<anonymous> (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\bin\eslint.js:61:20)
    ```
    
3. Modifies installed ESLint code with this patch.
4. Checks whether or not it reproduces that.
    
    ```
    > .\node_modules\.bin\eslint test.js
    
    C:\Users\t-nagashima.AD\Documents\GitHub\sand\test.js
    3:17  error  "obj" is not defined  no-undef
    
    ✖ 1 problem (1 error, 0 warnings)
    ```

    It works fine.

**Comment by nzakas** [comment]
Good enough!

**Comment by xjamundx** [comment]
Was running into this issue locally thanks!

**Pull request merged**
