### PR TITLE
Upgrade: babel-code-frame to version 7

### PR DESCRIPTION
**Pull request by realityking**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[X] Other, please explain:

Bumping babel-code-frame to version 7. Note I didn't touch the babel version used in the build process, only code-frame.

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by kaicataldo** [comment]
Hi, thanks for the PR. Do you mind changing the commit title to start with `Upgrade` instead of `Chore`, as outlined in our [contribution docs](https://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changes)?

**Comment by realityking** [comment]
My bad. Fixed!

**Comment by realityking** [comment]
My bad. Fixed!

Looks like GitHub has issues updating PRs right now, might be a bit until this shows up correctly.

**Comment by kaicataldo** [comment]
This LGTM. Thanks for contributing!

**Comment by kaicataldo** [comment]
Ah, actually, just had a thought. I wonder if this will interfere with the release process at all since this version won't match the Babel version we use for our browser bundle. Can you confirm this works when running the bundling step?

**Comment by realityking** [comment]
Running `npm run browserify` does work. The code doesn't really interact, as `code-frame` is completely unrelated to the bundling itself.

Any idea why the `commit-message` check failed?

**Comment by realityking** [comment]
I've pushed a commit with the correct message but GitHub has some trouble updating PRs. Might be a bit until it shows up.

**Comment by realityking** [comment]
Now GitHub caught up :)

**Comment by realityking** [comment]
Could someone restart the Travis build? Something timed out on the Node,js 6 build.

**Pull request merged**
