### PR TITLE
Update: Added osx support to travis ci

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
We tried it at some point, and turned it off. I don't remember what was the reason for that. Anyone else remembers?

**Comment by alberto** [comment]
Looking at the file history it doesn't look like it was ever enabled.

**Comment by nzakas** [comment]
@amilajack what's the benefit of doing this?

**Comment by amilajack** [comment]
@nzakas it can prevent issues that can be caused by dependencies' native dependencies.

**Comment by alberto** [comment]
The only benefit I can think of is catching issues with file paths. We've had a couple of those. Only tests were affected AFAIR.

**Comment by nzakas** [comment]
@amilajack thanks. Can you please open an issue describing this? We require issues for all pull requests.

Also, can you sign the CLA?

**Comment by nzakas** [comment]
No CLA or issue, so we can't merge. Closing.

**Pull request closed without merging**
