### PR TITLE
New: Extend no-negated-in-lhs rule to cover instanceof (fixes #2716)

### LINKED ISSUE #2716: Rule suggestion: disallow !a instanceof b
As the existing rule no-negated-in-lhs, it seems like it would be good to also disallow
```javascript
if (!a instanceof b) // do something
```
since the developer certainly meant to write
```javascript
if (!(a instanceof b)) // do something
```
instead. This prevents errors, and there's no legitimate case for the former that I can think of, so I think this could be enabled by default as with no-negated-in-lhs. I've thrown together a quick copy and paste job of no-negated-in-lhs which works; will attach PR.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/20812079-rule-suggestion-disallow-a-instanceof-b?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tornewuff**

### CODE REVIEW

**Comment by michaelficarra** [comment]
LGTM. :+1:

**Comment by gcochard** [comment]
:+1:

**Comment by nzakas** [comment]
See #2716 - I don't believe this is an appropriate approach.

**Comment by nzakas** [comment]
Per #2716, I think this would be better as a separate rule, so closing this out.

**Pull request closed without merging**
