### PR TITLE
Docs: fix examples in object-curly-newline

### PR DESCRIPTION
**Pull request by soobing**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
The example of correct/incorrect really helpful to user.
So if not match between these two, can give confusion.
When I was reading in `object-curly-newline` docs there was not matching example in case of `consistent`.

#### Is there anything you'd like reviewers to focus on?
I'm not sure that I correctly added example in correct case. So I ask to review to focus on pair between correct case and incorrect case.

### CODE REVIEW

**Comment by soobing** [comment]
@mdjermanovic 
Oh thanks for accept. I didn't know that the demo, so there are alot that I added examples in incorrect case even though it's correct 😃. I will try again today and ask review.

**Comment by mdjermanovic** [comment]
Looks great!

Can you please fix the linting error: it seems there's a tab at the beginning of line `338`.

You can check this locally with `npm run lint`

**Comment by soobing** [comment]
@mdjermanovic
Thank you I changed tab to space 👍🏻😃

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by mdjermanovic** [comment]
Thanks for contributing!

**Pull request merged**
