### PR TITLE
Docs: Correct a term in max-len.md (refs #6637)

### PR DESCRIPTION
**Pull request by vsemozhetbyt**
**What issue does this pull request address?**

#6637

**What changes did you make? (Give an overview)**

Replace "code points" by "code units" in the rule explanation.

**Is there anything you'd like reviewers to focus on?**

I guess not.

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
I've just signed the CLA, however I have not the git installed and I have not set any git confug locally (I only used the web interface all the time). Does it mean I can't contribute to Eslint?

**Comment by platinumazure** [comment]
@vsemozhetbyt You just need to set the "Name" and "E-mail" fields of your GitHub profile to match your CLA signature.

That said, in your case, the jQuery foundation prefers you use a real name, and they have a heuristic that catches 1-word names which "require manual verification". So the best way to get this moving is to put in a first/last name on your Git profile and... see if you can amend the commit from GitHub somehow. (Worst case, you can edit the file on master again, after you've changed your profile name and e-mail as needed.)

**Comment by vsemozhetbyt** [comment]
@platinumazure I've just change GitHub user name to three words and re-sign the CLA. Should I add another commit to this branch? Maybe to change  "code units" to  "16 bits code units"?

**Comment by platinumazure** [comment]
I don't think that will work, because the CLA checker checks all commits in
a branch.

You can try searching the Github help docs for how to amend a commit after
you changed your profile name. If you can't do it on the website, you can
install git locally and clone your fork, check out the branch, and run `git
commit --amend --no-edit` to update the commit locally, then `git push
origin your-branch -f` to force update the Github version of the branch.

Please stop by in Gitter chat (https://gitter.im/eslint/eslint) if you need
more help.

**Comment by vsemozhetbyt** [comment]
@platinumazure I've just done all the command by portable configured git. It seems it does not help, unfortunately.

**Comment by vsemozhetbyt** [comment]
Phew! It works with `--reset-author` :)

**Comment by alberto** [comment]
LGTM. Thanks!

**Pull request merged**
