### PR TITLE
fix: normalize `cwd` passed to `ESLint`/`FlatESLint` constructor

### LINKED ISSUE #17042: Bug: (eslintignore breaks when cwd is using forward slash on windows)
### Environment

Node version: 19.7.0
npm version: 9.5.0
Local ESLint version: 8.37.0
Global ESLint version: N/A
Operating System: windows 10 x64

### What parser are you using?

Default (Espree)

### What did you do?

When passing cwd option to eslint with a path with forward slash on windows (`C:/path/to/project`), eslintignore breaks and errors were reported from ignored files.

folder structure:
```
src/1.js
src/dist/2.js
.eslintignore
.eslintrc.js
lint.js
```
<details>
<summary>src/1.js</summary>

```js
console.log(1)
```
</details>

<details>
<summary>src/dist/2.js</summary>

```js
console.log(2)
```
</details>

<details>
<summary>.eslintignore</summary>

```
src/dist
```
</details>

<details>
<summary>lint.js</summary>

```js
const eslint = require('eslint');

const run = async (cwd) => {
  // 1. Create an instance.
  const instance = new eslint.ESLint({ cwd, extensions: ['.js'] });

  // 2. Lint files.
  const results = await instance.lintFiles(["./src"]);

  // 3. Format the results.
  const formatter = await instance.loadFormatter("stylish");
  const resultText = formatter.format(results);

  // 4. Output it.
  console.log(resultText);
};

const main = async () => {
  await run(__dirname);
  console.log('-----------');
  await run(__dirname.replaceAll("\\", "/"));
};

main();
```
</details>

<details>
<summary>.eslintrc.js</summary>

```
module.exports = {
  parserOptions: {
    ecmaVersion: 2020,
  },
  'root': true,
  'rules': {
    'semi': 'error',
  },
};
```
</details>

<details>
<summary>result</summary>

```
C:\src\eslinttest\src\1.js
  1:15  error  Missing semicolon  semi

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

-----------

C:\src\eslinttest\src\1.js
  1:15  error  Missing semicolon  semi

C:\src\eslinttest\src\dist\2.js
  1:15  error  Missing semicolon  semi

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```
</details>

### What did you expect to happen?

eslintignore working as expected

### What actually happened?

linting ignored files

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Where I get this problem? [Here](https://github.com/fi3ework/vite-plugin-checker/blob/20b739943495130c8119a4d255104704d0770dda/packages/vite-plugin-checker/src/checkers/eslint/main.ts#L56).
I'm using vite-plugin-checker on my project. It pass a `root` param recieved from `vite` to eslint `cwd` option which happens to be a path with forward slash on windows.

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #17042

#### What changes did you make? (Give an overview)

Updated `ESLint` and `FlatESLint` constructors to `path.normalize()` given `cwd` right away when processing options.

This fixes bug #17042 for the `ESLint` class (the same bug did not exist for the `FLatESLint` class) and also ensures that rules and formatters always get normalized `cwd`.

### CODE REVIEW

**Review by nzakas — APPROVED** [review]
LGTM. Would like someone else to review before merging.

**Comment by fasttime** [comment]
After this change, a custom formatter will be passed a normalized `cwd` instead of what was originally specified. A naively designed unit test could start failing because of the new behavior. Is this acceptable for a non-breaking fix?

**Comment by mdjermanovic** [comment]
> After this change, a custom formatter will be passed a normalized `cwd` instead of what was originally specified. A naively designed unit test could start failing because of the new behavior. Is this acceptable for a non-breaking fix?

I think it's acceptable for a non-breaking fix. We don't guarantee that the data passed to formatters will remain exactly the same, and that looks more like an integration test than a unit test.

**Comment by nzakas** [comment]
> I think it's acceptable for a non-breaking fix. We don't guarantee that the data passed to formatters will remain exactly the same, and that looks more like an integration test than a unit test.

Agreed.

**Review by fasttime — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
