### PR TITLE
Breaking: make `overrides[].files` matching dotfiles (fixes #11201)

### LINKED ISSUE #11201: overrides don't recognize dotfiles
**Tell us about your environment**

* **ESLint Version:** 5.10.0
* **Node Version:** 11.1.0
* **npm Version:** 6.5.0

**What parser (default, Babel-ESLint, etc.) are you using?**

- N/A

**Please show your full configuration:**

```yml
root: true

overrides:
  - files: "*.ts"
    parser: typescript-eslint-parser
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
eslint --print-config .test.ts
```

**What did you expect to happen?**

It prints:

```json
{
  "globals": {},
  "env": {},
  "rules": {},
  "parserOptions": {},
  "root": true,
  "files": "*.ts",
  "parser": "typescript-eslint-parser"
}
```

**What actually happened? Please include the actual, raw output from ESLint.**

It printed:

```json
{
  "globals": {},
  "env": {},
  "rules": {},
  "parserOptions": {},
  "root": true
}
```

**Are you willing to submit a pull request to fix this bug?**

I'm sorry, I don't have enough time for now.

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix: #11201

**What changes did you make? (Give an overview)**

This PR makes `overrides[].files` matching dotfiles.

```yml
overrides:
  - files: ["*.ts"]
    parser: "typescript-eslint-parser"
```

I surprised that that `overrides` setting wasn't applied to `.foo.ts`.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

**Comment by mysticatea** [comment]
@platinumazure This affects only files which start with dot.

**Comment by not-an-aardvark** [comment]
This seems like it might be a breaking change, because it would change the linting configuration for certain files. Do you think it would be worth waiting to add this until the next major release?

(Adding the `breaking`/`do not merge` labels for now so that this isn't accidentally merged while the discussion is ongoing.)

**Comment by mysticatea** [comment]
This is just a bug fix to me, but indeed, this might break existing CI builds.

**Comment by kaicataldo** [comment]
Is there currently another way to configure `overrides` to run over dotfiles? If so, I think it makes sense to wait for our next major release. If there currently isn't a way to do, I would consider this a pretty big omission and one that would be better to fix sooner rather than later.

**Comment by j-f1** [comment]
`["*.ts", ".*.ts"]` might work.

**Pull request merged**
