### PR TITLE
Update: Take type annotations into account in `space-infix-ops`

### LINKED ISSUE #226: Rule: Wrapping non-IIFE function literals in parens is unnecessary
This rule should warn when it encounters a function expression wrapped in parentheses with no following invoking parentheses.

See: http://jslinterrors.com/wrapping-non-iife-function-literals-in-parens/

The rule ID should be "none-iffe-wrapping" and should be on by default.

### LINKED ISSUE #5211: Flow type triggers space-infix-ops error
I know that eslint is not supporting flow types, but it seems that the space-infix-ops rule is assuming that between `left` and `right` side of an `ExpressionPattern`, there is only on `Punctation` which in the case of flow type is not true.
(https://github.com/eslint/eslint/blob/master/lib/rules/space-infix-ops.js#L32)

example:
```
(foo: string = 'test') => {};
```
triggers:
```
 1:5  error  Infix operators must be spaced  space-infix-ops
```

What would be a proper way to fix this? I think this is something in the rule itself should be accounted for and it should ignore anything which belongs to left or right side instead of treating it as "something between left and right".

refs babel/babel-eslint#226

eslint version: 1.10.3

### PR DESCRIPTION
**Pull request by gonsfx**
Test fails and i have no clue how i'm supposed to add `babel-eslint` to the testing stack for single tests.
Advice is welcome!

(fixes #5211)

### CODE REVIEW

**Comment by platinumazure** [comment]
One possible path forward:

1. Look at package.json in the root project directory and see if "babel-eslint" shows up as a devDependency.
1. If not, add it and run `npm install`.
1. Then see if you can change the parser using a RuleTester option.

FYI: I'm not 100% sure RuleTester lets you change the parser- it's the sort of thing plugin authors would need but core rule developers wouldn't, so I don't know if we ever did that.

**Comment by michaelficarra** [comment]
This doesn't seem to have anything to do with #226. Did you mean to open this PR against a different repo?

**Comment by gonsfx** [comment]
@michaelficarra Thanks. No clue what happened here, but i fixed it.

@platinumazure 
Thanks for your feedback!

I have `babel-eslint` installed as a devDependency but i wasn't sure if and how to set it using a RuleTester option.

Also, i'm not sure if this should be implemented in `eslint` at all - it could probably also be done in `eslint-plugin-babel`.

**Comment by nzakas** [comment]
@gonsfx you should be able to set `parser` for an individual test just like you do other options.

**Comment by alberto** [comment]
@gonsfx If you want to pull `babel-eslint`, you have to add it to our `package.json` `devDependencies`

To use it, add `parser: "babel-eslint"` to your test object.

**Comment by nzakas** [comment]
@gonsfx are you going to finish this up?

**Comment by nzakas** [comment]
Carried over to #6723.

**Pull request closed without merging**
