### PR TITLE
Docs: Minor rephrase in `no-invalid-this`.

### PR DESCRIPTION
**Pull request by Francisc**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Minor rephrase, check diff.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by platinumazure** [comment]
@eslint/eslint-team It looks like the Travis and AppVeyor builds might be broken due to an upstream dependency issue of some kind. Anyone know what might be going on?

**Comment by not-an-aardvark** [comment]
See https://github.com/eslint/eslint/issues/9539#issuecomment-340501373

**Comment by Francisc** [comment]
Thanks as well.

**Comment by not-an-aardvark** [comment]
Closing and reopening this PR to trigger a rebuild.

**Comment by not-an-aardvark** [comment]
Thanks for contributing!

**Pull request merged**
