### PR TITLE
Upgrade: Upgrade various dependencies (fixes #4303)

### LINKED ISSUE #4303: Infrastructure: Update dependencies
Update all the dependencies and devDependencies to latest version and make sure nothing breaks.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27845410-infrastructure-update-dependencies?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM

**Comment by IanVS** [comment]
Did you mean to grab the changes to the changes to the `rule-tester` tests?  Did that change because of one of the dependencies?

**Comment by gyandeeps** [comment]
@IanVS Yes. Since now the error message doesnt start with the expected start using `^`. Now it start with "Assertion error<something>" and then the error message as per the tests. Thats why I just removed `^`. Now it matches based on the regex.

**Comment by nzakas** [comment]
Commitc message should be "Upgrade:"

**Comment by gyandeeps** [comment]
Done.

**Pull request merged**
