### PR TITLE
Chore: Add object-property-newline tests to increase coverage.

### PR DESCRIPTION
**Pull request by jrpool**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[X] Other, please explain:
Add tests to an existing rule

**What changes did you make? (Give an overview)**
Added tests for some code patterns not already tested for.

**Is there anything you'd like reviewers to focus on?**
I would appreciate guidance on whether I am responsible for doing something about changes in package.json when I submit pull requests.

### CODE REVIEW

**Comment by platinumazure** [comment]
I'm curious, why did package.json change? Did you need to update anything in order for this change to run/test successfully?

Usually, we'll occasionally go through package.json and upgrade dependencies as separate PRs. It's good for PRs to focus on one thing, if possible. So if the dependency upgrade (package.json change) was necessary as part of the main purpose of the PR, then it makes sense to be included (indeed, it must be included); if the changes aren't necessary, it's probably better to do them separately.

**Comment by jrpool** [comment]
@platinumazure: I suddenly found it impossible to perform `npm test`. I didn’t keep a copy of the error messages, but they indicated that the code could not be found to run the script at all. So I ran `npm install`. That worked, except that I got 2 warnings about needing to install versions of ESLint as (something lixke) codependencies. So I installed ESLint globally. After that, `npm install` returned no warnings and testing became possible as before. Intuitively, anyway, it seemed to me that at least some of the updates reflected in `package.json` changes were necessary in order for testing to take place at all.

**Comment by not-an-aardvark** [comment]
Thanks for the PR!

I think it's unlikely that the changes to `package.json` in this PR had an effect; from your description, I think it's more likely that there was an issue with your local configuration which caused `npm test` to fail for some reason.

The two `peerDependencies` warnings that you mentioned are known, but they shouldn't affect running the tests in this case.

If it's true that other tests are currently failing on `master` without these `package.json` changes, then ideally we'd like to fix that independently from the `object-property-newline` tests that were also added in this PR.

**Comment by jrpool** [comment]
Thanks for the help, @not-an-aardvark. I have restored the upstream master version of package.json and the tests now run and pass. So this PR now has changes only in tests/lib/rules/object-property-newline.js.

**Comment by ilyavolodin** [comment]
Thanks for PR!

**Pull request merged**
