### PR TITLE
Update: Pass filePath to parser (fixes #5344)

### LINKED ISSUE #5344: Pass filename as an argument to `parse`
I have been experimenting with type-aware lint rules. The prototype I have combines [Flow](https://github.com/facebook/flow) with `babel-eslint` to annotate the AST with type information.

However, for Flow to be able to provide complete type information it needs the path to the current file so that it can properly resolve imports/requires. To that end I would like to pass the file name as an argument to `parse`.

I understand that this is a radical departure from the current idea of what a frontend for ESLint is, but the change required to support this idea is very small and will not interfere with existing code. I'm happy to put up a pull request if it is likely to be accepted.

### PR DESCRIPTION
**Pull request by nmote**

### CODE REVIEW

**Comment by nmote** [comment]
I looked at `tests/lib/eslint.js` and a couple other places and didn't find anything that was testing what got passed to custom parsers. It could be that I just overlooked something. Either way, advice on testing would be appreciated.

I did test this manually to ensure that the file path is available to parsers.

**Comment by nzakas** [comment]
I think this is the first thing we are passing that isn't implicitly tested somewhere else. Custom parser tests are here:
https://github.com/eslint/eslint/blob/master/tests/lib/eslint.js#L3701

You probably just want to create a stub parser using [mockery](https://github.com/mfncooper/mockery#registering-mocks) that has a parse() method that you can verify is passed the correct info (probably using a Sinon mock)

**Comment by ilyavolodin** [comment]
@nmote Are you planning on finishing this up?

**Comment by nmote** [comment]
I'd like to at some point but feel free to close if you're tidying and I can always re-open or create a new PR.

**Comment by ilyavolodin** [comment]
Sounds good. When you get time to add some tests, please open a new PR.

**Pull request closed without merging**
