### PR TITLE
Chore: Update README to pull in reviewer data

### PR DESCRIPTION
**Pull request by nzakas**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Updates the script that builds the README to include data from the reviewers team.

**What changes did you make? (Give an overview)**

Updated the `update-readme.js` script to include reviewers. This involved some refactoring to make things a bit easier to manage. I'm now using some EJS to do the overall layout of the team section.

**Is there anything you'd like reviewers to focus on?**

Is everything clear?

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Some linting errors needs to be fixed before this can be merged.

**Comment by nzakas** [comment]
Oops, thanks for pointing that out. Pushing a fixed version.

**Comment by not-an-aardvark** [comment]
It seems like there are still some linting errors in the readme.

**Comment by nzakas** [comment]
Thanks, I'll get that fixed.

**Pull request merged**
