### PR TITLE
Update: Add fixer for arrow-parens (fixes #4766)

### LINKED ISSUE #4766: Implement auto fix functionality for arrow-paren rule
Implement auto fix functionality for arrow-paren rule **when using "always" option**

While this does violate the best practice of only changing one character in a fix, I was not able to contrive a situation where it overlaps with another fix.  Caveat: I may not be familiar with every rule fix.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29298241-implement-auto-fix-functionality-for-arrow-paren-rule?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by madmed88**
This PR adds auto fix for arrow-parens rule. It removes the params as-needed and adds them when set to always.

### CODE REVIEW

**Comment by nzakas** [comment]
The code looks good. Can you also update the rule doc page?

**Comment by madmed88** [comment]
done

**Comment by nzakas** [comment]
Thanks for the contribution!

**Comment by ForsakenHarmony** [comment]
What about auto fix for the `requireForBlockBody` option?

**Pull request merged**
