### PR TITLE
Update: support `??` operator, import.meta, and `export * as ns`

### LINKED ISSUE #12629: Support `export * as ns from "source"`
**The version of ESLint you are using.**

6.7.2

**The problem you want to solve.**

ESLint doesn't support a new syntax [`export * as ns from "source"`](https://github.com/tc39/ecma262/pull/1174).

**Your take on the correct solution to problem.**

ESLint supports that under `ecmaVersion: 2020`.

- [x] **ESTree:** https://github.com/estree/estree/pull/205
- [x] **Acorn:** https://github.com/acornjs/acorn/pull/889
- [x] **Espree:** https://github.com/eslint/espree/pull/441
- [x] **`eslint-visitor-keys`:** https://github.com/eslint/eslint-visitor-keys/pull/10
- [ ] **ESLint:** https://github.com/eslint/eslint/pull/13196

**Are you willing to submit a pull request to implement this change?**

Yes.

### LINKED ISSUE #12642: Optional Chaining and Nullish coalescing Operator arrived at Stage 4
**The version of ESLint you are using.**
6.7

**The problem you want to solve.**
Support two new ES features: Optional Chaining and Nullish coalescing Operator.

**Your take on the correct solution to problem.**
- [x] **ESTree:** https://github.com/estree/estree/pull/204 and https://github.com/estree/estree/pull/211
- [x] **Acorn:** https://github.com/acornjs/acorn/pull/890 and https://github.com/acornjs/acorn/pull/891
- [x] **eslint-visitor-keys:** https://github.com/eslint/eslint-visitor-keys/pull/12
- [ ] **Espree:** https://github.com/eslint/espree/pull/441 and https://github.com/eslint/espree/pull/446
- [ ] **ESLint:** https://github.com/eslint/eslint/pull/13196 and https://github.com/eslint/eslint/pull/13416

*(Template inspired by Issue 12629)*

### LINKED ISSUE #13133: Support `import.meta`
> https://github.com/tc39/proposals/commit/0c27379ebb525ffebed75584827ce51687af99f8

`import.meta` meta property has arrived at Stage 4 as ES2020. ESLint should support it.

There is work we should do:

- [x] ESTree update: https://github.com/estree/estree/pull/210
- [x] Acorn update: https://github.com/acornjs/acorn/pull/943
- [x] Espree update https://github.com/eslint/espree/pull/441
- [ ] ESLint update https://github.com/eslint/eslint/pull/13196

### PR DESCRIPTION
**Pull request by mysticatea**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Changes an existing rule and existing core feature

#### What changes did you make? (Give an overview)

This PR upgrades dependencies and updates rules and code path analysis in order to support new syntax. Refs #12642, fixes #12629, fixes #13133.

- ESTree Update:
  - [ ] ~~Optional Chaining (estree/estree#204)~~
  - [X] Nullish Coalescing (estree/estree#211)
  - [X] `export * as ns from "source"` (estree/estree#205)
  - [X] `import.meta` (estree/estree#210)
- Acorn Update:
  - [ ] ~~Optional Chaining (acornjs/acorn#891)~~
  - [X] Nullish Coalescing (acornjs/acorn#890)
  - [X] `export * as ns from "source"` (acornjs/acorn#889)
  - [X] `import.meta` (acornjs/acorn#943)
- Espree Update:
  - [ ] ~~Optional Chaining (not yet)~~
  - [X] Nullish Coalescing (eslint/espree#441)
  - [X] `export * as ns from "source"` (eslint/espree#441)
  - [X] `import.meta` (eslint/espree#441)
- ESLint visitor keys Update:
  - [ ] ~~Optional Chaining (not yet)~~
  - [X] Nullish Coalescing (no change)
  - [X] `export * as ns from "source"` (eslint/eslint-visitor-keys#10)
  - [X] `import.meta` (no change)
- ESLint Scope Analysis Update:
  - [ ] ~~Optional Chaining (not yet)~~
  - [X] Nullish Coalescing (no change)
  - [X] `export * as ns from "source"` (eslint/eslint-scope#56)
  - [X] `import.meta` (no change)
- ESLint Code Path Analysis Update:
  - [ ] ~~Optional Chaining (not yet)~~
  - [X] Nullish Coalescing (c80d2d8)
  - [X] `export * as ns from "source"` (no change)
  - [X] `import.meta` (no change)
- ESLint Rules Update:
  - [ ] ~~Optional Chaining (not yet)~~
  - [X] Nullish Coalescing (bd58eabd557ee38d03cd4fb65c0db1644d0dc843)
  - [X] `export * as ns from "source"` (2b6c93b099d598bdb339ffc22b9481f080dec376)
  - [X] `import.meta` (no change)

[EDIT]: Optional chaining is still stuck and acorn has been released with the other parts. Therefore, we separate optional chaining from this PR.

#### Is there anything you'd like reviewers to focus on?

- Are there other rules we need to update?

### CODE REVIEW

**Comment by mdjermanovic** [comment]
As for `export * as ns`, this might also affect `no-duplicate-imports` (issues #12758 and #12760), but I guess it doesn't make sense to change anything in this PR, unless PRs for those two issues get merged first (otherwise, those PRs should account for `export * as ns`).

Other than that, I believe the list is complete (`keyword-spacing` and `no-restricted-exports`).

`no-restricted-imports`, `camelcase`, `id_blacklist`, and `id-match` should just work.

`id_length` and `no_underscore_dangle` will not work, but these two rules already don't check exported names at all.

**Comment by aldeed** [comment]
@mysticatea is this making it into v7 release? The v7 RC doesn't truly have ESM support right now since almost every ESM Node project has `import.meta.url` in some files.

**Comment by mysticatea** [comment]
@aldeed We are waiting for upstreams. I guess this PR will be landed on v7.1.0 or v7.2.0.

**Comment by mysticatea** [comment]
Optional chaining syntax still stays on the spec discussion, but the upstreams have been released along with the other syntax. Therefore, I separated the optional chaining from this PR in order to merge this PR soonly.

**Comment by ljharb** [comment]
Is the PR title no longer accurate?

**Comment by btmills** [comment]
@ljharb optional chaining is the only thing not in this PR. The other three features are included. Is that what you mean?

**Comment by ljharb** [comment]
Ah ok, so this does include nullish coalescing :-) thanks!

**Comment by dreyks** [comment]
https://github.com/acornjs/acorn/pull/891 is now merged, so hopefully, we can get back to this soon(ish) (once acorn gets a new release)

**Comment by dreyks** [comment]
released as https://github.com/acornjs/acorn/releases/tag/7.3.0

**Comment by stefan505** [comment]
When will this be released for eslint?

**Comment by kaicataldo** [comment]
This PR was released in the latest version (v7.2.0).

**Pull request merged**
