### PR TITLE
New: `no-boolean-trap` rule

### PR DESCRIPTION
**Pull request by mroderick**
#### What is the purpose of this pull request? (put an "X" next to item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[x] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What category of rule is this? (place an "X" next to just one item)

[ ] Enforces code style
[ ] Warns about a potential error
[x] Suggests an alternate way of doing something
[ ] Other (please specify:)

Provide 2-3 code examples that this rule will warn about:

```javascript
// disallowed
volumeSlider.setValue(90, false);
volumeSlider.setValue.apply(null, [false]);
volumeSlider.setValue.call(null, 90, false);
const set90 = volumeSlider.setValue.bind(null, 90, false);

// allowed
const shouldAnimateTransition = false;

volumeSlider.setValue(90, shouldAnimateTransition);
volumeSlider.setValue.apply(null, [shouldAnimateTransition]);
volumeSlider.setValue.call(null, 90, shouldAnimateTransition);
const set90 = volumeSlider.setValue.bind(null, 90, shouldAnimateTransition);
```

#### Why should this rule be included in ESLint (instead of a plugin)?

Boolean traps are a code smell, and far too common. Disallowing them will help developers improve their API design.

See:

* [hall of api shame: boolean trap](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap)
* [Clean Code, "Flag Arguments", p41](http://www.goodreads.com/book/show/3735293-clean-code)

I don't feel strongly about `no-boolean-trap` being included in ESLint. If it seems relevant to maintainers, then let us add it. Otherwise, I am more than happy to release it as a plugin.

#### What changes did you make? (Give an overview)

I implemented a new rule: `no-boolean-trap`

#### Is there anything you'd like reviewers to focus on?

Does the documentation explain the practice of avoiding boolean traps sufficiently? (I didn't want developers to have to read an essay paraphrasing the two linked resources).

### CODE REVIEW

**Comment by kaicataldo** [comment]
I like the motivation for this rule - one concern I have for including it in in core is for the situation when you would need to call a 3rd party function whose API you have no control over. If the one of the parameters in said function is a boolean, does this rule then recommend either disabling checking that line or assigning it to a variable (as described in the docs?).

I thought this was an interesting alternative to relieve some of the confusion from this sort of code: https://github.com/babel/babylon/issues/152

**Comment by mroderick** [comment]
> I like the motivation for this rule - one concern I have for including it in in core is for the situation when you would need to call a 3rd party function whose API you have no control over. If the one of the parameters in said function is a boolean, does this rule then recommend either disabling checking that line or assigning it to a variable (as described in the docs?).

I agree, the documentation is a bit vague here.

I wasn't sure if a recommendation for a solution to handling third party APIs is considered to be in scope for ESLint's documentation.

For simpler situations, I think that using variables is a good recommendation.

For more complex situations, like writing an SDK for a web service, one would probably want to write an API wrapper for 3rd party dependency anyway. This wrapper would hopefully encapsulate all the poor design choices with something better at a higher abstraction.

Do you think I should update the documentation with a section about handling boolean traps in third party methods?

Should I update the error message to suggest a solution?

**Comment by not-an-aardvark** [comment]
I think preventing boolean traps would a good idea, but I share @kaicataldo's concerns about calling third-party functions.

I think this proposal might be trying to solve the issue in the wrong place; it's reporting the code that *calls* the function with a boolean-trap API, but the problem could only be addressed by changing the function itself, not the code that calls the function. What if we changed the rule to detect the use of function *parameters* as booleans instead?

The rule would report any function parameter that is only used in a boolean condition. For example, all of the following functions would be reported:

```js
function foo(bar, baz) {
  if (baz) doSomething(bar);
}
```

```js
function foo(bar) {
  doSomething(!bar);
}
```

```js
function foo(foo, bar, baz) {
  return baz ? foo() : bar();
}
```

**Comment by mroderick** [comment]
> I think this proposal might be trying to solve the issue in the wrong place; it's reporting the code that calls the function with a boolean-trap API, but the problem could only be addressed by changing the function itself, not the code that calls the function.

It would still be a code smell. I think giving the author a recommendation of using a variable to label the argument would still improve the situation for readers, even when the author cannot fix the problem at the source.

> The rule would report any function parameter that is only used in a boolean condition

That is a great suggestion!

I have been wondering about how to implement this without types.

It might still miss a few situations, where authors might overload the meanings of arguments and derive other values from the boolean traps. I think that is acceptable.

I will take a stab at implementing this and push more commits

**Comment by mysticatea** [comment]
By the way, why are only boolean values the trap?
I'm not sure why boolean values are special.

```js
// what is the true?
foo(true)

// what is the 90?
foo(90)

// what is the "toru"?
foo("toru")
```

**Comment by platinumazure** [comment]
@mysticatea Your second example might be called a "magic number", and we have a rule for that. In that sense, this is about "magic booleans".

As for your string example, I'm not sure how we could catch magic vs useful strings. I suppose on some level we could forbid all literal arguments and require variables to be used in call expressions, so that there's no magic, but that would be ridiculous for things like Object.prototype.hasOwnProperty.

**Comment by mroderick** [comment]
This is my first PR working with ESLint and ESTree, so it will take me a while to figure out how to implement @not-an-aardvark's suggestion. Suggestions welcome

**Comment by mroderick** [comment]
> While you're certainly welcome to implement the suggestion now, it might be better to wait until we have consensus on the proposal first. That way, if the proposal changes again or the team decides to reject the proposal, you won't have wasted your time on an implementation.

That is a good point, I will take that into consideration.

**Comment by nzakas** [comment]
I agree with @not-an-aardvark's assessment, and I think this would be better as a plugin as I don't think this rises to the level of must-have for the core (Boolean traps are a bit controversial -- some people hate any Boolean parameters, some think one is okay but not two, etc.). I'd rather not wade into that for the core.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

**Pull request closed without merging**
