### PR TITLE
feat: Add suggestions for no-console and no-unused-vars Fix #17493

### LINKED ISSUE #17493: Rule Change: no-console could be fixable
### What rule do you want to change?

no-console

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

I debug a lot with console.log, and have to remove them all afterwards.

Some console.log I write are multiline, like this : 

```js
console.log(
	JSON.stringify({
		msg: "inspect-sectObj",
		inspect: util.inspect(sectObj, { showHidden: true, depth: 2 }),
	})
);
```

### What does the rule currently do for this code?

It will simply report the error

### What will the rule do after it's changed?

It could fix the error, removing the console.log alltogether

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

I know this has not been implemented on purpose, probably people don't want all their console.logs dropped by eslint by default, I would also like to be able to make this rule fix only on certain conditions.

### PR DESCRIPTION
**Pull request by edi9999**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

This adds suggestions both for rule "no-console" and for rule "no-unused-vars".

### CODE REVIEW

**Comment by edi9999** [comment]
I've just updated all tests to make them pass !

**Comment by edi9999** [comment]
Fixes https://github.com/eslint/eslint/issues/17493

**Comment by nzakas** [comment]
Thanks for the contribution. The issue you reference only has to do with `no-console`, so please remove the other changes from this PR. Also, you'll need to add tests for the `no-console` rule, which are in `tests/lib/rules/no-console`.

**Comment by edi9999** [comment]
Would it be possible to integrate the other changes in an other PR ? 

Or can I update the first issue to add "no-unused-vars" ?

**Comment by nzakas** [comment]
Please open a separate PR. We need to evaluate changes to rules separately.

**Comment by edi9999** [comment]
Closed in favor of https://github.com/eslint/eslint/pull/17542

**Pull request closed without merging**
