### PR TITLE
docs: Remove the $ prefix in terminal commands

### PR DESCRIPTION
**Pull request by AndreasLewis**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

I simply removed the use of $ as a prefix for shell commands without an output, since it is not used anywhere else than these few commands. I also modified the markdownlint config, so future $ prefixes will be removed when linting the markdown files. So to ensure consistency.

#### Is there anything you'd like reviewers to focus on?

Nothing, really. It's a tiny change.

### CODE REVIEW

**Review by bmish — CHANGES_REQUESTED** [review]
If we're going to make this change, we should also stop disabling the MD014 markdownlint rule:

https://github.com/eslint/eslint/blob/6f940c3ce715327f282c197d0f71b91848e5d83d/.markdownlint.yml#L10

https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md014---dollar-signs-used-before-commands-without-showing-output

**Comment by nzakas** [comment]
Sounds like a good idea. @AndreasLewis do you want to make that change?

**Comment by AndreasLewis** [comment]
> If we're going to make this change, which I support because it makes it easier to copy and paste, we should also stop disabling the MD014 markdownlint rule:
> 
> https://github.com/eslint/eslint/blob/6f940c3ce715327f282c197d0f71b91848e5d83d/.markdownlint.yml#L10
> 
> https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md014---dollar-signs-used-before-commands-without-showing-output

Good idea! I've added that change as well as linted all markdown files according to the removal of MD014.

**Review by snitin315 — APPROVED** [review]
LGTM. Thank you for contributing.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Review by bmish — APPROVED** [review]

**Comment by bmish** [comment]
Thanks!

**Pull request merged**
