### PR TITLE
Docs: Update Step 1 of Development Environment documentation

### PR DESCRIPTION
**Pull request by khawarlatifkhan**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Updated "Step 1: Install Node.js" of the "Development Environment" documentation with the aim to make it coherent.

#### Is there anything you'd like reviewers to focus on?
This pull request is created as a test to get used to the process before I can start working on "Configuration Documentation" as a part of the Google Season of Docs project.

### CODE REVIEW

**Comment by kaicataldo** [comment]
Thanks for contributing! The documentation changes LGTM (Look Good To Me). It looks like the commit message doesn't follow [our guidelines](https://github.com/eslint/eslint-github-bot/blob/master/docs/commit-message-check.md), which is important because we use this format to help automate parts of our release process. The link I included above has directions on what the check expects as well as how to update the commit message, but please feel free to comment here if you run into any issues!

**Comment by khawarlatifkhan** [comment]
I changed the title of the PR. Does this fix the error?

**Comment by kaicataldo** [comment]
When there's only 1 commit (like there is now), the check uses the commit message (which is `Update development-environment.md`). I'll go ahead and fix this when I merge it so you don't have to worry about it any more for this PR!

**Comment by kaicataldo** [comment]
For future reference, you can change the commit message using the commands listed [here](https://github.com/eslint/eslint-github-bot/blob/master/docs/commit-message-check.md#how-do-i-fix-it).

**Comment by kaicataldo** [comment]
Thanks for contributing!

**Comment by khawarlatifkhan** [comment]
I'm sorry. I still don't understand it fully. I'll try with another PR or we can discuss it at our next meeting, please?

**Pull request merged**
