### PR TITLE
Chore: upgrade deps.

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Other, please explain:

**What changes did you make? (Give an overview)**
upgrade deps to latest version.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
As mentioned in Greenkeeper issue, we have to have a good reason to update dependancies. We don't update them whenever the new version comes out. I'm not sure we need to update them right now, unless you know of a good reason to do so.

**Comment by not-an-aardvark** [comment]
@ilyavolodin What's the disadvantage of upgrading dependencies?

By the way, this was also discussed in https://github.com/eslint/eslint/pull/8304.

**Comment by platinumazure** [comment]
At least for packages we maintain ourselves (espree), I think it makes some sense to offer latest and greatest if we can. Otherwise, I can see both sides.

**Comment by Aladdin-ADD** [comment]
> As mentioned in Greenkeeper issue, we have to have a good reason to update dependancies. We don't update them whenever the new version comes out.

agree to this. but what is “a good reason”.  since we have a very good test coverage, maybe it is safe to upgrade to latest.

**Comment by gyandeeps** [comment]
I support periodic updates like these. I think there is no harm doing this periodically.

**Comment by corbinu** [comment]
I would also prefer that the dependencies are updated regularly, but just my two cents

**Comment by not-an-aardvark** [comment]
@ilyavolodin It looks like three team members are :+1: for this PR. Are you okay with merging it?

**Comment by ilyavolodin** [comment]
I'm fine with merging this one. Updating deps once in a while is perfectly fine. I just don't really want to update as soon as a new version of dependency comes out.

**Pull request merged**
