### PR TITLE
fix: remove TOC from printable

### PR DESCRIPTION
**Pull request by harish-sethuraman**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:
Before:
Screenshot 2022-06-19 at 8 44 56 AM

After:
Screenshot 2022-06-19 at 8 45 45 AM

Hide TOC from main branch in print preview.

### CODE REVIEW

**Comment by snitin315** [comment]
Is there an open issue for this? Can you attach some before/after screenshots?

**Comment by harish-sethuraman** [comment]
https://github.com/eslint/eslint/issues/15948

**Comment by snitin315** [comment]
Next time please link issues in description itself. Also you can use keywords like `Fix` `Resolve` they help in automatically closing the linked issue when PR is merged.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
