### PR TITLE
Update: add returnAssign option to no-extra-parens (fixes #6036)

### LINKED ISSUE #6036: Rule no-extra-parens needs an option to allow `return (foo = bar)`
**What version of ESLint are you using?**: 2.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**: default

**Please show your full configuration:** https://gist.github.com/domenic/f6f5b7c294b610e7184b29d5e589d73b

**What did you do? Please include the actual source code causing the issue.**

```js
  parentNode() {
    let node = this._currentNode;
    while (!isNull(node) && node !== this.root) {
      node = node.parentNode;

      if (!isNull(node) && this._filterNode(node) === FILTER_ACCEPT) {
        return (this._currentNode = node);  // THIS LINE, THIS ONE RIGHT HERE
      }
    }
    return null;
  }
````

**What did you expect to happen?** Since I have configured no-return-assign to be "except-parens", I was hoping "no-extra-parens" would have an option that's compatible with my no-return-assign configuration, and would allow the extra parens in that particular case.

**What actually happened? Please include the actual, raw output from ESLint.**

```
C:\Users\Domenic\Dropbox\GitHub\tmpvar\jsdom\lib\jsdom\living\traversal\TreeWalker-impl.js
   46:16  error  Gratuitous parentheses around expression  no-extra-parens
```

This is a request to add another option to no-extra-parens to allow it in the return-assign case.

### PR DESCRIPTION
**Pull request by kaicataldo**

### CODE REVIEW

**Comment by mysticatea** [comment]
I think the option should allow parentheses only if it's assignment expression.
Currently this rule allows parentheses for multiline expression at return statements, so I don't think the option to allow all parentheses at return statements is needed.

```js
/*eslint no-extra-parens:2*/

// good
return shortCondition;
return (
    longCondition
);

// bad
return (shortCondition);
return (a = 1);
```

```js
/*eslint no-extra-parens:[2, {returnAssign: false}]*/

// good
return shortCondition;
return (
    longCondition
);
return (a = 1);

// bad
return (shortCondition);
```

**Comment by kaicataldo** [comment]
@mysticatea Hm, okay, in that case I have some questions. Should this rule only when the entire returned expression is an AssignmentExpression, or if the AssignmentExpression is a child node of the ReturnStatement? As an example, what would the option do if it encountered this?

`return node ? (this._someNode = foo) : (this._currentNode = bar);`

It seems like maybe the change should actually happen in the check of the AssignmentExpression rather than the ReturnStatement - we could traverse the parent nodes and if it is a child of a ReturnStatement it can be ignored.

**Comment by mysticatea** [comment]
Good point.
Actually, `conditionalAssign: false` seems to not allow assignment expressions in nested positions.
But, `no-cond-assign` and `no-return-assign` allow those, so I prefer `no-extra-parens` with options to allow those.

image

**Comment by kaicataldo** [comment]
Okay! Do you think I should try to fix nested assignments for `conditionalAssign` too? Or just do one at a time?

I think the `return` change is easier, because we can just check to see if any of the AssignmentExpression's parent nodes are ReturnStatements. The `conditionalAssign` change is a little trickier, I think, because you can't just check if it's a child node of a conditional statement. For instance, both of these are children of the IfStatement node:

screen shot 2016-05-06 at 10 59 02 am

Maybe we can check for if it is a child node of a conditional statement and specifically if it's a child of `node.test`.

**Comment by mysticatea** [comment]
No problem that only `returnAssign`.

By the way, I recently wrote a similar code: https://github.com/eslint/eslint/pull/6041/files#diff-1de274761ce8abec2245f9edf9e85d89R55

**Comment by kaicataldo** [comment]
Cool - I can make an issue to update the other option and make a PR for that after I do this one then :)

**Comment by kaicataldo** [comment]
Interesting challenge with this one. My changes seem to be working for AssignmentExpressions, but it's still failing on the ReturnStatement check. It looks like the ReturnStatement check always happens first.

**Comment by mysticatea** [comment]
Oh, I see. the rule is checking parens between a node and their child nodes, not between a node and their parent node. I hadn't been aware of that.

> I currently feel like it's fair to only check one nested level deep.

#6036 requests one nested level. So it's fair enough.
Thank you!

**Comment by zxqfox** [comment]
Just a though: `{code: "b => c ? (d = b) : (e = b);", options: ["all", {returnAssign: false}]},`

**Comment by kaicataldo** [comment]
@zxqfox Good call!

**Comment by kaicataldo** [comment]
Updated to also work with arrow functions - thanks @zxqfox!

**Comment by zxqfox** [comment]
np ;-) LGTM

**Comment by mysticatea** [comment]
Awesome, LGTM.

**Pull request merged**
