### PR TITLE
Chore: update release script for new website repo

### PR DESCRIPTION
**Pull request by kaicataldo**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain: Update release script

**What changes did you make? (Give an overview)**
refs https://github.com/eslint/website/issues/576

This updates the release script now that we've change the website repository name to `eslint/website`.

**Is there anything you'd like reviewers to focus on?**

I've already changed the repository name, turned off publishing to GitHub Pages, and have updated the Jenkins script. Did I miss anything?

### CODE REVIEW

**Comment by kaicataldo** [comment]
That’s an interesting point. Do you mean to rename the repository or just the name of the directory when we clone it in the release script? My inclination is that it’s probably fine as is since the releases are mostly run in Jenkins, but I don’t have a strong opinion and am happy to change it if others are concerned!

**Comment by mysticatea** [comment]
I think that we should move the script to `eslint/website` repo. Because `eslint/website` repo depends on `eslint` package, it can update the website without sibling directories.

**Comment by kaicataldo** [comment]
@mysticatea That sounds good to me. How do you feel about landing this first (just to make sure we’re not blocking the upcoming release)?

**Comment by kaicataldo** [comment]
As a side benefit, if we run the eslint release first and then run the site generation afterwards, we can also bundle eslint and espree in `eslint/website` as well.

**Pull request merged**
