### PR TITLE
Update: in quote-props rule allow consistent-as-needed with numbers option (fixes #8093)

### LINKED ISSUE #8093: quote-props: ["error", "consistent-as-needed", { "numbers": true }]
**What rule do you want to change?**
`quote-props`

**Does this change cause the rule to produce more or fewer warnings?**
Fewer for some situations, more for others

**How will the change be implemented? (New option, new default behavior, etc.)?**
New object option `numbers` for string option `consistent-as-needed`, consistent with the same object option for string option `as-needed`

**Please provide some example code that this change will affect:**
```js
var object1 = {
    foo: 'bar',
    baz: 42,
    42: true
};
var object2 = {
    'foo': 'bar',
    'baz': 42,
    '42': true
};
```

**What does the rule currently do for this code?**
Warn about unnecessary quotes for `object2`

**What will the rule do after it's changed?**
Warn about missing quotes for `object1`

### PR DESCRIPTION
**Pull request by thecotne**
fixes #8093

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

It is explained here #8093

**What changes did you make? (Give an overview)**

 - Updated tests in `tests/lib/rules/quote-props.js` according to issue description (#8093)
 - Updated rules in `lib/rules/quote-props.js` to fix tests
 - Updated docs in `docs/rules/quote-props.md` to explain new behavior

**Is there anything you'd like reviewers to focus on?**

No

### CODE REVIEW

**Comment by kaicataldo** [comment]
@thecotne Thanks for the PR. Just so you're aware, we won't be able to accept this issue until we have [reached consensus](https://eslint.org/docs/maintainer-guide/issues#consensus) that this should be included in ESLint.

Since the linked issue was closed due to lack of activity, I think we should treat this PR as a brand new proposal.

**Comment by platinumazure** [comment]
I've added my support for this proposal. We need two more team members to support and a third to champion.

**Comment by thecotne** [comment]
is this process expected to be this slow?

it's bean over a month since i proposed this change ...

**Comment by platinumazure** [comment]
> is this process expected to be this slow?
> 
> it's bean over a month since i proposed this change ...

Unfortunately, we're an all-volunteer team who have jobs and many other demands on our time, so this can sometimes happen. I apologize for the delay you've experienced.

**Comment by platinumazure** [comment]
@eslint/eslint-team Anyone want to support this proposal? If not, I'll probably have to close this.

**Comment by kaicataldo** [comment]
I'm unfortunately going to have to close this. It doesn't look like there is enough support from the team to reach consensus, and the corresponding proposal issue has been closed. Just in case it wasn't clear in our documentation (and please do let us know if it can be improved), we generally recommend waiting for a proposal to be accepted before working on implementation.

We really appreciate your contribution, regardless!

**Pull request closed without merging**
