### PR TITLE
chore: add jsdoc type annotation to rules

### PR DESCRIPTION
**Pull request by bmish**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[X] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Adds jsdoc `type` annotation to core rules.

Supported by VSCode/Webstorm/other code editors. Uses TypeScript declaration to give JavaScript hints so code editors can provide information/autocomplete about various rule fields.

https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#type

Idea from: https://github.com/eslint/generator-eslint/pull/113

133895350-a19d0daf-593e-44b9-835f-bebf8b6a3d30

We also have this suggested in our "Working with Rules" guide: https://eslint.org/docs/developer-guide/working-with-rules

Uses single-line version of this comment since there's no need for it to take up additional space.

#### Is there anything you'd like reviewers to focus on?

No.

### CODE REVIEW

**Comment by nzakas** [comment]
It seems like we should be using our own type definition:
https://github.com/eslint/eslint/blob/main/lib/shared/types.js

**Comment by bmish** [comment]
> It seems like we should be using our own type definition: [`main`/lib/shared/types.js](https://github.com/eslint/eslint/blob/main/lib/shared/types.js?rgh-link-date=2021-11-12T01%3A41%3A00Z)

That should work too, updated. The internal `Rule` type is pretty similar to the externally-maintained one from [@types/eslint](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/08a61be703d95f82173de8ce5ae3a660c50e0e84/types/eslint/index.d.ts#L433).

**Review by nzakas — APPROVED** [review]
LGTM

**Comment by bmish** [comment]
FYI: I have added a test to ensure this jsdoc comment is present in each rule file. Otherwise, it would be easily forgotten when adding new rules.

**Pull request merged**
