### PR TITLE
Docs: add documentation about custom-formatters. (fixes #1260)

### LINKED ISSUE #1260: Missing documentation about custom formatters [$10]
Since #172 ESLint can load custom formatters by path but I can’t find any documentation about that feature.
A "Working with Formatters" page, which explains how to write a custom formatter, would be nice too.

<bountysource-plugin>
---
There is a **[$10 open bounty](https://www.bountysource.com/issues/4345778-missing-documentation-about-custom-formatters-10?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by royriojas**

### CODE REVIEW

**Comment by nzakas** [comment]
Looks like the commit is failing the markdown lint. Can you check that?

**Comment by royriojas** [comment]
hi @nzakas, how can I run the markdown lint to verify the errors? please let me know

**Comment by btmills** [comment]
@royriojas Either run `npm test` from your checkout, or in this case you can [look at the same output on Travis](https://travis-ci.org/eslint/eslint/jobs/72067763) (you can get there via Details on the failure below).

**Comment by royriojas** [comment]
Hi guys I'm getting this error in the appveyor. Which is weird because I only added a markdown file :)

```bash
[92m  5341 passing (42s)
  1 failing
 
  1) cli "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  
 ```

Running it locally I see other error as well...

```bash
1 failing

  1) FileFinder findAllInDirectoryAndParents Not consider directory with expected file names should only find one package.json from the root:
     expected [ Array(2) ] to equal '/Users/roy/royws/eslint/package.json'
  AssertionError: expected [ Array(2) ] to equal 'package.json'
      at Context.<anonymous> (tests/lib/file-finder.js:178:24)


```

**Comment by IanVS** [comment]
Yes we have been having trouble with Appveyor tests timing out lately, please ignore that error.

**Comment by nzakas** [comment]
@royriojas can you add a link to this from the developer guide README.md?

**Comment by royriojas** [comment]
@nzakas Inside the `docs/developer-guide` folder I don't see any `README.md`, do you mean the `README.md` in the root?

**Comment by nzakas** [comment]
Hmm, right you are, that's strange. This must have inadvertently got moved into the website repo.

Nevermind!

**Comment by nzakas** [comment]
Can you reformat your commit message to have "(fixes #1260)" at the end? We like consistent commit messages for everything. Thanks!

**Comment by royriojas** [comment]
@nzakas. Done!

**Comment by nzakas** [comment]
Thanks!

**Pull request merged**
