### PR TITLE
New: add --fix to no-console.

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Add autofixing to a rule

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
I don't think we should remove `console.log` statements from the user's code -- it would break any code that relies on something getting printed.

**Comment by Aladdin-ADD** [comment]
I see both sides. it's quite useful -- for most users, `console.log` is used for debugging.

**Comment by platinumazure** [comment]
I am :-1: on removing entire statements in autofix here.

**Comment by Aladdin-ADD** [comment]
closing, not a good idea!

**Pull request closed without merging**
