### PR TITLE
Breaking: validate parserOptions (fixes #9687)

### LINKED ISSUE #9687: False negatives with sourceType: module and ecmaVersion <= 5
**Tell us about your environment**

* **ESLint Version:**
v4.12.1
* **Node Version:**
8.4.0
* **npm Version:**
5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    "parserOptions": {
        "sourceType": "module",
        "ecmaVersion": 5,
    }
}
```

</details>

Running against this file, ecmaVersion is ignored (could also be '3'):
 
```js
// es6.js
const x = () => `hi`;
```

**What did you expect to happen?**

Either, I would see an error like the below, rejecting an unsupported config:

```bash
> eslint -c withoutModule.config.js es6.js
Incompatible config: sourceType: module cannot be used with ecmaVersion <= 5
```

or the (admittedly niche*) use-case of ES6 modules with ES5 syntax would be supported, and I'd see errors:

```bash
> eslint -c withoutModule.config.js es6.js
es6.js
  1:1  error  Parsing error: The keyword 'const' is reserved

✖ 1 problem (1 error, 0 warnings)
```

which I get correctly with this config:

```js
// withoutModule.config.js
module.exports = {
    "parserOptions": {
        "ecmaVersion": 5,
    }
}
```

*niche: I was using rollup with some old ES5 code, and only wanted to modify the code to add imports. I tried the above, and thought "cool, it's working", but actually it was silently ignoring the ecmaVersion.

**What actually happened? Please include the actual, raw output from ESLint.**

No errors are reported:

```bash
> eslint es6.js
> echo $?
0
```

### LINKED ISSUE #11495: False positive in "newline-after-var" when using let under another let
**Tell us about your environment**

* **ESLint Version:** 5.15.1
* **Node Version:** 10.15.2
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "parser": "babel-eslint",
  "parserOptions": { "ecmaVersion": 6 },
  "env": { "es6": true },
  "rules": {
    "newline-after-var": [1, "always"]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const x = 1;
const y = 2;

var a = 3;
var b = 4;

let m = 5;
let n = 6;

console.log(x + y);
```

```bash
eslint "**/*.{js,jsx}"
```

**What did you expect to happen?**
No warnings.

**What actually happened? Please include the actual, raw output from ESLint.**
  7:1  warning  Expected blank line after variable declarations  newline-after-var

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.

**Are you willing to submit a pull request to fix this bug?**
No

### PR DESCRIPTION
**Pull request by aladdin-add**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
fixes #9687 

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by g-plane** [comment]
> What changes did you make? (Give an overview)
> fixes #11495

Is this wrong? 🤔

**Comment by platinumazure** [comment]
Can we actually do this in ESLint, when a user could put in a custom parser where these rules don't apply? I'm not sure we can.

**Comment by not-an-aardvark** [comment]
Personally, I think it would be better to put this in espree.

**Comment by aladdin-add** [comment]
closing, as it has been in espree.

**Pull request closed without merging**
