### PR TITLE
Docs: add TOC to user-guide/configuring.md

### PR DESCRIPTION
**Pull request by metasean**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Added a very basic Table of Contents to https://eslint.org/docs/user-guide/configuring / https://github.com/eslint/eslint/blob/master/docs/user-guide/configuring.md 

#### Is there anything you'd like reviewers to focus on?
https://github.com/metasean/eslint/blob/toc-for-contributing.md/docs/user-guide/configuring.md#configuring-eslint (scroll past the introductory text to see the TOC)

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Hi @metasean, thanks for the PR and sorry for the late response!

I think this would be a very useful addition. but we are currently reorganizing this document and that work will be done soon (#13632), so I'm not sure should we be making changes to this particular document in the meantime.

@kaicataldo what do you think about this?

**Comment by metasean** [comment]
@mdjermanovic - All I know is that I really hate having to search through this long page when I have a basic idea of what I'm looking for.  (And I'm assuming I'm not the only one with this problem.)

So, _as long as there's a _better_ way to navigate all this information I'll be happy_, regardless of whether that better way is based on this PR or on a re-organization of the documentation itself.

**Comment by kaicataldo** [comment]
I think this is fine. We will be updating this, but this seems useful in the interim. @khawarlatifkhan Thoughts?

**Review by kaicataldo — APPROVED** [review]

**Comment by khawarlatifkhan** [comment]
@metasean this is really helpful. Thank you! We are currently working on the configuration documentation, both to reorganize the documentation and to improve its presentation. This TOC will def be helpful in the process.

@kaicataldo Thank you for pointing this out. Will keep this in mind as we move forward with the project.

**Comment by mdjermanovic** [comment]
Marking as accepted then.

**Review by mdjermanovic — CHANGES_REQUESTED** [review]
I think that one link should be changed, everything else LGTM.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by mdjermanovic** [comment]
Thanks for contributing!

**Pull request merged**
