### PR TITLE
fix: rules/indent - handle node.declarations.length < 1

### PR DESCRIPTION
**Pull request by michachan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Tell us about your environment:**

* **ESLint Version:** 8.30.0
* **Node Version:** v16.14.2
* **npm Version:** 8.19.2

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
`@typescript-eslint/parser`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true,
    jest: true,
  },
  extends: [
    'plugin:promise/recommended',
    'eslint:recommended',
    'plugin:@next/next/recommended',
    'next/core-web-vitals',
    'prettier',
  ],
  overrides: [],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  plugins: [ 'import', 'prettier', 'react' ],
  rules: {
    indent: [ 'error', 2 ],
    quotes: [ 'error', 'single' ],
    semi: [ 'error', 'always' ],
    'arrow-parens': [ 'error', 'always' ],
    'quote-props': [ 'error', 'as-needed' ],
    'max-len': [ 'error', {} ],
    'no-multi-spaces': 'error',
    'array-bracket-newline': [ 'error', { multiline: true } ],
    'array-element-newline': [ 'error', 'consistent' ],
    'key-spacing': [ 'error', { beforeColon: false, afterColon: true } ],
    'comma-spacing': [ 'error', { before: false, after: true } ],
    'eol-last': [ 'error', 'always' ],
    'object-curly-spacing': [ 'error', 'always' ],
    // 'array-bracket-spacing': ['error', 'never', { singleValue: true }],
    'array-bracket-spacing': [ 'error', 'always' ],
    'no-multiple-empty-lines': [ 'error', { max: 1, maxBOF: 0 } ],
    'no-console': [ 'warn', { allow: [ 'warn', 'error' ] } ],
    'comma-dangle': [ 'error', 'always-multiline' ],
    'import/order': [
      'error',
      {
        'newlines-between': 'always',
        groups: [
          [ 'builtin', 'external', 'internal' ],
          [ 'parent' ],
          [ 'sibling', 'index' ],
        ],
        warnOnUnassignedImports: true,
      },
    ],
    'import/newline-after-import': [ 'error', { count: 1 } ],
    '@next/next/no-html-link-for-pages': [ 'error', 'my-app/pages' ],
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue.**

For the line below, if you type just `const` (as you continue to type out the rest of your code), it'll throw a type error, as it'll attempt to access a node declaration that doesn't exist. I'm adding optional chaining to `node.declarations[node.declarations.length - 1]` in order to guard against this error.

`if (node.declarations[node.declarations.length - 1].loc.start.line > node.loc.start.line) {`

**What did you expect to happen?**

I don't expect the `indent` rule to throw a TypeError, accessing property of undefined

**What actually happened? Please include the actual, raw output from ESLint.**

```[Error - 11:39:50 PM] ESLint stack trace:
[Error - 11:39:50 PM] TypeError: Cannot read properties of undefined (reading 'loc')
Occurred while linting /Users/mchan/projects/kdfksjfnsdkjfndfsd/my-app/theme/test.ts:1
Rule: "indent"
    at Object.VariableDeclaration [as listener] (/Users/mchan/projects/kdfksjfnsdkjfndfsd/my-app/node_modules/eslint/lib/rules/indent.js:1521:69)
    at /Users/mchan/projects/kdfksjfnsdkjfndfsd/my-app/node_modules/eslint/lib/rules/indent.js:1732:55
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/mchan/projects/kdfksjfnsdkjfndfsd/my-app/node_modules/eslint/lib/rules/indent.js:1732:26)
    at ruleErrorHandler (/Users/mchan/projects/kdfksjfnsdkjfndfsd/my-app/node_modules/eslint/lib/linter/linter.js:1115:28)
    at /Users/mchan/projects/kdfksjfnsdkjfndfsd/my-app/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/mchan/projects/kdfksjfnsdkjfndfsd/my-app/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/mchan/projects/kdfksjfnsdkjfndfsd/my-app/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/mchan/projects/kdfksjfnsdkjfndfsd/my-app/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
```

#### What changes did you make? (Give an overview)

Added optional chaining to gracefully handle situations where node.declarations.length is less than 1.

#### Is there anything you'd like reviewers to focus on?

No.

### CODE REVIEW

**Comment by yeonjuan** [comment]
@michachan If you want to lint typescript code, you should use rule [@typescript-eslint/indent](https://typescript-eslint.io/rules/indent/). 

- eslintrc
```js
module.exports = {
  "rules": {
    // Note: you must disable the base rule as it can report incorrect errors
    "indent": "off",
    "@typescript-eslint/indent": "warn"
  }
};
```

**Comment by michachan** [comment]
> Hi, @michachan If it's typescript project, you should use [@typescript-eslint/indent](https://typescript-eslint.io/rules/indent/).
> 
> * eslintrc
> 
> ```js
> module.exports = {
>   "rules": {
>     // Note: you must disable the base rule as it can report incorrect errors
>     "indent": "off",
>     "@typescript-eslint/indent": "warn"
>   }
> };
> ```

Good callout, thanks

**Comment by yeonjuan** [comment]
@michachan I close this PR because the reason is a rule configuration issue. Thanks!

**Comment by mdjermanovic** [comment]
Closing as the rule works as intended because `const` alone (`node.declarations.length < 1`) should be a parsing error and core rules are not designed to work with broken ASTs. For a workaround when using parsers that don't throw parsing errors on such code, you can use the `ignoredNodes` option of this rule: https://github.com/eslint/eslint/issues/14538#issuecomment-862280037

**Pull request closed without merging**
