### PR TITLE
Upgrade: Update globals and environments (fixed #2682)

### LINKED ISSUE #2682: Update globals and possible new environments
This is the issue for https://github.com/eslint/eslint/pull/2675 which updates the `globals` package and possibly would add two new environments. Dependency diff: https://github.com/sindresorhus/globals/compare/v6.1.0...7.1.0

Do we want to add `mongo` (https://github.com/sindresorhus/globals/pull/27) and `applescript` (https://github.com/sindresorhus/globals/pull/29) environments, or should I leave these out of the PR?

### PR DESCRIPTION
**Pull request by silverwind**
Diff: https://github.com/sindresorhus/globals/compare/v6.1.0...7.1.0

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks. Per our contribution guidelines, all pull requests must first have an issue filed explaining why a change is needed. In this case, we don't always include all of the environments that are available in the global package. Please see: http://eslint.org/docs/developer-guide/contributing

**Comment by silverwind** [comment]
Thanks, wasn't aware of the required issue. https://github.com/eslint/eslint/issues/2682 is up for discussion.

**Comment by gcochard** [comment]
You'll also want to update your commit message to start with `Upgrade: ` per http://eslint.org/docs/developer-guide/contributing#step-2:-make-your-changes

**Comment by silverwind** [comment]
Already done!

**Comment by gcochard** [comment]
:smile_cat:

**Comment by nzakas** [comment]
Thanks, can you sign our CLA? http://eslint.org/cla

**Comment by silverwind** [comment]
Signed, but let's hold on from merging this until we have a conclusion.

**Comment by ilyavolodin** [comment]
One more thing, can you update commit message with "New:" instead of "Update:" as this brings two new environments. And probably change it to mention that. Sorry for making you update it again.

**Comment by ilyavolodin** [comment]
LGTM. Thanks

**Pull request merged**
