### PR TITLE
Docs: Fixing last eol and other minor issues

### PR DESCRIPTION
**Pull request by ilyavolodin**
This fixes a few small issues in documentation. Missing EOL on the last line is causing site to render incorrectly.

### CODE REVIEW

**Comment by nzakas** [comment]
It looks like you're removing EOLs, isn't that the opposite of what you want?

And why not just have the build step add `\n` at the end of each file rather than manually doing it!

**Comment by ilyavolodin** [comment]
I removed a few line in the files that had 2 empty lines at the end. This is mostly for consistency. As far as I know, .md doesn't trim multiple empty lines, so you get multiple <br>'s in html as a result. Looks kindda odd. Same reason for not adding it to a build script.

**Comment by nzakas** [comment]
Again, this seems like something the build script should handle. Expecting people to put exactly one empty line at the end of all files and having an error when they don't doesn't seem like a useful way to do things.

**Comment by ilyavolodin** [comment]
Ok, I can buy that. I'll see if I can modify build script to automatically do that.

**Pull request closed without merging**
