### PR TITLE
Add es2018 to available environments

### PR DESCRIPTION
**Pull request by GhassenRjab**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

- [x] Documentation update
- [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
- [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-- proposal.md))
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)

Added `es2018 ` to available environments.

I used this in order to work with "Rest/Spread Properties" but it was not mentioned in the documentation.

#### Is there anything you'd like reviewers to focus on?

No, nothing in particular

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Hi @GhassenRjab, thanks for the PR!

> Added `es2018 ` to available environments.
> 
> I used this in order to work with "Rest/Spread Properties" but it was not mentioned in the documentation.

I don't think we have `es2018` environment. Did you maybe use `ecmaVersion: 2018` as a [parser option](https://eslint.org/docs/user-guide/configuring#specifying-parser-options)?

**Comment by GhassenRjab** [comment]
> I don't think we have `es2018` environment. Did you maybe use `ecmaVersion: 2018` as a [parser option](https://eslint.org/docs/user-guide/configuring#specifying-parser-options)?

Hi @mdjermanovic,
Yes I used the environment, here is my `.eslintrc.json` file now:
```
{
  "root": true,
  "extends": ["eslint:recommended", "plugin:prettier/recommended"],
  "env": {
    "node": true,
    "es2018": true
  }
}
```
If it is not the right way, I can use the parser options instead.

**Comment by mdjermanovic** [comment]
> ```json
> {
>   "root": true,
>   "extends": ["eslint:recommended", "plugin:prettier/recommended"],
>   "env": {
>     "node": true,
>     "es2018": true
>   }
> }
>```

Does this work? I'm getting the following error when I run eslint from the command line:

```
Oops! Something went wrong! :(

ESLint: 7.14.0

Error: .eslintrc.json:
        Environment key "es2018" is unknown
```

**Comment by GhassenRjab** [comment]
No it is not, sorry.
I had the impression it was working because my IDE didn't show errors, but it was because of ESLint not working.
I updated my `.eslintrc` to this:
```
{
  "root": true,
  "extends": ["eslint:recommended", "plugin:prettier/recommended"],
  "env": {
    "node": true,
    "es2017": true
  },
  "parserOptions": {
    "ecmaVersion": 9
  }
}
```
And this is working well.

I am closing this PR. I apologize for the inconvenience.

**Pull request closed without merging**
