### PR TITLE
docs: set default layouts

### PR DESCRIPTION
**Pull request by kecrily**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Set default layouts and remove `layout: doc`

### CODE REVIEW

**Comment by nzakas** [comment]
Can you explain a bit about why you made this change? (In general, please be sure to describe *why* you've made a change when you submit a pull request, not just what change you made.)

Also, is `layout.js` the official way to set a default layout in Eleventy?

**Comment by kecrily** [comment]
> Can you explain a bit about why you made this change? (In general, please be sure to describe _why_ you've made a change when you submit a pull request, not just what change you made.)

Since the default for most documents is `layout: docs`, if we specify the default layout, then we don't need to make this repetitive declaration.

> Also, is `layout.js` the official way to set a default layout in Eleventy?

I referenced https://github.com/11ty/eleventy/issues/380#issuecomment-568033456

**Comment by snitin315** [comment]
I don't have strong opinions here. I'm ok with either way to define `layout`.

**Review by nzakas — APPROVED** [review]
Okay. I'm not sure it matters, but it also doesn't seem to break anything, so fine by me.

**Pull request merged**
