### PR TITLE
New: Allow decimal arguments to indent's VariableDeclarator (fixes #3339)

### LINKED ISSUE #3339: Separate indent options for var, let and const
In my variable declarations, I prefer to vertically align the identifiers within each `var`, `let` or `const` declaration, eg.
```
// Note: '.' below represents a tab character

var foo = 1,  // <- 'foo' aligns with 'bar'
. . bar = 2;

let baz = 3,  // <- 'baz' aligns with 'qux'
. . qux = 4;

const a = 5,  // <- 'a' aligns with 'b'
. . . b = 6;
```
The following rule in ESLint@1.1.0:
```
"indent": [2, "tab", {"VariableDeclarator": 2}]
```
...yields the error `Expected indentation of 2 characters but found 3. (indent)`.
This is because the const `b` is indented by 3 tabs instead of 2 to maintain alignment with `a` (due to the keyword `const` being longer than both `var` and `let`).

(Note: I prefer tabs over spaces, but the same issue would apply to spaces also)

Just wondering if anyone else shares this preference (for lining up identifiers vertically), and if so, whether consideration should be given to expanding the `VariableDeclarator` option to allow individually specified indents for `var`, `let` and `const`, eg.
```
"indent": [2, "tab", {"VariableDeclarator": {"var": 2, "let": 2, "const": 3}}]
```
If not, alternatives that don't violate the `indent` rule would be either:
```
// VariableDeclarator: 3, with extra indentation on top lines of any var/let declarations 

/* eslint indent: [2, "tab", {"VariableDeclarator": 3}]*/

var. .foo = 1,  // <- Extra spacing between 'var' and 'foo'
. . . bar = 2;

let. .baz = 3,  // <- Extra spacing between 'let' and 'baz'
. . . qux = 4;

const a = 5,
. . . b = 6;
```
```
// VariableDeclarator: 2, and ignore const top line alignment, 

/* eslint indent: [2, "tab", {"VariableDeclarator": 2}]*/

var foo = 1,
. . bar = 2;

let baz = 3,
. . qux = 4;

const a = 5,  // <- 'a' doesn't align with 'b'...
. . b = 6;    // <- ...but 'b' does align with 'foo', 'bar', 'baz', etc.
```

### PR DESCRIPTION
**Pull request by sauyon**
#3339 

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What rule do you want to change?**

indent VariableDeclarator

**Does this change cause the rule to produce more or fewer warnings?**

Neither

**How will the change be implemented? (New option, new default behavior, etc.)?**

Slightly modified checking and adding a Math.round

**Please provide some example code that this change will affect:**

```js
const foo = 'bar',
      baz = 'foo';

if (foo === 'bar') {
    console.log(baz);
}
```

**What does the rule currently do for this code?**

There is no nice way to make eslint accept this code.

**What will the rule do after it's changed?**

Make eslint accept the code.

**What changes did you make? (Give an overview)**

Allow number parameters to indent VariableDeclarator, add a Math.round around offset calculation.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by sauyon** [comment]
Note: I get ERR! test failed from npm test but the output appears fine:

```
> eslint@4.2.0 test /home/sauyon/devel/eslint
> node Makefile.js test

Validating Makefile.js
Validating JSON Files
Validating Markdown Files
Validating JavaScript files
Validating JavaScript test files
Validating rules

  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬․]
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]

  16973 passing (43s)

=============================================================================
Writing coverage object [/home/sauyon/devel/eslint/coverage/coverage.json]
Writing coverage reports at [/home/sauyon/devel/eslint/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 99.48% ( 13321/13391 ), 157 ignored
Branches     : 98.3% ( 10187/10363 ), 116 ignored
Functions    : 99.87% ( 2286/2289 ), 26 ignored
Lines        : 99.48% ( 13211/13280 )
================================================================================
[BABEL] Note: The code generator has deoptimised the styling of "/home/sauyon/devel/eslint/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".

START:
21 07 2017 05:43:15.728:WARN [watcher]: All files matched by "/home/sauyon/devel/eslint/node_modules/mocha/mocha.js" were excluded or matched by prior matchers.
21 07 2017 05:43:16.281:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
21 07 2017 05:43:16.282:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
21 07 2017 05:43:16.286:INFO [launcher]: Starting browser PhantomJS
21 07 2017 05:44:16.346:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
21 07 2017 05:44:18.348:WARN [launcher]: PhantomJS was not killed in 2000 ms, sending SIGKILL.
21 07 2017 05:44:20.350:WARN [launcher]: PhantomJS was not killed by SIGKILL in 2000 ms, continuing.

Finished in 0 secs / 0 secs @ 05:44:20 GMT+0100 (BST)

npm ERR! Test failed.  See above for more details.
```

**Comment by not-an-aardvark** [comment]
Thanks for the contribution. I'm not opposed to allowing code like this to be aligned, but I'm also not a big fan of the proposed solution here. Allowing decimal offsets and rounding the result seems like a very hacky workaround to me.

If we're going to support alignment, I would prefer an option like `VariableDeclarator: "first"` that auto-aligns the code, rather than making people specify decimal offsets.

**Comment by sauyon** [comment]
That does seem better, yeah. I just implemented the suggestion in that issue thread without thinking.

I'll play around and see if I can get that set up - though from my cursory glance at the code for the indent rule I suspect it would take some refactoring for it to work properly.

**Comment by not-an-aardvark** [comment]
Yeah, I think if we were going to implement that, we would want to refactor the `VariableDeclaration` to use the `addElementListIndent` helper. Off the top of my head it seems like that should be doable, but I haven't tried it yet so there might be edge-cases I'm missing.

**Comment by not-an-aardvark** [comment]
By the way, you're certainly free to try to implement the `"first"` option if you want, but keep in mind that the team hasn't accepted the proposal yet, so there's a chance the proposal would be rejected and your time would have been wasted. If you'd like, you can create an issue for the proposal first and wait for it to hopefully get accepted before starting the implementation, so that you wouldn't risk wasting your time.

**Comment by not-an-aardvark** [comment]
Seems doable, but would require enhancing how `"first"` works, to allow indent collapsing behavior to be ignored.

<details>
<summary>WIP implementation (doesn't handle all cases correctly)</summary>

```diff
diff --git a/lib/rules/indent.js b/lib/rules/indent.js
index ec3f7917..d10e66ae 100644
--- a/lib/rules/indent.js
+++ b/lib/rules/indent.js
@@ -508,25 +508,13 @@ module.exports = {
                     },
                     VariableDeclarator: {
                         oneOf: [
-                            {
-                                type: "integer",
-                                minimum: 0
-                            },
+                            ELEMENT_LIST_SCHEMA,
                             {
                                 type: "object",
                                 properties: {
-                                    var: {
-                                        type: "integer",
-                                        minimum: 0
-                                    },
-                                    let: {
-                                        type: "integer",
-                                        minimum: 0
-                                    },
-                                    const: {
-                                        type: "integer",
-                                        minimum: 0
-                                    }
+                                    var: ELEMENT_LIST_SCHEMA,
+                                    let: ELEMENT_LIST_SCHEMA,
+                                    const: ELEMENT_LIST_SCHEMA
                                 },
                                 additionalProperties: false
                             }
@@ -631,7 +619,7 @@ module.exports = {
             if (context.options[1]) {
                 lodash.merge(options, context.options[1]);
 
-                if (typeof options.VariableDeclarator === "number") {
+                if (typeof options.VariableDeclarator !== "undefined" && typeof options.VariableDeclarator !== "object") {
                     options.VariableDeclarator = {
                         var: options.VariableDeclarator,
                         let: options.VariableDeclarator,
@@ -759,9 +747,10 @@ module.exports = {
         * @param {Token} startToken The start token of the list that element should be aligned against, e.g. '['
         * @param {Token} endToken The end token of the list, e.g. ']'
         * @param {number|string} offset The amount that the elements should be offset
+        * @param {boolean} force `true` if collapsing should be disabled
         * @returns {void}
         */
-        function addElementListIndent(elements, startToken, endToken, offset) {
+        function addElementListIndent(elements, startToken, endToken, offset, force) {
 
             /**
             * Gets the first token of a given element, including surrounding parentheses.
@@ -781,7 +770,8 @@ module.exports = {
             offsets.setDesiredOffsets(
                 [startToken.range[1], endToken.range[0]],
                 startToken,
-                offset === "first" ? 1 : offset
+                offset === "first" ? 1 : offset,
+                force
             );
             offsets.setDesiredOffset(endToken, startToken, 0);
 
@@ -1274,6 +1264,13 @@ module.exports = {
             },
 
             VariableDeclaration(node) {
+                const variableKeyword = sourceCode.getFirstToken(node);
+
+                /*
+                 * TODO: this is a bit of a hack because addElementsListIndent expects there to be a "last token"
+                 * (like a closing array bracket) which is always aligned with the first token.
+                 */
+                const semicolon = sourceCode.getLastToken(node);
                 const variableIndent = options.VariableDeclarator.hasOwnProperty(node.kind) ? options.VariableDeclarator[node.kind] : DEFAULT_VARIABLE_INDENT;
 
                 if (node.declarations[node.declarations.length - 1].loc.start.line > node.loc.start.line) {
@@ -1297,16 +1294,13 @@ module.exports = {
                      * on the same line as the start of the declaration, provided that there are declarators that
                      * follow this one.
                      */
-                    const firstToken = sourceCode.getFirstToken(node);
-
-                    offsets.setDesiredOffsets(node.range, firstToken, variableIndent, true);
+                    addElementListIndent(node.declarations, variableKeyword, semicolon, variableIndent, true);
                 } else {
-                    offsets.setDesiredOffsets(node.range, sourceCode.getFirstToken(node), variableIndent);
+                    addElementListIndent(node.declarations, variableKeyword, semicolon, variableIndent);
                 }
-                const lastToken = sourceCode.getLastToken(node);
 
-                if (astUtils.isSemicolonToken(lastToken)) {
-                    offsets.ignoreToken(lastToken);
+                if (astUtils.isSemicolonToken(semicolon)) {
+                    offsets.ignoreToken(semicolon);
                 }
             },
 
diff --git a/tests/lib/rules/indent.js b/tests/lib/rules/indent.js
index fb621cb4..722d3cee 100644
--- a/tests/lib/rules/indent.js
+++ b/tests/lib/rules/indent.js
@@ -4859,6 +4859,14 @@ ruleTester.run("indent", rule, {
                     );
                 }
             `
+        },
+        {
+            code: unIndent`
+                const foo = {
+                      },
+                      baz = 1
+            `,
+            options: [4, { VariableDeclarator: "first" }]
         }
     ],
 
@@ -9098,6 +9106,20 @@ ruleTester.run("indent", rule, {
                 </div>
             `,
             errors: expectedErrors([3, 8, 6, "Block"])
+        },
+        {
+            code: unIndent`
+                const foo = 1,
+                    bar = 2,
+                    baz = 3
+            `,
+            output: unIndent`
+                const foo = 1,
+                      bar = 2,
+                      baz = 3
+            `,
+            options: [4, { VariableDeclarator: "first" }],
+            errors: expectedErrors([[2, 6, 4, "Identifier"], [3, 6, 4, "Identifier"]])
         }
     ]
 });

```
</details>

**Comment by kaicataldo** [comment]
Where does this PR stand? It looks like the corresponding issue was actually closed quite a while ago.

**Comment by not-an-aardvark** [comment]
I think https://github.com/eslint/eslint/issues/8976 is now the current issue discussing this.

**Comment by kaicataldo** [comment]
I'm :-1: for this implementation but am :+1: for this issue: https://github.com/eslint/eslint/issues/8976

**Comment by not-an-aardvark** [comment]
Closing this PR since there seems to be consensus that it's not the right approach. We appreciate the contribution regardless!

Let's move further discussion to https://github.com/eslint/eslint/issues/8976.

**Pull request closed without merging**
