### PR TITLE
Docs: display team members in a table

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update

**What changes did you make? (Give an overview)**
display team members in a table, added avatars 😄 
image

**Is there anything you'd like reviewers to focus on?**

~~The col width is not perfectly equal, so it looks a little strange.~~
~~please feel free to close if you don't like it. ❤️~~
fixed! see the above screenshot~~

### CODE REVIEW

**Comment by platinumazure** [comment]
I think it might be worth taking a look at how the "all contributors" CLI does this. I think they create a table with fixed-width cells, which looks nicer.

**Comment by kaicataldo** [comment]
I like the idea of this! Mind putting a screenshot in the description so that everyone can see what this change looks like?

**Comment by kaicataldo** [comment]
Should we remove the inline styles? Otherwise, this LGTM

**Comment by not-an-aardvark** [comment]
It looks a bit strange to me that some of the faces are squashed horizontally. Is there a way to make the widths even?

**Comment by platinumazure** [comment]
Hi @Aladdin-ADD, you might want to take a look at this table (autogenerated by allcontributors-cli in my README).

https://raw.githubusercontent.com/platinumazure/eslint-plugin-qunit/master/README.md (Search for "all-contributors")

Hope this helps!

**Comment by Aladdin-ADD** [comment]
updated the screenshot, what do you think now? @not-an-aardvark @platinumazure

**Pull request merged**
