### PR TITLE
docs: update with TypeScript info

### PR DESCRIPTION
**Pull request by Zamiell**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update

#### What changes did you make? (Give an overview)

I added TypeScript information to the docs.

#### Is there anything you'd like reviewers to focus on?

No.

#### Motivation

The `no-dupe-class-members` rule helpfully documents that if you are using TypeScript, then you don't have to enable the rule. This is fantastic! However, there are many other ESLint rules that are also pointless if you are using TypeScript, but they are not documented. So this is the first step in solving that problem.

#### Other Discussion

I want to document all rules that are covered by the TypeScript compiler, and this PR is the first step in doing so.
In my next PR I would like to reduce the text duplication that I am introducing with this PR by using some kind of auto-filled template. I envision something like:

```
{{ TypeScript 2377 }}
```

Which would output the following text during the actual website build:

```
It is safe to disable this rule when using TypeScript because [TypeScript's compiler enforces this check (`ts(2377)`)](https://github.com/Microsoft/TypeScript/blob/main/src/compiler/diagnosticMessages.json).
```

I don't know if the docs already contains anything like this, so I would like a contributor to work with me to find the cleanest way to accomplish this.

Furthermore, I also want to include a TypeScript icon next to these kinds of texts to make it easier to see at a glance that the rule is covered already by TypeScript, which is another idea for a future PR.

### CODE REVIEW

**Review by nzakas — CHANGES_REQUESTED** [review]
Thanks for the updates. I don't think linking to the JSON file is helpful and for all we know that location could change.

Is there some documentation you could link to instead?

**Comment by Zamiell** [comment]
Hi nzakas,

I don't know if there is generic documentation for TypeScript error types. I googlged it and found [this StackOverflow page](https://stackoverflow.com/questions/33410124/complete-list-of-typescript-error-codes-and-their-fixes) that just links to the JSON file.

For now, I'll just edit the PR and remove the link.

Can you respond to the topics that I raised in the "Other Discussion" section?

**Comment by mdjermanovic** [comment]
> However, there are many other ESLint rules that are also pointless if you are using TypeScript, but they are not documented.

I think the typescript-eslint repository would be better place to maintain this list and maybe even provide a configuration that disables these rules. There's already a configuration that disables `eslint:recommended` rules that are redundant with TypeScript checks:

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts

**Comment by Zamiell** [comment]
@mdjermanovic I think that they have already decided against this; see [this issue](https://github.com/typescript-eslint/typescript-eslint/issues/6449).
Furthermore, `typescript-eslint` doesn't want to maintain documentation for extended rules (meaning the core ESLint rules that they tack on logic to), let alone non-extended rules.
Given that the ESLint docs are already documenting some rules that conflict with TypeScript, I would like to continue that trend here.

**Comment by mdjermanovic** [comment]
> I think that they have already decided against this; see [this issue](https://github.com/typescript-eslint/typescript-eslint/issues/6449).

Fair, but after reading https://github.com/typescript-eslint/typescript-eslint/issues/6449#issuecomment-1437692058, I'd agree with their suggestion that this should be a separate project as I'm not sure we could afford following versions of TypeScript and testing whether the rules we mark as safe to disable when using TypeScript are indeed completely covered by TypeScript.

**Comment by nzakas** [comment]
I'd say let's open a separate issue to discuss whether or not we want to track `tsc` settings. That's a much broader discussion than is appropriate for this small PR.

**Review by nzakas — APPROVED** [review]

**Pull request merged**
