### PR TITLE
Fix: Add lastToken check at padding-line-between-statements

### PR DESCRIPTION
**Pull request by outpunk**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Tell us about your environment**

* **ESLint Version:** v4.0.0
* **Node Version:** v8.1.0
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?**
 babel-eslint

**Please show your full configuration:**
```yaml
---
  extends: airbnb-base
  parser: babel-eslint

  settings:
    import/resolver:
      node:
        extensions:
          - .js
          - .ios.js
          - .androis.js
        moduleDirectory:
          - node_modules
          - js

  plugins:
    - babel
    - react
    - import

  parserOptions:
    ecmaVersion: 7
    sourceType: module
    ecmaFeatures:
      jsx: true
      modules: true

  env:
    es6: true
    node: true
    jest: true

  globals:
    __DEV__: true
    fetch: true
    XMLHttpRequest: true

  rules:
    import/no-unresolved:
      - 2
      - { ignore: [ '^[app]' ] }
    import/extensions: 0
    import/no-extraneous-dependencies: 0
    import/prefer-default-export: 0

    strict: [2, 'never']
    no-debugger: 2
    arrow-body-style: 0
    no-return-assign: 0
    no-plusplus: 0
    class-methods-use-this: 0
    no-underscore-dangle: 0

    brace-style:
      - 2
      - stroustrup
      - { allowSingleLine: true }

    template-curly-spacing: [2, 'always']
    array-bracket-spacing: [2, 'always']

    array-element-newline: [2, { multiline: true }]

    key-spacing:
      - 2
      -
        align:
          afterColon: true
          on: value

    padding-line-between-statements:
        - 2
        - { blankLine: 'always', prev: 'block-like', next: '*' }
        - { blankLine: 'always', prev: '*', next: 'block-like' }

        - { blankLine: 'always', prev: '*', next: 'return' }

        - { blankLine: 'always', prev: '*', next: 'function' }
        - { blankLine: 'always', prev: 'function', next: '*' }

        - { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*'}
        - { blankLine: 'any', prev: ['const', 'let', 'var'], next: ['const', 'let', 'var']}
        - { blankLine: 'always', prev: 'expression', next: ['const', 'let', 'var']}

        - { blankLine: 'always', prev: 'import', next: '*'}
        - { blankLine: 'any', prev: 'import', next: 'import'}

    id-length:
      - 2
      - { properties: 'never', exceptions: ['x', 'y', 'i', '_', 'e'] }

    jsx-quotes: [2, 'prefer-single']
    react/jsx-filename-extension: 0
    react/prefer-stateless-function: 0
    react/jsx-uses-react: 2
    react/jsx-uses-vars: 2
    react/jsx-first-prop-new-line: [2, 'multiline']
    react/jsx-indent-props: [2, 2]
    react/react-in-jsx-scope: 2
    react/jsx-curly-spacing: [2, 'always']
    react/jsx-equals-spacing: [2, 'always']
    react/forbid-prop-types:
      - 2
      - forbid: ['any', 'array']
    react/sort-comp:
      - 2
      -
        groups:
          lifecycle:
            - displayName
            - propTypes
            - contextTypes
            - childContextTypes
            - mixins
            - statics
            - defaultProps
            - state
            - constructor
            - getDefaultProps
            - getInitialState
            - getChildContext
            - componentWillMount
            - componentDidMount
            - componentWillReceiveProps
            - shouldComponentUpdate
            - componentWillUpdate
            - componentDidUpdate
            - componentWillLeave
            - componentWillUnmount
```

**What did you do? Please include the actual source code causing the issue.**

```js
import AppNavigator from './AppNavigator';

const initialState = AppNavigator.router.getStateForAction(
  AppNavigator.router.getActionForPathAndParams('Login'),
);

export function reducer(state = initialState, action) {
  const nextState = AppNavigator.router.getStateForAction(action, state);

  return nextState || state;
}
```

**What did you expect to happen?**
I expected eslint to lint my code

**What actually happened? Please include the actual, raw output from ESLint.**

```
$(yarn bin)/eslint js/**/*.js *.js
Cannot read property 'value' of null
TypeError: Cannot read property 'value' of null
    at Object.isClosingBraceToken (/Users/outpunk/Code/App/node_modules/eslint/lib/ast-utils.js:364:17)
    at isBlockLikeStatement (/Users/outpunk/Code/App/node_modules/eslint/lib/rules/padding-line-between-statements.js:96:36)
    at Object.test (/Users/outpunk/Code/App/node_modules/eslint/lib/rules/padding-line-between-statements.js:331:37)
    at match (/Users/outpunk/Code/App/node_modules/eslint/lib/rules/padding-line-between-statements.js:473:41)
    at getPaddingType (/Users/outpunk/Code/App/node_modules/eslint/lib/rules/padding-line-between-statements.js:489:21)
    at Linter.verify (/Users/outpunk/Code/App/node_modules/eslint/lib/rules/padding-line-between-statements.js:551:30)
    at emitOne (events.js:115:13)
    at Linter.emit (events.js:210:7)
    at NodeEventGenerator.applySelector (/Users/outpunk/Code/App/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/outpunk/Code/App/node_modules/eslint/lib/util/node-event-generator.js:292:22)
```

**What changes did you make? (Give an overview)**

I have added check for null value of `lastToken` at `isBlockLikeStatement` in `lib/rules/padding-line-between-statements.js`

**Is there anything you'd like reviewers to focus on?**
No

### CODE REVIEW

**Comment by gyandeeps** [comment]
Is the issue still present if you just use default parser and not `babel-eslint`?
Asking because I want to makesure its not a issue with babel-eslint.

**Comment by outpunk** [comment]
@gyandeeps Can't reproduce today, with both of the parsers

**Comment by outpunk** [comment]
@gyandeeps reproduced, the same thing with the default parser

**Comment by outpunk** [comment]
@gyandeeps any news?

**Comment by platinumazure** [comment]
@outpunk Can you add a test for this change, which fails without your code change and passes with? Thanks!

**Comment by outpunk** [comment]
@platinumazure I'll try

**Comment by kaicataldo** [comment]
Marking as accepted because it is the same bug as https://github.com/eslint/eslint/issues/8839.

@outpunk Hi! I missed this PR and [also made a PR to fix this](https://github.com/eslint/eslint/pull/8840), though I like your solution better.

I don't all my tests need to be ported over because this is a more generic solution (which is why I like it better!). I think the important test from the tests I wrote is to check that this is valid:

```js
{
     code: "function test() {};",
     options: [
         { blankLine: "always", prev: "block-like", next: "block-like" }
     ]
},
```
The other tests are tied more to my specific implementation, so I don't think you need to add those.

**Comment by outpunk** [comment]
@kaicataldo thanks! I'll add your tests in a couple of days — I'm a bit busy until next week.

**Comment by ilyavolodin** [comment]
@outpunk Friendly ping

**Comment by outpunk** [comment]
Thanks, will do tomorrow

**Comment by outpunk** [comment]
@platinumazure I've added the test

**Comment by kaicataldo** [comment]
Restarting the Travis CI tests because it looks like they timed out.

**Comment by not-an-aardvark** [comment]
Thanks for contributing!

**Comment by outpunk** [comment]
Thanks for accepting!

**Pull request merged**
