### PR TITLE
Docs: fix typos

### PR DESCRIPTION
**Pull request by jwilk**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Fixed a bunch of typos.
They were found using [mwic](http://jwilk.net/software/mwic) and [anorack](https://github.com/jwilk/anorack).

### CODE REVIEW

**Comment by ilyavolodin** [comment]
@jwilk Those changes look great. Could you sign our CLA please so we could merge this in?

**Comment by kaicataldo** [comment]
@jwilk One more friendly ping. We'd love to land this!

**Comment by jwilk** [comment]
I won't sign the CLA.
Sorry for wasting your time.

**Comment by gyandeeps** [comment]
I will work on this

**Pull request closed without merging**
