### PR TITLE
Document remedy to some prefer-const errors

### PR DESCRIPTION
**Pull request by turadg**
see https://github.com/eslint/eslint/commit/37e09d96ada4b19eadc464644b8e818a00e3979d#commitcomment-15180158

### CODE REVIEW

**Comment by michaelficarra** [comment]
I'm not sure this really adds anything to the docs.

**Comment by turadg** [comment]
I thought it would be helpful to the reader to have parity between the "considered problems" cases and the "not considered problems" cases.

For example, it would have preempted the conversation in https://github.com/eslint/eslint/commit/37e09d96ada4b19eadc464644b8e818a00e3979d#commitcomment-15180158

The fact that [developers of the third market share JS engine have been confused on this point](https://bugzilla.mozilla.org/show_bug.cgi?id=1094995) supports that it's worth documenting.

**Comment by michaelficarra** [comment]
Okay, :+1:. This should serve as a reminder why you should never appeal to some perceived authority.

**Comment by turadg** [comment]
Thanks for accepting. I don't have repository write access so this will require someone else to click to merge.

**Comment by michaelficarra** [comment]
I'm not a maintainer either :relaxed:.

**Comment by mysticatea** [comment]
:+1: thank you @turadg !

**Pull request merged**
