### PR TITLE
Add ESLint tutorial embed & links to `Getting started` docs page

### PR DESCRIPTION
**Pull request by jamischarles**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Prior context here:
https://github.com/eslint/eslint.github.io/issues/324

This PR adds a youtube embed of an ESLint Tutorial Video to the `Getting started` docs page.

@ilyavolodin I don't have strong feelings about any of the wording or placement. We don't even have to include the `Pluralsight` verbiage.

**Is there anything you'd like reviewers to focus on?**
Content and placement.

**Special Notes & Testing steps**
I added the embed and tested it in the `eslint.github.io` repo locally, and by publishing it as github pages. In both cases the youtube embed seemed to work fine. Screenshot:

screen shot 2017-01-23 at 9 50 21 pm

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
I don't really have a strong opinion either way, but I think it would be slightly better if the tutorial video was below the "Installation and Usage" section. Personally, I would want to read the section before watching the video.

**Comment by ilyavolodin** [comment]
@not-an-aardvark I think video should be either at the begging or the end of the article. I have no preference either way, but I think we should avoid putting it in the middle. Current placement seems fine to me.

@jamischarles Builds are failing because there's a linting validation in the markdown file. You are missing a line-break around header.

**Comment by jamischarles** [comment]
@ilyavolodin Fixed the lint issue (oh the irony...)

@not-an-aardvark I lean more towards the top, because people then know what options they have and can decide which medium they want to use to continue, but happy to move it if you guys want.

**Comment by ilyavolodin** [comment]
I'm also leaning more towards the top. People can skip the video and come back to it later, if they know that it's there. @not-an-aardvark If you are OK with video placement, I'll merge this in.

**Comment by jamischarles** [comment]
🎉 Thanks folks! When should I expect this change to show up on eslint.org (so I can verify that everything looks good)?

**Comment by ilyavolodin** [comment]
@jamischarles This should be available with next ESLint release. We are currently on hold waiting to do next patch release, due to some issues with our build server. Hopefully it will be resolved in the next few days.

**Pull request merged**
