### PR TITLE
Breaking: change no-comma-dangle to comma-dangle (fixes #1350)

### LINKED ISSUE #1350: Change no-comma-dangle to comma-dangle
Facebook requires dangling commas where possible, so we should change `no-comma-dangle` to `comma-dangle` with a default of `"never"` to mimic the current behavior. Those like Facebook who want to can change the setting to `"always"`.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5155934-change-no-comma-dangle-to-comma-dangle?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lo1tuma**

### CODE REVIEW

**Comment by lo1tuma** [comment]
Travis build failed because of #1947

**Comment by nzakas** [comment]
Okay, if you rebase it should work now.

**Comment by lo1tuma** [comment]
Rebased.

**Comment by nzakas** [comment]
Awesome, thanks. I know this will make @vjeux very happy. :)

Can you also add this to the tracking issue for rule removal?

**Comment by vjeux** [comment]
Awesome, can't wait for the release so that i can enable this on react native repo :)

**Pull request merged**
