### PR TITLE
chore: Remove CODEOWNERS

### PR DESCRIPTION
**Pull request by nschonni**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

#### What changes did you make? (Give an overview)

The GitHub CODEOWNERS file isn't intended to be a Markdown file, so removed the file extension

### CODE REVIEW

**Review by snitin315 — COMMENTED** [review]
GitHub does show a message if a CODEOWNERS file is valid or not, [like it shows here](https://github.com/webpack/webpack-cli/blob/master/CODEOWNERS#L1).

Screenshot 2022-10-02 at 7 17 38 AM

I don't see this validation in [ESLint's CODEOWNERS file](https://github.com/eslint/eslint/blob/main/.github/CODEOWNERS.md) which means it isn't valid.


We may also want to move this file to root and change the content of CODEOWNERS to :

`* @eslint/eslint-tsc @eslint/eslint-reviewers @eslint/eslint-commiters`

@eslint/eslint-tsc thoughts?

**Comment by nzakas** [comment]
We should just remove the file. It’s out of date and we’ve moved on from this type of strict checking.

**Comment by nschonni** [comment]
Do you want me to close this, or change it to include the delete instead?

**Comment by harish-sethuraman** [comment]
We can delete the file instead of renaming it.

**Pull request merged**
