### PR TITLE
fix: limit `readFile` concurrency

### PR DESCRIPTION
**Pull request by fasttime**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

refs #18977

#### What changes did you make? (Give an overview)

This a prototype implementation that limits the maximum number of pending `readFile` calls in `lintFiles` to 100. Another possible candidate for limiting concurrency is `loadConfigFile` in `lib/config/config-loader.js`.

This implementation does not retry on error. It passes the EMFILE handling test by just reducing the number of concurrent asynchronous calls.

### CODE REVIEW

**Comment by fasttime** [comment]
I did some quick performance testing by measuring the time it takes to lint the repo on Windows (with `Measure-Command {node .\bin\eslint.js}` in the PowerShell) and I'm getting similar results with or without limited concurrency.

But the EMFILE handling test is running way faster when concurrency is limited. For example, the last CI run on macos took 45 seconds:

https://github.com/eslint/eslint/actions/runs/11569747260/job/32204777020

Screen Shot 2024-10-29 at 09 54 08

While on the main branch it's taking over one minute:

https://github.com/eslint/eslint/actions/runs/11568209930/job/32199779723

Screen Shot 2024-10-29 at 09 54 47

**Comment by LiviaMedeiros** [comment]
Would it be possible to set user-defined `maxConcurrency` via config or command line option?

**Comment by fasttime** [comment]
> Would it be possible to set user-defined `maxConcurrency` via config or command line option?

The max concurrency value should have little visible impact as long as it is sufficiently large. I guess we'll just want to hard-code a value that's sensible value for all systems.

**Comment by nzakas** [comment]
Here's what I'm working on: https://github.com/eslint/eslint/pull/19077

**Comment by fasttime** [comment]
Closing as done in #19077.

**Pull request closed without merging**
