### PR TITLE
Fix: Allow adjacent rule fixes unless ranges are identical (fixes #4373)

### LINKED ISSUE #4373: Sequential fixes regression
While checking `gulp-eslint` unit tests against eslint@1.9.0, I found that the "fix" option failed to correct the second (earlier in code) of two fixable messages; though, this test would pass prior to 1.9.0. You can find the failing test [here](https://github.com/adametry/gulp-eslint/blob/412098fe32dda7e4adf34c360ec3744e9ddcad25/test/linting.js#L228), or as described below.

#### CLI-Config
```javascript
{fix: true, rules: {'no-extra-semi': 1, 'no-trailing-spaces': 2}}
```

#### JS Source
```javascript
var x = 0;; 
```
*Note that there is an extra space after the second comma*

#### Expected Fixed Output
```javascript
var x = 0;
```
*Note that the trailing space and second semi-colon have been removed*

#### Actual Fixed Output:
```javascript
var x = 0;;
```
*Note that only the trailing space has been removed*

After stepping through the ESLint code, I found that the change #4329 resulted in an off-by-one flaw. Specifically, `fix.range[1]` is an exclusive upper boundary, while `lastFixPos` is an inclusive lower boundary from the previous fix. When the opposing bounds are equal, the two boundaries do not overlap; rather, they are adjacent.

*eslint v1.9.0 (via gulp-eslint@1.1.0)*

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28115498-sequential-fixes-regression?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by platinumazure**
Reverts #4329, plus other enhancements. Fixes #4373.

The basic idea is that fixes with non-identical ranges will sort deterministically and the pre-#4329 logic for adjacent but not overlapping fixes worked perfectly. The problem arises with identical ranges, and in this case we assume that either fix could cause problems and so apply neither and let the user figure it out.

Currently I don't have rule-specific test cases. They may be unnecessary since I have unit tests for this. If we do need rule-specific test cases, I'm wondering if they should be in `cli-engine` tests since those use fixtures and are more like integration tests.

Two examples of identical range conflicts:

```js
/* eslint object-curly-spacing: [2, "always"], comma-dangle: [2, "always"] */
var obj = {a: true};
//                ^ Both rules want to insert here and have a fix with range [18, 18]. Bail out.
// Could be fixed by having object-curly-spacing do a replaceText ([18,19]) instead of insertTextBefore
```

And:

```js
/* eslint hypothetical-prefer-var: 2, prefer-const: 2 */
let value = 2;
// Both rules want to replace `let` (range [0, 3]) with something. Unclear what outcome should be, bailing out.
// Hopefully we won't create a "var" rule that conflicts with prefer-const.
```

### CODE REVIEW

**Comment by gyandeeps** [comment]
Help me understand what meaningful changes this PR belongs to the project. Since there was a change made to the `eqeqeq` code to use a different strategy. Now with code in this PR and the new `eqeqeq` changes if I run eslint in fix mode for below code, nothing gets fixed.

**With current PR Code and new `eqeqeq` changes:
Input:
```js
/* eslint "eqeqeq": 2, "space-infix-ops": 2 */
if (x ==4) {
    x++;
}
``` 

Output:
```js
/* eslint "eqeqeq": 2, "space-infix-ops": 2 */
if (x ==4) {
    x++;
}
``` 

**Without current PR Code and with new `eqeqeq` changes:
Input:
```js
/* eslint "eqeqeq": 2, "space-infix-ops": 2 */
if (x ==4) {
    x++;
}
``` 

Output:
```js
/* eslint "eqeqeq": 2, "space-infix-ops": 2 */
if (x ===4) {
    x++;
}
``` 

So what is this PR doing? I am missing something here?

**Comment by platinumazure** [comment]
Hi @gyandeeps, thanks for reviewing this. Unfortunately my pull request was not complete, contrary to my belief. I have fixed the issue, added more tests, and force-pushed.

I made bad assumptions about 2 things when drafting this fix originally:

1. I assumed the fixes were strictly sorted by endpoint (reverse order of occurrence within text), then by startpoint (also reverse order of occurrence within text). Taking a look at the code again, I see that they were only partially ordered-- if one fix definitely ended at or before the start of another fix, those fixes were guaranteed to be ordered, but anything else would be ordered arbitrarily. That seems like a potential issue since we want to be confident of our fix application order, so I fixed that in this PR.

1. I misunderstood the implications of the new `eqeqeq` changes with regard to `space-infix-ops`. For some reason I had thought that `space-infix-ops` only inserted a space character, but in reality it must perform a `replaceText` in case of having to add space at each end. Even with the example above (space only needed after `==` operator), this means the range for both fixes is now identical, and so it is correct that both fixes are not applied. I have added a test case to `tests/lib/cli-engine.js` to reflect this. When you look at the fix objects for both messages, it becomes clear that we cannot reasonably figure out how to interleave a replacement of `==` to `== ` with a replacement of `==` to `===`. Yes, we are potentially missing a fix opportunity (adding single `=` character), but honestly both of the fixes read better semantically and it is safer for us to be conservative about applying fixes. (This is the same rationale as #4329, the difference being my approach allows adjacent fixes.)

I have added the test case from #4373 (`no-extra-semi`/`no-trailing-spaces`) to show that both of those fixes are now successfully applied with my changes. Those fixes are not able to be applied with the #4329 approach. So this PR does make improvements.

Again, I apologize for failing to submit a working PR the first time around and for my misconceptions that caused a communication breakdown. I hope the updated commit and this message help clear things up. Thanks again for reviewing this.

**Comment by platinumazure** [comment]
@nzakas Looks like I might have goofed in my understanding of `space-infix-ops`'s auto-fix modus operandi when I submitted my `eqeqeq` changes yesterday. The result now is that the fix ranges for both rules overlap exactly, and with this changeset, neither will get applied. Without this changeset, one fix does get applied. Is it more important that we fix where possible, even at the cost of semantics/maintainability within the auto-fix code for a rule? Or is it more acceptable that we try to keep the fixes semantically sensible and err on the side of caution when applying fixes? If you consider the former more important, you might want to revert my `eqeqeq` changes.

**Comment by gyandeeps** [comment]
If 2 fixes have identical ranges then why not let one fix get applied and leve the other (As it happens currently in master), why are we changing this behavior? Why was issue which triggered identical range change?

The whole conversation in this issue was about where a range overlaps each other like `[1, 4]` and `[4, 6]`.

**Comment by platinumazure** [comment]
Which one should be applied in that case? Coin flip?

I'm game for trying to apply one fix, but I'm afraid of causing other
problems or having unclear messages.

Take `eqeqeq` and `space-infix-ops`: If space-infix-ops mentioned the
operator in question (this is hypothetical- it does not do this as of now)
and the eqeqeq is auto-fixed, then the space message could become unclear
(it would hypothetically say `'==' operator must be surrounded with spaces`
even though the operator has been transformed to `===`).

**Comment by platinumazure** [comment]
Also, `[1,4]` and `[4,6]` are not overlapping ranges- they were incorrectly
treated as such in #4329 and I have fixed that in this PR.

**Comment by platinumazure** [comment]
I've thought about it some more and I realize that before #4329, we would have always been at risk of applying a fix that invalidates an error message located in the same place. I will prepare a PR that doesn't include the overlap logic and just reverts #4329 (along with some of my new cli-engine test cases) and we'll see how that looks. Hope that sounds okay.

**Pull request closed without merging**
