### PR TITLE
Fix: missing support for json sub configs

### LINKED ISSUE #5413: Sub-configs stopped supporting json files
**What version of ESLint are you using?**
2.0.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**What did you do? Please include the actual source code causing the issue.**
Updated eslint from v1 to v2 with my shareable config.

**What did you expect to happen?**
My shareable config would continue to work with sub-configs as json files.

**What actually happened? Please include the actual, raw output from ESLint.**
```
D:\Projects\project\node_modules\eslint\lib\config\config-file.js:361
            throw e;
            ^

Error: Cannot find module 'eslint-config-noamokman/test' from 'D:\Projects\project\node_modules'
Referenced from: D:\Projects\project\test\.eslintrc
    at Function.module.exports [as sync] (D:\Projects\project\node_modules\resolve\lib\sync.js:33:11)
    at resolve (D:\Projects\project\node_modules\eslint\lib\config\config-file.js:417:38)
    at load (D:\Projects\project\node_modules\eslint\lib\config\config-file.js:436:24)
    at D:\Projects\project\node_modules\eslint\lib\config\config-file.js:355:36
    at Array.reduceRight (native)
    at applyExtends (D:\Projects\project\node_modules\eslint\lib\config\config-file.js:338:28)
    at Object.load (D:\Projects\project\node_modules\eslint\lib\config\config-file.js:464:22)
    at loadConfig (D:\Projects\project\node_modules\eslint\lib\config.js:67:33)
    at getLocalConfig (D:\Projects\project\node_modules\eslint\lib\config.js:129:23)
    at Config.getConfig (D:\Projects\project\node_modules\eslint\lib\config.js:222:22)
```

Hi, now that we got the formalities out of the way,
I have a shareable config called [eslint-config-noamokman](https://github.com/noamokman/eslint-config-noamokman).
I recently updated it to work with eslint 2.
But it seems that the `test` sub config stopped working.
After checking the problem, it seems that the resolve module can't search for a json file when given: `eslint-config-noamokman/test`.

My module has an `eslint.json` for the main config, and a `test.json` for testing.
Changing from `test.json` to `test.js` fixes the problem, but I would like to add support for both.

I know that I have to open an issue first, so if everything looks good I would like to submit a PR.

Thanks,
Noam.

### PR DESCRIPTION
**Pull request by noamokman**
Fixes #5413 :smile:

### CODE REVIEW

**Comment by IanVS** [comment]
Looks like the commit is just missing the parenthesis around the "fixes #5413".

**Comment by noamokman** [comment]
Oh man... @IanVS Thanks!

**Comment by nzakas** [comment]
@noamokman the change looks good. Can you also add a test for this?

**Comment by platinumazure** [comment]
This looks reasonable to me. Just two questions:

1. Can any test changes be done to ensure that we are using `resolveModule.sync` with the correct options, to help avoid regression?
1. Looking at the changes, it seems that we might also have removed support for YAML sub-configurations as well. Should we address that here?

**Comment by noamokman** [comment]
I took a look at the tests and it seems that the `resolveModule.sync` function is somewhat mocked, and doesn't reach the part handling the arguments we use at this case.
Can we merge this for now? This is a breaking change that needs a patch.

**Comment by IanVS** [comment]
Actually, it looks like we don't have any tests at all around sub configs (unless I'm missing it, the tests aren't the easiest to understand).

**Comment by platinumazure** [comment]
I don't speak for the core team, but I think we need *something* in the testing space to reduce the chances that this accidentally regresses. The fact that this is a breaking change badly in need of a patch only underscores that point further, in my view.

**Comment by IanVS** [comment]
Yes, we require tests for all bugfix PRs.  From our [contributing guidelines](http://eslint.org/docs/developer-guide/contributing/pull-requests#step-6-double-check-your-submission):

> All changes must be accompanied by tests, even if the feature you're working on previously had no tests.

I think we need tests around sub configs of all supported types.

**Comment by nzakas** [comment]
> The fact that this is a breaking change badly in need of a patch only underscores that point further, in my view.

@platinumazure why do you think this is a breaking change?

**Comment by platinumazure** [comment]
@nzakas This PR does not represent a breaking change. I was referring to this comment:

> Can we merge this for now? This is a breaking change that needs a patch.

In other words, I was referring to the original regression. I apologize for the confusion.

**Comment by noamokman** [comment]
@kaicataldo sorry, been a bit busy.
Tests has been added and checked :smile:

**Comment by kaicataldo** [comment]
No need to apologize, just wanted to follow up since it had been awhile :) Just need to get the team members who commented earlier to give a final rubber stamp of approval @nzakas @platinumazure @IanVS

**Comment by nzakas** [comment]
LGTM. Thanks!

**Pull request merged**
