### PR TITLE
Fix: Make Chai as a dependency (fixes #3156)

### LINKED ISSUE #3156: api.js is broken
in current master, if I require `api.js` in "production" mode:

```
Cannot find module 'chai'
```

because chai is in devDeps

(this error came when trying to use Atom's linter-eslint with eslint's master)

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by nzakas** [comment]
Does Mocha also need to be added?

**Comment by gyandeeps** [comment]
I dont think so as it should be required by the plugin who consumes eslint.
I will double check.

**Comment by IanVS** [comment]
Looking at the dependencies of `eslint-tester`:

```
  "dependencies": {
    "chai": "^1.10.0",
    "eslint": "latest",
    "is-my-json-valid": "^2.10.1",
    "lodash.clonedeep": "^3.0.0",
    "lodash.merge": "^3.1.0",
    "lodash.omit": "^3.1.0",
    "mocha": "~1.17.1"
  }
```

Compared to `eslint`:

```
"dependencies": {
    "chalk": "^1.0.0",
    "concat-stream": "^1.4.6",
    "debug": "^2.1.1",
    "doctrine": "^0.6.2",
    "escape-string-regexp": "^1.0.2",
    "escope": "^3.2.0",
    "espree": "^2.2.0",
    "estraverse": "^4.1.0",
    "estraverse-fb": "^1.3.1",
    "globals": "^8.2.0",
    "inquirer": "^0.8.2",
    "is-my-json-valid": "^2.10.0",
    "js-yaml": "^3.2.5",
    "lodash.clonedeep": "^3.0.1",
    "lodash.merge": "^3.3.2",
    "lodash.omit": "^3.1.0",
    "minimatch": "^2.0.1",
    "mkdirp": "^0.5.0",
    "object-assign": "^2.0.0",
    "optionator": "^0.5.0",
    "path-is-absolute": "^1.0.0",
    "path-is-inside": "^1.0.1",
    "strip-json-comments": "~1.0.1",
    "text-table": "~0.2.0",
    "user-home": "^1.0.0",
    "xml-escape": "~1.0.0"
  }
```

It looks like `mocha` is the only other missing.

**Comment by gyandeeps** [comment]
I looked at couple of plugins and they all the mocha dependency. Since when they run the unit test they call mocha directly.
https://github.com/ilyavolodin/eslint-plugin-backbone/blob/master/package.json
https://github.com/yannickcr/eslint-plugin-react/blob/master/package.json

**Comment by IanVS** [comment]
Then why was it a dependency of eslint-tester?  Maybe it didn't need to be you're saying?

**Comment by gyandeeps** [comment]
Yes, thats what I think based on what I have seen so far.

**Comment by lo1tuma** [comment]
I think a `peerDependency` would be the correct relationship.

**Comment by IanVS** [comment]
Yes, I think you're right @lo1tuma,  but from what I've seen so far, peerDependencies are awful.  I think it would cause the least headaches to keep as a direct dependency.

**Comment by nzakas** [comment]
Let's just add mocha as a dependency for now, we can sort out the other stuff later.

**Comment by gyandeeps** [comment]
@nzakas Done.

**Comment by nzakas** [comment]
Thanks!

**Pull request merged**
