### PR TITLE
Docs: Minor grammar edit for `curly`

### PR DESCRIPTION
**Pull request by wilkinson**
This just adds a missing word to the documentation. I will probably send some more patches shortly :-)

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Could you make sure your commit message summary begins with "Docs:".

**Comment by wilkinson** [comment]
Not until you change the patch submission directions accordingly ;-)

**Comment by ilyavolodin** [comment]
You mean like here: http://eslint.org/docs/developer-guide/contributing.html under "Step 2: Make your changes"?

**Comment by wilkinson** [comment]
Ah, you are correct, it is already there :-)

**Comment by wilkinson** [comment]
I have changed the commit message as requested. Please let me know if there are other things I've overlooked. Obviously, I didn't read the directions closely enough, and for this I apologize. This is exactly why ESLint is so useful -- because we all make mistakes. Sorry about that!

**Pull request merged**
