### PR TITLE
Updating optionator dep to 0.8.1 (fixes #4851)

### LINKED ISSUE #4851: Outdated Optionator dep brings in deprecated version of lodash
The Optionator 0.8.0 dep brings in deprecated version of lodash (>3). This warning is displayed during `npm install`. Updating to 0.8.1 should resolve it. I'll submit a PR...

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29545812-outdated-optionator-dep-brings-in-deprecated-version-of-lodash?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by edj-boston**
Fixes npm install warning for deprecated version of lodash

### CODE REVIEW

**Comment by gyandeeps** [comment]
Check travis build error message to fix your PR. Thanks

**Comment by edj-boston** [comment]
All set!

**Comment by nzakas** [comment]
Can you please change your commit message to begin with "Upgrade:" instead of "Update:"?

**Comment by michaelficarra** [comment]
Please address the comment from @gyandeeps in #4851 before merging. This change seems unnecessary.

**Comment by edj-boston** [comment]
All set!

**Comment by nzakas** [comment]
I'm assuming he submitted the PR because he ran into a problem. In any event, this change doesn't hurt.

**Pull request merged**
