### PR TITLE
Fix: source code fixer does not handle undefined source code (fixes #4016)

### LINKED ISSUE #4016: Source code fixer does not handle undefined source code correctly
When running `eslint src --fix` I encountered the following error:

```bash
$ eslint src --fix
/usr/local/lib/node_modules/eslint/lib/util/source-code-fixer.js:62
        text = sourceCode.text,
                         ^
TypeError: Cannot read property 'text' of null
    at Function.SourceCodeFixer.applyFixes (/usr/local/lib/node_modules/eslint/lib/util/source-code-fixer.js:62:26)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:224:43)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:257:18)
    at executeOnFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:600:23)
    at Array.forEach (native)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:626:49
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:622:18)
    at Object.cli.execute (/usr/local/lib/node_modules/eslint/lib/cli.js:159:95)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint/bin/eslint.js:61:20)
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27117197-source-code-fixer-does-not-handle-undefined-source-code-correctly?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jvandemo**
This PR fixes #4016.

### CODE REVIEW

**Comment by jvandemo** [comment]
@nzakas &mdash; The checks failed because the commit message is too long.

Shall I create a new PR? Or can this be fixed in another way?

Thanks!

**Comment by ilyavolodin** [comment]
@jvandemo You can use:
```
$ git add .
$ git commit --amend --no-edit
$ git push -f
```

**Comment by michaelficarra** [comment]
Just amend your commit and force-push. If you don't know how to do that, there's plenty of guides on the internet.

**Comment by jvandemo** [comment]
Awesome &mdash; it worked, thank you @ilyavolodin and @michaelficarra!

All checks pass now :+1:

**Comment by nzakas** [comment]
LGTM

**Pull request merged**
