### PR TITLE
Chore: remove path-is-absolute in favor of the built-in (fixes #6598)

### LINKED ISSUE #6598: `path-is-absolute` module is no longer needed
ESLint should have depended on [`path-is-absolute`](https://www.npmjs.com/package/path-is-absolute) module for Node.js 0.10 support. However, from ESLint v3.0.0, we can use Node's built-in [`path.isAbsolute`](https://nodejs.org/api/path.html#path_path_isabsolute_path) because there is no need to consider Node 0.x anymore.

### PR DESCRIPTION
**Pull request by shinnn**
Fixes #6598.

### CODE REVIEW

**Comment by alberto** [comment]
LGTM

**Comment by gyandeeps** [comment]
yay i less dependency....

**Comment by alberto** [comment]
@gyandeeps you just merged it

**Comment by shinnn** [comment]
@alberto @gyandeeps Thanks for the review.

**Pull request merged**
