### PR TITLE
New: display beginner-friendly message if Node version is below(fixes #10549)

### LINKED ISSUE #10549: ESlint crashes with syntax error when run on lower version of Node
When newly installed, eslint crashes, if no config file has been generated yet. Is this nominal behavior?

C:\Users\Jon\Aukitekt\frontend>npm install eslint -g
....
C:\Users\Jon\Aukitekt\frontend>eslint
C:\Users\Jon\AppData\Roaming\npm\node_modules\eslint\lib\linter.js:739
                [methodName](...args) {
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Jon\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:21:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Tell us about your environment**

* **ESLint Version:**
5.0.1
* **Node Version:**
5.7.1
* **npm Version:**
3.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
not existing

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

### PR DESCRIPTION
**Pull request by aladdin-add**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain: refs https://github.com/eslint/eslint.github.io/issues/493

**What changes did you make? (Give an overview)**
image

**Is there anything you'd like reviewers to focus on?**

as @not-an-aardvark suggested,
+ removed the dep `please-upgrade-node-fork`
+ changed `bin/eslint.js` (-x)
+ moved the checking to a separate file `bin/eslint-cli.js` (+x)
+ changed bin: `bin/eslint.js` => `bin/eslint-cli.js`

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
A few thoughts:

* Should we move all the other code out of `bin/eslint.js` into a different file so that the message still works if we add new syntax to that code?
* This seems like it would be effectively a three-line code addition to implement, so I'm not sure if it's worth adding a dependency for.
* I feel like in an ideal world this would be the package manager's problem, and packages wouldn't need to use runtime checks for node version. I also wonder if this is just a short-term problem -- presumably most new users who use ESLint aren't going to be starting out on Node 4.

None of these are strong objections, just thoughts that came to mind when looking at the PR. I'm fine with this being merged if we think it would be a worthwhile addition for UX.

**Comment by platinumazure** [comment]
I think this could be worthwhile to add, if we can do so with minimal maintenance cost (including, if possible, no new dependency).

@Aladdin-ADD Have you had a chance to look into this again?

**Comment by Aladdin-ADD** [comment]
sure, I can update it this weekend!

**Comment by Aladdin-ADD** [comment]
@platinumazure having it in lib/eslint.js sounds reasonable. but I have a concern: it might add the difficulty to browserify eslint (though we don't support browser officially)

**Comment by platinumazure** [comment]
@Aladdin-ADD @not-an-aardvark What are the next steps here?

**Comment by not-an-aardvark** [comment]
I think this might need TSC approval since it's an enhancement to the CLI.

**Comment by kaicataldo** [comment]
Mind explaining why the [package.json `engines` field](https://docs.npmjs.com/files/package.json#engines) isn't satisfactory here?

**Comment by not-an-aardvark** [comment]
Maybe others can elaborate, but I think the issue is that npm's warning message for the `engines` field is not easily understandable for inexperienced users:

screen shot 2018-09-03 at 1 40 11 am

npm typically outputs a lot of warnings, many of which don't need to be immediately addressed. I suspect that users are often accustomed to ignoring warnings from npm, particularly warnings that they don't understand, and they might not realize that the warnings are related to the fact that an installed package doesn't work.

(The above screenshot is from npm 2.15.11, the version bundled with Node 4. I'm not sure if the message has been changed in more recent versions of npm.)

**Comment by platinumazure** [comment]
@kaicataldo The npm warning only occurs during install-- nothing stops users from running the package's main script even if their engine is outside of the package.json "engines" version range(s). The goal is to have ESLint fail more gracefully with a clear message, rather than having a syntax error or similar that doesn't immediately explain what the real problem is.

**Comment by kaicataldo** [comment]
What's the status of this? Is https://github.com/eslint/eslint/issues/10549 the relevant issue (I don't see it referenced in this PR, but maybe I'm just missing it)?

**Comment by nzakas** [comment]
**TSC Summary:** This pull request adds a check for the correct version of Node.js to use with ESLint. It outputs a simple message when ESLint is run if the Node.js version is incorrect. It does this by adding a new `eslint-cli.js` file that runs before the current `bin/eslint.js` file (in case the latter needs newer syntax that an older version of Node.js doesn't support).

**TSC Question:** Shall we merge this pull request?

**Comment by btmills** [comment]
Thank you for building this, @aladdin-add! We discussed it in today's TSC meeting, and everyone was generally in favor of adding some sort of message if this sort of problem persists, but since we haven't been getting issues about it lately, we're not going to add any messages right now. We're hoping that, by the next time we drop an unsupported Node version, package managers are checking for engine compatibility and displaying warnings so we don't have to, but if that doesn't happen, we may end up resurrecting this PR.

**Pull request closed without merging**
