### PR TITLE
Fix link typos in user-guide/README.md

### PR DESCRIPTION
**Pull request by clambodile**
Fix: Change several links which previously 404'd

**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Added ".md" to the ends of several links which 404'd previously.

**Is there anything you'd like reviewers to focus on?**
The links should work now.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Thanks for PR. But those links are actually correct. We use this document to generate website pages, and on the website we can't have `md` extensions. So I think this will actually break generated webpage. Granted, that webpage is not linked to by any other page, but...

**Comment by kaicataldo** [comment]
Thanks for contributing to ESLint. I think @ilyavolodin is right about this one - the links currently do seem to be working: http://eslint.org/docs/user-guide/

**Comment by clambodile** [comment]
Ah, I only noticed that they weren't working in github, but I didn't realize they were being used to generate another webpage. Thanks for your time, fellas.

**Comment by vitorbal** [comment]
Thanks, @clambodile! Closing, as it seems the links are indeed working as intended.

**Comment by kaicataldo** [comment]
@clambodile Appreciate the contribution :)

**Pull request closed without merging**
