### PR TITLE
concat-stream known to be vulnerable prior 1.5.2

### PR DESCRIPTION
**Pull request by faust64**
https://snyk.io/vuln/npm:concat-stream:20160901?utm_source=slack

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

**What changes did you make? (Give an overview)**

update a vulnerable dependency to the first known-to-be safe version

**Is there anything you'd like reviewers to focus on?**

https://snyk.io/vuln/npm:concat-stream:20160901?utm_source=slack

### CODE REVIEW

**Comment by vitorbal** [comment]
Hmm, why didn't this change trigger a travis build? 🤔

**Comment by not-an-aardvark** [comment]
It looks like Travis is having some trouble building PRs today: https://www.traviscistatus.com/incidents/ccp8bj1x2n6y

**Comment by faust64** [comment]
I'm not much familiar with re-writing commit messages. Is it normal I had to merge after amending my own (local) commit?! I can open a new PR, if you prefer.

**Comment by shinnn** [comment]
@vitorbal Probably we're faced with this problem: https://www.traviscistatus.com/incidents/ccp8bj1x2n6y

**Comment by vitorbal** [comment]
@faust64 if you amend a commit that was already pushed to upstream, you have to do a `push --force` to be able to overwrite the git history. I wouldn't worry much about it, though, the diff looks legit and we can squash all commits into one before merging.
Thanks a lot for the contribution!

**Comment by faust64** [comment]
Thanks, I'll keep that in mind.

**Comment by ilyavolodin** [comment]
Looks like Travis build was triggered, so removing `do-not-merge` label

**Comment by not-an-aardvark** [comment]
For what it's worth, I don't think we are vulnerable to this particular security issue.

If we're going to upgrade, I think it would be better to upgrade to the latest version (v1.6.0). But it also might not be necessary to do that.

**Comment by vitorbal** [comment]
Damnit, I forgot to edit the commit message before merging this in 😟 how did we usually go about this in the past?

**Comment by ilyavolodin** [comment]
@vitorbal You either have to re-write history (master branch is protected against force pushes, so protection has to be disabled and re-enabled after you are done). Or you can revert this commit and merge it back in with the right commit message. Problem with the second approach is that create of the PR has to re-submit it:-(

**Comment by vitorbal** [comment]
After chatting with the team, we've decided to keep the commit history untouched and manually edit the release changelog for this release cycle.

**Pull request merged**
