### PR TITLE
Update: support bigint and dynamic import (refs #11803)

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Add something to the core (#11803).

**What changes did you make? (Give an overview)**

This PR adds supports of bigint and dynamic import.

- Upgrade `espree` and `eslint-visitor-keys`.
- Fix `CodePathAnalyzer` to handle `ImportExpression` node as throwable.
- Fix `new-cap` rule's false positive.
- Fix `astUtils.getPrecedence` function to fix `no-extra-paren` false positive.
- Fix `astUtils.isNullLiteral` function to fix `eqeqeq` false positive.
- Update `func-call-spacing` rule to recognize `ImportExpression` node.
- Update `function-paren-newline` rule to recognize `ImportExpression` node.
- Update `indent` rule to recognize `ImportExpression` node.
- Update `no-extra-parens` rule to recognize `ImportExpression` node.
- Add `env.es2020` to declare new global variables: `BigInt`, `BigInt64Array`, and `BigUint64Array`.
- In passing, add `env.es2017` to declare new global variables: `Atomics` and `SharedBufferArray`. I'm not sure why we have not had it.

(platinumazure: Consumed espree/eslint-visitor-keys, fixed merge conflicts, did some minor chores to get tests to pass-- see commit list.)

**Is there anything you'd like reviewers to focus on?**

There are a ton of remaining stuff (see #11803), but those are "enhancements which increase errors." As following our semver policy, we need a major update to add those... :(

Or maybe can we add those with a minor?

### CODE REVIEW

**Comment by mysticatea** [comment]
> There are a ton of remaining stuff (see #11803), but those are "enhancements which increase errors." > As following our semver policy, we need a major update to add those... :(
>
> Or maybe can we add those with a minor?

We can update `ImportExpression`-related change safely because nobody has used `ImportExpression` node at all. (previously, it had been represented with `CallExpression` node with `Import` node in experimental. `babel-eslint` and `@typescript-eslint/parser` are using the old form.

**Comment by mercmobily** [comment]
What's the status of this PR? #11803 depends on it.

**Comment by mysticatea** [comment]
Please track https://github.com/eslint/eslint/issues/11803. This PR is waiting on new `acorn` release and the updates of `espree` and `eslint-visitor-keys`.

**Comment by mdjermanovic** [comment]
A small fix for `dot-notation` in PR #12095.

`astUtils.getStaticPropertyName` should be also aware of the `Literal.bigint` property, there is a pending PR #12056 which fixes the same for regex, feel free to copy everything to this PR if that would be more convenient for the project.

There might be an issue with `no-implicit-coercion` which auto-fixes `+foo` to `Number(foo)` as these two are no longer equivalent (`+` throws if `foo` is a bigint).

**Pull request merged**
