### PR TITLE
Fix: `no-empty` rule should allow any comments (fixes #2188)

### LINKED ISSUE #2188: `no-empty` rule should allow empty blocks with any single comment
If a single comment "// empty" is sufficient in the eyes of the `eslint` maintainers to mean "this empty block is intentional", then shouldn't *any* comment in an empty catch block be sufficient?

A specific example of this is here: https://github.com/es-shims/es5-shim/blob/1e3abcb09f9914f6fe408ddffb7471e5b98e053c/es5-sham.js#L109-L113

To me, that comment is far more explicit than "empty" and imo it should pass the rule.

(Related to #1841, #2187)

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by gyandeeps** [comment]
@ljharb does it look good now?

**Comment by ljharb** [comment]
LGTM, thanks

**Comment by nzakas** [comment]
:+1: thanks @gyandeeps

**Comment by doberkofler** [comment]
@gyandeeps I think, the documentation of the rule still needs to be changed as it still matches my original requirement of a specific comment containing `empty`.

**Comment by nzakas** [comment]
Good catch!

**Pull request merged**
