### PR TITLE
Docs: do not recommend global-installed usage

### PR DESCRIPTION
**Pull request by aladdin-add**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
do not recommend global-installed usage. this has been discussed for a long time, and seems we have done some work in this direction.

refs:
* https://github.com/eslint/eslint/issues/11914
* https://github.com/eslint/rfcs/pull/32

**Is there anything you'd like reviewers to focus on?**
seems it was not a trivial change, will it discussed in a TSC meeting?

### CODE REVIEW

**Comment by ilyavolodin** [comment]
I think it's fine to include those changes. Don't think they are controversial enough to warren TSC discussion.

**Comment by aladdin-add** [comment]
@kaicataldo no worries, leaving it as a draft, I just want to double-check if some more background is required. but it seems pretty clear.  😄

**Comment by aladdin-add** [comment]
well, I'm going to leave it open for a longer time -- to see if there is any objections from the team, and the community.

**Comment by GrayedFox** [comment]
To be honest, I've always wondered why a global installation was recommended, when nearly every project I've ever worked on bundles a specific version of eslint within the package.json :smile_cat:

**Pull request merged**
