### PR TITLE
Update: add `backtick` to `--init` (fixes #7997)

### LINKED ISSUE #7997: backtick open not shown in eslint --init
**What version are you using?**
v3.14.1

**What did you do?**
ran `eslint --init`

**What happened?**
for quotes, it only showed single or double

**What did you expect to happen?**
it should give the options of single, double or backtick.

### PR DESCRIPTION
**Pull request by alberto**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[X] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Add an option to `eslint --init` to set `quotes` rule to `backtick`.

**Is there anything you'd like reviewers to focus on?**
No

### CODE REVIEW

**Comment by platinumazure** [comment]
Only one question from me: Do we know that the version of Inquirer we support will allow answers to be a function that returns an array of answers? If not, we should make sure to bump the Inquirer dependency.

**Comment by alberto** [comment]
works on my machine

**Comment by platinumazure** [comment]
Yes, but we tend to do permissive dependency ranges in our dependencies
list. It seems that we should force users to upgrade to newer inquirer if
that should be necessary. (Also: As a TSC member, I'm a bit surprised you
would use the "works on my machine" canard.)

**Comment by not-an-aardvark** [comment]
We specify `"inquirer": "^0.12.0"` in `package.json`, and `0.12.0` is the only version that satisfies that range. So I think we should be fine.

(That said, maybe we should upgrade inquirer at some point -- it's at 3.0.1 now.)

**Comment by platinumazure** [comment]
Thanks @not-an-aardvark, that satisfies my concern.

**Comment by alberto** [comment]
I must have missed the "no fun allowed" policy.

As @not-an-aardvark mentioned, I used "0.12.0", the only version that matches our package.json. But that part of the code interacts with the cli and the filesystem, so it's no fully covered in the tests and I can't guarantee with 100% certainity it will run without problems for anyone.

Anyhow, I don't think upgrading inquirer to a different major version lowers the risk of breakage, _au contraire_.

**Comment by platinumazure** [comment]
@alberto Memes are fine, I just didn't like the implied message of "if it works on my machine, then it doesn't matter if we break the ecosystem". Apologies for misunderstanding.

**Comment by alberto** [comment]
Closing since the issue wasn't accepted

**Pull request closed without merging**
