### PR TITLE
Docs: remove outdated note about caching only valid files (fixes #10739)

### LINKED ISSUE #10739: Documentation about Caching is outdated
**The version of ESLint you are using.** v5.3.0

**The problem you want to solve.**

Since #10571 now also stores the result of failing files, the docs are no longer correct: https://eslint.org/docs/user-guide/command-line-interface#caching

> Note:: As of now, only the results for successfully linted files are stored in the cache. Files which fail linting are not stored in the cache, so they will be linted every time.

**Your take on the correct solution to problem.**

Just remove this paragraph.

### PR DESCRIPTION
**Pull request by ajafff**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Remove outdated paragraph.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by platinumazure** [comment]
I think this is probably okay as is, but I'll note that if a file is autofixed, it will not be stored in the cache (or rather, the changing of the file as part of autofix will invalidate the cache entry). So it would need to be linted one more time, and then it would be in the cache.

That said-- not sure that is an important note, so this is probably fine as it is.

**Comment by kaicataldo** [comment]
@ajafff Friendly ping!

**Comment by platinumazure** [comment]
@ajafff Friendly ping: Are you able to finish this? Let us know if we can help!

**Comment by zacnomore** [comment]
I'd like to take this over if that's alright. It's been a number of weeks at this point.

**Comment by zacnomore** [comment]
Added PR: #10913

**Comment by platinumazure** [comment]
Closing as #10913 was merged to resolve the original issue. Thanks for contributing regardless, we really appreciate it!

**Pull request closed without merging**
