### PR TITLE
Update: Adding environment for commonalities between node and browser

### PR DESCRIPTION
**Pull request by TheSavior**
Following up from https://github.com/eslint/eslint/issues/3599

### CODE REVIEW

**Comment by TheSavior** [comment]
It would be valuable to know why this was labeled as "Do not merge".

If it is related to the CLA, I signed that yesterday.

**Comment by nzakas** [comment]
When the bot message is triggered, we typically wait for the author of the pull request to comment. Prior to that, the PR shouldn't be merged.

In this case, the commit doesn't reference an issue and there was no real description for the PR. The issue mentioned in the description was closed, so it's unclear the purpose of this PR.

**Comment by TheSavior** [comment]
I created issue #5196 and updated the commit message to reference it.

**Comment by nzakas** [comment]
Thanks, can you also update the configuration docs to mention this environment?

**Comment by TheSavior** [comment]
Done. I apparently forgot to commit that change. :)

**Comment by gyandeeps** [comment]
LGTM. Thanks

**Pull request merged**
