### PR TITLE
Build: automatically convert line endings in release script (fixes #2642)

### LINKED ISSUE #2642: automatically convert line endings in release script
the release script today always publishes whatever files are on the local disk. That means misconfigured get repositories can change line endings and we can end up publishing files that won't work on Macs. We should add in a step that automatically converts all line endings to Unix style.

### PR DESCRIPTION
**Pull request by BYK**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Nice! LGTM.

**Comment by nzakas** [comment]
Cool! Can you update the commit message to begin with "Build:"?

**Comment by BYK** [comment]
@nzakas - oops, sorry :) Done!

**Comment by nzakas** [comment]
Thanks!

**Pull request merged**
