### PR TITLE
Fix: Check YieldExpression argument in no-extra-parens (fixes #4608)

### LINKED ISSUE #4608: no-extra-parens missing YieldExpression
While working on #4229, I came across this:

```js
function *test() {
  yield 1;
  yield (2);
  yield       // 4:8 - Missing semicolon. (semi)
    3;
  yield (
    4
  );
  return (5); // 9:10 - Gratuitous parentheses around expression. (no-extra-parens)
}

for (let val of test()) {
  console.log(val); // 1 2 (blank) 4
}
```

I ran the above code in the demo with only `no-extra-parens` and `semi` enabled and pasted the errors inline. I included `semi` and the `return` as sanity checks.

I would expect a warning about excess parens on `yield (2);`, but there was none. Looking at the source, `no-extra-parens` doesn't check `YieldExpression`s, so hopefully the fix is as simple as adding that check.

Working on this.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28866252-no-extra-parens-missing-yieldexpression?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by btmills**

### CODE REVIEW

**Comment by michaelficarra** [comment]
Please check expressions around this precedence boundary (as we do in lines 51 through 113). This will also give you some passing tests.

**Comment by btmills** [comment]
@michaelficarra Well that got quite a bit hairier, but it fixed a few bugs. Thanks. Does it look like I've covered everything adequately now?

**Comment by michaelficarra** [comment]
LGTM.

**Comment by michaelficarra** [comment]
Actually, please add a `yield yield` test.

**Comment by btmills** [comment]
As in what I just added on line 202?

**Comment by michaelficarra** [comment]
Yes. :+1:

**Pull request merged**
