### PR TITLE
Fix sandwiches typo

### PR DESCRIPTION
**Pull request by sebastiansandqvist**
Fixed a strange recurring typo in docs.

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks! Can you please update your commit message to begin with "Docs:"?

**Comment by sebastiansandqvist** [comment]
Not sure if I did this right. Is a new commit sufficient, or do I need to manually change the original commit message?

**Comment by btmills** [comment]
You'll want to squash all of the commits into one. The contributing guide has a [step for that](http://eslint.org/docs/developer-guide/contributing/pull-requests#step5) with a link to a guide.

**Comment by sebastiansandqvist** [comment]
It doesn't look like that's something I can do just through github, so I'll go ahead and close this. Just wanted to make a quick fix to a typo I had noticed.

**Comment by nzakas** [comment]
And we appreciate that, we just have some guidelines we need everyone to follow. For future reference: http://eslint.org/docs/developer-guide/contributing/pull-requests

**Comment by IanVS** [comment]
I can make this fix in my doc linting PR.

**Pull request closed without merging**
