### PR TITLE
Config package internal resolve

### PR DESCRIPTION
**Pull request by mattfysh**
Allows `@scope/eslint-config/es5` and `@scope/eslint-config/babel`

### CODE REVIEW

**Comment by platinumazure** [comment]
Can you link this to an issue?

**Comment by mattfysh** [comment]
@platinumazure sure thing - added #5158

**Comment by ilyavolodin** [comment]
Could you update commit message to start with "Fix:" and end with "(fixes #5158)"? Also can you add a few unittests to verify the fix?

**Comment by nzakas** [comment]
Already fixed. See note on #5158.

**Pull request closed without merging**
