### PR TITLE
Upgrade: @eslint/eslintrc@1.0.0

### PR DESCRIPTION
**Pull request by mdjermanovic**
Remaining steps:

- [x] import environments from the `@eslint/eslintrc` API.
- [x] update `package.json` with the new version of `@eslint/eslintrc`.

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

Updates ESLint to use `@eslint/eslintrc` version with the `"exports"` field in package.json (https://github.com/eslint/eslintrc/pull/39), presumably in v8.0.0.

#### What changes did you make? (Give an overview)

* Updated modules that used deep imports such as `require("@eslint/eslintrc/lib/shared/config-ops")` to use the `Legacy` API from the main (and only) entry point.
* Removed unused functions from `in-memory-fs`.

#### Is there anything you'd like reviewers to focus on?

* Was there a reason we were using `require("@eslint/eslintrc/lib/shared/config-ops")` and others instead of `Legacy`?
* Fixing `in-memory-fs` would be a bit more complicated and untestable since we're not using it anymore (aside from one function `defineInMemoryFs`), so I just removed the unused functions.
* ~Environments are imported using a "hack" with absolute paths, in order to test other changes. This will be fixed when we update eslint/eslintrc#39.~ fixed

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Browser Test is failing:

```
ERROR in ./node_modules/resolve-from/index.js 5:15-32
Module not found: Error: Can't resolve 'module' in '/home/runner/work/eslint/eslint/node_modules/resolve-from'
 @ ./node_modules/import-fresh/index.js 5:20-43
 @ ./node_modules/@eslint/eslintrc/dist/eslintrc.cjs 7:18-41
 @ ./lib/linter/linter.js 23:4-31

ERROR in ./node_modules/resolve-from/index.js 7:11-24
Module not found: Error: Can't resolve 'fs' in '/home/runner/work/eslint/eslint/node_modules/resolve-from'
 @ ./node_modules/import-fresh/index.js 5:20-43
 @ ./node_modules/@eslint/eslintrc/dist/eslintrc.cjs 7:18-41
 @ ./lib/linter/linter.js 23:4-31

ERROR in ./node_modules/@eslint/eslintrc/dist/eslintrc.cjs 5:9-22
Module not found: Error: Can't resolve 'fs' in '/home/runner/work/eslint/eslint/node_modules/@eslint/eslintrc/dist'
 @ ./lib/linter/linter.js 23:4-31

ERROR in ./node_modules/@eslint/eslintrc/dist/eslintrc.cjs 11:13-30
Module not found: Error: Can't resolve 'module' in '/home/runner/work/eslint/eslint/node_modules/@eslint/eslintrc/dist'
 @ ./lib/linter/linter.js 23:4-31

webpack compiled with 4 errors
```

**Comment by nzakas** [comment]
Opened https://github.com/eslint/eslintrc/pull/51

**Comment by nzakas** [comment]
Published @eslint/eslintrc v1.0.0: https://github.com/eslint/eslintrc/releases/tag/v1.0.0

**Review by nzakas — APPROVED** [review]
LGTM

**Review by btmills — APPROVED** [review]

**Pull request merged**
