### PR TITLE
Build: Add karma-chrome-launcher support

### PR DESCRIPTION
**Pull request by aladdin-add**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x ] Other, please explain:

**What changes did you make? (Give an overview)**
the change was merged in https://github.com/eslint/eslint/pull/10898, but was reverted in https://github.com/eslint/eslint/pull/10973, due to a release build failing on Jenkins.

the change added it back again, and added `puppeteer ` in dev, to fix the build failing.

**Is there anything you'd like reviewers to focus on?**

what can we do to make sure it fixed the issue? (e.g. run on Jenkins)

### CODE REVIEW

**Comment by Aladdin-ADD** [comment]
I think it was discussed in https://github.com/eslint/eslint/pull/10898. it was introduced as Phantomjs no longer being maintained, than to help validate our unofficial browser capability.

**Comment by g-plane** [comment]
Once we are going to use Chrome, `babel-core`, `babelify`, `babel-polyfill` and `babel-preset-es2015` can be removed.

**Comment by aladdin-add** [comment]
@g-plane switching to chrome does not mean dropping support IE. so I'm not sure we can remove these deps. but it seems a good idea to upgrade babel 7, since `babel-*` were no longer maintained.

**Comment by not-an-aardvark** [comment]
Ignoring the CLA checker because the name changed and the email address is the same (also see https://github.com/eslint/eslint/pull/11220#issuecomment-451560551).

**Pull request merged**
