### PR TITLE
Fix: Shared config being clobbered by other config (fixes #2592)

### LINKED ISSUE #2592: Shared config doesn't cascade properly
I've been trying to isolate this bug, but it seems to only occur under very specific conditions. I'll continue trying to boil this down, but for now I'll report what I know.

I have a company shared-config, with 2 modes: `node` and `browser` Our app's config hierarchy looks like:

 * `.eslintrc`: `{ extends: "segment/node" }`
 * `app/client/.eslintrc`: `{ extends: "segment/browser" }`

When ESLint runs, it approaches files in this order:

 * `app/client/index.js`
 * `app/server.js`

What happens is that the `server.js` file (which should _only_ be following `segment/node`) is wrongly failing because of rules in `segment/browser`. If I manually reverse the order, it processes the rules correctly. (which tells me that some clobbering is happening between various config objects)

I've dropped a couple `console.log` in there to try and follow the cascade and see where things go awry. The first time `segment/node` is loaded, it appears to get the right value, but all subsequent times get the wrong value.

From what I can see, `utils.mergeConfig()` modifies the `base` directly, which I suspect is the source of this problem. I'm hoping the solution can be as simple as cloning the config objects after being `require`d as to prevent clobbering.

### PR DESCRIPTION
**Pull request by dominicbarnes**
this is my approach to solving the issue I found in #2592

### CODE REVIEW

**Comment by dominicbarnes** [comment]
fwiw, this solves the problem I came across

**Comment by ilyavolodin** [comment]
Can you format you commit message to follow our [contributing guidelines](http://eslint.org/docs/developer-guide/contributing) please? Also you would need to sign our [cla](http://eslint.org/cla/).

**Comment by ilyavolodin** [comment]
@gyandeeps Can you review please? You did the previous fix for this issue. I'm guessing your fix didn't cover all use cases and should be removed in favor of this one (I don't want unnecessary code laying around the codebase).

**Comment by dominicbarnes** [comment]
All right, I have signed the CLA, squashed my commits and rewritten the subject. Let me know if there's anything else I need to do :)

**Comment by dominicbarnes** [comment]
Haha, just thought that last message was not really what should be shown on a changelog. I'm done now, seriously :)

**Comment by gyandeeps** [comment]
I was expecting the change to be made on line 95 only. But I guess it works the way we have it right now also.
yeah, when I made the change I was under the impression that `object-assign` actually did a deep copy. I think we should be good after making this change.

**Comment by ilyavolodin** [comment]
So lines 94-96 should just be removed, since they don't serve any purpose now. @dominicbarnes would you mind updating your pull request with that please? That was the old fix for the same issue, that didn't quite fix it.

**Comment by gyandeeps** [comment]
No they can't be removed. At the end we need to assign everything to `config` object.

**Comment by nzakas** [comment]
Reminder: we need tests to verify all changes.

**Comment by ilyavolodin** [comment]
@dominicbarnes Can you update your pull request with the test for this? It took me a bit to figure out how to test this, but I think I got it. You need to create StubbedConfig (like we do everywhere else) and then use `configHelper.getConfig` twice on two different config files both of which extend the same shared config. And then check the output of the first `getConfig` call for the rules that were added in the second one.

**Comment by dominicbarnes** [comment]
I should be able to write up a test sometime this weekend

**Comment by dominicbarnes** [comment]
All right, I've written the test and updated this PR. We should be ready to go now, once CI passes of course. :)

**Comment by ilyavolodin** [comment]
LGTM. One last thing, unfortunately I can't check right now if you already signed our cla. If you haven't, could you sign it here http://eslint.org/cla/ and let me know when it's done.

**Comment by dominicbarnes** [comment]
I've already signed the CLA. :)

**Pull request merged**
