### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by balazsorban44**
Fixing a typo.

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [x] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain: Fixing `PULL_REQUEST_TEMPLATE.md`

#### What changes did you make? (Give an overview)

Corrected the markdown checklist, and added a word

#### Is there anything you'd like reviewers to focus on?
No.

### CODE REVIEW

**Comment by platinumazure** [comment]
Hi @balazsorban44, thanks for the PR.

Regarding the checkboxes not being checkboxes: This is intentional-- if you change them to checkboxes, then the PR List will show them as uncompleted tasks. (For example, this PR says only 3 out of 10 tasks are done.)

In reality, only the first section is really supposed to be a task list. The second section is conceptually more like a radio button, but GitHub-flavored Markdown does not have any way to represent this. So we intentionally use text-based boxes and ask people to put an X in them, so it's clear what the pull request type is but also does not create new tasks that will never actually be completed.

This is also referenced in prior discussions, including [here](https://github.com/eslint/eslint/pull/7072#discussion-diff-77872859).

We would love to accept a PR for adding the word "an", as that is definitely a typo and we would love to fix it. So if you want to revert the check box changes but preserve the "an" addition, we could probably accept and merge this. Thanks!

**Comment by kaicataldo** [comment]
If you wouldn't mind updating the commit message to start with `Chore:`, that would be great.

**Comment by balazsorban44** [comment]
Thanks for all the comments! :slightly_smiling_face: Fixed now, and I understand the reasoning.

**Comment by kaicataldo** [comment]
Thanks for contributing to ESLint!

**Pull request merged**
