### PR TITLE
docs: improve styles for versions and languages page

### PR DESCRIPTION
**Pull request by snitin315**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### What changes did you make? (Give an overview)

- [Preview Languages Page](https://deploy-preview-16553--docs-eslint.netlify.app/languages/)
- [Preview Versions Page](https://deploy-preview-16553--docs-eslint.netlify.app/versions/)
### Before

Screenshot 2022-11-16 at 7 44 19 AM

Screenshot 2022-11-16 at 7 44 13 AM

### After
Screenshot 2022-11-16 at 7 41 22 AM
Screenshot 2022-11-16 at 7 41 16 AM

### CODE REVIEW

**Comment by amareshsm** [comment]
In the preview still, it is showing the old one.
https://deploy-preview-16553--docs-eslint.netlify.app/languages/

image

**Comment by snitin315** [comment]
@amareshsm That's the language page, Thanks for the catch, I'll update that as well. Here's the [version page](https://deploy-preview-16553--docs-eslint.netlify.app/versions/)

**Review by amareshsm — APPROVED** [review]
LGMT

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
