### PR TITLE
Chore: Typographic consistency and terminology fixes in documentation for `indent`

### PR DESCRIPTION
**Pull request by Trott**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Thanks for PR! LGTM
@pedrottimark Can you take a look?

**Comment by pedrottimark** [comment]
@Trott Good eyes. Thank you for contributing. Because this is a correction to documentation, can you please change the commit message to Docs. So far, Chore has been for code change that does not affect which problems that rules report.

👍 

In future case like this, you can submit a pull request without opening an issue.

**Comment by Trott** [comment]
Updated the commit message and force pushed.

**Comment by nzakas** [comment]
LGTM. Thanks @trott!

**Pull request merged**
