### PR TITLE
Fix: `block-scoped-var` issues (fixes #2253, fixes #2747)

### LINKED ISSUE #2253: `block-scoped-var` fails on deeper desctructuring
```javascript
let {PropTypes, addons: {PureRenderMixin}} = React;
let Test = React.createClass({
  mixins: [PureRenderMixin],

  // ...
});
```

```
  11:11  error  "PureRenderMixin" used outside of binding context  block-scoped-var
```

Moved out from closed issue https://github.com/eslint/eslint/issues/1863#issuecomment-89869081

### LINKED ISSUE #2747: block-scoped-var fails on mutual recursion
Simplified my case to the following code:

```javascript
function a(n) {
	return n > 0 ? b(n - 1) : "a";
}

function b(n) {
	return n > 0 ? a(n - 1) : "b";
}
```

And simplified eslintrc that allows to reproduce the issue:

```json
{
  "ecmaFeatures": {
    "blockBindings": true,
    "modules": true
  },
  "rules": {
    "no-use-before-define": 2,
    "block-scoped-var": 2
  }
}
```

Without `blockBindings` enabled, only `no-use-before-define` fails.
Turning `modules` on/off doesn't affect the result, only adds `use strict`-related check in this case.

### PR DESCRIPTION
**Pull request by mysticatea**
I remade the rule with using escope.

### CODE REVIEW

**Comment by mysticatea** [comment]
Oops, this implement is checking `let/const` also, so I will fix a bit tomorrow.

**Comment by olalonde** [comment]
:+1:

**Comment by mysticatea** [comment]
OK, ready for review.

`escope` knows relations between variables and references, so the process for this rule became simple a bit.

----

I found this rule is not emulating behaviors `no-redeclare` and `no-shadow`.
I can add the behaviors easily, so I will send a PR later.

**Comment by mysticatea** [comment]
[This](https://github.com/eslint/eslint/pull/3126/files#diff-519b9ef37335dfc6add4248702ff395cR61) test case make this rule ignore a switch block, why is that?

**Comment by michaelficarra** [comment]
Looks like a bug to me.

**Comment by nzakas** [comment]
Why is that a bug? Switch statements create a block but case statements do not.

**Comment by michaelficarra** [comment]
@nzakas There's a reference outside the switch.

**Comment by mysticatea** [comment]
Ah.... I'm sorry, I got a behavior which is same as the test case, on Chrome.
I had not known this behavior, switch statement seems to not make a block. I will study later....

image

**Comment by michaelficarra** [comment]
That also looks like a bug. Switch statements do make a block.

**Comment by mysticatea** [comment]
I found: http://www.ecma-international.org/ecma-262/6.0/#sec-switch-statement-runtime-semantics-evaluation

Yeah, switch statement should make a block.
And firefox does correctly.

image

**Comment by mysticatea** [comment]
I modified a bit for switch statement. The diff is here: https://github.com/mysticatea/eslint/commit/cc1af6c3a5e02ad0ee8595e20f94475971d2d5e0

**Comment by nzakas** [comment]
@michaelficarra ah, right you are. Thanks, completely missed that.

**Comment by mysticatea** [comment]
I added tests for #2967.

And my misunderstanding was corrected in #3158, so I removed a logic which allows multiple blocks.
The logic of this rule became simple more.

----

I have a question.

- Why does this rule report the same warnings as `no-undef`?

For example:

```
> echo "var a = b;" | node .\bin\eslint.js --stdin --no-eslintrc --rule "block-scoped-var:2, no-undef:2"

<text>
  1:10  error  "b" used outside of binding context  block-scoped-var
  1:10  error  "b" is not defined                   no-undef

✖ 2 problems (2 errors, 0 warnings)
```

I guess the warnings can be removed.
Specifically, I guess [this function](https://github.com/eslint/eslint/pull/3126/files#diff-2eae62ef882b59ec4c48073d22ddd7b6R127) can be removed.

**Comment by mysticatea** [comment]
Coverage decreased.... but `block-scoped-var` is 100%...

**Comment by gyandeeps** [comment]
this is new. I have never seen coveralls to display here.

**Comment by mysticatea** [comment]
When the tests of node `v0.12` finished lastly, it seems to decrease coverage.
It's a mystery.

**Comment by mysticatea** [comment]
I complement [my question](#issuecomment-125307709).

It needs to rewrite some tests in order to remove the duplicate warning of `no-undef`.
I want to do it, but can I do it?

**Comment by nzakas** [comment]
The function can be removed, but you should create a separate issue and pull request because it's a breaking change.

**Comment by mysticatea** [comment]
OK, thank you.

So this PR is ready for review again.

**Comment by nzakas** [comment]
LGTM

**Pull request merged**
