### PR TITLE
Build: `npm run perf` command should check the exit code

### LINKED ISSUE #5279: `npm run perf` command should check the exit code.
From #5277.

Currently `npm run perf` is ignoring error silently.
Should check the exit code.

(The following result is failed. The result of single file and multi files are the same time....)

```
C:\Users\t-nagashima.AD\Documents\GitHub\eslint [(41be483...)]> npm run perf

Loading:
  Load performance Run #1:  201.671863ms
  Load performance Run #2:  202.398129ms
  Load performance Run #3:  202.881703ms
  Load performance Run #4:  203.029312ms
  Load performance Run #5:  202.084802ms

  Load Performance median:  202.398129ms


Single File:
  CPU Speed is 3392 with multiplier 13000000
  Performance Run #1:  1448.943683ms
  Performance Run #2:  1429.113218ms
  Performance Run #3:  1444.159559ms
  Performance Run #4:  1434.09204ms
  Performance Run #5:  1453.60465ms

  Performance budget ok:  1444.159559ms (limit: 3832.5471698113206ms)


Multi Files (450 files):
  CPU Speed is 3392 with multiplier 39000000
  Performance Run #1:  1436.000377ms
  Performance Run #2:  1400.927062ms
  Performance Run #3:  1431.816343ms
  Performance Run #4:  1414.330397ms
  Performance Run #5:  1417.529775ms

  Performance budget ok:  1417.529775ms (limit: 11497.641509433963ms)
```

### PR DESCRIPTION
**Pull request by BYK**
Fixes #5279

### CODE REVIEW

**Comment by BYK** [comment]
Builds will fail until #5277 is fixed on master and this branch is rebased against it.

**Comment by BYK** [comment]
>Builds will fail until #5277 is fixed on master and this branch is rebased against it.

I stand corrected since we don't run `npm run perf` for these checks.

**Comment by nzakas** [comment]
Lgtm

**Comment by nzakas** [comment]
Oh, can you update your commit summary to begin with "Build:"?

**Comment by BYK** [comment]
@nzakas done!

**Pull request merged**
