### PR TITLE
Update: Bump inquirer to version 6

### PR DESCRIPTION
**Pull request by realityking**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[X] Other, please explain:

Bump inquirer to version 6.

Full changelog: https://github.com/SBoudrias/Inquirer.js/releases/tag/v6.0.0

The only breaking change is the update of Rx.js to v6. Since eslint doesn't directly access Rx.js, this doesn't affect eslint.

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by kaicataldo** [comment]
Thanks for the PR! What does upgrading `inquirer` buy us right now?

**Comment by realityking** [comment]
Not much except better deduplication with other tools that use it as well and are staying up to date.

In my case, the project I work on currently loads 3 inquirer versions and this would cut it down to two (and remove the divergent subdepebdencies)

**Comment by Aladdin-ADD** [comment]
there is another PR https://github.com/eslint/eslint/pull/10622, upgrade inquirer@6.1.0

**Comment by realityking** [comment]
Fixed with #10622 / 10690b7714d8a3c7d6d85a7ff75d7d793cd392ab

**Pull request closed without merging**
