### PR TITLE
Upgrade: Debug 4.0.1 > 4.3.2

### PR DESCRIPTION
**Pull request by sandeshvijayraj**
#### Prerequisites checklist

- [X ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add auto fixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ X] Other, please explain:

#### What changes did you make? (Give an overview)

The Debug libraries < 4.1.1 are considered to be vulnerable. A project having vulnerability scanners are getting blocked due to this vulnerable library inside eslint. The eslint consumer may not have a way to override sub-libraries. The fix can be done in the core repo only.

The MR just updates Debug library specified in package.json dependencies to the latest 4.3 version

#### Is there anything you'd like reviewers to focus on?

I ran the test specified in your project and seems to be fine but can still test the MR has no issues

### CODE REVIEW

**Review by mdjermanovic — COMMENTED** [review]
@sandeshvijayraj thanks for the PR!

Can you please sign our [CLA](https://cla.js.foundation/eslint/eslint?pullRequest=14892) so we could merge this?

**Comment by sandeshvijayraj** [comment]
@mdjermanovic 

I did signed it and when I open it it shows me as signed not sure why its not updating here do I have to do any more steps ??

**Comment by mdjermanovic** [comment]
It looks like you used a different email address for commits, so maybe this could help:

https://docs.github.com/en/github/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-linked-to-another-user

**Comment by sandeshvijayraj** [comment]
I did that but I think need to create a new MR here ??? As the other account commit would stay here and needs approval I guess @mdjermanovic

**Review by snitin315 — APPROVED** [review]
LGTM, thanks for contributing.

**Comment by snitin315** [comment]
Note to the merger - 

While merging make sure to remove `Co-authored-by: Sandesh.Bafna@cimpress.com <sandesh.bafna@cimpress.com>` from the commit description, as `CLA` is not signed with this email.

**Review by nzakas — APPROVED** [review]

**Comment by nzakas** [comment]
Thanks @snitin315

**Pull request merged**
