### PR TITLE
Docs: Access parseInt property correctly

### PR DESCRIPTION
**Pull request by canac**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Fixed documentation of the `prefer-numeric-literals` rule to correctly access `a`'s `parseInt` property.

### CODE REVIEW

**Comment by platinumazure** [comment]
The "incorrect" way of calling `parseInt` is intentional.

The goal of the rule is to avoid calls to `parseInt` (for certain bases) and recommend the use of appropriate literal syntax instead. In that section, we demonstrate that calling the computed property will not result in a lint warning, because it is not the same as calling the actual `parseInt` method.

It's not very valuable documentation, I'll admit, but it is correct as is.

**Comment by canac** [comment]
@platinumazure Ah, gotcha. Thanks for explaining.

**Comment by platinumazure** [comment]
@canac No worries, thanks for taking the time to contribute!

**Comment by canac** [comment]
@platinumazure You're welcome, and thanks for a great first-time-contributor experience!

**Pull request closed without merging**
