### PR TITLE
Docs: update global require documentation to match new eslint-disable-next-line syntax

### PR DESCRIPTION
**Pull request by akirilyuk**
Update documentation to match newest version

**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Updated documentation for disable next line of global require since the current syntax is not working

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Hi, thanks for the PR!

`eslint-disable-line` is still supposed to work. Could clarify what you mean by "the current syntax is not working"?

**Comment by akirilyuk** [comment]
Hi, see the attached screenshot. If I am using 

> // eslint-disable-line global-require

 instead of 

> // eslint-disable-next-line gloabl-require

 an error is trown if I runt linter:

screen shot 2019-03-01 at 11 20 21
screen shot 2019-03-01 at 11 20 28

tested wit the following setup:

"eslint": "^5.14.1",
"eslint-config-airbnb-base": "^13.1.0",
"eslint-config-prettier": "^4.1.0",
"eslint-plugin-import": "^2.15.0",
"eslint-plugin-jest": "^22.3.0",
"eslint-plugin-prettier": "^3.0.1",

**Comment by not-an-aardvark** [comment]
`// eslint-disable-line` disables the rule on the line containing the comment. `// eslint-disable-next-line` disables the rule on the line after the comment.

To make `// eslint-disable-line` work, you should put the comment on the same line you want to disable:

```js
const logger = require('../../../src/utils/logger'); // eslint-disable-line global-require
```

**Comment by akirilyuk** [comment]
Oh, okay, I didn't know that, well thank you then. I will close the PR.

**Pull request closed without merging**
