### PR TITLE
Fix: Use default assertion messages for rule tester messages

### PR DESCRIPTION
**Pull request by dmitriiabramov**
Fixes https://github.com/eslint/eslint/issues/6532

### CODE REVIEW

**Comment by ilyavolodin** [comment]
I wonder if we want to do the same for everything (type, line, column, etc.)

**Comment by platinumazure** [comment]
Hmm. This might just need a force-push to restart the Travis build.

I agree with @ilyavolodin about removing messages from all assertions, if feasible.

**Comment by dmitriiabramov** [comment]
yeah. i'll update the PR

**Comment by nzakas** [comment]
Let's not expand the scope of this PR further than it was originally intended.

@ilyavolodin if you want to propose other changes, please open a separate issue as I have concerns about removing the message for other assertions.

**Comment by ilyavolodin** [comment]
@nzakas Ok, sounds good. Should we merge this in as is than?

**Comment by nzakas** [comment]
Yeah. I just realized the Travis failure was the Node 6 thing we already fixed. LGTM.

**Pull request merged**
