### PR TITLE
Fix: prefer-destructuring says "Use destructuring" on "super" (#9625)

### LINKED ISSUE #9625: prefer-destructuring says "Use destructuring" on "super"
**Tell us about your environment**

* **ESLint Version: 4.11.0**
* **Node Version: v9.2.0**
* **npm Version: 5.5.1**

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
<details>
<summary>Configuration</summary>

```js
const config = {
    parserOptions: {
        ecmaVersion: 6,
    },
    rules: {
        'prefer-destructuring': ['warn'],
    },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// eslint-test.js
const code = `
class Node {
    static get inheritance() {
        return ['node'];
    }
}
class Element extends Node {
    static get inheritance() {
        const inheritance = super.inheritance;
        inheritance.push('element');
        return inheritance;
    }
}
console.log(Element.inheritance);
`;
const {Linter} = require('eslint');
const linter = new Linter();
const config = {
    parserOptions: {
        ecmaVersion: 6,
    },
    rules: {
        'prefer-destructuring': ['warn'],
    },
};
const messages = linter.verify(code, config);
for (const message of messages) {
    console.log(message);
}
```

```bash
node ./eslint-test.js
```

**What did you expect to happen?**
I expect `prefer-destructuring` ignores the `const inheritance = super.inheritance;` statement.
`const {inheritance} = super` throws a SyntaxError.

**What actually happened? Please include the actual, raw output from ESLint.**
```
{ ruleId: 'prefer-destructuring',
  severity: 1,
  message: 'Use object destructuring.',
  line: 9,
  column: 15,
  nodeType: 'VariableDeclarator',
  source: '        const inheritance = super.inheritance;',
  endLine: 9,
  endColumn: 40 }
```

### PR DESCRIPTION
**Pull request by kei-ito**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

This fixes #9625 

**What changes did you make? (Give an overview)**
- `tests/lib/rules/prefer-destructuring.js`: I added a test to reproduce #9625 
- `lib/rules/prefer-destructuring.js`: I updated a line to fix #9625 

**Is there anything you'd like reviewers to focus on?**
No

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
I agree that it would be nice to have a test. Having said that, I think the implementation in this PR already handles that case correctly by reporting an error because `const {bar} = super.foo` is legal.

Conceptually, the rule should report an error only when `node.object` is a valid expression on its own. So I think checking the type of `node.object` is correct here, regardless of whether `node.object` is another `MemberExpression` or contains `super`.

**Comment by platinumazure** [comment]
Thanks for the explanation. You are right that I had misunderstood conceptually how this rule is supposed to work and thought that `const { bar } = super.foo;` was invalid syntax, when in reality it is valid. Thanks!

**Comment by kei-ito** [comment]
Thank you for the reviewing. I added another test to check what @platinumazure pointed out.
I found that I can omit `get` and the simplest test reproducing #9625 is
```javascript
class Foo extends Bar {
  foo() {
    var foo = super.foo;
  }
}
```

**Comment by not-an-aardvark** [comment]
Thanks for contributing!

**Pull request merged**
