### PR TITLE
Chore: Mark SourceCode getComments() method as deprecated (fixes #13293)

### LINKED ISSUE #13293: SourceCode not optimize for RuleTester changes
**Tell us about your environment**

* **ESLint Version: 7**

**What parser (default, Babel-ESLint, etc.) are you using?**

1. babel-eslint
2. @typescript-eslint/parser

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

We using RuleTester for custom rule, and have this code inside rule:

```js
// context: Rule.RuleContext
const sourceCode = context.getSourceCode();
const comments = sourceCode.getComments(nodeSource).leading;
```

After updating to Eslint 7, have a error, because `source-code.js` use deprecated by `rule-tester.js` node properties.

**What did you expect to happen?**

My tests passes succesfull

**What actually happened? Please include the actual, raw output from ESLint.**

```bash
Use token.range[0] instead of token.start
    Occurred while linting <input>:3

      68 |       const chunkName = last(propName.split('/'));
      69 |       const sourceCode = context.getSourceCode();
    > 70 |       const comments = sourceCode.getComments(nodeSource).leading;
         |                                   ^
      71 | 
      72 |       if (!comments || comments.length === 0) {
      73 |         return context.report({

      at Object.get (node_modules/eslint/lib/rule-tester/rule-tester.js:223:23)
      at SourceCode.getComments (node_modules/eslint/lib/source-code/source-code.js:352:50)
      at checkImport (packages/eslint/src/config/rules/bundle-chunk-name.ts:70:35)
      at ImportExpression (packages/eslint/src/config/rules/bundle-chunk-name.ts:134:16)
      at listeners.(anonymous function).forEach.listener (node_modules/eslint/lib/linter/safe-emitter.js:45:58)
          at Array.forEach (<anonymous>)
      at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
      at NodeEventGenerator.applySelector (node_modules/eslint/lib/linter/node-event-generator.js:254:26)
      at NodeEventGenerator.applySelectors (node_modules/eslint/lib/linter/node-event-generator.js:283:22)
      at NodeEventGenerator.enterNode (node_modules/eslint/lib/linter/node-event-generator.js:297:14)
```

**Are you willing to submit a pull request to fix this bug?**

Yes

### PR DESCRIPTION
**Pull request by SuperOleg39**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [x] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Update source-code.js `getComments` method:

Program node [exclude leading and trailing comments from our range](https://github.com/eslint/espree/blob/master/lib/espree.js#L156), and i add special conditions, when given node has parent Program, leading and trailing comments tokens always belong to this node

### CODE REVIEW

**Comment by SuperOleg39** [comment]
> Given that `SouceCode#getComments()` is [deprecated](https://eslint.org/docs/developer-guide/working-with-rules#deprecated), we won't be accepting any more PRs to change the behavior. A PR updating the JSDoc block to include an `@deprecated` tag would be welcome, though!

Thank you, update PR!

**Comment by SuperOleg39** [comment]
Done!

**Comment by SuperOleg39** [comment]
☺️

**Comment by kaicataldo** [comment]
LGTM, thank you!

**Pull request merged**
