### PR TITLE
Chore: use eslint-plugin-local instead of --rulesdir for self-linting

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Other, please explain:

**What changes did you make? (Give an overview)**

This updates our internal linting build to use `eslint-plugin-local` rather than the `--rulesdir` CLI flag.

We've been talking about deprecating `rulesdir` for awhile, so I think it would be good for us to dogfood some of the alternatives for using project-specific linting rules.

https://github.com/eslint/eslint/pull/9164 is another way of solving the same problem. This PR is mutually exclusive with https://github.com/eslint/eslint/pull/9164.

**Is there anything you'd like reviewers to focus on?**

We should choose between this approach and the approach in https://github.com/eslint/eslint/pull/9164. Which do you prefer?

### CODE REVIEW

**Comment by gyandeeps** [comment]
Can we move `.eslintplugin.js` file to folder rather than polluting the base folder with so many files?

**Comment by not-an-aardvark** [comment]
No. `eslint-plugin-local` just consists of `module.exports = require('../../.eslintplugin')`, so with this solution we need to have `.eslintplugin.js` in the root directory.

**Comment by not-an-aardvark** [comment]
@eslint/eslint-team Any thoughts on this PR or https://github.com/eslint/eslint/pull/9163? I think we should accept one of them -- they would make it easier for new contributors (since editor integrations wouldn't report issues from `--rulesdir`), and they would help us dogfood the recommended approaches for project-specific linting rules.

**Comment by Aladdin-ADD** [comment]
I'm slightly prefer that one (#9163),  as `.eslintplugin.js` file in the root dir in this PR.

**Comment by not-an-aardvark** [comment]
> I'm slightly prefer that one (#9163)

Did you mean to link to #9164 instead of #9163? #9163 is this PR.

**Comment by Aladdin-ADD** [comment]
(⌒▽⌒)

**Comment by not-an-aardvark** [comment]
Closing because https://github.com/eslint/eslint/pull/9164 was merged.

**Pull request closed without merging**
