### PR TITLE
Update: Add class support to `require-jsdoc` rule (fixes #4268)

### LINKED ISSUE #4268: require-jsdoc for ES6 class methods [$10]
The `require-jsdoc` rule only supports `FunctionDeclaration` node type. It would be nice to have support for ES6 class methods and maybe constructors.

<bountysource-plugin>
---
There is a **[$10 open bounty](https://www.bountysource.com/issues/27719739-require-jsdoc-for-es6-class-methods?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by nzakas** [comment]
We probably need to add some options to this rule so people can opt-out if they just want to require JSDoc for one or two types of things. What do you think?

**Comment by gyandeeps** [comment]
I dont know if we need it right now as very few people would use `classes` and whoever uses would need docs. But later we can always add options to opt-out.

**Comment by nzakas** [comment]
We don't know that very few people are using classes. We also don't know that if people are using them, that they necessarily want to require JSDoc for them. I think it's safer to add the option now because this is a big change in this rule's responsibility.

**Comment by gyandeeps** [comment]
Alright lets do it, let discuss the option names.
I am thinking, 
```js
{
    "require": {
        "classes": false,
        "functions": true
    }
}
```

This would be default.

I think we want to be specific here saying `FunctionDeclaration` or `ClassDeclaration` because we dont apply this to expressions as of now.

**Comment by nzakas** [comment]
Yeah, I'd use the Node names.

**Comment by dweidenfeld** [comment]
+1

**Comment by gyandeeps** [comment]
@nzakas Do we need an option for class methods separately or its should go with class only. Like if we have `ClassDeclaration` to true then it will also check for jsdoc on class methods.

**Comment by nzakas** [comment]
We probably want to have a separate setting for MethodDefinition.

**Comment by nzakas** [comment]
LGTM

**Pull request merged**
