### PR TITLE
Fix: Crash in `constructor-super`

### LINKED ISSUE #5319: Crash in `constructor-super`
**The version of ESLint you are using (run eslint -v)**

```
$ ./node_modules/.bin/eslint -v
v2.1.0
```

**The source code that caused the problem**
```js
class Foo extends Object {
  constructor(method) {
    super();
    this.method = method || function() {};
  }
}
```

**The configuration you're using (for the rule or your entire config file)**
```yaml
env:
  es6: true
rules:
  constructor-super: 2
```

**The actual ESLint output complete with line numbers**
```
$ ./node_modules/.bin/eslint foo.js
/private/tmp/test/node_modules/eslint/lib/rules/constructor-super.js:69
        return segInfoMap[segment.id].calledInEveryPaths;
                                     ^

TypeError: Cannot read property 'calledInEveryPaths' of undefined
    at isCalledInEveryPath (/private/tmp/test/node_modules/eslint/lib/rules/constructor-super.js:69:38)
    at Array.every (native)
    at EventEmitter.onCodePathSegmentStart (/private/tmp/test/node_modules/eslint/lib/rules/constructor-super.js:156:56)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at forwardCurrentToHead (/private/tmp/test/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:176:34)
    at processCodePathToExit (/private/tmp/test/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:506:9)
    at CodePathAnalyzer.leaveNode (/private/tmp/test/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:9)
    at CommentEventGenerator.leaveNode (/private/tmp/test/node_modules/eslint/lib/util/comment-event-generator.js:111:23)
    at Controller.controller.traverse.leave (/private/tmp/test/node_modules/eslint/lib/eslint.js:839:36)
```

### PR DESCRIPTION
**Pull request by BYK**
Fixes #5319.

@mysticatea - I'm not sure whether what I did makes sense or not so feel free to guide me. Apparently I'm not great at understanding code path analysis :)

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you very much!

The cause of this bug seems to be https://github.com/eslint/eslint/blob/master/lib/rules/constructor-super.js#L142

This code is comparing the current scope in order to check whether this is a code path segment on the current constructor or not, . But on `FunctionExpression`, `context.getScope()` is returning the scope of the nested function.
Due to that, information of one segment in the constructor was not initialized.

I guess, this error is happened only when the first node of a code path segment is a `FunctionExpression`.

I'm investigating a way to fix...

**Comment by BYK** [comment]
>The cause of this bug seems to be https://github.com/eslint/eslint/blob/master/lib/rules/constructor-super.js#L142

I'm not very sure of that since when I checked `funcInfo` was `null` and the segment was skipped altogether. I may be wrong though. Anyways, feel free to take over the branch :)

**Comment by mysticatea** [comment]
Thank you. I will do.

(I'm almost sure `no-this-before-super` rule has the same problem...)

**Comment by mysticatea** [comment]
image

I updated this PR.
Diff: https://github.com/eslint/eslint/pull/5321/files?w=1

**Comment by mysticatea** [comment]
I made information of code path segments being created correctly even if the first node of the segment is a function node.

**Comment by BYK** [comment]
Nice visualization, thanks! I'm also glad you've found a better solution. Great work!

**Pull request merged**
