### PR TITLE
Update: Uniform messages for the rules in "complexity" section

### PR DESCRIPTION
**Pull request by IgorNovozhilov**
**What is the purpose of this pull request? (put an "X" next to item)**

- [x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))

**What rule do you want to change?**

It is proposed to unify the content of messages from the category "[complexity](https://eslint.org/docs/rules/complexity)". And make them more informative.

**Does this change cause the rule to produce more or fewer warnings?**

no changed

**How will the change be implemented? (New option, new default behavior, etc.)?**

- Changing the message template in `exports.meta.messages`
- Changing `data` in a `context.report` method call

**Please provide some example code that this change will affect:**

```js
function test(a) {
  // Comment qwerty qwerty qwerty qwerty
  if (a) {
    if (a) {
      console.log('qwerty');
    }
    a(function() {
      onsole.log('qwerty qwerty');
    })
    a++;a++;a++
    if (a) a(); else a();
  }
}
 
test(a);test(a);

class a {
  
}

class b {
  
}
```

*rules config*
```json
  "rules": {
    "complexity": ["warn", 1],
    "max-depth": ["warn", 1],
    "max-len": ["warn", { "code": 30, "comments": 36 }],
    "max-lines": ["warn", 7],
    "max-lines-per-function": ["warn", 5],
    "max-nested-callbacks": ["warn", 0],
    "max-params": ["warn", 0],
    "max-statements": ["warn", 2],
    "max-statements-per-line": ["warn", { "max": 1 }],
    "max-classes-per-file": ["warn", 1]
  }
```

**What does the rule currently do for this code?**

изображение

**What will the rule do after it's changed?**

изображение

**What changes did you make? (Give an overview)**

*complexity*, *max-depth*
- Added maximum allowed rule value

*max-len*, *max-classes-per-file*
- Added actually rule value 

*max-lines*, *max-lines-per-function*
- Uniforming a rule message

**Is there anything you'd like reviewers to focus on?**

Also I want to change the messages for the rules: *max-classes-per-file*, *max-statements-per-line*, and possibly other similar rules that use numeric metrics. Are there any other such rules?

### CODE REVIEW

**Comment by IgorNovozhilov** [comment]
**max-statements-per-line**
before
изображение

after
изображение

**Comment by platinumazure** [comment]
Hmm. Do we need to mention the line number in the error messages? All ESLint messages already have a starting line and column associated with them.

**Comment by IgorNovozhilov** [comment]
@platinumazure, Half of the rules had a line number. So I decided to leave it.
Although I, too, think that he glee. I propose to replace with `This line`. Ok?

**Comment by ilyavolodin** [comment]
I'm 👍 for this change. Unifying messages across multiple rules should make it easier to read results of linting a file.

**Pull request closed without merging**
