### PR TITLE
Fix: `comma-dangle` with `"always"`/`"always-multiline"` false positive after a rest element

### LINKED ISSUE #3627: comma-dangle = always-multiline and the spread operator
There is a bit of an issue with `comma-dangle` set to `"always-multiline"` and the spread operator used in a destructuring assignment:

```
var [
  x,
  y,
  ...data // Getting "missing trailing comma" error
] = parsed;
```

For compliance with [spec](http://www.ecma-international.org/ecma-262/6.0/#sec-destructuring-assignment) there should be no comma after the `AssignmentRestElement` and I think that `"always-multiline"` should treat this as a special case and ignore the missing trailing comma.

For now I'm ignoring the error for this line.

The version I have is 1.2.1.

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #3627.

I refactored this rule for simple flow.

### CODE REVIEW

**Comment by nzakas** [comment]
Can you rebase?

**Comment by mysticatea** [comment]
Sure, I rebased.

And I modified comments in `isTrailingCommaAllowed` function a bit.

**Comment by ilyavolodin** [comment]
Need another rebase. Something strange is going on with Github today

**Comment by mysticatea** [comment]
I rebased again :)

**Pull request merged**
