### PR TITLE
Update: space-infix-ops reports violating operator

### PR DESCRIPTION
**Pull request by madbence**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What rule do you want to change?**

`space-infix-ops`

**Does this change cause the rule to produce more or fewer warnings?**

no change

**How will the change be implemented? (New option, new default behavior, etc.)?**

change the error message to include the violating operator

**Please provide some example code that this change will affect:**

```js
var foo=1;
```

**What does the rule currently do for this code?**

reports `Infix operators must be spaced.`.

**What will the rule do after it's changed?**

reports `Operator '=' must be spaced.`.

**What changes did you make? (Give an overview)**

Clarify which operator violated the rule (on a longer line with many operators this can be confusing)

**Is there anything you'd like reviewers to focus on?**

`?` or `:` are not really an operators on their own, but i guess that's not a big deal.

### CODE REVIEW

**Comment by platinumazure** [comment]
I like the idea. I will champion this proposal with the team. Thanks for contributing!

**Comment by madbence** [comment]
@platinumazure any progress with this?

**Comment by platinumazure** [comment]
@madbence Thanks for following up, I lost track of this.

I'm trying to find one more :+1: from the team. I'll see if I can get that done today.

**Comment by platinumazure** [comment]
Hi @madbence, apologies for letting this slip through the cracks.

I've restarted the Travis build to make sure this still passes on the latest master. I assume it will; if it does, I'll merge this tonight. Thanks!

**Pull request merged**
