### PR TITLE
Docs: Improve options description in `no-redeclare`

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by pedrottimark** [comment]
@alberto So to make sure I understand: when we sweep through the rule docs again in the coming weeks, we need to add examples of **incorrect** code for this rule with the default `"builtinGlobals": false` option? Declare global variables via `/*global */` comment and redeclare them? Probably example of both third-party library like jQuery and also something that sounds app-specific?

**Comment by alberto** [comment]
Setting `"builtinGlobals": false` has the same effect as passing no options.

**Comment by pedrottimark** [comment]
Yes, indeed. To match the improvement to the wording, we can show example code for redeclaration of non-built-in global variable?

**Comment by alberto** [comment]
@pedrottimark Hold on, I totally misunderstood what the rule was doing. Let me fix it.

**Comment by alberto** [comment]
PR updated

**Comment by pedrottimark** [comment]
Nice, now I understand too 😀 and just linted a little example code to make sure.

**Comment by pedrottimark** [comment]
LGTM, thank you

**Comment by alberto** [comment]
@pedrottimark Thank you for reviewing it!

**Pull request merged**
