### PR TITLE
Fix grammar in “there’s nothing prevent you”

### PR DESCRIPTION
**Pull request by PoziWorld**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update

**What changes did you make? (Give an overview)**
Changed
“For example, there’s nothing prevent you from writing:”
to
“For example, there’s nothing preventing you from writing:”

**Is there anything you'd like reviewers to focus on?**
No.

### CODE REVIEW

**Comment by g-plane** [comment]
Hi @PoziWorld , thanks for contributing! Can you update your commit message to follow our guideline?

**Comment by PoziWorld** [comment]
@g-plane,

I made another pull request per the guideline, but it still fails.

Does it fail because the commit message doesn't mention the issue number?
What if there is no related issue?

**Comment by g-plane** [comment]
Please read this: https://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changes

**Comment by g-plane** [comment]
@PoziWorld Here's an example: https://github.com/eslint/eslint/pull/11387

**Comment by not-an-aardvark** [comment]
Thanks for contributing! I fixed the commit message when I merged the PR.

For future reference, I think the issue was that the commit message needs to start with a prefix, such as `Docs: Fix grammar in “there’s nothing prevent you”`.

**Pull request merged**
