### PR TITLE
[WIP] Fix: Ignore warning when file in linked folder

### LINKED ISSUE #3720: Ignore warning when file in linked folder
I have a linked folder in project. 

```
~/Projects/ttt tree -f
.
├── ./1.js
├── ./bzzz -> ../LINKED
└── ./xxx
    └── ./xxx/3.js

2 directories, 2 files
```

So, when I lint file in linked dir, I get an ignore warning

```
~/Projects/ttt eslint bzzz/2.js                
  eslint:cli Running on files +0ms
  eslint:cli-engine Processing /Users/roadhump/Projects/LINKED/2.js +5ms
  eslint:cli-engine Linting /Users/roadhump/Projects/LINKED/2.js +12ms
  eslint:config Constructing config for /Users/roadhump/Projects/LINKED/2.js +1ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Merging command line environment settings +1ms
  eslint:cli-engine Linting complete in: 28ms +12ms

/Users/roadhump/Projects/ttt/bzzz/2.js
  0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override

✖ 1 problem (0 errors, 1 warning)

```

and if I run on folder, file is silently excluded

```
~/Projects/ttt eslint .
  eslint:cli Running on files +0ms
  eslint:cli-engine Processing /Users/roadhump/Projects/LINKED/2.js +101ms
  eslint:cli-engine Linting /Users/roadhump/Projects/LINKED/2.js +17ms
  eslint:config Constructing config for /Users/roadhump/Projects/LINKED/2.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Merging command line environment settings +2ms
  eslint:cli-engine Processing /Users/roadhump/Projects/ttt/1.js +12ms
  eslint:cli-engine Linting /Users/roadhump/Projects/ttt/1.js +14ms
  eslint:config Constructing config for /Users/roadhump/Projects/ttt/1.js +0ms
  eslint:config Using .eslintrc and package.json files +1ms
  eslint:config Loading /Users/roadhump/Projects/ttt/.eslintrc +0ms
  eslint:config Using /Users/roadhump/Projects/ttt/.eslintrc +22ms
  eslint:config Merging command line environment settings +0ms
  eslint:cli-engine Processing /Users/roadhump/Projects/ttt/xxx/3.js +12ms
  eslint:cli-engine Linting /Users/roadhump/Projects/ttt/xxx/3.js +12ms
  eslint:config Constructing config for /Users/roadhump/Projects/ttt/xxx/3.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/roadhump/Projects/ttt/.eslintrc +0ms
  eslint:config Using /Users/roadhump/Projects/ttt/.eslintrc +1ms
  eslint:config Merging command line environment settings +0ms
  eslint:cli-engine Linting complete in: 192ms +2ms

/Users/roadhump/Projects/ttt/1.js
  1:9  error  Strings must use doublequote  quotes

/Users/roadhump/Projects/ttt/xxx/3.js
  1:9  error  Strings must use doublequote  quotes

✖ 2 problems (2 errors, 0 warnings)


```

I think it would be nice if there were no difference between linked and real folders

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26588806-ignore-warning-when-file-in-linked-folder?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BYK**
Fixes #3720

### CODE REVIEW

**Comment by gyandeeps** [comment]
Can we also upgrade `glob` to 6.0 with this pr?

**Comment by BYK** [comment]
>Can we also upgrade glob to 6.0 with this pr?

I can but not sure if this branch actually fixes the problem.

**Comment by nzakas** [comment]
@byk do you want to pursue this further? If not, it's probably best to close this PR.

**Comment by BYK** [comment]
I'll close the PR since it's been too long and things around this have changed. If the issue still exists, I'll try again from scratch.

**Pull request closed without merging**
