### PR TITLE
Docs: incorrect syntax in the example for rule «one-var»

### PR DESCRIPTION
**Pull request by albburtsev**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Can you prefix your pull request with "Docs:" please, as per our requirements: http://eslint.org/docs/developer-guide/contributing#step-2-make-your-changes

**Comment by albburtsev** [comment]
Done.

**Comment by IanVS** [comment]
Hi @albburtsev, you've changed the name of the pull request, but in fact the name of the commit itself needs to be changed.  Do you know how to do that (with `git rebase -i HEAD~1`)?

Also, can you please sign our [Contributor License Agreement](http://eslint.org/cla/)?

**Comment by albburtsev** [comment]
Done. I accepted LA and renamed the commit.
Sorry for skipping of this rules.

**Comment by IanVS** [comment]
No need to apologize.  Thanks for contributing!

**Pull request merged**
