### PR TITLE
Docs: multiline-comment valid block separate-lines

### PR DESCRIPTION
**Pull request by gpiress**

### CODE REVIEW

**Comment by gpiress** [comment]
@Aladdin-ADD The PR with the docs change.

To be honest, I'm having a hard time understanding why the block comment is valid in this case. What your earlier issue stats is more aligned with the behavior that would be expected, I believe.

**Comment by Aladdin-ADD** [comment]
currently, the rule does not apply unsafe autofix, e.g.
```js
// The following line comment
// contains '*/'.
```
cannot be fixed to:
```js
/* The following line comment
 * contains '*/'.*/
```
maybe it is worthy to add a section to clarify these exceptions, instead of adding it to the normal examples.


> What your earlier issue stats is more aligned with the behavior that would be expected,

that issue was a bug report (I found the "separate" option autofix didn't consider some edge cases), you can open a new proposal issue (which is an enhancement).

**Comment by kaicataldo** [comment]
@gpiress Please fill out the PR template provided. It helps us understand the intention of the PR. Thank you.

**Comment by ilyavolodin** [comment]
Closing this PR due to the lack of response from the author. We always appropriate time people put into improving ESLint, but we need to follow certain rules to make sure what we are merging makes sense.

**Pull request closed without merging**
