### PR TITLE
Update: add fixer for new-parens (fixes #6994)

### LINKED ISSUE #6994: Add a --fix option for new-parens
I'm using Node v6.4.0 and ESLint v3.4.0.

It would be useful to have an autofix option for the `new-parens` rule. The fixer would simply add `()` to all places where the rule reports an error.

```js
var x = new Foo;
var y = new foo.Bar;
var z = (new Foo).bar;

// gets corrected to:

var x = new Foo();
var y = new foo.Bar();
var z = (new Foo()).bar;
```

I would be willing to add this if the issue is accepted.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What issue does this pull request address?**

#6994

**What changes did you make? (Give an overview)**

This adds a --fix option for `new-parens`, as described in #6994.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

~~#6994 has not been accepted yet (needs one more 👍), so this should not be merged yet.~~ (edit: #6994 is accepted now.)

### CODE REVIEW

**Comment by platinumazure** [comment]
Oops, I've been slacking as champion. :smile: I'll see if I can get the issue accepted today.

**Comment by kaicataldo** [comment]
LGTM

**Comment by platinumazure** [comment]
LGTM. @kaicataldo Up to you if you want to merge or solicit further review.

**Comment by kaicataldo** [comment]
Thanks for contributing to ESLint!

**Pull request merged**
