### PR TITLE
Update README.md with a workaround for #10618

### PR DESCRIPTION
**Pull request by joaotavora**
#### Prerequisites checklist

- [ ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Added a question to the faq answering some of problems in #10618, which I've recently come across myself.  I just need a bit of linting for some javascript and don't want a big node.js setup.  I figured providing people with a way to make a quick `.eslintrc` would be a good idea.  Even better would be for Eslint to have that thing called defaults and work out of the box.

#### Is there anything you'd like reviewers to focus on?

Not really.  I'm just making this for my own reference and trying my luck at helping others with the same problem I had.

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks for the suggestion. This question hasn't come up frequently enough to put it on the README, but it might make sense in the getting started guide: https://github.com/eslint/eslint/blob/master/docs/user-guide/getting-started.md

**Comment by joaotavora** [comment]
I admit I didn't read this guide.  I just read the README to install eslint, which went OK, and then when `eslint --init` failed I went straight to Google to getting it to work.  Like me, I suspect thousands will, and either be frustrated or invest in some frameworkey setup.

Actually, if eslint works with an even smaller `.eslintrc` file, just mention that in the README.  You should advise, but not force people to use `eslint --init`.  First give them something working, then leave that fine-tuning for later. My two cents, but you can move my contribution anywhere you want.

Thanks for eslint, it's working nicely.

**Comment by nzakas** [comment]
Just to close the loop on this, we don't force anyone to use `--init`. You can always set up a config file manually, but for people just starting out, doing so is often overwhelming. There are some rough edges we can probably still work on, though.

**Comment by joaotavora** [comment]
> You can always set up a config file manually, but for people just starting out, doing so is often overwhelming. 

But if you really care about that, then just make configless `eslint` infer reasonable defaults. A lot of applications do this.

Remember that the problem here is that `--init` does force you to have a `package.json`, and I found it exactly that: overwhelming and frankly, just sill, given that it's totally unrequired for `eslint` to work reasonably well.

**Pull request closed without merging**
