### PR TITLE
Chore: use meta.messages in some rules (2/4) (refs #9870)

### PR DESCRIPTION
**Pull request by aladdin-add**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

**What changes did you make? (Give an overview)**
use messages in some rules, to help to support the localization of error messages.
- [x] 1/4 #10764
- [x] 2/4 #10773 

**Is there anything you'd like reviewers to focus on?**

I plan to separate it to 4 PRs. temporally disabled the rule, and will enable it when all the changes finished.

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Trying again, it seems like Appveyor has two separate OAuth apps ("Appveyor" and "Appveyor CI").

**Comment by platinumazure** [comment]
Hi @Aladdin-ADD, what are the next steps here?

As an aside, would it be possible to edit the initial post to fill out the PR template? That way we can get some context when reviewing. 😄 Thanks!

**Comment by Aladdin-ADD** [comment]
@platinumazure it was ready to be reviewed. I will finish the remaining work in a few days.

**Comment by nzakas** [comment]
@not-an-aardvark @aladdin-add are you both still working on this?

**Comment by aladdin-add** [comment]
I've updated and rebased, could you please take another look at the commit https://github.com/eslint/eslint/commit/57805385f41064c6c3b965edf44f0444c5457721 ? 😄

**Comment by kaicataldo** [comment]
Thanks for contributing to ESLint!

**Pull request merged**
