### PR TITLE
Docs: Clearer plugin rule configuration (fixes #2022)

### LINKED ISSUE #2022: Documentation lacking for plugin rules configuration
Currently, documentation doesn't include anything about configuring rules that came from plugins, only how to include plugins themselves. Documentation for including plugins states that you can either use plugin name or prefix with plugin name. So "eslint-plugin-test" and just "test" will do the same. Since no documentation is provided for setting plugin's rules, one can easily assume that the same rules apply for "rules" part of configuration, however, that's not true. Only plugin name (without prefix) can be used. So the following rules section will not do anything:

```json
"rules": {
  "eslint-plugin-test/somerule": 2
}
```
P.S. Was this intentional? Not missing documentation, but functionality? This feels like an oversight. cc @lo1tuma 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9541422-documentation-lacking-for-plugin-rules-configuration?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
I think the original issue was for clarification that you can't use full plugin name inside rules object. As in instead of using `eslint-plugin-blah` you __have__ to use just `blah`

**Comment by nzakas** [comment]
Oh really? I didn't realize we were doing that. I'll update.

**Comment by nzakas** [comment]
Ok, updated

**Comment by ilyavolodin** [comment]
Nice! Thanks. I didn't realize that either until @btmills explained it in original issue.

**Pull request merged**
