### PR TITLE
Make sort-keys fixable (fixes #7714) [WIP]

### LINKED ISSUE #7714: Make sort-keys rule fixable
[sort-keys](http://eslint.org/docs/rules/sort-keys) is a laborious style requirement when applied on a large code base. Fixing these errors by hand is time consuming and error prone, esp. with nested objects.

### PR DESCRIPTION
**Pull request by gajus**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[X] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Made sort-keys fixable.

**Is there anything you'd like reviewers to focus on?**

The current implementation does not respect indentation.

### CODE REVIEW

**Comment by gajus** [comment]
Sorting properties was easy. However, I need to make the fixer respect the original indentation.

**Comment by gajus** [comment]
For the record, this is not ready to merge. I have ran the code on a large code base and found some edge cases.

Waiting for the outcome of https://github.com/eslint/eslint/issues/7714 before proceeding with a fix.

**Comment by alberto** [comment]
Thanks for your contribution. Unfortunately, I'm closing this PR since it doesn't fit the team vision.

**Comment by TSMMark** [comment]
@gajus Would you consider releasing a standalone package for a version of this rule that will autofix sort keys?

**Comment by gajus** [comment]
Sorry, overloaded with work and no time for new open-source projects.

Ping me if you do get to doing it, though. Would definitely use it.

**Comment by TSMMark** [comment]
@gajus I wouldn't mind putting it together. You mentioned in [another thread](https://github.com/eslint/eslint/issues/7714#issuecomment-265543495) that you were already using this, or a version of it, for personal use. Is this code the version that you ended up using? Do you have the latest version from your personal use? Or do you have more information on the [edge cases](https://github.com/eslint/eslint/pull/7715#issuecomment-265555818) you found?

**Comment by gajus** [comment]
This was the version of code I was using, but I have stopped because it contained some bugs. What bugs, I cannot recall after this time. I just remember that I was too busy at the time to fix it.

**Comment by TSMMark** [comment]
That's too bad, sounds like a little more time than I am able to put in at the moment. Thanks anyway!

**Comment by jedwards1211** [comment]
@alberto what is the team vision -- is it written down anywhere?

**Comment by not-an-aardvark** [comment]
I don't think there is a definitive document for the "team vision", but the decision to not accept this particular PR was discussed in https://github.com/eslint/eslint/issues/7714.

**Pull request closed without merging**
