### PR TITLE
feat: add `name` to eslint configs

### PR DESCRIPTION
**Pull request by aladdin-add**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ x] Other, please explain:

#### What changes did you make? (Give an overview)
added name to config, per https://eslint.org/docs/head/use/configure/configuration-files#configuration-naming-conventions
#### Is there anything you'd like reviewers to focus on?

suggestions for the naming?

### CODE REVIEW

**Comment by mdjermanovic** [comment]
Looks like there are merge conflicts in `packages/eslint-config-eslint/base.js` now.

**Review by nzakas — APPROVED** [review]
LGTM. Would like another review before merging.

**Comment by mdjermanovic** [comment]
There's a merge conflict in `tests/lib/cli.js` now.

**Review by fasttime — APPROVED** [review]
LGTM, thanks!

**Comment by fasttime** [comment]
Part of the changes in this PR have been reverted in #18368 because they were causing some unit tests to fail. The tests started to fail only after upgrading the @eslint/js dependency in eslint's package.json.

**Pull request merged**
