### PR TITLE
fix!: Update ajv options to align with aims for behaviour

### PR DESCRIPTION
**Pull request by matwilko**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Updated the `ajv` options used to more closely align with the aims of rule option validation:

Added `allErrors: true` because [`RuleValidator.validate`](https://github.com/eslint/eslint/blob/b79b6fb64473969b426d086b484d2e29594a5e9a/lib/config/rule-validator.js#L147) seems to have been written to handle multiple validation errors, but by default, `ajv` will only return the _first_ validation error. Seems like better UX to tell a user everything wrong with their options at once rather than make them fix one issue at a time, and that seems to have been the original intent.

Added `logger: false` since the aim at lint-time seems to be that users receive no feedback about invalid schemas, and issues in schemas are just silently ignored - this ensures ajv won't ever write anything to the console.

Added `addSchemas: false`:

By default, ajv will add any compiled schemas to the ajv instance (the compilation cache is different and separate). This is usually to allow schemas with an `$id` to be referenced by other schemas after they've been added.

Technically, this allows rules to attempt to reference each other's schemas if they're clever with `$id` and `$ref`. However, because rules have no control over the order in which rules and their schemas might be loaded, this is inherently unreliable. In principle, all rule schemas should be completely independent.

I'm proposing that we should just outright eliminate this corner-case so that rule developers can't trick themselves into thinking this is a viable thing to do because it "works on their machine" when conditions/configuration are aligned just right.

This would technically be a breaking change, but I can't imagine that any sane rule developer would ever have thought this was a good idea to implement.

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks for putting some thought into this. We definitely can't just merge this as-is because we don't know what effects this would have on the ecosystem. In general, we require an RFC for any breaking change so that we can properly evaluate its effect and get a better understanding of the pros vs. cons. I'll flip this to be a PR draft for now. If you'd like to submit an RFC, we can then evaluate this further.

@bmish I'd be interested in your perspective here.

**Comment by matwilko** [comment]
Sure, absolutely wasn't trying to go round process or anything here 😄

Is it just the `addSchemas` change that requires a wider discussion? Totally understand the reason, but thought it might be a rare enough corner case that it might go through without much fanfare :)

If I take off the `addSchemas` commit, would the other two non-breaking changes be acceptable by themselves without larger discussion?

**Comment by nzakas** [comment]
This is actually an area of the project I'm not super familiar with, so I'm not sure of the effect these changes will have. Going through the RFC process makes the change visible to a larger group of people so we can get the feedback of those who will be affected by the change.

Because the ecosystem of ESLint rules is so large, anything that affects how rules are executed requires an extra degree of care.

**Comment by matwilko** [comment]
No worries, I seem to have a growing list of potential changes in the options schema area to try to tighten things up/improve behaviour, so I'll have a look at rolling them all into a single RFC some time this week.

Apologies if I keep throwing things at the project in the wrong way, it can be hard to gauge what is "big" enough to need to go through one path or another 😄

**Comment by nzakas** [comment]
No worries at all, we appreciate the enthusiasm and the ideas. Check out the docs on the RFCs repo, which provides more info on what types of changes we'd like to see RFCs for:
https://github.com/eslint/rfcs

**Comment by bmish** [comment]
`allErrors: true`:
1. I agree it's helpful to see all errors instead of just the first one.
2. Changing the output to include all errors shouldn't be a breaking change today as it just changes the console output.
3. But it seems that it would become a breaking change after the [ability to test invalid schemas](https://github.com/eslint/eslint/pull/16823) is merged. If we want to adopt `allErrors: true`, perhaps we should consider doing so before my PR is merged, as it would be much harder to do so after. Either way, I will update my PR to ensure this scenario (multiple schema errors) is tested.

`logger: false`:
1. When are warnings logged today? As in, what would the before and after difference be?
2. While we of course don't want to log anything about schema validation during production, logging info during tests seems helpful.

`addSchemas: false`:
1. It sounds like an extreme edge case that one rule could be relying on another, given that ESLint doesn't make any promises about what order rules are run in.
2. Since anyone using this behavior is relying on the order that ESLint rules are run, and ESLint doesn't provide any guarantees about that, perhaps breaking this behavior should not be considered a breaking change?
3. Could we search ESLint plugins on GitHub to see if anyone is relying on this behavior? I previously wrote a [script](https://github.com/bmish/eslint-ecosystem-analyzer) that downloads the top 1,000 ESLint plugins for analysis and it could be adapted to help check for this behavior.

**Comment by bmish** [comment]
To be clear, I'm in favor of all the changes, just wanted to call out any potential considerations or issues we'll have to watch out for.

**Comment by mdjermanovic** [comment]
> Added `allErrors: true` because [`RuleValidator.validate`](https://github.com/eslint/eslint/blob/b79b6fb64473969b426d086b484d2e29594a5e9a/lib/config/rule-validator.js#L147) seems to have been written to handle multiple validation errors, but by default, `ajv` will only return the _first_ validation error.

There are already cases where `ajv` returns multiple validation errors, even without `allErrors: true`. For example, with this configuration for the `no-extra-parens` rule:

```js
{
    rules: {
        "no-extra-parens": ["error", "all", { foo: 5 }]
    }
}
```

`validateRule.errors` has 3 items, and the output is:

```
Error: Key "rules": Key "no-extra-parens":      Value ["all",{"foo":5}] should NOT have more than 1 items.
        Value {"foo":5} should NOT have additional properties.
        Value ["all",{"foo":5}] should match some schema in anyOf.
```

**Pull request closed without merging**
