### PR TITLE
Update: Added "allowAfterSuper" property to rule "no-underscore-dangle" (fixes #6355)

### LINKED ISSUE #6355: Update: Added "allowAfterSuper" property to rule "no-underscore-dangle"
This is to accompany PR #6354.

Request to add a new property for the no-underscore-dangle rule which can allow use of underscores with the ES2015 super keyword.

### PR DESCRIPTION
**Pull request by peteward44**
Update: Same as the "allowAfterThis" option, but for the ES2015 'super' keyword. fixes #6355

### CODE REVIEW

**Comment by platinumazure** [comment]
Adding "do not merge" just because the issue hasn't been accepted by the team yet. I am hoping this will be a noncontroversial enhancement and that this can get in pretty soon :smile:

**Comment by nzakas** [comment]
@peteward44 can you rebase this PR?

**Comment by nzakas** [comment]
@peteward44 oops, it looks like the rebase got mixed with a merge, and this PR now has too many changes. We have instructions for rebasing here: http://eslint.org/docs/developer-guide/contributing/pull-requests#rebasing

**Comment by peteward44** [comment]
Sorry guys, i've made a mess of this. I'm going to create a new PR for this.

**Pull request closed without merging**
