### PR TITLE
 Fix: Indentation rules incorrectly flag properly indented code

### LINKED ISSUE #5384: Indentation rules incorrectly flag properly indented code
Hi there,
This seems to be related to #5295 
Using the following rule config:
```
indent: [2, "tab"]
```
The following lines will throw errors:
```js
instance.layoutSerializer = new LayoutSerializer(
	{
		builder: instance.get('formBuilder')
	}
);
```

However, with the same config, the following will **not** throw any errors:
```js
instance.layoutSerializer = LayoutSerializer(
	{
		builder: instance.get('formBuilder')
	}
);
```
The reason for this is because on [this line](https://github.com/eslint/eslint/commit/afb6708eff08b739b7e57b7d807cf8ef9a790b14#diff-f7ae198ea24182d178b8f3376e61b6edR434), it's not checking for `NewExpression` which is what the first block of code will register as.

### PR DESCRIPTION
**Pull request by natecavanaugh**
Fixes #5384

### CODE REVIEW

**Comment by BYK** [comment]
LGTM

**Comment by BYK** [comment]
Build failed because of the old commit, new one should fix it.

**Comment by BYK** [comment]
Thanks for the FTL patch @natecavanaugh! :)

**Comment by natecavanaugh** [comment]
No problem :)

**Comment by natecavanaugh** [comment]
Ah wait, sorry, missed the part about the new commit. Do you want me to send a new pull or just force push over this one?

**Comment by BYK** [comment]
@natecavanaugh you still need to make the first line shorter (max 72 chars): `First line of commit message must not exceed 72 characters`

**Comment by ilyavolodin** [comment]
@natecavanaugh No need for new pull request, you can modify and force push.

**Comment by mysticatea** [comment]
Looks good to me!

**Pull request merged**
