### PR TITLE
Chore: Add .pre-commit-hooks.yaml file

### PR DESCRIPTION
**Pull request by mondeja**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

Add `.pre-commit-hooks.yaml` file to make work Eslint hooks whit [pre-commit framework](https://pre-commit.com).

This allows users to configure a file in their project named `.pre-commit-config.yaml` with a content like, for example, this:

```yaml
repos:
  - repo: https://github.com/eslint/eslint
    rev: master
    hooks:
      - id: eslint
        name: eslint-webpack-config
        files: webpack
        args: ['-c', 'webpack/.eslintrc.json']
      - id: eslint
        name: eslint-frontend
        files: static/src/js
        args: ['-c', 'static/src/js/.eslintrc.json']
```

...and every commit that users would attempt in their project will run two hooks to check Javascript files against Eslint. If any of the hooks fails, the commit will be aborted. The interesting part is that only files with changes will be linted.

See [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli/blob/master/.pre-commit-hooks.yaml), [flake8](https://gitlab.com/pycqa/flake8/-/blob/master/.pre-commit-hooks.yaml) or [yamllint](https://github.com/adrienverge/yamllint/blob/master/.pre-commit-hooks.yaml) as other examples of linters that have been added the file without efforts. 

#### Is there anything you'd like reviewers to focus on?
It's something that doesn't need maintainment, so you wouldn't need focus on.

### CODE REVIEW

**Comment by kaicataldo** [comment]
I'm not against adding this if it doesn't require any additional maintenance, though it feels like an inverse of responsibilities to me to put the onus on the other projects to include this definition rather than the project that will be consuming it.

**Comment by mondeja** [comment]
I understand you, close the pull if you don't feel comfortable with the file. It's only useful for the programmers that want to use the master of eslint in their hooks, but we can always settle for [the mirror that uses pre-commit](https://github.com/pre-commit/mirrors-eslint).

**Review by nzakas — APPROVED** [review]
Seems like a small enough change without any overhead, so okay by me.

**Comment by kaicataldo** [comment]
Do we need to include this file in the published package on npm, or does this check the repo somehow?

**Comment by mondeja** [comment]
Only checks the repo, `pre-commit` clones repos to prepare environments for hooks.

**Review by kaicataldo — APPROVED** [review]

**Review by jdufresne — APPROVED** [review]

**Review by nzakas — APPROVED** [review]

**Pull request merged**
