### PR TITLE
Docs: Note about fix rules (fixes #4774)

### LINKED ISSUE #4774: Note about fix rules in docs
Add note about fix rules to docs

Related #4766 #4767 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29310164-note-about-fix-rules-in-docs?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by SpainTrain**
[Review on Reviewable](https://reviewable.io/reviews/eslint/eslint/4775)

### CODE REVIEW

**Comment by nzakas** [comment]
I'm not sure this is the correct place for such a notice. It seems like a better location would be in the contributor guidelines somewhere, as this doc is just generally about how how you write rules.

**Comment by SpainTrain** [comment]
:question: 

There is a section in this doc regarding acceptance criteria, which is specific to contributing to core rules - https://github.com/eslint/eslint/blob/master/docs/developer-guide/working-with-rules.md#rule-acceptance-criteria

Additionally, there are notes about contributing to core rules scattered about the doc:

- "Each rule must have a set of unit tests submitted with it to be accepted."
- "Provide as many unit tests as possible. Your pull request will never be turned down for having too many tests submitted with it!"

**Comment by nzakas** [comment]
That's a mistake, we moved that information to here: http://eslint.org/docs/developer-guide/contributing/new-rules

**Comment by SpainTrain** [comment]
:+1: How about this as an update to my PR:

* Remove those bits I mentioned that are about core contributions
* Add link to document you linked
* Add note about fixes to the document you linked

**Comment by nzakas** [comment]
:+1:

**Comment by gyandeeps** [comment]
@nzakas r we good to go here?

**Comment by nzakas** [comment]
The PR hasn't been updated

**Comment by gyandeeps** [comment]
Oh yeah. Sorry abt that.

**Comment by nzakas** [comment]
@SpainTrain are you still working on this?

**Comment by SpainTrain** [comment]
Sorry, haven't had slack time to update this.  Feel free to close for now and I can ping if/when it's updated.

**Comment by nzakas** [comment]
Ok, thanks!

**Pull request closed without merging**
