### PR TITLE
Breaking: space-before-function-parentheses replaces space-after-function-name and checkFunctionKeyword (fixes #1618)

### LINKED ISSUE #1618: missing rule : space before the round brace for functions
Hi. I've tried to review each and every rule of JSHint, JSCS and ESLint to see if I could entirely "get rid of" the first two in favour of the latter one. As suggested by the owner of the @geteslint twitter account, I'm reporting the JSCS rules I've found actually not covered by ESLint. My apologies if it's a duplicate.

 - "disallowSpacesInAnonymousFunctionExpression"
 - "requireSpacesInAnonymousFunctionExpression"
 - "disallowSpacesInNamedFunctionExpression"
 - "requireSpacesInNamedFunctionExpression"
 - "disallowSpacesInNamedFunctionExpression"
 - "requireSpacesInNamedFunctionExpression"

The space before the opening curly brace is covered by "space-before-block".
What is not covered is the space before the round brace, i.e being able to say this is invalid

```js
var Foobar = {
    foo: function (){}
}
array.map(function () {})
var x = function () {}
var x = function a (){}
function a () {}
```

only because, say, the rule would require a space between the function name (or `function` if it is anonymous) and the opening round brace. Or the contrary.
And perhaps being able to differentiate between named and anonymous functions.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7465888-missing-rule-space-before-the-round-brace-for-functions?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lo1tuma**

### CODE REVIEW

**Comment by nzakas** [comment]
Looks good, just want to hold off merging in case we have one more patch release.

**Comment by nzakas** [comment]
Okay, no more patch releases, this is good to go.

**Comment by Delapouite** [comment]
Hi. All other rules are named with "parens", is there any reason for having this one called space-before-function-parentheses and not space-before-function-parens ?

**Comment by nzakas** [comment]
We just missed it.

**Pull request merged**
