### PR TITLE
Update: Fix incorrect default value for position

### PR DESCRIPTION
**Pull request by revolter**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Tell us about your environment**

* **ESLint Version:** 5.2.0
* **Node Version:** v8.9.4
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```js
{
    "env": {
        "browser": true,
        "es6": true,
        "greasemonkey": true
    },
    "extends": "eslint:recommended",
    "globals": {
        "player": false,
        "PLAYER_STATE": false
    },
    "rules": {
        "line-comment-position": [
            "error", {
                "ignorePattern": "fall\\-through"
            }
        ]
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
var playerState = player.getPlayerState();

// This should not trigger an error
switch (playerState) {
    case PLAYER_STATE.Unstarted: // fall-through
    case PLAYER_STATE.Ended: // fall-through
    case PLAYER_STATE.Paused: // fall-through
    case PLAYER_STATE.Buffering: // fall-through
    case PLAYER_STATE.VideoCued: {
        player.playVideo();

        break;
    }
}
```

**What did you expect to happen?**

Not throw an error.

**What actually happened? Please include the actual, raw output from ESLint.**

```
.../scripts/Main/main.js
  3:1  error  Expected comment to be beside code  line-comment-position

✖ 1 problem (1 error, 0 warnings)
```

**What changes did you make? (Give an overview)**

I ensured that the current documentation is correct regarding the `line-comment-position` rule. It states that the `above` `position` is the default value, but specifying the `ignorePattern` (or `applyDefaultIgnorePatterns` for that matter) caused the `position` to default to `beside` instead. The change is merely copied and adapted from 3 lines above it.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by revolter** [comment]
What is invalid about the commit message?

**Comment by not-an-aardvark** [comment]
I think the problem is that it's too long -- the first line needs to be at most 72 characters.

**Comment by Aladdin-ADD** [comment]
`[wip]` is not allowed. https://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changes

no worries, we can correct it before merging.

**Comment by revolter** [comment]
`[WIP]` is only in the PR's title on GitHub. I'll shorten the commit message and add a test soon.

**Comment by revolter** [comment]
Done 😃

**Comment by revolter** [comment]
_The current workaround is to explicitly setting `above` for the `position` option in the options object._

**Comment by revolter** [comment]
@platinumazure, Done 😃

**Comment by platinumazure** [comment]
Merged, thanks for contributing!

**Pull request merged**
