### PR TITLE
Fix: require-atomic-updates false positive (fixes #11194, fixes #11687)

### LINKED ISSUE #11194: require-atomic-updates false positive
**Tell us about your environment**

* **ESLint Version:** 5.10.0
* **Node Version:** 11.1.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**

- default

**Please show your full configuration:**
**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Online demo: https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgcmVxdWlyZS1hdG9taWMtdXBkYXRlczogZXJyb3IgKi9cclxuXHJcbmFzeW5jIGZ1bmN0aW9uIGYoKSB7XHJcbiAgICBsZXQgcmVjb3Jkc1xyXG4gICAgXHJcbiAgICByZWNvcmRzID0gYXdhaXQgZGIucmVjb3Jkcy5nZXQoKVxyXG5cclxuICAgIGcoKCkgPT4geyByZWNvcmRzIH0pXHJcbn1cclxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo4LCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19

```js
/*eslint require-atomic-updates: error */

async function f() {
    let records
    
    records = await db.records.get() //→ Possible race condition: `records` might be reassigned based on an outdated value of `records`. (require-atomic-updates)

    g(() => { records })
}
```

**What did you expect to happen?**

No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

`require-atomic-updates` warns the line `records = await db.records.get()`.

If I change the `db.records.get` to `db.recordsDash.get` or something like, the warning is gone, so I guess that the rule uses the property name as a variable name.

**Are you willing to submit a pull request to fix this bug?**

I don't have enough time to investigate this for now. I'm sorry.

### LINKED ISSUE #11687: require-atomic-updates false positive
May be related to #11194, but that looked more like naming conflicts.

**Tell us about your environment**

* **ESLint Version:** 5.16.0
* **Node Version:** 11.13.0
* **npm Version:** 6.7.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    "parserOptions": {
        "ecmaVersion": 2017
    },
    "rules": {
        "require-atomic-updates": "error",
    },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgcmVxdWlyZS1hdG9taWMtdXBkYXRlczogZXJyb3IgKi9cclxuXHJcbmFzeW5jIGZ1bmN0aW9uIGYoKSB7XHJcbiAgICB0cnkge1xyXG4gICAgICAgIHRoaXMuZm9vID0gZG9Tb21ldGhpbmcoKTtcclxuXHR9ICBjYXRjaCAoZSkge1xyXG4gICAgICAgIHRoaXMuZm9vID0gbnVsbDtcclxuICAgICAgICBhd2FpdCBkb0Vsc2UoKTtcclxuICAgIH1cclxufVxyXG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjgsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=

```js
async function f() {
  try {
    this.foo = doSomething();
  }  catch (e) {
    this.foo = null;
    await doElse();
  }
}
```

**What did you expect to happen?**
No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

```
foo.js
  5:5  error  Possible race condition: `this.foo` might be reassigned based on an outdated value of `this.foo`  require-atomic-updates

✖ 1 problem (1 error, 0 warnings)
```

The `doSomething` method is synchronous so it cannot violate this rule about using "await".  I'm thinking it is confused about reassigning in the "catch" block, but for a synchronous method, that should be allowed and not violate this rule.

**Are you willing to submit a pull request to fix this bug?**
No.

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fixes #11194, fixes #11687

**What changes did you make? (Give an overview)**

First of all, I'm sorry that this change is huge.

I have improved the rule's logic with using information that `eslint-scope` made. The new logic is the following steps (roughly):

1. Create `Identifier` → `Reference` map when ESLint entered each async/generator function.
1. In an async/generator function,
    1. initialize each code path segment having two information: outdated read variables and fresh read variables. Segments inherit that information from the previous segments.
    1. On `Identifier` nodes, find the reference of the node by the map (of step 1). Then:
        - If `reference.isRead()` is true, add it to the fresh read variable list of the current code path segment.
        - If `reference.isWrite()` is true, store the `reference.writeExpr` (this is `AssignmentExpression#right` if it's assignment) to verify it later.
    1. On `AwaitExpression`/`YieldExpression` nodes (exit), move the fresh read variables to the outdated read variables, on the current code path segment.
    1. On expression nodes (exit), if it's a stored `reference.writeExpr`, do the verification. If the variable that the reference refers is outdated on the current code path, report it.

Therefore, this logic does the verification on the main traversal instead of extra traversal.

The important part for #11194 bug fix is the step 1. The rule ignores `Identifier` node if it's not a reference.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
@mysticatea Friendly ping

**Comment by platinumazure** [comment]
@mysticatea Friendly ping: Are you still working on this?

**Comment by mysticatea** [comment]
I apologize that I had lost track of this.

**Comment by mysticatea** [comment]
I agreed that the code path analysis needs some changes...

**Pull request merged**
