### PR TITLE
Chore: add integration tests for cache files (refs #7748)

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Other, please explain:

**What changes did you make? (Give an overview)**

This adds some integration tests for ESLint's behavior relating to cache files.

Two of the tests are currently failing. This should get fixed when a new version of `flat-cache` is published. (See the discussion in https://github.com/eslint/eslint/issues/7748.)

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
@platinumazure I rebased onto master. The changes are the same as before, but the tests should now pass because an upgrade to `flat-cache` has been released.

**Comment by not-an-aardvark** [comment]
I would agree, but we don't actually depend on `flat-cache` at all in our `package.json`. It's a subdependency of `file-entry-cache`, so I think we would need to get that package to do a release first if we wanted to pin the version.

**Comment by platinumazure** [comment]
Ah. Well, `file-entry-cache` is maintained by the same person as `flat-cache`, for what that's worth.

**Comment by platinumazure** [comment]
I did run Travis' PR job before merging this, so hopefully I haven't just broken master by merging this in. :smile:

**Pull request merged**
